quest = "The Giant Dwarf"
step_count = 7

[[steps]]
index = 0
name = "Property damage"
links = ["Relleka", "fairy ring", "Trollweiss Mountain", "Dwarven Boatman", "Dwarven Ferryman", "Keldagrim", "King Alvis", "Commander Veldaban", "Keldagrim minecart system", "Blasidar the sculptor", "The Giant Dwarf", "Thurgo"]
text = """
Enter the Keldagrim dungeon entrance, east of [[Relleka]] and just south-west of [[fairy ring]] {{Fairycode|dks}}. After entering, continue through another cave entrance directly to the east by the statues - do '''not''' head south, as that takes you to the base of [[Trollweiss Mountain]].

Talk to the [[Dwarven Boatman]] ('''not''' the [[Dwarven Ferryman]]), who will offer you a free ride to [[Keldagrim]]. A cutscene will play, during which the boat will crash into the statue of [[King Alvis]]. After being arrested and taken to the Black Guard headquarters, [[Commander Veldaban]] will tell the player that the statue was long overdue for replacement anyway. He wants you to help out the local sculptor to rebuild the statue.

:'''''You can now use the [[Keldagrim minecart system]] throughout Gielinor.'''''

Talk to [[Blasidar the sculptor]]. He lives in the eastern side of Keldagrim, across the bridge, south of the kebab shop. He will make you the statue if you can get him clothes, an axe and boots "fit for a king". It is advisable to complete the [[The Giant Dwarf#An axe fit for a king|axe part of the quest]] last, as [[Thurgo]] will teleport the player directly to Blasidar.
"""

[[steps]]
index = 1
name = "Clothes fit for a king"
links = ["coins", "coal", "logs", "tinderbox", "general store", "Vermundi", "librarian", "Keldagrim Library", "Keldagrim", "book on costumes", "exquisite clothes"]
text = """
{{Needed|200 [[coins]], [[coal]], [[logs]] and a [[tinderbox]]|skills={{SCP|Firemaking|16}} {{Boostable|yes}} to light the spinning machine}}

:'''Note:''' A tinderbox can be purchased from the [[general store]] on the west side of town, and coal can be mined on the east side of town.''
{{Map|name=Vermundi|2887,10188|mapID=10|r=2|mtype=square|align=left|height=200|width=200|caption=Vermundi's location}}
{{Map|name=Librarian|2862,10225|mapID=10|r=5|mtype=square|align=right|height=200|width=200|caption=The librarian's location}}
Talk to [[Vermundi]], the silk trader in the corner of the east marketplace, and ask her about making the king's clothes. She can, but first she needs a picture of the clothes. Talk to the dwarf [[librarian]] in the [[Keldagrim Library|library]] across the [[Keldagrim]] bridge. He tells you to search the library for a book about dwarven clothes. Climb any bookcase with a ladder in front of it to find the [[book on costumes]].

:'''Note:''' If you weigh 30&nbsp;kg or more, you will be unable to climb the ladder. You can simply drop some items and then pick them back up.''

Give [[Vermundi]] the book. You now need to fix her steam-powered spinning machine. Use the coal on her machine with [[logs]] in your inventory, then use your tinderbox on it ({{SCP|Firemaking|16}}). If you fail to light it, just try again. Once the machine is lit, talk to her again and pay her 200 [[coins]] to get the [[exquisite clothes]].
{{Clear}}
"""

[[steps]]
index = 2
name = "Boots fit for a king"
links = ["Telekinetic Grab", "Air rune", "law rune", "anvil", "Keldagrim", "Saro", "Dromund", "left boot", "right boot", "Dromund's cat", "Exquisite boots"]
text = """
{{Needed|Means to cast [[Telekinetic Grab]] ([[Air rune|air]] and [[law rune]]).|skills={{SCP|Thieving|14}} {{Boostable|yes}} to steal the left boot, {{SCP|Magic|33}}  {{Boostable|yes}} to cast Telekinetic Grab}}

Go to the south-western [[anvil]] in [[Keldagrim]] (south of the Black Guards' HQ) and ask [[Saro]] about the boots. He sold them to [[Dromund]], another dwarf in Keldagrim. Speak to Dromund in his house just north of the bank, who will refuse to sell you the boots.

When Dromund is not looking towards you, steal the [[left boot]] from the table next to the door ({{SCP|Thieving|14|link=yes}}). The [[right boot]] is on another table, but you cannot steal it from inside the house because of his [[Dromund's cat|cat]] watching over it. Stand outside by the window with the right boot, then use [[Telekinetic Grab]] on it ({{SCP|Magic|33}}) when Dromund is not looking. Once both boots are obtained, they turn into [[Exquisite boots]].
"""

[[steps]]
index = 3
name = "An axe fit for a king"
links = ["iron bar", "sapphire", "redberry pie", "Thurgo", "The Knight's Sword", "Prying Times", "Santiri", "Quality Weapons Shop", "Keldagrim", "Dwarven battleaxe", "Smithing", "Imcando dwarf", "Reldo", "Varrock Palace", "Mudskipper Point", "Rimmington", "Port Sarim", "Fairy rings", "Blasidar the sculptor"]
text = """
{{Needed|An [[iron bar]], 3 [[sapphire]]s, and a [[redberry pie]] (if you have not given [[Thurgo]] a free redberry pie in the past, with the required redberry pies for [[The Knight's Sword]] and [[Prying Times]] not counting).|skills={{SCP|Crafting|12}} {{Boostable|yes}} to attach sapphires to the hilt}}
{{Map|name=Santiri|2828,10231|height=200|width=200|rectX=11|rectY=9|zoom=2|mapID=10|mtype=rectangle|align=left|caption=Santiri's location}}
{{Map|name=Thurgo|3001,3144|height=200|width=250|r=2|mtype=square|align=right|caption=Thurgo's location}}
Talk to [[Santiri]], the tradesman of the [[Quality Weapons Shop|sword shop]] in north-west [[Keldagrim]]. He talks about how his family came to possess the [[Dwarven battleaxe]], mentioning it has been damaged and that the [[sapphire]]s on the hilt had either been stolen or washed away. During the dialogue where you offer to repair the axe, Santiri may note your mastery of [[Smithing]] but exclaims that even you aren't skilled enough.

After he gives you the axe, use three sapphires on it to rebuild the hilt ({{SCP|Crafting|12}}). Talk to Santiri again, who says that only an [[Imcando dwarf]] could fully repair it.

If you have completed [[The Knight's Sword]], the player will remark that they know an Imcando dwarf. If you have not completed it, you will need to first talk to [[Reldo]] in the [[Varrock Palace]] library to discover [[Thurgo]]'s location; this is necessary to progress.

Thurgo resides in the single house at [[Mudskipper Point]], south-east of [[Rimmington]] and south of [[Port Sarim]]. The fastest way to get there is to travel using [[Fairy rings]] to {{Fairycode|AIQ}}. Go to him with an [[iron bar]], and ask him to repair the axe. After that, if you have not yet given him a [[redberry pie]] for '''free''' previously, you must give him one now. He will then repair the axe.

:'''''Note:''' Thurgo will supply you with another axe if lost, but it will require three sapphires to be added again.''

When Thurgo is done, you have the option to return immediately to Keldagrim. This will place you back in [[Blasidar the sculptor]]'s house.
"""

[[steps]]
index = 4
name = "The Head"
links = ["Riki the sculptor's model", "Blasidar the sculptor"]
text = """
Give [[Riki the sculptor's model|Riki]] the axe, clothes and boots by speaking to him with the items in your inventory. Talk to [[Blasidar the sculptor|Blasidar]], who explains that the Consortium wants the head of the statue modelled after one of its directors, but has not agreed which one. He asks you to go and help them make a decision. You will see a short cutscene of the incomplete statue.

:'''Make sure to complete this step before starting the tasks below, or the tasks for the director will go on indefinitely!'''
"""

[[steps]]
index = 5
name = "Joining the consortium"
links = ["Consortium", "The Green Gemstone", "The White Chisel", "The Silver Cog", "The Brown Engine", "The Yellow Fortune", "The Blue Opal", "The Purple Pewter", "The Red Axe", "Purple Pewter Secretary", "H.A.M. robes", "Giant Dwarf (statue)", "Ore seller.", "clay", "copper ore", "tin ore", "iron ore", "silver ore", "gold ore", "mithril ore", "coal", "bronze bars", "iron bars", "steel bars", "silver bars", "gold bars", "mithril bars", "Blasidar the sculptor"]
text = """
There are eight mining companies in the [[Consortium]], which are located upstairs in either the east or west marketplace:
*[[The Green Gemstone]]
*[[The White Chisel]]
*[[The Silver Cog]]
*[[The Brown Engine]]
*[[The Yellow Fortune]]
*[[The Blue Opal]]
*[[The Purple Pewter]]
*[[The Red Axe]] ''(you cannot join this company)''

You will need to pick a company to join. Joining [[The Purple Pewter]] provides a headstart of 20 points in the scoring system by speaking to the [[Purple Pewter Secretary]] whilst wearing three or more pieces of the [[H.A.M. robes]] set. Otherwise, your choice will only impact the [[Giant Dwarf (statue)|final model of the statue]] built at the end of the quest.

The companies on the west side of the building have faster bank access, whilst the east side is closer to the [[Ore seller.|ore seller]] and Grand Exchange (through minecart).

To begin, talk to the secretary of the company that you want to work for. You will be given several errands to collect 1-5 of a certain ''un-noted'' material within a time limit. The possible items are [[clay]], [[copper ore]], [[tin ore]], [[iron ore]], [[silver ore]], [[gold ore]], [[mithril ore]], and [[coal]]. With the exception of clay, all materials can be mined or bought nearby, if they are not already in your bank or inventory. You can say "no," then talk to the secretary again to receive a different task.

A hidden scoring system determines your progress with a company; each ore delivery completed gives 20 points, while failing or cancelling a task subtracts 2 points. '''Progress is not shared between companies, so only perform tasks for one of them.'''

:'''Note:''' If you fail a task and are unable to obtain a new one, logging out and logging back in should fix the issue.

Once you reach 75 points, you will be told that the director of the company wants to speak with you. At this point you may start doing errands for the director, who will request different items from you. These items include [[bronze bars]], [[iron bars]], [[steel bars]], [[silver bars]], [[gold bars]], and [[mithril bars]], and give 12 points.

When you have have obtained 100 points for a company, you can ask the director to officially join them, and they will agree and accept you as a "trusted associate". Next, tell them that [[Blasidar the sculptor|Blasidar]] sent you, and that you will vouch for them at the next Consortium meeting.
"""

[[steps]]
index = 6
name = "Art by committee"
links = ["Commander Veldaban", "meeting notes"]
text = """
Return to [[Commander Veldaban]] (west of the bank) and tell him you will go to the meeting. You will see a cutscene of about 4 minutes. You can also skip the cutscene by refusing to go to the meeting; you can read a summary of it in the [[meeting notes]], received after completing the quest.

<gallery captionalign="center" widths="200">
File:The Giant Dwarf statue.png|The completed statue representing the director of the Green Gemstone or the Silver Cog.
File:Blue opal dwarf.png|The completed statue representing the director of the Blue Opal.
File:The Giant Dwarf Brown Engine Director Statue.png|The completed statue representing the director of the Brown Engine.
File:Yellow Fortune.png|The completed statue representing the director of the Yellow Fortune.
File:Consortium Meeting.png|Hreidmar storms out of the Consortium meeting.
</gallery>

'''Congratulations, quest complete!'''
"""
