quest = "The Slug Menace"
step_count = 6

[[steps]]
index = 0
name = "The mission"
links = ["Commorb", "Jeb", "Holgart", "Col. O'Niall", "Ezekial Lovecraft", "Mayor Hobb", "Brother Maledict", "Sir Tiffy Cashien", "Falador Park", "Witchaven", "Col. Jake O'Niall", "Commorb v2"]
text = """
[[File:Sir Tiffy Cashien chathead.png|left]]
{{Needed|[[Commorb]]|recommended= Ardougne teleport}}
{{Map|mtype=pin|align=right|caption=All NPC locations.
|2723,3303,title:[[Jeb]] and [[Holgart]],desc:
|2739,3311,title:[[Col. O'Niall]],desc:
|2734,3292,title:[[Ezekial Lovecraft]],desc:
|2709,3291,title:[[Mayor Hobb]],desc:
|2723,3283,title:[[Brother Maledict]],desc:
|2696,3283,title:Temple entrance,desc:
}}

Talk with [[Sir Tiffy Cashien]] in [[Falador Park]], who will give you a mission to investigate the city of [[Witchaven]], which has had some rather strange things going on recently. He'll tell you to check in with their local agent in Witchaven, [[Col. Jake O'Niall]]. Sir Tiffy Cashien will then upgrade your [[Commorb]] to [[Commorb v2]], which will start the quest. Use the ''contact'' option on Commorb v2 and head to Witchaven.
"""

[[steps]]
index = 1
name = "Investigating Witchaven"
links = ["O'Niall", "Mayor Eustace Hobb", "Witchaven Dungeon", "Witchaven", "Ardougne", "Mayor Hobb", "Brother Maledict", "Holgart", "Savant", "Commorb v2", "Jeb"]
text = """
[[File:Col. O'Niall chathead.png|left]]
[[O'Niall]] sits on a rocking chair on the pier at the north-east corner of town. Talk to him, and he'll tell you that some of the people have been acting strangely recently, especially [[Mayor Eustace Hobb]]. Recently, he started looking rather sickly and working feverishly to restore the ancient, ruined [[Witchaven Dungeon|shrine]] just west of town (between [[Witchaven]] and [[Ardougne]]). Before leaving, ask O'Niall about who the important people in town are, which are [[Mayor Hobb]], [[Brother Maledict]], and [[Holgart]]. Speak to each of them in any order.

[[Mayor Hobb]]'s house is the one at the north-west side of [[Witchaven]]. Talk to him, and ask him about Witchaven or the shrine. When you are done speaking to him, don't go anywhere as [[Savant]] will stop you. She'll ask you to scan the mayor, so ''scan'' with the [[Commorb v2]].

'''Note: You need to finish the dialogue with Mayor Hobb with "Nothing at the moment, thanks" after asking the questions to make Savant ask you to scan him. It takes 3–4 seconds before she contacts you after ending the conversation.'''

[[Brother Maledict]] will mention that he's a bit worried about some of his congregation, who have begun to act a little bit strangely lately. You can finish the dialogue without asking more questions. Walk a little bit north and talk to [[Holgart]], who'll tell you that the mayor recently took his boat and gave it to another man named [[Jeb]], standing near by.
"""

[[steps]]
index = 2
name = "The shrine"
links = ["O'Niall", "Witchaven Dungeon", "Mayor Hobb", "minimap", "giant lobster", "Agility", "shortcut", "Imposing Doors", "Savant", "Commorb v2", "Jorral", "dead sea slug", "outpost", "West Ardougne"]
text = """
[[File:Savant chathead.png|left|90px]]
[[File:Slug menace wall.png|right|thumb|200px|The false wall.]]
Report back to [[O'Niall]] to tell him what you have found out so far. He'll suggest you go look into the [[Witchaven Dungeon|shrine]] that the [[Mayor Hobb|mayor]] is so interested in.

[[File:Witchaven dungeon map.png|right|thumb|The dungeon.|393x393px]]
Walk a little ways west of town, and climb down the stairs to get into the shrine. Once you're inside, look at the [[minimap]]. You can see a red portion of wall on the east side of the room indicating where there's a false wall that can be pushed open, and you'll find a new area. Inside are some aggressive level 45 [[giant lobster]]s in a winding tunnel. Walk through it, or take the [[Agility]] [[shortcut]] to get to where there's an [[Imposing Doors|imposing door]] blocking your way. '''Don't try to open it or you will take 5 damage'''. Walk next to it, and [[Savant]] will contact the [[Commorb v2]] to tell you about the strange markings on the door. ''Scan'' the Commorb for her. She can't read them and suggests you take them to [[Jorral]] to try to find out what they mean. '''Pick up the [[dead sea slug]] off the floor''' before leaving and head to Jorral's house, which is located at an [[outpost]] just north-west of [[West Ardougne]].

'''Note:''' Check your quest log whether it has been updated and requires you to go to Jorral; otherwise, open the doors (taking 5 damage) and a replay of your communication with Savant will be played. You can now proceed to Jorral. Make sure you have an extra inventory spot available for the door transcription.
"""

[[steps]]
index = 3
name = "The pages"
links = ["Swamp paste", "dead sea slug", "Jorral", "Outpost", "Necklace of passage", "Savant", "Witchaven", "O'Niall", "Brother Maledict", "Mayor Hobb", "Page 1", "study desk (The Slug Menace)", "Page 2", "Ezekial Lovecraft", "Fishing", "Page 3", "swamp paste", "Fragment 1", "Fishing Platform", "Jeb", "Bailey", "sea slug glue"]
text = """
{{Needed|[[Swamp paste]], [[dead sea slug]] and five open inventory spaces}}
{{Map|2434,3350|2439,3350|2439,3346|2438,3346|2438,3343|2434,3343|mtype=polygon|caption=Jorral is found in the outpost due north of West Ardougne.|align=left|width=200|height=200}}

Make sure you have a free inventory slot, as you will '''not''' get the notes if your inventory is full. Now, go talk to [[Jorral]], who is at his [[Outpost]] (you can use the [[Necklace of passage|necklace of passage]] to teleport here, use a spirit tree to get to the Gnome Stronghold and head south). After some coaching from [[Savant]] on what to say, Jorral will translate the message for you. When you leave the building, Savant will contact you again to let you know just what this new revelation entails.

Head back to [[Witchaven]], and report in with [[O'Niall]]. He'll suggest you go talk to the [[Brother Maledict|priest]] and see if he knows anything about how to open the door. As you approach the church, you'll see a brief cutscene of the [[Mayor Hobb|mayor]] leaving the church. When you go in, the priest will be looking rather ill and acting strangely. Ask him about the door, and he'll tell you that he has a book that might be of use, but the three most important pages are missing.

For the [[Page 1|first one]], go to the mayor's house and look in his [[study desk (The Slug Menace)|desk]]. The [[Page 2|second one]] will be given to you by [[Ezekial Lovecraft]], the owner of the [[Fishing]] store, when you talk to him. For the [[Page 3|last one]], talk to O'Niall again. He too has taken the same look as the rest of the villagers. He'll give you the last page, but unfortunately, it has been ripped into three pieces.

Try to ''use'' [[swamp paste]] on any of the [[Fragment 1|fragments]] to glue the page back together, but [[Savant]] stops you. The oily tar would ruin the ancient parchment, she warns. Instead, she advises, to make sticky glue from a rendered slug, and she mentions that it can only be done by someone who is renowned in seafood cooking.

[[File:The Slug Menace page puzzle.png|thumb|325px|The solution of the puzzle.]]
Travel to the [[Fishing Platform]] by talking to [[Jeb]], who is next to Holgart. There, talk to [[Bailey]] in the small room on the south-west corner of the platform. Hand him the dead slug you picked up earlier from the shrine, and in a few seconds, he gives you the [[sea slug glue]] you need. Finally, use the glue on the fragments, and a puzzle will pop up.

You can move the three pieces around using the buttons on the side, turn them, and even flip them over. The easiest way to tell if you've got them all on the right side is that one side is lighter than the other. ''You can look at the solution on the right side of this page.'' After you put the pieces in their correct place, the puzzle will close automatically.
"""

[[steps]]
index = 4
name = "Crafting the runes"
links = ["Abyss", "Guardians of the Rift", "chisel", "rune essence", "pure essence", "Blank air rune", "Blank water rune", "Blank fire rune", "Blank earth rune", "Blank mind rune", "Page 1", "Runecraft", "Earth Altar", "talisman", "Tiara (disambiguation)", "mysterious ruins", "Air Altar", "Falador", "Water Altar", "Lumbridge", "Zanaris", "Varrock", "Lumber Yard", "Fire Altar", "Emir's Arena", "Al Kharid", "Mind Altar", "Wilderness"]
text = """
{{Needed|Commorb, 3 pages from previous section, at least 5 rune or pure essence (it is recommended to bring more, using an essence pouch will help manage inventory space), chisel, tiaras/talismans for entering the air, water, fire, earth, and Mind Altars (not necessary if travelling through the [[Abyss]] or using [[Guardians of the Rift]])|recommended=Fast travel methods to either the five altars, the Abyss, or Guardians of the Rift}}

For the next part, you'll need a [[chisel]] and at least five [[rune essence|rune]] or [[pure essence]], although it is advised to bring as many as you can hold. Craft the runes into the [[Blank air rune|shapes of air]], [[Blank water rune|water]], [[Blank fire rune|fire]], [[Blank earth rune|earth]], and [[Blank mind rune|mind]] by ''right-clicking'' the [[Page 1|pages]], selecting the options to make the runes. It is likely to fail a few times and break some runes. The odds of success are 43% at level 1 Runecrafting and 99% at level 99 Runecrafting, scaling linearly{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1523556174893023233|date=9 May 2022|archiveurl=https://reldo.runescape.wiki/i/97377|archivedate=19 June 2022|quote=Success is 43% at level 1 RCing, 99% at level 99. Interpolate linearly between those.}}. '''Do not use the chisel on the essence, or you'll get fragments.''' When finished, you need to ''use'' the shapes' on their respective [[Runecraft#Altars|altars]] (e.g. earth on the [[Earth Altar]]). It is possible to fail empowering the runes, in which case they will also break. Thus, keep your pages, chisel and spare essence handy as you make your way to the various altars. You can travel through the [[Abyss]], Guardians of the Rift, or use a [[talisman]] or [[Tiara (disambiguation)|tiara]] on the following [[mysterious ruins]];

*Air: the [[Air Altar]] is south of [[Falador]].
*Water: the [[Water Altar]] is south of [[Lumbridge]] (next to the shack to [[Zanaris]]).
*Earth: the [[Earth Altar]] is north-east of [[Varrock]] (next to the [[Lumber Yard|Lumber yard]]).
*Fire: the [[Fire Altar]] is on the north-west corner outside of [[Emir's Arena]] in [[Al Kharid]].
*Mind: the [[Mind Altar]] is north of [[Falador]] (just below the [[Wilderness]], between the Black Knight's fortress and the Goblin village).
"""

[[steps]]
index = 5
name = "The imposing door"
links = ["Air rune (The Slug Menace)", "Fire rune (The Slug Menace)", "Mind rune (The Slug Menace)", "Earth rune (The Slug Menace)", "Water rune (The Slug Menace)", "Witchaven", "Imposing Doors", "Commorb v2", "Witchaven Dungeon", "Mayor Hobb", "White Knights", "Mother Mallum", "Slug Prince", "Prayer", "Melee", "Savant", "Falador Park", "Sir Tiffy Cashien"]
text = """
{{Needed|Commorb, melee weapon, [[Air rune (The Slug Menace)|special air rune]], [[Fire rune (The Slug Menace)|special fire rune]], [[Mind rune (The Slug Menace)|special mind rune]], [[Earth rune (The Slug Menace)|special earth rune]], and [[Water rune (The Slug Menace)|special water rune]]}}
[[File:The Slug Menace - Mother Mallum appears.png|thumb|left|200px|Confronting the slug queen.]]
{{Listen
|title = The Slug Prince
|align = right
|filename = The Slug Prince (The Slug Menace).ogg
|desc = The music track that only plays during the encounter with Mayor Hobb.}}
{{Listen
|title = Mother Mallum
|align = right
|filename = Mother Mallum (The Slug Menace).ogg
|desc = The music track that only plays during the encounter with Mother Mallum.}}
Now, head back to [[Witchaven]] to open the [[Imposing Doors|mysterious door]], and prepare for a fight. Go down with the [[Commorb v2]] into the [[Witchaven Dungeon|shrine]] in Witchaven again, and ''use'' your newly created runes on the door in any order. It is revealed that [[Mayor Hobb]] tricked you into opening the door, sealed by the [[White Knights]], so [[Mother Mallum]] could escape.

You'll have to fight a level 62 [[Slug Prince]]. Its attacks drain your [[Prayer]] by the amount of damage dealt. '''You can only use [[Melee]] to damage it'''.


Once you kill it, you'll be treated to another cinematic introducing you to [[Mother Mallum]]. The situation gets too hot to handle, and [[Savant]] will teleport you to [[Falador Park]]. Talk with [[Sir Tiffy Cashien]] again to finish the quest.

'''Congratulations, quest complete!'''
{{Clear}}
"""
