quest = "Current Affairs"
step_count = 3

[[steps]]
index = 0
name = "Duck troubles"
links = ["charcoal", "Arhein", "Catherby", "Councillor Catherine", "Archery shop", "form cr-4p", "Cabinet (Current Affairs)", "Harry"]
text = """
{{Needed|[[charcoal]] (obtainable during this section)}}
[[File:Current Affairs - Catherby Council Office.png|thumb|The player engages with Councillor Catherine in bureaucratic combat.]]
{{Map|align=right|2835,3418|mtype=pin|caption=The starting point for tracking the current.}}
[[File:Councillor Catherine chathead.png|left|frameless]]
Talk to [[Arhein]] on the northern end of the [[Catherby]] docks, and ask him what's with the duck. He explains that a travelling salesman claimed a duck is able to accurately track currents. Unfortunately, Arhein is unable to test that theory, as the local councillor is threatening to fine Arhein for using non-human workers. After offering your help, he suggests you might want to talk to [[Councillor Catherine]].

Find her in the council office in north-east Catherby, just north of the [[Archery shop]]. Ignoring your concerns, she points out that you are not registered as a sailor to do business in Catherby, and hands you the [[form cr-4p]] to fill in. If you didn't bring charcoal, search the [[Cabinet (Current Affairs)|cabinet]] and grab some.

Click on the form with the charcoal in your inventory, and you will be presented with a series of nonsensical questions with three options. '''You can select any responses you want, but you will need to repeat the same answers later'''. This can be simplified by simply picking the first answer every time, as the order of the answers do not change later when being quizzed. Speak to her again to return the form. She explains that any change to the by-laws requires approval from the Mayor of Catherby, but the Catherby Data Protection Regulation prevents her from sharing their location.

Return to Arhein and ask him about the mayor. He explains that the mayor recently died; there have been 25 consecutive mayors, all of which have been fish. As nobody other than Catherine wanted the job, the citizens used fish to prevent her from becoming mayor. You need to sneakily replace the latest mayor before she realises, and Arhein suggests that [[Harry]] at the nearby fishing shop could help.
"""

[[steps]]
index = 1
name = "Fishing a mayor"
links = ["coins", "mayoral fishbowl", "tiny net", "Mayor of Catherby", "aquarium", "form cr-4p", "form 7r4-5h", "Mayor of catherby"]
text = """
{{Needed|50 [[coins]]}}
Harry is located in the most eastern building in Catherby. Tell him you are here about the mayor, and he will sell you a [[mayoral fishbowl]] and [[tiny net]] for 50 [[coins]]. Fish the [[Mayor of Catherby]] from one of the two [[aquarium]]s in the shop.

Show Arhein the mayor and he will give the fish a mayoral chain and tell you to return to Catherine. Speak to her and after showing the mayor, she will refuse to do anything until you've reviewed your [[form cr-4p]] and ensured all the information is correct. Repeat your answers from before.

'''Note''': If you make any mistakes, Catherine will ask you to repeat only the incorrect answers after finishing the form, allowing you to choose new responses each time until they’re correct.

After successfully confirming your answers, she gives you [[form 7r4-5h]]. Use it on the [[Mayor of catherby|Mayor of Catherby]] to sign it, then return it to Catherine to finally change the by-law.
"""

[[steps]]
index = 2
name = "Charting the current"
links = ["Obelisk of Water", "Holgart"]
text = """
[[File:Current duck detail.png|80px|left|frameless]]
Inform Arhein that the by-law has been changed. He will hand you his duck; he wants you to take it out on the ocean to test the theory. Head east in your boat until you find a ripple in the water just west of the [[Obelisk of Water]]. While on top of the ripple, click on the current duck to track the current. Follow the duck until it arrives at the shore where [[Holgart]] is. Collect the duck and return to Arhein to tell him you've charted the currents. He thanks you for your help and lets you keep the current duck and mayor.

'''Congratulations, quest complete!'''
"""
