quest = "Darkness of Hallowvale"
step_count = 9

[[steps]]
index = 0
name = "Introduction"
links = []
text = """
Throughout the quest, you're expected to run around parts of Morytania, which can take quite some time, even with the proper teleports. To avoid having to retrace steps, '''be sure to read each section carefully! If you're unsure if a step is finished, check your quest log to see if it matches what's next in the walkthrough.''' Rushing to finish the quest can end up causing parts to be skipped and require going through all of Meiyerditch over again.
"""

[[steps]]
index = 1
name = "Starting out"
links = ["planks", "nails", "hammer", "Vyrewatch outfit", "Thieving", "Hitpoints", "Veliaf Hurtz", "Burgh de Rott", "Myreque", "Meiyerditch", "plank", "Boat Chute"]
text = """
[[File:Darkness of Hallowvale - Fixing boat.png|thumb|Repairing the boat in Burgh de Rott.]]
{{Needed|2 [[planks]], 8 [[nails]] and a [[hammer]]|recommended=[[Vyrewatch outfit]] or 1,950gp to purchase one once you get to the city (only if your [[Thieving]] or [[Hitpoints]] is low)}}

Speak to [[Veliaf Hurtz]] in the basement of the pub in [[Burgh de Rott]]. Ask if there is something you can do to help out, and he will request assistance in scouting a route into the Sanguinesti region. He wants you to make contact with the [[Myreque]] in [[Meiyerditch]].

Go south-east to the docks where you'll find a hut with a boat in it. Inspect the boat to repair it using a [[plank]] and four [[nails]]. Inspect the [[Boat Chute|boat chute]] going down into the water to repair it, also using a plank and four nails. You can now bank or drop your hammer. Push the boat down the chute into the water and board it to travel to [[Meiyerditch]].
"""

[[steps]]
index = 2
name = "Welcome to Meiyerditch"
links = ["Vyrewatch", "Hitpoints", "Thieving", "Myreque hideout", "Daeyalt ore", "pickaxe", "Old Man Ral", "Trader Sven", "Vyrewatch outfit", "vyrewatch"]
text = """
[[File:Floating Vyre.png|thumb|Arriving in Meiyerditch.]]
'''Note''': While in Meiyerditch, the [[Vyrewatch]] will occasionally stop you, and you will be presented by several options. You may choose to logout and login during the conversation to avoid this.

* ''"Pay a blood tithe" - The Vyrewatch will damage you for 6 [[Hitpoints]]. '''Chosen by default if you don't select an option.'''''
* ''"Bring it on" - The Vyrewatch will attack you, allowing you to run away. '''The Vyrewatch are invulnerable to all sources of damage available to you at this stage.'''''
* ''"Distract him" - Success rate depends on your [[Thieving]] level, if you fail you will be damaged for 6 [[Hitpoints]].''
* ''"Send me to the mines!" - (this option appears after you've found the [[Myreque hideout]]). You will not lose health, instead you will need to mine 15 [[Daeyalt ore]]s, place them in a minecart and then talk to a guard to leave. '''You'll then appear in the north-east part of the city.''' If you have no [[pickaxe]], a miner will supply one.''

After boarding the boat, you will arrive at the very southern, damaged end of the southern wall of Meiyerditch. Climb onto the rocks and then climb up. Follow the winding wall until it runs straight north, then search (right click) the very first set of floorboards. Kick them in, then climb down into the passage below.

Climb over the wall rubble to enter the town, and talk to any nearby Meiyerditch citizen. Ask them in a '''whisper''' if they know about the Myreque, then '''whisper''' that you really need to meet them. They will tell you to speak to [[Old Man Ral]]. Ask if they can introduce you to him. They will tell you to say a friend recommended him.

Old Man Ral is north of where you climbed over the rubble - follow the wall until it turns inwards, and he is in the second building to the east (and one building north of [[Trader Sven]]). Tell him someone said you could help me, then when he asks you what they called him, tell him it was the ''"Sage of Sanguinesti".'' He should now tell you that you need to get to Sector 3 of the city by following sickle symbols on the walls.

'''''Optional:''' Just to the south, [[Trader Sven]] sells the [[Vyrewatch outfit]] for 1,950 GP. The [[vyrewatch]] will stop you less often while wearing this outfit, which may save you time throughout the quest.
"""

[[steps]]
index = 3
name = "The sickle logo agility course"
links = ["knife", "sickle", "RuneLite", "Old Man Ral", "Door key (Darkness of Hallowvale)", "ladder top", "lumpy rug", "Vertida Sefalatis", "Message (Vertida)", "Veliaf Hurtz", "Burgh de Rott"]
text = """
{{map:Meiyerditch DoH}}
[[File:Darkness of Hallowvale - navigating the ghetto.png|400px|thumb|The rooftops of Meiyerditch.]]
{{Needed|A [[knife]] or a [[sickle]] (a knife can be acquired on the way, in sector 3 of the agility course)}}

You now need to make a complex journey across the city - watch for the sickle marks or simply follow the instructions below. Make sure to have a knife or a sickle on you.

'''Note:''' The sickle marks may be more difficult to see when using [[RuneLite]] graphics enhancers like 117 HD.

''You may click each of the steps below as you do it to track your progress.''
{|class="wikitable lighttable"
!Sector 1 directions
|-
|Go to the house south-west of [[Old Man Ral]] with the door facing north (with a sickle symbol next to the door)
|-
|Climb up the ladder there.
|-
|Jump south to the floorboards.
|-
|Jump east to the floorboards.
|-
|Go to the north-east corner of the room, push the wall and walk across the gap.
|-
|Crawl under the wall to the north.
|-
|Go north to the second room, look on the west side, push the wall and go across.
|-
|Go down the ladder.
|-
|Search the table next to the west wall, open the trapdoor, and go through the resulting tunnel.
|-
|Climb up the shelf next to the sickle in the north west corner.
|-
|Crawl under the wall to the east side.
|-
|Jump to the floorboards to the east.
|-
|Go down the ladder.
|-
|Search the pots near the eastern door to get a [[Door key (Darkness of Hallowvale)|door key]].
|-
|Use the key to open the door in that room. You are now in sector two.
|}
{| class="wikitable lighttable"
!Sector 2 directions
|-
|Go up the ladder in the room to the east, by the sickle.
|-
|Jump south to the floorboards.
|-
|Go east around the wall then climb up the shelves to the south.
|-
|Go up the ladder to the west.
|-
|Jump south again to the floorboards.
|-
|Go down the ladder to your immediate west.
|-
|Go east and walk across the washing line.
|-
|Climb down the ladder.
|-
|Push the wall to the north and walk across the floor.
|-
|Climb up the shelf to the north.
|-
|Climb down the shelf in the north-eastern corner.
|-
|Jump to the floorboards to the north.
|-
|Jump to the floorboards to the north again.
|-
|Go to the north end of the building and jump to the floorboards to the east.
|-
|Climb up the ladder (not down using the broken one).
|-
|Search the wall to the west to get a [[ladder top]].
|-
|Climb down again and repair the broken ladder (going down) with the ladder top.
|-
|Climb down the fixed ladder. You are now in sector three.
|}
{| class="wikitable lighttable"
!Sector 3 directions
|-
|Exit through the door, and go past the building to the north.
|-
|Enter the only house with an intact door to the north.

''If you don't have a knife yet, climb the ladder in this room to take one. Climb back down after.''
|-
|Go west through the door into the next room, then north out of the house.
|-
|Head north until you reach a sickle symbol, then follow the path east and enter the house to the south with a ladder inside.
|-
|Go up the ladder.
|-
|Jump to the floorboards to the east.
|-
|Climb down the stairs. Go around the east side of the stairs, and use your knife or sickle on the wall to the south. Push open the wall.
|-
|Press the decorated wall with a hanging sickle, then open the [[lumpy rug]] from the south-east square.

''If you take too long, you will have to push the wall again as the system will quickly reset.''
|-
|Climb down trapdoor to enter the hideout.
|}

Speak to [[Vertida Sefalatis]] in the northern room of the hideout. Tell him you've come to investigate and make contact with the Myreque, and he will give you a [[Message (Vertida)|message]] to take to [[Veliaf Hurtz]] back in [[Burgh de Rott]].
"""

[[steps]]
index = 4
name = "Urgent business"
links = ["Message (Vertida)", "Burgh de Rott", "Drezel", "Paterdomus", "shadowy figure", "Fairy ring", "Varrock", "Bush (Darkness of Hallowvale)", "Shadowy figure", "River Salve", "King Roald", "runes", "Varrock Teleport", "Varrock Castle", "Aeonisig Raispher", "Veliaf Hurtz"]
text = """
{{Needed|recommended=Fast travel method to Burgh de Rott, Paterdomus Temple and Varrock|[[Message (Vertida)|Message]] (from Vertida)}}

Return to [[Burgh de Rott]] and talk to Veliaf Hurtz in the basement of the pub again. He will tell you that he has received word from [[Drezel]] that something strange has been happening in the Temple of the Salve in [[Paterdomus]], and he wants you to check it out.

[[File:Darkness of Hallowvale - werewolves appear.png|thumb|The player is knocked unconscious by [[shadowy figure]]s.]]

Go to [[Drezel]] in [[Paterdomus]] ([[Fairy ring|fairy code]] {{fairycode|CKS}}) and talk with him. He will say that strange noises have been heard outside the temple and asks you to investigate. Exit the temple via the west ladder towards [[Varrock]]. Past the stairs to the temple, look for a [[Bush (Darkness of Hallowvale)|bush]] that is searchable. A short cut-scene will follow where you will be knocked out. You will see [[Shadowy figure|werewolves]] that seem to have managed to get across the [[River Salve]].

Return to Drezel, and tell him what you have just seen. He tells you to speak with [[King Roald]] and gives you [[runes]] for a [[Varrock Teleport]].

Go to [[Varrock Castle]], and speak with King Roald located in the south-easternmost room near the main entrance. After a long, fruitless conversation, ask him what you should do now. Afterwards, a free teleport back to [[Paterdomus]] is offered by [[Aeonisig Raispher]]. Accepting the teleport is optional, as you will need to then return to [[Burgh de Rott]] instead.

Speak to [[Veliaf Hurtz]] again, who will send you onwards to warn the Myreque's Sanguinesti order.
"""

[[steps]]
index = 5
name = "Scoping Castle Drakan"
links = ["Protect from Melee", "Meiyerditch", "Vertida Sefalatis", "Vyrewatch", "Daeyalt ore", "Safalaan Hallow", "rocky surface", "Barricade (Darkness of Hallowvale)", "papyrus", "charcoal", "Castle sketch 1", "Castle sketch 2", "Vanstrom Klause"]
text = """
{{Needed|A knife or sickle and 4 free inventory spaces.|recommended=Any pickaxe (the strongest you can wield), armour and food if you cannot use [[Protect from Melee]].}}

Travel once more with the boat you fixed to [[Meiyerditch]]. Head towards [[Vertida Sefalatis]] again, using the rooftop route described above or with the faster alternative method described below.
{{Map|align=right|x=3635|y=3278|height=500|zoom=3|caption=
{{legend|#f0ff00|caption=Laboratory}}
{{legend|#ff0000|caption=Myreque Hideout}}
|mtype:line,stroke:#0fff00,stroke-width:4
,3631:3267,3634:3267,3634:3277,3638:3277,3638:3283,3635:3283,3635:3288
,3633:3288,3633:3294,3628:3294,3628:3300,3631:3303,3631:3306,3624:3313,3624:3320
|mtype:line,stroke:#f0ff00,stroke-width:4,3633:3294,3635:3294,3635:3300,3640:3300,3640:3302,3638:3302,3638:3305,3641:3307
|mtype:line,stroke:#ff0000,stroke-width:4,3631:3267,3631:3258
|mtype:line,stroke-width:4,3632:3257,3633:3256,3639:3256
|mtype:line,stroke:#ff0000,stroke-width:4,3639:3256,3639:3257,3640:3257,3640:3253
|mtype:rectangle,rectY:2,rectX:2,stroke:#ff0000,fill:#ff0000,fill-opacity:0.7,desc:Myreque Hideout,3639:3250
|mtype:rectangle,rectY:2,rectX:2,stroke:#f0ff00,fill:#f0ff00,fill-opacity:0.7,desc:Laboratory,3643:3305
}}
{| class="wikitable lighttable"
!Alternative route to Vertida Sefalatis
|-
|Speak to any [[Vyrewatch]] and ask to be sent to the mines.
|-
|Mine 15 [[Daeyalt ore]]s and place them in the minecart. ''If you have no pickaxe, talk to a miner to obtain a bronze one.''
|-
|Once the mine cart is full, talk to a guard to leave. You will appear up on the surface, north-east of the slums.
|-
|''See the map to the right and follow the green path.'' This involves zigzagging through a southern path between the houses. You will have reached the correct house to enter once you can no longer head any further south along the path. Travel through this house and enter the next one to the south.
|-
|From there, follow the old route; climb up the ladder, jump east to the floorboards, climb down the stairs, and go south-east through the hidden door.
|-
|Push the wall to the north and enter the trapdoor underneath the rug (south-east corner).
|}

Once you're down the trapdoor, talk to Vertida Sefalatis. He will urge you to talk to their leader [[Safalaan Hallow]], who is out on a mission to sketch Castle Drakan. Ask Vertida to lead the way, and he will take you to the south of [[Meiyerditch]].

Starting from the south of Meiyerditch, reach [[Safalaan Hallow]] with the following steps;
{| class="wikitable lighttable"
!'''Route to Safalaan Hallow'''
|-
|Climb down the ladder.
|-
|Head south and climb over the wall rubble where you first came into the city.
|-
|Head south climb up the floor to get on top of the wall. Then, travel as far north on the wall as you can, until you reach a ladder you can go down.
|-
|Proceed down the ladder.
|-
|Search the [[rocky surface]] (east wall) to unlock the [[Barricade (Darkness of Hallowvale)|false wall]] to the north (labelled as "barricade").
|-
|Open the barricade; then go north, and climb the ladder.
|-
|Go north along the wall, up a ladder and down one to cross a gap, and keep going north until you reach the Darkmeyer south wall.
|-
|Climb the wall and go north until you see Safalaan.
|}
[[File:Darkness of Hallowvale - the Drakans.png|thumb|Vanstrom meets with the Drakans.]]
Talk to Safalaan and the player will inform him of all the developments so far. Safalaan wants to return to the Myreque base, and asks you to take over his mission to sketch Castle Drakan. He asks you to sketch three sides of the castle in order -- north, west and south, and gives you some [[papyrus]] and [[charcoal]] to draw with. There are sickle symbols on the ground to tell you where to sketch. Follow the wall west towards the back of the castle. Walk past the first sickle symbol, heading instead to the north towards the second one. Standing on the sickle symbol to the north, use [[charcoal]] on a piece of [[papyrus]] to make [[Castle sketch 1|a drawing]] of the castle. Head back to the sickle symbol you passed by earlier, and make a [[Castle sketch 2|second sketch]]. You will see a short cutscene, of [[Vanstrom Klause]] talking to Vanescula Drakan and Ranis Drakan. They will drink some fresh blood and then fly away.
"""

[[steps]]
index = 6
name = "Ambush!"
links = ["Safalaan", "Vanstrom Klause", "Protect from Melee", "Sarius Guile"]
text = """
[[File:Darkness of Hallowvale - Vanstrom knocks player out.gif|thumb|Vanstrom Klause knocks you out.]]
Go to the south-eastern side of the castle (where you spoke to [[Safalaan]]), and attempt to make another drawing on the sickle symbol there. After a short cutscene, [[Vanstrom Klause]] will interrupt your drawing and attack you. You cannot damage him in any way, and it is possible to die here. Vanstrom only uses melee, so [[Protect from Melee]] will stop all damage - activate it after the cutscene has concluded.

After five attacks, Vanstrom will knock you out. When you awake, remember to '''finish your final drawing'''. Speak to Vanescula's servant, [[Sarius Guile]]. She gives you a long-winded hint about where to find a secret laboratory.  Your quest log should then read ''"I have all three sketches of the castle. I need to take them to Safalaan".''

'''Note''': If you die on the fifth attack from Vanstrom, you will be teleported back to your grave and the cutscene will continue.{{fact|Confirmation needed. An elaboration may also be appropriate.}}
"""

[[steps]]
index = 7
name = "The secret laboratory"
links = ["normal spellbook", "vampyre statue", "Meiyerditch", "knife", "Message (fireplace)", "Portrait (Darkness of Hallowvale)", "large ornate key", "Vertida", "Safalaan", "broken rune case", "runes", "Telekinetic Grab", "Haemalchemy volume 1"]
text = """
{{Needed|Be on the [[normal spellbook]]. A knife|recommended=Any pickaxe (the strongest you can wield) and three free spaces for mining Daeyalt ores}}

[[File:Darkness of Hallowvale - route to fireplace.png|thumb|The route to the fireplace.]]
[[File:Darkness of Hallowvale vampyre statue.png|thumb|A key [[vampyre statue]].]]
Return to the Myreque base in [[Meiyerditch]] via your preferred route; having a vyrewatch send you to the mine is the fastest. Just before you enter the base, head to the building with the fireplace and portrait just west of the rug entrance. If you lack a [[knife]], climb the ladder in the building with the fireplace and grab one off the table.

Use the knife on the fireplace to discover a hidden [[Message (fireplace)|message]] about a laboratory. Using a sickle will cause it to say it's the wrong shape. Then, use the knife on the southern [[Portrait (Darkness of Hallowvale)|portrait]] in the same room. Search the slashed portrait to get a [[large ornate key]]. Return to [[Vertida]], who is now accompanied by [[Safalaan]]. Give Safalaan the message you got from the fireplace and the three drawings of the castle.

After filling in Safalaan, you need to locate the hidden laboratory that Sarius mentioned. Leave the hideout, go up the stairs, jump west, go down the ladder, and exit the house on the northern side. Walk through the house north. Continue north-east staying near the eastern wall. You will find the house with a clearly visible large tapestry in one of the rooms, coloured red and yellow. Enter the house and use your knife on the tapestry, then walk through it.

'''Note''': If you see the message {{Mes|you see no reason to destroy this tapestry}}, then you did not collect the message from the fireplace earlier.

Use the large ornate key with the [[vampyre statue]] to open the secret laboratory entrance. '''Do NOT try to open the door by using the key on the door as this will inflict 10 damage.'''

Open the door, and go down the stairs. You may search the [[broken rune case]] to the west of the staircase for some [[runes]] (including [[Telekinetic Grab]] runes). Use Telekinetic Grab on the book [[Haemalchemy volume 1]] in the room.
"""

[[steps]]
index = 8
name = "Finishing up"
links = ["Safalaan", "Veliaf Hurtz", "sealed message", "Myreque Hideout", "Burgh de Rott"]
text = """
Leave the room and take the book back to [[Safalaan]]. He will tell you to return to [[Veliaf Hurtz]] with a [[sealed message]]. You will now be able to use the shortcut doors on the path to the [[Myreque Hideout]]. However, this is not recommended due to this method being slower than being teleported to the mine.

Get back to [[Burgh de Rott]] via any method, and talk to [[Veliaf Hurtz]] in the basement of the pub to finish the quest.

'''Congratulations, quest complete!'''
"""
