quest = "Waterfall Quest"
step_count = 4

[[steps]]
index = 0
name = "Searching for treasure"
links = ["Almera", "Coal Trucks", "Baxtorian Falls", "games necklace", "Hudon", "Log raft (Waterfall Dungeon)", "bookcase (Waterfall Quest)", "book on baxtorian", "Lord Baxtorian Cadarn", "Glarial", "Glarial's pebble", "Tree Gnome Village (location)"]
text = """
{{Needed|recommended=Fast travel to Tree Gnome Village and then a bank for the next section}}
[[File:Almera chathead.png|left|frameless]]
Start out by speaking to [[Almera]] in her house west of the [[Coal Trucks]] and north-east of the [[Baxtorian Falls]] (use the [[games necklace]] to teleport to Barbarian Outpost, and run south). She will tell you that she is worried about her son, [[Hudon]], who is on the opposite side of the river looking for treasure.
[[File:Waterfall Quest - Shipwrecked raft.png|thumb|220px|Hudon and the crashed boat.]]
She will request that you check on him. Exit Almera's house toward the river and board the [[Log raft (Waterfall Dungeon)|log raft]]; you will crash into a small island.

Talk to Hudon. You will tell him to come back to his mother, but he'll refuse, hoping to stay out and find treasure. When you ask if you can help, he rejects you, saying you will steal his loot. '''Finish all the dialogue or the book will not spawn in the next part'''.

Swim to the south and you will be sent downstream, washing ashore near a large building with a fisherman outside of it. Upstairs in the building, search the southernmost [[bookcase (Waterfall Quest)|bookcase]] on the eastern wall to find a book named [[book on baxtorian]]. '''Read the book''' or the key will not appear for the next part.

You will discover that [[Lord Baxtorian Cadarn|Baxtorian]] and [[Glarial]] were elven, and read about the legend of treasure under the falls. You will also learn that [[Glarial's pebble]] can be found under [[Tree Gnome Village (location)|Tree Gnome Village]], which will give you access to her tomb.
"""

[[steps]]
index = 1
name = "Glarial's Pebble"
links = ["food", "armour", "Tree Gnome Village (location)", "Tree Gnome Village", "Elkoy", "Spirit Tree", "Grand Exchange", "King Bolren", "hobgoblin", "Key (Gnome Village Dungeon)", "Golrie", "Glarial's pebble", "drop trick", "Roving Elves"]
text = """
{{Needed|recommended=[[food]] and [[armour]]}}
[[File:Glarial's pebble detail.png|left|frameless|80px]]
{{Map|x:2533,y:3155|x:2545,y:3155|x:2545,y:3148|x:2542,y:3148|x:2542,y:3150|x:2539,y:3150|x:2539,y:3145|x:2549,y:3145|x:2549,y:3156|x:2551,y:3156|x:2551,y:3159|x:2545,y:3159|x:2545,y:3165|x:2550,y:3165|x:2550,y:3175|x:2544,y:3175|x:2544,y:3177|x:2533,y:3177|x:2533,y:3179|x:2531,y:3179|x:2531,y:3177|x:2529,y:3177|x:2529,y:3179|x:2527,y:3179|x:2527,y:3177|x:2514,y:3177|x:2514,y:3179|x:2521,y:3179|x:2521,y:3184|x:2524,y:3184|x:2524,y:3181|x:2529,y:3181|x:2529,y:3182|x:2532,y:3182|x:2532,y:3188|x:2511,y:3188|x:2511,y:3191|x:2503,y:3191|mtype=line|align=right|height=250|width=250|caption=Follow the line to find the Dungeon.}}

Head to the [[Tree Gnome Village (location)|Tree Gnome Village]] south-west of Ardougne. If you have previously started or completed the [[Tree Gnome Village]] quest, you may follow [[Elkoy]] through the maze, or use the [[Spirit Tree]] from the [[Grand Exchange]] to reach the centre (if it was completed).

'''Note:''' It is recommended to start the Tree Gnome Village quest now by talking to [[King Bolren]] in the centre of the maze, which will allow you to follow [[Elkoy]] through the maze in the future.

If you have not begun [[Tree Gnome Village]] you will have to navigate through the maze. You should find a ladder in the hedge maze. Very low level players should exercise caution due to the [[hobgoblin]]s within. Climb down the ladder, and find [[Key (Gnome Village Dungeon)|the key]] in the east room. The key is in the slightly differently-coloured crate next to the two crates stacked on top of each other in the south-east corner. In the west room, you will find a gnome called [[Golrie]] locked away. Use your key on the door, then speak to the gnome to receive [[Glarial's pebble]].

'''Note:''' You can use the [[drop trick]] to obtain multiple pebbles, which is highly recommended for low level players in case you die during the next steps. You will also save some time in the future by keeping your pebble after the quest if you plan to complete [[Roving Elves]].

Once you've started Tree Gnome Village, you can exit the maze by following [[Elkoy]].
"""

[[steps]]
index = 2
name = "Tomb Raiding"
links = ["Glarial's pebble", "Glarial's Tomb", "weapons", "armour", "runes", "arrows", "logs", "Jewellery", "games necklace", "food", "Baxtorian Falls", "Fishing Guild", "skeleton", "Zombie (common)", "Moss Guardian", "Glarial's amulet", "Glarial's urn", "drop trick"]
text = """
{{Needed|[[Glarial's pebble]], two free inventory slots|recommended=Food and armour, fast travel method to a bank and Baxtorian Falls for the next section}}
[[File:Glarial's tombstone.png|thumb|left|80px|Glarial's tombstone]]
{{Map|name=Glarial's Tombstone|x:2558,y:3445|plane=0|r=4|mapID=0|mtype=square|align=right|height=220|width=220|caption=Glarial's tomb location}}

[[Glarial's Tomb]] has significant restrictions on items you can equip or carry. You can either bank these items now, or drop them outside the tomb to recollect afterwards. This includes [[weapons]], [[armour]] (including capes), [[runes]], [[arrows]] and any type of [[logs]] you may be carrying. [[Jewellery]] like the [[games necklace]] can be taken in. See the Glarial's Tomb page for a full list. Bring [[food]] with you, as you will need to run past high level monsters.

Head just south-east of [[Baxtorian Falls]] and just north-west of the [[Fishing Guild]] to find a tombstone, and use the pebble on it to enter. Inside, there are high-level monsters that you will need to pass. One strategy is to attack a lower level [[skeleton]] or [[Zombie (common)|zombie]], as the area is single combat and this will prevent  the more dangerous [[Moss Guardian]] attacking you, which has a max hit of 14.

Run to the west part of the cave, past the level 84 moss guardians, and search the chest to get [[Glarial's amulet]]. Then head to the south part of the cave and search the coffin to get [[Glarial's urn]]. '''Note that you will be unable to perform actions while searching the coffin but can be attacked, so beware!'''

'''Note''': You can get multiples of both items using the [[drop trick]], which is advised for low levels as you can die in the next section.


Once you have '''both items''', you can exit the tomb by going up the ladder.
"""

[[steps]]
index = 3
name = "The Chalice of Eternity"
links = ["Rope", "Air rune", "water rune", "earth rune", "Glarial's urn", "Glarial's amulet", "armour", "food", "weapon", "Almera", "shadow spider", "A key (Waterfall Dungeon)", "skeleton mage", "Fire Giant", "Chalice of Eternity", "Kandarin Diary", "air rune"]
text = """
{{Needed|[[Rope]], 6 [[Air rune]]s, 6 [[water rune]]s, 6 [[earth rune]]s, [[Glarial's urn]], [[Glarial's amulet]], 5 free inventory slots|recommended= [[armour]], [[food]], [[weapon]] if killing a Fire Giant for a diary task, fast travel method out after quest completion}}

Go back to [[Almera]]'s house and board the raft. You will crash again. '''Do not swim or interact with the tree without the rope!''' Use your '''rope''' on the large grey rock on the small patch of land just downstream, then use the '''rope''' on the dead tree that you can climb. When you reach the doors at the waterfall ledge, go inside.
[[File:Waterfall Dungeon map.png|thumb|left|130px|Map of Waterfall Dungeon.]]
{|class="wikitable"
!Map Label
!Description
|-
|1
|A cavern with level 52 [[shadow spider]]s that drain your prayer
|-
|2
|A room with crates containing [[A key (Waterfall Dungeon)|a key]] needed for the quest and level 16 [[skeleton mage]]s
|-
|3
|Not used in the quest
|-
|4
|A cavern with level 86 [[Fire Giant]]s
|-
|5
|The path to the [[Chalice of Eternity]]
|-
|6
|A room with the Chalice of Eternity
|}

Take the eastern passage first to search the crates for [[A key (Waterfall Dungeon)|a key]], then take the western passage north. This is a single combat area, so you may choose to attack a shadow spider so that the [[Fire Giant]]s will be unable to attack you. This is a common training spot, so you may also consider world hopping until you find players fighting the Fire Giants. You may also consider killing a Fire Giant to complete a medium [[Kandarin Diary]] task (not recommended for lower level players)

[[File:Chalice of Eternity.png|100px|left|The Chalice of Eternity.]]

{{Color|Red|Warning:}} Follow the next part carefully. If done incorrectly you will either be washed from the final room, or take up to 20 damage if you do not place the runes correctly.

Beyond the fire giants, you will find six pillars, two statues, and a [[Chalice of Eternity|chalice]] trophy. Use an [[air rune]], a [[water rune]], and an [[earth rune]] on one pillar, then do the same for the other five. Use Glarial's amulet on the '''Statue of Glarial''', and then use Glarial's urn on the '''Chalice of Eternity''', '''completing the dialogue'''. Take the reward (note that you must have five free slots to accept it) from the chalice after the ground rises up to it to finish! {{Color|Red|Warning:}} any items you drop inside the chamber with the six pillars will be unretrievable once you use Glarial's amulet with the statue. Make sure to drop any items you want to recover outside the chamber by crossing the door.

'''Note:''' If you do get flushed out, or leave, the pillars will remain active. However, you will need to retrieve another amulet to re-enter the dungeon.

'''Congratulations, quest complete!'''
{{Clear}}
"""
