quest = "A Soul's Bane"
step_count = 5

[[steps]]
index = 0
name = "Rage"
links = ["Tolna", "weapon rack (Tolna's rift)", "Angry unicorn", "Anger sword", "Angry bear", "Anger spear", "Angry giant rat", "Anger mace", "Angry goblin", "Anger battleaxe"]
text = """
{{Cquote2|''"<big>Why should I, Tolna, be trapped in such a wretched place? Arrghh, It's not fair! Feel my ANGER!</big>"''}}[[File:Weapon rack (Tolna's rift) (Full).png|left|frameless|width=104x104]]''This room represents [[Tolna]]'s anger by frustrating players, as they can only hit monsters with certain weapons.''<br>

The rage room has four types of monsters, which must be killed to fill a rage meter. When entering this room, players will see a [[weapon rack (Tolna's rift)|weapon rack]], which contains four types of weapons. Each of the weapons only work on a specific monster, and will deal normal damage multiplied by 10 when correctly chosen.[[File:A Soul's Bane - maximum outrage.gif|thumb|500x500px|The player, outraged, kills all the remaining monsters.]]To defeat the monster, unwield your weapon and shield, and select one of the weapons from the rack and wield it. Only one weapon can be taken at a time. Once you have the weapon, kill the monster it can damage, based on the table below:
{| class="wikitable"
|+
!Monster
!Monster name
!Weapon
!Weapon name
|-
|[[File:Angry unicorn.png|frameless|width=100x100]]
|[[Angry unicorn]]
|[[File:Anger sword detail.png|frameless|width=100x100]]
|[[Anger sword]]
|-
|[[File:Angry bear (level 40).png|frameless|width=100x100]]
|[[Angry bear]]
|[[File:Anger spear detail.png|frameless|width=100x100]]
|[[Anger spear]]
|-
|[[File:Angry giant rat (level 45, 1).png|frameless|width=139x139]]
|[[Angry giant rat]]
|[[File:Anger mace detail.png|frameless|width=102x102]]
|[[Anger mace]]
|-
|[[File:Angry goblin.png|frameless|width=132x132]]
|[[Angry goblin]]
|[[File:Anger battleaxe detail.png|frameless|width=100x100]]
|[[Anger battleaxe]]
|}
[[File:A Soul's Bane - Tolna leaves home.png|thumb|300x300px|Tolna leaves the streets of Varrock in search of a more lucrative life.]]Players will do large amounts of damage on these creatures, but no experience will be gained. Each creature killed will fill the "rage level" bar at the top of the screen. After several kills of the player's choice of angry creatures, the bar will reach maximum and the player will yell, spin, and kill all remaining monsters in the room. This grants the player 40 Attack experience.

A cutscene will then play, in which Tolna leaves his mother for a more lucrative life. Players can then exit out of the rage room near the east end of the cave, and proceed to the next room.
<br>
"""

[[steps]]
index = 1
name = "Fear"
links = ["Tolna", "fear reaper", "Dark hole (A Soul's Bane)"]
text = """
{{Cquote2|''"<big>It's so quiet and dark. I FEAR I may never escape this horrid place. Mum, Dad, help me!</big>"''}}[[File:Fear reaper (Level 42).png|left|frameless|width=141x141]][[File:A Soul's Bane - dark holes.png|thumb|300x300px|You must look into the dark holes. Prepare for a small shock.]]''This room represents [[Tolna]]'s fear, giving players a frightening jolt when they don't know whether or not a [[fear reaper]] will attack.''<br>

In this room, you will find multiple [[Dark hole (A Soul's Bane)|dark holes]] lining the outer walls. One of these holes is too dark and frightening to search, while the others have a chance of triggering a 'jumpscare' and summoning a [[fear reaper]]. You will have to kill five of these in order to progress.  Which hole that spawns a [[fear reaper]] is random and changes after each kill, requiring you to move around the room and search different holes after each encounter. Depending on your luck, you might need to circle the room up to five times to get defeat all five reapers.[[File:A Soul's Bane lit up hole.png|thumb|alt=Picture of the hole for the player to proceed.|width=120x120|Lit up hole to the west]]
<br>
{| class="wikitable"
|+After each kill your character is less afraid.
!Kill count
!Message
|-
|1
|I don't like looking in these holes but I must!
|-
|2
|I don't feel quite so afraid now.
|-
|3
|These holes aren't that spooky.
|-
|4
|This isn't so scary after all!
|}
After the final kill, your character will remark "Phew, I don't feel so scared now. This feels like the figment of someone's imagination!", and a cutscene will be triggered. Following the cutscene, the hole to the west will be lit up, and you will be able to proceed. <br>
"""

[[steps]]
index = 2
name = "Confusion"
links = ["Tolna", "confusing door", "confusion beast", "combat", "experience", "Ranged", "Magic", "melee", "poison", "Throwing knife", "multi-hit weapons"]
text = """
{{Cquote2|''"<big>Where am I, How long have I been here? Am I still the person I once was? Oh why am I so CONFUSED?</big>"''}}[[File:Confusion beast.png|left|frameless|width=100x100]]''This room represents [[Tolna]]'s confusion, flabbergasting the player because some doors lead nowhere and some beasts can't be hurt. ''

[[File:A Soul's Bane - confusion beasts.png|thumb|300x300px|If you're doing 0 damage, then the creature is an illusion.]]
In this room, there are six [[confusing door]]s. There are also five [[confusion beast]]s, but only one of them is real at the time; the others are illusions, and cannot be damaged (although they will still grant [[combat]] [[experience]]).

'''''(TIP: You can color each beast, and when you find the right one, that''''' '''''same color will be the correct beast all 6 times)'''''

The illusions will disappear after you hit eight zeroes on them; players can simply keep attacking the beasts until they disappear, or disengage by running to the opposite corner and then attacking another beast.

Once you kill the real confusion, one of the confusing doors will vanish, and the rest of the beasts will respawn. Repeat the previous process four more times, until only one door remains, at which point a cutscene will trigger.

[[Ranged]] or [[Magic]] is best for this step, as the beasts attack from a distance. When using [[melee]], they have a chance to inflict [[poison]], which can be negated by attacking with a long-distance weapon. [[Throwing knife|Throwing knives]], [[multi-hit weapons]], or other fast weapons are helpful for speedy kills on the illusions.
[[File:SoulBane1a.jpg|thumb]]
Illusions will chase you after attacking, and will keep you from attacking any of the other monsters while you are still in combat.

You will see a cutscene after the last kill. After that, you can proceed through the final Confusing Door.

'''''{{Colour|red|Note: this room sometimes glitches, resulting in no monsters appearing. If you don't see any monsters when you enter the room, simply log out and log back in.}}'''''
"""

[[steps]]
index = 3
name = "Hopelessness"
links = ["Tolna", "hopeless creature", "Hope Bridge"]
text = """
[[File:A Soul's Bane - the hope bridge.png|thumb|300x300px|The hope bridge that appears after killing all the hopeless creatures.]]
{{Cquote2|''"<big>What's the point? No-One will ever help me. I'm not worth anything, will anyone ever combat my HOPELESSNESS?</big>"''}}
[[File:Hopeless creature.png|left|frameless|width=100x100]]
''This room represents [[Tolna]]'s hopelessness — players must not give up when the creatures reappear after dying.''

In this room are five [[hopeless creature]]s, which need to be killed three times each to fully die. Be careful of eating, as the monster's health will be restored. Additionally, if they are poisoned, the poison effect is lost when they reach their next phase.

Once they have all died, the [[Hope Bridge|Bridge of Hope]] will appear. After crossing the bridge, go through the exit, which will trigger a short cutscene.
"""

[[steps]]
index = 4
name = "Tolna"
links = ["Tolna", "multicombat", "poison", "antipoison", "Ranged", "Magic", "Ava's device", "Varrock Diary"]
text = """
[[File:A Soul's Bane - Brana confronts Tolan.png|thumb|300x300px|Tolna's father, Brana, confronts his son.]]
''The final room contains [[Tolna]], a three-headed beast which must be slain in order to revert him back to a human.''

The final room is a [[multicombat]] zone, and all three heads will attack at once. They use a ranged attack from a distance, and the northern head will very rapidly melee when up close. They are not very strong, but they attack quickly and can [[poison]], so players should bring an [[antipoison]] and a decent amount of food. The three heads are very easy to beat with [[Ranged]] or [[Magic]], although be warned that if using range without an [[Ava's device|accumulator]], player will not be able to retrieve their arrows.

After killing each head, Tolna will become human again. Talk to Tolna, and he will take you back to the surface. Talk to him again to finish the quest.

'''Congratulations, quest complete!'''

'''''Tip:''' Re-enter the dungeon right after completing the quest to complete a medium [[Varrock Diary]] task.''

{{Clear}}
"""
