quest = "Hazeel Cult"
step_count = 4

[[steps]]
index = 0
name = "Hazeel Thieves"
links = ["East Ardougne", "Ceril Carnillean"]
text = """
[[File:Ceril Carnillean chathead.png|left|frameless]]
Head to the house in the south-western corner of [[East Ardougne]]. Speak to [[Ceril Carnillean]], who will start ranting about thieving cultists. Ask him what's wrong; some cultists have stolen a suit of armour, and the player will offer to help get it back. He points you in the direction of a cave to the south of the city. Head east of the clock tower, and enter the cave (south of Valve 3 on the side).
{{Clear|left}}
"""

[[steps]]
index = 1
name = "Picking a side"
links = ["Ceril Carnillean", "Hazeel", "coins", "Carnillean armour", "iron platebody", "Hazeel's mark", "Alomone", "Secrets of the North"]
text = """
[[File:Clivet chathead.png|left|frameless|80px]]
At this stage you will have a choice between two sides in this quest, helping [[Ceril Carnillean]] get his family armour back and foiling the plan to revive [[Hazeel]], or helping Hazeel's followers murder a Carnillean and resurrect their master.

The reward is almost the same for both, though siding with Ceril will reward 5 additional [[coins]] and gives you the option to obtain [[Carnillean armour]], although this armour has lower defensive bonuses than an [[iron platebody]]. Siding with Hazeel will reward the [[Hazeel's mark]], which is a purely cosmetic reward. Rewards may only be obtained during or upon completion of the quest, and can '''never''' be reclaimed afterward.

Ceril's side is quicker, but requires killing [[Alomone]], which is not recommended for very low-level players.  Your choice will also have a minor effect on the events of the quest [[Secrets of the North]].

If siding with Hazeel, skip the following section and read the next one.
"""

[[steps]]
index = 2
name = "Siding with Ceril"
links = ["Ceril Carnillean", "Clivet", "Alomone", "Hazeel", "sewer valve", "Carnillean armour", "drop trick", "cupboard (Hazeel Cult)"]
text = """
[[File:Hazeel Cult - Quest map.png|thumb|409x409px|Map Showing the Hazeel Cult Quest Legend:<br/>
1: Start quest, [[Ceril Carnillean]],
2: [[Clivet]],
3: [[Alomone]] (level 13),
A: Quest Area (Area to travel, from begin to end).
Green numbers indicate valve locations.]]
{{Needed|Weapon, armour and food}}
[[File:Butler Jones chathead.png|left|frameless]]
If you've chosen to side with Ceril, talk to [[Clivet]] in the cave to learn about [[Hazeel]], an ancient and powerful follower of Zamorak who was killed by an ancestor of Ceril. He will ask for your help in reviving Hazeel. '''Refuse'''.

Clivet will sail away on a raft, saying that you'll never be able to find him. Go back upstairs, find the [[sewer valve]]s, and turn them in the proper direction.

{{Checklist|
*'''Valve 1''' - This is right across the bridge south of the Carnilleans' house. Turn it <u>'''right'''</u>.
*'''Valve 2''' - This is right behind Carnilleans' house. Turn it <u>'''right'''</u>.
*'''Valve 3''' - This is north of the cave. Turn it <u>'''left'''</u>.
*'''Valve 4''' - This is south of the zoo's penguin cage. Turn it <u>'''right'''</u>.
*'''Valve 5''' - Go south-east of the fourth valve, past the monk. Turn it <u>'''right'''</u>.
}}
After you've turned all five, go back into the cave. Board the raft, then head to the southernmost room and talk to [[Alomone]]. He will let it slip that Ceril's butler is part of the cult, before attacking you. Kill him, then open the chest in the room to get the [[Carnillean armour]].

'''Note''': You can use the [[drop trick]] if you want your own armour.

Board the raft again in order to return to the sewer entrance. Back at the Carnilleans' house, talk to [[Ceril Carnillean]], who will take the armour from you and give you 5 coins. After the player accuses the butler, he will refuse to believe you.

'''You'll see a quest reward screen, but you haven't received the real reward yet!'''

{{Listen|filename=Oh Dear!.ogg|align=right|title=Congratulations! Quest complete!|desc=Or not...}}
[[File:Hazeel Cult partial completion reward scroll.png|frame|centre|The first (fake) "reward". Continue the next step to claim your real reward.]]

Search the [[cupboard (Hazeel Cult)|cupboard]] on the {{FloorNumber|uk=1}} and you will find the Mark of Hazeel and a bottle of poison. Show these to Ceril. He will fire Butler Jones and give you the ''real'' quest reward.
"""

[[steps]]
index = 3
name = "Siding with Hazeel"
links = ["Ceril Carnillean", "Clivet", "Alomone", "Hazeel", "Hazeel's mark", "Sewer valve", "Hazeel scroll", "Butler Jones", "crate (Hazeel Cult)", "Chest key (Hazeel Cult)"]
text = """
[[File:Hazeel Cult - Quest map.png|thumb|409px|Map Showing the Hazeel Cult Quest Legend:<br/>
1: Start quest, [[Ceril Carnillean]],
2: [[Clivet]],
3: [[Alomone]] (level 13),
A: Quest Area (Area to travel, from begin to end).
Green Numbers are marking valves.]]
[[File:Hazeel chathead.png|left|frameless]]
If you've chosen to side with [[Hazeel]], make sure you have a free inventory slot and then talk to [[Clivet]] to learn about [[Hazeel]]. He will explain that Hazeel is an ancient and powerful follower of Zamorak who was killed by an ancestor of Ceril. He will ask for your help in reviving Hazeel. '''Accept.'''

He wants you to prove your loyalty by killing Ceril. Ask him how, and he will give you some poison and instruct you to pour it in Ceril's food.

Head to the basement of Ceril's house, and use the bottle of poison on the range. Then, go upstairs and talk to Ceril Carnillean to learn that you've accidentally killed Scruffy the family dog instead; his son gave the meal to him.

Talk to Clivet again, and he will have heard about the accident, but takes it as proof of your loyalty regardless.  He'll give you [[Hazeel's mark]], then tell you to meet with their leader [[Alomone]] in their hideout. To get to the hideout, you need to find five [[Sewer valve]]s and turn them the proper direction.
{{Checklist|
*'''Valve 1''' - This is right across the bridge south of the Carnilleans' house. Turn it <u>'''right'''</u>.
*'''Valve 2''' - This is right behind Carnilleans' house. Turn it <u>'''right'''</u>.
*'''Valve 3''' - This is north of the cave. Turn it <u>'''left'''</u>.
*'''Valve 4''' - This is south of the zoo's penguin cage. Turn it <u>'''right'''</u>.
*'''Valve 5''' - Go south-east of the fourth valve, past the monk. Turn it <u>'''right'''</u>.
}}
[[File:Hazeel Cult - Hazeel revived.gif|thumb|200px|Hazeel emerges from his coffin.]]

Go back to the cave and board the raft. Once you're in the main hideout, talk to [[Alomone]]. He wants you to help the Carnillean's butler, an undercover cultist, retrieve a [[Hazeel scroll| magical scroll of restoration]] that is hidden in the Carnilleans' house.

Talk to [[Butler Jones]] in the house, who believes the scroll is hidden where even the family won't find it. Search the [[crate (Hazeel Cult)|crate]] in the basement for a [[Chest key (Hazeel Cult)|chest key]] (make sure to finish the dialogue to get the key in your inventory). Go up the ladder, then up the stairs and knock on the wall in the east room, on the northern side, then finally go up the ladder. Use the key on the chest to get the scroll. Return to Alomone to start Hazeel's resurrection.{{Clear}}
"""
