quest = "Making History"
step_count = 4

[[steps]]
index = 0
name = "Erin the silver merchant"
links = ["Spade", "Enchanted key", "Chest (Making History)", "The Enchanted Key"]
text = """
{{Needed|[[Spade]].}}
{{Map|2442,3139|mtype=square|r=4|align=right|width=250|height=250|caption=The location to dig for the chest.}}
''Note: Erin won't talk to you if you've recently stolen from his stall.''

Talk to Erin, the Silver merchant, in East Ardougne. He is at the north-western stall in the central market. He will tell you about his great grandfather, and that he has an [[Enchanted key]]. Ask him if you can borrow it and he will agree. The key changes temperature as you walk.

Travel to Castle Wars and cross both northern bridges, until you are around 4 steps north from the east side of the second bridge. As soon as you feel that the enchanted key is steaming, take out your spade and dig to find a [[Chest (Making History)|chest]]. Use the enchanted key to open it and you will find a Journal.

''Note: The enchanted key is used in [[The Enchanted Key]] miniquest to find and claim hidden treasures, but the miniquest cannot be started until this quest is complete. Depending on your stage of completion, Using the key will result in one of the following messages: "You have already found the chest", "You have already found the journal", or "You've already delivered the journal".
"""

[[steps]]
index = 1
name = "Droalak the ghost"
links = ["Ghostspeak amulet", "Sapphire amulet", "Ectophial", "Ghosts Ahoy", "Port Phasmatys", "ecto-token", "Charter ship", "Droalak", "Melina", "sapphire amulet"]
text = """
{{Needed|[[Ghostspeak amulet]], [[Sapphire amulet]].|recommended=[[Ectophial]] ''(If [[Ghosts Ahoy]] has been completed.)''}}{{Map|3659,3475,icon:bluePin,desc:Droalak|3673,3482,icon:redPin,desc:Melina|mtype=pin|caption=Locations of Droalak (blue) and Melina (red).|align=right|width=250|height=250}}

Travel to [[Port Phasmatys]]; if [[Ghosts Ahoy]] has not been completed, you must pay two [[ecto-token]]s to the town guards. (''Get ecto-tokens by heading to the Ectofuntus, just north of Port Phasmatys. Use the bones in the bone grinder on the second floor, get a bucket of slime from the trapdoor west of the fountain, and use those items on the fountain. Then, talk to a ghost disciple to claim your ecto-tokens.)'' The port can also be reached by [[Charter ship|Charter Ship]] to Port Phasmatys.

Once in Port Phasmatys, head to the general store. Then talk-to [[Droalak]] in, or around the general store. He will give the player a scroll if they give his wife, [[Melina]], a strung [[sapphire amulet]]. Melina is in the building directly east of the general store.

After giving Melina the amulet, the player must go back to Droalak to receive the scroll.
"""

[[steps]]
index = 2
name = "Dron the warrior"
links = ["Rellekka", "Blanin", "Dairy churn", "Skulgrimen's Battle Gear", "Dron"]
text = """
Travel to [[Rellekka]] and talk to Dron's brother [[Blanin]]. He can be found near the [[Dairy churn]], east of the Longhall.

Go north of [[Skulgrimen's Battle Gear]], and speak to [[Dron]]. He can be found close to the northern-most dock. He will quiz the player on the information that Blanin gave them. Dron will ask various questions; these are the answers (in the order used):

To get through the conversation quickly, the numbers you can press are: 3, 2, 2, 1, 2, 1, 2, 2, 1, 3, 3, 1, 1, 1.
*''I'm after important answers''
*''Why, you're the famous warrior Dron!''
*He wields an '''iron mace''' in battle.
*He eats '''rats''' for '''breakfast'''.
*He eats '''kittens '''for '''lunch'''.
*He eats '''bunnies''' for '''tea'''.
*His favourite drink is '''red '''spider blood.
*He is '''36 years,'''
*'''8 months''' (21 days) old.
*He studies the '''Fifth '''and''' Fourth '''ages.
*His house is on the '''north-east side''' of town.
*His brother's name is '''Blanin'''.
*His pet cat is named '''Fluffy'''.
*5 and 7 is '''12.'''
Dron will immediately end the conversation if a wrong answer is given.

After answering the questions, Dron will reveal part of the outpost's history that involves two friends battling each other at the Outpost. One sided with Zamorak, and the other sided with Saradomin. It's later learned that they both decided to stand down after observing the destruction of the battle, and chose to side with Guthix. As time went on, one became King of Ardougne and the other ran the Ardougne marketplace.
"""

[[steps]]
index = 3
name = "Back to Jorral"
links = ["Jorral", "East Ardougne", "King Lathas", "Ardougne Castle"]
text = """
Give everything to [[Jorral]]. He'll give the player a letter to take to the king of [[East Ardougne]]. [[King Lathas]] can be found upstairs in his [[Ardougne Castle|castle]] in central Ardougne just across the river. He will give back a letter to take to Jorral, in which he promises not to tear down the outpost. After taking it to Jorral, Jorral will make a museum out of the Outpost.

'''Congratulations, quest complete!'''
"""
