quest = "The Tourist Trap"
step_count = 5

[[steps]]
index = 0
name = "Missing daughter"
links = ["Desert Mining Camp", "Irena", "Shantay Pass", "Al Kharid", "shantay pass", "Shantay", "Ana", "desert heat", "waterskin", "armour", "desert clothing", "waterskins", "knife", "slash", "Mercenary Captain", "safespot", "Mercenary", "multicannon", "rings of recoil", "metal key"]
text = """
[[File:Irena chathead.png|left|frameless]]
[[File:The Tourist Trap - Talking to Irena.png|thumb|220px|right|Talking to Irena.]]
{{Map|3270,3029|zoom=1|width=220|height=220|align=right|mtype=pin|caption=The Mercenary Captain outside the [[Desert Mining Camp]] entrance.}}
Head to [[Irena]], found just through the [[Shantay Pass]] south of [[Al Kharid]]. You can pass through by buying a [[shantay pass]] from [[Shantay]] nearby. Talk to the distressed Irena and ask what's the matter, and she will explain that her daughter [[Ana]] has gone missing in the desert. She found some footprints that appear to lead to the [[Desert Mining Camp]].

In the desert, you will take around 10 damage from [[desert heat]] without access to a [[waterskin]]. Every 30-90 seconds you will use a charge from your waterskin, or take damage if you have none left. The interval depends on the [[armour]] worn.

'''Equip your [[desert clothing]] now''' to extend the intervals, and ensure you have 1-2 full [[waterskins]]. They can be refilled by cutting cacti found around the desert with a [[knife]] or [[slash]] weapon. Head south until you reach the mercenaries guarding the [[Desert Mining Camp]] gate (west side of the camp), and talk to the [[Mercenary Captain]].

:'''Note''': After concluding the following dialogue, you will need to defeat the captain. It is possible to [[safespot]] him by waiting to complete the dialogue until a [[Mercenary]] is nearby, then talking to the [[Mercenary]] to block his way before attacking him. A dwarf [[multicannon]] may also be set up west of the gate, just in the edge of his roaming area. He may be killed entirely with [[rings of recoil]] and the key will still drop. Non-ironmen players may stay on the final dialogue ''The guards gather around to watch the fight'' and wait while a friend kills the captain, then press continue right as the captain dies.

Say ''wow, a real captain!'', then say ''you'd love to work for him'', ask ''if you can do something for him'', and he will ask you to bring him the head of Al Zaba Bhasim, head of the desert bandits. '''Refuse''', then ''accuse him of being unable to fight his own battles''. {{Chat option|1Wow! A real captain!|2I'd love to work for a tough guy like you!|2Can't I do something for a strong Captain like you?|2Sorry Sir, I don't think I can do that.|1It's a funny captain who can't fight his own battles!}}

He will agree to a duel, and the guards will gather round. '''Complete the dialogue when you are ready to fight, if you attack him too early you will be teleported away, taking damage and losing your water.''' Once the captain attacks you, kill him and take his [[metal key]].
"""

[[steps]]
index = 1
name = "Getting into the mine"
links = ["bowl of water", "cell door key", "Prison door (Desert Mining Camp)", "Rock (The Tourist Trap)", "rowdy slave", "Tenti pineapple", "Bedabin Camp", "Desert Mining Camp", "Fairy ring", "Al Shabim", "Technical plans"]
text = """
[[File:Male slave (brown hair) chathead.png|left|frameless]]
Once you have the key, '''you must unequip everything except your desert clothing {{Color|red|before}} entering the camp.''' Ammunition is allowed.

:'''Note''': If you have weapons/armour equipped during the camp, you will be put in a cell. To escape, you must bend the bars in the window and climb out, climb the rocks then the cliff, then the rocks again. During this process you may be sent away from the camp and have your waterskins taken away. You can then return to the gate to enter again.

[[File:The Tourist Trap - Trading clothes.png|thumb|220px|Trading clothing with a slave keen to escape.]]

In the northern building, search the table with a [[bowl of water]] on it to receive a [[cell door key]]. You may use the [[bowl of water]] to refill your waterskins. The key can be used if you are caught in upcoming sections to escape via the [[Prison door (Desert Mining Camp)|prison door]], which will save you some time. Note that the guards may occasionally confiscate the keys from you.

Head to the east wall by the rocks and talk to the male slave, who says you look like a new recruit. When you ''tell him you've just arrived'', he mentions he is planning on a escape. ''Tell him that it sounds interesting'', and he will mention there is one missing detail from the plan. Ask ''what's that then'' and he says he can't get his bracelets off. Tell him ''you can try to undo them for him'', and he will mention making a trade. Say ''it's funny you should say that'' and the player will request his slave robes in return for your desert clothing. Keep trying until you break the bracelets off the slave and then agree to the trade. '''If a guard is close to you while you attempt to break off the bracelets, they will detain you in the cell and you will need to escape using the key (or through the window, see the earlier note).''' {{Chat option|1I've just arrived.|2Oh yes, that sounds interesting.|1What's that then?|1I can try to undo them for you.|1It's funny you should say that...|1Yeah, okay, let's give it a go.|1}}

:'''{{Colour|Red|Warning}}:''' While in the mine in the following sections, you must have your slave robes equipped at all times. If the guards spot you without the robes,  you will be jailed and forced to mine 15 [[Rock (The Tourist Trap)|rocks]] to be freed (though you may teleport out). If you are caught, you can logout during the dialogue to avoid being jailed (re-equip the slaves robes on relogging).

'''Wearing the slave robes,''' enter the mine and follow the winding path to the area just below where you entered (click to the south on the minimap). '''Don't''' talk to the [[rowdy slave]]s, or they attack you. Talk to a guard and ask to mine in a new area, and he will request a [[Tenti pineapple|'Tenti' pineapple]]. You will now need to visit the [[Bedabin Camp]] to the west of the [[Desert Mining Camp]]. Either exit the mine the way you came, '''unequipping your slaves robes {{Color|red|after}} leaving the mine''' or teleport out. [[Fairy ring]] {{Fairycode|BIQ}} is just north-east of the [[Bedabin Camp]].

:'''Note:''' If your gate key was confiscated and you do not have access to a teleport, you can get it back by searching the west table upstairs in the building.

{{Map|name=Al Shabim|caption=Location of Al Shabim in the Bedabin Camp.|x=3171|y=3029|width=200|height=200|align=left|r=4|mtype=square}}

Talk to [[Al Shabim]] in the southern circular tent of the [[Bedabin Camp]]. He will agree to give you the pineapple if you get some weapon [[Technical plans|plans]] for him, and gives you a key.
"""

[[steps]]
index = 2
name = "The plans"
links = ["prototype dart tip", "prototype dart", "Captain Siad", "bookcase (The Tourist Trap)", "Al Shabim", "Bedabin Camp", "anvil", "bronze bar", "Prototype dart tip", "feather", "Prototype dart", "Tenti pineapple"]
text = """
{{Needed|skills={{SCP|Smithing|20}} {{Boostable|yes}} to create a [[prototype dart tip]], and {{SCP|Fletching|10}} {{Boostable|yes}} to turn it into a [[prototype dart]]}}
[[File:The Tourist Trap - Making the prototype dart.png|thumb|220px|Making the prototype dart tip for Al Shabim.]]
Return to the Desert Mining Camp, entering '''without armour or weaponry equipped''', and go into the northern building. Climb up the ladder and you will find [[Captain Siad]]. Search the [[bookcase (The Tourist Trap)|south-west bookcase]] to learn he has an interest in sailing, then talk to him and ''ask to have a chat''. He will insist that you leave, but ignore him and tell him he ''seems to have a lot of books'', to which he will agree. Mention that he has an ''interest in sailing'' and he will say it's been a passion of his for some years. Tell him you ''could tell by the cut of his jib'' and he will be flattered and begin rambling, creating a distraction. {{Chat option|1I wanted to have a chat?|5You seem to have a lot of books!|3So, you're interested in sailing?|1I could tell by the cut of your jib.}}

Search the chest and steal the blueprints, then return to [[Al Shabim]] in the [[Bedabin Camp]], who will give you permission to use the [[anvil]] nearby. Enter the tent directly north of Al Shabim, near the magic carpets and use your [[bronze bar]] on the anvil to create a [[Prototype dart tip]] ({{SCP|Smithing|20}}). Then add the [[feather]]s to make a [[Prototype dart]] ({{SCP|Fletching|10}}). It is possible to fail both steps so make sure you have brought additional materials.  Take the dart and the technical plans back to Al Shabim and he will give you the [[Tenti pineapple|pineapple]] you need.
{{Clear|left}}
"""

[[steps]]
index = 3
name = "Finding Ana"
links = ["tenti pineapple", "Ana"]
text = """
[[File:Ana in a barrel detail.png|left|frameless|80px]]
[[File:Tourist Trap - Riding the mine cart.png|thumb|220px|Riding the mine cart. Enjoy the ride!]]
'''With your slave outfit equipped''', enter the mine and give the [[tenti pineapple]] to the guard who wanted it, who will allow you to enter the next section of the mine. Head east until you reach a mine cart, then '''search''' (not look in) a nearby barrel to take one. Once you have one, '''search''' the mine cart to get in, and the player will ride it to the other side. It is possible to fail and take 1-4 damage by banging your knee or falling off the edge of the minecart.

[[Ana]] can be found down the north-west path, at the very end. Use the barrel on her, then return to the mine cart.

{{Color|red|Warning:}} Do not drop the barrel while she is inside, and do not mention sneaking past the guards or the key if you choose to talk to her, else you will be thrown in jail.
{{Clear|left}}
"""

[[steps]]
index = 4
name = "Rescuing Ana"
links = ["Ana in a barrel", "winch bucket", "winch (The Tourist Trap)", "wooden cart (The Tourist Trap)", "mine cart driver", "Irena"]
text = """
[[File:Mine cart driver chathead.png|left|frameless]]
[[File:The Tourist Trap - Ana in a barrel in a mine cart.png|thumb|220px|Putting Ana on the cart.]]
Use [[Ana in a barrel]] on the mine cart to send her down the track. When the cart returns, get in. Once you reach the other side, '''search''' an empty barrel and you will retrieve [[Ana in a barrel]] again.

'''{{Colour|Red|Warning}}:''' '''Do not exit the mine''' the way you did before holding [[Ana in a barrel]], or you will need to repeat the previous section.

Use [[Ana in a barrel]] on the [[winch bucket]] to the north-west, and a guard will offer to help. Accept his help, then when he suspects that Ana said something, say you were just calling him ''very gregarious'' to throw him off.

:'''Note''': If this glitches and the guards are alerted, just relog and try again.

[[File:The Tourist Trap - Operating the crane.png|thumb|220px|Operating the crane with Ana in the barrel.]]

Return to the surface '''still wearing your slave robes''' to avoid being thrown in jail. Operate the [[winch (The Tourist Trap)|winch]] in the south-west corner of the camp, then search the nearby barrel to retrieve Ana. Put her in the wooden [[wooden cart (The Tourist Trap)|cart]] nearby.

{{Colour|Red|Warning}}: If you click the wrong dialogue options in the next section you will have to redo the majority of this quest!

Now, you need to talk to the [[mine cart driver]] and say the following dialogue before he will allow you to hide in the cart. {{Chat option|2Nice cart.|2One wagon wheel says to the other, 'I'll see you around'.|1'One good turn deserves another.'|3Fired... no, shot perhaps!|3In for a penny in for a pound.|3Well, you see, it's like this...|1Prison riot in ten minutes, get your cart out of here!|2You can't leave me here, I'll get killed!}}

*''"Nice cart."''
*''"One wagon wheel says to the other, 'I'll see you around'."''
*''"One good turn deserves another."''
*''"Fired... no, shot perhaps!"''
*''"In for a penny in for a pound."''
*''"Well, you see, it's like this..."''
*''"Prison riot in ten minutes, get your cart out of here!"'' (You could also choose to bribe the driver instead for 100 coins)
*''"You can't leave me here, I'll get killed!"''

Once he has agreed to help you, search the cart and choose the option to get on it.

Head back to [[Irena]], and she'll reward you for all your hard work.

'''Congratulations, quest complete!'''
{{Clear}}
"""
