quest = "Temple of the Eye"
step_count = 5

[[steps]]
index = 0
name = "An Eye for a Favour"
links = ["Wizard Persten", "Al Kharid", "Abyss", "Zamorak Magical Institute", "eye amulet", "Asgarnia Smith", "Ruins of Uzer", "Order of Wizards", "Wizards' Tower"]
text = """
{{Needed|1 free inventory slot|recommended=Varrock Teleport}}
[[File:Wizard Persten chathead.png|left]]
Talk to [[Wizard Persten]] just north of the pool of water/gnome glider in [[Al Kharid]]. Ask her what she is doing in Al Kharid, and she will tell you she came here to buy something. She will ask you about the [[Abyss]], and you will tell her that you helped the [[Zamorak Magical Institute]] gain access to the rune essence mine, much to her dismay. Regardless, she will ask you if you want to help her with a task; agree to help her to start the quest.

She will show you an [[eye amulet]] that she purchased for 100 coins from [[Asgarnia Smith]], who found it washed up near the [[Ruins of Uzer]] and sold it to her, believing it to be junk. In reality, the amulet bears the symbol of the [[Order of Wizards]] of the [[Wizards' Tower]] and contains two distinct magical signatures: one of rune essence and one of the Abyss.

She asks that you find out the origin of the amulet by tracing the Abyssal energy that it contains. However, the spell needed to trace the amulet will only work properly when inside the Abyss. You will need to contact someone within the [[Zamorak Magical Institute|Z.M.I.]] to assist you, though she'll ask you not to disclose how you acquired the amulet.
"""

[[steps]]
index = 1
name = "Herbert and the Dark Mage"
links = ["Mage of Zamorak", "Chaos altar (Prayer)", "Varrock", "bucket of water", "strong cup of tea", "Tea Seller", "Dark Mage (Abyss)", "Abyssal incantation"]
text = """
{{Needed|Eye Amulet (Obtained during the quest), a Bucket of Water, 1 free inventory slot|recommended=ring of dueling or Lumbridge Teleport}}
[[File:Mage of Zamorak chathead.png|left]]
Head to the [[Mage of Zamorak]] in the [[Chaos altar (Prayer)#Varrock|Zamorakian chaos altar]] in south-eastern [[Varrock]]. Use the eye amulet on him, and he'll cast an appraisal spell on it. He'll admit that the amulet is indeed unusual, but requests that you bring him a [[bucket of water]] and a [[strong cup of tea]], which can be acquired from the [[Tea Seller]] at the eastern entrance to Varrock.

Talk to the Tea Seller and ask for a strong cup of tea. You will tell him the mage, whose real name is Herbert, asked you to bring him one. In reality, they are just regular cups of tea, and he gives one to you. Return to Herbert with the bucket of water, and use the strong cup of tea on him to continue.

[[File:Temple of the Eye - tracing spell.png|thumb|280px|Runic energies emerge from the rift.]]
You will be prompted to teleport to the centre of the Abyss, and Herbert will tell you that the bucket of water is for the [[Dark Mage (Abyss)|Dark Mage]] maintaining the rift, who needs a bath. He will offer you a one-time teleport to the centre of the Abyss. Upon arriving to the Abyss, use the eye amulet on the Dark Mage and you will automatically give him a wash by soaking him with water. He will then cast a spell to triangulate the origins of the amulet, using the rift to compare energy from that origin with energy from the runic altars.

For his tracing spell to work, you will need to help him work out what order the runic energy from the Abyssal rift goes in. This is randomised for each player; click each rune type until all turn white in order to determine your order (document as you go). You have to return to each energy as you get the order, so for instance the one will turn white, try another energy. If it does not turn white, return to the first one that turned white, once you get that second white that too will need to stay white to move on to the next colour. (for example; if you get Law Energy first, that must stay white, if you try earth and it doesn't turn white you will have to go back to Law Energy before proceeding).

After working out the order, he will give you an [[Abyssal incantation]]. Reading the incantation provides the message "You don't understand the incantation. It needs the knowledge of a wizard."
"""

[[steps]]
index = 2
name = "Help from Some Wizards"
links = ["Archmage Sedridor", "Wizards' Tower", "Wizard Traiborn", "Apprentice Cordelia", "Apprentice Felix", "Apprentice Tamara"]
text = """
Return to Wizard Persten in Al Kharid (exiting the Abyss through the fire rift will bring you north of Al Kharid, just next to the Wizard). She will cast a spell to disable a magical feed the Z.M.I placed on the spell and redirect it to give them false information. She will then tell you to head to [[Archmage Sedridor]] for assistance in opening up wherever the amulet would lead to, and offers you a one-time teleport directly to the [[Wizards' Tower]]. Sedridor can be found in the basement; use the abyssal incantation on him. While skeptical due to the Z.M.I being involved, he casts a spell to ensure that the amulet and incantation is safe. In the meantime, he asks you to speak to [[Wizard Traiborn]], on the {{FloorNumber|uk=1}} of the tower.

Speak to Wizard Traiborn, and ask him for his three wizard apprentices to help you with the incantation. But first, he will ask you to help his apprentices solve a puzzle he gave them. Speak with all three to receive their parts of the puzzle:
{| class="wikitable" style="text-align:center;"
!Wizard
!First sentence
!Second sentence
|-
|[[Apprentice Cordelia|Cordelia]]
|Fire is four and Body is seven.
|A thingummywut is less than three Water and more than three Air.
|-
|[[Apprentice Felix|Felix]]
|Water is six and Mind is eight.
|A thingummywut is less than two Body and more than two Earth.
|-
|[[Apprentice Tamara|Tamara]]
|Earth is five and Air is three.
|A thingummywut is less than three Fire and more than one Mind.
|}

Using the clues given, the answer to the puzzle would be 11. Give this answer to Traiborn.
"""

[[steps]]
index = 3
name = "Enter the Gate"
links = ["Portal (Wizards' Tower)", "Stone of Jas", "Justiciar Zachariah", "Justiciar Aliya", "Jas", "Abyssal Rift (The Scar)"]
text = """
[[File:Temple of the Eye - arriving at the Temple of the Eye.png|thumb|280px|Persten and Traiborn's apprentices arrive at an ancient underwater temple.]]
Return to the basement and speak to Sedridor. He will confirm that both the incantation and amulet are safe, and will reluctantly agree to help you. A cutscene will play in which Traiborn's apprentices and Persten cast the incantation. A [[Portal (Wizards' Tower)|portal]] will open, and you will enter it with them, arriving at what appears to be an underground Saradominist temple.

Tamara will cast a locator spell, and finds that they are south of Morytania, deep below the sea. Explore the temple and speak to all the apprentices, who make various discoveries about the temple. Afterwards, speak to Persten, who examines the markings and tells you that they radiate magical energy she's never encountered before.

You will then experience a vision of a [[Stone of Jas|Mysterious Stone]], alongside two voices: those of [[Justiciar Zachariah]] and [[Justiciar Aliya]], who discuss guarding the Stone, which they refer to as the Eye. You will randomly proclaim [[Jas]], much to Persten's confusion.

Upon learning of what the apprentices have discovered, Persten concludes that the wizards of the temple used the power of the Abyss and the Eye to create portals to the runic altars. She will then cast a spell in an attempt to reveal additional secrets of the Temple, only for an [[Abyssal Rift (The Scar)|abyssal rift]] to open and suck her inside, with warped abyssal creatures emerging from it. Cordelia will cast a spell to kill the creatures.

<gallery captionalign="center" widths="200">
Temple of the Eye - vision of the Mysterious Stone.png|Experiencing a vision of the distant past.
Temple of the Eye - the wizards convene.png|Persten and Traiborn's apprentices discuss their discoveries.
Temple of the Eye - Persten disappears.png|Persten accidentally opens a rift, and disappears.
Temple of the Eye - Cordelia attacks.png|Abyssal creatures begin appearing, and Cordelia casts a powerful spell to kill them.
</gallery>
"""

[[steps]]
index = 4
name = "Guardians of the Rift"
links = ["The Great Guardian", "Guardians of the Rift", "weak cell", "Stone of Jas", "Betrayal of Zaros", "Zaros", "Battle for the Eye", "the Scar"]
text = """
{{Needed|Chisel (Obtainable during the quest), Pickaxe (Obtainable during the quest)}}''Be aware that dropping items on the ground during the tutorial is risky; when going to the runecrafting altars, the instance is refreshed and items dropped are permanently lost''[[File:The Great Guardian chathead.png|left]]
[[The Great Guardian]] will appear in the centre, and asks that you assist it in closing the rift. This part of the quest serves as a tutorial for the [[Guardians of the Rift]] minigame.

Speak to Felix and take a [[weak cell]] from the eastern table. Bring it to Tamara, then place it in the inactive cell tile near her to create a barrier.

Return to Felix, and take a chisel from the table and assemble the essence piles into rune guardians. Afterward, speak to Tamara again, who will ask you to collect guardian fragments and assemble them into essence.
[[File:Temple of the Eye - The Great Guardian.png|thumb|280px|The Great Guardian explains the origins of the Temple.]]
Once the Great Guardian has enough energy to close the rift, a cutscene will play. After closing the rift, the Great Guardian explains to you and the group that the temple was a place to hold the [[Stone of Jas]] and following the [[Betrayal of Zaros]], the servants of [[Zaros]] tried to claim it for themselves during the [[Battle for the Eye]]. As the Eye is no longer in the temple, the rift will eventually return and thus will need the humans' help in closing it. The three apprentices will choose to stay and help the Great Guardian, feeling a need to atone for the mistake. It also presumes that Persten is dead as she has fallen into [[the Scar]], the most dangerous place in the Abyss. The apprentices will then tell you to inform Sedridor of the development.

Leave through the portal and inform Sedridor that the so-called teleportation matrix was instead a rift to the Abyss that Persten had accidentally re-opened and that abyssal creatures spewed out. Sedridor will lament that he had forsaken his own principles due to his reluctance in following Persten's idea. He promises to give Traiborn's apprentices all the help they need in defending the place and research a way to close the rift as they have work to do.

'''Congratulations, quest complete!'''
"""
