quest = "My Arm's Big Adventure"
step_count = 4

[[steps]]
index = 0
name = "Starting the adventure"
links = ["Bucket", "Death Plateau (location)", "Burntmeat", "goutweed", "dragon platelegs", "Troll Stronghold (location)", "Troll kitchen", "adventurer", "human", "cutscene", "Adventurer", "My Arm", "goutweedy lump", "cooking pot (My Arm's Big Adventure)", "games necklace", "Protect from Missiles", "rock thrower", "Protect from Melee", "bucket", "farming manual"]
text = """
{{Needed|[[Bucket]] (can be found next to the cooking pot at [[Death Plateau (location)|Death Plateau]]),
1 free inventory space|recommended=}}
[[File:My Arm's Big Adventure kitchen cutscene.png|thumb|250px|[[Burntmeat]] discovers [[goutweed]] underneath the [[dragon platelegs]].]]
To start the quest, travel to the [[Troll Stronghold (location)|Troll Stronghold]] and speak to [[Burntmeat]]. He is found in the [[Troll kitchen]], go south after going down the stairs. He has heard from another [[adventurer]] that [[human]]s can grow [[goutweed]] and wonders if you can help. You will see a short [[cutscene]] with this adventurer in a cooking pot, with his [[Adventurer|equipment]] strewn over the floor. Burntmeat wants his assistant, [[My Arm]], to learn how to farm.

My Arm is at the back of the room; talk to him, and he will tell you he needs the [[goutweedy lump]] from the [[cooking pot (My Arm's Big Adventure)|cooking pot]] on [[Death Plateau (location)|Death Plateau]]. Either talk to Burntmeat and follow his instructions to get to the Death Plateau or travel there via other means such as the [[games necklace]].

When near [[Death Plateau (location)|Death Plateau]], it is advisable to activate [[Protect from Missiles]] against the [[rock thrower]]s and [[Protect from Melee]] while on the plateau. There, use a [[bucket]] on the cooking pot to get the [[goutweedy lump]]. There is a [[bucket]] spawn in a nearby hut if you forgot one.

Return to the [[Troll Stronghold (location)|Troll Stronghold]] and talk to [[My Arm]] again, who will promptly eat the goutweed. He will then guide you to his farm on the roof of the stronghold to show you what he had tried to grow. Speak with him there, and he will give you a [[farming manual]] that he asks you to read.
"""

[[steps]]
index = 1
name = "Fertiliser"
links = ["Ugthanki dung", "bucket", "red hot sauce", "Camulet", "supercompost", "spade", "camulet", "Pollnivneach", "Ali the Kebab seller", "Ali the Camel Man", "Al Kharid", "Al the Camel"]
text = """
{{Needed|Three buckets of [[Ugthanki dung]] (obtainable with three empty [[bucket]]s and either [[red hot sauce]] or the [[Camulet]]), seven [[supercompost]], and a [[spade]].}}
You now need to get the fertiliser for the goutweed: three [[bucket]]s of [[Ugthanki dung]] and seven [[supercompost]]. There are two ways to obtain [[Ugthanki dung]]; using [[red hot sauce]] or the [[Camulet]].

If you do not have the [[camulet]], go to [[Pollnivneach]] and talk to [[Ali the Kebab seller|Ali/Isma'il the Kebab Seller]]. Ask him for his [[red hot sauce]]. Then, head to [[Ali the Camel Man|Ali/Sami the Camel Man's]] store and use the red hot sauce on the trough. A camel nearby should eat it and produce dung. Use the empty buckets on the dung; picking it up will result in a humorous message.

If you do have the camulet, go to [[Al Kharid]] and ask a camel there (such as [[Al the Camel]]) to spare you a little dung. The camel may or may not agree to the request, so simply keep doing so until they agree to.

Once the camel dung is obtained, head back to the patch with a [[spade]] and seven [[supercompost]](Bottomless compost bucket will not work!). Use them all on the patch My Arm made. With the patch set, now you just need the herb.
"""

[[steps]]
index = 2
name = "Karamja"
links = ["Machete", "Tai Bwo Wannai Cleanup", "My Arm", "Karamja", "Tai Bwo Wannai", "cutscene", "Ardougne", "Brimhaven", "Jiminua's Jungle Store", "Murcaily", "hardy gout tuber", "hardy gout tubers", "Qutiedoll", "broodoo victim", "Jagbakoba"]
text = """
{{Needed|[[Machete]] (only if you lack 60% favour in [[Tai Bwo Wannai Cleanup]])}}
[[File:My Arm's Big Adventure boat journey.png|thumb|250px|The player and [[My Arm]] heading to [[Karamja]].]]
Having fertilised the patch, talk to My Arm again. He will want to venture with you to [[Tai Bwo Wannai]], as goutweed supposedly originates from there. You'll see a short [[cutscene]] on the docks of [[Ardougne]], followed by a scene on the ship. Once you arrive at [[Brimhaven]], My Arm will have already run off towards Tai Bwo Wannai. You can find him just east of [[Jiminua's Jungle Store]]. Talk to him there.

With at least 60% favour talk to [[Murcaily]]. Note that doing this will subtract this percentage from your total favour, so you may first want to reach 100% for the diary. Murcaily will initially give you a single [[hardy gout tuber]]. Then, a cutscene will follow in which My Arm causes havoc around the village in search of the tubers, and Murcaily will give you lots of [[hardy gout tubers]]. You will then return to [[Ardougne]].


During the cutscene, the inventory may automatically rearrange into a different order. Ultimate Ironmen should be aware of this.

<gallery>
My Arm's Big Adventure jungle rumble.png|My Arm harasses [[Qutiedoll]] in his quest for Goutweed.
My Arm's Big Adventure jungle rumble 2.png|My Arm knocks away a [[broodoo victim]].
My Arm's Big Adventure jungle rumble 3.png|My Arm defeats the village's strongest warrior, [[Jagbakoba]], with a hefty punch.
</gallery>
"""

[[steps]]
index = 3
name = "The Rocs"
links = ["hardy gout tubers", "rake", "seed dibber", "spade", "plant cure", "supercompost", "Tool Leprechaun (Larry)", "armour", "weaponry", "food", "Troll Stronghold (location)", "My Arm", "Rake", "Seed dibber", "Supercompost", "Drunken Dwarf", "Drunken dwarf's leg", "goutweed", "Baby Roc", "Giant Roc", "Melee", "Ranged", "Protect from Missiles", "Magic", "inventory", "Burnt food"]
text = """
{{Needed|Combat equipment, the [[hardy gout tubers]], and 69 coins or a [[rake]], [[seed dibber]], [[spade]] and either [[plant cure]] or [[supercompost]]}}
{{Instance}}
Speak with My Arm again - he suggests you go back to the bank to get some food because of some "large birds" on top of the mountain. You will need to bring the required farming tools or ensure your [[Tool Leprechaun (Larry)|tool leprechaun]] has them. You should also bring decent [[armour]], [[weaponry]] and [[food]]. Magic combat gear is recommended.

Go back to the top of the [[Troll Stronghold (location)|Troll Stronghold]] where [[My Arm]] is. You can retrieve or purchase the tools from the nearby [[Tool Leprechaun (Larry)|tool leprechaun]] nearby.

You'll need to give My Arm the materials to plant his tubers, as if you were planting them yourself. Give him the tools in the following order;
#[[Rake]] (this may break - simply retrieve the head and combine it with the handle, then hand it back to My Arm)
#The [[hardy gout tubers]]
#[[Seed dibber]]
#[[Supercompost]] before it fully grows, or [[plant cure]] after it becomes diseased ( there is a chance for the plant to become diseased in the cutscene with the drunken dwarf so have a plant cure stored in the leprechaun just in case)

When the goutweed is planted in step #3, the [[Drunken Dwarf]] will appear before getting unceremoniously thrown off the roof of the stronghold by My Arm, and then eaten by an [[Drunken dwarf's leg|unnamed troll child]].
<gallery>
My Arm's Big Adventure farming.png|[[My Arm]] planting the [[hardy gout tubers]].
Drunken dwarf punched off troll stronghold.png|My Arm attacks the [[Drunken Dwarf]], hurling him off the roof.
My Arm's Big Adventure unnamed troll child.png|An [[Drunken dwarf's leg|unnamed troll child]], soon to earn his name.
</gallery>
After the [[goutweed]] finishes growing, a bird will swoop down and attack the goutweed - it is only a level 75 [[Baby Roc]] and defeating it should be fairly easy.
[[File:Fighting Giant Roc.png|thumb|250px|An ideal spot to fight the [[Giant Roc]]. Note that you can still get hurt by the wing blasts and ranged attacks.]]
[[File:Giant Roc flinching.png|thumb|width=252x252|Possible flinching spot for the Giant Roc fight. First leave and return via the ladder to drag the Roc around the parasol, then run to this location to begin flinching.]]
However, this will anger a far more dangerous level 172 [[Giant Roc]], who will immediately attack you. It uses both [[Melee]] and [[Ranged]] attacks. The melee attack will also force you backwards unless your back is against a rock or wall. Its ranged attacks may be dodged, although this requires precise timing. It is recommended to fight with [[Protect from Missiles]] activated and eat when required. The Giant Roc is more resistant to Ranged or Melee damage compared to Magic damage as shown by the respective defence roll formulas: <math>(100\\text{ Defence Level} + 9) \\times (0 + 64) = 6976</math> for melee/ranged (the Giant Roc has 0 defence bonuses for all melee styles and ranged) vs <math>(1\\text{ Magic Level} + 9) \\times (150 \\text{ Magic defence bonus} + 64) = 2140</math>. With its lower defence roll against magic, it is advised to use [[Magic]] to damage it.  My Arm will also attack the bird, but his attacks only tend to hit 1 to 3, so don't rely on this.

Once it has been defeated, talk to My Arm again. You will now need to give him a [[spade]] to dig up the [[goutweed]]. If you forgot the spade, climb down the ladder and back up for the leprechaun to reappear. My Arm will then tell you to speak with Burntmeat for your great reward - you guessed it, a full [[inventory]] of [[Burnt food|burnt meat]]!

Talk to My Arm one last time to complete the quest. He will offer you some better rewards.

'''Congratulations, quest complete!'''
"""
