quest = "What Lies Below"
step_count = 8

[[steps]]
index = 0
name = "Rat Burgiss"
links = ["Rat Burgiss", "Varrock", "Lumbridge", "outlaw", "Rat's paper", "an empty folder", "Edgeville", "Grand Exchange", "Skills necklace", "Ring of wealth", "Outlaw Camp", "full folder", "Letter to Surok", "Surok Magis", "Varrock Palace Library", "VPSG code", "clay", "gold bar", "bowl", "infused wand", "Sin'keth's diary", "Wand (What Lies Below)", "Dagon'hai History", "Historian Minas"]
text = """
{{Map|name=Rat Burgiss|3266,3333|r=3|mtype=square|align=right|width=250|height=250|caption=Rat Burgiss's location.}}
Speak to [[Rat Burgiss]] on the crossroads between [[Varrock]] and [[Lumbridge]]. He tells you that a bunch of [[outlaw]]s have ransacked his trading cart and that he needs you to get back the [[Rat's paper|five papers]] they stole from him. He will give you [[an empty folder]] to keep them in.

{{Map|3122,3473|align=left|width=200|height=200|rectX=16|rectY=11|mtype=rectangle|caption=The outlaws' campsite.}}
The outlaws are located between [[Edgeville]] and the [[Grand Exchange]]. You can use a [[Skills necklace]] or [[Ring of wealth]] to travel towards them. Once at the [[Outlaw Camp|camp]], kill five [[outlaw]]s (level 32) to retrieve five of [[Rat's paper]]s, and then use them on the folder to get a [[full folder]].

[[File:What Lies Below - fighting outlaws.png|thumb|250px|Fighting the outlaws in their camp.]]
Return to Rat with the folder; he will then ask you to deliver a [[Letter to Surok|letter]] to [[Surok Magis]] in the [[Varrock Palace Library]]. Though written in a [[VPSG code|hard to read font]], the message is in English.

Head to the library, on the north side of the {{FloorNumber|uk=0}} of the castle, and speak to Surok Magis. He will destroy the letter and tell you that he can turn plain [[clay]] into [[gold bar]]s! He will need two items, an ordinary [[bowl]] and an [[infused wand]]. He gives you [[Sin'keth's diary]] and a [[Wand (What Lies Below)|wand]] to be infused with chaos.

'''Note:''' Despite what he says, you do not need a chaos talisman or tiara to infuse the wand if using a different method to access the altar.

'''Note:''' If you want to get kudos from the Varrock museum you'll need to get the book [[Dagon'hai History]]. You'll find it in one of the two bookcases farthest east. After the quest you can give the book to the [[Historian Minas]] on the {{FloorNumber|uk=1}} of the Varrock museum.
"""

[[steps]]
index = 1
name = "Chaos Altar"
links = ["Wand (What Lies Below)", "chaos rune", "chaos talisman", "chaos tiara", "Varrock teleport", "Abyss"]
text = """
{{Needed|[[Wand (What Lies Below)|Wand]], 15 [[chaos rune]]s, and a [[chaos talisman]]/[[chaos tiara|tiara]]|recommended=A method of [[Varrock teleport]] to quickly return from the altar.}}
Entering the chaos altar with either a [[chaos talisman]] or [[chaos tiara|tiara]], or access to the [[Abyss]]. There are four ways to reach the altar:
"""

[[steps]]
index = 2
name = "=Option 1="
links = ["Chaos talisman", "Chaos tiara", "Sin'keth's diary", "Varrock", "Lumberyard", "Earth Altar", "Statue (Tunnel of Chaos)", "Anna Jones", "bronze pickaxe", "Tunnel of Chaos", "Dagon'hai", "Chaos Altar"]
text = """
{{Needed|[[Chaos talisman]] or [[Chaos tiara|tiara]]}}

Following this option avoids the Wilderness entirely but requires 42 mining. Read the [[Sin'keth's diary]], and then go east of [[Varrock]]. Go south-west of the [[Lumberyard]] and west of the [[Earth Altar]]. You should find a [[Statue (Tunnel of Chaos)|statue of Saradomin]]. Talk to [[Anna Jones]], and she will give you a [[bronze pickaxe]]. You must use a bronze pickaxe to excavate the statue (requires 42 mining) to reveal the [[Tunnel of Chaos]] entrance. Enter the tunnel, and you will find that the [[Dagon'hai]] organisation lives there. Head north until you reach a portal. The portal leads to the second level of the Chaos Maze. Climb down a ladder to reach the [[Chaos Altar]].
"""

[[steps]]
index = 3
name = "=Option 2="
links = ["Chaos talisman", "Chaos tiara", "Wilderness", "Chaos Altar"]
text = """
{{Needed|[[Chaos talisman]] or [[Chaos tiara|tiara]]}}
Travel through the Wilderness ([[Wilderness#Wilderness levels|level 10]]). Head to the [[Chaos Altar]] entrance. Once inside, make your way through the maze to the Chaos Altar.
[[File:Infusing wand.gif|thumb|150px|Infusing the wand.]]
"""

[[steps]]
index = 4
name = "=Option 3="
links = ["Chaos Altar", "Enter the Abyss", "miniquest", "Mage of Zamorak", "Edgeville", "Skull (status)", "Abyssal walker"]
text = """
Use the Abyss to travel to the [[Chaos Altar]], which requires completion of the [[Enter the Abyss]] [[miniquest]]. Teleport via the [[Mage of Zamorak]] north of [[Edgeville]] to reach the Abyss. Your prayer will be drained and you will be [[Skull (status)|skulled]]. Make your way past [[Abyssal walker]]s (level 81) into the inner circle, from where you can teleport to the altar.
"""

[[steps]]
index = 5
name = "=Option 4="
links = ["Chaos Altar", "Guardian of Chaos", "Temple of the Eye (location)", "Temple of the Eye", "Guardians of the Rift", "Portal talisman (chaos)", "Minigame Teleport", "necklace of passage"]
text = """
This option avoids the wilderness. Travel to the [[Chaos Altar]] by entering the [[Guardian of Chaos]] at the [[Temple of the Eye (location)|Temple of the Eye]], which requires completion of the [[Temple of the Eye]] quest. To do this, join a game of [[Guardians of the Rift]] and wait for the Guardian of Chaos to be active, or use a [[Portal talisman (chaos)|Portal Talisman (Chaos)]] to access the Chaos Altar when the Guardian is inactive. This will teleport you close to the altar. To leave, go back through the portal and pass through the barrier at the entrance to Guardians of the Rift.

To reach the Temple of the Eye, use the [[Minigame Teleport]] for Guardians of the Rift. Alternatively, use a [[necklace of passage]] to teleport to the Wizards' Tower and enter the portal in the basement.
"""

[[steps]]
index = 6
name = "=Wand="
links = ["Wand (What Lies Below)", "chaos rune", "Infused wand", "Varrock", "Surok Magis", "Surok's letter", "Rat Burgiss", "King Roald"]
text = """
When you have reached the Chaos Altar, you must ''use'' your [[Wand (What Lies Below)|wand]] on the altar. This will absorb the 15 [[chaos rune]]s to turn the wand into the [[Infused wand]]. Return to the library of [[Varrock]], and talk to [[Surok Magis]] with the infused wand and an empty bowl. He will then give you [[Surok's letter]] for [[Rat Burgiss]].

'''Note:''' If you take Surok's letter to show [[King Roald]] before Rat Burgiss, you will learn about his guards' skills.
"""

[[steps]]
index = 7
name = "Ending"
links = ["Rat Burgiss", "Surok's letter", "Varrock Palace Secret Guard", "Surok Magis", "Misthalin", "King Roald", "Zaff", "Zaff's Superior Staffs!", "Varrock", "beacon ring", "Zaff's instructions", "Dagon'hai", "Battlestaff", "Varrock Diary", "One-defence pure", "Defence"]
text = """
Head back to [[Rat Burgiss]], and deliver the [[Surok's letter|letter]]. You will need to return to Varrock shortly, so restock on teleport supplies if necessary. Rat Burgiss will explain to you that he is actually the commander of [[Varrock Palace Secret Guard]] and that [[Surok Magis]] is planning on taking over the Kingdom of [[Misthalin]] by using a mind-control spell on [[King Roald]], and that you accidentally helped him with that. Rat Burgiss will direct you to [[Zaff]], owner of the [[Zaff's Superior Staffs!|staff shop]] in [[Varrock]], in order to prepare a spell to counteract Surok's.

Talk to Zaff, who will explain his plan to you. Zaff will give you a [[beacon ring]] and [[Zaff's instructions|instructions]] on how to arrest Surok Magis. You do not need to equip the ring.

Get your gear ready for a fight. Head to Surok Magis (who is now wearing [[Dagon'hai]] robes), and talk to him. He will cast his mind-control spell on [[King Roald]] (level 47), who you will have to fight. When the King has low health, your character will say that ''"Now would be a good time to summon Zaff!"''. Now you can ''operate'' the Beacon ring to summon Zaff.

Zaff will arrive and saves King Roald by teleporting him away. Then he casts a spell on Surok Magis that permanently seals him in the library. Zaff then casts another spell and the library goes dark. When the light comes back, evidence of the battle is cleaned up and Zaff is gone. '''After this occurs, you will be able to purchase [[Battlestaff|battlestaves]] from [[Zaff's Superior Staffs!|Zaff's Superior Staffs]], in addition to the discounted battlestaves from the [[Varrock Diary]].'''

<gallery>
What Lies Below - Fighting King Roald.png|The player fights King Roald.
What Lies Below - King Roald restored.png|Zaff casts a spell upon his arrival, restoring the King's mind.
What Lies Below - Surok teleblocked.png|Surok attempts to escape, and is stopped by Zaff.
</gallery>

Return to [[Rat Burgiss]] to finish the quest.

'''Note:''' If you are a [[One-defence pure|1 defence pure]], it is advised not to skip through the dialogue when speaking to Rat, as [[Defence]] experience would be gained if you proceed to complete the quest. The player is given a dialogue warning before receiving the experience. Simply decline the option, leaving the quest incomplete, if you would prefer not to get the XP.

'''Congratulations, quest complete!'''
{{clear}}
"""
