quest = "Below Ice Mountain"
step_count = 5

[[steps]]
index = 0
name = "Willow the 'archaeologist'"
links = ["Willow (Below Ice Mountain)", "Dwarven Mine", "Ice Mountain", "Burntof", "Checkal", "Marley"]
text = """
[[File:Willow (Below Ice Mountain) chathead.png|left]]
Speak to [[Willow (Below Ice Mountain)|Willow]], north-east of Falador and south of the [[Dwarven Mine]] entrance by [[Ice Mountain]]. A self-proclaimed 'archaeologist', she will tell the player that she has found a set of doors beneath a tonne of rocks, and asks for their help, as she cannot leave the area in fear of another 'archaeologist' claiming the credit for her discovery.

Agree to help Willow, and she'll need you to convince her old 'excavation team' to help her, since they had a falling out with Willow. Her mates, [[Burntof]], [[Checkal]] and [[Marley]], can be spoken to in any order.
"""

[[steps]]
index = 1
name = "Checkal the strongman"
links = ["Checkal", "Barbarian Village", "Atlas", "The Long Hall", "Flex", "beer", "meat"]
text = """
[[File:Below Ice Mountain workout scene.png|thumb|right|The trials of the strongman.]]
[[File:Checkal chathead.png|left]]
[[Checkal]]  can be found in the centre of [[Barbarian Village]]. In order to get him to join Willow, the player must prove their strength by training with his old friend [[Atlas]], who can be found in [[The Long Hall]] tavern in Barbarian Village.

Speak to Checkal. He will refer the player to Atlas, who will agree to train them. A long cutscene of training regimens will ensue, which afterward will unlock the [[Flex]] emote. Before returning to Checkal, grab a [[beer]] and [[meat]] from the table if you have not obtained it already.

Return to Checkal and use the Flex emote when prompted, and he will agree to help Willow.
"""

[[steps]]
index = 2
name = "Burntof, master of explosives"
links = ["coins", "beer", "Burntof", "Rising Sun Inn", "Falador"]
text = """
{{Needed|3 [[coins]] or a [[beer]]}}
[[File:Burntof chathead.png|left]]
[[Burntof]] can be found in the [[Rising Sun Inn]] in [[Falador]]. Drunk as he is, he will ask the player for a drink. If you have not already picked up the beer from Barbarian Village, purchase one from the bartender and give it to Burntof.

Burntof will agree to join the team if the player manages to beat him in a best-of-three game of rock paper scissors. Regardless of what is chosen, Burntof will agree to help Willow as he is too drunk to properly play the game.

{{clear|left}}
"""

[[steps]]
index = 3
name = "Marley the thief"
links = ["knife", "cooked meat", "bread", "Charlie the Tramp", "Marley", "Edgeville", "steak sandwich", "Blue Moon Inn", "Cook (Blue Moon Inn)", "Varrock"]
text = """
{{Needed|[[knife]], [[cooked meat]] and [[bread]]}}
[[File:Marley chathead.png|left]]
Though Willow instructs the player to speak to [[Charlie the Tramp]] to find Marley's whereabouts, you can skip this conversation and directly reach [[Marley]] in the [[Edgeville]] ruins, by the yew trees south of Edgeville bank.

He will want a [[steak sandwich]] from the [[Blue Moon Inn]] in order to help Willow. However, he was banned from the inn and the cook won't make him another one. Thus, the player must go to the inn in his place.

Speak to the [[Cook (Blue Moon Inn)|cook]] in the east room of Blue Moon Inn in [[Varrock]]. Though he will still refuse to make a steak sandwich due to Marley trying to steal from one of their patrons, he will tell the player the 'delicate art' of creating a steak sandwich: using a [[knife]] on [[bread]] while having [[cooked meat]] in your inventory.

With the steak sandwich beautifully and masterfully created, return to Marley with it in your inventory. He will now agree to help Willow.
"""

[[steps]]
index = 4
name = "The Ruins of Camdozaal"
links = ["pickaxe", "weapon", "armour", "Blocked entry", "Ice Mountain", "Ancient Guardian", "structural pillar", "Willow's bag", "Ramarno", "Imcando dwarves", "Runecrafting Crusades", "Ruins of Camdozaal"]
text = """
[[File:Below Ice Mountain 2.png|thumb|The crew assembled prepares to enter.]]
{{Needed|Some food for low combat players, and any [[pickaxe]] '''or''' a [[weapon]] and [[armour]] to kill a level 25 monster|skills={{SCP|Mining|10}} {{Boostable|yes}} if avoiding combat}}
With the crew assembled, head to the [[Blocked entry|ancient doors]] at the west side of [[Ice Mountain]] (marked by the dungeon icon on the minimap), and talk to Willow. The crew will begin unblocking the entrance, with Burntof blowing up the rocks, Checkal moving the debris, and Marley disabling the traps within.
[[File:Below Ice Mountain 3.png|thumb|left|Willow's treachery is revealed, whilst Burntof finds the ruins rather familiar.]]
Though the player becomes fascinated at the potential historical value of the ruins, Willow reveals that they are not actually archaeologists, but grave robbers hoping to find valuable loot. Now that the player knows, she can't risk being revealed to the authorities and prepares to kill them. However, Burntof accidentally sets off a trap, awakening the [[Ancient Guardian]]. Having bit off more than they can chew, the four crew members flee.
[[File:Below Ice Mountain 4.png|thumb|Fighting the Ancient Guardian.]]
After the cutscene ends, kill the level 25 [[Ancient Guardian]]. You can choose to kill it through standard combat, but lower levelled players are recommended to mine the four [[structural pillar]]s in the corners of the room; this will cause some rocks to fall down, damage the golem and ultimately kill it. When using the mining method, the guardian will constantly hit the player, so bring enough food. Alternatively, the guardian can be safespotted by hugging the east wall by the ruins' exit.

After defeating the golem, the player will loot some items from [[Willow's bag]], which she left behind in a panic. However, the doors leading deeper into the mountain open, revealing a dwarf named [[Ramarno]]. Being one of the few [[Imcando dwarves]] to have survived the [[Runecrafting Crusades]], Ramarno has since lived isolated inside these ruins: the [[Ruins of Camdozaal]].

'''Congratulations, quest complete!'''
{{clear|left}}
"""
