quest = "Death to the Dorgeshuun"
step_count = 6

[[steps]]
index = 0
name = "Infiltrating the H.A.M. hideout"
links = ["H.A.M. Hideout", "Lumbridge", "H.A.M. Member", "H.A.M. Guard", "H.A.M. Deacon", "Johanhus Ulsbrecht", "Jimmy the Chisel", "Bronze key (H.A.M.)", "Iron key (H.A.M.)", "Steel key (H.A.M.)", "Silver key (H.A.M.)", "Tears of Guthix (minigame)", "Trapdoor (H.A.M. Hideout)", "Dorgeshuun", "Hidden trapdoor"]
text = """
<imagemap>
File:H.A.M. Dungeon Map.png|center
desc none
#Title
poly 115 13 387 13 400 21 406 29 400 37 387 45 115 45 102 37 96 29 102 21 [[H.A.M. Hideout]]
#Entrance
circle 125 100 8 [[Lumbridge]]
#Legend
rect 317  86 445 102 [[H.A.M. Member]]
rect 317 107 491 124 [[H.A.M. Guard]]
rect 317 129 436 144 [[H.A.M. Deacon]]
rect 317 149 478 164 [[Johanhus Ulsbrecht]]
rect 317 170 462 185 [[Jimmy the Chisel]]
rect 317 192 463 210 [[Bronze key (H.A.M.)]]
rect 317 214 445 231 [[Iron key (H.A.M.)]]
rect 317 234 450 252 [[Steel key (H.A.M.)]]
rect 317 255 456 273 [[Silver key (H.A.M.)]]
#Monsters and NPCs
circle 130 236 8 [[H.A.M. Member]]
circle 172 213 8 [[H.A.M. Member]]
circle 174 189 8 [[H.A.M. Member]]
circle 193 165 8 [[H.A.M. Member]]
circle 202 182 8 [[H.A.M. Member]]
circle 214 214 8 [[H.A.M. Member]]
circle 220 168 8 [[H.A.M. Member]]
circle 224 105 8 [[H.A.M. Member]]
circle 270 188 8 [[H.A.M. Member]]
circle  22 149 8 [[H.A.M. Guard]]
circle  30 208 8 [[H.A.M. Guard]]
circle  49 174 8 [[H.A.M. Guard]]
circle  70 141 8 [[H.A.M. Guard]]
circle  80 195 8 [[H.A.M. Guard]]
circle 107 236 8 [[H.A.M. Guard]]
circle 131 121 8 [[H.A.M. Guard]]
circle 138 219 8 [[H.A.M. Guard]]
circle 152 126 8 [[H.A.M. Guard]]
circle 170 168 8 [[H.A.M. Guard]]
circle 172 248 8 [[H.A.M. Guard]]
circle 221 188 8 [[H.A.M. Guard]]
circle 228 244 8 [[H.A.M. Guard]]
circle 234 131 8 [[H.A.M. Guard]]
circle 249 266 8 [[H.A.M. Guard]]
circle 194 200 8 [[H.A.M. Deacon]]
circle 165 271 8 [[Johanhus Ulsbrecht]]
circle 277 278 8 [[Jimmy the Chisel]]
#Chests on lower level
rect 34 184 48 199 [[Bronze key (H.A.M.)|Chest (bronze key)]]
rect 51 148 66 164 [[Iron key (H.A.M.)|Chest (iron key)]]
rect 53 183 68 198 [[Steel key (H.A.M.)|Chest (steel key)]]
rect 59  98 72 120 [[Steel key (H.A.M.)|Chest (steel key)]]
rect 32 150 46 164 [[Silver key (H.A.M.)|Chest (silver key)]]
</imagemap><br/>

[[File:Death to the Dorgeshuun - Zanik and Juna.png|thumb|200px|Zanik telling stories about her adventures to Juna.]]
After speaking to all the aforementioned denizens of Lumbridge, ask her, "Have you seen enough of Lumbridge yet?" (Zanik will tell you to go back to Lumbridge if you ask this question inside the H.A.M. headquarters.) Zanik will now explain about the mark on her forehead; she received it whilst doing [[Tears of Guthix (minigame)|Tears of Guthix]], and it indicates that she is destined to do something great.

Zanik will now suggest going to the [[H.A.M. Hideout|H.A.M. headquarters]]. Put on your set of H.A.M. robes, and go to the H.A.M. headquarters.

When you arrive at the [[Trapdoor (H.A.M. Hideout)|trapdoor]] that leads down to the [[H.A.M. Hideout|H.A.M. headquarters]], right-click and select pick-lock on the trapdoor. This may take some time.

Talk to a regular [[H.A.M. Member]] or [[H.A.M. Guard|guard]], and go through all the questions. They will tell you that the leaders are planning something big in order to get rid of the [[Dorgeshuun]], but they won't tell any regular members.

Talk to [[Johanhus Ulsbrecht]] near the jail about the Cave Goblins.

Wander around the south part of the main H.A.M. room where Zanik will spot a [[Hidden trapdoor|trapdoor]] located slightly west of Johanhus and south of the stage. Pick-lock the trapdoor, and go down. You are now in a storeroom. You will need to distract each of the guards in such a way that Zanik can shoot them from behind.

:'''Note:''' In this section you may be jailed by a guard if caught. Zanik will free you - if you interrupt her, you may instead pick the lock on the door. You will have to repeat the process of killing the guards.

[[File:Death to the Dorgeshuun - Hidden trapdoor.png|thumb|220x220px|The hidden trapdoor.]]
[[File:Death to the Dorgeshuun - Zanik Shoots a Guard.png|thumb|200px|Zanik shooting one of the guards.]]
{{Checklist|
*The first guard will see you and tell you to go back upstairs—as regular members aren't allowed down there. He says that the other guards will not be so kind. Walk past the guard, and talk to him; Zanik will shoot him.
*Over to the west side, just where the guard was standing, squeeze through the crack in the wall to get into the south-west room. Wait for the guard in the narrow hallway to walk away so he doesn't detect you. Run through the second crack to the north, around the corner, and talk to the guard. Zanik will shoot him. Note: picking the door to access the guard might make your character move south and end up in jail. Squeezing through the crack is easier.
*You'll see a guard patrolling the central corridor. Speak to Zanik again, and when the guard has his back turned, select the "Now!" option. Zanik will snipe him.
*Move to the eastern side of the central corridor, stopping just before the guard can see you. Make sure you wait until Zanik is next to you, otherwise she may not take the shot.
*Then, run east and south down the room at least 2 steps, making the north-east guard follow you. Zanik will shoot him as he passes the central corridor again. Don't tell Zanik to wait, as she will not shoot the guard.
*For the final guard, go to the end of either the left or right passages, and talk to Zanik again, tell her to wait there; then, go to the other passage, and distract the guard by making yourself visible. Zanik will shoot him. (NOTE: Do not walk past the corner of either wall, as the guard will jail you once you are in line of sight.)
*Listen at the door. After Zanik hears a bit of info, a senior guard will respawn and arrest you.
}}
"""

[[steps]]
index = 1
name = "Reviving Zanik"
links = ["Jimmy the Chisel", "Sigmund", "Juna", "Chasm of Tears"]
text = """
You find yourself in the jail. Talk to [[Jimmy the Chisel]]. He will tell you that [[Sigmund]] took Zanik outside. Pick the lock to escape. If you accidentally leave the jail before talking to Jimmy, you can speak with Johanhus again and he will tell you about Zanik and you can continue.

[[File:Death to the Dorgeshuun - Zanik's body.png|thumb|200px|Zanik's dead body.]]
Go back outside, and you'll find Zanik lying on the ground, dead. Investigate her and your character will find that her mark is glowing. Take her body to [[Juna]] in the [[Chasm of Tears]].

:'''Note:''' If you for some reason die with Zanik, she will spawn again at the H.A.M hideout.
"""

[[steps]]
index = 2
name = "If the [[Tears of Guthix]] quest has already been completed"
links = ["Tears of Guthix (minigame)", "games necklace", "drilling machine"]
text = """
Go to the [[Tears of Guthix (minigame)|Tears of Guthix minigame]]. A [[games necklace]] will teleport you nearby. Juna will tell you to collect 20 tears using Zanik's bowl, which will restore Zanik to life.

:'''Note:''' This provides no experience and does NOT count for your weekly Tears of Guthix game.

[[File:Death to the Dorgeshuun - H.A.M. Meeting.png|thumb|200px|The meeting.]]
A cutscene will follow, where Zanik tells you what she heard just before she died. Johanhus, Sigmund, the H.A.M. deacon, and a senior guard will talk about using a [[drilling machine]] at the Lumbridge water wheel, to cause the swamp caves to flood!
"""

[[steps]]
index = 3
name = "If Tears of Guthix has not been completed"
links = ["pickaxe", "light source", "candle", "torch", "oil lamp", "tinderbox", "rope", "antipoison", "spiny helmet", "Lumbridge Swamp Caves", "Tears of Guthix", "chisel", "sapphire lantern", "Lumbridge Swamp", "Dorgesh-Kaan mine", "Lumbridge Castle", "Stepping stone (Lumbridge Swamp Caves)", "Juna", "candle lantern", "drilling machine", "Sapphire lantern", "Light creature", "Magic stone (Tears of Guthix)", "Stone bowl"]
text = """
{{Needed|A [[pickaxe]], [[light source]] ([[candle]]s, [[torch]]es and [[oil lamp]]s will explode), [[tinderbox]], [[rope]] (if entering from Lumbridge swamp), [[antipoison]], and [[spiny helmet]] (if unfamiliar with [[Lumbridge Swamp Caves]])}}

''If you meet the [[Tears of Guthix]] requirements, now is a good opportunity to complete that quest  during this step, in which case you also need a [[chisel]] and a [[sapphire lantern]].''

[[File:Lumbridge Swamp Caves map.png|thumb|Lumbridge Swamp Caves]]
Either enter the hole in [[Lumbridge Swamp]] or enter the [[Dorgesh-Kaan mine]] through the hole in the [[Lumbridge Castle]] cellar. In the mine, go directly south of the entrance and Kazgar to a blocked tunnel, mine it with your pickaxe, and squeeze through into the [[Lumbridge Swamp Caves]]. In the south-eastern part of the cave, directly south of the entrance from the Dorgesh-Kaan mine, cross the [[Stepping stone (Lumbridge Swamp Caves)|stepping stone]] in the stream. '''''Warning:''' If you fail, it will extinguish your light source.'' On the southern side you will find the entrance to the Tears of Guthix Cavern. Go through it and follow the path, climb down the rocks and speak to [[Juna]].

'''Warning for Hardcore Ironmen:''' It is recommended you enter the Lumbridge Swamp caves via the dark hole entrance in the western part of Lumbridge Swamp. This way you bypass the Cave Crawlers that if aggressive will poison you. Also bring plenty of food as the Wall Beasts deal on average 9 damage, with a max hit of 18.

'''Warning: '''If you happen to slip on the stepping stones carrying a [[candle lantern]] it will break, leaving you stranded without a light source (apart from a [[candle]] itself after the lantern breaks, which is risky to use in the Swamp Caves). For safety precautions, bring any kind of quick teleportation if needed.

[[Juna]] will ask you to gather blue tears from the waterfalls. Your hands must be empty for this. Once you talk to her with empty hands and you are holding the bowl, just click on the blue waterfalls as they spawn until you are at 20. A cutscene will begin and Zanik will be revived. Zanik tells you what she heard just before she died. Johanhus, Sigmund, the H.A.M. deacon, and a senior guard will talk about using a [[drilling machine]] at the Lumbridge water wheel, to cause the swamp caves to flood!

To complete the [[Tears of Guthix]] quest, after talking to [[Juna]] use the optional [[Sapphire lantern]] on a [[Light creature]] to be carried to the upper level of the south mine. There you can mine the [[Magic stone (Tears of Guthix)|Magic Stone]]; use a chisel on it to make the [[Stone bowl|Stone Bowl]] and return to Juna to complete Tears of Guthix.
"""

[[steps]]
index = 4
name = "Preparing for battle"
links = []
text = """
{{Needed|recommended=H.A.M. outfit, Melee or Magic equipment ('''not''' Ranged) to deal with three level 22 guards and one level 50 boss, food and enough space to have both your hands empty}}

Return to Lumbridge and grab your combat equipment, then head to the chicken farm near the water mill, across the river from Lumbridge Castle and heading north. You will need to bring Zanik with you - if you teleport she will need to be retrieved from the cellar before continuing. '''If she doesn't appear, try logging out and in.'''

'''Equip the full H.A.M. outfit''' then search one of the southern crates (the '''empty''' ones, not the ones with machine parts in them), Zanik will suggest she hides in it whilst you carry it, pick her up, and go down the trapdoor. You must have free hands (no weapon or offhand).

:'''Note:''' If you walk too far away from the trapdoor Zanik will leave the crate and suggest "we get down there and save my city!".

Also, immediately exiting the cave will make you unable to re-enter the trapdoor due to Zanik waiting for you in the cave. Logging out and back in will resolve this but you may have to return to the Lumbridge basement to have her follow you again.
"""

[[steps]]
index = 5
name = "The battle"
links = ["Guard (Death to the Dorgeshuun)", "prayer", "safespot", "Magic", "halberds", "Protect from Missiles", "ring of life"]
text = """
{{Instance}}
[[File:Death to the Dorgeshuun - The Battle.png|thumb|200px|The fight. Try to line up the guards, with Sigmund at the back.]]
[[File:Smashing the drill.png|thumb|left|The machine is smashed to smithereens.]]
Go to the west room after climbing down the ladder of the nearby trapdoor. Sigmund (level 50) will appear along with three level 22 [[Guard (Death to the Dorgeshuun)|H.A.M. Guards]].

Sigmund will use a protection [[prayer]] based on the attack you are using, so focus on his henchmen first. The crates nearby may be used as a [[safespot]] with [[Magic]] or melee using [[halberds]].

Once the henchmen are dead, Zanik will attack Sigmund with her crossbow, causing him to switch to [[Protect from Missiles]]. Attack him with melee or magic. At 1 HP, he will escape with a [[ring of life]]. Smash the drilling machine in the same location.

{{bug|If Sigmund is hit while he is swapping prayers, the icon above his head will display the wrong protection prayer.}}

Exit through the southern tunnel to find yourself back with the Dorgeshuun leaders. You '''must''' exit through the tunnel, or the cutscene will not play.

'''Congratulations, quest complete!'''

:'''Note:''' If you don't have a light source, Zanik will provide you one after the cut scene when going through the short cut.
"""
