quest = "Elemental Workshop II"
step_count = 5

[[steps]]
index = 0
name = "Starting off"
links = ["Exam Centre", "Digsite", "beaten book", "Seers' Village", "primed mind bar"]
text = """
[[File:Elemental Workshop II - Beaten book location.png|left|thumb|220px|The bookcase in which the beaten book is located.]]
To begin, you need to go to the [[Exam Centre]] south of the [[Digsite]]. In the south eastern corner of the building, there are two chests. Search the bookcase two tiles down (the one attached both to the wall and another bookcase) to find a [[beaten book]] with a scroll in it as a bookmark.

''Note: There is a bug where searching the bookcase may give the message "The label on this shelf reads 'Earth Sciences'; however, the helpful books have been taken. It looks like the other students got to them first." If this happens, search the other bookcases to start the quest.

Read the book and then the scroll, and then head to [[Seers' Village]]. '''Do not''' get rid of this book before the end of the quest; if you do, you will not be able to make the helmet out of the [[primed mind bar]].
{{Clear|left}}
"""

[[steps]]
index = 1
name = "The key"
links = ["battered key", "Seers' Village", "Bank", "bookcase (Elemental Workshop I)", "slashed book", "anvil", "Elemental Workshop (location)", "Elemental Workshop I", "Quests", "water elemental", "elemental ore", "mind shield", "elemental metal", "coal", "Coal Trucks", "Agility", "Log balance (Coal Trucks)"]
text = """
[[File:Elemental Workshop II - Hatch key location.png|thumb|220px|The hatch key location.]]
If you don't already have the [[battered key]], head to the building south-west of [[Seers' Village]] [[Bank]], and search the north-east [[bookcase (Elemental Workshop I)|bookcase]] to get a [[slashed book]] and a battered key. Enter the north building with the [[anvil]] icon, and let yourself in to the [[Elemental Workshop (location)|workshop]] the same way as in the [[Elemental Workshop I]] [[Quests|quest]].

Next, go into the northern [[water elemental]] room and search the machinery to the south-west side of the room. You will receive the key used to unlock the hatch in the main room.

:'''Note:''' If you do not read the scroll, you will not get the search option for the machinery.
:'''Note:''' Before you go down, quickly "mine" two [[elemental ore]]s (three if you desire a [[mind shield]]) from the west room, and smelt them into [[elemental metal]]s in the south room (you will need 4 [[coal]] per elemental bar). Ironmen may find coal at the [[Coal Trucks|mine]] west of Seers' Village; 20 [[Agility]] is required to access it through a [[Log balance (Coal Trucks)|shortcut]].
"""

[[steps]]
index = 2
name = "Making repairs"
links = ["Elemental Workshop (location)", "Schematic crate", "an old lever", "Crane schematic", "lever schematic", "crane claw", "old crane", "junction box", "small cog", "medium cog", "large cog", "Pipe (Elemental Workshop II)", "wind tunnel", "Cog (Elemental Workshop)", "Tunnel wall"]
text = """
[[File:Elemental Workshop II - Junction pipe placement.png|left|thumb|190px|Pipe connections]]
[[File:Elemental Workshop II - Cog placement.png|thumb|190px|Cog placements]]
Go to the middle of the room and use the key on the locked hatch. Once you're [[Elemental Workshop (location)#Second sublevel|downstairs]], you need to fix the machinery. First, go to the "[[Schematic crate]]" (directly beside [[an old lever]]) to the south and take both the  [[Crane schematic|crane]] and the [[lever schematic]]s. Then go back upstairs and use '''one''' of your bars on the workbench ('''make sure you only make one in the smithing menu, as the default will be make all!)''' and make the [[crane claw]]. '''Do not make a helmet yet!'''

Now, go back down and pull the south-western lever right next to the [[old crane]], and then use the claw on the crane.

Next, head up the small stairs to your west (not up the hatch, but onto the metal construct) to get to the upper level. Open the [[junction box]] in the west to work on the pipes for the press (click on the ends you want to connect). You'll want to arrange them as seen on the left.

'''Hint:''' The player is led to assume that the machine operates by steam pressure. There is a huge entry pipe that leads from outside the workshop, suggesting that this is a power input source. Observe the lever schematic and the relative pipe entry points. The lever schematic indicates that it is in the middle position normally, blocking flow from the middle pipe, and requires pulling to either side to activate and allow flow from the middle pipe to the outer pipes.

'''Explanation of the solution:''' The correct solution is worked out from the clue given by the lever schematic as well as by seeing how the 6 pipes are connected to the back of the junction box. These correspond to the pipe ends in the interface. The lever schematic shows that the middle pipe coming from the lever, top-right in the interface, allows steam to flow towards the lever and must therefore be connected to the large supply pipe, top-middle in the interface. Next, the 2 remaining pipes coming from the lever, bottom-right and bottom-middle in the interface, must be connected to the 2 pipes coming from the press, top-left and bottom-left in the interface. The only combination that works is bottom-right to top-left and bottom-middle to bottom-left.

For the next two parts, you'll need to search some crates in the bottom and upstairs area. The [[small cog]], [[medium cog]], [[large cog]] and [[Pipe (Elemental Workshop II)|piece of pipe]] are located randomly in crates for each player. However, only certain crates contain items: on the bottom floor try searching the double-stacked crates next to the large exit staircase, the single crate north-west by the stairwell down, the double-stacked crate east of the west water valve, the double-stacked crates south-east, and the crate next to the schematics crate. Upstairs try searching the double-stacked crate south-east above the [[old crane]] and the double-stacked crate directly north-west of the [[junction box]]. If searching a crate does not yield an "It's empty." message or produce an item, it is not possible to find an item within. Once you have found all 3 cogs and the [[Pipe (Elemental Workshop II)|piece of pipe]], you can stop searching the crates. If you lose one of the items before using it you can retrieve it in the same crate it was found previously.

Use the pipe on the broken pipe upstairs on the northernmost point of the scaffolding. Then for the cogs, take them back down the steps to the [[wind tunnel]] on the east side of the track. On the side of the wind tunnel are three [[Cog (Elemental Workshop)|pins]] (under 2 [[Tunnel wall#Arrow right|yellow directional arrows]]). By using the cogs on the machine pins, you want to stick the small one on the upper-left pin, the medium one on the lower left, and the large one on the right.
"""

[[steps]]
index = 3
name = "Operating the machine"
links = ["elemental metal", "jig cart", "Mine cart sign", "steam press", "pipe (Elemental Workshop II)", "water tank", "an old lever", "corkscrew lever", "Water valve (Elemental Workshop)", "fan blade", "primed bar", "Mind shield"]
text = """
[[File:Elemental Workhop II - Making a primed bar.png|thumb|One of the many steps to creating a primed bar.]]
{{Checklist|
*Place your [[elemental metal]] on the [[jig cart]], which should be on the south crane right now. (If it is not, you must have already pulled the lever with the [[Mine cart sign|yellow cart-sign]] - keep operating it, until the cart completes the circle around the room and arrives again.)
*The crane
**The west lever (near the crane) will raise and lower the crane, and the east one (also near the crane) will rotate the crane. Raise the crane, rotate it, lower it to dip it into the lava and raise it back out. The bar should now be glowing orange.
**Rotate the crane back, lower it and raise it again to deposit the bar on the jig.
**:'''Note:''' Make sure to lower the crane and then '''raise it again''' in order to correctly deposit the bar. Not doing so will cause the bar to remain on the crane.
*Pull the lever right behind you, by the yellow sign (north of the crane) to move the cart to the next station. Remember this lever, you will need to use it to move the cart after each step.
*Go to where the cart now is and pull the lever to the east, north-west of the yellow sign. The bar will be flattened by a [[steam press]].
*Go back to the yellow-sign lever and move the cart forward again.
*If you haven't already fixed the pipe, go upstairs (not up the hatch, but onto the metal construct), and use the [[pipe (Elemental Workshop II)|pipe piece]] you found on the pipes to the north (they have a hole) to fix them and go down the stairs again.
*The [[water tank]]
**You will see [[an old lever]], a [[corkscrew lever]], and two [[Water valve (Elemental Workshop)|water valves]].
**Pull the old lever to open the door, then turn the corkscrew lever twice to pull the cart into the tank. Close the door again with the old lever.
**Make sure the eastern valve is closed, then open up the western valve (between two stacks of crates). The bar should turn blue once it gets cooled by the water. If it does not, the eastern valve is open.
**Close the western valve again, then open the eastern one to let the water out and close it down again.
**:'''Note:''' If the eastern valve reports that it is sucking air, you skipped step 6 (Fixing the pipe).
**Open the door with the old lever, turn the corkscrew twice to deposit the cart back on the track, close the door again using the old lever. The cart will not move forward again while the door is open.
*Pull the yellow-sign lever again to move the cart to the next station.
*Turn on the [[fan blade|fan]] by pulling the lever next to it, and then turn it back off. When it is dry, the bar turns white.
*:'''Note:''' If the fan reports that it is sucking air <!-- Maybe not correct, that is what a fan does right? -->, the cogs are not correct.
Pull old lever to turn off fan or cart will not move forward in the next step.
*Go back and pull the lever to advance the cart again.
*Pick up the [[primed bar]]!
}}
Do this twice if you want the [[Mind shield|shield]].
"""

[[steps]]
index = 4
name = "Finishing up"
links = ["Elemental Workshop (location)", "extractor gun", "extractor hat", "Mind bar", "Magic", "mind shield", "mind helmet", "slashed book"]
text = """
[[File:Elemental Workshop II - Extractor hat.gif|thumb|x180px|A bit of mind draining.]]
Go down [[Elemental Workshop (location)#Third sublevel|one more level]] to where there are two doors, one with the mind symbol and the other with the body symbol. Go into the mind room (nearest), and place your bar on the [[extractor gun]] and operate the [[extractor hat]] next to it. A part of you will be drained into the bar turning it into a [[Mind bar|primed mind bar]] (that will be picked upstairs in the old crane).

This will temporarily lower your [[Magic]] level by 20.

NOTE: You can power multiple bars while here, but each additional bar will drain your Magic by another 20 levels. Power an additional bar if you wish to make a [[mind shield]] at the same time as your [[mind helmet]] (this is not required to complete the quest).

Once you have picked up the bar/s from the extractor gun, go back up to the workshop. '''The beaten book is required to be in your inventory to make the [[mind helmet]], otherwise you will make a mind shield'''. Make a [[mind helmet]] out of the bar and the quest is complete.

'''Congratulations, quest complete!'''

After the quest is completed, if you have gathered an additional powered bar, make the [[mind shield]] with the [[slashed book]] in your inventory. '''Using a bar on the anvil with the slashed book in your inventory will make a [[mind shield]], otherwise you will make a second mind helmet'''.

Both the mind shield and helmet can be sold on the grand exchange for {{Coins|{{GEP|Mind shield}}}} and {{Coins|{{GEP|Mind helmet}}}} respectively.
"""
