quest = "Priest in Peril"
step_count = 4

[[steps]]
index = 0
name = "Beginning the quest"
links = ["Combat equipment", "Varrock teleport", "King Roald", "Varrock Palace", "Drezel", "Paterdomus Temple", "Varrock"]
text = """
{{map|3410,3494|zoom=3|align=right|caption=Location of the Temple and Dungeon Entrance to the north.}}
{{Needed|[[Combat equipment]]|recommended=[[Varrock teleport]]}}
To begin the quest, talk to [[King Roald]] in [[Varrock Palace]], located in the south-easternmost room near the main entrance, and ask him for a quest. He will tell you that it has been some days since he heard from [[Drezel]], a priest who lives in the [[Paterdomus Temple|temple]] to the east, and ask you to check up on him.

[[File:Paterdomus Temple.png|thumb|220px|The entrance to the temple.]]
The [[Paterdomus Temple|temple]] is located east of [[Varrock]]. Go through the wooden gate north-east of the east exit by the Earth Altar. Then, follow the path to the temple. Attempt to open the door to the temple and a mysterious voice will ask what you want and who you are. Tell them King Roald sent you to check on Drezel. After some whispering, they will ask you to do them a favour; a dog in the nearby mausoleum has been bothering them, and they want you to kill it. Agree to it.
"""

[[steps]]
index = 1
name = "The dungeon"
links = ["temple guardian", "safespotted", "flinched", "Magic", "rings of recoil"]
text = """
[[File:Temple_Guardian_safespot.png|thumb|left|220px|Safespotting the Temple Guardian.]]

Climb down the trapdoor north of the temple, then kill the unaggressive level 30 [[temple guardian]], which may be [[safespotted]] with ranged, or [[flinched]] using melee. You cannot use [[Magic]]. To trap the guardian, simply move one square east after coming down the ladder, and drag the dog over by using ranged attacks, or by attacking with melee and then running back to the same square.

:'''Note:''' If using [[rings of recoil]], 1 damage must be dealt by the player for the kill to register.
"""

[[steps]]
index = 2
name = "Returning to King Roald"
links = ["Varrock Palace", "Temple guardian", "Misthalin"]
text = """
Return to King Roald in the [[Varrock Palace]]. After telling him you killed the dog in the mausoleum, King Roald becomes enraged, and explains that the [[Temple guardian|dog]] was protecting the mausoleum from sabotage, and that the whole of [[Misthalin]] is now at risk. He instructs you to go back and fix it right away.

Before returning, if you don't yet have a bucket, go up the nearby stairs and grab one from the bedroom in the north eastern corner. Alternatively you can buy one from the general store to the south of the palace.
"""

[[steps]]
index = 3
name = "Back to the temple"
links = ["Rune essence", "pure essence", "bucket", "combat", "equipment", "inventory", "Essence pouch", "Varrock teleport", "Monk of Zamorak", "golden key", "rings of recoil", "Drezel", "monument", "Well (Paterdomus)", "iron key", "murky water", "pot", "feather", "candle", "tinderbox", "needle", "hammer", "blessed water", "Coffin (Priest in Peril)", "rune essence", "essence pouch", "Morytania"]
text = """
{{Needed|50 Unnoted [[Rune essence|rune]] or [[pure essence]], an empty [[bucket]], [[combat]] [[equipment]] and 1 free [[inventory]] space|recommended=[[Essence pouch]]es and [[Varrock teleport]]s}}
[[File:Monk_of_zamorak_safespot.png|thumb|left|220px|Safespotting the Monk of Zamorak.]]
Return to the temple and enter it. Kill one of the '''level 30''' [[Monk of Zamorak|Monks of Zamorak]] to get a [[golden key]]. The monks attack with magic, and can be trapped inbetween the pews by standing south of the pew, to be safespotted with ranged or magic. They can also be flinched with the same method.

:'''Note:''' If using [[rings of recoil]], 1 damage must be dealt by the player to receive the key.

After receiving the key, climb up the stairs in the north-east corner of the room, then climb up the ladder of the south west corner of the room to reach the top floor. Talk to [[Drezel]] through the bars, and he will tell you that the Zamorakians have attacked the temple and imprisoned him. Ask him why the river is such a good defence. After explaining the significance of the river the mausoleum is built over, he will ask you to aid him in foiling the Zamorakian plot.

Next, go back down the trap door into the mausoleum. With the golden key in the inventory, the player can now unlock the gate to the south. Through the gate is a room with seven [[monument]]s and a [[Well (Paterdomus)|well]]. Study the monuments until you find the one that holds an [[iron key]], then use the golden key on it to swap the two. After obtaining the iron key, use your empty [[bucket]] on the nearby well to fill it with [[murky water]].

:'''Note''': The other monuments hold golden items which may be obtained once as souvenirs by swapping them with the regular versions. The items that may be swapped are a [[pot]], [[feather]], [[candle]], [[tinderbox]], [[needle]], and [[hammer]]. This can no longer be done after Drezel moves to the mausoleum in the following steps.'''

[[File:Priest in Peril - Blessing the coffin.png|thumb|250px|The player pours the bucket of blessed water on the coffin, trapping the vampyre within.]]
Return to the top floor of the temple, and use the iron key on the cell door. Enter the cell and talk to [[Drezel]] and he will bless the murky water for you. Use the [[blessed water]] on the [[Coffin (Priest in Peril)|coffin]] just outside of the cell to seal the vampyre within it. Talk to [[Drezel]] again and he will tell the player to meet him in the dungeon.

Return to the dungeon and proceed through the gate located in the north-east corner of the monument room. Speak to [[Drezel]], who will tell you that the Zamorakians have used a potion to poison the river, and he requests you bring him 50 '''unnoted''' essence to soak up the evil magic released by the potion.

If you need to, you can give him a mixture of both [[rune essence|rune]] and [[pure essence]]. Players with essence pouches can bring all 50 essence in a single trip if desired. If you don't have an [[essence pouch]], make multiple trips as needed.

'''Congratulations, quest complete!'''

:'''Note:''' To unlock access to [[Morytania]], you must ask Drezel if you can now pass through the barrier, and wait until he has blessed you.
"""
