quest = "Vale Totems (miniquest)"
step_count = 1

[[steps]]
index = 0
name = "Main"
links = ["Ranulph", "Auburnvale", "Isadora", "totem site", "Sacraments of ent folk"]
text = """
Talk to [[Ranulph]] in north-western [[Auburnvale]]. Ask him what he's preoccupied by, and he will tell you about the strange behaviour of the local ents. Together you will investigate a totem, which Ranulph will break. [[Isadora]], a nearby child, will see this happen and tell you that you now need to build a new totem.

Ranulph and Isadora will tell you to take a set of logs, oak or better, and use them to build the base of the new totem.

* Click on the [[totem site]] to the north to build the totem base, then return to Ranulph and Isadora. Various trees are scattered around the totem that can be chopped for logs.
* Next they will tell you to carve depictions of the nearby spirit into the totem. Click on the totem, then click on the options for each of the nearby spirit animals. The animals are unique for each player.
* After this, return to Ranulph and Isadora. They will tell you to decorate the tree using bows or shields fletched from the same material as the totem. With four of these items in your inventory, click on the totem to decorate it.
* At this point Ranulph and Isadora will tell you that the ents approve of the totem and left an offering for you. Click on the offerings to claim them. After this, speak to Ranulph or Isadora to receive [[Sacraments of ent folk]] and complete the miniquest.
"""
