quest = "Twilight's Promise"
step_count = 8

[[steps]]
index = 0
name = "With friends like these..."
links = ["Regulus Cento", "Varrock", "Varlamore", "Ennius Tullus", "Furia Tullus", "Sunrise Palace", "Civitas illa Fortis", "Prince Itzla", "bazaar", "Metzli, Teokan of Ranul", "Servius", "Servius, Teokan of Ralos", "Knight of Varlamore (Children of the Sun)"]
text = """
[[File:Ennius Tullus chathead.png|left]]
Talk to [[Regulus Cento]] outside [[Varrock|Varrock's]] east gate to travel to [[Varlamore]]. When you arrive, speak to [[Ennius Tullus|Ennius]] or [[Furia Tullus]] at the entrance to the [[Sunrise Palace]] in [[Civitas illa Fortis]]. You will be instructed to visit the temple in the city, as [[Prince Itzla]] is expecting you. The temple is found just south-east of the [[bazaar]], marked on the world map with two [[File:Dungeon map link icon.png]] dungeon icons.

At the temple, you will find [[Metzli, Teokan of Ranul]], who will tell you that you saved the life of her counterpart, [[Servius]]. Tell her you're meant to be meeting the prince, and Metzli will tell you he is talking to Servius in the crypt under the temple. Take the stairs down to proceed.

After entering the crypt, head north through the gate and speak to the prince in the centre of the open area. He will re-introduce you to [[Servius, Teokan of Ralos]], revealing him to be his father, and will remind you that someone is plotting to kill Servius. He will then explain that, given the strict policies on travelling outside the kingdom before the signing of the treaty in Varrock, the culprit can only be a member of the delegation that visited. Prince Itzla therefore suspects that one of the [[Knight of Varlamore (Children of the Sun)|Knights of Varlamore]] who travelled with Servius is responsible, and suggests speaking with the Tullus twins once more.
"""

[[steps]]
index = 1
name = "Oh Brother!"
links = ["Sunrise Palace", "Varlamore crest", "Knight of Varlamore (Children of the Sun)"]
text = """
[[File:Varlamore crest detail.png|left|73px]]
Return to the Tullus twins at the [[Sunrise Palace]], who are now found further inside the palace grounds. They will mention six knights and give you their locations, as well as a [[Varlamore crest]] to prove you are helping them. You must now find and collect the [[Knight of Varlamore (Children of the Sun)|knights]], who will all be known as "Knight(s) of Varlamore". They do not have to be returned to the palace in any particular order.
"""

[[steps]]
index = 2
name = "=Arrun and Claudia="
links = ["bazaar", "Citizen (Twilight's Promise)", "stolen amulet"]
text = """
[[File:Twilight's Promise - pickpocking stolen amulet.png|thumb|220px|The correct citizen to steal the stolen amulet from.]]
Arrun and Claudia can be found in the centre of the [[bazaar]]. They will agree to return to the palace after finishing their work of catching a thief, for whom they planted an amulet at one of the stalls, hoping it would be stolen. They will encourage you to rummage through the pockets of bazaar-goers until you find the thief that took the bait.

Pickpocket the male [[Citizen (Twilight's Promise)|citizen]] in the second-to-lightest shade of blue robes (he will be the only one with robes of that colour, see picture) to find the [[stolen amulet]]. Return it to the knights, and at which point they will agree to return to the palace.
"""

[[steps]]
index = 3
name = "=Nel="
links = ["Fortis Cothon", "Crate (Twilight's Promise)"]
text = """
[[File:Twilight's Promise - weapons crate.png|thumb|220px|The crate full of weapons.]]
Nel can be found in the south-western part of the [[Fortis Cothon]], on the docks. To help her return to the palace quicker, she will ask for assistance in finding a [[Crate (Twilight's Promise)|crate]] full of weapons. Complete the dialogue until Nel mentions where to find the crate, and then head to the north-east corner of the cothon.

The crate you will need to search is directly adjacent to two barrels with fish in them, close to a bench. Search the crate to learn the name of the smuggling ship, the Fortis Spark, and return to Nel. Inform her of your findings and she will agree to return to the palace.
"""

[[steps]]
index = 4
name = "=Mezan="
links = ["Glory", "Fortis Colosseum", "poisoned", "skillers", "poison dynamite", "Saradomin brews"]
text = """
{{Needed|Combat equipment for two different styles, or a poisoned weapon (there is a bank in the Colosseum that requires [[Glory]] to use).}}
Upon entering the [[Fortis Colosseum|Colosseum]], head north to the training area and talk to Mezan. He will mention that his training partner has not shown up, and will only leave if you spar with him in the partner's place. The fight will require any two combat styles, as he will start praying against the one currently being used every four attacks. If no attack style is used 4 times in a row (for instance, attack 3 times with melee then once with range and repeat) then he will never use protection prayers. It is also possible to use a [[poisoned]] weapon to finish Mezan off, as this can be reapplied through his prayers. Once the fight is over, Mezan will leave for the palace. If the player dies at the same time as the knight then the knight will still return to the castle when spoken to.

Note: The Voidwaker special attack counts as a non-melee based attack.

Note: [[skillers]] and other limited account builds can use [[poison dynamite]] to poison Mezan and run in circles until he dies. Players can also use dynamite for true damage dealt on him, and then recoil him down to 0. Mezan's max hit is 8, meaning that players doing this method should be prepared with a substantial amount of food as well as [[Saradomin brews]].
"""

[[steps]]
index = 5
name = "=Velam and Azali="
links = ["Atlazora's Rest", "Outer Fortis General Store", "cutscene"]
text = """
[[File:Twilight's Promise - Velam sobering up.png|thumb|250px|The player instructs Azali to dunk her head in the fountain in order to sober up.]]
Velam and Azali can be found at [[Atlazora's Rest]], just north of the [[Outer Fortis General Store]]. Azali will need to sober up, so lead her to the fountain east of the bar to trigger a short [[cutscene]]. Once in a while, Azali will stop following you; simply talk to her again and then head towards the fountain once more. Return to the bar and speak to Velam, and then head to the palace after finishing the conversation. If you have a pet or follower active, Azali will not follow you.
"""

[[steps]]
index = 6
name = "=Judgement="
links = ["Kualti Headquarters", "Queen Zyanyi Arkan", "Chest (Twilight's Promise)", "incriminating letter", "the Teomat"]
text = """
[[File:Twilight's Promise - Velam is killed.png|thumb|250px|Ennius kills Velam, who pleaded his innocence until the very end.]]
Once all knights have returned to the palace, speak to the twins again to learn that the knights stayed in the [[Kualti Headquarters]] prior to visiting Varrock, just west of the palace. The Headquarters is the large building containing a statue of [[Queen Zyanyi Arkan]], situated across the road from a small building with training dummies. Head north-west and go up both flights of stairs to reach their bedrooms.

Investigate one of the [[Chest (Twilight's Promise)|chest]]s in the south-eastern room to find an [[incriminating letter]] (the letter has an equal chance of being in either chest), and then read it and return to the twins once more. Speaking to the twins will trigger a cutscene in which Velam, claiming innocence, will be killed by Ennius. The twins will now tell you to deliver the news to the prince at [[the Teomat]]. '''Note:''' reading the letter is '''required''' to start the cutscene.
"""

[[steps]]
index = 7
name = "The Twilight Emissaries"
links = ["Regulus Cento", "quetzal", "Quetzal feed (Twilight's Promise)", "Renu", "Quetzal Transport System", "the Teomat", "Cam Torum", "Twilight Emissaries", "Metzli", "Ximoua", "Old Ones", "cultist"]
text = """
Speak to [[Regulus Cento]] south-east of the palace next to the quetzals and ask about getting to the Teomat. Regulus will tell you that Prince Itzla has given you a personal [[quetzal]] to fly around Varlamore, and gives you some [[Quetzal feed (Twilight's Promise)|quetzal feed]] for [[Renu]], who is newly trained and ready. Feed Renu the quetzal feed, and an interface for the [[Quetzal Transport System]] will open. Travel to [[the Teomat]] (it will be a small option on the menu that looks like a tiny house on top of mountains, found just north of the [[Cam Torum]] location). Note that from here on out, you can access the already-unlocked quetzal locations at any time; you do not need to finish the quest.

Head inside the Teomat and speak to Prince Itzla in the room with the altar icon, and let him know about Velam's betrayal. He will be surprised, and when you tell him that you believe that Velam's murder is too convenient and that Ennius had killed him too quickly, he will agree to keep an eye on the twins. He will then share to you about the [[Twilight Emissaries]], a religious cult obsessed with the end of the world - the Final Dawn.

To learn about the Final Dawn, head slightly north to the library and speak with [[Metzli]]. She will mention [[Ximoua]], a belief passed down from the [[Old Ones]], and say that the Final Dawn being an interpretation of it; the difference in belief however is not that the end of the world ''will'' come, but rather that it must be ''made''. As you're finishing up the conversation, you will be attacked by eight level 34 [[cultist]]s, whom the guards must defeat. Note that only one will attack you; the rest will only attack after being attacked first. If necessary, you may let the guards kill the cultists.

Once you defeat all eight cultists, a cutscene will play showing that Servius has been gravely wounded, even though none of the cultists made it inside. Notably, [[Metzli]] has disappeared, but Servius is quickly brought back to the capital. Prince Itzla will then tell you that he will contact you again once he has planned the next steps.

<gallery captionalign="center" widths="200">
Twilight's Promise - killing cultists.png|Cultists storm the Teomat.
Twilight's Promise - Servius is injured.png|Servius is gravely injured during the attack.
</gallery>

'''Congratulations, quest complete!'''
"""
