quest = "Olaf's Quest"
step_count = 6

[[steps]]
index = 0
name = "Family honour"
links = ["Olaf Hradson", "Rellekka Hunter area", "Keldagrim", "fairy ring", "Rellekka", "windswept tree", "windswept logs", "crude carving", "Ingrid Hradson", "cruder carving", "Volf", "rock crabs", "Fremennik Diary"]
text = """
[[File:Olaf Hradson chathead.png|left]]
[[File:Chopping windswept logs.png|thumb|220px|Chopping the wretched, bare tree.]]
Talk to [[Olaf Hradson]], who is north-east of Rellekka by the entrance to the [[Rellekka Hunter area|snow hunting area]], [[Keldagrim]], and [[fairy ring]] {{Fairycode|DKS}}. He will tell you about his attempt to live up to his family's reputation by becoming an expert explorer. Although he failed miserably, he still wants to make his family proud. He wants you to deliver some special carvings to his wife and son in [[Rellekka]], pretending they are from a faraway land. Unfortunately, he only has damp driftwood on him, as his ship was allegedly smashed thrice onto the rocks in a huge storm. He directs you to the [[windswept tree]] up the mountain path to the east, from which you could obtain some dry wood. He promises you the treasure map he had been carrying in return.

Go up the snowy hill to the east and cut the windswept tree with any axe to get [[windswept logs]]. Once you bring the logs back, Olaf will make a [[crude carving]] for you to take to his wife [[Ingrid Hradson|Ingrid]], and an even [[cruder carving]] to give his son [[Volf]] back in Rellekka.

:'''Tip''': Kill five [[rock crabs]] near him to complete an easy [[Fremennik Diary]] task.
"""

[[steps]]
index = 1
name = "To Rellekka"
links = ["Ingrid Hradson", "Rellekka", "bread", "Volf Olafson", "Skulgrimen's Battle Gear", "shark"]
text = """
[[File:Crude carving detail.png|left|80px|frameless]]
Olaf's wife, [[Ingrid Hradson]], is found wandering around the well, just south-east of the longhall in [[Rellekka]], or in the house next to it. You can take the agility shortcut at the eastern fence if you have {{SCP|Agility|57}}.  The player will give her the carving, describing it as an expensive, exotic gift from the far-flung and tropical shores of the Island of Obscurity. She will give you a piece of freshly baked [[bread]] as thanks.

Olaf's son, [[Volf Olafson]], is further north by the [[Skulgrimen's Battle Gear|helmet shop]]. After you tell him that his father has sent him a very valuable gift from the Island of Obscurity, he will give you a cooked [[shark]] as thanks.

[[File:Svens_last_map_read.png|thumb|220x220px|Sven's last map.]]
"""

[[steps]]
index = 2
name = "Cold, damp and hungry"
links = ["damp planks", "embers", "tinderbox", "Sven's last map", "Sven the Helmsman", "windswept tree", "Brine Rat Cavern"]
text = """
[[File:Windswept tree.png|80px|frameless|left]]
Talk to Olaf again, whose fire seems to have gone out. He is freezing but would rather die than return to Rellekka so soon and admit his lie. He will give you some [[damp planks]] and ask you to light the fire. Use them on the [[embers]], and light it with your [[tinderbox]] (requiring {{SCP|Firemaking|40}}). After you make the fire, he will ask for food, having eaten nought but seaweed and biscuits for a week. You do not have to give him food; you can simply tell him not a chance, and he will give you the map anyway. If you do choose to give him food, he will take '''any piece''' from your inventory.

He will give you [[Sven's last map|the last map]] of his grandfather, [[Sven the Helmsman]]. It supposedly leads to his last treasure hoard, but Olaf has been unable to decipher the runic inscriptions. He wishes you luck on your search and decides to remain where he is for now to practise his carving and possibly starve.

Read Sven's map. It depicts the precise area where you are. The '''X''' represents the tree up on the hill that you visited earlier. Dig next to the same [[windswept tree]] on the hill from earlier and you will fall into a [[Brine Rat Cavern|cave]].

[[File:Brine_Rat_Cavern_map.png|thumb|220x220px|A detailed map of [[Brine Rat Cavern]].]]
"""

[[steps]]
index = 3
name = "=The jolly rog-door="
links = ["brine rat", "Medium Fremennik Diary", "Skeleton fremennik", "Key (Olaf's Quest)", "Crumble Undead", "picture wall"]
text = """
'''Note''': You can leave the cave at any time by rolling up the boulder. This will place you by Olaf, and you will need to climb the hill and dig again to re-enter.

Follow the corridor to the east and then north, until you reach the picture wall. Along the way you may kill a [[brine rat]] in the western enclave to complete a task in the [[Medium Fremennik Diary]] (requires {{SCP|Slayer|47}}).

[[File:Olaf's_quest_puzzle_completed.png|thumb|left|220px|A picture of the completed puzzle.]]

Once at the picture wall, kill a level 40 [[Skeleton fremennik]] to get a [[Key (Olaf's Quest)|key]]. [[Crumble Undead]] is useful to kill the skeleton quickly.

Search the [[picture wall]] to find a puzzle on it that must be solved by pulling levers. The pieces must be rotated to get an image of a skull and crossbones. The top lever turns the top and left circles ''anticlockwise''. The left lever rotates the left and bottom circles. The bottom lever rotates the top and bottom circles. Finally, the lever on the right rotates the left and right circles. Once the image is correct, pull the horizontal lever at the very bottom.

The levers in order are: '''right''', '''up''', '''left''', '''down''', and then '''the very bottom'''.
{{Clear|left}}
"""

[[steps]]
index = 4
name = "=The rotten walkway="
links = ["rope", "rotten barrel", "agility potion", "summer pie", "windswept tree", "Skeleton fremennik"]
text = """
[[File:Rotten barrel detail.png|left|80px|frameless]]
[[File:Olaf's Quest walkway.png|thumb|220px|Attaching a rotten barrel to the walkway.]]
Inside the next room, you will find [[rope]]s and [[rotten barrel]]s that can be picked up. Take two barrels and, if you haven't brought them with you, six ropes. If you brought an [[agility potion]] or a [[summer pie]], drink or eat it here to boost your Agility level. Cross the bridge to the north-east and use a barrel on the broken section of the bridge to fix it. Do this again on the next broken section. You may slip and fall off the bridge. If this happens, you will appear just north of Olaf and will have to climb up the hill by the [[windswept tree]] and dig to enter the cave again.

Contrary to popular belief, '''Agility level is the only factor''' in increasing the player's chance of successfully crossing the bridge. The success rate for crossing '''each tile''' of the bridge is <math>Agility Level\\times 0.86 + 32.47 + (Falls \\times 2.4)</math>.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1343522677676527617|date=28 December 2020|archiveurl=https://archive.vn/yWnjf|archivedate=30 December 2020|quote=At level 1 Agility, the first time they try a slippery bit, the success chance is 33.3%.
At level 99 Agility, it starts at 117.6% (guaranteed pass).
Interpolate linearly between those.
Every time they fail, this increases by +2.4%, i.e. the level 1 player gets 35.7%, 38.1%, etc.}} Crossing the entire bridge is guaranteed at {{SCP|Agility|78}}. However, because it rolls for all 12 tiles, there is still only a ~50% probability of crossing the bridge at {{SCP|Agility|73}}. {{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1599709945670213635|date=5 December 2022|archiveurl=https://archive.ph/UGNcs|archivedate=5 December 2022|quote=Looks like every tile, rather than being determined up front.}} At {{SCP|Agility|1}}, the probability per tile is only 33.33%.

[[File:Brine_Rat_Gate.png|thumb|220px|The gate and its subsequent puzzle.]]

There is a locked gate in the middle of the bridge. Try to open it by using your key on it and selecting the right shape, and you will be shown five different locks. '''If you fall after you opened the gate you will have to collect a key again from a [[Skeleton fremennik]] nearby.''' Choose the one that matches the loop of your key, and the gate will open. If you lose your key, or fall off after the door, but before you complete the rest of the bridge, you will need to kill another Skeleton fremennik to get another key to be able to get back through the door.
"""

[[steps]]
index = 5
name = "=Sven's skeletal sentinel="
links = ["Ulfric", "melee", "Protect from Melee", "safespot", "Hitpoints", "Crumble Undead", "salve amulet"]
text = """
[[File:Ulfric.png|left|frameless|80px]]
[[File:Fighting_Ulfric.png|thumb|250px|A player fighting Ulfric.]]
Once through the gate, make your way to the end of the rotten bridge. Again, you can fail, in which case you are washed out of the cave. The final section of the cavern contains a rotten shipwreck containing a treasure chest.

[[File:Olaf's_Quest_-_Safespot.png|thumb|left|200px|Using Ulfric's grave as a safespot.]]
Attempt to open the chest. A level 100 skeleton named Captain [[Ulfric]] will appear from a grave. As he only uses [[melee]] [[Protect from Melee]] is effective; otherwise you may use his grave as an obstacle for a [[safespot]]. It is worth noting that he can teleport to you during the fight. Although the undead Fremennik is strong and accurate, he only has 60 [[Hitpoints]] and can be killed quickly. [[Crumble Undead]] and/or a [[salve amulet]] are also effective.

After defeating Ulfric, search the chest again to claim Sven's treasure and finish the quest.

'''Congratulations, quest complete!'''{{Clear}}
"""
