quest = "Enlightened Journey"
step_count = 4

[[steps]]
index = 0
name = "The aspiring balloonist"
links = ["Entrana", "Auguste", "Frincos's Fabulous Herb Store", "papyrus", "ball of wool", "balloon structure", "unlit candle", "origami balloon", "cutscene", "basket of apples", "Auguste's sapling", "empty sack", "sand pit", "sandbags"]
text = """
[[File:Balloon design.png|thumb|250px|Balloon design]]
{{Needed|3 Papyrus, unlit candle, ball of wool, sack of potatoes, red and yellow dyes, 10 silk, 8 empty sacks, bowl (obtainable during this section from the house just east of Auguste, up the ladder)}}

Travel to [[Entrana]] while obeying its inventory [[Entrana#Rules|rules]] and carrying only the items required for this section. Talk to [[Auguste]], found on the western side of the island, just north of the [[Frincos's Fabulous Herb Store|Herblore shop]].

:'''Note:''' If boosting the requirements, you must boost them all before talking to [[Auguste]]. Once the quest is started, there will be a further skill check of {{SCP|Crafting|36|link=yes}} to add the unlit candle to the origami balloon, and {{SCP|Firemaking|20|link=yes}} to fly the balloon.

Auguste will ask for your help in testing his balloon system. After he shows the player his new design, talk to him again and he will request that you bring a number of items to create some test balloons.

Use the [[papyrus]] on the [[ball of wool]] to create a [[balloon structure]], then use the [[unlit candle]] on it to create an [[origami balloon]]. '''Do not light the balloon or else you will have to get the items again!'''

[[File:Enlightened Journey balloon test.png|thumb|250px|An angry mob destroys the balloon.]]

Talk to Auguste to see a short [[cutscene]] of the balloon launch. After that, talk to him again, and he will take the remaining two pieces of papyrus and the sack of potatoes from you. In a second cutscene, the player launches the next balloon, which is attacked by an angry mob of peasants.

Finally, [[Auguste]] will ask the player to get the materials for a real balloon, as well as give you a [[basket of apples]] and [[Auguste's sapling]].

Use the [[empty sack]]s on the [[sand pit]] to the south of [[Auguste]] to create 8 [[sandbags]], then talk to him again to give him all of the remaining items you have brought with you.

:'''Note''': All of the chat options for giving him items should be used, so if there are some remaining you may have forgotten to bring an item with you.
"""

[[steps]]
index = 1
name = "Ballooning"
links = ["Pest Control", "Minigame Teleport", "Port Sarim", "Auguste's sapling", "willow branches", "Grand Exchange", "tree patch", "Apples", "willow branch", "secateurs", "Entrana", "log storage", "Auguste"]
text = """
{{Needed|12 willow branches, 10 '''regular''' logs (axes cannot be taken to Entrana, obtain the logs before), tinderbox|recommended=additional noted regular/oak/willow/yew/magic logs if you wish to unlock additional routes after the quest}}

Once you have given him all of the items in the previous section, you will need to retrieve the remaining required items. You may consider banking in [[Pest Control]], either using [[Minigame Teleport]] or returning to [[Port Sarim]] and travelling there and back via the ships.

:'''Note:''' If you plan to grow [[Auguste's sapling]] instead of buying the [[willow branches]] on the [[Grand Exchange]], plant the sapling in any [[tree patch]] and give the local farmer the [[Apples|basket of apples]] to look after it. Once it is fully grown, check its health, wait a half hour, then cut [[willow branch]]es from it by using [[secateurs]] on the tree. You can only get 6 branches at once, so you'll need to wait another half hour to get all 12.

Return to [[Entrana]] and use a [[willow branch]] on the balloon basket to start a cutscene. Once it concludes, the [[log storage]] will appear. If you brought additional noted logs, you may store them now.

Talk to [[Auguste]] again. He'll describe some of what the player should notice and some tips on how to fly the balloon. An interface to control the balloon will appear. Manoeuvre through the obstacle course without hitting ''anything'' (including birds, trees, houses, and clouds) and safely ''land'' on the well-marked landing spot on the third screen. See the sections below for an easy route to complete the flight.
"""

[[steps]]
index = 2
name = "=Balloon control panel="
links = []
text = """
[[File:Balloon Controls.png|frame|Balloon Controls panel]]
Clicking any control advances the balloon one "space" to the right.
*The top button (drop sandbag) moves the balloon two spaces up ('''UP 2''').
*The next button (use log) moves the balloon one space up ('''UP 1''').
*"Relax" advances the balloon to the right without changing altitude ('''RIGHT''').
*The normal rope lowers the balloon by one space ('''DOWN 1'''),
*The red rope lowers the balloon by two spaces ('''DOWN 2''').
*Clicking "Bail" will cancel the flight.

The numbers at the side of sack and log buttons correspond to how many times player can use the resources respectively; therefore, fuel is limited. If the player runs out of fuel, they can still "relax" or lower altitude (by pulling ropes).

A tip is that ''how'' the balloon appears to travel is not as important as ''where'' it will end up. If the balloon meets a cloud right above it and a bird in front of it, it is possible to go right through both obstacles by dropping sacks or pulling the red rope (raising and dropping the balloon by 2 spaces respectively). The balloon will fly high or low enough to avoid the bird, and will advance one space forward to avoid the cloud. It might not ''seem'' like the balloon can fit through, but it ''can''.
"""

[[steps]]
index = 3
name = "Navigating the screens"
links = ["logs", "tinderbox", "Entrana", "Auguste"]
text = """
There will be three screens to navigate across. '''The balloon should end up one space above the landing pad, with no air space in between'''. Flying past the landing pad would get the balloon blown away, and getting the balloon in the space with the landing pad would cause it to smash to the ground—in both cases, the flight would be considered unsuccessful. The player needs to restart the flight by preparing the [[logs]] and [[tinderbox]] again before going to [[Entrana]], although they don't have to rebuild the balloon.

There are various ways to control the balloon, and the following is just one of the ''suggested'' paths:

{{:Balloon transport system/Taverley}}

After the balloon has landed, talk to [[Auguste]] to finish the quest. If you wish to unlock additional routes, talk to him after the quest to open the interface and choose the route you wish to unlock.

'''Congratulations, quest complete!'''
"""
