quest = "Lost Lover"
step_count = 2

[[steps]]
index = 0
name = "Starting Out"
links = ["Fabia", "Xilo", "Tlati Rainforest", "Kastori", "Crypt of Tonali"]
text = """
Speak to either [[Fabia]] or [[Xilo]] in the [[Tlati Rainforest]].

* [[Fabia]] can be found by the southern magic trees west of [[Kastori]]. She claims she agreed to meet Xilo by the "magic tree," but Xilo has not arrived.
* [[Xilo]] can be found by the river bank west of the [[Crypt of Tonali]] lift platform. She claims she agreed to meet Fabia by the "special tree," but Fabia has not arrived.
"""

[[steps]]
index = 1
name = "Finishing up"
links = ["Fabia", "Xilo"]
text = """
Speak to either [[Fabia]] or [[Xilo]], whoever you did not speak to first. One will leave their current location to join the other.
"""
