quest = "Big Chompy Bird Hunting"
step_count = 5

[[steps]]
index = 0
name = "Arrows for the hunt"
links = ["chisel", "axe", "knife", "feathers", "wolf bones", "food", "ogre arrows", "Rantz", "Gu'Tanoth", "Gnome glider", "One Small Favour", "Feldip Hills", "Feldip hills teleport", "fairy ring", "chompy bird", "wolves", "safespotted", "wolfbone arrowtips", "Achey Tree", "Achey tree logs", "ogre arrow shaft", "feather", "Ogre arrow shaft", "flighted ogre arrow", "Flighted ogre arrow"]
text = """
[[File:Rantz chathead.png|left]]
{{Needed|[[chisel]], [[axe]], [[knife]], 100 [[feathers]], 4 [[wolf bones]] (or combat equipment to kill level 64 wolves)|recommended=[[food]] for low levels if killing the wolves for the bones|skills={{SCP|Fletching|5}} {{Boostable|yes}} to create [[ogre arrows]]}}
{{Map|name=Rantz|x=2630|y=2981|r=4|width=240|height=240|align=right|mtype=square|caption=The start point of the quest.}}
Talk to [[Rantz]]; he is located south-east of [[Gu'Tanoth]]. Some ways to get to him include using the [[Gnome glider]] (after completing [[One Small Favour]]), [[Feldip Hills]] [[Feldip hills teleport|teleport]], or the [[fairy ring|Fairy rings]] system ({{Fairycode|AKS}}).

Rantz is hungry and wants you to help him make arrows for his unusually large bow, so he can hunt the [[chompy bird]]. The quest '''must be started by talking to Rantz first''', otherwise you will be unable to make the arrowtips. '''Rantz will not accept the arrows unless you make them yourself.'''

If you didn't bring [[wolf bones]], kill 4 level 64 [[wolves]] in the crater to the south-west of [[Rantz]] and pick up the bones. They may be [[safespotted]] by standing near the roots in the north-east of the swamp.

{{Checklist|
*Use a [[chisel]] on the wolf bones to produce [[wolfbone arrowtips]], and you will receive between 2-6 per bone at random ({{SCP|Fletching|5}}).
*Chop down 4 [[Achey Tree]]s nearby for [[Achey tree logs]].
*Use a [[knife]] on the logs to produce some [[ogre arrow shaft]]s ({{SCP|Fletching|5}}).
*Use [[feather]]s on the [[Ogre arrow shaft|shafts]] to produce [[flighted ogre arrow]]s ({{SCP|Fletching|5}}).
*Use the [[Flighted ogre arrow|arrows]] with the [[wolfbone arrowtips|arrowtips]] ({{SCP|Fletching|5}}).
}}
"""

[[steps]]
index = 1
name = "The cave"
links = ["Rantz", "Ogre arrow", "Swamp Toad", "Locked Ogre chest", "Rantz's cave", "Fycie", "Bugs", "ogre bellows", "Mourning's End Part I", "Recipe for Disaster", "Strength", "Unlocked Ogre chest"]
text = """
*Return to [[Rantz]], and give him at least 6 [[Ogre arrow|arrows]]. He then tells you about the [[Swamp Toad|swamp toads]] that his children like to play with.
*Ask Rantz all of the questions that are listed, or else, you won't be able to open the [[Locked Ogre chest|chest]] later.
*Enter the [[Rantz's cave|cave entrance]] north of Rantz.
*Speak to Rantz' children ([[Fycie]] and [[Bugs]]) in the cave. They will inform you that Rantz locked their [[ogre bellows]] in the chest (keep the bellows if you plan on doing [[Mourning's End Part I]] and/or [[Recipe for Disaster]]). The chest is closed and weighted shut with a large rock.
[[File:Big Chompy Bird Hunting - Opening the Ogre Chest.png|thumb|220px|Opening the chest.]]
*Attempt to unlock the chest. Unsuccessful attempts will reduce your [[Strength]] by 1.
*Search the [[Unlocked Ogre chest|chest]] to retrieve the bellows (make sure to search it right away, or it may lock again).
"""

[[steps]]
index = 2
name = "The inflatable toads"
links = ["Rantz", "wolves", "bellows", "swamp bubbles", "Yanille Agility dungeon", "poison spider", "bloated toad"]
text = """
[[File:Big Chompy Bird Hunting - Bloating the toad.png|thumb|220px|Filling the bellows and using it on the toads.]]
*Head back to the south-west of [[Rantz]], where you found the [[wolves]]. They surround a swamp. (see the first picture of the walkthrough.)
*Use the [[bellows]] on the [[swamp bubbles]] in the swamp, at the southern end of the swamp pond. You get three shots with the gas filled bellows before it needs to be filled again. (Swamp bubbles may also be found at [[Yanille Agility dungeon]] near [[poison spider]]s.)
*Use the bellows on a toad again to get a [[bloated toad]], and you will catch it and put it in your inventory. Get three toads. You can only carry a maximum of three bloated toads; inflating more will simply replace one toad in your inventory.
"""

[[steps]]
index = 3
name = "The chompy and the hunt"
links = ["ogre bow", "Rantz", "chompy bird", "comp ogre bow", "raw chompy", "Grand Exchange"]
text = """
{{Needed|skills={{SCP|Ranged|30}} {{Boostable|no}} to equip the [[ogre bow]]}}
*Return to [[Rantz]] and talk to him. He will show you where you need to place the toads to lure the [[chompy bird]]s out.

*'''Drop''' some toads on the spot (a yellow flashing arrow will mark it), then walk closer to Rantz. Don't stay too close to the bait, but make sure it is in visible range. On a successful lure, a chompy bird will appear. Occasionally, the lure will be unsuccessful and the bait will disappear; if this happens, drop another toad. Rantz will take a shot at it, but he will miss. He will complain that the arrows don't fly straight.
*Talk to Rantz and offer to help shoot for him. He will agree and give you his [[ogre bow]]. (If you're quick getting the bow, the already spawned chompy bird can be killed. The ogre bow or [[comp ogre bow]] are used during Recipe for Disaster, so be sure to hold on to either if planning to do that quest too).
*Head back down to the clearing and place another toad (it doesn't have to be on the exact tile indicated at first).
*Wield the bow ({{SCP|Ranged|30}}) and arrows and when the bird appears, range it. If the bird doesn't appear or it flies away before you can kill it, keep placing bloated toads to lure the Chompies back.
*Once you kill a Chompy, pluck the carcass and take the [[raw chompy]] back to Rantz. He now wants you to cook it as well. '''In order to progress, you must kill the chompy yourself.''' Purchasing a raw chompy from the [[Grand Exchange]] or another player will not allow you to move forward in the quest.
"""

[[steps]]
index = 4
name = "Cooking the chompy bird"
links = ["raw chompy", "Rantz", "Chompy", "Doogle leaves", "Onion", "Tomato", "Cabbage", "Potato", "Equa leaves", "onions", "stool", "tomato", "glider", "willow tree", "Seasoned chompy"]
text = """
{{Needed|skills={{SCP|Cooking|30}} {{Boostable|yes}} to cook [[raw chompy]]}}
[[File:Big Chompy Bird Hunting - Cooking the Chompy.png|thumb|220px|Cooking the Chompy!]]
[[Rantz]] will name a special ingredient that he wants the bird to be cooked with. He will also tell you to ask the children what they would like the bird seasoned with.
*Travel to the cave, and ask each of the two Ogre children what they want the [[Chompy]] seasoned with. In all, you will need three different ingredients, but only one bird.
{{Map|mtype=pin|align=right|caption=Seasoning locations.
|x:2562,y:2972,title:[[Doogle leaves]],desc:
|x:2583,y:2965,title:[[Onion]],desc:
|x:2584,y:2966,title:[[Tomato]],desc:
|x:2587,y:2973,title:[[Cabbage]],desc:
|x:2642,y:2959,title:[[Potato]],desc:
|x:2639,y:2952,title:[[Equa leaves]],desc:
|x:2630,y:2981,title:[[Rantz]],desc:
}}
*It's different from player to player what the ogres want on the Chompy, but here's a quick list of where to get it all:
**'''[[Onion]]:''' A little bit to the west-south-west of Rantz, there's a fire near the tomato spawn. The [[onions]] are growing next to the [[stool]] where you find the [[tomato]]. Right click on the grassy shoots and pick them. You may instead receive an onion seed; simply pick another plant if this happens.
**'''[[Doogle leaves]]:''' To the west, east of the [[glider]].
**'''[[Equa leaves]]:''' Three equa leaves spawn on a small peninsula by some [[willow tree]]s, south-east of Rantz.
**'''[[Tomato]]:''' West-south-west of Rantz, near the ogres and in the same area as the onion plants. It spawns on top of a stool.
**'''[[Potato]]:''' A bit south-east of Rantz near the equa leaf spawns, there are potato plants; pick one to get the potato. You may instead receive a potato seed; simply pick another plant if this happens.
**'''[[Cabbage]]:''' Several cabbage plants are scattered throughout the area, the closest ones are either south-west of Rantz (north of the tomato and onions) or south-east of him (by the potatoes and equa leaves). You may instead receive a cabbage seed; simply pick another plant if this happens.
*Use the bird on the spit north of Rantz while holding all three ingredients ({{SCP|Cooking|30}}). Present Rantz with his delicious [[Seasoned chompy|seasoned cooked chompy]] bird.

'''Congratulations, quest complete!'''
"""
