quest = "Getting Ahead"
step_count = 3

[[steps]]
index = 0
name = "A Strange Event"
links = ["Pot of flour", "Gordon", "Gordon and Mary's farm", "Farming Guild", "Shayzien soldier", "lizardmen", "Mary (Getting Ahead)", "pot of flour", "needle", "thread", "flour (Getting Ahead)", "hammer", "Flour (Getting Ahead)"]
text = """
{{Needed|[[Pot of flour]]}}
[[File:Gordon chathead.png|left]]
[[File:Getting Ahead - pouring flour on gate.png|thumb|250px|Pouring flour over the gate.]]
Start the quest by speaking to [[Gordon]] in [[Gordon and Mary's farm|his and his wife's farm]], just south of the [[Farming Guild]]. Ask him if he needs a hand with anything, and he'll tell you that some strange beast has been stealing his livestock, and is seeking an adventurer to help them, as the [[Shayzien soldier]]s are too busy dealing with [[lizardmen]] to help. Agree to help him, and he'll tell you he doesn't exactly know where the beast is, but he'll tell you to try asking his wife, [[Mary (Getting Ahead)|Mary]], who is in their house.

Mary will tell you that the beast only comes in the night, so they've never had the chance to get a proper look at it. She suggests, however, that if the beast was coated in flour, it might be easier to track down.

If you don't already have a [[pot of flour]], go upstairs and take one. While here, take the [[needle]] and [[thread]] as well, as you'll need them later. Talk to Gordon again, who will tell you that the beast has been mainly targeting their cattle, and he had built a gate by their pen to try to keep it out. Use the pot of flour on the southern gate (just north of the bridge), and you'll begin to see a [[flour (Getting Ahead)|trail of flour]] going southward. Before tracking the beast, take the [[hammer]] by the gate to use towards the end of the quest.
{{Map|1255,3684|1256,3678|1255,3665|1248,3658|1236,3657|1226,3656|1217,3655|1213,3649|mtype=line|ptype=object|align=right|caption=The trail of [[Flour (Getting Ahead)|flour]]}}
"""

[[steps]]
index = 1
name = "A Strange Beast"
links = ["Kebos Lowlands mine", "plank", "Headless Beast's Lair", "Headless Beast", "Skeleton (Getting Ahead)", "Neilan's journal"]
text = """
{{Needed|Combat equipment}}
[[File:Getting Ahead - fighting Headless Beast.png|thumb|250px|A player fights the Headless Beast from a safespot.]]
Follow the trail of flour, which ends at the [[Kebos Lowlands mine]]. Before entering the cave, take the two [[plank]]s by the broken rowboat and mine some clay, as it will be used later. Enter the [[Headless Beast's Lair|cave]] to do battle with the [[Headless Beast]].

The [[Headless Beast]] uses melee attacks, and has a special attack in which it slams the ground, resulting in a large rock crashing on the player. The rock can be avoided by stepping away before it hits the ground. The beast can be safespotted by trapping it around the pond, where it will never perform the special attack.

Upon killing the beast, search the [[Skeleton (Getting Ahead)|skeleton]] nearby to receive [[Neilan's journal]], revealing the beast was the work of a necromancer from the mainland. Return to Gordon, who refuses to pay you as you can't prove you've killed the beast.
"""

[[steps]]
index = 2
name = "A Strange Fake"
links = ["Soft clay", "knife", "bear fur", "needle", "thread", "red dye", "hammer", "saw", "plank", "soft clay", "clay head", "Kebos Lowlands mine", "fur head", "Shelves (Getting Ahead)", "bloody head", "Ghosts Ahoy", "yellow dye", "ancient machinery", "iron nails", "Plank"]
text = """
{{Needed|[[Soft clay]], [[knife]], [[bear fur]], [[needle]], [[thread]], [[red dye]], [[hammer]], [[saw]], two [[plank]]s, six nails of any kind}}

Talk to Mary, who suggests to have you make a fake head via the use of clay modelling to fool her husband. Use a [[knife]] and a piece of [[soft clay]] to create a [[clay head]], and return to Gordon. (If you need to soften the clay you mined at the [[Kebos Lowlands mine]] then take advantage of the bucket spawn and the sink which are in the same room as Mary.) Still not convinced, add [[bear fur]] to the head (while having a [[needle]] and [[thread]]) to create a [[fur head]] and speak to him again. He will remain unconvinced, so add a [[red dye]] (found by searching the [[Shelves (Getting Ahead)|shelves]] next to the stairs in the house) to create a [[bloody head]].

:'''Tip''': If you haven't yet completed [[Ghosts Ahoy]], you can grab three extra red dye and three [[yellow dye]] for free here and save them for the quest.

[[File:Getting Ahead - Gordon fooled.png|thumb|250px|Gordon is fooled by the mounted head, much to your and Mary's relief.]]

The bloody head will finally convince him, and he asks that you mount the head in his house. A Mounted Head Space will appear by the staircase in the house. Players will need a [[hammer]], [[saw]], nails of any kind, and two [[plank]]s.

A hammer can be found by the gate where you poured the flour, while the saw can be found by the small barn with the [[ancient machinery]]. The workbench inside can also be searched for twenty [[iron nails]]. [[Plank]]s can be found just west of the entrance to the Headless Beast Cave. After mounting the bloody head, return to Gordon once more.

'''Congratulations, quest complete!'''
"""
