quest = "Pirate's Treasure"
step_count = 4

[[steps]]
index = 0
name = "Captain Redbeard"
links = ["coins", "Redbeard Frank", "Port Sarim", "Karamjan rum", "Monk of Entrana", "Karamja", "Ring of Charos (a)"]
text = """
{{Needed|60 [[coins]].}}
[[File:Redbeard Frank chathead.png|left|frameless|100px]]
Talk to [[Redbeard Frank]] located in front of the northernmost dock in [[Port Sarim]]. Tell him you are in search of treasure, and he will ask you to bring him some [[Karamjan rum]] before he'll tell you where to find some.

Walk south on the docks to see three sailors (NOT the [[Monk of Entrana|Monks of Entrana]]). Talk to any one of these sailors to board the ship to [[Karamja]] for 30 [[coins]] (free using a [[Ring of Charos (a)]]).
{{Clear}}
"""

[[steps]]
index = 1
name = "Rum smuggling"
links = ["coins", "Karamja Wines, Spirits, and Beers", "Zembo", "Karamjan rum", "Customs officer", "Asgarnia", "random event", "banana", "Luthas", "Crate (Pirate's Treasure)", "Wydin", "Port Sarim", "Ring of charos (a)"]
text = """
{{Needed|30 [[coins]].}}
{{Map|name=Pirate's Treasure crate|x=2939|y=3149|r=1|mtype=pin|align=right|caption=Location of the crate used to hide the rum.|width=200|height=200}}
[[File:Zembo chathead.png|left|frameless]]
When you arrive in Karamja, follow the path to the west and enter the [[Karamja Wines, Spirits, and Beers|bar]]. Trade with [[Zembo]] and buy one [[Karamjan rum]].

'''Do not leave the island''' with the rum - it will be confiscated by the [[Customs officer|officers]] as [[Asgarnia]] has banned the import of intoxicating spirits. The bottle will also break if you teleport or accept a [[random event]] where you would be temporarily teleported.

You will need to find a method to smuggle the rum off the island. First, pick 10 [[banana]]s from the plantation to the north. Then talk to [[Luthas]] in his hut to the east of the plantation and ask him for a job, and he will hire you as his worker.

Outside the south east corner of his hut is a [[Crate (Pirate's Treasure)|crate]]. Use the rum on it to hide it in the crate, then "Fill Crate" on it to fill it with bananas.

'''Note''': If you get a message saying "Why would I want to do that?" make sure you have asked for employment first.

Talk to Luthas again and he will pay you 30 coins for loading the crate. Ask him where the crate goes, and he will tell you they go to [[Wydin]], who owns the food store in [[Port Sarim]]. Travel back to Port Sarim at the customs officer to the east for 30 coins (free with [[Ring of charos (a)]]).
"""

[[steps]]
index = 2
name = "Retrieving the rum"
links = ["Varrock Teleport", "Falador Teleport", "Gerrant's Fishy Business", "white apron", "Wydin", "Wydin's Food Store", "Crate (Food Store, banana)", "banana", "Redbeard Frank", "Chest key (Pirate's Treasure)", "Varrock", "Blue Moon Inn", "One-Eyed Hector", "pirate message"]
text = """
{{Map|name=Chest|x=3219|y=3396|plane=1|mtype=pin|align=right|caption=Location of Hector's chest.|width=200|height=200}}
{{Needed|recommended=a teleport to [[Varrock Teleport|Varrock]] and [[Falador Teleport|Falador]].}}
[[File:Wydin chathead.png|left]]
Once you are in Port Sarim, make a quick stop at [[Gerrant's Fishy Business|the fishing shop]] just to the west. Hanging on the back wall is a [[white apron]]. Take it and wear it.

Talk to [[Wydin]] at his [[Wydin's Food Store|food store]] directly south of the fishing shop, and ask him for a job. He will agree as long as you are wearing your [[white apron]]. Enter the back room and search the [[Crate (Food Store, banana)|crate]] with a [[banana]] on top of it. You will find the rum. '''Do not teleport with it in your inventory (including random events).''' Head back to [[Redbeard Frank]] and give him the drink.

Frank will give you a [[Chest key (Pirate's Treasure)|key]] to the chest found upstairs in [[Varrock|Varrock's]] [[Blue Moon Inn]], owned by the now deceased [[One-Eyed Hector]]. Travel to [[Varrock]] and head to the [[Blue Moon Inn]] located just north of the city's southern gate. Go upstairs and find the chest in the room at the end of the hall. Use the key on the chest to find a [[pirate message]]. It will give you a clue to the treasure's location. '''Be sure to read the clue'''.
"""

[[steps]]
index = 3
name = "Buried treasure"
links = ["Spade", "pirate message", "weapon", "Saradomin", "gardener"]
text = """
{{Needed|[[Spade]], [[pirate message]]|recommended=A [[weapon]].}}
[[File:Gardener chathead.png|left]]
[[File:Pirate's Treasure - Buried treasure location.png|thumb|200px|Location of the buried treasure.]]
Travel to Falador Park, located in the north of Falador. If you don't yet have a spade, grab one from the estate agency just south-west of the park. Find the statue of [[Saradomin]] in the middle of the park, and notice where it's pointing. Note the configuration of the dirt, which vaguely makes an X. Stand in the middle of the dirt "X" and dig.
An angry level-4 [[gardener]] will appear out of nowhere and attack you. You will be unable to dig again until you either kill him, or run out of the park to despawn him. Dig again in the same spot to get a casket and complete the quest.
{{Map|name=Chest|x=2999|y=3383|plane=0|mtype=pin|align=right|caption=Location of the buried treasure.|width=200|height=200}}

'''Congratulations, Quest Complete!'''
"""
