quest = "Dwarf Cannon"
step_count = 3

[[steps]]
index = 0
name = "The Black Guard"
links = ["Captain Lawgof", "Fishing Guild", "coal trucks", "Dwarven Black Guard", "railing", "hammer", "Strength", "Crafting", "Gilob", "Lollk"]
text = """
{{Needed|recommended=Fast travel to the Goblin Cave, Dwarven Mine, and return trip to Coal Trucks for future sections}}
[[File:Dwarf Cannon - Broken railing.png|thumb|300px|Broken railing in need of repair.]]
[[File:Captain Lawgof chathead.png|left]]
Talk to [[Captain Lawgof]] beyond the gates north of the [[Fishing Guild]], south-west of the [[coal trucks]]. You can enter the fenced area from the south, or cross the log from the east with {{SCP|Agility|20|link=yes}}.

Captain Lawgof will ask if you would like to be made an honorary member of the [[Dwarven Black Guard]]. Goblins are attacking from the south, and they are in need of a hero to prevent them from breaking through their perimeter. He will give you 6 [[railing]]s and a [[hammer]] (if you do not already have one in your inventory) to replace the broken railings.

Locate the railings in the fence that need to be repaired (zoom in to find any looking bent from the front or back). '''Inspect''' the railing to attempt to repair it; if you fail you may take 1 or 2 damage or your [[Strength]] or [[Crafting]] will be temporarily reduced. It may take several attempts, but you will see {{Mes|The railing is now fixed}} in the chat once you are successful.

After repairing all 6 rails, talk to Captain Lawgof again and he will explain that since they've been overrun, communication was lost with their watchtower to the south. He wants you to find [[Gilob]], the dwarf-in-charge at the tower to tell him they will send over a relief guard.

Head south of the gate to find the watchtower (ladder on the map). Climb the ladder to the top floor and retrieve the dwarf remains, then take them back to Captain Lawgof.

Devastated, Captain Lawgof will tell you that the now deceased Gilob had a son named [[Lollk]] with him that is still missing. He wants you to seek out the goblin's hideout and find him.
{{Clear|left}}
"""

[[steps]]
index = 1
name = "The missing son"
links = ["Lollk", "Goblin Cave", "Fishing Guild", "Crate (Dwarf Cannon)"]
text = """
[[File:Lollk chathead.png|left|frameless]]
[[File:Dwarf Cannon - Lollk.png|thumb|right|220px|Location of the [[Lollk|dwarf child]] in the [[Goblin Cave]].]]
Head to the south-east to find the [[Goblin Cave]], located just outside of the south-eastern corner of the [[Fishing Guild]].

The cave forks into three passages. Take the centre passage and head north-west to find the goblin outpost. Go further north-west to a room filled with crates inside. Search the northernmost [[Crate (Dwarf Cannon)|crate]] on the east wall (as seen in the picture) and Lollk will jump out. After thanking you for rescuing him, Lollk will run back to Captain Lawgof.
{{Clear|left}}
"""

[[steps]]
index = 2
name = "The dwarven multicannon"
links = ["Captain Lawgof", "toolkit", "Nulodion", "Ice Mountain", "combat bracelet", "Falador", "skills necklace", "Mining Guild", "ammo mould", "Nulodion's notes"]
text = """
[[File:Nulodion chathead.png|left|frameless|70px]]
[[File:Toolkit interface.png|thumb|220px|right|The interface shown when using the toolkit on the damaged cannon.]]
Return to [[Captain Lawgof]], who will thank you, then ask for one more favour. Goblins have sabotaged  their cannon, and nobody knows how to fix it. Use the [[toolkit]] he gives you on the cannon. You need to match up the three tools with the three parts on the screen that shows up in this order:

#Use the pliers on the safety switch at the bottom. (2nd tool)
#Use the hooked tool on the spring. (3rd tool)
#Use the toothed tool on the gear located at the bottom of the hammer, on the gear. (1st tool)

Talk to Captain Lawgof again, who thanks you but admits that he doesn't know what ammo to use for the cannon as the Black Guard forgot to send instructions. He wants you to ask [[Nulodion]] at the dwarf base south of [[Ice Mountain]] for advice.

{{Map|name=Nulodion|x=3012|y=3452|r=4|mtype=square|width=220|height=220|align=left|caption=[[Nulodion]]'s location.}}
The fastest way to arrive there is using a [[combat bracelet]] to teleport to the monastery. Alternatively you can teleport to [[Falador]] and walk there or use a [[skills necklace]] to teleport to the [[Mining Guild]]. Talk to [[Nulodion]] who is in the western building of the base. He will give you an [[ammo mould]] and his [[Nulodion's notes|notes]]. You must bring '''both''' items to Captain Lawgof, who will reward you for your efforts.

'''Congratulations, quest complete!'''
{{Clear}}
"""
