quest = "The Hand in the Sand"
step_count = 5

[[steps]]
index = 0
name = "Sandy hand"
links = ["Beer", "Bert", "Yanille", "POH portal", "sandy hand", "Guard Captain", "Dragon Inn", "Ye Olde Dragon Inn", "beer", "bartender", "coins", "beer soaked hand", "Wizards' Guild", "Magic", "Zavistic Rarve", "Clarence"]
text = """
{{Needed|[[Beer]]}}
[[File:Bert chathead.png|left]]
Start the quest by talking to [[Bert]] in [[Yanille]] in the building just east of the [[POH portal]]. He works in the sandpit but has found a severed hand and is afraid to tell the authorities for fear of losing his job. Agree to lend him a hand and you will receive a [[sandy hand]]. He'll tell you to go talk to the [[Guard Captain|captain of the guards]]. He hangs around [[Dragon Inn|the inn]] in Yanille, usually drunk.

Take the hand to the captain of the guards in the [[Ye Olde Dragon Inn]]; he'll demand a beer. Give him a pint; a cheap [[beer]] can be bought from the [[bartender]] for two [[coins]]. He will ramble on, and then, he'll take a look at the hand and accidentally drop it in his beer, turning it into a [[beer soaked hand]]. He suggests it was probably the wizards who did it and suggest you ring the bell of their guild and talk to 'the first pointy hatted ninny you shee.'

Go to the [[Wizards' Guild]], east of the bar; enter if you meet the requirements (66 [[Magic]]), or ring the bell to make [[Zavistic Rarve]] come out. Talk to him to wave the hand in front of his face and enquire whether the guild still has all of its wizards. You explain the situation and hand him the hand. He will tell you that this is the hand of one of his wizard students, [[Clarence]]. He'll ask you to see if Bert's working schedule has changed recently, for he has been working rather long hours recently.
"""

[[steps]]
index = 1
name = "Sandy the slavedriver"
links = ["Bert", "Sandy's Sand Corp", "Brimhaven", "Bert's rota", "Sandy", "Ardougne", "coins", "Dead Man's Chest", "pickpocket", "sand"]
text = """
{{Map|2790,3176|rectX=8|rectY=7|mtype=rectangle|align=right|caption=Sandy's whereabouts.}}
Return to [[Bert]]'s home and talk to him again. He'll tell you that he works for [[Sandy's Sand Corp]], which is based in [[Brimhaven]], by hauling sand from there to the pit in Yanille. He'll give you a copy of his [[Bert's rota|schedule]] and tell you that it hasn't changed recently, or so he thinks. Now, you need to head to [[Sandy]] in Brimhaven to compare Bert's rota with the original. You can go to [[Ardougne]] and pay 30 [[coins]] to get to Brimhaven. Sandy is located in the office just north-west of the [[Dead Man's Chest]] bar.

[[File:Sandy chathead.png|left]]
In Brimhaven, you'll see Sandy in his office. You can talk to him first if you want, but this isn't necessary. Search his desk in the house to get Bert's old schedule. Read it and compare it to the other schedule to see that Bert has indeed been working longer hours. While you're here, [[pickpocket]] Sandy to find some [[sand]] in his pocket — this may take multiple attempts. Keep it; it will become important later on in the quest.
"""

[[steps]]
index = 2
name = "Truth serum"
links = ["Bert's rota", "Sandy's rota", "white berries", "redberries", "lantern lens", "sand", "Sandy", "vial", "Bert", "Yanille", "a magic scroll", "Zavistic Rarve", "Wizards' Guild", "Betty", "Port Sarim", "truth serum", "magical orb", "minimap", "bottled water", "redberry juice", "pink dye", "rose-tinted lens", "earth rune"]
text = """
{{Needed|[[Bert's rota]], [[Sandy's rota]], [[white berries]], [[redberries]], [[lantern lens]], [[sand]] (pickpocketed from [[Sandy]]), empty [[vial]].|recommended=A second empty [[vial]]}}

Now, you need to visit [[Bert]] once more. Talk to Bert in [[Yanille]] to inform him of his changed hours. He will not remember it and blame it on the wizards and the magic leaking from their nearby guild. You give him the rotas in exchange for [[a magic scroll]] that appeared in his house recently. He instructs you to see whether 'those infernal wizards' are up to anything.

Take the scroll to [[Zavistic Rarve]] at the [[Wizards' Guild]] to learn that it's a mind-altering scroll, explaining why Bert doesn't remember his hours' changing. You suspect [[Sandy]] is behind it and Zavistic asks you to first get [[Betty]] in [[Port Sarim]] to make you a [[truth serum]] and then record Sandy using the [[magical orb]] he gives you. If you ask him to help you more, he will teleport you to Betty's shop just once in exchange for an empty [[vial]].

[[File:Betty chathead.png|left]]
[[Betty]] can be found in a small shop marked by the [[File:Magic shop icon.png|frameless]] icon on the [[minimap]]. Talk to Betty about the quest and she will ask for another empty vial. In return, she gives you some [[bottled water]]. You need to add redberries to make [[redberry juice]], then add white berries to make [[pink dye]]. Once you've made some, use it on a [[lantern lens]] to create a [[rose-tinted lens]].

Talk to Betty again. She tells you to stand in the doorway while the door is open and shine your lens at the counter to focus the light on an empty vial whilst she pours the [[truth serum]] into it. Do so by clicking on the lens in your inventory, then using it on the counter. This will heat up and shatter the lens. Speak to Betty again; you now need a personal item from Sandy for the potion to work.

Return to Sandy's office and pickpocket him to get some loose [[sand]] if you had not already. Return to Betty for her to finish the serum with the handful of sand. She warns you that you should dilute the serum in tea or coffee or else 'bits' might drop off the drinker.

Make sure to buy five [[earth rune]]s from Betty before you leave if you don't have them already.
"""

[[steps]]
index = 3
name = "Sandy Truth-Be-Told"
links = ["Truth serum", "magical orb", "Brimhaven", "Sandy", "Bert"]
text = """
{{Needed|[[Truth serum]], [[magical orb]]}}
[[File:The Hand in the Sand - Sandy confesses.png|thumb|220px|Sandy confesses to killing Clarence, thanks to the truth serum.]]
Back in [[Brimhaven]], return to [[Sandy]]. He has a mug of steaming coffee next to him, but will require distraction for you to be able to add the truth serum. Get him distracted with tall tales of herds of giant mutant herrings and pygmy shrews. Try all the options, as there is no guaranteed one that will work. Once he looks out the window, use the [[Truth serum|serum]] on his coffee. He will drink it. Next, activate your [[magical orb]] and talk to him.

He'll confess that he bribed a wizard to put a mind-altering spell on [[Bert]]. He then changed Bert's schedule so that he'd work longer for the same salary. Afterwards, Sandy killed the wizard so that he wouldn't have to pay him; then, he buried parts of him in all of the sandboxes around Gielinor. This fills the magical orb; return to Zavistic in Yanille to show him the evidence.
"""

[[steps]]
index = 4
name = "And Sandy said, "Drat- foiled again!""
links = ["earth rune", "bucket of sand", "magical orb", "Sandy", "sandpit", "Bert", "Entrana", "Mazion", "wizard's head", "Clarence", "Ardougne Diary"]
text = """
{{Needed|5 [[earth rune]]s, a [[bucket of sand]].}}
[[File:Magically refilled sandpit.gif|thumb|220x220px|The sand magically refills, thanks to Zavistic Rarve.]]
Hand Zavistic Rarve the [[magical orb]] in your inventory - it is proof of [[Sandy]]'s confession. He asks for five [[earth rune]]s and a [[bucket of sand]], refusing to tell you why. Bring these to him. A bucket can be filled at Bert's [[sandpit]] if necessary. He will then cast a spell on [[Bert]]'s sandpit to magically refill itself to compensate Bert for his troubles. He will no longer have to work! Zavistic says he has sent wizards around the various sandpits of RuneScape to find the remains of Clarence and asks you to check on the [[Entrana]]n one.

Go to Entrana (there is a bank deposit box at Port Sarim to deposit all armour and weapons before going to the holy island). Talk to [[Mazion]] by the sandpit to get the dead [[wizard's head]]. Give this to Zavistic Rarve. He'll confirm that it belongs to [[Clarence]] and that the wizard will be buried the same day. He has also sent word for Sandy to be arrested and gives you a reward for your help.

'''Congratulations, quest complete!'''

'''Tip:''' Speak to Bert right after completing the quest to complete a medium [[Ardougne Diary]] task.
"""
