quest = "The Depths of Despair"
step_count = 3

[[steps]]
index = 0
name = "The Envoy to Varlamore"
links = ["Arceuus Library", "Galana", "Varlamore envoy", "Crabclaw Caves", "Woodcutting Guild"]
text = """
Travel north to the [[Arceuus Library]] which can be found next to Tower of Magic.  '''Tip''': a fairy ring can be found nearby (code: {{Fairycode|CIS}}).

Speak to [[Galana]], who is found in the north-eastern segment on the ground floor. She will suggest you find a book called [[Varlamore envoy]], the location of which is random for each player. Ask her where it is and search the bookcases in that area until you find it—each square in game is its own bookshelf, so be thorough.

'''Note:''' If you log out before finding the book, make sure to speak to [[Galana]] again, as the location may have changed.

Read the book, and you will discover that the original copy of the Accord was lost at sea, and that the ship carrying it sunk into the [[Crabclaw Caves]], whose entrance is found south of the [[Woodcutting Guild]], marked with the [[File:Dungeon map link icon.png]] icon. (If you don't read the book, a message saying "You have no reason to go in there." will appear in the chat when you try to enter the Crabclaw Caves.) Skill necklace teleport to Woodcutting Guild or row boat to land's end.
"""

[[steps]]
index = 1
name = "The Crabclaw Caves"
links = ["Crabclaw Caves", "Crabclaw Isle", "Hitpoints", "Agility", "Sand Crab", "Kourend & Kebos Diary", "Artur Hosidius", "Sand Snake", "magic", "Royal Accord of Twill", "max hit"]
text = """
{{Instance}}
{{Needed|Weapons, armour, and food}}
[[File:The Depths of Despair - Crabclaw Caves entrance.png|thumb|left|200px|The entrance to the Crabclaw Caves.]]
Make your way into the [[Crabclaw Caves]] (not [[Crabclaw Isle]]), which are found by heading south from the Woodcutting Guild or Hosidius West mine cart for 20 gp. ({{Map|type=maplink|x=1644|y=3449|mtype=pin}})

Once inside the cave follow the path east, then south through a crevice. Follow the path over the Stepping Stones and through the rocks. If your [[Hitpoints]] level and [[Agility]] level are both low, you might want to bring some food in case you fall while attempting to cross the stepping stones or rocks, and for the upcoming fight.

'''Note:''' Killing a [[Sand Crab]] is an Easy Task in the [[Kourend & Kebos Diary]].
[[File:The Depths of Despair - Fighting Sand Snake.png|thumb|250px|The player fights the Sand Snake.]]
At the end of the caves, climb down the tunnel entrance to find [[Artur Hosidius]]. He believes the chest further ahead contains the original Accord, but it is guarded by a [[Sand Snake]]. As he is not good at fighting, he asks you to kill it for him. Climb the rocks ahead, and kill the Sand Snake. It is weak to [[magic]], so magical attacks are recommended to kill it quickly. Once you have killed the Sand Snake, search the chest, which contains the original [[Royal Accord of Twill]].
[[File:The Depths of Despair - sand snake safespot.mp4|thumb|left|250px|Setting up the safespot for the sand snake.]]
'''Tip:''' The sand snake can be safespotted by going all the way either north or south along the west wall. Once the snake is near or attacks you, continue hugging the west wall and walk back to the centre entrance where the rubble is. Note that the [[max hit]] of the snake is 3.
"""

[[steps]]
index = 2
name = "Finishing up"
links = ["Hosidius", "Lord Kandur", "the Accord"]
text = """
Return to the [[Hosidius]] family's house, and speak to [[Lord Kandur]]. He will take [[the Accord]], and give you your reward.

'''Congratulations, quest complete!'''
"""
