quest = "At First Light"
step_count = 3

[[steps]]
index = 0
name = "A Missing Fox"
links = ["Quetzal", "Primio", "Varrock", "Civitas illa Fortis", "Twilight's Promise", "Renu", "Hunter Guild", "Guildmaster Apatura", "Guild Scribe Verity", "The Burrow", "rumours", "Huntmaster Gilman (Novice)", "Guild Hunter Fox", "Guild Hunter Wolf (Master)", "Guild Hunter Kiko", "toy mouse", "Outer Fortis", "pyre fox"]
text = """
[[File:Guildmaster Apatura chathead.png|left|Guildmaster Apatura Chathead]]
Take the [[Quetzal]] [[Primio]] just outside of the [[Varrock]] east gate to go to [[Civitas illa Fortis]]. If [[Twilight's Promise]] is completed you can use [[Renu]] right next to where you land to quickly go to the [[Hunter Guild]], otherwise run just south-west of the city. Speak to [[Guildmaster Apatura]] in the [[Hunter Guild]], in the building with the oven. Ask her if she needs any help, and she will tell direct you to [[Guild Scribe Verity]]. Verity is found in the [[The Burrow|Burrow]], the guild's underground pub, which can be accessed via the stairs inside the large tree.

Speak to Verity behind the counter. She will introduce you to the guild's [[rumours]] system, then tell you that she and [[Huntmaster Gilman (Novice)|Gilman]] are concerned about [[Guild Hunter Fox|Fox]], who left without informing anyone of his whereabouts. She will add that [[Guild Hunter Wolf (Master)|Wolf]] had put him up to the hunt, and asks that you speak to her for information.

Wolf will tell you that she asked Fox to make some repairs to the bed of [[Guild Hunter Kiko|Kiko]], the grey cat nearby, which has recently become tatty, and assumes he's out to get the required materials. To distract Kiko so you can inspect his bed, Wolf will give you a [[toy mouse]]; wind it up and then use it on Kiko. Once Kiko is distracted, attempt to check the cat bed. You will find that the bed is made of a fluffy fur and that someone has cut off a small bit of it.

Be warned, if you use your cat to catch the toy mouse it will disappear and you will have to find another one yourself.

Talk to Wolf again, who will tell you that Fox has likely gone to [[Outer Fortis]] to meet a contact who stocks good quality fabrics, and guesses that he is hunting [[pyre fox]]es along the way there.
"""

[[steps]]
index = 1
name = "Fox Tracking"
links = ["Box trap", "hammer", "Avium Savannah", "Guild Hunter Fox", "jerboa tail", "leafy bush", "smooth leaf", "Locus Oasis", "rough-looking bush", "sticky leaf", "Jerboa tail", "embertailed jerboa", "box trap", "makeshift poultice", "fur sample", "Atza", "Civitas illa Fortis", "pile of equipment", "trimmed fur", "Fox's report"]
text = """
{{Needed|[[Box trap]], [[hammer]]}}
{{Map|zoom=1|mtype=pin|align=right|caption=Key locations:<br>
'''Red:''' Guild Hunter Fox and smooth leaves.<br>
'''Yellow:''' Sticky leaves and embertailed jerboas.<br>
'''Green:''' Atza
|1618,2979,icon:redPin,desc:Guild Hunter Fox/smooth leaves
|1673,2992,icon:yellowPin,desc:Sticky leaves and jerboas
|1697,3064,icon:greenPin,desc:Atza}}
Make your way to the [[Avium Savannah]] mining site, just south-east of the guild. [[Guild Hunter Fox|Fox]] will be found, laying injured, on the south-east side of the crevice there. Dazed, he tells you that he was attacked and cannot move, and that to help him recover, he'll need two plants to make a poultice, as well as a [[jerboa tail]] to hold them together.

The first plant can be found immediately west, as a brownish [[leafy bush]]; pick a [[smooth leaf]] from it. The second plant is found by the western end of the [[Locus Oasis]], also as a brownish [[rough-looking bush]]; pick a [[sticky leaf]] from it. If you don't have two [[Jerboa tail|jerboa tails]], catch [[embertailed jerboa|embertailed jerboas]] northwest of the Locus Oasis with a [[box trap]] to acquire them.

Combine the three items to create the [[makeshift poultice]], and return to Fox. He will feel better and tell you that he was attacked and knocked unconscious whilst on a hunt, and so cannot identify his attacker. However, he will ask that you deliver a [[fur sample]] to someone named [[Atza]] to acquire the fur needed for Kiko's bed.

Atza is found in one of the buildings just south-east of the South gate of [[Civitas illa Fortis]] (note: not the south-east gate), which contains a [[pile of equipment]] in the middle. She will have the fur, but needs to find it. There is a hammer spawn in the house directly north of her. Set up the aforementioned pile of equipment for her and finish the conversation to obtain the [[trimmed fur]].

Bring the fur to Fox, who will ask that you let Wolf and Verity know that he's doing fine. He will ask that you repair Kiko's bed, as well as deliver [[Fox's report|his report]] to Verity.
"""

[[steps]]
index = 2
name = "Finishing up"
links = ["Jerboa tail", "needle", "costume needle", "Hunter Guild", "Guildmaster Apatura"]
text = """
{{Needed|[[Jerboa tail]] and either a [[needle]] or [[costume needle]]}}
Return to the [[Hunter Guild]] and deliver Fox's report to Verity in the Burrow pub, then repair Kiko's bed.

Lastly, speak to [[Guildmaster Apatura]] to finish the quest.

'''Congratulations, quest complete!'''
"""
