quest = "Fairytale II - Cure a Queen"
step_count = 8

[[steps]]
index = 0
name = "Master Gardener"
links = ["Martin the Master Gardener", "Draynor Market"]
text = """
[[File:Martin the Master Gardener chathead.png|left|103x103px]]
{{Map|name=Fairytale II - Cure a Queen|x:3078,y:3258|plane=0|mapID=0|mtype=square|r=4|height=250|width=250|align=right|caption=Martin's location}}
'''Note:''' Do not pickpocket [[Martin the Master Gardener|Martin]] before you start the quest, or you won't be able to continue for 10 consecutive minutes of in-game time.

To start, talk to [[Martin the Master Gardener]] in the [[Draynor Market]]. He will tell you to come back once his crops are grown, so wait until your quest menu says his crops have had plenty of time to grow; this takes approximately five and a half minutes of logged in time.

Talk to him again. He informs you rather crossly that there is still something wrong with the crops, not believing your story about fairies and accusing you of creating this problem. Agree to investigate for him.
"""

[[steps]]
index = 1
name = "Surprise!"
links = ["Dramen staff", "Lunar staff", "Zanaris", "Fairy Nuff", "Nuff's certificate", "Lunar alphabet", "Fairy chef", "Rune temple sign", "Cosmic Altar", "tanglefoot"]
text = """
[[File:Fairy Nuff's grotto ransacked.png|thumb|left|200px|Fairy Nuff's grotto, ransacked]]
{{Map|mapID=28|group=1|y:4472,x:2387|mtype=square|r=4|height=250|width=250|align=right|caption=Fairy Nuff's grotto location.}}
[[File:Nuff's certificate strange symbols.png|thumb|220px|Strange fairy symbols found on the back of Fairy Nuff's certificate.The certificate reads: "The Godfather attacked us. We have fled to safety. If you are loyal to her majesty, find us by using coordinates: air, dlr, djq, ajs."]]
{{Needed|[[Dramen staff]] or [[Lunar staff]]}}

Head south-east into the Lumbridge Swamp, towards the hut. Equip a Dramen or Lunar staff and go into [[Zanaris]], and head toward [[Fairy Nuff]]'s grotto, just north of the bank. Walk in, and you'll see a short cutscene. On the ground and next to one of the potion shelves is Fairy [[Nuff's certificate]]; pick it up. Right click and choose "Study". Studying the certificate reveals its back, which is covered with [[Lunar alphabet|strange fairy symbols]].
[[File:Cosmic Rune Altar Sign.png|thumb|220px|The sign reads: "Cosmic Rune Altar" and is on the south wall.]]
Talk to the [[Fairy chef]], south of the bank. She will tell you that she's seen similar inscriptions on a [[Rune temple sign|sign]] near the mysterious ruins — the [[Cosmic Altar]] ruins in southern Zanaris, next to the [[tanglefoot]] area.  Go South of the Altar and click on the wall that says " Read Rune Temple Sign".

'''You must look at the sign and study the certificate.'''

The symbols say "Cosmic Rune Altar." If you were to translate it, the back of the certificate reads:

{{cquote2|''The Godfather attacked us. We have fled to safety. If you are loyal to her majesty, find us by using the co-ordinates "AIR", "DLR", "DJQ", "AJS".''}}
"""

[[steps]]
index = 2
name = "Unlocking fairy rings"
links = ["Fairy Godfather", "Fairy Queen", "fairy rings", "Co-ordinator", "Fairy Fixit", "Dramen staff", "Lunar staff", "Lunar Diplomacy"]
text = """
[[File:Fairytale II - The Fairy Godfather.png|thumb|The Fairy Godfather]]
Talk to the [[Fairy Godfather]] in the [[Fairy Queen]]'s throne room located next to the Slayer master. Ask him what happened to the Queen, to which he visibly starts panicking and rushes to say that he will create a search party for her. Ask him both questions, and then agree to return to him once you've found the queen. The Godfather gives you permission to use the [[fairy rings]] to locate the queen. He asks you to speak to the [[Co-ordinator]] outside the room (North of the Godfather) to learn more about the rings.

After talking to the Co-ordinator and being informed of the vast history of the fairy rings and the queen, head West to the [[File:Water source icon.png]] fountains, then South to the fairy ring. Talk to [[Fairy Fixit]] near the fairy ring, south of the fountains. After that, use the fairy rings while wielding a [[Dramen staff]] (or a [[Lunar staff]] if you have partially or fully completed [[Lunar Diplomacy]]).
:'''''{{Colour|#C04040|You may now use the [[fairy rings]] throughout Gielinor without finishing the quest, if you'd prefer.}}'''''
:''See the '''[[fairy rings]]''' guide for all the possible combinations.''
"""

[[steps]]
index = 3
name = "Regrouping"
links = ["Nuff's certificate", "fairy ring", "Witchaven", "Poison Waste", "Isafdar", "Penguin", "Miscellania", "Fairy Queen", "Fairy Resistance Hideout", "Fairy Nuff", "Fairy Very Wise", "Godfather", "magic secateurs", "Fairy Godfather", "Thieving", "Salve graveyard teleport", "Canifis", "Queen's secateurs", "ork", "magic essence"]
text = """
With [[Nuff's certificate]] in your inventory, use the [[fairy ring]] four times in sequence. '''You will need to repeat this sequence each time you wish to visit the Fairy Queen's hideout.''' Once you have correctly done it once, the sequence of four appears as an option at the bottom of the teleports list. After the quest you will no longer need Nuff's certificate, but you will still need to do all four teleports. Nuff's certificate in your inventory '''must''' be obtained '''after''' you meet the required skill levels to complete the quest.
#{{fairycode|AIR}} (Islands: South of [[Witchaven]])
#{{fairycode|DLR}} (Islands: [[Poison Waste]] south of [[Isafdar]])
#{{fairycode|DJQ}} (un-attached code, will not teleport you anywhere)
#{{fairycode|AJS}} (Islands: [[Penguin]]s near [[Miscellania]], or [[Fairy Queen|Queen]]'s location)

'''If you end up in the same spot on any code other than DJQ''' with your character saying "''Wow, fairy magic sure is useful!''", it could be because the default click-action for the fairy ring is "Last destination (AIP)". Make sure to right-click and and choose "Configure".
'''If you end up on an island with some penguins''', you do not have Nuff's certificate in your inventory. You may also have skipped deciphering the certificate's message or simply missed one code in the sequence. (If you get the message "Maybe you need to investigate further first..", this indicates you correctly input the fairy ring sequence but may have skipped the sign at the Cosmic Altar.)

[[File:Fairytale II - The dying Fairy Queen.png|thumb|220px|The Fairy Queen, on her bed, dying.]]
You should be in the [[Fairy Queen]]'s [[Fairy Resistance Hideout|new location]]. Just go up the path, and head to the north-eastern room. Talk to [[Fairy Nuff]] and to [[Fairy Very Wise]], who will inform you that the queen is not well because the [[Godfather]] has hurt her by not returning her [[magic secateurs]]. As her essence is drained, she cannot retaliate without obtaining the secateurs, which you accept to bring back.

Head back to Zanaris, and pickpocket the [[Fairy Godfather]]. This requires level 40 [[Thieving]] to be completed successfully. If you fail, you will be teleported outside Zanaris. A quick way to get back to Zanaris is the [[Salve graveyard teleport]] which will place you a few strides away from the [[Canifis]] fairy ring.

Try pickpocketing from behind or the side, and make sure neither of his henchmen are looking directly at you. You should get a golden [[Queen's secateurs]]. Also, at this point, you will see [[ork]]s patrolling Zanaris.

Return to the Fairy Queen's Hideout by using the same four-ring sequence listed above.

:{{Colour|red|Warning:}} If you prepared the ingredients in advance, make sure you give the secateurs to Fairy Nuff before mixing the [[magic essence]]/crushing the gorak claw, or you'll have to get the ingredients all over again!
"""

[[steps]]
index = 4
name = "Magic essence"
links = ["Fairy Nuff", "Queen's secateurs", "magic essence", "Star flower", "gorak claw powder"]
text = """
Back at the fairy hideout, talk to [[Fairy Nuff]], and give her the [[Queen's secateurs|secateurs]]. She will use them to rejuvenate the queen, but they do not work completely. Nuff tells you that she needs a certain [[magic essence]] potion to replenish the queen's missing life energy. To make the potion, you need to collect some [[Star flower]]s and [[gorak claw powder]].
"""

[[steps]]
index = 5
name = "=Star flower="
links = ["Dramen staff", "Lunar staff", "fairy ring", "Cosmic entity's plane", "Star flower", "Cosmic Being", "Farming", "vial of water", "Herblore", "boost", "gorak claw powder"]
text = """
[[File:Starflowers growing.png|thumb|220px|Starflowers]]
{{Needed|[[Dramen staff]] or [[Lunar staff]]}}

Return to the [[fairy ring]] and use the code {{fairycode|CKP}}, which transports you to a [[Cosmic entity's plane|cosmic plane]]. Move around for about two minutes whilst the [[Star flower]]s grow. You can pass the time by talking to the [[Cosmic Being]] who lives there, contemplating the mysteries of the universe.

Pick a star flower when ready (49 [[Farming]] needed), and add your harvest to the [[vial of water]] (57 [[Herblore]] needed—however, if you are [[boost]]ing, wait until you have the [[gorak claw powder]] because you need 57 Herblore to finish the potion).
"""

[[steps]]
index = 6
name = "=Gorak claws="
links = ["Gorak", "Zanaris", "armour", "weapons", "food", "Armour/Melee armour", "multicombat area", "Protection prayers", "Piety", "fairy ring", "restore potion", "Gorak claws"]
text = """
{{Needed|Dramen or Lunar staff, Nuff's certificate|recommended=Armour, weapons, food and restore potions to kill [[Gorak]]s}}

Return to [[Zanaris]], and withdraw any [[armour]] and [[weapons]], along with around 10 pieces of good [[food]]. Goraks are '''very''' accurate, so take the best [[Armour/Melee armour|melee armour]] you have. They are aggressive, but luckily, they are not located in a [[multicombat area]], therefore you can only fight one at time. However, by remaining in the fairy ring, they will not be aggressive until they are attacked.
[[File:Gorak safespot (1).png|thumb|width=212x212|A player safespotting the goraks]]
'''Tips:'''
:* [[Gorak]]s use typeless melee attacks, meaning [[Protection prayers]] do not have any effect. However, you may use boosting prayers such as [[Piety]].
:* The accuracy of the goraks' attacks is calculated by your '''crush''' defence, so it is recommended to wear crush-resistant armour such as chainmail.
:* It is possible to safespot the goraks (see picture). However, their aggression and high max hit may render this difficult, so be extra careful if you are low levelled.

At the Zanaris [[fairy ring]], use the sequence {{fairycode|DIR}} to get to another plane full of goraks. They are level 145 or 149 and occasionally drain stat points. Kill them, eating food when necessary and drink [[restore potion]]s if needed until you get a [[Gorak claws|gorak claw]]. To leave, equip your staff of choice and teleport to Zanaris using the right-click option on the fairy ring.
"""

[[steps]]
index = 7
name = "The final scene"
links = ["pestle and mortar", "gorak claw powder", "star flower", "vial of water", "magic essence", "Herblore", "Fairy Resistance Hideout", "Fairy Queen", "Zanaris", "Fairy Very Wise", "Fairy Nuff", "Fairy Godfather", "ork"]
text = """
{{Needed|Dramen or Lunar staff, Nuff's certificate, star flower, gorak claw, pestle and mortar, vial of water}}

Note: Ensure you have retrieved the Queen's secateurs at this point, otherwise a dose of the magic essence potion will be lost and the queen will not regain consciousness.

Crush the claw with a [[pestle and mortar]] to get [[gorak claw powder]]. Mix the [[star flower]] and [[gorak claw powder]] into a [[vial of water]] to make a [[magic essence]] potion (57 [[Herblore]] needed). Return to the [[Fairy Resistance Hideout|Resistance Hideout]], use a dose of the magic essence potion on the [[Fairy Queen|queen]], who finally regains her senses.
[[File:Curing Fairy Queen.gif|frame|The player uses the magic essence on the Queen, saving her life!]]
As the queen angrily prepares to return to [[Zanaris]] and take back her throne, [[Fairy Very Wise]] and [[Fairy Nuff]] remind her that the [[Fairy Godfather]] has thugs and [[ork]]s at his disposal. His "army" has her easily outclassed, compared to her Majesty's small band of loyalists (many of whom are injured). The queen realises the flaw in the plan, and accepts the advice and allows the Fairy Godfather to remain Zanaris' ruler for the time being.

'''Congratulations, quest complete!'''
"""
