quest = "Cabin Fever"
step_count = 6

[[steps]]
index = 0
name = "War o' words"
links = ["Port Phasmatys", "ecto-token", "Ghostspeak amulet", "Ghosts Ahoy", "Charter ship", "coins", "Bill Teach", "The Green Ghost", "Mos Le'Harmless"]
text = """
[[File:Bill Teach chathead.png|left]]
Travel to [[Port Phasmatys]]. Bring [[ecto-token]]s and the [[Ghostspeak amulet]] (if you have not completed [[Ghosts Ahoy]] and are entering through the main gate), or you may also [[Charter ship|charter a ship]] for 1,000-3,500 [[coins]] (requiring no ecto-tokens) and speak to [[Bill Teach]] in [[The Green Ghost]] inn. Bill is the captain of ''The Adventurous'', a ship which he claims is the finest ever to sail the seas. He needs a pirate to help him leave the port, but none will sail with him, not even his crew.

Last night, he had a heated argument with the captain of another ship, wherein the captain threatened to sink ''The Adventurous'' and put his crew "to the sword". Scared, all his crewmembers have abandoned him and he has no choice but to sail back to his home land.

Seeing his dilemma and wanting to be a pirate, you offer to help him. Although he doubts your plundering abilities, Bill accepts your help and tells you to meet him on his ship. Go to the Port Phasmatys docks, and board the easternmost ship, ''The Adventurous''. Speak with Bill to set sail for [[Mos Le'Harmless]] and begin your journey as a pirate.
"""

[[steps]]
index = 1
name = "Under attack!"
links = ["cutscene", "Bill Teach", "Fuse (Cabin Fever)", "rope", "tinderbox", "pirate", "run energy"]
text = """
[[File:Cabin Fever - Enemy ship attacks.png|thumb|220px|''The Adventurous'' is attacked by an enemy ship.]]
As soon as you leave port, you see a [[cutscene]], where an enemy pirate ship starts firing on ''The Adventurous'', destroying the ship's hull and cannon. [[Bill Teach|Bill]] calms you down and tells you to first take care of the enemy's cannon.

[[File:Cabin Fever - gunpowder explosion.png|left|thumb|Detonating the gunpowder barrel.]]
He suggests you grab some [[Fuse (Cabin Fever)|fuse]] and [[rope]] from the ship's bottom deck. Climb down to the bottom deck and search the ''repair locker'', to take out '''four''' ropes (you will need to cross to the enemy ship a second time later, and each trip requires two ropes). Search the ''gun locker'' located near the repair locker, and pick up a fuse. In the southern corner, there is also a [[tinderbox]]; grab it.

[[File:Cabin Fever - On the enemy ship.png|thumb|220px|A player is attacked by a [[pirate]] on the enemy ship.]]
Climb up the ship's ladder to the main deck, and use the climbing net to climb up the main mast. Use your rope on the hoisted sail of ''The Adventurous'' (your own ship) to swing over to the enemy ship. If you fail the jump, your [[run energy]] will drop to 0.

The ship is populated by level 57 [[pirate]]s. If you need to escape from them for a moment, climb up the net on the main mast. For your job, find the powder barrel next to the cannon on the west side of the deck and use the fuse on the powder barrel. Light the fuse to blow up the barrel and the cannon. Climb back on the main mast using the net, and using a rope, swing back over to ''The Adventurous'' - '''if you forgot to bring a second rope, you can find one in the south-western corner of the main deck of the enemy pirate's ship.'''
"""

[[steps]]
index = 2
name = "=Repairing the Damage="
links = ["Bill Teach", "Repair plank", "Tacks", "Swamp paste", "hammer"]
text = """
[[File:Cabin Fever - Repairing hull.png|thumb|220px|Repairing the ship's hull.]]
Now that you've controlled the offence, you need to build your defence. Talk to [[Bill Teach|Bill]], and he'll want you to repair the damaged hull. Climb down the ship's ladder and search the repair locker for:
*6 [[Repair plank]]s
*30 [[Tacks]]
*3 [[Swamp paste]]
*A [[hammer]]
Each of the three holes takes two planks, ten tacks and one swamp paste to fix. When you have enough resources, a message in the chat interface will say so, if you try to get more than is needed.

For each hole, use a repair plank and then a swamp paste on the ship hull to patch it up.

Then, go talk to Bill again.
"""

[[steps]]
index = 3
name = "=Retaliation!="
links = ["pirate", "Bill Teach", "rope", "plunder", "inventory"]
text = """
For attacking your ship, the enemy [[pirate]]s need to be taught a lesson. [[Bill Teach|Bill]] asks you to pillage the enemy ship and bring back their booty. Return to the main deck, climb the net again, use a [[rope]] on the hoisted sail, and swing back over to the enemy ship.

Climb down the ship's ladder. Steal from the chest, loot the crate and ransack the barrel for enemy [[plunder]]; you will need to wait for it to respawn. You need 10 plunder, but looting all three once only provides you with 6 plunder, 3 being from the chest, 2 from the crate and 1 from the barrel. It can take anywhere up to 5 minutes for the plunder to respawn; however, you can simply log out and log back in (or switch worlds) for the plunder to respawn. The barrel will respawn fastest, then the crates and finally, the chest.

After you have ten plunder in your [[inventory]], return to the main deck, and return to ''The Adventurous''.

Climb down the ship's ladder, and use your plunder on the plunder storage at the back. If you leave the ship, you will lose the plunder and have to steal it back over again. Also, you can only store ten plunder; Bill will confiscate any surplus in your inventory when you talk to him.
"""

[[steps]]
index = 4
name = "=Into Davy Jones' Locker="
links = ["Bill Teach", "pirate", "Cannon (Cabin Fever)", "cannon barrel (Cabin Fever)", "ramrod", "Fuse (Cabin Fever)", "canister", "Gunpowder", "cannon ball (Cabin Fever)"]
text = """
[[File:Cabin Fever - Using ship cannon.png|thumb|220px|Using the ship's cannon to retaliate.]]
Finally, [[Bill Teach|Bill]] wants you to prepare a send-off for the enemy. He wants to give the enemy [[pirate]]s a blast, from the [[Cannon (Cabin Fever)|cannon]]. The aim here is to prepare the cannon (follow steps below) and to fire the cannon when the pirates are in front of the cannon on the pirate ship, so that you will hit them. Follow these steps to repair and fire the cannon:

Climb down the ship's ladder, search the gun locker, and take a [[cannon barrel (Cabin Fever)|cannon barrel]]. Trying to take anything else at this point will result in the message "You do not need a [item name] right now." Climb back up and left-click the [[Cannon (Cabin Fever)#Exploded|broken cannon]] to fix it (The cannon will have the option "Repair broken cannon").

Talk to Bill again, then go below and search the gun locker for a [[ramrod]], a few [[Fuse (Cabin Fever)|fuse]]s (at least 4 is recommended here), and a [[canister|cannon canister]]. Return to the main deck, and choose the take-powder option from the powder barrel next to the cannon.

[[Gunpowder]] can be obtained from the powder barrel located right next to the cannon, just left click the 'take powder' option.
#Use gunpowder on the cannon.
#Use the ramrod on the cannon.
#Use a canister on the cannon.
#Use a fuse on the cannon.
#Fire the cannon!
#Use the ramrod on the cannon again to clean it out.

If you miss, use the ramrod on the cannon to clean it out and then repeat the steps, until you score a hit. If you don't clean the cannon, it will explode from the previous unused gunpowder. If this happens, replace the broken barrel with a new one from the gun locker. Try not to fire the cannon immediately after attaching the fuse. This can cause multiple misses. Count to 3 before firing.

When you hit the pirates with the canisters, talk to Bill. He tells you to sink the enemy pirate ship by blasting holes in its hull; three would be enough. Go down below, and search the gun locker to take three [[cannon ball (Cabin Fever)|cannon ball]]s (best to take extra cannon balls and fuses because you can miss).

Up on the main deck, complete the following:

#Clean the cannon out with a ramrod.
#Use gunpowder on the cannon.
#Use the ramrod on the cannon to compact the gunpowder.
#This time, use a CANNONBALL (INSTEAD of a canister) on the cannon.
#Use a fuse on the cannon.
#Fire the cannon!



'''Note:'''

Clean the cannon immediately after firing every time. '''Selecting "Empty-Out Cannon" does not clean the cannon''' in spite of the chat message that reads, "You clean out the cannon," upon doing so. You will take some damage (around 6) and destroy the cannon (having to repair it again) each time you fail to complete:

• Step 1: cleaning the cannon after firing and before loading gunpowder, OR

• Step 3: using the ramrod after loading with gunpowder and before loading a canister OR cannonball. ***



Upon hitting the enemy ship THREE (3) times, a short cutscene will follow.
"""

[[steps]]
index = 5
name = "Mos Le'Harmless"
links = ["Mama", "Bill Teach", "cutscene", "The Other Inn", "Book o' piracy"]
text = """
[[File:Cabin Fever - Le'Fiette & Teach.png|thumb|220px|[[Mama]] and [[Bill Teach|Bill]] chat.]]
Following your third hit of the enemy pirate ship, you see a [[cutscene]] with [[Bill Teach]] talking with [[Mama|Mama Le'Fiette]] in [[The Other Inn]]. Bill then thanks you and gives you a [[Book o' piracy]], to add "pirate" to your vocabulary as your ineptitude at speaking "pirate" annoyed him to no end in the voyage.

'''Congratulations, quest complete!'''

{{Clear}}
"""
