quest = "Tower of Life"
step_count = 6

[[steps]]
index = 0
name = "Obtaining the builder's costume"
links = ["Tower of Life (building)", "East Ardougne", "Necromancer Tower", "fairy ring", "Ardougne cloak", "Ardougne Monastery", "Effigy", "Bonafido", "'Black-eye'", "hard hat", "Builder's trousers", "'Gummy'", "plant (Tower of Life)", "'The Guns'", "beer", "coins", "Flying Horse Inn", "Fight Arena (location)", "Yanille", "Builder's shirt", "'No fingers'", "Thieving", "Builder's boots"]
text = """
Begin the quest by heading to the [[Tower of Life (building)|Tower of Life]] south of [[East Ardougne]], just south-west of the [[Necromancer Tower]] (south-west of [[fairy ring]] {{Fairycode|DJP}}, or [[Ardougne cloak]] teleport to the [[Ardougne Monastery|monastery]] and go east).

*Talk to [[Effigy]]. He will tell you speak to [[Bonafido]] if you want to help.

*Talk to Bonafido. He can be found lying around the boxes just north of the entrance to the Tower of Life - if you can convince him you're a builder by getting the outfit, he will let you into the tower. You need a hard hat, some scruffy trousers, a good top, and some hard boots. Talk to the other builders to get them.
*Talk to [['Black-eye']] to get a [[hard hat]], and answer his three questions. Here are the questions and answers:

:#''How many nails does it take to make a rocking chair?'' - '''Three.'''
:#''What takes 3 planks, 3 cloths and 3 nails to make, and helps remove light from a room?'' - '''Torn curtains.'''
:#''I like fish and I want to put some in my garden, but I need a special water feature. What materials would I require?'' - '''10 clay pieces.'''

{{Map|2656,3212|mtype=pin|align=right|caption=Location of [[Builder's trousers|Trousers]].}}

*Talk to [['Gummy']] and ask for trousers. He says he lost a pair around the tower - just search the [[plant (Tower of Life)|plants]] south-east of the tower to find the [[Builder's trousers]].
*Talk to [['The Guns']], who wants a [[beer]]. Go and buy a beer for 2 [[coins]] at [[Flying Horse Inn|The Flying Horse]] pub in north-west East Ardougne or the pub at the [[Fight Arena (location)|Fight Arena]] or [[Yanille]] and return, give him the beer, and he will give you his [[Builder's shirt|shirt]].
*Finally, talk to [['No fingers']] and [[Thieving#Pickpocketing|pickpocket]] him when he refuses to give you the [[Builder's boots|boots]].
*Once you've acquired all the items, you must answer some questions from Bonafido for him to grant you entry to the tower. The answers are:

:#''You've plenty of work to do, but you need a drink fast - what do you go for?'' - '''Tea.'''
:#''Now, let's hear you whistle!'' - '''Whistle for attention.'''
:#''What's a good sign that you need to replace your trousers?'' - '''Your legs are getting a bit cold.'''
:#''What do you do if you cut your finger?'' - '''Carry on, it'll fix itself.'''

After answering these questions, you are allowed to enter the tower. Please note that you need to wear the outfit if you want to enter the tower at any time during the quest, although it is not needed after.
"""

[[steps]]
index = 1
name = "Fixing up the tower"
links = ["hammer", "saw", "crystal saw"]
text = """
[[File:Tower of Life Repair Supplies Location.png|right|thumb|400px|Repair Supplies Location]]
*All the required items are on the {{FloorNumber|uk=0}} in crates. Search these as required. Each crate gives the same item; search again to get more or if you get nothing the first time.
*A pressure machine, a pipe system, and a strange cage at the top need to be finished. A [[hammer]] and a [[saw]] (or [[crystal saw]]) are needed to fix these machines.
{| class="wikitable"
! colspan="2" | Item
! Machine
! Amount
|-
| {{plinkt|Valve wheel}}
|  Pressure
| 4
|-
| {{plinkt|Metal sheet}}
| Pressure
| 3
|-
| {{plinkt|Coloured ball}}
| Pressure
| 4
|-
| {{plinkt|Pipe (Tower of Life)|txt=Pipe}}
| Pipe
| 4
|-
| {{plinkt|Pipe ring}}
| Pipe
| 5
|-
| {{plinkt|Rivets}}
| Pipe
| 6
|-
| {{plinkt|Metal bar}}
| Cage
| 5
|-
| {{plinkt|Binding fluid}}
| Cage
| 4
|}
"""

[[steps]]
index = 2
name = "=Pressure machine="
links = ["Coloured ball", "Metal sheet", "Valve wheel"]
text = """
'''Items needed:'''
*4 [[Coloured ball]]s
*3 [[Metal sheet]]s
*4 [[Valve wheel]]s

[[File:Tower of Life - fixing pressure machine.png|right|thumb|400px|The pressure machine fixed.]]
On the {{FloorNumber|uk=1}}, once the pressure machine is built, follow these instructions to fix the pressure machine:

''Wheels labelled from the leftmost (1) to the rightmost (4)''

#Turn '''wheel 1''' to the '''left''' until the ball plugs the hole.
#Turn '''wheel 1''' to the '''right''' until the pipe fills.
#Pull the '''left lever'''.
#Turn '''wheel 2''' to the '''left''' until the ball plugs the hole.
#Turn '''wheel 2''' to the '''right''' until the pipe fills.
#Turn '''wheel 3''' to the '''right''' until the water starts dripping.
#Turn '''wheel 3''' left '''once''' to plug the hole.
#Turn '''wheel 3''' to the '''right''' until the pipe fills.
#Pull the '''right lever'''.
#Turn '''wheel 4''' to the '''right''' until the water starts dripping.
#Turn '''wheel 4''' left '''once''' to plug the hole.
#Turn '''wheel 4''' to the '''right''' until the pipe fills.

You will receive a message saying the machine is working.
"""

[[steps]]
index = 3
name = "=Pipe machine="
links = ["Pipe (Tower of Life)", "Pipe ring", "Rivets"]
text = """
[[File:Tower of Life Pipe Puzzle.png|220px|thumb|right|The completed puzzle]]
'''Items needed:'''

*4 [[Pipe (Tower of Life)|Pipe]]s
*5 [[Pipe ring]]s
*6 [[Rivets]] (These stack)

On the {{FloorNumber|uk=2}}, you will need to solve a rather simple puzzle similar to a jigsaw (solution on the right). As soon as you put a pipe in the correct location, it will lock in place. You only have to rotate the largest piece; the rest are the correct orientation when you start. Select a piece and use the arrow and rotation controls at the bottom to move it to the correct location.
"""

[[steps]]
index = 4
name = "=Caged area (Top floor)="
links = ["Metal bar", "binding fluid"]
text = """
[[File:Tower of Life broken cage.png|220px|thumb|right|The broken Cage]]
'''Items needed:'''

*5 [[Metal bar]]s
*4 Bottles of [[binding fluid]]

Clicking the horizontal or vertical button will make a bar appear. It can increase in size by using the + sign. The bars start off at size one once selected. Click "place bar" and it will go in. If it disappears, redo the steps with the next size up.

It is helpful to remember each "square" of the cage is composed of 2-length pipes. So a missing pipe spanning 1½ squares would need a pipe of length 3.

'''Quick guide:'''
[[File:Tower of Life repairing the cage.png|400px|thumb|right|Repairing The Cage]]''When each side is finished, turn the cage with the right arrow.''

'''Side One'''
#'''Horizontal:''' Size 2
#'''Horizontal:''' Size 3
#'''Vertical:''' Size 2

''This side of the cage is now complete''

'''Side Two'''
#'''Horizontal:''' Size 2
#'''Vertical:''' Size 4
#'''Vertical:''' Size 2

''This side of the cage is now complete''

'''Side Three'''
#'''Horizontal:''' Size 4
#'''Vertical:''' Size 2
#'''Vertical:''' Size 3

''This side of the cage is now complete.''

'''Side Four'''
#'''Horizontal:''' Size 2
#'''Horizontal:''' Size 2
#'''Vertical:''' Size 2

''The cage should now be complete!''
"""

[[steps]]
index = 5
name = "The Alchemists' Secret"
links = ["Effigy", "cutscene", "Homunculus", "Creature Creation"]
text = """
*Once all three machines are properly fixed, go outside and talk to [[Effigy]]. He will be delighted that you've finished and asks you to join him at the top of the tower with the other alchemists.

[[File:Tower of Life - creating Homunculus.png|thumb|250px|The alchemists begin to create a homunculus.]]

*Go back up to the top of the tower to start a long [[cutscene]] where the [[Homunculus]] is brought to life.
*Go back to the base of the tower and talk to Effigy - then, return back to the top of the tower to confront the Homunculus.

You now need to push the Homunculus's mind towards magic or logic. All multiple-choice answers are either magical, logical, or neither. You need to push the bar at the top of the screen either to fully magical or fully logical; once done, the Homunculus will be okay. It does not matter if you push the Homunculus's mind towards magic or logic - the outcome will be the same.

There are 14 questions. Choosing a magical answer moves the arrow to the left, a logical answer moves the arrow to the right, and a neither answer does not move the arrow. If you don't move the arrow all the way to one end, then the questions repeat. Likewise, you could finish before all the questions are asked.
[[File:Homunculus Magic or Logic.png|thumb|220px|Helping Homunculus with magic or logic]]

*''How can I make fire appear at my fingertips?''
**'''Logic''' - Get some logs and a tinderbox.
**'''Magic''' - With the aid of 5 fire runes.
**'''Neither''' - That's impossible! No one can do that!
*''How do dragons breathe fire?''
**'''Neither''' - Not too sure, I've never seen it happen.
**'''Magic''' - With the help of the magical dragonstones!
**'''Logic''' - By ignition of gas in their belly as they exhale.
*''What do people do, day-in, day-out?''
**'''Magic''' - Runecraft, enchant jewellery, perform alchemy.
**'''Neither''' - Eat, sleep, nothing that exciting.
**'''Logic''' - Fletching, Crafting, Smithing.
*''What could I do with unwanted bones?''
**'''Logic''' - Bury them.
**'''Neither''' - I'd like to think you wouldn't be carrying bones around.
**'''Magic''' - Turn them into bananas or peaches!
*''What's the best way to travel?''
**'''Neither''' - I'm not really much of a traveller, sorry.
**'''Logic''' - Run, run as fast as you can.
**'''Magic''' - Depends where you are headed, but teleport spells are a safe bet.
*''I hear people whisper of potions...''
**'''Magic''' - Yes, you can make magic potions to boost your skills.
**'''Logic''' - People mix together ingredients in vials. The nutrients will help you.
**'''Neither''' - Yes, liquid-filled vials. Big deal.
*''How are runes created?''
**'''Magic''' - By harnessing the power of the gods!
**'''Neither''' - Never seen one personally.
**'''Logic''' - Take some essence to an altar and use a talisman.
*''Can people move things with the power of the mind?''
**'''Neither''' - Perhaps. I've never seen it myself, though.
**'''Magic''' - Yep, you can use the Telekinetic Grab spell.
**'''Logic''' - Sure. Use your brain to tell someone to move it!
*''How can I possibly exist?''
**'''Magic''' - Through the power of alchemy.
**'''Neither''' - It's beyond me!
**'''Logic''' - It's a simple case of combining materials.
*''Explain those flashing sparks that scared the alchemists.''
**'''Magic''' - You have special powers - no surprise seeing how you were created.
**'''Logic''' - Coincidence - there is a lot of loose metal around.
**'''Neither''' - Yeah, they were cool! Nice one.
*''I want to learn more - what should I study?''
**'''Logic''' - Try some Mining followed by Smithing.
**'''Magic''' - How about Magic and Runecrafting?
**'''Neither''' - That's up to you; depends on what you find interesting.
*''If I reach out far enough I can grab the sun.''
**'''Neither''' - Don't be silly! You'd get burnt!
**'''Magic''' - Can't see why not, anything is possible.
**'''Logic''' - Well the sun is not actually there, it's where it used to be!
*''Am I a creature of magic or a creature of logic?''
**'''Logic''' - Everything has a reason, even if you don't know what it is.
**'''Neither''' - Probably a bit of both.
**'''Magic''' - Your very existence speaks of mystical forces.
*''Which do you believe in?''
**'''Magic''' - Magic.
**'''Neither''' - I'm too laid back to really care, mate.
**'''Logic''' - Logic.

[[File:Tower of Life alchemists.png|thumb|220px|The Homunculus scares off the alchemists]]Once more, return to the {{FloorNumber|uk=0}}, talk to Effigy and the Homunculus will appear and scare off the alchemists. The Homunculus will speak with you again and tell you to meet him in the basement of the tower.
You will be granted access to the [[Creature Creation|dungeon]]. Go into the dungeon and talk to the Homunculus north of where you enter the dungeon once more to complete the quest.

'''Congratulations, quest complete!'''
{{Clear}}
"""
