quest = "Nature Spirit"
step_count = 4

[[steps]]
index = 0
name = "Starting out"
links = ["Drezel", "Paterdomus Temple", "Priest in Peril", "meat pie", "apple pie", "Filliman Tarlock", "Holy Barrier", "Mort Myre Swamp"]
text = """
[[File:Drezel chathead.png|left]]
Talk to [[Drezel]] in the basement of the [[Paterdomus Temple]] where you left him at the end of [[Priest in Peril]]. Drezel will give you three [[meat pie]]s and three [[apple pie]]s to take to [[Filliman Tarlock]].

Pass through the [[Holy Barrier]] by Drezel, then cross the nearby bridge. Travel south to the gate permitting access to the [[Mort Myre Swamp]].
"""

[[steps]]
index = 1
name = "Traversing the swamp"
links = ["swamp decay", "ghasts", "typeless", "druid pouch", "Canifis", "Mort Myre Swamp", "Bridge (Nature Grotto)", "Filliman Tarlock", "amulet of ghostspeak", "washing bowl", "mirror", "Journal (Filliman Tarlock)", "Grotto tree", "Druidic spell"]
text = """
{{Needed|Ghostspeak amulet|recommended=Additional food for low levels (some may be rotted, see below)}}
{{Map|3441,3337|r=8|mtype=square|align=right|caption=Location of the Grotto Tree.}}
[[File:Nature Spirit - Nature Grotto.png|thumb|220px|The Grotto Tree.]]
While in the swamp the player will lose 3 health every 2 minutes to [[swamp decay]]. Additionally [[ghasts]] will attempt to rot your food, though they may often miss. Without any food in your inventory they will instead deal up to 3 [[typeless]] damage per attack. The [[druid pouch]] obtained later during the quest will protect you from ghasts by consuming charges per attack. Do not worry about the food given by Drezel being rotted as you won't actually end up giving Filliman the food. You may considering banking this food in [[Canifis]] before entering the swamp to avoid it rotting if you have more inexpensive food to use.

You must enter the [[Mort Myre Swamp]] through the gate, or Filliman will not appear. Head south along the west river until you see the grotto tree. Jump across the [[Bridge (Nature Grotto)|broken bridge]] to the grotto. There is a chance to fail, with the player taking upwards of 7 damage.

Once on the island, the player will be safe from both swamp decay and ghasts. Attempt to enter the grotto via the small black hole with an "Enter" option, and the ghost of [[Filliman Tarlock]] will appear.

Equip your [[amulet of ghostspeak]] to speak to him. He won't believe that he's dead, so take the [[washing bowl]] off the nearby table to find a [[mirror]] underneath. Use the mirror on Filliman to convince him. After this, he will tell you to find his [[Journal (Filliman Tarlock)|journal]]. Search the [[Grotto tree]] to get it and give it to him.

Ask him how you can help, and Filliman will mention that the journal details the requirements for him to complete his transformation into a Nature Spirit. He will give you a [[Druidic spell|spell scroll]].
"""

[[steps]]
index = 2
name = "Blessings"
links = ["Silver sickle", "Drezel", "Prayer", "altar", "Paterdomus Temple", "rotting log", "druidic spell", "a used spell", "Filliman", "Bloom", "drop trick", "stone (Nature Spirit)", "Nature Grotto", "Silver sickle (b)", "Druid pouch", "ghast"]
text = """
{{Needed|Druidic spell (given to you by Filliman), a [[Silver sickle]], and your ghost speak amulet|recommended=Additional food to prevent the mushroom from being rotted in this section}}
[[File:Nature Spirit - Drezel's blessing.gif|thumb|170px|[[Drezel]] blesses the player.]]

Return to [[Drezel]] and ask him to bless you. For the next step you will need to use [[Prayer]] points. If you need to recharge them, there is an [[altar]] on the [[Paterdomus Temple]]'s main floor.

Once blessed by Drezel, return to the swamp and look for any [[rotting log]]. Cast the [[druidic spell]] next to it to make a mushroom grow. The [[druidic spell]] will transform into [[a used spell]]; '''do not''' drop it as you will need it later. Pick up the mushroom and show it to [[Filliman]]. If a Ghast turns your mushroom rotten, go back to the grotto to ask for another [[Bloom]] scroll.

:'''Note:''' Multiple spells cards may be obtained from Filliman utilising the [[drop trick]]. This can be used to avoid the need to use prayer in the next section.

[[File:Nature Spirit - Performing the nature spirit ritual.gif|thumb|220px|[[Filliman]] performs the transformation ritual.]]

At Filliman's grotto, '''use''' (don't drop) the mushroom on the [[stone (Nature Spirit)#Brown|light-brown (western) stone]], and the used spell card on the [[stone (Nature Spirit)#Grey|grey stone]]. Summon Filliman again if needed by trying to enter his grotto, '''then, while standing on the [[stone (Nature Spirit)#Orange|orange stone]]''', tell Filliman you think that you have solved the puzzle. Filliman will complete half of his transformation and ask you to come inside the [[Nature Grotto|grotto]].

[[File:Nature spirit - Blessing sickle.gif|thumb|170px|[[Filliman]] blesses the player's silver sickle.]]

Go inside, and search the grotto in the middle of the cave. Filliman will turn into a Nature Spirit, then ask you to get a [[Silver sickle]]. Talk to him again and Filliman will bless the sickle, turning it into a [[Silver sickle (b)]]. After giving you a [[Druid pouch]], he will then ask you to kill three [[ghast]]s.
"""

[[steps]]
index = 3
name = "Killing the ghasts"
links = ["weapon", "Ghostspeak amulet", "druid pouch", "prayer potions", "Prayer", "ghast", "Bloom", "Prayer points", "Mort myre pear", "Mort myre fungi", "Mort myre stem", "Altar of nature", "Morytania Diary"]
text = """
{{Needed|A [[weapon]], [[Ghostspeak amulet]], [[druid pouch]], and [[prayer potions]] for players with low [[Prayer]]}}
[[File:Ghast dying.gif|thumb|120px|The [[ghast]] is freed after it is killed.]]

Go into the swamp with the blessed silver sickle, and operate it to cast [[Bloom]] while standing next to logs, bushes, and twigs. Each cast costs 1-6 [[Prayer points]] and allows you to harvest nearby [[Mort myre pear|pears]], [[Mort myre fungi|fungi]], and [[Mort myre stem|stems]].

Add at least three pears, fungi, or stems to your druid pouch by clicking "Fill" while three of them are in your inventory.

When you use the druid pouch on the level 30 ghasts, they'll become visible, and one charge will be deducted from your druid pouch. Kill three of them (you may use any weapon).

:'''Note:''' If you get a message when using the druid pouch saying "You've not been told how to use this item yet", ensure you've finished the dialogue with Filliman explaining how to use it.

Enter the grotto tree, then search the grotto and speak with the Nature Spirit to complete the quest.

:{{Color|red|Warning:}} Any items dropped before speaking with the Nature Spirit will be lost in the "old" grotto upon completion of the quest.

'''Congratulations, quest complete!'''

:'''Tip:''' Before leaving, pray at the [[Altar of nature]] within the Grotto to complete an easy task for the [[Morytania Diary]].
"""
