quest = "Recipe for Disaster/Freeing King Awowogei"
step_count = 7

[[steps]]
index = 0
name = "=Greegrees="
links = ["Monkey Madness I", "coins", "monkey talisman", "ninja monkey", "zombie monkey", "monkey guard", "Zooknock", "Ape Atoll Dungeon", "Tutab", "Monkey Child", "Karamjan monkey greegree", "Monkey Guard", "safespot", "Monkey Archer", "Zombie monkey", "antipoison potion", "food"]
text = """
'''Note: if you already obtained the ninja, zombie and gorilla greegrees during [[Monkey Madness I]], you can skip this section.'''
{{Needed|3,000 [[coins]] or 3 [[monkey talisman]]s|recommended=Combat equipment to kill a [[ninja monkey]] and a [[zombie monkey]], Ranged or Magic equipment to kill a [[monkey guard]], Prayer potions, stamina potions and food for combat and running through Ape Atoll dungeon}}

In order to make the three required greegrees, you must bring a [[monkey talisman]] and the respective bones to [[Zooknock]] (located at the end of the [[Ape Atoll Dungeon]]). Monkey talismans can be purchased from the rune salesman [[Tutab]] on Ape Atoll for 1,000 coins each, or obtained for free from the [[Monkey Child]].

Once you land on Ape Atoll, head north with a greegree equipped (use the [[Karamjan monkey greegree|karamjan greegree]] if you do not have the others) and pass through the gate. Purchase three monkey talismans from the rune salesman. Next, kill a [[Monkey Guard]] and take its bones. Monkey Guards are located near the prayer altar on Ape Atoll. Make sure to use Ranged or Magic and [[safespot]] them,  Melee can be used but Monkey Guards will heal themselves when they reach low health so high damage is needed to combat this. A safespot location is in the north-east corner of the building behind the fire, or to the south behind the ladder.

Next you will need to kill a [[Monkey Archer]]. North of the bank icon on the mini-map are two ninja monkeys (monkey archers); either protect from range or safespot (by standing in the tall grass) to kill one. Make sure to grab the bones.

[[Zombie monkey]]s can be found in the Ape Atoll dungeon (entrance located on the south side of the island). This is the same cave that [[Zooknock]] can be found in. Be wary of traps and poisonous spiders.

Equip any greegree you have already so that the monsters in the dungeon to [[Zooknock]] do not attack you, negating the need for prayer potions.

Rubble will constantly fall on you throughout the cave dealing small amounts of damage. This damage is negated if standing under the stone outcroppings when the screen rumble occurs. It is a good idea to bring [[antipoison potion]]s and [[food]]. Kill a zombie monkey in the cave and collect its bones.

Speak with Zooknock at the end of the cave with all three bones and talismans. Confirm that you want to make another (he calls it a talisman) greegree and then '''use''' the bones and talisman on Zooknock (he will pause after the conversation before giving you the greegree). Repeat this three times with the different bones to get all three greegrees.
"""

[[steps]]
index = 1
name = "=Awowogei's Palace="
links = ["greegree", "M'speak amulet", "Monkey nuts", "Banana", "monkey nuts", "banana", "m'speak amulet", "Awowogei", "Ape Atoll", "Elder Guard", "three wise monkeys", "snake corpse", "big snake", "Sliced banana", "red banana", "tchiki monkey nuts", "stuffed snake"]
text = """
{{Needed|Any [[greegree]], [[M'speak amulet]], [[Monkey nuts]], [[Banana]]}}
Buy [[monkey nuts]] and grab a normal [[banana]] if you haven't already. Make sure you've equipped one of your [[greegree]]s and your [[m'speak amulet]]. Go to [[Awowogei]]'s palace on [[Ape Atoll]] by talking to the [[Elder Guard]] to let you in.

'''Note: You must have started the quest by inspecting [[Awowogei]] at the table before the Elder Guard will let you through.'''

Talk to Awowogei about his favourite food; he will refuse to divulge it, but will mention [[three wise monkeys|three monkeys]] in the temple. The three monkeys are located in the temple north of Awowogei, in the north-west corner of the ground floor. Tell them that you're planning a surprise party for the king. They will tell you to stuff the [[snake corpse|corpse]] of a [[big snake]] with [[Sliced banana|banana slices]] and monkey nut paste. If you have a banana and the monkey nuts with you, speak to them again, twice, one for banana and one for monkey nuts. They will tell you that these are not good enough for the king's sophisticated palate, and that you will need to replace the ingredients with the sacred [[red banana]] and the [[tchiki monkey nuts]]. The normal [[banana]] and [[monkey nuts]] are no longer needed after this point. Be sure to '''<u>speak with all 3 monkeys</u>''' or the red banana tree will not spawn.

'''Note:''' If you speak with the three monkeys with a red banana in your inventory, they will eat it and you will need to get another.

'''Note:''' If your cooking level is at or just above the requirement (or you are boosting) the failure rate for cooking the [[stuffed snake]] is quite high. It is useful to obtain multiple [[tchiki monkey nuts]], [[red banana]]s and [[snake corpse]]s to avoid having to re-gather the ingredients. This can only be achieved by drop picking (dropping an item, retrieving it from its original source and picking up the original), otherwise the player will receive a message deterring it.
"""

[[steps]]
index = 2
name = "=Snake="
links = ["Big Snake", "Antipoison", "Crash Island", "snake corpse", "Ape Atoll", "pit (Crash Island)", "Crash Island Dungeon", "poisonous", "Protect from Melee"]
text = """
{{Needed|Combat equipment to kill a level 84 [[Big Snake]]|recommended=[[Antipoison]]}}
{{Instance}}
[[File:Killing big snakes.png|thumb|220px|Killing the big snakes in the pit on [[Crash Island]].]]
'''Note''': You cannot get the [[snake corpse]] beforehand. If you kill a snake before talking to Awowogei and then the three monkeys, you will get only bones.

Leave [[Ape Atoll]] and return to [[Crash Island]]. Go east until you find a [[pit (Crash Island)|large hole]] in the ground, and enter the [[Crash Island Dungeon|cave]] below.

You will find five level 84 [[Big Snake]]s. Since they hit hard and are [[poisonous]], [[Protect from Melee]] is advised. Turn it on before entering the cave. Kill one and take the [[snake corpse]]. You might want to grab multiple corpses since you might accidentally burn the snake. Try to stay away from the walls as more snakes (which are scenery) will appear and attack you.
"""

[[steps]]
index = 3
name = "=Red banana="
links = ["Rope", "gorilla greegree", "Ape Atoll", "red banana", "gnome glider", "rope", "Ifaba", "Red banana", "sliced red banana"]
text = """
'''Items needed:'''  [[Rope]], [[gorilla greegree]], knife, pestle and mortar[[File:Getting red banana.png|thumb|220px|Getting the banana.]]
Return to [[Ape Atoll]] and enter the city.

The [[red banana]] tree is located on the north-west coast of the island, just south-west of the [[gnome glider]] icon. To get the [[red banana]], wield your [[gorilla greegree]], as you'll need lots of strength. Then, go to the west coast and find the tree. Use your [[rope]] on it to get the banana. Do this at least twice, since the three monkeys will eat one of the sliced bananas that you bring back to them. If you forgot rope, [[Ifaba]] at the general store sells some. Slice the [[Red banana|banana]] to get [[sliced red banana]]. You might want to get more sliced red bananas, since you might accidentally burn the snake.

If no bananas are on the tree, go to the three wise monkeys again with a normal banana and go through the dialogue regarding it until it is finished.
"""

[[steps]]
index = 4
name = "=Tchiki monkey nuts="
links = ["fairy rings", "ninja greegree", "Ape Atoll Agility Course", "Agility", "tchiki monkey nuts", "Bush (Tchiki monkey nuts)", "tchiki nut", "tchiki nut paste", "Western Provinces Diary"]
text = """
[[File:Picking tchiki bush.png|thumb|220px|Picking the tchiki nuts from the bush.]]

Players with access to [[fairy rings]] may use the code {{Fairycode|CLR}} to skip part of the Agility course.

Wield your [[ninja greegree]], then go to the south part of town. The [[Ape Atoll Agility Course|Agility course]] start-point is on the other side of a small river. You will need 48 [[Agility]] to access the course. Boosts will '''not''' work for this. Once over the bridge, head south-west near the cliff to enter the agility course. Continue on the course until right after the rope swing to reach the broken hut around a hole in the ground. Go down and pick some [[tchiki monkey nuts]] from the [[Bush (Tchiki monkey nuts)|bush]]. Grind the [[tchiki nut]] into [[tchiki nut paste]]. You might want to create more [[tchiki nut paste]], since you might accidentally burn the snake.

If there are no nuts on the bush, return to the three monkeys and use the standard monkey nuts on one of them and go through the dialogue regarding it until it is finished.

Pets cannot be brought onto the Agility course. If you have a pet following you, pick it up to use the course.

Note: Completing a lap of the course is a hard task in the [[Western Provinces Diary|Western Provinces]] achievement diary.
"""

[[steps]]
index = 5
name = "=Cooking the snake="
links = ["Red banana", "Tchiki monkey nuts", "Snake corpse", "raw stuffed snake", "Ape Atoll", "greegree", "Zombie greegree", "Monkey Guard", "Cooking", "Snake over-cooked", "stuffed snake", "Lumbridge Castle", "m'speak amulet", "Awowogei"]
text = """
[[File:Cooking stuffed snake.png|thumb|220px|Cooking the snake.]]
After you have everything, slice the [[Red banana|banana]] and grind the [[Tchiki monkey nuts|nuts]], then stuff your [[Snake corpse|snake]] with them to create a [[raw stuffed snake]]. Be careful not to eat them yourself.

Go back to [[Ape Atoll]], equip a [[greegree]] (you will need your [[Zombie greegree]] soon, but cannot run with it equipped), and then go back to the temple. Go down the trapdoor protected by [[Monkey Guard|gorillas]], then down one of the ramps. There is a crack in the wall between the two bamboo ramps. Go through it, and you will see a patch of hot coals. This is where you need to equip your zombie greegree, as the hot coals will prevent you from going to the other side. Go to the long rock on the floor, boost your [[Cooking]] level if needed, and then, cook the snake on it. It is possible to [[Snake over-cooked|over-cook]] the [[stuffed snake]]. You will know if you successfully cook or burn the snake, as there will be an animation when you try to cook it.

Travel back to [[Lumbridge Castle]], and make sure your [[m'speak amulet]] is equipped. '''Right click''' the stuffed snake, and use it on [[Awowogei]]. If you eat the snake, you'll have to get another one.

'''Congratulations! Subquest complete!'''
"""

[[steps]]
index = 6
name = "Rewards"
links = ["Cooking", "Agility", "Ape Atoll Teleport (standard)", "Culinaromancer's Chest"]
text = """
----
{{Quest rewards
|name = Recipe for Disaster/Freeing King Awowogei
|image = [[File:Recipe for Disaster (Freeing King Awowogei) reward scroll.png|centre]]
|qp = 1
|rewards =
*{{SCP|Cooking|10,000}} [[Cooking]] experience
*{{SCP|Agility|10,000}} [[Agility]] experience
*[[Ape Atoll Teleport (standard)|Ape Atoll Teleport]] spell
*Further access to the [[Culinaromancer's Chest]]
}}</onlyinclude>
"""
