quest = "Roving Elves"
step_count = 4

[[steps]]
index = 0
name = "Starting out"
links = ["Regicide", "Arianwyn", "Lord Iorwerth", "Camelot", "Islwyn", "Eluned", "Glarial", "Glarial's tomb", "Waterfall Dungeon", "Waterfall Quest", "consecration seed", "Glarial's pebble", "Golrie", "Tree Gnome Village Dungeon"]
text = """
After the events of [[Regicide]], the player decides to help the rebelling elves, led by [[Arianwyn]], against [[Lord Iorwerth]]'s apparent scheme to take over [[Camelot]]. Arianwyn sent out scouts, [[Islwyn]] and [[Eluned]], to guide you to their holdout. However, Islwyn seemingly distrusts any human and will not assist you, as it was an act of humans that led to his grandmother's death. He will mention that his grandmother was [[Glarial]], whose remains you moved from her [[Glarial's tomb|tomb]] to the [[Waterfall Dungeon]] during the [[Waterfall Quest]]. He will be surprised and relieved upon hearing this, as he believes this to be the perfect resting place for her.

Islwyn changes his mind and will help you, on the condition you complete the ritual of burying her. Speak with Eluned to learn about this ritual. She will tell you to retrieve the [[consecration seed]] from her previous resting place. Talk to Eluned before leaving for the tomb or you will not be able to retrieve the seed.

You will require [[Glarial's pebble]] to enter the tomb. If you have lost this, speak with [[Golrie]] in the [[Tree Gnome Village Dungeon]] to obtain another.
"""

[[steps]]
index = 1
name = "The consecration seed"
links = ["Glarial's Tombstone", "Glarial's Tomb", "Moss Guardian", "Prayer", "food", "potions", "Protect from Melee", "ring of recoil", "goblin paint cannon", "H.A.M. robes", "Flinching", "consecration seed", "Eluned"]
text = """
[[File:Glarial's tombstone.png|thumb|upright=0.65|[[Glarial's Tombstone]]]]
Having talked with Eluned, head towards [[Glarial's Tomb]] and use the pebble to enter it. Note that there will be many [[Glarial's Tomb#Restricted items|restrictions]] to entering the tomb.

[[File:Roving Elves moss giant.png|thumb|Fighting the [[Moss Guardian]].]]
You will need to kill any level-84 [[Moss Guardian]] to retrieve the consecration seed. Because of the restrictions towards entering the tomb, you will have to fight it using unarmed melee. [[Prayer]], [[food]], and [[potions]] may be used and it is advised to do so. As the Moss Guardian does physical damage, or unavoidable magical damage if the physical damage doesn't land, it is recommended to pray [[Protect from Melee]]. The [[ring of recoil]] will also prove effective. You can wield the [[goblin paint cannon]] to increase your attack speed, as it isn't restricted. You can wear [[H.A.M. robes|H.A.M. clothing]] for a little extra defence bonus. It is also possible to [[Flinching|flinch]] it by standing directly south of the south-eastern pillar when fighting the Moss Guardian directly west of the entrance.

Take the [[consecration seed]] back to [[Eluned]], who has possibly moved to the other location shown on the map. If she has moved, you can switch worlds until she appears. She will enchant the seed by casting a silent spell on it. If you lose the seed after this point, you may return to her for a new one.
"""

[[steps]]
index = 2
name = "Through the waterfall"
links = ["Rope", "Spade", "Key (Waterfall Dungeon)", "consecration seed", "Waterfall Dungeon", "Waterfall Quest", "Baxtorian Falls", "Chalice of Eternity", "Glarial"]
text = """
{{Needed|[[Rope]], [[Spade]], [[Key (Waterfall Dungeon)|Key]] (found in the Waterfall Dungeon) and the '''enchanted''' [[consecration seed]].

Note: After completing Waterfall Quest and the Kandarin Medium Diary, permanent ropes are now in place at Baxtorian Falls for easy dungeon access.}}

Travel to the [[Waterfall Dungeon]] with all the required items. Similar to how you entered it during the [[Waterfall Quest]], board the raft in the middle of the lake above the [[Baxtorian Falls]]. It will crash just before the waterfall. Then, ''use'' the rope on the rock to the south, followed by using the rope once again on the dead tree hanging on the edge. You will then find yourself in front of the dungeon entrance.

Inside the dungeon, search the northernmost crates in the eastern room to find a [[Key (Waterfall Dungeon)|key]]. With this key, open the locked doors in the western rooms, and proceed to the room with the [[Chalice of Eternity]]. Bury the seed anywhere next to the chalice to complete the ritual, laying [[Glarial]]'s spirit to rest.
[[File:Planting consecration seed.gif|thumb|The player plants the [[consecration seed]], with a crystal tree growing afterwards.]]
"""

[[steps]]
index = 3
name = "Ending"
links = ["Islwyn", "crystal shield", "crystal bow", "Ilfeen", "Hard Western Provinces Diary", "Mourning's End Part I", "Eluned", "Arianwyn", "Lletya", "teleport crystal", "Prifddinas", "Song of the Elves"]
text = """
Head back to [[Islwyn]] to claim your reward. You will be given a choice between a free, but partly used, [[crystal shield]] or [[crystal bow]]. Both can be bought later from him, for {{NoCoins|750,000}} and {{NoCoins|900,000}} coins respectively. These items have charges that deplete when using them, after which they will become unusable until recharged by [[Ilfeen]], for a varying cost.

You will need the crystal bow for the [[Hard Western Provinces Diary]]. Therefore, in addition to its higher cost, it is advised to take the bow.

If you have the requirements to start [[Mourning's End Part I]], it's highly recommended to speak to [[Eluned]] after claiming your reward in order to start the quest. By doing so, Eluned will teleport you to [[Arianwyn]] in [[Lletya]], while also granting you a [[teleport crystal]] with 4 charges that can be used to teleport there (and [[Prifddinas]] upon completion of the [[Song of the Elves]] quest). Eluned may have moved locations during the prior dialogue; in this case just switch worlds until she reappears.

'''Congratulations, quest complete!'''
"""
