quest = "Misthalin Mystery"
step_count = 4

[[steps]]
index = 0
name = "Riddle 1"
links = ["knife", "table (Misthalin Mystery)", "Tayten", "killer", "Notes (Misthalin Mystery - 1)", "painting (Misthalin Mystery)", "Ruby key (Misthalin Mystery)", "tinderbox", "shelves (Misthalin Mystery)", "candle (Misthalin Mystery)", "barrel (Misthalin Mystery)"]
text = """
[[File:Misthalin Mystery - Tayten dies.png|thumb|left|200px|Tayten is murdered by the Killer.]]
Enter the manor, pick up the [[knife]] on the [[table (Misthalin Mystery)|table]], and attempt to open the door with the red topaz (pink) knob up north. This will trigger another cutscene, where [[Tayten]] is murdered by the [[killer]] hiding in the wardrobe. Before returning to the wardrobe, the killer slides a [[Notes (Misthalin Mystery - 1)|note]] under the door. Pick it up and '''read it''' (You must read it in-order to progress).

[[File:Misthalin_Mystery_-_painting.png|thumb|The painting slashed with a knife.]]
The riddle refers to a [[painting (Misthalin Mystery)|painting]] found in the adjacent room to the south-west (the room with the normal door). The painting is one with mountains, a blue river, and the sun on the horizon (on the east side of the room). Use the knife on it, and search it to find a [[Ruby key (Misthalin Mystery)|ruby key]]. The doorknobs on the doors throughout the mansion will indicate the appropriate key that opens them.

Open the eastern door, and take a [[tinderbox]] from the [[shelves (Misthalin Mystery)|shelves]]. Light all four [[candle (Misthalin Mystery)|unlit candle]]s in the room, and you will get a message the room is warm enough to dry the fuse attached to the [[barrel (Misthalin Mystery)|barrel of explosives]]. Then, use the tinderbox on the barrel next to the damaged wall. Exit the room to trigger the explosion.
"""

[[steps]]
index = 1
name = "Riddle 2"
links = ["Lacey", "Killer", "Count Check", "Notes (Misthalin Mystery - 2)", "piano (Misthalin Mystery)", "emerald key"]
text = """
[[File:Misthalin Mystery - Lacey dies.png|thumb|200px|Lacey is murdered by the Killer.]]
Climb over the wall, and head north of the manor to trigger another cutscene, where [[Lacey]] is tied up. The [[Killer]] will ask her the name of the vampyre who lives in South Misthalin, but players will be given a choice; none of options matter, so pick any (the correct answer is actually [[Count Check]], but if you say it, the Killer will kill Lacey for you interfering). She will die and the Killer will leave players [[Notes (Misthalin Mystery - 2)|another note]]. Pick it up and read it.

It's like music to my ears!
<br/>The glorious sounds, spelling out your fate!

The riddle refers to the [[piano (Misthalin Mystery)|piano]] found in the north-eastern corner of the manor (music). You must enter the room through the damaged north-eastern wall. The Killer wants you dead - play the notes D-E-A-D on the piano, and search it to find an [[emerald key]].
"""

[[steps]]
index = 2
name = "Riddle 3"
links = ["Mandy", "Killer", "Notes (Misthalin Mystery - 3)", "knife", "sapphire key"]
text = """
[[File:Misthalin Mystery - Mandy dies.png|thumb|left|200px|Mandy is murdered by the Killer.]]
Return inside the manor by climbing the damaged east wall, and open the door with the emerald doorknob where the first note was found. Attempt to open the kitchen doors where [[Mandy]] is found, and another cutscene will occur where she is apparently killed by the [[Killer]]. Once again, he will leave players [[Notes (Misthalin Mystery - 3)|a third note]]. Pick it up and read it.
[[File:Misthalin Mystery - Gemstone switch panel.png|thumb|left|200px|The correct solution to the gemstone switch panel.]]

<br/>'''H'''ear at first these word'''s'''.
<br/>'''E'''ach murder you witness helplessly from start to en'''d'''.
<br/>'''A'''s you fail to solve the final letters of this qui'''z'''.
<br/>'''R'''azor sharp like a gemstone is the blade of my knif'''e'''.
<br/>'''T'''he last sound you hear will be your scream's ech'''o'''.
<br/>'''H'''eed that I will have the final word in this thrille'''r'''.

The riddle refers to the unlit fireplace in the eastern room, go out to the south-east room (the damaged wall room) and enter the north door (HEARTH). Use the [[knife]] on the unlit fireplace to reveal a panel of switches inside the hidden compartment. The correct solution corresponds to the final letter of each sentence. Therefore, to open the compartment, click the following in order (sdzeor): Sapphire - Diamond - Zenyte - Emerald - Onyx - Ruby. Search the fireplace once more to find a [[sapphire key]].
"""

[[steps]]
index = 3
name = "Showdown"
links = ["Killer", "Abigale", "Hewey", "Bandos godsword", "killer's knife", "Mandy"]
text = """
{{Bug|Mobile players may not be able to click on or move the mirror during this part of the quest. Logging out and back in or unequipping your weapon may temporarily solve it.}}{{Bug|When you confront the Killer and trigger the first cutscene, make sure you only click continue on the text box. If you click anywhere but the text box or hit spacebar before the first cutscene completes, the game will force you out of the room and end the cutscene early. This can be very confusing initially if you're unaware.}}[[File:Misthalin Mystery - confronting Killer.png|thumb|left|200px|Showdown with the mysterious Killer.]]
Open the westernmost door, and a cutscene will occur where the player confronts the [[Killer]].

He will hide in wardrobes and throw knives. The player can know which wardrobe he's in by looking for a brief black shadow surrounding the wardrobe. The player must push the mirror into the row/column of the wardrobe and '''then push it at least once towards the wardrobe''' in order to have the mirror facing the wardrobe to reflect the thrown knife back to the killer (otherwise the mirror will deflect the knife, but not back at the killer). You need to get the knife to bounce back at the killer a few times before proceeding on with the quest.[[File:Misthalin Mystery - two Killers.png|thumb|200px|They were the two killers all along!]]
After defeating the Killer, players will discover that the killer was [[Abigale]] all along! She complains about how adventurers always take all the glory from her when she tries to help others every year. However, another killer appears, and reveals himself as Abigale's boyfriend, [[Hewey]].
[[File:Misthalin Mystery - Mandy kills Abigale.png|thumb|left|200px|Mandy finishes off Abigale with a [[Bandos godsword]].]]
After basking in her glory, Abigale argues with Hewey over her selfishness, and in her anger, kills him. Pick up the [[killer's knife]] and attack Abigale.

As you attempt to leave the manor, Abigale attempts to kill you, but is stopped by [[Mandy]], who survived due to her having dextrocardia, a rare condition where her heart is located on the right side.

Speak to her outside the mansion to collect the rewards which require 3 empty inventory slots. Congratulations, quest complete!

{{clear}}
"""
