quest = "Defender of Varrock"
step_count = 4

[[steps]]
index = 0
name = "Organised Zombies?"
links = ["Lumberyard teleport", "stamina potion", "graceful set", "Jolly Boar Inn", "Elias White", "Wilderness", "Grubby key (Defender of Varrock)"]
text = """
{{Needed|None|recommended=[[Lumberyard teleport]], [[stamina potion]]s, [[graceful set]]}}
[[File:Elias White chathead.png|left]]
[[File:Defender of Varrock - inspecting the trail.png|thumb|300px|The player and Elias track down the footprints.]]
Make your way to the [[Jolly Boar Inn]] and speak to [[Elias White]], a wise explorer. He will tell you that one of the inn's patrons were raving that zombies have been organising in the [[Wilderness]], but were dismissed as the ramblings of someone who's had too much to drink. Believing there is more to the rambling, he will enlist your help in investigating the claims.

From here, you must follow the trail, inspecting the correct objects along the way; you cannot skip ahead, as the "Inspect" option will not appear unless all previous objects have been inspected.

{| class="wikitable"
|+Tracking route
!Steps
!Map
|-
|1. Inspect the plant outside the inn.
| rowspan="7" |[[File:Defender of Varrock - Path to Zemouregal's Base.png|300px]]
|-
|2. Follow the trail west, and inspect the rocks.
|-
|3. Follow the '''southern''' trail, and inspect the plant.
|-
|4. Follow the '''eastern''' trail, and inspect the spiny bush to get a [[Grubby key (Defender of Varrock)|grubby key]].
|-
|5. Follow the '''eastern''' trail through the gate, and inspect the green bush.
|-
|6. Follow the '''eastern''' trail, and inspect the small bush.
|-
|7. Follow the '''northern''' trail, and run past the end to find a trapdoor.
|}
"""

[[steps]]
index = 1
name = "The Infamous Necromancer"
links = ["Varrock Teleport", "Salve Amulet", "Zemouregal's Base", "Sharathteerk", "Mahjarrat", "Zemouregal", "Arrav", "Fourth Age", "red mist", "Lucien", "Temple of Ikov", "Bottle of mist", "Gate (Defender of Varrock)", "melee", "ranged", "Protect from Melee", "whip", "Special attacks", "dragon dagger", "salve amulet", "Bottle (Defender of Varrock)", "Stone of Jas", "broken zombie axe"]
text = """
{{Needed|Combat equipment, 3 free inventory spaces|recommended=[[Varrock Teleport]]s, [[Salve Amulet]]}}
[[File:Sharathteerk chathead.png|left|frameless]]
[[File:Defender of Varrock - plotting Mahjarrat.png|thumb|300px|Sharathteerk reporting to Zemouregal, with an undead Arrav in tow.]]
Enter the [[Zemouregal's Base|dungeon]] and finish the dialogue with Elias, then run north a little bit to a balcony. Look over the balcony to begin a cutscene showing [[Sharathteerk]], the second-in-command of the [[Mahjarrat]] [[Zemouregal]], and the now-undead [[Arrav]], a former hero of the [[Fourth Age]].

Sharathteerk will complain about being imbued with a [[red mist]], with Zemouregal saying the mist is required for the dungeon's security system. Sharathteerk will suggest allying with his cousin [[Lucien]], who you've met during the quest [[Temple of Ikov]], but Zemourgal rejects the idea, as he believes he would be serving under Lucien in such an arrangement. The two will then leave to inspect their troops. Elias will also leave, to inform the Varrockian authorities, leaving you to uncover more information within the dungeon.

To explore further, you will need [[Bottle of mist|bottles of red mist]] to bypass the dungeon's security. Each [[Gate (Defender of Varrock)|gate]] requires three bottles of mist to unlock, and each bottle will need to filled by killing an armoured zombie. Note that you will be unable to fill the bottles without watching the cutscene.

Zombies attack with either [[melee]] or [[ranged]] attacks, and the dungeon is multicombat. You can tell which attack style a zombie will use by looking at its weapon; a sword indicates melee. As there are more melee zombies, it is recommended to use [[Protect from Melee]]. After killing a zombie, click on the red mist they leave behind to fill a bottle. As the zombies have relatively low defence, a fast weapon such as a [[whip]] or a weapon with a [[Special attacks#Multi-hit|multi-hit special attack]], such as the [[dragon dagger]], are recommended. A [[salve amulet]] or its imbued versions is also beneficial as the zombies are undead creatures.
[[File:Defender of Varrock - zombie army.png|thumb|300px|Zemouregal's zombie army, ready to attack Varrock.]]
Head west and pick up three [[Bottle (Defender of Varrock)|bottles]] on the ground, then slay three zombies. After filling three bottles with [[red mist]], enter the gate to find yourself face-to-face with [[Arrav]], whose physical body is forcibly under Zemouregal's control, though he sometimes can speak of his own will when Zemouregal's concentration is elsewhere. He will tell you that Zemouregal controls him through possession of his heart.

Head further north through the corridor and refill your bottles by killing three more zombies, and open the door to the east. Run further east to the end to find another balcony; look over it to begin another cutscene. Zemouregal will tell Sharathteerk that he has no time to worry about "[[Stone of Jas|fairy tales]]" that Lucien is supposedly close to finding, and will claim the planned invasion of Varrock is his last real chance before the time for the Mahjarrat's ritual arrives.

'''Warning:''' Looking over the second balcony ends the instance of the dungeon. Ironman players looking to obtain the [[broken zombie axe]] might want to hold off on ending the instance, since the normal version of the dungeon is a popular multi-combat area.
"""

[[steps]]
index = 2
name = "The Sacred Forge"
links = ["Barronite deposit", "chaos core", "pickaxe", "combat equipment", "Mind Altar Teleport", "Varrock Teleport", "Varrock Palace", "Sir Prysin", "Captain Rovin", "Shield of Arrav", "Avarrocka", "The Legend of Arrav", "Imcando dwarves", "Ruins of Camdozaal", "Ramarno", "Sacred Forge", "imbued barronite", "barronite deposit", "Chaos Golem", "barronite rocks", "barronite shards"]
text = """
{{Needed|[[Barronite deposit]], [[chaos core]], [[pickaxe]], [[combat equipment]]|recommended=[[Mind Altar Teleport]], [[Varrock Teleport]]s}}
[[File:Ramarno chathead.png|left|frameless]]
[[File:Ramarno's Shard Exchange.png|thumb|300px|The Sacred Forge of Camdozaal, said to have been built when the city was established during the God Wars.]]
Head to [[Varrock Palace]] and speak to Elias, just outside [[Sir Prysin|Sir Prysin's]] room, who has reported to [[Captain Rovin]] that an attack on Varrock is imminent. Elias will mention the [[Shield of Arrav]], which was once used to repel Zemouregal's first attempt at invading the city of [[Avarrocka]] in a tale known as [[The Legend of Arrav]]. Elias will add that the Shield was forged by the [[Imcando dwarves]], leading you to note that the [[Ruins of Camdozaal]] were recently rediscovered, and that [[Ramarno]] may be able to help.

Make your way to [[Ruins of Camdozaal|Camdozaal]] and speak to [[Ramarno]] about the Shield of Arrav, and he will ask that you stoke the [[Sacred Forge]] with [[imbued barronite]]. As he is blind, you must be the one to gaze into the forge for answers.

The [[imbued barronite]] you must use is made by combining a [[chaos core]] with a [[barronite deposit]]. Chaos cores are dropped by [[Chaos Golem]]s in the eastern side of the ruins at a rate of 2/15, whilst barronite deposits are mined from [[barronite rocks]] on the western side at a rate of 6/25.  Note that when mining from the barronite rocks in the walls: [[Barronite deposit]] differs from [[barronite shards]]. Both can be received while mining but it is the deposits you will need to imbue on the chaos core. Use either item on the other to imbue the barronite, then use it on the Sacred Forge.

Within the Dream Theatre, you will speak to Arrav, who is temporarily free from Zemouregal's control. You will ask him how to use his shield, but he will tell you that its powers are unleashed by a person with the bloodline of the founder of Avarrocka, and that only his descendants can repel the Varrockian invasion. Suddenly, Zemouregal will appear in place of Arrav, fully aware of your interference, and tell you that his army has already begun laying siege to Varrock.

<gallery captionalign="center" widths="200">
File:Defender of Varrock - Imcando Dream Theatre.png|The player speaks to Arrav in the Dream Theatre, free from Zemouregal's control.
File:Defender of Varrock - Zemouregal interferes.png|Zemouregal appears, aware of your interference.
</gallery>
"""

[[steps]]
index = 3
name = "The True Descendant"
links = ["Shield of arrav (item)", "Varrock Palace Library", "Reldo", "scrolls (Defender of Varrock)", "List of elders", "Varrock Census", "Fourth Age", "King Roald", "Varrock Palace", "Aeonisig Raispher", "Sir Prysin", "Romeo", "Varrock Square", "Horvik", "Horvik's Armour Shop.", "Curator Haig Halen", "Varrock Museum", "Dimintheis"]
text = """
Return to Varrock Palace to find it under attack. Go two flights up the north-western staircase and speak to Elias and Captain Rovin, who will give you the [[Shield of arrav (item)|Shield of Arrav]]. Rovin will then tell you your best bet is to consult the [[Varrock Palace Library|library]] downstairs, so head to the palace library on the ground floor and speak to [[Reldo]], who will tell you about an old document he had with a list of elders who sent Arrav on his quest. Search the [[scrolls (Defender of Varrock)|scrolls]] by the flipped table in the north-east corner to obtain this [[List of elders|list]]. Read the [[Varrock Census]] north-west of the scrolls before leaving. If you happen to read the Varrock Census before searching the scrolls, you will need to destroy the list and read the census '''first'''.

<gallery captionalign="center" widths="200">
Defender of Varrock - Zemouregal at Varrock.png|Zemouregal at the northern wall of Varrock, with an army of zombies in tow.
Defender of Varrock - zombie invasion.png|Armoured zombies lay siege to Varrock Palace!
Defender of Varrock - Arrav leads the invasion.png|Arrav leading the invasion of Varrock against his will.
</gallery>

There are six elders who were alive during Zemouregal's first invasion in the [[Fourth Age]], but only one is of the founding bloodline. You must match them with the surnames found on the Varrock Census next to the flipped table.
{|class="wikitable"
!Founding elder
!Descendant
!Location
|-
|Tarrlo Remanis
|[[King Roald]]
| rowspan="2" |[[Varrock Palace]] ({{Map|type=maplink|x=3222|y=3472|mtype=pin|desc=Roald Remanis and Aeonisig Raispher}})
|-
|Dathero Raispher
|[[Aeonisig Raispher]]
|-
|Khom Prysin
|[[Sir Prysin]]
|Varrock Palace ({{Map|type=maplink|x=3203|y=3472|mtype=pin|desc=Enhtor Prysin}})
|-
|Laris Gontamue
|[[Romeo]]
|[[Varrock Square]] ({{Map|type=maplink|x=3211|y=3425|mtype=pin|desc=Romeo Gontamue}})
|-
|Ramone Ravitz
|[[Horvik]]
|[[Horvik's Armour Shop.|Armour Shop]] ({{Map|type=maplink|x=3230|y=3437|mtype=pin|desc=Horvik Ravitz}})
|-
|Marv Halen
|[[Curator Haig Halen]]
|[[Varrock Museum]] ({{Map|type=maplink|x=3260|y=3451|mtype=pin|desc=Haig Halen}})
|}

Though [[King Roald]] is a descendant of Tarrlo Remanis, he is never the "correct" person, so players need not talk to him unless they wish to read additional dialogue. Visiting the other five descendants will result in each of them failing to activate the shield's true power, but only one of them (random for each player) will reveal that they are not a blood descendant of the family line, and explain that their great-grandfather was adopted in. They will then tell you that the last true descendant of their family was married into the Fitzharmon family.

Head to south-east Varrock, past the gated area, and speak to [[Dimintheis]], who is of the noble family Fitzharmon. Upon equipping the shield, it will begin to crackle with lightning, indicating that he is indeed descended from the founder of Varrock.

A cutscene will then play where you bring Dimintheis to Varrock Palace to unleash the shield's powers on the zombies throughout the area. With the second attempt a complete failure, Zemouregal, Sharathteerk will retreat, with Arrav in tow.

<gallery captionalign="center" widths="200">
Defender of Varrock - Dimintheis attacks.png|Dimintheis unleashes the shield's latent powers.
Defender of Varrock - monk of Zamorak freed.png|The imprisoned monk, temporarily freed.
Defender of Varrock - shield saves the Queen.png|The shield saves the Queen.
Defender of Varrock - Zemouregal retreats.png|With the invasion a failure, Zemouregal is forced to retreat.
</gallery>

After the cutscene, finish the conversation with Elias and Captain Rovin to complete the quest.

'''Congratulations, quest complete!'''
"""
