quest = "Gertrude's Cat"
step_count = 2

[[steps]]
index = 0
name = "Starting out"
links = ["coins", "Gertrude", "Varrock", "Cooks' Guild", "Fluffs", "seasoned sardine", "doogle leaves", "Varrock Square", "Wilough", "Shilop", "Lumber Yard"]
text = """
{{Needed|100 [[coins]].}}

[[File:Gertrude chathead.png|left]]
Speak to [[Gertrude]] at her house west of [[Varrock]], south of the [[Cooks' Guild]]. She has lost her cat, [[Fluffs]], and she wants you to look for her. Her two children were the last to see her. If you don't already have a [[seasoned sardine]],  pick up some [[doogle leaves]] to the south.

Head to the [[Varrock Square]] and talk to [[Wilough]] or [[Shilop]]. They will tell you about their secret playground, which is the last place they remember seeing Fluffs. Pay them {{NoCoins|100}} coins to tell you the location, which is the [[Lumber Yard]] found north-east of Varrock.
[[File:Gertrude's Cat - Fluffs.png|thumb|220px|Fluffs, located on the {{FloorNumber|uk=1}} in the Lumberyard.]]
"""

[[steps]]
index = 1
name = "The secret playground (Lumber Yard)"
links = ["Bucket of milk", "seasoned sardine", "raw sardine", "doogle leaves", "Lumberyard teleport", "axe", "easy Varrock Diary", "Lumber Yard", "Fluffs", "bucket of milk", "crate (Gertrude's Cat)", "Fluffs' kitten", "ring of charos (a)"]
text = """
{{Needed|[[Bucket of milk]], and [[seasoned sardine]] '''OR''' [[raw sardine]] and [[doogle leaves]].|recommended=[[Lumberyard teleport]]. An [[axe]] to complete an [[easy Varrock Diary]] task.}}

At the [[Lumber Yard]], climb-over the broken fence on the southern side to enter, then climb up the ladder in the centre of the area. There you will find Gertrude's cat, [[Fluffs]]. Try to pick-up the cat and she will hiss at you, then use a [[bucket of milk]] on her and try to pick her up again. She will still hiss. Use the [[doogle leaves]] on the [[raw sardine]] to make a [[seasoned sardine]] and use it on her. Try to pick her up again and she will be afraid to leave; in the distance you can hear kittens mewing...

{{Map|x:3315,y:3515,title:Crate|x:3298,y:3514,title:Crate|x:3303,y:3506,title:Crate|x:3307,y:3507,title:Crate|x:3305,y:3500,title:Crate|x:3310,y:3499,title:Crate|mtype=pin|icon=greenPin|caption=Locations of all crates where kittens can potentially be found.|align=right
}}

Go down the ladder and search through the nearby [[crate (Gertrude's Cat)|crates]] with the yellow "Mew!" above them. Despite the mews moving around, the location of the kitten remains the same, so keep searching different crates until you find [[Fluffs' kitten]]. '''Click on continue''' and the kitten appears in your inventory. Do '''not''' drop the kitten or it will run away and you will have to find it again.

:'''Note:''' If the kitten didn't appear in your inventory, log out and back in.


Go back up the ladder and use the kitten on Fluffs, and they will both return home.

Return to Gertrude to complete the quest. Wear a [[ring of charos (a)]] if you want to choose the colour of your kitten reward.

'''Congratulations, quest complete!'''
"""
