quest = "Recipe for Disaster/Freeing Evil Dave"
step_count = 1

[[steps]]
index = 0
name = "Rewards"
links = ["Cooking", "hellrat", "Hellcat", "Hell-Rat Behemoth", "stew", "Spicy stew", "Culinaromancer's Chest"]
text = """
----
{{Quest rewards
|name = Recipe for Disaster/Freeing Evil Dave
|image = [[File:Recipe for Disaster (Freeing Evil Dave) reward scroll.png|centre]]
|qp = 1
|rewards =
*{{SCP|Cooking|7,000}} [[Cooking]] experience
*The ability to catch [[hellrat]]s to get a [[Hellcat]]
*The ability to have your cat fight [[Hell-Rat Behemoth]]s
*The ability to add coloured spices to [[stew]] by catching hellrats ([[Spicy stew]]s can boost and lower certain stats)
*Further access to the [[Culinaromancer's Chest]]
}}</onlyinclude>
"""
