quest = "Elemental Workshop I"
step_count = 3

[[steps]]
index = 0
name = "Bound under lock and key"
links = ["Seers' Village", "bookcase (Elemental Workshop I)", "battered book", "Fifth Age", "knife", "slash weapon", "battered key", "slashed book", "anvil", "Elemental Workshop (location)"]
text = """
Head to [[Seers' Village]] and into the house immediately south-west of the bank, indicated by the quest start icon. Search the [[bookcase (Elemental Workshop I)|bookcase]] on the east wall to receive a [[battered book]]. '''Read it''' to start the quest.

The book details the discovery of a new ore in the [[Fifth Age]], and the workshop erected to work the new material. After the true power of the unique ore was realised, the workshop was closed and bound under lock and key. The book hints that the secret to entering the workshop lies within it.

After reading it, use a [[knife]] (one spawns in the house north of the church) or [[slash weapon]] on the book to get a [[battered key]], turning it into a [[slashed book]] in the process. '''Do not drop''' the slashed book.

Enter the northern building with the [[anvil]] icon, and use the key on the odd-looking wall with the strange crack. Climb down the stairs you find there to enter the [[Elemental Workshop (location)|workshop]].[[File:Elemental Workshop (location) map.png|thumb|left|200px|A map of the [[Elemental Workshop (location)|dungeon]].]]
[[File:Elemental Workshop I - Filling a stone bowl.png|thumb|195x195px|A player filling a stone bowl with lava.]]
[[File:Elemental Workshop I Location of Leather.png|alt=Located in the north-west section of crates.|thumb|195x195px|The crate containing leather.]]
[[File:Elemental Workshop I Location of Stone Bowl.png|alt=Located in the north eastern part of the central area.|thumb|195x195px|The crate containing a stone bowl.]]
"""

[[steps]]
index = 1
name = "Restarting"
links = ["bellows (Elemental Workshop)", "elemental rock", "Water wheel (Elemental Workshop)", "Crate (Elemental Workshop I, leather)", "Crate (Elemental Workshop I, needle)", "earth elemental", "elemental ore", "Elemental Workshop II", "Mind shield", "Easy Kandarin Diary", "Boxes (Elemental Workshop)", "a stone bowl", "furnace"]
text = """
{{Needed|skills={{SCP|Crafting|20}} {{Boostable|yes}} to fix the [[bellows (Elemental Workshop)|bellows]], {{SCP|Mining|20}} {{Boostable|yes}} to mine an [[elemental rock]]}}
In the northern chamber is an inactive [[Water wheel (Elemental Workshop)|water wheel]], with two water controls to the west and east of it. Turn both to change them to green, then pull the lever near the water wheel. The water wheel should now be spinning.

Next you will need to repair the bellows, found in the eastern chamber. If you did not bring leather and a needle, they may be found in a [[Crate (Elemental Workshop I, leather)|crate]] in the north-western part of the central room, and a [[Crate (Elemental Workshop I, needle)|stacked crate]] in the western room respectively.

Fix the bellows with a spool of thread and leather ({{SCP|Crafting|20}}), then pull the lever next to it. The bellows should begin pumping air.

Head into the western cavern and attempt to mine an elemental rock ({{SCP|Mining|20}}). The rock springs to life, yells, and attacks you. Kill the [[earth elemental]], and pick up the [[elemental ore]] that it drops. The elementals walking around do not count; it must be an elemental awoken by an attempt to mine them.

:'''Tip:''' Kill two more if you want to save time for [[Elemental Workshop II]], or three more if you also want a [[Mind shield]] after completing that quest.

:'''Tip:''' You may choose to kill one of each elemental in the workshop to complete an easy [[Easy Kandarin Diary|Kandarin Diary]] task. You must kill a regular earth elemental for this, not the ones that are mined first.

Finally, head back to the central chamber. Search the [[Boxes (Elemental Workshop)|boxes]] north-east of the hatch to obtain [[a stone bowl]]. Fill it with lava from the lava trough in the southern chamber, then use it on the [[furnace]] to the east in the same chamber. The inside of the furnace should now glow orange.
"""

[[steps]]
index = 2
name = "A lost art"
links = ["elemental metal", "elemental shield", "coal", "slashed book", "Grand Exchange"]
text = """
{{Needed|skills={{SCP|Smithing|20}} {{Boostable|yes}} to smith [[elemental metal]] and [[elemental shield]]}}
Proceed to use the elemental ore, along with four [[coal]], on the furnace to obtain an [[elemental metal]] ({{SCP|Smithing|20}}). If this does not work, ensure that you used the elemental ore on the furnace rather than the coal, and that both the water wheel and bellows were successfully activated in the previous steps.

With the [[slashed book]] in your inventory, use the elemental metal on the workbench in the centre to make an [[elemental shield]] ({{SCP|Smithing|20}}). If you are unable to craft the shield, destroy the slashed book and obtain a new one from the bookcase.

'''Congratulations, quest complete!'''

:'''Tip''': You may choose to create more shields after the quest, returning with the battered key, slashed book and 4 coal to smelt with the elemental ore. The shield may also be sold on the [[Grand Exchange]] for {{Coins|{{GEP|Elemental shield}}}} gold, costing {{Coins|{{GEP|Coal}}*4}} to create.
"""
