quest = "The Ribbiting Tale of a Lily Pad Labour Dispute"
step_count = 3

[[steps]]
index = 0
name = "Crazy Frogs"
links = ["Marcellus", "Locus Oasis", "hardwood tree patch", "teak tree"]
text = """
[[File:Marcellus chathead.png|left]]
Speak to [[Marcellus]] at the [[Locus Oasis]] (fairy ring {{Fairycode|AJP}} - this is only accessible if you have visited Varlamore first), by the [[hardwood tree patch]]. He will appear to be crazy, accusing you of being in cahoots with the frogs at the other side of the oasis, believing that the frogs will enslave all of humanity.

Head to the centre of the oasis, just north of the grove of [[teak tree]]s, and speak to the blue frogs. They will tell you that they simply have gone on strike, as they believe Marcellus is mistreating them. You will then attempt to mediate between the two parties.

Return to Marcellus, who tells you that he refuses to make peace until they return his brain back, and will only negotiate with their leader.
"""

[[steps]]
index = 1
name = "Democracy at Work"
links = ["axe", "Gary", "Sue", "Cuthbert", "Dave", "Jane", "Orange tree (Locus Oasis)", "bronze axe"]
text = """
{{Needed|An [[axe]]}}
Speak to [[Gary]] or [[Sue]], who will decide to hold an election to determine who leads, and reluctantly asks you to sabotage [[Cuthbert]]'s lily pad so that he does not win the vote in the frog-hopping competition, as they believe he will declare all out war with the humans. They will also ask that you do not let [[Dave]] and [[Jane]] spot you, as they are sticklers for the rules.

Speak to Dave or Jane, who you find has already set up the lily pads for the election. You will attempt to convince them to let you inspect the lily pads, but they refuse, believing it is their duty to look after them. They will note that they are hungry, and that the oranges nearby are considered a nice treat.

Chop down the [[Orange tree (Locus Oasis)|orange tree]] near them; if you did not bring an axe, the stump near Marcellus will give a [[bronze axe]]. With the both of them distracted, sabotage the lily pad.

Return to Gary and Sue, who will begin the election. A cutscene will play in which Sue and Cuthbert compete; Sue successfully hops on the lily pad, but Cuthbert sinks into the water and dies, as he never learned how to swim.

<gallery captionalign="center" widths="200">
The Ribbiting Tale of a Lily Pad Labour Dispute - chopping orange tree.png|Distracting Dave and Jane by cutting down an orange tree.
The Ribbiting Tale of a Lily Pad Labour Dispute - election hop-off.png|The frogs' Election Hop-Off begins.
</gallery>
"""

[[steps]]
index = 2
name = "Peace Talks"
links = ["Bed (The Ribbiting Tale of a Lily Pad Labour Dispute)", "love letter", "Chest (The Ribbiting Tale of a Lily Pad Labour Dispute)", "plushy", "Capybara Dung", "Cuthbert, Lord of Dread"]
text = """
Now that Sue is the leader, she will negotiate with you and ask that in exchange for helping Marcellus by eating flies, he must pay the frogs with oranges. Take this offer to Marcellus, who will ask what the flies have done wrong. You will tell him that they are planning to kill him, but he wants proof of the flies' betrayal.
[[File:Chest (The Ribbiting Tale of a Lily Pad Labour Dispute) passcode.png|thumb|right|The interface displaying a passcode required to open the chest.]]
Return to Gary and Sue, who will suggest you steal something from Marcellus and pin it on the flies. Inside Marcellus' home, search his [[Bed (The Ribbiting Tale of a Lily Pad Labour Dispute)|bed]] for a [[love letter]]; reading it reveals he is in love with someone named Nalia, which is the passcode to the [[Chest (The Ribbiting Tale of a Lily Pad Labour Dispute)|chest]] in his home.

[[File:The Ribbiting Tale of a Lily Pad Labour Dispute - battling Cuthbert, Lord of Dread.png|thumb|300px|Cuthbert, Lord of Dread, returns with a vengeance.]]
Open the chest to retrieve a [[plushy]], then place it by the [[Capybara Dung|capybara dung]] to the east to plant the "evidence". However, upon doing so, [[Cuthbert, Lord of Dread]], is revealed to have survived the election and proceeds to attack the player. Cuthbert is a level-1 enemy and poses no meaningful threat. However, Cuthbert can still damage the player so can be killed with recoil damage for non-combat accounts.

After your epic battle with Cuthbert, Lord of Dread, speak to Marcellus, who will now accept the frogs' terms. Finish up by talking to Sue or Gary to finish the quest.

'''Congratulations, quest complete!'''
"""
