quest = "Daddy's Home"
step_count = 3

[[steps]]
index = 0
name = "Starting out"
links = ["Marlo", "Varrock", "Estate Agent", "Old Man Yarlo", "Aubury's Rune Shop"]
text = """
Begin the miniquest by speaking to [[Marlo]] in the house of the [[Varrock]] [[Estate Agent]] in north-east Varrock. He will ask you if you would be willing to complete an off-the-books favour for him by helping his father renovate his recently acquired house, explaining that the landlord isn't exactly aware of his presence there. He will direct you to [[Old Man Yarlo]] in his house in south-east Varrock, south-west of [[Aubury's Rune Shop]]. There is a saw on the ground in the same building as Marlo.
"""

[[steps]]
index = 1
name = "Yarlo's house"
links = ["planks", "bolt of cloth", "hammer", "saw", "nails", "Old Man Yarlo", "crates (Daddy's Home)", "waxwood log", "sawmill"]
text = """
'''''Items required:''' 10 [[planks]], 5 [[bolt of cloth|bolts of cloth]], a [[hammer]], and a [[saw]].''<br/>
'''''Items recommended:''' At least 60 [[nails]] of any type.''

Speak to [[Old Man Yarlo]] and he'll ask you to remove all of the old furniture in the house: a chair, a carpet, two tables, two stools, and his campbed. You must right click the carpet for the option to remove to appear. If you interrupt the cutscene you will have to rewatch it. Once this is done, speak with him again to be given the option to view a cutscene showing the wonders of the Construction skill, or skip it to watch later. Once this is done, Old Man Yarlo will ask you to build him new furniture. Everything except the bed can be built now, however the bed requires a special type of wood; search the [[crates (Daddy's Home)|crates]] in the kitchen to receive three [[waxwood log]]s, and bring them to the [[sawmill]].
[[File:Daddy's Home - removing daddy's furniture.png|thumb|300px|Removing furniture from the residence.]]
{| class="wikitable"
!Furniture!!Item requirements
!Experience
|-
|Carpet||3 bolts of cloth
|45 xp
|-
|2 wooden stools||2 planks and 4 nails in total
|30 xp per stool
|-
|2 wooden tables||6 planks and 8 nails in total
|87 xp per table
|-
|Wooden chair||2 planks and 2 nails
|58 xp
|-
|Waxwood bed||3 waxwood planks and 2 bolts of cloth
|207 xp
|}
"""

[[steps]]
index = 2
name = "Finishing up"
links = ["waxwood log", "Varrock sawmill", "sawmill operator", "waxwood plank", "Old Man Yarlo", "Construction", "Marlo"]
text = """
'''''Items required:''' 3 [[waxwood log]]s.''

Go to the [[Varrock sawmill]] and talk to the [[sawmill operator]] to receive 3 [[waxwood plank]]s. Since he knows of Old Man Yarlo, he'll provide them free of charge.

Return to Old Man Yarlo's home and build the new furniture (chair, carpet, two tables, two stools, and the bed). Speak to [[Old Man Yarlo]] again, he'll thank you and offer the player the basics and benefits of [[Construction]].

Finally, return to [[Marlo]] to claim your reward.
"""
