quest = "Black Knights' Fortress"
step_count = 3

[[steps]]
index = 0
name = "Spy mission"
links = ["Sir Amik Varze", "White Knights' Castle", "Falador", "Black Knights' Fortress (location)", "iron chainbody", "Wayne's Chains - Chainmail Specialist", "bronze med helm", "Peksa", "Barbarian Village", "cabbage", "Edgeville Monastery"]
text = """
[[File:Sir Amik Varze chathead.png|left]]
Talk to [[Sir Amik Varze]], who can be found on the {{FloorNumber|uk=2}} west wing of [[White Knights' Castle]] in [[Falador]]. Ask him for a quest, and he will tell you that he needs a spy to infiltrate the [[Black Knights' Fortress (location)|Black Knights' Fortress]]. The Black Knights claim to have developed a powerful new secret weapon, and he wants you to find it and sabotage it. He will hand you a dossier (requires a free inventory space). Read it and it will self destruct, signifying the start of the quest.

If you still need the required items, on the way to the fortress you can purchase an [[iron chainbody]] from [[Wayne's Chains - Chainmail Specialist|Wayne's Chains]] to the west of the southern entrance to Falador, a [[bronze med helm]] from [[Peksa]] in [[Barbarian Village]], and a [[cabbage]] may be taken from the [[Edgeville Monastery]].
"""

[[steps]]
index = 1
name = "Infiltrating the fortress"
links = ["iron chainbody", "bronze med helm", "cabbage", "Black Knights' Fortress (location)", "Dwarven Mine", "Oracle", "Edgeville Monastery", "Black Knight", "Aggressiveness", "Iron chainbody", "Bronze med helm", "Black Knight Captain", "Witch (Lensig)", "goblin (race)", "Greldo", "Draynor Manor"]
text = """
{{Needed|An [[iron chainbody]], a [[bronze med helm]], and a [[cabbage]] not from Draynor Manor.}}
{{Map|width=250|height=250|x=3020|y=3514|align=right|caption=The fortress is due north-east of Falador and slightly west of the Monastery.}}
Make your way to the [[Black Knights' Fortress (location)|Black Knights' Fortress]], located north-east of the [[Dwarven Mine]] and the [[Oracle]], and north-west of the [[Edgeville Monastery|Monastery]]. Run through the [[Black Knight]]s outside the fortress; they will be [[Aggressiveness|aggressive]] to players under 67 combat. Equip the [[Iron chainbody]] and [[Bronze med helm]] to disguise yourself as a Black Knight before entering through the southern door (you may enter with anything equipped in any of the other slots).

:'''Note:''' You only need to be wearing the chainbody and med helm to enter the fortress - you can then unequip it and use the slots for something else.

Throughout the following steps, there will be numerous black knights that will attack you. While in an area without any, make sure you have healed up and read ahead to the next steps to quickly pass them.
{{Checklist|
*Once inside, the wall right in front of you can be pushed. Push it to enter a small room.
*Climb up the ladder in this small room.
*Climb up the ladder immediately to the right of it.
*Climb down the ladder just south.
*Go through a door to the east.
*Go up the closest ladder.
*Climb down the ladder immediately to the east.
*Open the sturdy door to the south and climb down the ladder to the west of it.
}}

In this small room, there will be a grill. Click on it to listen. You will overhear a conversation between the [[Black Knight Captain]], a [[Witch (Lensig)|witch]] and a [[goblin (race)|goblin]]. The witch is talking about an invincibility potion she has been working on - she needs [[Greldo]] the goblin to retrieve the final ingredient to complete it, a special type of cabbage grown only in [[Draynor Manor]]. She mentions that any other type of cabbage would wreck the potion.
"""

[[steps]]
index = 2
name = "Sabotaging the secret weapon"
links = ["Edgeville Monastery", "Monk", "cabbage", "Sir Amik Varze"]
text = """
[[File:Fortress Guard chathead.png|left|frameless|80px]]
[[File:Black Knights' Fortress - Cauldron.png|thumb|220px|Dropping the cabbage creates a strange reaction.]]
:'''Note:''' Lower levelled players may choose to heal at the [[Edgeville Monastery]] to the east by speaking to a [[Monk]] before continuing.

Return to the entrance of the building and enter the room directly east; after entering, the guard will warn you the Black Knights inside are in the middle of an important meeting, and will try to kill anyone that interrupts it.
Click the option saying you don't care to enter the room, and then climb the ladder on the northern wall.

Walk around the upper, L shaped landing, and Push the wall open. '''Right-click''' your [[cabbage]] so that you do not eat it, and use it on the hole. A cutscene will play showing the potion being destroyed by the cabbage.

Return to [[Sir Amik Varze]], and tell him you sabotaged the weapon.

'''Congratulations, quest complete!'''
{{Clear}}
"""
