quest = "Swan Song"
step_count = 8

[[steps]]
index = 0
name = "Starting the quest"
links = ["coins", "ring of charos", "fairy rings", "Transportation", "Draynor Village", "Piscatoris Fishing Colony", "Piscatoris teleport", "Tree Gnome Stronghold", "Kathy Corkat", "Ring of Charos", "fairy ring", "Herman Caranos", "Wise Old Man", "Ogre shaman", "Drunken Dwarf", "The Shaikahan", "Kalphite Queen", "Dad"]
text = """
{{Needed|recommended=50 [[coins]] or a [[ring of charos]] unless using [[fairy rings]]. A [[Transportation#Teleportation|teleport]] to [[Draynor Village]] or nearby.}}

The easiest way to reach the [[Piscatoris Fishing Colony]] is to teleport using the [[Piscatoris teleport]] scroll. It can also be reached by boat, from the river west of the [[Tree Gnome Stronghold]]. To use the boat, you must either pay [[Kathy Corkat]] 50 [[coins]], or charm her while wearing the [[Ring of Charos]]. After you have started the quest, you will not need to pay her again. You can also use the [[fairy ring]] code {{Fairycode|AKQ}}, and run north-east to the Colony.

Once you reach the Colony, walk a short distance north-east, and speak to [[Herman Caranos]]. When you agree to help him, the quest will start. He will ask you to find the [[Wise Old Man]] of [[Draynor Village]] and secure his services. Agree to this, and travel to Draynor Village.

<gallery>
Swan Song flashback (1).png|Killing an [[Ogre shaman]]
Swan Song flashback (2).png|Killing the [[Drunken Dwarf]]
Swan Song flashback (3).png|Subduing [[The Shaikahan]]
Swan Song flashback (4).png|Fighting the [[Kalphite Queen]]
Swan Song flashback (5).png|Fighting [[Dad]]
</gallery>
"""

[[steps]]
index = 1
name = "The Wise Old Man"
links = ["lava rune", "mist rune", "blood rune", "Wise Old Man", "runes", "Fishing Colony"]
text = """
{{Needed|10 [[lava rune]]s, 10 [[mist rune]]s, and 5 [[blood rune]]s.}}

Talk to the [[Wise Old Man]]. After some conversation, he will tell you that he requires 10 [[lava rune]]s, 10 [[mist rune]]s, and 5 [[blood rune]]s before he will help you. Give him these [[runes]] and return to the [[Fishing Colony]].
"""

[[steps]]
index = 2
name = "Battle at the Colony"
links = ["Combat equipment", "Sea troll", "Ranged", "Magic", "safespot", "Teleportation", "Yanille", "iron bar", "logs", "tinderbox", "Piscatoris Fishing Colony", "Wise Old Man", "Herman Caranos", "Saradomin Strike", "Herman's book"]
text = """
{{Needed|[[Combat equipment]] to fight 8 level 79 [[Sea troll]]s with no [[Ranged]]/[[Magic]] [[safespot]]s.|recommended=A [[Teleportation|teleport]] to [[Yanille]], 5 [[iron bar]]s, [[logs]], a hammer, and a [[tinderbox]]. Fishing level boosting item if you're below 62.}}

{{Instance}}
[[File:Sea troll fight.png|thumb|The player and the Wise Old Man confront several sea trolls.]]
Travel back to the [[Piscatoris Fishing Colony]]. The [[Wise Old Man]] will be waiting in place of [[Herman Caranos]]. Talk to him to enter the main Colony grounds, where you will be attacked by eight (8) level 79 [[Sea troll]]s. The Wise Old Man will help you by casting [[Saradomin Strike]] on the trolls (he hits super high, sometimes over 40); however, after 10 casts, he runs out of runes and resorts to throwing stones at the trolls, with a maximum hit of 2. Note that you can "use" blood, air, and fire runes on The Wise Old Man during the fight to give him more runes. However, he will only take one rune each time you use them on him, making this not recommended as the trolls will continue to attack you. The trolls only attack with melee so using Protect from Melee will prevent you from taking any damage.

Once you have killed the trolls, enter the gates of the Colony. The Wise Old Man will tell you to find Herman Caranos, after which he will disappear. Herman is in the building at the eastern end of the Colony.

:'''Tip''': Pick up the bones that the trolls drop as you'll need 7 of them later in the quest.
:'''Optional:''' You can search Herman's desk for a [[Herman's book|book]], which tells you about the Wise Old Man's past. If you have a house with a bookcase in it, this book will become available after the quest.

When you talk to Herman, the Wise Old Man will reappear. You will then be told to do some odd jobs around the colony.
"""

[[steps]]
index = 3
name = "Repairing the Colony"
links = ["Arnold Lydspor", "Fishing Colony", "Franklin Caranos"]
text = """
The following two tasks can be done in any order:
#Talk with [[Arnold Lydspor]], and refill the [[Fishing Colony]]'s food stocks.
#Talk with [[Franklin Caranos]], and repair the Colony's walls.
"""

[[steps]]
index = 4
name = "=Arnold Lydspor="
links = ["Arnold Lydspor", "bank", "Herman Caranos", "minimap", "Arnold's Eclectic Supplies.", "Fishing Colony", "fresh monkfish", "small fishing net", "fishing spot (Swan Song)", "Sea troll", "range"]
text = """
[[File:Fishing for fresh monkfish.png|thumb|A player is attacked by a sea troll while attempting to fish.]]
[[Arnold Lydspor]] can be located in the [[bank]] to the west of [[Herman Caranos]], at the bank sign on the [[minimap]].
:'''Note:''' Arnold's bank and [[Arnold's Eclectic Supplies.|general store]] cannot be accessed until the quest is complete.

He will tell you that the [[Fishing Colony]] has no food and that he needs five cooked [[fresh monkfish]]. He will give you a [[small fishing net]] with which to catch fresh monkfish. The [[fishing spot (Swan Song)|fishing spot]] for them is located to the north-west. If you are using a boost to exactly level 62, bring at least eight doses because [[Sea troll|trolls]] will spawn each time you try to fish, which will take up time and your level may drop. Catch a few extra as you may burn the fish.

While fishing, you will be attacked by three Sea Trolls whose levels get progressively higher - levels 65, 87 and 101. You must kill these in order to continue fishing. When you have caught the fresh monkfish, you can cook it on a [[range]] to the south. When you have five cooked fresh monkfish, take them to Arnold. If you burn some, you can give him the cooked ones and go back to fish for more.  Despite being quest items, once cooked the left-click of fresh monkfish is "eat", and they will heal 1hp if eaten.
"""

[[steps]]
index = 5
name = "=Franklin Caranos="
links = ["Franklin Caranos", "Piscatoris Fishing Colony", "iron sheet", "tinderbox", "iron bar", "logs", "pickaxe", "axe", "iron ore", "dead tree", "small furnace (Piscatoris Fishing Colony)", "hammer", "clay"]
text = """
[[Franklin Caranos]] is near the entrance gate of the [[Piscatoris Fishing Colony|Colony]]. He will ask you to make five [[iron sheet]]s to repair the west walls. He will give you a [[tinderbox]] to heat the metal press. If you have the [[iron bar]]s and [[logs]], you can skip the following steps:
[[File:Fixing colony wall.png|thumb|A player fixing the colony walls.]]
Pick up a [[pickaxe]] and an [[axe]] from the pile east of Franklin. Exit the Colony via the gate, and head back underneath the hole. To the south, you should find several rocks; mine enough [[iron ore]]s to make five iron bars (you will be able to smith them with the usual 50% success rate at the Colony), and cut down a [[dead tree]] for some logs. Return to the Colony and smith your ores into bars, returning to the rocks and mining more ores if required, until you have five bars.

Go into the building with the [[small furnace (Piscatoris Fishing Colony)|furnace]], and use your logs on the Firebox east end of the press then use the tinderbox and light them. Then, use your iron bars with the press to make iron sheets. Tell Franklin that you have the sheets and he will give you a [[hammer]], with which you can repair the walls to the west. Once you have done this, talk to Franklin again.

Note: When you repair the wall, you need to use the Iron Sheets on the broken wall. If you use the hammer on the broken wall, your character will yell and hammer the wall. You'll receive a message that you feel a lot calmer, but it didn't achieve anything, and to use the iron sheets on the wall instead.

'''{{Colour|Red|Important}}:''' Keep the pickaxe since you'll need it to mine [[clay]] in the next part if you didn't bring any.
"""

[[steps]]
index = 6
name = "Raising an army"
links = ["pickaxe", "clay", "bones", "pot", "pot lid", "Wise Old Man", "Herman Caranos", "Sea troll", "Wizard Frumscone", "Wizards' Guild", "Magic", "Yanille", "Malignius Mortifer", "God Wars Dungeon", "Saradomin Cape", "Piscatoris Fishing Colony", "pottery", "amulet of glory", "Draynor Village", "Port Sarim", "Betty's Magic Emporium", "Dark Wizards' Tower", "dark wizard", "Highwayman", "chicken", "ashes", "Crafting Guild", "brown apron", "Master Crafter", "Crafting Guild mining site", "jug", "potter's wheel", "pottery oven"]
text = """
{{Needed|A [[pickaxe]] (to mine the [[clay]], needed only if you didn't bring any).|recommended=7 [[bones]], a [[pot]], and a [[pot lid]]. (If making a pot lid, bring a pickaxe.)}}

Next, go back to the [[Wise Old Man]] and [[Herman Caranos]], who tell you that they need an army to fight and defeat the [[Sea troll]]s once and for all. The Wise Old Man tells you to visit [[Wizard Frumscone]], in the basement of the [[Wizards' Guild]].
:'''Note:''' This is where you need to boost your [[Magic]] level if it is lower than 66.

You may find it advisable to pick up a [[pickaxe]], if you have not done so already, before you leave for [[Yanille]]. You can use any recommended methods as mentioned to travel to Yanille. If you use the minigame teleport to the Nightmare Zone you will need to leave the area through the tunnel first.

At Yanille, you may get seven normal [[bones]], [[pot]], and [[pot lid]] from the bank if you have them. Head into the Wizards' Guild and go down the ladder. Wizard Frumscone will appear and refuse to help you, but he does tell you of one who may - [[Malignius Mortifer]].

'''{{Colour|Red|Important}}:''' Be sure to bank any [[God Wars Dungeon#God equipment|Saradomin]]-related items prior to talking to Malignius, or he will refuse to help you. The [[Saradomin Cape]] does not count. As he teleports you to [[Piscatoris Fishing Colony]] when you speak to him, it is not advised to drop any items.

After making the [[pottery]], however, you may wear your items.
{{Map|name=Malignius Mortifer|x=2990|y=3268|r=10|mtype=square|width=250|height=250|align=right|caption=Malignius Mortifer's location.}}
You can use your charged [[amulet of glory]] if you have them to teleport to [[Draynor Village]], and head west to find Malignius, who is accompanied by elemental wizards, slightly north-west of the [[Port Sarim]] [[Betty's Magic Emporium|magic shop]].

Alternatively, you can use the southern portal at the top of the Guild to take you to the [[Dark Wizards' Tower]]. The [[dark wizard]]s drop [[bones]], so you can kill seven of them for seven bones if you still need them. Walk south, through the gate, and then south-east from here to find Malignius.

Malignius will tell you that he needs seven normal bones. You can kill [[Highwayman|highwaymen]] or the [[chicken]]s in the farm nearby for these. (You cannot kill the surrounding wizards, as they drop [[ashes]].) When you give them to him, he will tell you that you also need some way of storing the seeds he will give you, and that you should ask in the [[Crafting Guild]] to the west. He will give you a [[brown apron]], which will allow you access.

Ask the [[Master Crafter|master craftsmen]] (the one with no skillcape) about how to store the seeds until you find the one that will tell you; you will need simply a pot with a pot lid. ''You may skip the rest of this paragraph if you have both items''. Mine two pieces of [[clay]] in the [[Crafting Guild mining site|Guild mine]]; use the [[jug]] in the northern end of the Guild filled with water from the sink to the south to soften the clay, and then shape them on the [[potter's wheel]]. Fire them in the [[pottery oven]].
:'''Warning:''' Now, you may wish to restock your combat supplies for the upcoming fight at a bank as Malignius will, without any warning, teleport you to the [[Piscatoris Fishing Colony]] after you have finished talking with him.

Now, return to Malignius with your pot and pot lid, and he will teleport you to the Fishing Colony.
"""

[[steps]]
index = 7
name = "The final battle"
links = ["Combat equipment", "Sea Troll Queen", "Magic", "Melee", "Prayer", "Ranged", "safespot", "Piscatoris Fishing Colony", "Herman Caranos", "Skeleton Mage", "Sea troll", "Wise Old Man", "Sea Troll General", "Water Wave", "protection prayers", "armour", "Armadyl armour", "Protect from Magic", "Armour/Melee armour", "Mystic robes", "Wave spell", "Herman"]
text = """
{{Needed|Bone seeds, [[Combat equipment]] to defeat a level 170 [[Sea Troll Queen]], which is able to use [[Magic]] and [[Melee]] and can drain [[Prayer]]. [[Ranged]]/Magic [[safespot]]s are available but not advisable.}}
{{Instance}}

After entering the [[Piscatoris Fishing Colony|Colony]] and talking to [[Herman Caranos]], you will be shown a cutscene of your army of [[Skeleton Mage]]s defeating the [[Sea troll]]s and then the [[Wise Old Man]] killing the levelless [[Sea Troll General]]. However, while he is celebrating, he gets hit for 254 damage (which doesn't make the slightest dent on his health bar). He will be disabled for the rest of the fight, so you must take on the [[Sea Troll Queen]] yourself.

<gallery>
Rise from the Sea.png|The Sea Trolls rise from the ocean depths.
Swan Song army.png|This means war!
Sea Troll General dies.png|The Wise Old Man kills the [[Sea Troll General]]
Wise Old Man weakened.png|The Wise Old Man is badly hurt by a powerful water spell.
The Sea Troll Queen.png|You must fight the Sea Troll Queen!
</gallery>

The Queen cannot move from her location, so anywhere not directly next to her is suitable for long-ranged attacks. The Queen uses the [[Magic]] attack [[Water Wave]] and a basic [[Melee]] attack where possible. If you are using overhead [[protection prayers]] and are not within melee range, the queen will use a [[Prayer]]-draining attack. This means that ''long-ranged attacks are inadvisable'' unless you are confident in your [[armour]] to protect you from powerful magical spells (e.g. [[Armadyl armour]]). Meleeing the queen means she will not use her prayer draining attack; however, she uses both Melee and Magic attacks. She is much more damaging with magical attacks, with a max hit of '''37''', so it is '''best to use [[Protect from Magic]] and wear [[Armour/Melee armour|melee armour]]'''. She is not too hard for a skilled fighter, though she should not be taken for a pushover either, as her melee can still hit up to 16.

It is possible to wear full [[Mystic robes]] and use the Mystic Might Prayer. This way the queen splashes more often. Be careful though, she can still hit 25 consistently. Use the best [[Wave spell]] you can.

After defeating the queen, talk to [[Herman]] to finish the quest.

'''Congratulations, quest complete!'''
"""
