quest = "Sleeping Giants"
step_count = 2

[[steps]]
index = 0
name = "What is this? A workshop for giants?"
links = ["oak logs", "wool", "nails", "hammer", "chisel", "bucket of water", "ice gloves", "Giants' Plateau", "Al Kharid", "Minigame Teleport", "amulet of glory", "Hill Giant (Giants' Plateau)", "Giant anvil (Giants' Plateau)", "Giants' Foundry", "Trip hammer", "Grindstone", "Polishing wheel"]
text = """
{{Needed|3 [[oak logs]], 1 [[wool]], 10 [[nails]], 1 [[hammer]], 1 [[chisel]], 1 [[bucket of water]] or [[ice gloves]], 20 empty inventory spaces}}
[[File:Sleeping Giants - entering the Giants' Foundry.png|thumb|300px|Kovac and the player enter the Giants' Foundry.]]
[[File:Kovac chathead.png|left]]
Make your way to the [[Giants' Plateau]] east of [[Al Kharid]]. The quickest way there is the [[Minigame Teleport]] to Giants' Foundry. Alternatively, travel to Al Kharid using an [[amulet of glory]] and head east from the palace. Past the [[Hill Giant (Giants' Plateau)|Hill Giants]], a singular Hill Giant with a "Strike" option rather than an "Attack" option can be seen by a [[Giant anvil (Giants' Plateau)|giant anvil]]. Attempt to strike the Hill Giant, and it will ask you to stop, requesting your help. Accept his request to start the quest.

The Hill Giant, whose name is Kovac, will ask you to accompany him to the cave next to him. A cutscene will play, showing a workshop too big for regular-sized people to use. This is the [[Giants' Foundry]], where giants of ages past once forged weapons. Kovac wishes to restore the foundry to forge giant weapons to help his kin remember how civilised their race once was.

You must now repair the various features of the foundry that have been dilapidated. If you forgot to bring any of the required items, a big chest can be found which accesses your bank.
* [[Trip hammer]] - 1x Oak log, 5x nails
* [[Grindstone]] - Chisel
* [[Polishing wheel]] - 2x Oak log, 5x nails, 1x wool
"""

[[steps]]
index = 1
name = "Make-A-Sword"
links = ["Giants' Foundry", "bucket of water", "preform", "ice gloves", "lava pool", "Waterfall (Giants' Foundry)", "Obor", "Edgeville Dungeon"]
text = """
[[File:Giants' Foundry - Foundry Overview.png|thumb|300px|An overview of the features in the Giants' Foundry.]]
[[File:Ultimate_ironman_chat_badge.png]] You will need 20 empty inventory spaces for max 20 seconds. Drop your items, search the crate, speak to Kovac, use items on the crucible then recover items.

'''Warning:''' The initial room is an instance, pick up any dropped items before talking to Kovac or they will be lost.

Speak to Kovac once you've repaired the aforementioned objects. He will now ask that you make a sword for his old friend; this part of the quest acts as an interactive tutorial for the [[Giants' Foundry]] minigame.

Search the crate near the cave exit for an assortment of bronze and iron items, and use them on the crucible. Once it is full, speak to Kovac again, and he will tell you to set up the mould for the sword's forte, blade, and tip which match the commission.

Once you've got a fitting mould set, speak to Kovac and pour the molten metal from the crucible into the mould jig. With no weapon and shield equipped, use a [[bucket of water]] to cool the sword and obtain the [[preform]]. An empty bucket can be taken from the pile next to the polishing wheel, and filled by using the bucket on the waterfall. Alternatively, a bucket of water is not needed if you have [[ice gloves]] equipped.

Now, you must refine the preform into a quality giant sword:
* Heat the preform to maximum by using it on the [[lava pool]].  The "Heat-preform" option will increase the heat by small increments, while the "Dunk-preform" option will heat it faster. The temperature should be red.
* Hit the preform with the Trip Hammer repaired earlier, repeating until progress bar is onto the yellow section. Be sure to keep the temperature in the red while doing this, otherwise the quality of the sword will decrease. Using the Trip Hammer will cool the preform.
* Cool the preform using the [[Waterfall (Giants' Foundry)|waterfall]] until its temperature is almost green. The "Cool-preform" option will cool the preform slowly, while the "Quench-preform" option cools it more quickly.
* Use the preform on Grindstone repaired earlier, repeating until progress is onto green section. Be sure to watch the temperature as the Grindstone will heat the preform during use.
* Cool the preform in the waterfall until its temperature is high green.
* Use the preform on the Polishing Wheel, repeating until the sword is complete. The Polishing Wheel will cool the preform during use, so be sure to watch the temperature.
* '''Note:''' Kovac will accept any quality sword for the purpose of this quest, though he will comment on it being not quite up to standard.

Once you've completed the sword, speak to Kovac again. He will reveal that the sword was made for his old friend [[Obor]], who resides in the [[Edgeville Dungeon]].

Congratulations, quest complete!
"""
