quest = "Spirits of the Elid"
step_count = 3

[[steps]]
index = 0
name = "The Waterfall"
links = ["Robe of elidinis", "rope", "ancestral key", "Ranged weapons", "ammo", "runes", "Magic", "pickaxe", "ballad", "Armour", "food", "River Elid", "bronze pickaxe", "shortbow", "bronze arrows", "Desert Phoenix", "Phoenix feather", "The Golem", "Desert Diary", "Shantay Pass", "magic carpet", "amulet of glory", "ring of dueling", "Al Kharid", "Water Ravine Dungeon", "necklace of passage"]
text = """
{{Needed|[[Robe of elidinis]], [[rope]], [[ancestral key]], '''melee weapons in each of the 3 attack styles, a''' [[Ranged weapons|ranged weapon]] '''and''' [[ammo]] '''or''' [[runes]] '''for''' [[Magic]]''',''' [[pickaxe]]''',''' [[ballad]].|recommended=[[Armour]] and some [[food]].}}
[[File:Water Ravine Dungeon entrance.png|thumb|The waterfall.]]
{{Map|3371,3132|r=4|mtype=square|align=right|width=220|height=220|caption=The location of the waterfall on the map.}}
The next location is the waterfall at the source of the [[River Elid]], on the east bank. To get there, either:

*Leave Nardah and walk north-west until you come to the banks of the River Elid, and then follow them to the north until you come to a waterfall at the source of the river. On the way, you'll pass respawn points for a [[bronze pickaxe]], a [[shortbow]], and some [[bronze arrows]]. Take these if you don't already have them in your inventory.
*You will also pass by a [[Desert Phoenix]]; pluck a [[Phoenix feather]] for use in [[The Golem]] and for a medium task in the [[Desert Diary]].
*Alternatively, return to [[Shantay Pass]] (via [[magic carpet]]s or [[amulet of glory]]/[[ring of dueling]] teleport to [[Al Kharid]]). Once back in the desert, head south-east to a bridge and cross the River Elid—then, follow the river north to the [[Water Ravine Dungeon|dungeon]] entrance.
*Alternatively, you can use a [[necklace of passage]] to teleport to Eagle's Eyrie and run south-west for a short while.

When you reach the dungeon entrance, use your [[rope]] on the root above the waterfall to enter.

While wearing the Robes of Elidinis top and bottom, open the door with the ancestral key in your inventory. If you are not wearing the robes, or do not have the ballad, your character will ask what they could possibly have forgotten.
"""

[[steps]]
index = 1
name = "The Golems"
links = ["Crush", "Slash", "Stab", "Spear", "Hasta", "Defence", "black golem", "target", "Ranged", "Magic", "grey golem", "white golem", "Thieving", "Nirrie", "Tirrie", "Hallak", "Statuette (Spirit of the Elid)"]
text = """
Once you're inside, ignore the door to the north; head east a short ways to where you'll see three doors. Upon attempting to open each door, you'll be attacked by one of three coloured level-75 golems, which can only be defeated by one type of attack style ([[Crush]]/[[Slash]]/[[Stab]]). A [[Spear]] or [[Hasta]] can use all of these attack styles in one slot, and a pickaxe (if decent material) can use Stab / Crush. It is also possible to fight the black golem (Crush) unarmed, but this is only recommended if your stats are high (70+) due to its high [[Defence]] level. After defeating them, the door they protected will open. Enter the room and solve the puzzle to clear the water channel:

If you attempt to open the door before the golem has finished its death animation, another golem will spawn.
[[File:Spirits of the Elid - Clearing the Channel.png|thumb|Clearing the channel using range.]]

*The [[black golem]] protecting the '''north-east room''' is vulnerable to '''crushing attacks'''. Once inside, you'll see a [[target]] on the other side of the water channel. Attack it with [[Ranged]] or [[Magic]]. Once you've hit it, the channel will be cleared. If you don't do damage and the water doesn't start flowing, you didn't clear it.
*The [[grey golem]] protecting the '''east room''' is vulnerable to '''slashing attacks'''. Once it's dead, clear the water channel with your pickaxe.
*The [[white golem]] in the '''south room''' is vulnerable to '''stabbing attacks'''. Kill it, then clear the water channel behind the door with [[Thieving]].

After you clear all three channels, go north through the remaining door, walk around the lake, and talk to the spirits, [[Nirrie]], [[Tirrie]] and [[Hallak]]. They'll tell you to recover the sacred [[Statuette (Spirit of the Elid)|Statue of Elidinis]] and return it to the shrine in Nardah to break the curse.
"""

[[steps]]
index = 2
name = "The Crevice"
links = ["knife", "light source", "rope", "Crevice (Spirits of the Elid)", "Shoes (Spirits of the Elid)", "sole", "Genie (Spirits of the Elid)", "Genie", "Elidinis Statuette", "medium Desert Diary"]
text = """
{{Needed|[[knife]], [[light source]], [[rope]].}}

Go to Nardah and talk to the mayor again. He will tell you that they threw the statue down a [[Crevice (Spirits of the Elid)|crevice]] west of town. While you're here, take the mayor's [[Shoes (Spirits of the Elid)|shoes]] from beside the door and use your [[knife]] on them to remove their [[sole]]s. (The mayor won't let you if you're too close to him.)
{{Map|3374,2905|r=6|mtype=square|align=right|width=220|height=220|caption=The crevice, west of Nardah.}}
Go west from the general store in Nardah until you come to the crevice and use a rope on it. You need a [[light source]], or else you'll be eaten alive by tiny bugs. Talk to the [[Genie (Spirits of the Elid)|genie]] (the evil brother of the [[Genie|random event]]). He will tell you to get the mayor's sole in exchange for the statue. Give the soles to him to get the statue back.

Finally, take the statue to the shrine back in town (the building you stole the key in) and place it on the statuette plinth.

'''Congratulations, quest complete!'''

:'''Note:''' After completing the quest, pray at the [[Elidinis Statuette]] to complete a [[medium Desert Diary]] task. At least one Prayer point must be restored, praying at it with full Prayer will not complete the task.
"""
