quest = "Enter the Abyss"
step_count = 2

[[steps]]
index = 0
name = "Starting off"
links = ["Saradomin", "Guthix", "River Lum", "Edgeville", "Mage of Zamorak", "Wilderness ditch", "Wilderness", "Varrock", "Zamorak", "Aubury's Rune Shop", "runes", "Abyss"]
text = """
'''Note:''' If you are wearing any [[Saradomin]] or [[Guthix]] items, the mage will''' NOT '''speak with you. Therefore, it is best to unequip any and all god related items (with the exception of Zamorakian items) before starting a conversation with the mage of Zamorak. Simply putting the items in your inventory is enough, you don't need to bank them.

*Follow the [[River Lum]] near [[Edgeville]] until you reach the [[Mage of Zamorak]], or travel north over the [[Wilderness ditch]]; he wanders around Level 4-7 [[Wilderness]]. Talk to him, and he will explain to you that it is too dangerous to talk in the Wilderness.
*Talk to the mage back in [[Varrock]] at the [[Zamorak]] chaos temple (south-east of [[Aubury's Rune Shop]]).
*Ask him where he gets his [[runes]] from when the question is available. He will tell you about the [[Abyss]] and that he is having problems. Say that you will help him.
"""

[[steps]]
index = 1
name = "Getting the readings"
links = ["scrying orb", "rune essence mine", "Aubury", "Varrock", "Archmage Sedridor", "Wizards' Tower", "Draynor Village", "Wizard Cromperty", "East Ardougne", "Brimstail", "Grand Tree", "Wizard Distentor", "Wizards' Guild", "miniquest"]
text = """
*He will then give you a [[scrying orb]]. He will explain that you need to travel to the [[rune essence mine]] from three different locations with the orb in your inventory. This will give the scrying orb readings of where you travelled from and how you got there.
*Travel to the rune essence mines from three of the five locations.
**It is suggested you travel from [[Aubury]] in [[Varrock]], [[Archmage Sedridor]] in the basement of the [[Wizards' Tower]] (south of [[Draynor Village]]) and [[Wizard Cromperty]] in [[East Ardougne]] (north-east of the marketplace).
**One may also travel from [[Brimstail]] at his cave south-west of the [[Grand Tree]] or [[Wizard Distentor]] at the [[Wizards' Guild]].
*When you are done, go back to the chaos temple in Varrock. Speak to the Mage of Zamorak, and you will complete the [[miniquest]].
{{Clear|left}}
"""
