quest = "Ernest the Chicken"
step_count = 5

[[steps]]
index = 0
name = "Ernest the missing"
links = ["Veronica", "Draynor Manor", "Ernest", "Professor Oddenstein", "pressure gauge", "rubber tube", "oil can"]
text = """
[[File:Veronica chathead.png|left]]
Talk to [[Veronica]] standing just outside the courtyard of the [[Draynor Manor]]. She wants you to find her fiancé, [[Ernest]], who had gone to the manor an hour ago for directions and has not come back yet.

Enter the manor and climb up the staircase in the centre room. Then climb up the spiral stairs immediately west to find [[Professor Oddenstein]]. He will explain that Ernest was turned into a chicken when he was helping on an experiment with his 'pouletmorph' machine. However, to change him back, the professor needs parts that were stolen and hidden by the poltergeists in the manor.

You need to help him find a [[pressure gauge]], a [[rubber tube]], and an [[oil can]] in any order.
"""

[[steps]]
index = 1
name = "Pressure gauge"
links = ["fish food", "poison (item)", "poisoned fish food"]
text = """
[[File:Pressure gauge detail.png|left|80px]]
To get the pressure gauge, [[fish food]] and [[poison (item)|poison]] are required. Fish food is in a blue box, one is found on the {{FloorNumber|uk=1}} in the room directly south of the main staircase. Poison is in a green bottle, one is found on the {{FloorNumber|uk=0}} in the small north-western room south of the kitchen.

Use the poison on the fish food to create [[poisoned fish food]]. Go to the south-eastern room (of the {{FloorNumber|uk=0}}), '''grab the spade''' next to the door leading outside (respawn every 48s), if you do not already have one to get the rubber tube. Leave the manor by exiting the door in the south-eastern room, go to the south-western corner of the manor grounds to the fountain. '''Use''' the poisoned fish food on the fountain to kill the piranhas then search the fountain to get the pressure gauge.
"""

[[steps]]
index = 2
name = "Rubber tube"
links = ["compost heap", "belladonna", "special patch", "cabbage (Draynor Manor)", "spade", "Key (Ernest the Chicken)", "aggressive", "skeleton", "rubber tube"]
text = """
[[File:Ernest the Chicken - Rubber tube.png|thumb|220px|The rubber tube and the skeleton.]]
[[File:Rubber tube detail.png|left|80px]]
On the west side of the grounds look for a [[compost heap]], north of the [[belladonna]] [[special patch]] near a patch of [[cabbage (Draynor Manor)|cabbage]]s. Search the compost heap, requiring a [[spade]] and you will get a [[Key (Ernest the Chicken)|key]]. Go back into the manor through the front door then go through the door to the room behind the stairs containing the [[aggressive]] [[skeleton]] and take the [[rubber tube]]. The skeleton will attack you, so if you are a low level it is recommended to get the tube and leave as quickly as possible.
{{Clear|left}}
"""

[[steps]]
index = 3
name = "Oil can"
links = ["Bookcase (Draynor Manor)", "Telekinetic Grab", "oil can"]
text = """
[[File:Oil can detail.png|left|80px]]
Go to the western room on the {{FloorNumber|uk=0}}, search the [[Bookcase (Draynor Manor)|bookcase]] on the western side on the wall to gain access to a secret room. Go down the ladder into the basement where there will be doors and levers around you. It is '''not''' possible to use [[Telekinetic Grab]] to pick up the oil can.

'''Note:''' The levers can be reset by leaving the room and returning.

Follow the steps given below to obtain the oil can:
[[File:Ernest the Chicken - Oil can map.png|300px|right]]
{{Checklist|
*Pull levers B then A down.
*Enter door 1.
*Pull lever D down.
*Enter doors 2, then 3.
*Pull levers B, then A up.
*Enter doors 3, 4, and 5.
*Pull levers E, then F down.
*Enter doors 6 and 7.
*Pull lever C down.
*Enter doors 7 and 6.
*Pull lever E up.
*Enter doors 6, 8, and 3.
*Go through door 9 and grab the [[oil can]].
}}
"""

[[steps]]
index = 4
name = "Transmogrification"
links = ["Professor Oddenstein", "Ernest"]
text = """
[[File:Chicken (Ernest).png|left|80px]]
Leave the basement and leave the secret room by pulling the lever on the eastern wall.

Finally, go back to the top floor and talk to [[Professor Oddenstein]]. Give him the items, he will fix his machine which turns [[Ernest]] back into a human.
:'''Note:''' You are still required to leave the manor through the back doors.

{{Clear}}
'''Congratulations, quest complete!'''
"""
