quest = "Recipe for Disaster/Defeating the Culinaromancer"
step_count = 7

[[steps]]
index = 0
name = "=Agrith-Na-Na="
links = ["Agrith-Na-Na", "Agrith Naar", "Shadow of the Storm", "melee", "Fire Blast"]
text = """
[[Agrith-Na-Na]] is [[Agrith Naar]] from the [[Shadow of the Storm]] quest, but he is now made of bananas and is level 146. He uses [[melee]] up close and [[Fire Blast]] at a distance. Agrith-Na-Na has decent magic attack and defence, so use your best melee or ranged setup.
"""

[[steps]]
index = 1
name = "=Flambeed="
links = ["Flambeed", "Fareed", "Desert Treasure I", "ice gloves", "prayer", "snare", "cake"]
text = """
[[Flambeed]] is [[Fareed]] from [[Desert Treasure I]]. He's level 149 now. You need [[ice gloves]] to wield a weapon. If you attack him without ice gloves, your weapon will return to your inventory. He's harder to defeat without [[prayer]], but you should be able to kill him with plenty of high healing food. You can [[snare]] him, run away, and then mage him so you only use little to no food. He drops [[cake]]s.
"""

[[steps]]
index = 2
name = "=Karamel="
links = ["Karamel", "Kamil", "Desert Treasure I", "stat restore potion", "Bolt spells", "Chaos gauntlets", "Melee", "choc-ice", "Iban Blast"]
text = """
[[Karamel]] is [[Kamil]] from the [[Desert Treasure I]] quest. Fight her up close with a spell that has a lower level requirement than your actual Magic level, preferably a fire spell to take advantage of her elemental weakness. You should not be using your highest level spell, as Karamel will likely lower your magic level to the point that you are no longer able to cast it. Bring [[stat restore potion]]s and lots of food. Even with lowering your stats, Karamel is incredibly inaccurate. A good strategy is to use a [[Bolt spells|Bolt Spell]] with [[Chaos gauntlets]]. As usual, [[Melee]] doesn't work on her very well. Unlike Kamil, Karamel uses ranged attacks at melee range. Since her ranged attacks are not very strong, a good tactic is to stand right next to her so she uses ranged, which reduces how frequently she uses her ice attacks. Manually casting spells is beneficial due to her freezing effects stopping your auto-attacks. She drops a [[choc-ice]].

Note: Even though Kamil is immune to [[Iban Blast]], Karamel is not. Iban Blast can be used very effectively.
"""

[[steps]]
index = 3
name = "=Dessourt="
links = ["Dessourt", "Dessous", "Desert Treasure I", "Melee", "stab weapons", "Magic", "Iban Blast", "Ranged", "chocolate dust"]
text = """
[[Dessourt]] is [[Dessous]] from [[Desert Treasure I]]. [[Melee]] doesn't work very well on him, however he is less resistant to [[stab weapons]]. [[Magic]] such as [[Iban Blast]] works well. [[Ranged]] also works really well on him. Bring lots of food, and then, defeat him as quickly as possible. He drops [[chocolate dust]].
"""

[[steps]]
index = 4
name = "=Gelatinnoth Mother="
links = ["Gelatinnoth Mother", "Dagannoth Mother", "Horror from the Deep", "Magic", "Defence", "dragonhide armour", "dragonfire shield", "granite shield", "toktz-ket-xil", "Barrows equipment", "Mystic robes", "Air spells", "Wind Strike", "Wind Bolt", "Wind Blast", "Wind Wave", "Wind Surge", "Water spells", "Water Strike", "Water Bolt", "Water Blast", "Water Wave", "Water Surge", "Melee", "Earth spells", "Earth Strike", "Earth Bolt", "Earth Blast", "Earth Wave", "Earth Surge", "Fire spells", "Fire Strike", "Fire Bolt", "Fire Blast", "Fire Wave", "Fire Surge", "Ranged"]
text = """
[[Gelatinnoth Mother]] is the [[Dagannoth Mother]] from the [[Horror from the Deep]] quest, with that in mind you will need to bring Water, Air, Earth, and Fire runes in order to attack her during her weakness. She uses a ranged attack that rolls two hits per attack, one magic based and one ranged based. Each hit is capable of hitting for 20 for a possible max hit of 40 per attack. Players who have 80 or less health can die easily with a bit of bad luck and slow eating. The fight itself is fairly easy, although a bit long. She changes colour depending on her weakness. She has a low [[Magic]] [[Defence]] but high Melee Defence, making it best to not bother with Melee and just focus on maging and ranging. A great strategy is to mage her while wearing a mix of the best [[dragonhide armour]] available, a shield such as a [[dragonfire shield]], [[granite shield]], or [[toktz-ket-xil]], and melee helmet such as [[Barrows equipment|Barrows]]. Otherwise, she will rip through [[Mystic robes]] and other magic robes with her ranged attacks. This would give the player a balanced Defence against both Ranged and Magic Defence without sacrificing too much Magic attack bonus.

{| class="wikitable"
!Image
!Colour
!Weakness
!Attack Using
|-
|[[File:Gelatinnoth Mother (air).png|frameless|100x100px]]
|White
|[[Air spells]]
|[[Wind Strike]], [[Wind Bolt|Bolt]], [[Wind Blast|Blast]], [[Wind Wave|Wave]], or [[Wind Surge|Surge]].
|-
|[[File:Gelatinnoth Mother (water).png|frameless|100x100px]]
|Blue
|[[Water spells]]
|[[Water Strike]], [[Water Bolt|Bolt]], [[Water Blast|Blast]], [[Water Wave|Wave]], or [[Water Surge|Surge]].
|-
|[[File:Gelatinnoth Mother (melee).png|frameless|100x100px]]
|Orange
|[[Melee]]
|[[Melee]] attacks.
|-
|[[File:Gelatinnoth Mother (earth).png|frameless|100x100px]]
|Brown
|[[Earth spells]]
|[[Earth Strike]], [[Earth Bolt|Bolt]], [[Earth Blast|Blast]], [[Earth Wave|Wave]], or [[Earth Surge|Surge]].
|-
|[[File:Gelatinnoth Mother (fire).png|frameless|100x100px]]
|Red
|[[Fire spells]]
|[[Fire Strike]], [[Fire Bolt|Bolt]], [[Fire Blast|Blast]], [[Fire Wave|Wave]], or [[Fire Surge|Surge]].
|-
|[[File:Gelatinnoth Mother (ranged).png|frameless|100x100px]]
|Green
|[[Ranged]]
|[[Ranged]] attacks.
|}
"""

[[steps]]
index = 5
name = "=Culinaromancer="
links = ["Gelatinnoth Mother", "Culinaromancer", "Defence", "Magic", "max hit", "crush"]
text = """
After you've defeated the [[Gelatinnoth Mother]], the [[Culinaromancer]] himself will attack you. He's level 75, hits high (can hit rapid 25s with magic), but has practically no [[Defence]]. He uses [[Magic]], but tries to get up close to attack as well. Kill him with any attack style and bring food. It is recommended to use armour that maximizes [[max hit]] (and to a lesser extent [[crush]] defence), as his magic attack has a flat 1-in-3 hit rate, so magic defence is irrelevant.

If you happen to defeat the Culinaromancer with a full inventory, the reward lamp will drop at your feet when you return to the Lumbridge castle.

A cake will drop to the ground, but you are unable to pick it up. It is mostly symbolic.
<gallery>
Fighting Agrith-Na-Na.png|Fighting Agrith-Na-Na.
Fighting Flambeed.png|Fighting Flambeed.
Fighting Karamel.png|Fighting Karamel.
Fighting Dessourt.png|Fighting Dessourt.
Fighting Gelatinnoth Mother.png|Fighting the Gelatinnoth mother.
Fighting Culinaromancer.png|Fighting the Culinaromancer.
</gallery>
[[File:Culinaromancer_dies.gif|center|frame|The Culinaromancer is defeated!]]
'''Congratulations! Quest (finally!) complete!'''
"""

[[steps]]
index = 6
name = "Rewards"
links = ["experience lamp", "Culinaromancer's Chest", "barrows gloves"]
text = """
----
{{Quest rewards
|name=Recipe for Disaster
|image=[[File:Recipe for Disaster (Defeating the Culinaromancer) reward scroll.png|centre]]
|qp=1
|rewards=*An [[experience lamp]], which grants 20,000 experience to any skill above 50 (can be banked for later use)
*Full access to the [[Culinaromancer's Chest]], containing [[barrows gloves]]
}}</onlyinclude>
"""
