quest = "Witch's House"
step_count = 4

[[steps]]
index = 0
name = "Lost ball"
links = ["boy", "Taverley", "ball", "Nora T. Hagg"]
text = """
[[File:Witch's House - Boy.png|thumb|220px|Talking to the [[boy]].]]
Head to [[Taverley]] and talk to the [[boy]] near the eastern entrance along the hedges. He will start crying; ask him what's the matter, and he will say that he kicked his [[ball]] over the hedge into the garden, and the [[Nora T. Hagg|witch]] living in the house put it in her shed. The boy wants you to get it back for him.
"""

[[steps]]
index = 1
name = "Breaking in"
links = ["Door key (Witch's House)", "Diary (Witch's House)", "leather gloves", "boxes (witch's house)", "gate (witch's house)", "cupboard (witch's house)", "Magnet (Witch's House)", "cheese", "Mouse (Witch's House)"]
text = """
[[File:Witch's House - Breaking in.png|thumb|220px|The location of the [[Door key (Witch's House)|key]].]]
{{Needed|Cheese, gloves, combat equipment}}
Head west then north around the hedge to the front door of the house - it is locked. Look-under the pot north of the door to find a [[Door key (Witch's House)|door key]] and enter the house. Read the entire [[Diary (Witch's House)|diary]] on the table.

Go down the ladder in the northern room to enter the basement. If you don't already have [[leather gloves]], search the [[boxes (witch's house)|boxes]] for a pair, however it may take many attempts to find them. Equip your gloves, go through the [[gate (witch's house)|gate]], and search the [[cupboard (witch's house)|cupboard]] for the [[Magnet (Witch's House)|magnet]]. Go back up the ladder and into the southern room with the door that leads to the garden. Drop your [[cheese]] or use it on the mouse hole. Suddenly, a [[Mouse (Witch's House)|mouse]] will come out; use the magnet on the mouse and it will unlock the door. '''Be quick or the mouse will leave, and you will lose the cheese.''' Enter the door into the garden.
{{Clear|left}}

[[File:Nora T. Hagg.png|60px|left|frameless]]
"""

[[steps]]
index = 2
name = "Getting past the witch"
links = ["Nora T. Hagg", "fountain (witch's house)", "Key (Witch's House)"]
text = """
Once in the garden, you will see the [[Nora T. Hagg|witch]] walking back and forth in the middle. You cannot walk through the garden, and must walk around it while using the hedges as cover until you reach the [[fountain (witch's house)|fountain]]. If the witch catches you, she will teleport you out of the garden and you will have to repeat most of the previous steps. Search the fountain to obtain a [[Key (Witch's House)|key]].

{{Clear|left}}
"""

[[steps]]
index = 3
name = "Witch's experiment"
links = ["Witch's experiment", "Rings of recoil", "Dwarf multicannon", "safespot", "Flinching", "ball", "Ranged", "Magic"]
text = """
Head to the shed (east of the courtyard) and use the key on the door. Do '''not''' attempt to take the ball otherwise the [[Witch's experiment]] will lower your stats. Attack the Witch's experiment. Each time you kill the experiment's current form it changes to a stronger form. You have to kill the experiment four times before it is defeated - the first stage is a Skavid (level 19), then a spider (level 30), then a bear (level 42), and finally a wolf (level 53). If you flee during the battle you will have to start over.
[[File:Witch's House - Fighting the Witch's experiment.png|thumb|220px|Fighting the [[Witch's experiment]].]]

:'''Note:''' [[Rings of recoil]] may be used - a maximum of 4 will be required, as the experiments combined have a total of 144 hitpoints.

:'''Note:''' You cannot use a [[Dwarf multicannon]] in the shed.

The first and second forms can be [[safespot]]ted with Magic or [[Flinching|flinched]] with Melee by going into the north-east corner and waiting for the experiment to move south of you. Once it is in position, run past it, then walk on top of it. After this, walk west 1 tile so you are positioned diagonally from the Witch's experiment, then you're free to attack.

The third and fourth can also be safespotted by walking to the south wall of the shed between the sacks and the crate with the [[ball]] on it and using [[Ranged]] or [[Magic]] attacks from there.

Once you have killed the Witch's experiment, take the ball and return it to the boy.

'''Do not let the witch see you''' or she will teleport you outside and '''you will lose the ball'''. You can avoid needing to pass her by teleporting out. If she does catch you, the doors to the shed will need to be unlocked again. Although the creature will respawn, it will not attack you.

'''Congratulations, quest complete!'''
"""
