quest = "Architectural Alliance"
step_count = 1

[[steps]]
index = 0
name = "Main"
links = ["Hosa", "Kourend Castle", "favour", "Arcis", "Arceuus", "Piliar", "Port Piscarilius", "Lovada", "Lovakengj", "Shayda", "Shayzien", "Hosidius"]
text = """
{{Map|name=Statue|1637,3673|r=5|mtype=square|align=right|width=260|height=260|caption=Location of the statue}}
Speak with [[Hosa]] by the statue of King Rada I in Great Kourend to start this miniquest. The Hosidius architect explains that he wishes to rebuild the statue of King Rada I in the [[Kourend Castle]] courtyard after it was heavily damaged in a storm. However, he is unable to receive the assistance of the other architects in their respective cities, and requests that you do so for him.

In order to receive the assistance of a Great Kourend architect, players need to speak with them once they gain 100% [[favour]] with their respective city. Once players have spoken to an architect, they will then appear at the statue. In order to complete the miniquest and rebuild the statue of King Rada, players must gain 100% favour with all cities.

The location of the architects are as follows:
{|class=wikitable style="text-align:center;"
! colspan=5|Locations
|-
|{{Map|name=Arcis|1652,3754|mtype=pin|icon=redPin|caption=[[Arcis]] in [[Arceuus]].|width=200|height=200}}
|{{Map|name=Piliar|1794,3738|mtype=pin|icon=redPin|caption=[[Piliar]] in [[Port Piscarilius]].|width=200|height=200}}
|{{Map|name=Lovada|1487,3833|mtype=pin|icon=redPin|caption=[[Lovada]] in [[Lovakengj]].|width=200|height=200}}
|{{Map|name=Shayda|1532,3545|mtype=pin|icon=redPin|caption=[[Shayda]] in [[Shayzien]].|width=200|height=200}}
|{{Map|name=Hosa|1631,3671|mtype=pin|icon=redPin|caption=[[Hosa]] in [[Hosidius]].|width=200|height=200}}
|}
"""
