quest = "Recipe for Disaster/Freeing Sir Amik Varze"
step_count = 2

[[steps]]
index = 0
name = "=Evil Chicken and Black Dragon="
links = ["Cook (Lumbridge)", "Wise Old Man", "Draynor Village", "Evil Chicken (Recipe for Disaster)", "Zanaris", "combat", "Anti-dragon shield", "black dragon", "raw chicken", "Dragonfire shield", "halberd", "safespot", "dragon token", "random event", "Magic", "Evil chicken's egg", "cinnamon", "pestle and mortar", "ice gloves", "K'klik", "Antifire potion", "cat", "kitten", "Call follower", "Brulee supreme", "Sir Amik Varze", "The Fairy Dragon"]
text = """
{{Map|2818,2895|align=right|mtype=square|r=3|caption=There are five vanilla plants. You only need one Vanilla Pod to complete the quest, and the item has no other uses.|width=250|height=250}}

#'''Note:''' If you do not talk to the [[Cook (Lumbridge)|Cook]] before this point in the sub-quest, you will not have the option to ask about the Evil Chicken through the Wise Old Man's Dialogue. Return to Lumbridge Castle and talk to him if you have not done so.
#Talk to the [[Wise Old Man]] of [[Draynor Village]], in the building north of the bank. Choose the option about wanting to ask him something, and ask to talk about strange beasts, and then, ask about the [[Evil Chicken (Recipe for Disaster)|Evil Chicken]].
{{Instance}}
[[File:Fighting Evil Chicken.png|thumb|240px|A player fighting the Evil Chicken in its lair.]]
# Enter [[Zanaris]] and use the bank to set up for some [[combat]]: bring your [[Anti-dragon shield]], and whatever you think you'll need to kill the [[Evil Chicken (Recipe for Disaster)|Evil Chicken]] and a safespottable level 227 [[black dragon]]. In case you choose to bank between them, you will need another [[raw chicken]]. The Evil Chicken is level 159 if you are between 58-100 combat — level 170 if you're higher. Once you are ready for the fights, equip your anti-dragon shield, and use a raw chicken (green Raw chicken from Morytania will not work) on the Evil Chicken shrine north of the fairy ring that leads to the shack in Lumbridge (North-east of the fairy ring that you teleport into normally).
# With your anti-dragon shield (or [[Dragonfire shield]]) equipped, kill one [[black dragon]]. If you are ranging or using a [[halberd]], there is a [[safespot]] next to the entrance and just inside the corridor that leads to a mine. When it dies, the dragon will drop a [[dragon token]]. '''Note:''' If you die whilst killing the black dragon and the evil chicken's egg is in your inventory, the egg will respawn in the nest.
# Run past the black dragons into the northern cave (not the mining-area to the east), and kill the Evil Chicken. It fights the same as it used to during [[random event]] fights. The Evil Chicken hits frequently with [[Magic]], but for very low damage - it shouldn't be too hard to kill. '''Take note that if you happen to die before you leave the lair after killing the Evil Chicken, all items dropped on death will disappear!''' Pick up the [[Evil chicken's egg|egg]] it drops.
#Back in a bank, add the egg to the brulee, and then, grind your dramen branch into [[cinnamon]] with your [[pestle and mortar]] and add that too. A game message should now tell you that "Now it just needs flambeing."
#Put your [[ice gloves]] on, and then, rub the token. [[K'klik]] will appear (you must be in Lumbridge or Zanaris for this to work). Wish for it to flambé your brulee to cook it. You can take up to 50 damage if you don't wear any ice gloves (it is possible to reload the game to stop the scene if you forgot, alternatively you can use the second dialogue option "Could I just keep your token" to exit the dialogue & return to the world). ([[Antifire potion]] + [[Anti-dragon shield]] works as well.) If a [[cat]] or [[kitten]] is following you, a glitch may occur where it disappears. Your pet is still following you - simply log out and log back in to fix this or "[[Call follower]]" on "Worn Equipment" tab.
#Travel back to Lumbridge Castle and then give the [[Brulee supreme|brulee]] to [[Sir Amik Varze]] to protect him.
{{Listen
|title = [[The Fairy Dragon]]
|desc = The music which plays when meeting K'klik.
|filename = The Fairy Dragon.ogg
}}
[[File:Flambéing brulee supreme.gif|thumb|upright=0.6|[[K'klik]] flambees the brulee.]]
"""

[[steps]]
index = 1
name = "Rewards"
links = ["Cooking", "Hitpoints", "Evil Chicken's Lair", "black dragon", "Evil Chicken", "Culinaromancer's Chest", "Evil Chicken (Recipe for Disaster)", "Nightmare Zone"]
text = """
----
{{Quest rewards
|name=Recipe for Disaster/Freeing Sir Amik Varze|image=[[File:Recipe for Disaster (Freeing Sir Amik Varze) reward scroll.png|center]]|qp=1|rewards=*{{SCP|Cooking|4,000}} [[Cooking]] experience
*{{SCP|Hitpoints|4,000}} [[Hitpoints]] experience
*Access to the [[Evil Chicken's Lair]], where you can fight [[black dragon]]s (The [[Evil Chicken|fowl beast]] himself has moved on to other things.)
*Further access to the [[Culinaromancer's Chest]].

Unlocks:
* [[Evil Chicken (Recipe for Disaster)|Evil Chicken]] accessible in the [[Nightmare Zone]].
}}</onlyinclude>
"""
