quest = "Rum Deal"
step_count = 8

[[steps]]
index = 0
name = "Setting out"
links = ["Pirate Pete", "Ectofuntus", "Braindeath Island", "Captain Braindeath", "Zombie pirate (Braindeath Island)", "Captain Donnie", "Blindweed seed", "blindweed", "zombie swab"]
text = """
[[File:Rum Deal protestors.png|thumb|220px|Zombies protesting outside the brewery.]]
Talk to [[Pirate Pete]] at the dock north-east of the [[Ectofuntus]] to start the quest. Pirate Pete claims to be a dispossessed nobleman who needs to reclaim his family sword in order to defeat his evil half-brother, who has stolen his lands and is now terrorizing the local lemon farmers. Agree to help him, after which he will warn you about his brother's dangerous ally, the demon Barrelor the Destroyer. Agree nonetheless; Pete will explain his half-brother has stolen most of his fortune, but he will gladly part with what remains for your help. Refuse the money he offers you. He will instruct you to pick up a diversion, knock you out and row you to a secret location.
[[File:Rum Deal meeting.png|thumb|left|220px|Pirate Pete brings you to Captain Braindeath.]]
A cutscene ensues in which Pete delivers you, tied up and unconscious, to a worried pirate captain, revealing that the entire story was fabricated. Upon awakening, you will find yourself in a small room with the captain, who will explain that you are in the brewery on the secret [[Braindeath Island]]. He introduces himself as [[Captain Braindeath]], and explains that a week ago the island came under siege of a group of [[Zombie pirate (Braindeath Island)|zombie pirates]] protesting. He needs to make some 'rum' in order to get the protesters' leader [[Captain Donnie]] drunk, after which Braindeath and his brewers can sneak out of the factory and set up a new brewery elsewhere. You will have to gather the ingredients to make the rum.

Braindeath will give you a [[Blindweed seed|seed]] in order to grow the first ingredient, [[blindweed]]. He explains the [[zombie swab]]s have trashed the previous blindweed patches, but that intimidation should be sufficient to get rid of them.
"""

[[steps]]
index = 1
name = "Brewing "rum""
links = []
text = """

"""

[[steps]]
index = 2
name = "=Blindweed="
links = ["Rake", "seed dibber", "cupboard (Rum Deal)", "farming patches", "zombie swab", "Captain Braindeath", "stagnant water"]
text = """
[[File:Rum Deal - kitten censor.png|thumb|220px|"We interrupt this insult to bring you this soothing picture of a kitten. Normal service will be resumed shortly. Thank you for your patience."]]{{Needed|[[Rake]] and [[seed dibber]].}}
If you don't have the rake and seed dibber yet, go down the ladder in the north-west corner of the building to the basement, and then head south-east past the spiders to find a [[cupboard (Rum Deal)|cupboard]]. There, take the rake and seed dibber from the cupboard.

Leave the building by the southernmost stairway, towards the [[farming patches]]. You may be attacked by [[zombie swab]]s; walk out of combat and right-click to "Intimidate" them, which permanently stops them from attacking you. A picture of a kitten will be shown to censor your insults.

The only usable farming patch is the south-eastern one. Use your rake on the patch to remove the weeds and then plant the seed (requires {{SCP|Farming|40|link=yes}}).  '''''Note:''''' If you have grabbed more then one seed by drop trick this will plant all of them in the stack, once planted you will be unable to get more. Wait a few minutes for the blindweed to grow; you will receive the notification "''I wonder how my blindweed is coming along...''". Harvest the crop. '''''Note:''' Should you lose the blindweed after this, Braindeath will give you some he had in storage all along.''

[[File:Rum Deal Hopper.png|thumb|220px|The hopper is in the north-west corner.]]
Return to [[Captain Braindeath]], who will tell you to put the blindweed in the hopper upstairs. Use the south-eastern ladder to climb upstairs and then use the blindweed on the hopper in the north-western corner of the room. You can ignore the lever for now. Talk to Captain Braindeath for the next ingredient; [[stagnant water]].
"""

[[steps]]
index = 3
name = "=Stagnant water="
links = ["Bucket", "bucket", "50% Luke", "Ring of charos", "tinderbox", "Captain Braindeath"]
text = """
{{Needed|[[Bucket]].}}
Braindeath will hand you a [[bucket]] unless you already have one. You will have to travel to a nearby volcano and fill the [[bucket]] with the stagnant water.

Leave the house via the south stairway again and exit the outside fence, then travel north-west to find [[50% Luke]] guarding a small gate (you may equip a [[Ring of charos|Ring of charos (a)]] or use a [[tinderbox]] on him for some amusing dialogue). Pass the gate behind him and travel up the volcano to collect the stagnant water. Return to the house, pour the water into the hopper, and talk to [[Captain Braindeath]].
"""

[[steps]]
index = 4
name = "=Sluglings="
links = ["Fishbowl and net", "fishing spots", "sluglings", "karamthulhu", "Captain Braindeath"]
text = """
Braindeath will give you a [[Fishbowl and net|fishbowl tangled in a big net]]. '''''Note:''' If you untangle the fishbowl and net, you have to use them on each other to re-tangle them.'' Head to the [[fishing spots]] near the farming patch you used earlier. You have to catch a total of FIVE (5) [[sluglings]] or [[karamthulhu]] and add them to the pressure barrel upstairs in the building, next to the hopper. Pull the lever, and the brewing control apparatus downstairs will start to spin and shake uncontrollably. Return to [[Captain Braindeath]].
"""

[[steps]]
index = 5
name = "=Evil spirits="
links = ["Davey", "prayer points", "holy wrench", "Evil spirit", "Protect from Melee", "safespot", "Ranged", "Magic", "halberd"]
text = """
[[File:Holy wrench blessing.png|thumb|220px|Blessing the wrench.]]
The captain will tell you that the controls for the brewery have become possessed, which "occasionally happens". He will give you a wrench in order to beat the controls with it, but remarks that it requires a blessing first for the possessing spirit to come out. Head to the west side of the house and get your wrench blessed by former priest [[Davey]]. He will only bless the wrench if you have 47 or more '''available [[prayer points]]'''. ''Note that this does '''not''' drain any prayer points.''

Now, beat up the controls with the [[holy wrench]]. They are located directly south of Captain Braindeath. As soon as you hit the controls, a level 150 [[Evil spirit]] will appear and attack you. His attacks can be negated with [[Protect from Melee]], or by using a [[safespot]] with [[Ranged]], [[Magic]], or a [[halberd]].
"""

[[steps]]
index = 6
name = "=Fever spider="
links = ["Magic", "Ranged", "Halberd", "disease", "Slayer gloves", "Relicym's balm", "fever spider", "Protect from Melee", "safespot", "slayer gloves", "Morytania Diary"]
text = """
{{Needed|recommended=Means to deal damage at range ([[Magic]], [[Ranged]] or a [[Halberd]]) '''or''' means to negate [[disease]] (such as [[Slayer gloves]] or a [[Relicym's balm]]).}}
Having defeated the evil spirit, Captain Braindeath will tell you that the final ingredient is the carcass of a diseased [[fever spider]]. You must complete the dialogue with him or the carcass will not drop!

Go down the nearby ladder into the basement and kill a fever spider. Be warned that fever spiders inflict [[disease]] on hit, even with [[Protect from Melee]]; you can circumvent this by using a [[safespot]] or having [[slayer gloves]] equipped, or using a cure such as [[Relicym's balm]]. Collect its carcass, use it on the hopper, and return to Captain Braindeath.

Note that killing the fever spider completes a [[Morytania Diary#Medium|medium Morytania Diary]] task.

<gallery captionalign="center" widths="220">
Rum Deal farming.png|Sowing some blindweed amidst the terrified zombie crew of The Inebriated.
Rum Deal - stagnant lake.png|Collecting a bucket of stagnant water.
Rum Deal - fishing sluglings.png|Using the fishbowl and net to catch sluglings.
Rum Deal - fighting evil spirit.png|Battling the evil spirit.
</gallery>
"""

[[steps]]
index = 7
name = "Captain Donnie"
links = ["Captain Donnie", "unsanitary swill", "Rabid Jack", "Captain Braindeath"]
text = """
Now that the 'rum' is complete, collect some with a bucket from the output tap at the south end of the machinery. Braindeath gives you a bucket if you don't already have one.

Head outside and find [[Captain Donnie]] near the farming patches to give him the [[unsanitary swill]]. He will smell the 'rum' and demand you hand it over, downing it as quickly as possible. He will then accidentally disclose the name of his boss, [[Rabid Jack]]. Return to [[Captain Braindeath]] to inform him of this. He will be shocked at Jack's name before pretending he had never heard of it before. He then thanks you for your help and announces the brewery is not going to be relocated, and they will keep the zombies too drunk to be a bother.

'''Congratulations, quest complete!'''
"""
