quest = "Alfred Grimhand's Barcrawl"
step_count = 7

[[steps]]
index = 0
name = "Starting out"
links = ["Agility", "Barbarian Outpost", "Barcrawl card", "runes", "teleport tablet", "Karamja"]
text = """
To begin, talk to one of the barbarian guards outside the [[Agility]] training area at the [[Barbarian Outpost]] (Games necklace) to get the [[Barcrawl card]]. If your inventory is full, the guard will make no mention of the miniquest and you '''will not receive the card'''. While doing the bar crawl, you'll be given a card with a list of all the bars you have to visit. Take the card with you and each one will be checked off when you've visited the bar and drunk the specific brew required. If you lose the card, you'll have to start the entire miniquest all over again.

You'll need to tell the barkeepers that you're doing the Alfred Grimhand Barcrawl and they will give you what you need. The brews are very strong, though, causing some damage as well as some steep temporary drops in stats. The entire trip will cost around 230 coins, plus any money for [[runes]]/[[teleport tablet|tablets]] and boat trips to [[Karamja]]. Once you have every line of the card signed, return it to one of the guards at the Barbarian Outpost.
"""

[[steps]]
index = 1
name = "Visiting the bars"
links = ["Hitpoints", "jewellery box", "Blue Moon Inn", "Varrock", "Attack", "Defence", "Strength", "Smithing", "Blurberry Bar", "Grand Tree", "Dead Man's Chest", "Brimhaven", "Brimhaven Agility Arena", "Herblore", "Cooking", "Prayer", "Dragon Inn", "Yanille", "Flying Horse Inn", "Ardougne", "Forester's Arms", "Seers' Village", "Fletching", "Firemaking", "Woodcutting", "Jolly Boar Inn", "Lumber Yard", "Mining", "Crafting", "Magic", "Karamja Wines, Spirits, and Beers", "Musa Point", "Rising Sun Inn", "Falador", "Ranged", "Fishing", "Rusty Anchor Inn", "Port Sarim"]
text = """
You can visit the bars in any order. The amount of damage dealt by the damaging drinks is dependent on your [[Hitpoints]] level. For the possible routes, check out the section after the table below. Note that a very cost efficient way to get around is by going on to a house party world (World 330 for example) to use the teleports and the [[jewellery box]]es provided by the hosts.
{|class="wikitable lighttable" style="text-align:center;"
!Bar
!Location
!Drink Name
!Cost (Coins)
!Effects
!Map
|-
|[[Blue Moon Inn]]
|South-central [[Varrock]]
|Uncle Humphrey's Gutrot
|50
|Lowers [[Attack]], [[Defence]], [[Strength]], [[Smithing]] and [[Hitpoints]]. Makes you say, "Blearrgh!"
|{{Map|3225,3399|rectX=18|rectY=12|mtype=rectangle|width=200|height=200}}
|-
|[[Blurberry Bar]]
|{{FloorNumber|uk=1}} of the [[Grand Tree]], south-eastern corner (west of Heckel Funch's grocery/liquor store. Talk to Blurberry, '''not''' 'The Barman')
|Fire Toad Blast
|10
|Lowers health.
|{{Map|2480,3491|2480,3486|2485,3486|2485,3491|mtype=polygon|plane=1|width=200|height=200}}
|-
|[[Dead Man's Chest]]
|[[Brimhaven]] (south-west of [[Brimhaven Agility Arena]])
|Supergrog
|15
|Lowers [[Attack]], [[Defence]], [[Herblore]], [[Cooking]] and [[Prayer]]. Causes double vision.
|{{Map|2791,3170|2791,3154|2800,3154|2800,3170|mtype=polygon|width=200|height=200}}
|-
|[[Dragon Inn]]
|[[Yanille]]
|Fire Brandy
|12
|Lowers Attack and Defence. Blurs vision.
|{{Map|2548,3083|2548,3077|2558,3077|2558,3083|mtype=polygon|width=200|height=200}}
|-
|[[Flying Horse Inn]]
|[[Ardougne]] (north of Ardougne Castle)
|Heart Stopper
|8
|Lowers health by about 20-30% of your total. Makes your eyes water and causes chest pain.
|{{Map|2572,3327|2572,3318|2578,3318|2578,3327|mtype=polygon|width=200|height=200}}
|-
|[[Forester's Arms]]
|[[Seers' Village]] (between the pillory and the anvil room)
|Liverbane Ale
|18
|Lowers [[Attack]], [[Defence]], [[Fletching]], [[Firemaking]], and [[Woodcutting]]. Causes dizziness.
|{{Map|2689,3499|2689,3488|2701,3488|2701,3499|mtype=polygon|width=200|height=200}}
|-
|[[Jolly Boar Inn]]
|[[Varrock]] (next to the [[Lumber Yard]])
|Olde Suspiciouse
|10
|Lowers [[Attack]], [[Defence]], [[Mining]], [[Crafting]], and [[Magic]]. Makes your head spin.
|{{Map|3272,3511|3272,3486|3289,3486|3289,3511|mtype=polygon|width=200|height=200}}
|-
|[[Karamja Wines, Spirits, and Beers|Karamja Spirits Bar]]
|[[Musa Point]]
|Ape Bite Liqueur
|7
|
|{{Map|2918,3148|2918,3142|2931,3142|2931,3148|mtype=polygon|width=200|height=200}}
|-
|[[Rising Sun Inn|Rising Sun]]
|[[Falador]]
|Hand of Death Cocktail
|70
|Lowers [[Attack]], [[Defence]], [[Ranged]], and [[Fishing]]. Lowers health. Makes the screen shake slightly for between 2–5 seconds.
|{{Map|2953,3379|2953,3366|2962,3366|2962,3379|mtype=polygon|width=200|height=200}}
|-
|[[Rusty Anchor Inn|Rusty Anchor]]
|[[Port Sarim]]
|Black Skull Ale
|8
|Blurs vision. Causes hiccups.
|{{Map|3044,3260|3044,3255|3056,3255|3056,3260|mtype=polygon|width=200|height=200}}
|}
"""

[[steps]]
index = 2
name = "Possible routes"
links = ["Forester's Arms", "Seers' Village", "Blurberry Bar", "Tree Gnome Village", "spirit tree", "Tree Gnome Stronghold", "Amulet of glory", "Ring of dueling", "Al Kharid", "gnome glider", "The Grand Tree", "Grand seed pod", "skills necklace", "Grand Tree", "Blurberry", "Jolly Boar Inn", "Lumberyard teleport", "Digsite pendant", "Digsite Teleport", "shortcut", "Wilderness", "Balloon transport system", "Castle Wars", "Willow logs", "Blue Moon Inn", "Varrock teleport", "Chronicle", "Flying Horse Inn", "Rat Pits", "Ardougne", "Jimmy Dazzler", "Captain Barnaby", "Rimmington", "Khazard battlefield", "Dragon Inn", "Watchtower Teleport", "Teleport to House", "Yanille", "Rising Sun Inn", "The Rusty Anchor", "Explorer's ring 2", "amulet of glory", "Draynor Village", "Port Sarim", "Pest Control", "minigame teleport", "POH", "Karamja Wines, Spirits, and Beers", "Musa Point", "Dead Man's Chest", "charter ship", "Brimhaven", "Barbarian Outpost"]
text = """
{{Checklist|
*The [[Forester's Arms]] - Teleport to Camelot and head west to [[Seers' Village]].
*The [[Blurberry Bar]] -  If [[Tree Gnome Village]] has been completed, teleport to Grand Exchange and use the [[spirit tree]] to teleport directly to the [[Tree Gnome Stronghold]]. Alternatively, the [[Amulet of glory]] or the [[Ring of dueling#Teleportation_options|Al Kharid PvP Arena teleport]] can be used to teleport to [[Al Kharid]] and then a [[gnome glider]] can be used to get to the [[Tree Gnome Stronghold]] after completing [[The Grand Tree]] quest. It's also possible to use a [[Grand seed pod]] - note that this is not recommended due to the price of the pod. Alternatively, you can use a [[skills necklace|Fishing guild teleport]] and run West. After reaching the Tree Gnome Stronghold, go to the {{FloorNumber|uk=1}} of the [[Grand Tree]], and get the drink from [[Blurberry]] at the [[Blurberry Bar]].
*The [[Jolly Boar Inn]] - A [[Lumberyard teleport]] is the quickest way. If the [[gnome glider]]s can be used, you can take the glider to Varrock and walk north-west. Alternatively, you can use a [[Digsite pendant]] or [[Digsite Teleport]] and walk north-west. You can also teleport to Varrock, head east outside of the city, and then straight north to the bar. If using the spirit trees, teleport back to the Grand Exchange and either use the north-west agility [[shortcut]] (21 Agility required) and run east along the [[Wilderness]] border. With {{SCP|Firemaking|50}} and access to the [[Balloon transport system]], you could alternatively teleport to [[Castle Wars]] and pay [[Willow logs]] to get to the Lumber Yard.
*The [[Blue Moon Inn]] - Use a [[Varrock teleport]], the [[Chronicle]] or walk back to the southern end of Varrock.
*The [[Flying Horse Inn]] -  The [[Rat Pits]] of [[Ardougne]] (run by [[Jimmy Dazzler]]) are next to the pub - if possible, you can teleport using the minigame teleport. Alternatively, use a [[skills necklace]] to teleport to the Fishing Guild, Teleport to [[Ardougne]], take [[Captain Barnaby]]'s boat from [[Rimmington]] or use the spirit tree in the Gnome Stronghold to teleport to the [[Khazard battlefield]], and then proceed to the north-western part of East Ardougne.
* The [[Dragon Inn]] - Use a [[Watchtower Teleport]], [[Teleport to House|teleport to house]] in Yanille, teleport to Castle Wars, use fairy ring code {{fairycode|ciq}}, or the minigame teleport to the Nightmare Zone and walk south-west from there to [[Yanille]]. The bar is at the south-western part of the city.
*The [[Rising Sun Inn]] - Teleport to Falador. The bar is south-west of the teleport spot.
*[[The Rusty Anchor]] - Use an [[Explorer's ring 2]] or higher variant to teleport to the Falador farm cabbage patch and run south to The Rusty Anchor, use an [[amulet of glory]] to teleport to [[Draynor Village]] and walk west to Port Sarim, use the [[Rat Pits]] minigame teleport to get to [[Port Sarim]], use the [[Pest Control]] [[minigame teleport]] and run north and travel with the squire to get to Port Sarim, if your [[POH|house]] is in [[Rimmington]], teleport to house and run east to [[Port Sarim]], or simply walk south from Falador to Port Sarim and proceed to the most north-eastern building in Port Sarim.
*The [[Karamja Wines, Spirits, and Beers|Karamja Spirits Bar]]  -  Take a ship to [[Musa Point]] from Port Sarim or glory teleport to Karamja.
*[[Dead Man's Chest]] - Take a [[charter ship]] to [[Brimhaven]], or take [[Captain Barnaby]]'s boat from [[Rimmington]], or go to Musa Point and walk past the volcano.
*Return to the [[Barbarian Outpost]], preferably by using a games necklace.
}}
"""

[[steps]]
index = 3
name = "=Alternative routes="
links = []
text = """

"""

[[steps]]
index = 4
name = "==Low magic/few teleports=="
links = ["Tree Gnome Stronghold", "Grand Tree", "Blurberry Bar", "Flying Horse Inn", "Yanille", "Blue Moon Inn", "Jolly Boar Inn", "Lumber Yard", "Rising Sun Inn", "Port Sarim", "the Rusty Anchor", "Musa Point", "Karamja Wines, Spirits, and Beers", "charter ship", "Brimhaven", "Dead Man's Chest", "Seers' Village", "Forester's Arms", "Barbarian Outpost"]
text = """
{{Checklist|
*Run to the [[Tree Gnome Stronghold]], go to the {{FloorNumber|uk=1}} of the [[Grand Tree]], and get the drink from [[Blurberry Bar]].
*Go to Ardougne, then proceed to the [[Flying Horse Inn]], located in the western side of East Ardougne.
*Travel south to [[Yanille]]. Buy a drink from the bar at the south-western part of the city.
*Go to Varrock and visit the [[Blue Moon Inn]].
*Proceed north-east in Varrock to the [[Jolly Boar Inn]]. It is just west of the [[Lumber Yard]].
*Go to Falador and then go to the [[Rising Sun Inn]].
*Walk to [[Port Sarim]], and proceed to [[the Rusty Anchor]].
*Take the ship to [[Musa Point]] and visit the [[Karamja Wines, Spirits, and Beers|Karamja Spirits Bar]].
*Take the [[charter ship]] to [[Brimhaven]], or simply run west over the volcano, getting the drink from the [[Dead Man's Chest]].
*Now take the charter ship for 480 coins to Catherby then go to [[Seers' Village]], and then visit the [[Forester's Arms]].
*Return to the [[Barbarian Outpost]], preferably by using a games necklace.
}}
"""

[[steps]]
index = 5
name = "==Low cost/low magic/shortest walking distances=="
links = ["games necklace", "Dramen staff", "Balloon transport system", "Falador", "Varrock", "Seers' Village", "Forester's Arms", "Yanille", "spirit tree", "Tree Gnome Stronghold", "Grand Tree", "Blurberry Bar", "Khazard Battlefield", "Flying Horse Inn", "Brimhaven", "Dead Man's Chest", "Musa Point", "Karamja Wines, Spirits, and Beers", "Port Sarim", "the Rusty Anchor", "Rising Sun Inn", "balloon transport system", "Jolly Boar Inn", "Blue Moon Inn", "Barbarian Outpost"]
text = """
Required:
*Extra coins for transportation
*A [[games necklace]]
*A [[Dramen staff]] or better for Fairy Ring teleportation
*Unlocked [[Balloon transport system]] to [[Falador]] and [[Varrock]]

{{Checklist|
* Start in [[Seers' Village]] (walk or teleport there), and visit the [[Forester's Arms]].
* Take the Sinclair Mansion fairy ring to [[Yanille]] ({{fairycode|ciq}}). Buy a drink from the bar at the south-western part of the city.
* Run back to the fairy ring, travel to the Grand Exchange ({{fairycode|dkr}}) and climb the [[spirit tree]] to the [[Tree Gnome Stronghold]], go to the {{FloorNumber|uk=1}} of the [[Grand Tree]], and get the drink from [[Blurberry Bar]].
* Climb the spirit tree again to the [[Khazard Battlefield]] and run north to the [[Flying Horse Inn]], located in the western side of East Ardougne.
* Take the ship to [[Brimhaven]], getting the drink from the [[Dead Man's Chest]].
* Walk to [[Musa Point]] and visit the [[Karamja Wines, Spirits, and Beers|Karamja Spirits Bar]].
* Take the ship to [[Port Sarim]], and proceed to [[the Rusty Anchor]].
* Run north (or teleport) to Falador and then go to the [[Rising Sun Inn]]. This is probably the longest distance to run after Seers' Village, you can consider to teleport.
* Run south (by first taking the Crumbling Wall on the West, or going underneath in the south) and take the [[balloon transport system|balloon]] to [[Varrock]] and walk to the [[Jolly Boar Inn]].
* Run south and visit the [[Blue Moon Inn]].
* Return to the [[Barbarian Outpost]], preferably by using a [[games necklace]].
}}
"""

[[steps]]
index = 6
name = "==Utilising gnomes' transportation=="
links = ["spirit tree", "gnome glider", "Ardougne cloak", "Tree Gnome Stronghold", "Grand Tree", "Blurberry Bar", "Lemanto Andra", "Jolly Boar Inn", "Blue Moon Inn", "Varrock", "Grand Exchange", "Khazard Battlefield", "Flying Horse Inn", "charter ship", "Brimhaven", "Dead Man's Chest", "Karamja Wines, Spirits, and Beers", "Musa Point", "Pirate's Treasure", "Karamjan rum", "Port Sarim", "Rusty Anchor Inn", "Falador", "Rising Sun Inn", "Tree Gnome Village (location)", "Elkoy", "Yanille", "Dragon Inn", "Nightmare Zone", "Port Khazard", "Catherby", "Seers' Village", "Forester's Arms", "Barbarian Outpost", "games necklace", "Barbarian Assault"]
text = """
Required:
*Extra coins for transportation
*Access to [[spirit tree]]s and [[gnome glider]]s
*Easy access to a [[spirit tree]] (e.g. [[Ardougne cloak]])

{{Checklist|
* Start in the [[Tree Gnome Stronghold]] and go to the {{FloorNumber|uk=1}} of the [[Grand Tree]] to get the drink from [[Blurberry Bar]].
* Take the [[gnome glider]] to [[Lemanto Andra]] and walk north-west to the [[Jolly Boar Inn]].
* Walk around to the [[Blue Moon Inn]] in South [[Varrock]].
* Take the spirit tree from the [[Grand Exchange]] to [[Khazard Battlefield]] to the [[Flying Horse Inn]].
* Take the [[charter ship]] to [[Brimhaven]] and get wasted at the [[Dead Man's Chest]].
* Run east to the [[Karamja Wines, Spirits, and Beers|Karamja Spirits Bar]] at [[Musa Point]].
** If you haven't done [[Pirate's Treasure]] yet, now's a good time to smuggle your [[Karamjan rum]] over.
* Take the ship to [[Port Sarim]] and go north to the [[Rusty Anchor Inn]].
* From then, go north into [[Falador]] and visit the [[Rising Sun Inn]].
* Take a spirit tree to [[Tree Gnome Village (location)|Tree Gnome Village]] and leave the maze via [[Elkoy]]. Run south and then east to get to [[Yanille]]'s [[Dragon Inn]].
** Players who have access to the [[Nightmare Zone]] can use the minigame teleport instead, and also pop in and out of a practice instance to restore run energy.
* Take the charter ship from [[Port Khazard]], a little north east of Yanille, to [[Catherby]], and run to [[Seers' Village]] to visit the [[Forester's Arms]].
* Return to the [[Barbarian Outpost]], either by running west, using a [[games necklace]], or taking the minigame teleport to [[Barbarian Assault]].
}}
"""
