quest = "Sea Slug"
step_count = 3

[[steps]]
index = 0
name = "The Fishing Platform"
links = ["Ardougne Diary", "Caroline", "Witchaven", "Ardougne", "Kent", "Kennith", "Fishing Platform", "Holgart", "swamp paste"]
text = """
{{Needed|swamp paste|recommended=small fishing net for a medium [[Ardougne Diary]] task}}
[[File:Caroline chathead.png|left|frameless]]
[[File:Sea Slug - Patching up the boat.png|thumb|200px|Starting the quest.]]
Talk to [[Caroline]] on the coast north of the town of [[Witchaven]], east of [[Ardougne]]. She will tell you her husband [[Kent]] took her son [[Kennith]] to the [[Fishing Platform]] a week ago, and she hasn't heard from them since; other families have not heard from the fishermen there either. She wants you to talk to [[Holgart]], who has a boat that can take you to the platform to investigate.

Talk to [[Holgart]], and he will tell you his ship is in need of repairs. He will ask for [[swamp paste]] ('''not swamp tar''') to fix it up. Once you give him it, Holgart will appear in a cut scene fixing the boat. Talk to him again to go to the Fishing Platform.
"""

[[steps]]
index = 1
name = "Investigate"
links = ["sea slug (race)", "small fishing net", "Ardougne Diary", "Bailey", "broken glass"]
text = """
[[File:Bailey chathead.png|left|frameless]]
[[File:Sea Slug - Speaking with bailey.png|thumb|200px|Talking to Bailey.]]
When you arrive, you will notice the odd behaviour of everyone as they all seem to be in a zombie-like trance. Avoid interacting with the [[sea slug (race)|sea slug]]s; they will deal 3 damage if picked up.

'''Note:''' If you brought a [[small fishing net]], you can catch a fish here to complete a task for the medium [[Ardougne Diary]].

Look around and find [[Bailey]] inside a small room in the south-west corner of the platform. Talk to him, he will tell you about the odd happenings and the hauling up of the sea slugs. Pick up the [[broken glass]] on the floor for later in the quest.
"""

[[steps]]
index = 2
name = "Helping Kennith"
links = ["dry sticks", "unlit torch", "damp sticks", "Kennith", "Kent", "Holgart", "Bailey", "broken glass", "Dry sticks", "badly repaired wall", "crane (Sea Slug)", "Caroline"]
text = """
{{Needed|skills={{SCP|Firemaking|30}} to use [[dry sticks]] to light the [[unlit torch]]}}
[[File:Sea Slug - Drying damp sticks.png|thumb|left|130px|Using the glass to dry the sticks.]]
[[File:Sea Slug - Rescuing Kennith.png|thumb|200px|Using the crane to save Kennith.]]
Pick up some [[damp sticks]] close to the ladder in the north-east corner of the platform, then climb up the ladder. Upstairs, in a room on the west side, past the crane, you will find [[Kennith]]. He will tell you that his father tried to leave days ago, but the fishermen stopped him from doing so. He will ask you to find his father, [[Kent]] and help him.

Go back to [[Holgart]] and talk to him. He will take you to a deserted island, where you will find Kennith's father stranded. Talk to Kent and he will tell you his story. Then ask Holgart to take you back to the platform. Talk to [[Bailey]] to find out the slugs' weakness - they are afraid of heat. He will give you an [[unlit torch]], which he cannot light himself as it is too damp. Use the [[broken glass]] on the [[damp sticks]], which are found near the ladder to [[Dry sticks|dry them]], then rub them together to '''light the torch''' ({{SCP|Firemaking|30}}). If you do not light it now, you will be damaged by a fisherman when going upstairs.

Climb up the ladder again (on the north-east of the platform), go into the room, and talk to [[Kennith]]. From outside the room, kick the [[badly repaired wall]] to make an opening, then use your lit torch on any fisherman or sea slugs nearby and then talk to Kennith again. Rotate the [[crane (Sea Slug)|crane]] to save him, shown in a cut scene. Talk to [[Holgart]] to return to shore. Finish the quest by talking to [[Caroline]].

'''Congratulations, quest complete!'''
"""
