quest = "Mountain Daughter"
step_count = 7

[[steps]]
index = 0
name = "Mountain Camp"
links = ["rope", "plank", "staff", "Camelot Teleport", "Rellekka", "Golden Apple Tree", "enchanted lyre", "Seers' Village", "Fairy rings", "Player-owned house", "Mountain Camp"]
text = """
{{Needed|[[rope]], [[plank]]|recommended=[[staff]], [[Camelot Teleport]]}}
{{Map|group=camp|align=right|x=2787|y=3685|caption=
{{Mapkey|col=2
|line1=diamond...#FF00FF,text=Ragnar
|line2=diamond...#FFA500,text=Jokul
|line3=polygon...#F0FF00,text=Mud
|line4=polygon...blue,text=Cave
|line5=dot...red,text=Ancient rock
|line6=dot...#00FF00,text=Pole
|line7=dot...#7777FF,text=Muddy rocks
}}
|mtype:square,r:3,stroke:#0000FF,fill-opacity:0.5,2810:3705,desc:cave
|mtype:circle,r:0.8,fill-opacity:1,2812:3680,2812:3687,2809:3679,2804:3660,desc:rocks
|mtype:circle,r:1.5,stroke:#FF0000,fill-opacity:1,fill:#FF0000,2799.5:3660,desc:Ancient rock
|mtype:square,r:3,stroke:#F0FF00,r:3,fill-opacity:0.2,fill:#F0FF00,2809:3662,desc:MUD
|mtype:circle,r:0.8,stroke:#00FF00,fill-opacity:1,fill:#00FF00,2813:3685,desc:pole
|mtype:polygon,stroke:#FFA500,fill:#FFA500,fill-opacity:1,2809.5:3683.5,2808:3681.75,2809.5:3680,2811:3681.75,desc:Jokul
|mtype:polygon,stroke:#FF00FF,fill:#FF00FF,fill-opacity:1,2766:3677,2764.5:3675.25,2766:3673.5,2767.5:3675.25,desc:Ragnar
}}

Make your way to the Mountain Camp east of [[Rellekka]] and north-east of the [[Golden Apple Tree]]. To get to that area, you can use the [[enchanted lyre]] and head east; walk north from [[Seers' Village]] or use the [[Fairy rings|fairy ring]] code {{Fairycode|ajr}} and then go north a bit; or if your house is in Rellekka, teleport to your [[Player-owned house|house]] and go east, or by using Fremennik sea boots head east.

[[File:Mountain Daughter - Entering the mountain camp.png|thumb|left|A player using a rope to climb down the cliffside.]]
Start up the path to the [[Mountain Camp]], then head north up the slope above the guard. Use your [[rope]] on the boulder that says "push boulder" and you will automatically climb down.

{{clear}}
"""

[[steps]]
index = 1
name = "Hamal's daughter"
links = ["Hamal the Chieftain", "Rellekka", "Fremennik", "mud", "swamp paste", "Jokul", "pole"]
text = """
[[File:Hamal the Chieftain chathead.png|left]]
Follow the path into the village, enter the longhouse to the east, and speak to [[Hamal the Chieftain]] by asking, ''"Why is everyone so hostile?"'', to begin the quest. Speaking of his tribe, Hamal tells you that they are citizens of [[Rellekka]], although due to differences they have moved out to become closer to nature, disagreeing with the [[Fremennik]] tradition of choosing their tools over skill. The chieftain tells you about his missing daughter and after much arguing against "employing" an outerlander, he eventually allows you to search for her. From this point on, you can enter the camp by climbing over the rockslide.

Head south of Hamal's house, and take some [[mud]] from the roots along the edge of the bubbling mud pond ([[swamp paste]] also works, but the mud can be obtained during the quest).

If you did not bring a staff, go north of Hamal's house to [[Jokul]]'s place and pick up the [[pole]].
"""

[[steps]]
index = 2
name = "Crisis"
links = ["mountain goat", "Shining pool", "mud", "swamp paste", "pole", "staff", "plank", "Shining pool (scenery)", "Dramen staff", "Asleif Hamalsdotter", "Rellekka", "Mountain Camp"]
text = """
[[File:Mountain Daughter - Climbing the tree.png|thumb|Climbing the tall tree to gain access to the island.]]
Just north of Hamal's tent are [[mountain goat]]s. Follow the path leading west along the [[Shining pool]]. Follow it until you reach a tall tree by the geysers above the path you came up.

#Use the [[mud]] (or [[swamp paste]]) you gathered on the tall tree to prevent yourself from slipping.
# Climb the tall tree, crawl along its branch, and jump down to the little island.
#Use your [[pole]] or [[staff]] on the clump of rocks to pole-vault over them.
# Then use the [[plank]] to cross the flat stone.
#On one of the [[Shining pool (scenery)|bubbles]] rising from the pool, select "Listen-to Shining pool".

: '''Note:''' The [[Dramen staff]] can no longer be used as a pole vault as it was changed from a staff to a blunt weapon.<ref>Update: [[Update:QoL and Treasure Trails Feedback Changes|QoL and Treasure Trails Feedback Changes]] - April 18 2019</ref>

You hear the voice of the spirit of the chieftain's daughter [[Asleif Hamalsdotter]], who is dead. She asks you to make peace between her tribe and [[Rellekka]] and to also find a new food source for the camp. Agree to help her. To return to shore, use a plank on the flat stone. You can do her two tasks in either order.
:'''Note:''' Both tasks can be started at the same time. This reduces going back to the [[Mountain Camp]] multiple times. Plan it out accordingly.
"""

[[steps]]
index = 3
name = "Making peace"
links = ["pickaxe", "Mountain Camp", "Hamal the Chieftain", "Rellekka", "Svidi", "Fremennik", "Brundt the Chieftain", "Ancient Rock", "half a rock", "safety guarantee", "Fremennik Diary", "The Fremennik Trials"]
text = """
{{Needed|A [[pickaxe]]}}

{{Map|name=Svidi|align=right|width=250|height=250|caption=Svidi's roaming area.|zoom=1|x=2724|y=3675|mtype=square|r=10}}
Return to the [[Mountain Camp]], and talk to [[Hamal the Chieftain]]. Ask about the people of [[Rellekka]], and he tells you that he sent a villager named [[Svidi]] to initiate a simple trade route, but he hasn't yet returned. Head to the rockslide that first blocked your entrance to the Mountain Camp. Climb over it, and go into the forest north-west of the rockslide, outside the entrance to Keldagrim. Locate and speak with Svidi. To find Svidi, go to the black unicorns and look for a fast moving yellow dot on your mini map between the fence shortcut and the south fence turn. you must run to catch him once spotted.
:'''Note:''' Make sure to choose the option "Can't I persuade you to go in there somehow?", as the other option will cause him to walk off and you will have to find him again.

He will tell you he's afraid of the [[Fremennik]] in Rellekka and thinks that they might kill him. Offer to help him enter Rellekka and he agrees if you can secure a promise from the chieftain that he will be safe.

Head to Rellekka, and talk to [[Brundt the Chieftain]] in the longhall. He will promise not to hurt Svidi if you can retrieve a relic - an [[Ancient Rock|ancient rock]] - that the Mountain Camp tribe stole from Rellekka long ago.

[[File:Mountain Daughter - Mining the ancient rock.png|thumb|A player mining the Ancient Rock.]]
Return to the Mountain Camp, and enter the large tent south-west of Hamal the Chieftain. If you want, you can first talk to Hamal, but he refuses to let you have the rock. ''Right-click'' to use your [[pickaxe]] on the Ancient rock located in the southern tent to acquire [[half a rock]]. If you're wielding your [[pickaxe]], you will have to ''right-click on the'' ancient rock, as it cannot be mined using ''left-click''. Take this back to Rellekka, and talk to Brundt the Chieftain, who will agree to share the rock and give you a [[safety guarantee]] granting Svidi safe passage. Take the guarantee to Svidi to initiate peace talks between the two tribes.

'''Note:''' Once back in Rellekka with your pickaxe, now may be a good time to run north to the mine and gather some coal for the [[Fremennik Diary]] task.  Players will need to have completed [[The Fremennik Trials]] to enter the mine.
"""

[[steps]]
index = 4
name = "Finding food"
links = ["gloves", "ring of dueling", "Royal seed pod", "Gnome glider", "Camelot Teleport", "Mountain Camp", "Hamal the Chieftain", "Jokul", "mountain goat", "White pearl", "gnome glider", "White Wolf Mountain", "thorny bushes", "The Grand Tree", "quest", "Emir's Arena", "White pearl seed"]
text = """
{{Needed|A pair of [[gloves]]|recommended=A [[ring of dueling]] or [[Royal seed pod]] for [[Gnome glider]], or a [[Camelot Teleport]]}}

Return again to the [[Mountain Camp]] and speak with [[Hamal the Chieftain|Hamal]], and then talk to [[Jokul]], who is in the tent north of Hamal, looking after his [[mountain goat]]s. He will tell you that he thinks the members of the Mountain Camp could survive if the seed of a [[White pearl]] fruit, a hardy plant which can grow anywhere, were planted in the area.

:'''''Note:''' You must have talked to Jokul before being able to pick the fruit.''

[[File:Mountain Daughter - The thornbush.png|thumb|left|A thorny bush, just south of the [[gnome glider]] on the peak of [[White Wolf Mountain]].]]
Travel to the peak of [[White Wolf Mountain]] and look for [[thorny bushes]] near the [[gnome glider]]. If you have completed [[The Grand Tree]] [[quest]], you may use a [[ring of dueling]] to teleport to the [[Emir's Arena]] which is near a gnome glider. Head west from the Emir's Arena to the glider, then fly to the mountains. Alternatively, you may use a Camelot Teleport and walk up the mountain. Put on your [[gloves]] (4 damage will be inflicted if not wearing any, and you won't get the fruit seed), pick a [[White pearl]] fruit off the thorny bushes and eat it. You will automatically spit out the [[White pearl seed]].

Go back to the Mountain Camp and give the White pearl seed to Hamal the Chieftain, who accepts your solution for feeding the tribe.
"""

[[steps]]
index = 5
name = "The Kendal"
links = ["Asleif Hamalsdotter", "plank", "the Kendal", "Kendal's Lair", "Dead tree (Mountain Daughter)", "axe", "Cave entrance (The Kendal's Lair)", "hitpoints", "combat level", "Protect from Melee", "Prayer", "Ranged", "Magic", "safespot", "Bearhead", "inventory", "corpse of woman", "Hamal the Chieftain"]
text = """
{{Needed|An axe, combat equipment, a staff (or pole found near Jokul), and a plank}}

After you've completed both tasks, go back to the shining pool and speak to [[Asleif Hamalsdotter|Asleif]] again (make sure to pole vault, and use your [[plank]] on the flat stone). She asks you to convince her father that she is really dead. She was attacked by a creature ([[the Kendal]]) and dragged off nearby to the north where she was killed. Leave the island and head to the north side of the pool (alternatively, cross the gap without using the plank; you'll end up on the north side). Follow the path east to a [[Kendal's Lair|cave]] blocked by [[Dead tree (Mountain Daughter)|dead trees]]. Chop down the ones that block your path with an [[axe]] until you reach a [[Cave entrance (The Kendal's Lair)|cave entrance]] (if you face problems chopping down the trees, stand to the west side of the first tree when chopping it down to walk over the stump).

Enter the cave and make your way to the large cavern. You find the Kendal as well as numerous corpses near a central pillar. Talk to the Kendal, and when it asks who you are, say, "It's just me, no one special", and then "You mean a sacrifice?". The Kendal tells you that it is the god of the northern lands.

Say that he actually looks like a man in a bearsuit, to which he finally admits. After you blow his cover, he also confesses to killing Asleif more than ten years ago. Humbly request her remains, to which he refuses as he cannot let anyone know his true identity. Threaten to kill him, and he'll attack you. He has 50 [[hitpoints]] and a [[combat level]] of 70, and all damage can be blocked if you use the [[Protect from Melee]] [[Prayer]]. If you are using [[Ranged]] or [[Magic]], you can find a [[safespot]] around the skeletons to attack him.

: '''Note:''' It is possible to defeat the Kendal with a Dwarf Multicannon. If safespotting, be careful though: after attacking the boss, another one will spawn. The cannon will hit him too, making him aggressive, and repeating the process multiple times.

Once he dies, a [[Bearhead]] mask will appear in your [[inventory]]. Take Asleif's corpse, which lies in the south-eastern corner of the pillars ([[corpse of woman]]), and exit the cave. Cut your way back out of the dead trees and head back to [[Hamal the Chieftain]]. Tell him what you learned and show him his daughter's corpse.

<gallery widths="200">
File:Mountain Daughter - Entering the Kendal's cave.png|The Kendal's Lair.
File:Kendal safespot.png|The safespot for the Kendal.
</gallery>
"""

[[steps]]
index = 6
name = "Finishing up"
links = ["Ragnar", "muddy rock", "Spawning", "Asleif's necklace", "burial cairn"]
text = """
[[File:Mountain Daughter - Creating the burial.png|thumb|A player creating the burial cairn for Asleif.]]
{{Needed|5 muddy rocks, a staff (or pole found by Jokul), and a plank}}

Hamal asks you to give her a proper burial by building a grave on the island at the centre of the pool topped with a cairn, symbolising the longboats used to cross the seas, and some of her possessions. He tells you perhaps [[Ragnar]] has one of her possessions for you to use. On your way up, gather five [[muddy rock]]s from the mountain goat pen. The rocks [[Spawning|respawn]] quickly, so it's possible just to pick up the same rock multiple times.

Follow the path up to Ragnar (he is just past the tall tree), and speak with him. He gives you [[Asleif's necklace]], which he had intended to give her as a gift. Climb up the tall tree, pole-vault the clump of rocks, and use the plank on the flat stones to make your way back to the small island. Bury the corpse there; you will  go to the designated burial location. Use the muddy rocks on the burial mound to create Asleif's [[burial cairn]].

'''Congratulations, quest complete!'''
"""
