quest = "Pandemonium"
step_count = 3

[[steps]]
index = 0
name = "Job interview"
links = ["Will", "Anne", "Food Store", "Port Sarim", "Bay of Sarim", "Ship Yard", "wreck", "Salvaging hook (Pandemonium quest)", "mysterious medallion", "old cup"]
text = """
[[File:Pandemonium - Push.webm|thumb|width=250x250|Anne pushing you off the boat.]]
To begin the quest, talk to either [[Will]] or [[Anne]] on the dock immediately east of the [[Food Store]] in [[Port Sarim]]. They will eagerly offer you a role within their new salvaging business. When ready, you will be taken aboard their boat, and the pair will reveal that they want to collect some salvage from an old pirate wreck. They will put you in charge of steering the ship; after clicking the helm to control the ship, use the minimap to navigate south, through the [[Bay of Sarim]], to the wreck east of the [[Ship Yard|Karamja Shipyard]].

{{Map|align=left|name=Pirate wreck|x=3031|y=3035|r=3|mtype=square|caption=Pirate wreck location, east of Karamja Shipyard.|width=220|height=220}}

Upon arriving at the [[wreck]], Anne will ask you to lower the salvaging hook. After deploying the [[Salvaging hook (Pandemonium quest)|salvaging hook]], you'll retrieve a [[mysterious medallion]] and an [[old cup]]. Will, recognising the medallion, will take it and leave you with the cup. Anne will then shove you overboard.
"""

[[steps]]
index = 1
name = "Pandemonium!"
links = ["The Pandemonium", "'Squawking' Steve Beanie", "Ribs_(The_Pandemonium)", "The Pandemonium (Pub)"]
text = """
[[File:The Pandemonium.png|thumb|right|250x250px|The Pandemonium docks.]]
You'll wash up at [[The Pandemonium]]. Speak to [['Squawking' Steve Beanie]], who will recognise Anne and Will as thieves that stole a map to the wreck, breaking the one rule of the Pandemonium. He'll point you towards [[Ribs_(The_Pandemonium)|Ribs]], the map's original owner.

Talk to [[Ribs_(The_Pandemonium)|Ribs]] in the [[The Pandemonium (Pub)|pub]], and he'll share the tale of Crimson Kraken, a deadly vessel captained by the cruel and vicious pirate Barnacle Barnaby. He'll claim that now that Barnaby's medallion has been found, a curse has been unleashed, and will ask you to talk to Steve Beanie again to find Will and Anne. Talk to Steve again, and he'll mention Old Grog, who might be interested in tracking them down. In the meantime, you'll need to acquire your own boat.
"""

[[steps]]
index = 2
name = "Collecting cargo"
links = ["Junior Jim", "hammer", "saw", "facilities", "Captain's log", "shipyard", "Port Sarim", "Buoy (Sailing)", "ledger table", "Old Grog"]
text = """
Head east out of the pub, and talk to [[Junior Jim]] on the second docked ship. After giving him the old cup in exchange for a raft, he'll inform you that you need to pick up cargo to get sails for the boat. He'll then take you to the shipyard, where you'll learn how to customize your boat (or in this case, raft).

Pick up a [[hammer]] and [[saw]] from the two open crates to the south, then board the gangplank. On your raft, build a cargo hold in the [[facilities]] hotspot, then use the gangplank to disembark your raft and return to Junior Jim. After giving you a [[Captain's log]], he'll ask you to head over to Port Sarim to collect the cargo.

Use the gangplank to the north east to board your raft, then use the helm to navigate and travel north past the [[shipyard]] to [[Port Sarim]]. Use the [[Buoy (Sailing)|buoy]] just south of the southernmost dock to dock your raft, then use the gangplank to the north to disembark. Take cargo from the [[ledger table]] at the western end of the dock. '''You must unequip weapons before carrying cargo.''' Return to the gangplank to board your raft, then open the basic cargo hold to deposit your cargo.

Navigate south back to the docks of The Pandemonium, parking within the perimeter of the buoys. Open the basic cargo hold and withdraw the crate, then use the gangplank to the north west to disembark. Deposit the cargo on the ledger table at the western end of the dock, and talk to Junior Jim to let him know you delivered his cargo. Finally, talk to Steve Beanie in the pub for an update on Will and Anne, and he'll introduce you to [[Old Grog]], who'll agree to help track them down.

'''Congratulations, quest complete!'''
"""
