quest = "Rune Mysteries"
step_count = 1

[[steps]]
index = 0
name = "Main"
links = ["Duke Horacio", "Lumbridge Castle", "air talisman", "Wizards' Tower", "Air talisman", "drop trick", "Money making guide/Collecting air talismans", "Draynor Village", "Archmage Sedridor", "research package", "Aubury", "Varrock", "Varrock east bank", "Aubury's Rune Shop", "Notes (Rune Mysteries)", "energy", "Runecraft"]
text = """
[[File:Duke Horacio chathead.png|left]]
Talk to [[Duke Horacio]] on the {{FloorNumber|uk=1}} of [[Lumbridge Castle]], and ask if he has any quests to give out. He will explain that although he himself has no tasks for the player, he did find a strange talisman. Curious about its origin, he will give you an [[air talisman]] and ask you to bring it to the arch mage of the [[Wizards' Tower]].

:'''Tip''': Multiple [[Air talisman|air talismans]] can be obtained by using the [[drop trick]] at [[Duke Horacio]]. This may be useful for early runecraft training methods. For details, see [[Money making guide/Collecting air talismans|this guide]].''

Go to the Wizards' Tower found south of [[Draynor Village]], and descend the ladder into the basement to talk to [[Archmage Sedridor]]. He will take your air talisman and give you a [[research package]] to deliver to [[Aubury]] in [[Varrock]].

Aubury is located south of [[Varrock east bank|Varrock's east bank]], inside of [[Aubury's Rune Shop|his rune shop]]. Talk to Aubury, and he will give you some [[Notes (Rune Mysteries)|notes]] to deliver back to Wizard Sedridor. He will also offer the player a cup of tea, which will completely restore [[energy|run energy]] if accepted.

Make your way back to the [[Wizards' Tower]], and talk to [[Archmage Sedridor]] once more. He will give you back your air talisman and explain the basics of [[Runecraft]].

'''Congratulations, quest complete!'''
"""
