quest = "Client of Kourend"
step_count = 1

[[steps]]
index = 0
name = "Main"
links = ["Veos", "Port Sarim", "Rusty Anchor Inn", "Great Kourend", "Port Piscarilius", "Kourend", "enchanted scroll", "feather", "enchanted quill", "Gerrant's Fishy Business", "Hosidius", "Shayzien", "Lovakengj", "Arceuus", "Regath", "Dark Altar", "Mysterious orb (Client of Kourend)", "broken glass", "Veos' Client"]
text = """
[[File:Client of Kourend - quest map.png|thumb|300x300px|Map showing locations visited during the quest:<br/>
'''1:''' Veos<br/>
'''2:''' Leenz<br/>
'''3:''' Regath<br/>
'''4:''' Munty<br/>
'''5:''' Jennifer<br/>
'''6:''' Horace<br/>
'''7:''' Dark Altar]]
[[File:Veos chathead.png|left]]
Speak to [[Veos]] at the northernmost dock of [[Port Sarim]] (near the [[Rusty Anchor Inn]]) to sail to [[Great Kourend]]. You will arrive in [[Port Piscarilius]], speak to [[Veos]] again and ask if he has any quests for you. He will say that he has a client from the mainland who is interested in some knowledge surrounding the cities of [[Kourend]], specifically its hierarchy and general social organisation. Agree to help him, and he will give you an [[enchanted scroll]], '''which you must use a [[feather]] on to create an [[enchanted quill]]'''. If you haven't got one already, a feather can be easily obtained from [[Gerrant's Fishy Business]] in [[Port Sarim]].

With the [[enchanted quill]] and [[enchanted scroll]] from Veos in your inventory, you will have to speak to the general store owners of Great Kourend. They can be found in buildings marked with the [[File:General store icon.png]] icon. You will need to travel to [[Hosidius]], [[Shayzien]], [[Lovakengj]], and [[Arceuus]] to visit these stores.

[[File:Enchanted Quill Damage.gif|thumb|upright|right|A player taking damage from the enchanted quill.]]

Speak to a store owner, and ask them about their respective city and what there is to do in their respective city. When you are receiving information from the [[Regath]], the [[Arceuus]] general store owner, the quill will mysteriously glow and damage your hand! You will not take any damage, however.

Once you've spoken to every single general store owner, a mysterious voice whispers to you that you must return to [[Veos]]. He will take your quill and scroll. You then tell [[Veos]] about your hand being damaged, and he says the client apologises, as the mention of the [[Dark Altar]] "provoked emotions".
[[File:Activate the Mysterious orb near the Dark Altar.png|thumb|left|220px|Activating the orb near the Dark Altar.]]
[[Veos]] will then ask you to take a [[Mysterious orb (Client of Kourend)|mysterious orb]] and activate it when near the [[Dark Altar]]. The Dark Altar is found north of [[Arceuus]] at the end of the area with purple crystals.
[[File:Client possessing Veos.gif|thumb|upright|right|Veos becomes possessed by his client.]]
Once you are near the [[Dark Altar]], activate the orb. It will shatter into [[broken glass]]. The mysterious voice will then whisper to you that you must return to [[Veos]] once more.

Return to [[Veos]] in [[Port Piscarilius]] (the quest cannot be completed by talking to him in [[Port Sarim]]). He will then claim that he has not spoken to you since taking you to [[Great Kourend]], and suddenly becomes possessed. [[Veos' Client]] will now speak, with the player questioning him to no avail. Before he releases [[Veos]] from his possession, he will give you your reward.

'''Congratulations, quest complete!'''
"""
