quest = "Imp Catcher"
step_count = 3

[[steps]]
index = 0
name = "Mizgog's little helper"
links = ["Wizards' Tower", "Draynor Village", "Wizard Mizgog", "Wizard Grayzag", "imp", "black bead", "yellow bead", "red bead", "white bead"]
text = """
Make your way to the [[Wizards' Tower]], south of [[Draynor Village]] and over a long stone bridge. Climb the stairs, and go up to the {{FloorNumber|uk=2}}. Talk to [[Wizard Mizgog]] and ask him questions to find out that he needs your help. He will tell you that [[Wizard Grayzag]]'s [[imp]]s have stolen his beads and he wants you to get them back for him. He needs you to collect:
*A [[black bead]] - {{Coins|{{GEP|Black bead}}}}
*A [[yellow bead]] - {{Coins|{{GEP|Yellow bead}}}}
*A [[red bead]] - {{Coins|{{GEP|Red bead}}}}
*A [[white bead]] - {{Coins|{{GEP|White bead}}}}

''Note: You can collect the beads in advance without starting the quest to save additional trips to the Wizards' Tower.
"""

[[steps]]
index = 1
name = "Obtaining beads"
links = ["imps", "Grand Exchange", "Gielinor", "Ardougne Monastery", "Karamja Volcano", "scorpion", "Falador", "Kastori", "Magic", "Ranged"]
text = """
Beads are only obtained as a 5/128 drop from [[imps]], buying them through the [[Grand Exchange]], or trading with other players. Because of the relatively low drop rate, many players may choose to buy beads on the [[Grand Exchange]] to avoid the hassle of killing imps (for a total cost of {{Coins|{{GEP|Red bead|1}} + {{GEP|Black bead|1}} + {{GEP|Yellow bead|1}} + {{GEP|White bead|1}}}}).

If looking to collect the beads as a drop, imps commonly spawn throughout [[Gielinor]], and you might consider collecting them passively over time when encountering them. Alternatively, you can use some of the following hotspots where many spawn at a time:
*East of the [[Ardougne Monastery]]
*On top of the [[Karamja Volcano]] (be aware of level 14 [[scorpion]]s in this area)
*Southern entrance to [[Falador]]
*In a basement in [[Kastori]]

Every 30–120 seconds there is a 25% chance for an imp to disappear into a puff of smoke and teleport a short distance away. Using [[Magic]] or [[Ranged]] is recommended to reduce downtime when killing them.
"""

[[steps]]
index = 2
name = "Finishing up"
links = []
text = """
Once you have all four beads, return to Wizard Mizgog and give them to him to finish the quest. He won't accept them one at a time, so Ultimate Ironmen should plan to get the whole thing done at once.

'''Congratulations, quest complete!'''
"""
