quest = "Jungle Potion"
step_count = 6

[[steps]]
index = 0
name = "An abandoned village"
links = ["Tai Bwo Wannai", "Brimhaven", "Karamja", "Trufitus", "herb", "potions"]
text = """
[[File:Trufitus chathead.png|left|frameless]]
Head to the small village of [[Tai Bwo Wannai]], located south of [[Brimhaven]] on [[Karamja]]. Talk to [[Trufitus]], found in a small house north-east of the main village area, and ask him where everyone is. He will explain they are afraid to stay in the village. Ask him how you can help, and he will ask for several [[herb]]s to mix a [[potions|potion]] to commune with the Gods, in order to see what fate befalls them.

:'''Note:''' You cannot collect all of the herbs at once. You will need to go back to talk with Trufitus each time.
{{Clear|left}}
<gallery mode="packed" widths="180px" heights="180px">
Jungle Potion - Snake weed.png | Location of the snake weed.
Jungle Potion - Ardrigal.png | Location of the ardrigal.
Jungle Potion - Sito foil.png | Location of the sito foil.
Jungle Potion - Valencia moss.png | Location of the Volencia moss.
Jungle Potion - Rogue's purse.png | Location of the Rogue's purse.
</gallery>
"""

[[steps]]
index = 1
name = "Snake Weed"
links = ["marshy jungle vine", "grimy snake weed", "Herblore", "Trufitus", "Legends' Quest", "Zogre Flesh Eaters"]
text = """
Head south-west of the village near the ocean to find [[marshy jungle vine]]. Search it to get a [[grimy snake weed]]; this may take 1-5 minutes depending on your [[Herblore]] level. Clean the herb and give it to [[Trufitus]].

:'''Note''': If you intend to do [[Legends' Quest]] and [[Zogre Flesh Eaters]], take two extra to save yourself time later.
"""

[[steps]]
index = 2
name = "Ardrigal"
links = ["Trufitus", "palm tree (Ardrigal)", "Shortcuts", "Harpie Bug Swarm", "grimy ardrigal", "Legends' Quest"]
text = """
Head north-east of [[Trufitus]]' hut until you reach a peninsula with several [[palm tree (Ardrigal)|palm trees]] on it, just south of the [[Shortcuts|agility shortcut]].

Avoiding the nearby level 46 [[Harpie Bug Swarm]]s, search a palm tree to find a [[grimy ardrigal]]. Clean the herb and give it to [[Trufitus]].

:'''Note:''' If you intend to do [[Legends' Quest]], take 2-3 extra to save yourself time later (3 are needed for the long path).
"""

[[steps]]
index = 3
name = "Sito Foil"
links = ["tribesmen", "scorched earth", "grimy sito foil", "Trufitus"]
text = """
{{Color|red|Warning:}} The [[tribesmen]] in this section are aggressive, and can poison you with damage starting at 11.

Immediately south of the village you will find [[scorched earth]]. Search it to find the [[grimy sito foil]]. Clean the herb and give it to [[Trufitus]].
"""

[[steps]]
index = 4
name = "Volencia Moss"
links = ["rock (volencia moss)", "grimy volencia moss", "Trufitus", "Fairytale I - Growing Pains"]
text = """
Head south-east of the hut until you reach a group of [[rock (volencia moss)|rocks]] you can search that are in the mining area, search an empty one to find the [[grimy volencia moss]]. Clean the herb and give it to [[Trufitus]].

:'''Note''': If you intend to do [[Fairytale I - Growing Pains]] take an extra to save yourself time later.
"""

[[steps]]
index = 5
name = "Rogue's Purse"
links = ["Jogre", "rocks (Pothole Dungeon)", "Karamja Diary", "jogre bones", "Tai Bwo Wannai Trio", "rogue's purse", "aggressive", "fungus covered cavern wall", "Zogre Flesh Eaters"]
text = """
{{Needed|recommended=Food for low levels to run aggressive level 53 Jogres, and combat equipment to kill a level 53 [[Jogre]] for an easy Diary task}}
[[File:Jogre.png|80px|left|frameless]]
[[File:Jungle Potion - Jogre Cave.png|thumb|right|220px|The Jogre cave entrance.]]
Head north-east of the village towards where you found the Ardrigal. Once you find the end of the cliffs, follow the coastline west until you find a [[rocks (Pothole Dungeon)|pile of searchable rocks]]. Search them and enter the cave.

:'''Note:''' You may kill a [[Jogre]] inside the dungeon for an easy [[Karamja Diary]] task. Take the [[jogre bones]] for [[ Tai Bwo Wannai Trio]]. Although they may drop the grimy [[rogue's purse]], they do not count for the quest.

Run south past the [[aggressive]] level 53 [[Jogre]]s until you find a [[fungus covered cavern wall]]. Search it until you find the grimy rogue's purse (may take some minutes).

:'''Note''': If you intend to do [[Zogre Flesh Eaters]], take an extra to save yourself time later.

Return to Trufitus with the final cleaned herb.

'''Congratulations, quest complete!'''
{{Clear}}
"""
