quest = "The Knight's Sword"
step_count = 5

[[steps]]
index = 0
name = "Sword trouble"
links = ["Squire", "White Knights' Castle", "Falador", "Sir Vyvin", "Reldo", "Varrock Palace", "The Giant Dwarf", "Thurgo", "Mudskipper Point", "Port Sarim"]
text = """
{{Map|name=Squire|x=2977|y=3342|r=3|mtype=square|align=right|caption=The location of Sir Vyvin's squire.|width=200|height=200}}
{{Needed|recommended=Fast travel method to Varrock and Mudskipper Point}}
[[File:Squire chathead.png|left|frameless]]
Talk to the [[Squire]], found in the courtyard of the [[White Knights' Castle]] in [[Falador]]. He has lost [[Sir Vyvin]]'s sword, a family heirloom made many generations ago by the Imcando dwarves. Offer to make a new one and he will mention that [[Reldo]] the [[Varrock Palace]] librarian may know where to find an Imcando dwarf.

'''Note''': If you have already completed [[The Giant Dwarf]], skip the following step and go straight to [[Thurgo]]; otherwise you must talk to Reldo before you may continue.

Talk to Reldo in the [[Varrock Palace]] library, the northernmost room on the ground floor. Ask him what he knows about Imcando dwarves, and he will point you towards [[Mudskipper Point]], just south of [[Port Sarim]].
{{Map|name=Thurgo|x=3001|y=3144|r=2|mtype=square|align=right|caption=The location of Thurgo, an Imcando dwarf.|width=200|height=200}}
"""

[[steps]]
index = 1
name = "Thurgo the Imcando dwarf"
links = ["Redberry pie", "Port Sarim", "Thurgo", "redberry pie"]
text = """
{{Needed|[[Redberry pie]]|recommended=Fast travel method to Falador}}
[[File:Thurgo chathead.png|left|frameless|80px]]
Head south of [[Port Sarim]] to find [[Thurgo]] on the west side of a hill, in his hut with the anvil. Ask him if he would like some [[redberry pie]], and he will take some and eat it. Ask if he can make a special sword, and he requests that you bring him a picture of the lost sword as a reference.
{{Clear|left}}
"""

[[steps]]
index = 2
name = "Acquiring the picture"
links = ["portrait", "White Knights' Castle", "Falador", "Cupboard (The Knight's Sword)"]
text = """
[[File:Portrait detail.png|left|100px|frameless]]
Return to the Squire in the Falador Castle courtyard again, and he will mention that a [[portrait]] of Sir Vyvin's father includes the sword.

'''Note:''' You must have spoken to the squire before you may obtain the portrait.

From the courtyard of the [[White Knights' Castle]] in [[Falador]], go east through three doors, and then up the ladder. Go west through the door and then further west through the open doorway, then up the stairs. Sir Vyvin's room will be directly to the south.

You need to obtain the portrait by searching the [[Cupboard (The Knight's Sword)|cupboard]] inside his room, but Sir Vyvin will stop you if he is inside the room and looking towards the player. Open the door to his room and wait for him to walk out, or hop worlds until you find one where he is outside the room, then take the portrait from the cupboard.
"""

[[steps]]
index = 3
name = "Mining the blurite"
links = ["pickaxe", "iron bar", "blurite ore", "Thurgo", "blurite sword", "Asgarnia Ice Dungeon", "aggressive", "skeletal wyvern", "safespot", "Falador Diary"]
text = """
{{Needed|A [[pickaxe]], the portrait, 2 [[iron bar]]s (4 if making extra sword)|recommended=Food and plate armour (slash resistant) for low levels, fast travel method to Mudskipper Point and Falador|skills={{SCP|Mining|10}} to mine [[blurite ore]]}}
[[File:Asgarnia_Ice_Dungeon_safespot.png|thumb|left|220px|Safespot by the cave entrance sign.]]
[[File:Asgarnian_Ice_Dungeon.png|thumb|right|240px|The Asgarnia Ice Dungeon.]]
Return to [[Thurgo]] and give him the portrait. He now knows a [[blurite sword]] is what he needs to make, and you must obtain the [[blurite ore]] for it. This ore is only found in the [[Asgarnia Ice Dungeon]], located on the hill to the north east. '''All enemies in the dungeon are [[aggressive]], so get ready to run past them'''. Head down the ladder on the hill, run north through the dungeon until you reach the pirates, then head east down the first corridor and enter the large icy room, which contains several bright blue rocks to mine for the ore. At the south-eastern end of the icy room, there is an entrance to the [[skeletal wyvern]]s section of the cave. Standing directly in front of this entrance is a [[safespot]], which you may wait in until it is safe to mine the nearby rocks.

'''Note''': Mine 1-2 extra if you are planning to complete the easy [[Falador Diary]] and/or want your own [[blurite sword]].
{{Clear}}
"""

[[steps]]
index = 4
name = "Creating the sword"
links = ["iron bar", "blurite ore", "redberry pie", "The Giant Dwarf", "Thurgo", "Members", "Squire"]
text = """
{{Needed|2 [[iron bar]]s (4 if making extra sword), [[blurite ore]] (2 if making extra sword)|recommended=an additional [[redberry pie]] if doing [[The Giant Dwarf]]}}
[[File:Blurite sword detail.png|left|80px|frameless]]
Return to [[Thurgo]] with your [[blurite ore]]s and your iron bars and he will make you a sword. If you want a sword for yourself, drop it and ask Thurgo for a replacement, then pick up the second sword again.

'''Note''': [[Members]] planning on doing [[The Giant Dwarf]] soon after this quest are recommended to give Thurgo an additional [[redberry pie]] now to avoid a return trip during that quest.

Go back to the [[Squire]] and he will take one of your blurite swords.

'''Congratulations, quest complete!'''
"""
