quest = "Spirit of Adventure"
step_count = 6

[[steps]]
index = 0
name = "Starting Out"
links = ["ghostspeak amulet", "Auburn Valley", "the Darkfrost", "Shipwreck Cove", "salvager", "Jasper"]
text = """
{{Needed|[[ghostspeak amulet]]}}

With a [[ghostspeak amulet]] equipped, speak to the ghost wandering near the [[Auburn Valley]] road, north of [[the Darkfrost]]. The ghost will introduce herself as Bernina, and tell the player that she was killed in the shipwreck which is now the namesake of [[Shipwreck Cove]].
She tells the player that her special diamond necklace was stolen from the shipwreck by [[salvager]]s, and this is preventing her from moving on to the afterlife. She asks the player to recover her necklace from a salvager named [[Jasper]].
"""

[[steps]]
index = 1
name = "The Salvagers"
links = ["Salvager Overlook", "Jasper"]
text = """
Head east to the [[Salvager Overlook]] and speak to [[Jasper]] inside the north-east building. Jasper will tell the player that Bernina's necklace was causing him bad luck, so he sold it to a mountain climber.
"""

[[steps]]
index = 2
name = "The Mountain Climber"
links = ["Logs", "Tinderbox", "Proudspire", "Bernard"]
text = """
{{Needed|[[Logs]] and a [[Tinderbox]]}}

The houses south of Jasper contain Logs and a Tinderbox. Head south and then west to the base of the [[Proudspire]]. Climb the mountain until you find a man named [[Bernard]]. Bernard will tell the player about the bad luck he is having and ask the player to light a fire.
Use your logs and tinderbox while standing next to Bernard to light this fire. Once a fire is lit, Bernard will tell the player that he is carrying a diamond necklace to the top of the Proudspire to honour his mother, who happens to be Bernina!
"""

[[steps]]
index = 3
name = "Arranging a Meetup"
links = ["ghostspeak amulet"]
text = """
{{Needed|[[ghostspeak amulet]]}}

Return to Bernina and tell her what you have learned. She will disappear from her current location and appear next to Bernard on the Proudspire.
"""

[[steps]]
index = 4
name = "Reconciliation"
links = ["ghostspeak amulet"]
text = """
{{Needed|[[ghostspeak amulet]]}}

Return to Bernard at the Proudspire, where you will find him nervous about the sudden appearance of a ghost. Speak with him to act as a ghost interpreter for Bernina, allowing her to finally speak with her son and rest in peace.
"""

[[steps]]
index = 5
name = "Laid to Rest"
links = []
text = """
Climb the mountain to meet Bernard at the peak.  It is recommended to continue upwards from Bernard, backtracking to the agility shortcut is slower.  Speak to Bernard in front of the Obelisk atop the Proudspire to complete the miniquest.
"""
