quest = "Land of the Goblins"
step_count = 6

[[steps]]
index = 0
name = "Grubfoot's Dream"
links = ["Dorgesh-kaan sphere", "Dorgesh-Kaan", "Dorgeshuun Mines", "Grubfoot", "Zanik", "Mistag", "Dorgeshuun Council", "Oldak", "Yu'biusk", "Big High War God", "Goblin Cave"]
text = """
{{Needed|recommended=Light source}}'''Note:''' [[Dorgesh-kaan sphere]]s can be obtained by right-clicking Oldak and selecting "Buy-sphere". This will cost 2 law runes and 1 molten glass (can be noted).[[File:Grubfoot chathead.png|left]]
Start out by making your way to the main entrance to [[Dorgesh-Kaan]] at the [[Dorgeshuun Mines]]. Here, you will find [[Grubfoot]], who tells you that he wants to enter Dorgesh-Kaan to speak to [[Zanik]], who he refers to as the Chosen Commander, as he had a dream about her that he needs to discuss with her.
[[File:Land of the Goblins - Grubfoot's dream.png|thumb|280px|Grubfoot's vision of Yu'biusk, the Land of the Goblins.]]
However, [[Mistag]] says that though the [[Dorgeshuun Council]] agreed to allow humans into the city, their laws currently don't allow surface goblins entry. Though the Council wishes to establish relations with them, they have heard the surface goblins are a very warlike people, and most believe letting them into the city is too much of a risk. You will tell Mistag that you will take responsibility for Grubfoot, and enter the city.

Take Grubfoot to [[Zanik]], who can be found in [[Oldak]]'s workshop in the north-west corner of the city. He will tell you and Zanik about his dream of [[Yu'biusk]], the Land of the Goblins, where goblins of all tribes live together in peace in a lush land. He believes that Zanik, the Chosen Commander, is the one who is prophesied to save the goblins by leading them back to Yu'biusk.

Grubfoot will then tell you of a hidden temple of the [[Big High War God]], where the priests within may know the means to reach Yu'biusk. After promising to keep the location of the temple a secret, he'll tell you the entrance is found in a muddy cave near a "place where many humans catch fish". Oldak will recognise that he is referring to the [[Goblin Cave]], and will use a teleportation sphere to take you and Zanik there.
"""

[[steps]]
index = 1
name = "Impostor Among Goblins"
links = ["Dorgesh-kaan sphere", "skills necklace", "Goblin guard (Land of the Goblins)", "black dye", "black mushrooms", "Zanik", "Goblin Temple", "Oldak", "Dorgesh-Kaan", "Makeover Mage", "Crafting Guild", "goblin potion", "toadflax", "pharmakos berries", "goblin mail", "Hopespear's Will"]
text = """
{{Needed|recommended=[[Dorgesh-kaan sphere]], [[skills necklace]]}}

Upon arrival, head north-west until you reach the entrance to the temple, guarded by two [[Goblin guard (Land of the Goblins)|goblin guards]]. If you haven't obtained [[black dye]] already, pick the [[black mushrooms]] nearby for later use.
[[File:Land of the Goblins - temple entrance.png|thumb|280px|The entrance to the Goblin Temple, guarded by two goblins.]]
Speak to the goblin guards, who will allow [[Zanik]] to enter the [[Goblin Temple]]. However, as you are a human, they will deny you entry. Return to [[Oldak]] in [[Dorgesh-Kaan]] and tell him about your predicament, and he will refer you to the [[Makeover Mage]], who may be able to help you. (Talking to Oldak is not required to progress.)

Make your way to the Makeover Mage, who can be found north of the [[Crafting Guild]] (easily reached via [[skills necklace]]), and ask them about turning yourself into a goblin. Though they don't want to perform the procedure for you, wanting to avoid being responsible should something go wrong, they will tell you the recipe to create the [[goblin potion]], which are [[toadflax]] and [[pharmakos berries]], found on bushes just outside the building. They'll also tell you that the potion has several restrictions that if not adhered to will result in the transmogrification being reversed, which include standing in direct sunlight, entering combat, and wearing any items that is not a [[goblin mail]]. (It can be beneficial if doing [[Hopespear's Will]] to make two potions, allowing for you to kill the weaker priests and then re-gear for the last.)
"""

[[steps]]
index = 2
name = "The Temple of Tribes"
links = ["Toadflax potion (unf)", "pharmakos berries", "goblin mail", "black dye", "black mushroom", "pestle and mortar", "vial", "pet", "POH", "menagerie", "goblin potion", "Goblin Cave", "Fishing Guild", "skills necklace", "Goblin guard (Land of the Goblins)", "goblin name", "Goblin Temple", "High Priest Bighead", "Zanik", "Huzamogaarb", "black goblin mail", "Dorgesh-kaan sphere", "Yu'biusk", "Big High War God"]
text = """
{{Needed|[[Toadflax potion (unf)]], [[pharmakos berries]], [[goblin mail]], [[black dye]], don't bring any armour for this part because you will need to unequip it}}

If you picked a [[black mushroom]] earlier, use it on a [[pestle and mortar]] whilst having an empty [[vial]] in your inventory to create [[black dye]], as you'll need it for this part of the quest. Otherwise, bring the vial and pestle and mortar with you when you return to the Goblin Cave. In addition, if you have a [[pet]] following you, deposit it at a bank or store it in your [[POH]] [[menagerie]] as you will not be able to enter the temple otherwise.
[[File:Drinking goblin potion.gif|frame|The player transforms into a goblin.]]
Once you create the [[goblin potion]], make your way back to the [[Goblin Cave]]. You can use the [[Fishing Guild]] teleport on the [[skills necklace]] to reach the cave entrance.

Drink the goblin potion, and you will be prompted to choose how you'll appear as a goblin. Speak to the [[Goblin guard (Land of the Goblins)|goblin guards]] again, who will try guessing your [[goblin name]]; if you like the name they've guessed, tell them they've guessed correctly, otherwise keep telling them to guess again. Afterwards you'll be granted entry to the [[Goblin Temple]]. '''Once inside, if you haven't obtained a goblin mail already, search the crates by the exit for one. It is recommended to take six in total.'''

'''Note:''' if you at any point need to teleport out while in goblin form, make sure to not be wearing your dyed goblin mail with a full inventory or the armour will be '''permanently destroyed'''.

Inside the temple, speak to [[High Priest Bighead]] in the north of the temple, who will tell you that [[Zanik]] has been imprisoned for her antitheist views by the [[Huzamogaarb]] tribe. Use your [[black dye]] on a [[goblin mail]] to create a [[black goblin mail]], then wear it and enter the Huzamogaarb tribal room, found in the north-eastern part of the temple. Speak to Zanik, who will tell you that her [[Dorgesh-kaan sphere]] was confiscated and placed in a crate across the room. Search the crate to receive the sphere and return it to Zanik, who will use it and escape. If you speak to Zanik with a Dorgesh-Kaan sphere already in your inventory, she will take it; you can still search the crate to retrieve a spare.

Return to High Priest Bighead, and ask him about [[Yu'biusk]]. He will tell you that knowledge is not for ordinary goblins, and only those who understand the ways of the [[Big High War God]] may learn of it. The High Priest will test your knowledge about the Big High War God, and you must answer four questions with the correct replies to proceed, as seen below:
* True or false: those who do not believe in Big High War God, whether they goblins or other races, must die.
** True.
** Big High War God commands it.
* True or false: Big High War God chose goblins to be his race because goblins mighty warriors.
** False.
** Goblins not mighty warriors before he chose us.
* True or false: goblin leaders should be good at planning in order to win battles.
** False.
** That one of the commandments.
* Prophecy say some day Big High War God send Chosen Commander. What Chosen Commander do?
** Lead goblins to victory over whole world.
"""

[[steps]]
index = 3
name = "Keys to the Crypt"
links = ["Fishing rod", "raw slimy eel", "coins", "blue dye", "orange dye", "purple dye", "yellow dye", "black goblin mail", "goblin potion", "combat", "goblin mail", "Snothead", "Priest (Goblin)", "Huzamogaarb key", "Whitefish", "Coins", "Aggie", "Draynor Village", "whitefish", "Hemenster", "Fishing Contest", "Ranging Guild", "Morris", "white goblin mail", "Saragorgak", "Yurkolgokh", "Huzamogaarb", "Ekeleshuun", "Narogoshuun", "Horogothgar"]
text = """
{{Needed|[[Fishing rod]], [[raw slimy eel]], 5 [[coins]], [[blue dye]], [[orange dye]], [[purple dye]], [[yellow dye]], [[black goblin mail]],  [[goblin potion]], [[combat]] equipment for the next section|recommended=Two teleports to Draynor Village, 5 extra [[goblin mail]]s}}

After passing the test, the High Priest will answer your questions. ''(The altar in the centre of the room will now also work for you.)'' Ask him about Yu'biusk, and ask of its whereabouts. He will say he does not know, but his predecessor [[Snothead]] might. However, he is buried in the temple crypt, which only the High Priest can enter with the six keys of the six tribal priests. You can also ask other questions, such as the Big High War God's true name, and the reason why there are only six tribes in the temple when there were originally twelve. ''If the pickpocket option doesn't show up on the six Priests, talk to the High Priest again until he mentions the six keys. The option to pickpocket becomes available when you select "can i talk to old high priests"''

[[File:Goblin Temple.png|thumb|280px|The Goblin Temple, dedicated to the Big High War God.]]
To access the temple crypt, you'll need to steal the keys from each of the tribal priests. As you're already wearing the black goblin mail, enter the Huzamogaarb tribal room and pickpocket the [[Priest (Goblin)|priest]] for the [[Huzamogaarb key]]. You will then need to dye your goblin mail(s) to match each of the remaining tribes in order to gain access to their rooms. You will now need to leave the cave to bleach your armour white, and collect the other dyes if you don't already have them. '''Do not teleport out of the temple if your inventory is full or you will lose your goblin mail.'''

'''Note:''' Optionally 5 more goblin mails can be used that are dyed in the colours yellow, blue, orange, and purple. The fifth goblin mail can then be taken to Aggie with a [[Whitefish]] and 5 [[Coins]] to be bleached white.

Make your way to [[Aggie]] in [[Draynor Village]] and ask if she can make dyes for you, and then about the black and white dyes. She says that she will need 5 coins and a [[whitefish]], which are caught only at [[Hemenster]] with [[raw slimy eel]] as bait. Go to the [[Fishing Contest]] area west of the [[Ranging Guild]]. Upon arrival, click on the gate and tell [[Morris]] that you need to catch a whitefish. Once you've caught one, return to Aggie and she'll give you a [[white goblin mail]]. ''Note that you cannot do this before speaking to Aggie''.

Take the dyes, the white goblin mail, the Huzamogaarb key, and some combat gear to the cavern. Unequip everything, and take another sip of your goblin potion to enter the temple.   Pass the guard in the doorway of Saragorgak tribe in the west side of the temple, pickpocket the tribe's priest, and then pass the guard again to leave.

Dye your goblin mail and pickpocket the remaining keys correspondingly:

{| class="wikitable"
!Tribe
!Corner
!Colour
!Key
|-
|[[Saragorgak]]
|West
|{{plink|White goblin mail|txt=White}}
|{{plink|Saragorgak key}}
|-
|[[Yurkolgokh]]
|North-west
|{{plink|Yellow goblin mail|txt=Yellow}}
|{{plink|Yurkolgokh key}}
|-
|[[Huzamogaarb]]
|North-east
|{{plink|Black goblin mail|txt=Black}}
|{{plink|Huzamogaarb key}}
|-
|[[Ekeleshuun]]
|East
|{{plink|Blue goblin mail|txt=Blue}}
|{{plink|Ekeleshuun key}}
|-
|[[Narogoshuun]]
|South-east
|{{plink|Orange goblin mail|txt=Orange}}
|{{plink|Narogoshuun key}}
|-
|[[Horogothgar]]
|South-west
|{{plink|Purple goblin mail|txt=Purple}}
|{{plink|Horogothgar key}}
|}
"""

[[steps]]
index = 4
name = "High Priests of Ages Past"
links = ["Snothead", "Snailfeet", "Strongbones", "Mosschin", "Redeyes", "skoblin"]
text = """
Once obtaining  all 6 keys and using them on the door, they will be removed from your inventory and the door will be open from then on without the use of the keys again.

Now you can enter the crypt - the big door in the north. Once inside, prepare for battle by equipping weapons and armour; you will change from goblin to human when you do this. Go to the first grave to the left, and say the name of the high priest, [[Snothead]]. He will rise from the ground and proceed to attack.

After defeating Snothead, ask about Yu'biusk's whereabouts. Though he does not know, he believes his ancestor knows. Ask for his name, and he'll tell you it is [[Snailfeet]]. Continue with this pattern until you have beaten the remaining high priests. The further back in time you go, you'll realise that the older high priests have a more expansive knowledge of Yu'biusk, speak more eloquently than their successors, and are also more adept at fighting.

After defeating the last priest, [[Strongbones]], he will tell you that Yu'biusk is another plane of existence, not a place on Gielinor.

'''Note:''' Redeyes and Strongbones can deal high amounts of damage, players should be prepared. If needed, players can leave the crypt between fights to bank, but doing so requires turning into a goblin to gain access to the temple and therefore crypt again.

All of the high priests that attack with Ranged/Magic can be somewhat safe-spotted. As long as you stay a few tiles away, they will default to their Ranged/Magic attack and you can use protection prayers. Redeyes and Mosschin both attack with magic, even though their attack animation is with a bow. You might want to attack [[Strongbones]] with strong armour praying against Magic so that you're fairly protected against both the reanimated skeletons and the boss's melee and Ranged attacks.

If the player dies during the fight, their gravestone will appear in the cave outside the temple entrance  - obtaining a new goblin potion and goblin mail is '''not''' required to retrieve their items.
[[File:Land of the Goblins - fighting Strongbones.png|thumb|280px|The player fights Strongbones, the strongest high priest in the crypt.]]
{| class="wikitable"
!Image
!Priest Name
!Level
!Grave location
!Attack Style
|-
|[[File:Snothead chathead.png|center]]
|[[Snothead]]
|32
|South-west
|Melee
|-
|[[File:Snailfeet chathead.png|center]]
|[[Snailfeet]]
|56
|South-east
|Melee and Ranged
|-
|[[File:Mosschin chathead.png|center]]
|[[Mosschin]]
|88
|North-west
|Melee, and Magic
|-
|[[File:Redeyes chathead.png|center]]
|[[Redeyes]]
|121
|North-east
|Melee, and Magic (Lowers Attack, Strength and Defence)
|-
|[[File:Strongbones chathead.png|center]]
|[[Strongbones]]
|184
|North
|Melee, Magic, and Ranged. Summons level 29 [[skoblin]]s, and lowers Attack, Strength and Defence
|}
"""

[[steps]]
index = 5
name = "Path to Yu'biusk"
links = ["Dorgesh-kaan sphere", "dramen staff", "lunar staff", "fairy rings", "Oldak", "Dorgesh-Kaan", "fairy ring", "Dorgesh-Kaan South Dungeon", "law rune", "Dorgesh-Kaan Agility Course", "Yu'biusk", "Bandos", "God Wars", "Strange box (Yu'biusk)"]
text = """
{{Needed|Light source|recommended=[[Dorgesh-kaan sphere]], [[dramen staff|Dramen]] or [[lunar staff]] if players have access to the [[fairy rings]]}}
Return to [[Oldak]]'s workshop in [[Dorgesh-Kaan]], and tell them what you've learned from the high priests. Oldak will tell you that they've found a [[fairy ring|fungus ring]] in the [[Dorgesh-Kaan South Dungeon|southern caves]] with similar properties to [[law rune]]s, and believes that with enough power and Zanik's presence, it should be able to open a portal to Yu'biusk.

If players have access to the [[fairy rings]], use the code {{Fairycode|AJQ}} to teleport there. Otherwise, to get there, travel south on the same floor level as Oldak's workshop, go up the stairs at the end and then up again to reach the [[Dorgesh-Kaan Agility Course|agility course]]. Climb down the ladder at the west side of the agility course platform, walk a bit south and take the first corridor to the east. At the end of the corridor, head south and look west for the [[File:Transportation icon.png]] icon at the southern entrance of the {{FloorNumber|uk=2}}.

Meet up with Zanik and Oldak, who will ask you to adjust the machine by allocating power to each ring proportional to the area within the ring. The rings, from outer to inner, have a radius of 3, 2 and 1. Because a circle's area is proportional to the square of its radius, this means the power given to each of the circles should be 9, 4, and 1.

[[File:Fairy ring power relay.png|right|thumb|280px|The interface used to allocate power to each of the circles in the [[fairy ring]].]]

Enter the values 9-4-1 and activate the machine to start a cutscene where the three of you will be teleported to [[Yu'biusk]]. Upon arriving, you see that it is a barren wasteland, torn asunder in a fit of rage by [[Bandos]], after the [[God Wars]]. Walk north-west until you get to some short walls surrounding a [[Strange box (Yu'biusk)|strange box]]. Oldak will warn you that you need to return fast, but keep walking. Zanik will notice the box and ask you to help her open it.

Open the strange box, and Zanik will be sucked into it. As this happens, Oldak tells you that you and him have to leave, as the portal is closing. Upon returning to Gielinor, Oldak will tell you that he hasn't been able to get the fairy ring-hacking machine working again, and suggests that there may be a way to reach Yu'biusk after breaching the planar barriers between it and Gielinor.

'''Congratulations, quest complete!'''

<gallery captionalign="center" widths="200">
Land of the Goblins - arriving in Yu'biusk.png|The player, Zanik, and Oldak arrive in Yu'biusk, only to find it is not as Grubfoot described.
Land of the Goblins - dreams shattered.png|A strange box is found, being the only intact object you can see in this place.
Land of the Goblins - opening the strange box.gif|The player and Zanik open the box, and Zanik is sucked into it.
</gallery>
"""
