quest = "Fishing Contest"
step_count = 3

[[steps]]
index = 0
name = "Dwarves can't fish!"
links = ["Austri", "Vestri", "White Wolf Mountain", "Hemenster", "fishing pass"]
text = """
{{Map|x=2842|y=3486|x:2876,y:3483,desc:[[Austri]]|x:2821,y:3487,desc:[[Vestri]]|plane=0|mapID=0|zoom=1|height=220|width=220|align=right|mtype=pin|caption=This quest can be started from either side of the White Wolf Mountain.}}
{{Needed|recommended=Fast travel method to McGrubor's Wood and Hemenster for the subsequent sections}}
[[File:Austri chathead.png|left|frameless|80px]]
To start this quest, head to either the dwarf [[Austri]] east of [[White Wolf Mountain]] or the dwarf [[Vestri]] west of the mountain, at the points shown on the map.

:'''Tip:''' The western quest start point is closer to the next part of the quest, so it is recommended if not planning to use fast travel.

Talk with either dwarf, and use the following dialogue options. {{Chat option|1I was wondering what was down those stairs?|2Why not?|3If you were my friend I wouldn't mind it.|1Well, let's be friends!|1And how am I meant to do that?}} Ask what is down the stairs, and he will say you can't use them. Ask why not, and he will ask you how you would like it if he took a shortcut through your home. Tell him if he was your friend you wouldn't mind, and he will say he doesn't know you. Ask to be friends; he wants you to earn his trust first. Ask how you are meant to do that, and he will mention that the dwarves are after a gold artefact, the first prize at the [[Hemenster]] fishing contest. He will give you a [[fishing pass]] to enter in the competition. You must win the competition before the dwarves will allow you to use the shortcut.
"""

[[steps]]
index = 1
name = "Help from the champion"
links = ["spade", "Grandpa Jack", "garlic", "bank", "Seers Village", "McGrubor's Wood", "Fairy ring", "Kandarin Diary", "guard dog", "red vine worms"]
text = """
{{Needed|A [[spade]]|recommended=armour and food for low level players}}
[[File:Fishing Contest - red vine.png|thumb|Checking the vine.|220px]]
[[File:Grandpa Jack chathead.png|left|frameless|80px]]
If you were to head to the contest, [[Grandpa Jack]] the previous champion would give you advice on how to win; you can skip this however, and gather the required items without needing to speak to him.

If you don't already have [[garlic]], pick up a piece off the table in the house south-west of the [[bank]] in [[Seers Village]].

With your [[spade]], head to [[McGrubor's Wood]] west of [[Seers Village]], also accessible by the [[Fairy ring]] {{Fairycode|als}} inside (using the ring will also complete a medium [[Kandarin Diary]] task). If entering from outside, the southern gate is locked and you must squeeze through the railing on the northern side. Beware of aggressive level 44 [[guard dog]]s.

Just west of the fairy ring, you will find a red vine. Check the red vine and collect at least 2 [[red vine worms]].
"""

[[steps]]
index = 2
name = "Winning the trophy"
links = ["fishing pass", "fishing rod", "garlic", "coins", "red vine worm", "Hemenster", "Grandpa Jack", "Morris", "Bonzo", "Sinister Stranger", "raw giant carp", "Fishing trophy"]
text = """
{{Needed|A [[fishing pass]], [[fishing rod]], [[garlic]], 5 [[coins]] (10 if no rod), and 1 [[red vine worm]]}}
[[File:Sinister Stranger chathead.png|left|frameless|80px]]
Head to [[Hemenster]], located by the Ranging Guild. If you didn't bring a fishing rod, buy one for 5 [[coins]] from [[Grandpa Jack]] in the house slightly north-east of the town.

Find [[Morris]] at the gate to [[Hemenster]] and show him your [[fishing pass]] and he will let you in.

Put the [[garlic]] into one of the pipes on the south wall of the north building (just next to the gate).

Pay [[Bonzo]] the contest fee to start the contest (5 coins). The [[Sinister Stranger]] will complain about a horrible smell and you will change places with him.

[[File:Fishing Contest - Fishing the giant carp.png|thumb|220px|Fishing next to the pipes.]]
Fish at the spot by the pipes using the [[red vine worm]]s. You will catch a [[raw giant carp|giant carp]], a unique type of fish that you can't catch normally, and that will be the prize winning fish.

Speak to [[Bonzo]] again and hand over the [[raw giant carp|giant carp]]. You will be announced the winner of the Fishing Competition.

After winning the contest and obtaining your [[Fishing trophy|trophy]], head back to the quest starting point on either side of the mountain and give the dwarf your trophy.

'''Congratulations, quest complete!'''
[[File:Fishing trophy detail.png|left|60px]]
{{Clear}}
"""
