quest = "Ratcatchers"
step_count = 8

[[steps]]
index = 0
name = "Starting out"
links = ["cat", "overgrown cat", "Gertrude", "Phingspet", "Grimesquit", "Varrock Sewers", "rat", "rat pole", "Jimmy Dazzler", "Ardougne"]
text = """
{{Needed|A [[cat]] (not an [[overgrown cat]]).}}

Talk with [[Gertrude]]. She will tell you to speak to [[Phingspet]] and [[Grimesquit]], the Sisters Grime. They can be found in the [[Varrock Sewers]], East of the Palace exit. After speaking with them briefly, your cat will have to catch eight [[rat]]s before they will speak to you more. To find out how many rats you've caught, check your quest journal or speak to either of them and they will tell you.

'''Note:''' ''You must have the two sniff your cat '''before''' starting to have it chase rats, or they will not count!''

Alternatively, a conversation box will pop up when you've caught the eight rats. The success rate of catching rats seems to take into account the proximity of the rat, so if you're using a kitten it may be worth attacking one to turn it aggressive to you, which in turn will keep it close. This trick will not work for rats later in the quest.

Catch eight rats in Varrock Sewers by clicking the "Chase" option on your cat. Then, speak to them again to receive a [[rat pole]], and they will send you to talk to [[Jimmy Dazzler]] in [[Ardougne]].
"""

[[steps]]
index = 1
name = "Jimmy Dazzler"
links = ["cat", "overgrown cat", "Ardougne", "Varrock", "Jimmy Dazzler", "Flying Horse Inn", "East Ardougne", "Ali Morrisane", "Directions", "world map", "Run", "Kitten", "The Feud"]
text = """
{{Needed|A [[cat]] (not an [[overgrown cat]]), 1 free inventory space.|recommendedFast travel to [[Ardougne]] and [[Varrock]].}}

{{Map|name=Jimmy Dazzler|x=2561|y=3320|r=4|mtype=square|align=right|caption=[[Jimmy Dazzler]] is located in a house west of the [[Flying Horse Inn]] in [[East Ardougne]].|width=250|height=250}}

'''Note:''' Be prepared to spend some time on this part unless you get extremely lucky. '''The guards simply having their backs turned is not enough to keep you from being seen.'''

[[Jimmy Dazzler]] can be found in a house to the west of the [[Flying Horse Inn]] in [[East Ardougne]] on the west side of the river. He needs a house cleared of rats in an unofficial capacity so as not to tarnish his [[Ali Morrisane|client]]'s reputation; to this end, you will need to sneak around the house unnoticed, avoiding the guards who will think you are an intruder. Jimmy will give you [[Directions]] to follow to the house. Read them, and you will be prompted to go to the house (it is not located on the [[world map]] — you are teleported there instantly). You will find yourself in front of the house, in the gardens.

To make your way inside the house, you will need to make sure you don't draw the guards' attention; keeping [[Run]] on is advised and having lots of patience will help greatly. Guards will not notice your cat. There are three "checkpoints"; upon reaching these points, any guards who see you will send you back to these points, rather than the very beginning. You must also avoid the party guests, but they are all located away from any of the rooms containing rats.

[[Kitten]]s and [[cat]]s have increased rat catch rates during this section of the quest. The catch rate for kittens is increased from 10% to 40%, and the catch rate for cats is increased from 50% to 75%. The catch rates of other cat types remains unchanged.

{{Bug|If [[The Feud]] has been completed, Ali Morrisane should not teleport the player out if he catches them. However, due to the game checking for an impossible state of the quest variable, this does not work, and being seen by Ali Morrisane will always result in the player being teleported out.}}
"""

[[steps]]
index = 2
name = "=Part 1="
links = []
text = """
[[File:Ratcatchers Mansion(Outside, S).png|600px]]

''The red and blue tiles indicate where the guards stop along their paths. Note that the guards retrace their steps and stop at each spot on their return. For example, the south guard goes along the path (1-2-3-2-1).''
* Start at tile '''A'''.
* When the south guard is on '''blue tile 1''', run to tile '''B'''.
* Immediately run to tile '''C'''.
"""

[[steps]]
index = 3
name = "=Part 2="
links = []
text = """
[[File:Ratcatchers Mansion(Outside, N).png|600px]]

''Note that when the north guard would normally move from their position at tile 7, they will instead teleport to tile 5.''
* Start at tile '''A'''.
* When the south guard is at '''blue tile 1''' and the north guard is on any '''red tile 1-4''', run to tile '''B'''.
* When the north guard is on any '''red tile 4-7''', run to tile '''C'''.
* While the north guard is still on any '''red tile 4-7''', run to tile '''D''' and climb the trellis, then immediately move to tile '''A''' in '''Part 3''' below, if not caught.
*Climbing the trellis will set a safe checkpoint north of the trellis.
"""

[[steps]]
index = 4
name = "=Part 3="
links = ["Settings", "Ardougne Rat Pits", "Hooknosed Jack"]
text = """
''For this section, it's recommended to go into your [[Settings]], then "All Settings" and enable the option "Hide Roofs" under the Display category. This will make it a lot easier to see the guards as they move around while you attempt to move inside the mansion.''

'''Note:''' If the guards follow a pattern that will never allow passage, you are required to either switch worlds or get caught by the same guard several times.

For this section, it is recommended to keep your cat in your inventory while moving about to avoid it becoming stuck on obstacles, or else use the 'Call follower' option in the equipment tab to teleport your cat to you.

[[File:Ratcatchers Mansion(Inside).png|600px]]


* When the west guard is on any '''blue tile 6-7''' and the east guard is on any '''red tile 4-7''', run to tile '''B'''. Note that you '''MUST''' run onto the balcony behind the wall to reach tile '''A''' before continuing.'
* Catch the rat in this room. Make sure you are not standing in the doorway when the guard passes by.
* When the west guard is on any '''blue tile 4-7''' and the east guard is on any '''red tile 6-7''', run to tile '''C''' and go through the door, again making sure you are not standing in the doorway when the guard passes by.
** Alternatively for steps 3-4, get caught and start at the tile that mirrors A, then mirror previous steps.
* When the west guard is on any '''blue tile 1 or 3-6''' and the east guard is on '''red tile 1''', run to tile '''D'''.
* Catch the 2 rats in this room and go down the ladder. There will be no more guards once you go down the ladder.
* Catch the last 3 rats in this room and the kitchen to the north.
*1 rat may spawn outside of this room/kitchen, simply change world and the rat will be correctly spawn in the room.

To proceed, all six rats need to have been caught. You will automatically start a dialogue with your cat after catching the last rat.

Once you catch all six rats, teleport out of the mansion and return to Jimmy Dazzler. Alternatively, you can return to Ardougne by sneaking back to the trellis. He will give you access to the [[Ardougne Rat Pits]] and tell you about the next person you have to find: [[Hooknosed Jack]].
"""

[[steps]]
index = 5
name = "Hooknosed Jack"
links = ["cat", "Cat", "cheese", "rat poison", "vial", "red spiders' eggs", "kwuarm", "bucket of milk", "marrentill", "unicorn horn dust", "catspeak amulet", "fish", "raw karambwanji", "Hooknosed Jack", "Varrock", "poisoned cheese", "Apothecary", "cat antipoison", "King rat", "Call follower", "Worn Equipment", "Smokin' Joe"]
text = """
{{Needed|A [[cat]] with decent [[Cat#Combat_stats|combat stats]], four pieces of [[cheese]], [[rat poison]] or the ingredients for it (a [[vial]], [[red spiders' eggs]], and a [[kwuarm]]), a [[bucket of milk]], a [[marrentill]] and [[unicorn horn dust]].|recommended=A [[catspeak amulet]] and 8-10 [[fish]] to heal your cat (leaping trout/salmon won't work); [[raw karambwanji]] are stackable and easy to get, freeing inventory space. More mature cats have higher strength and HP stats, making it easier.}}

You can find [[Hooknosed Jack]] in south-eastern [[Varrock]] (look for the minigame icon). He will tell you about the rat infestation in a warehouse nearby. You need rat poison, or he can make you some if you give him a vial, red spiders' eggs, and a kwuarm. Use the poison on four pieces of cheese to create [[poisoned cheese]]; then, go to the warehouse south of the pub. Go in and climb the ladder to the top. Use (be sure not to eat!) your poisoned cheese on the four rat holes to poison them. Return to Hooknosed Jack.

[[File:Ratbattle.png|thumb|right|Fighting the King rat.]]
He will tell you that his cat, Pox, ate some of the poisoned rats. Go to the [[Apothecary]] (the potion shop in west Varrock). He will ask for a marrentill herb, a crushed unicorn horn, and a bucket of milk to make a special [[cat antipoison]]. Give the antipoison to Hooknosed Jack to cure Pox, who will then tell you that there is still one rat left - the biggest and most evil. Go back to the warehouse. Climb upstairs and inside a room, you'll see the [[King rat]], but you won't be able to reach it yourself. If your cat disappears log out and back in, or use the [[Call follower]] button.


Ensure that you have enough fish (8-10 recommended). Use your cat on the hole in the wall (not the rat holes) to challenge the king rat. You will be presented with two dialogue options:
*"Be careful!" : Your cat will automatically retreat if it has only one hitpoint remaining, allowing you to restart the fight. (The King rat will regain its hp.)
*"Don't hold back!" : Your cat will continue fighting until it or the rat dies. '''''{{Colour|red|Warning}}:''' Not recommended due to the potential risk of losing your cat.''
''You can always withdraw and pull back your cat by climbing down the stairs, or by calling it via the [[Worn Equipment|worn equipment]] tab.''


The king rat has 10 hitpoints and deals a maximum of 1 damage at a time. Your cat has [[Cat#combat stats|combat stats]] according to its type. Whenever your cat takes too much damage, you can use fish on the hole in the wall ('''''not on the cat itself''''') to heal it.

After you defeat the King rat, go back to Hooknosed Jack. He'll give you access to the Varrock Rat Pits and tell you about [[Smokin' Joe]].
"""

[[steps]]
index = 6
name = "Smokin' Joe"
links = ["cat", "catspeak amulet", "pot of weeds", "tinderbox", "The Giant Dwarf", "Keldagrim", "Grand Exchange", "Blast Furnace", "minigame teleport", "Rellekka", "Smokin' Joe", "Pickaxe-Is-Mine", "Dragon Slayer II", "smouldering pot", "The Face", "Call follower"]
text = """
{{Needed|A [[cat]], a [[catspeak amulet]], a [[pot of weeds]] and a [[tinderbox]].}}''[[The Giant Dwarf]] must be started to access [[Keldagrim]].''[[File:Ratcatchers Keldagrim smoking.png|thumb|The rats are smoked out of their hole and ambushed by the cat.]]
Go to Keldagrim (you can use the minecart entrance north-west of the [[Grand Exchange]], the [[Blast Furnace]] [[minigame teleport]], or the city's entrance east of [[Rellekka]]) and talk to [[Smokin' Joe]] east of the [[Pickaxe-Is-Mine|pickaxe shop]] (far in the east of Keldagrim), who will tell you about his rat problem. The only way to get the rats out of their hole is to smoke them out, but Smokin' Joe can't do it because of the poor condition of his lungs. Offer to help him. Light a pot of weeds with your tinderbox, and use it on the rat hole to the east of him. Rats will come out the other side and quickly go back in. Place your cat on the ground and wear your catspeak amulet - note that '''wearing the catspeak amulet is''' '''required''', even for those who can speak with cats after [[Dragon Slayer II]]. Use your [[smouldering pot]] on the rat hole again, and your cat will offer to help. Accept, and your cat will ambush the rats and kill them. Talk to Smokin' Joe again, and he will give you access to the Keldagrim Rat Pits and tell you about [[The Face]].

:'''Note:''' If your cat disappears when you use the smouldering pot on the rat hole, simply log out and back in again, or use the [[Call follower]] button, and it will reappear next to you.
"""

[[steps]]
index = 7
name = "The Face and Felkrash"
links = ["catspeak amulet", "snake charm", "music scroll", "The Feud", "coins", "ring of charos", "Port Sarim", "Pollnivneach", "The Face", "Gerrant's Fishy Business", "Felkrash", "manhole (Rat Pits)", "snake charmer", "Kharidian Desert", "Ali the Snake Charmer"]
text = """
{{Needed|A [[catspeak amulet]], a [[snake charm]] (comes with the [[music scroll]] that you buy or from [[The Feud]]) and 101 [[coins]] (or 51 with a [[ring of charos]] (a)).|recommended=Fast travel to [[Port Sarim]] and [[Pollnivneach]].}}
[[File:Ratcatchers Charm Music.png|thumb|The music sheet to charm the rats.]]
[[File:Ratcatchers Port Sarim charming.png|thumb|Charming the rats in Port Sarim.]]

You can find [[The Face]] in Port Sarim next to the [[Gerrant's Fishy Business|fishing shop]] (look for the minigame icon). She will tell you to talk to [[Felkrash]] down in the rat pits. Go down the [[manhole (Rat Pits)|manhole]] and find Felkrash, who will tell you to get rid of all of Port Sarim's vermin at once.

Talk to The Face and ask the third option she will tell you about a [[snake charmer]] in [[Pollnivneach]].

'''Note:''' You have to talk with The Face before heading to Pollnivneach, else the snake charmer will not discuss the alternate methods of animal charming.

Go to Pollnivneach in the [[Kharidian Desert]]. You will find [[Ali the Snake Charmer]] there south of the bar (After completion of The Feud, his name changes from Ali to Badir). Use a coin on his money pot to get his attention. Ask him about charming other animals, and he will tell you that he and Felkrash had a falling out because of Felkrash's killing of animals. When presented with multiple-choice dialogue, ''offer him some money''. Tell him you ''don't care about his offer'' and ''walk away slowly'' until you get the option to ''stop''. He will reluctantly give you a [[music scroll]] and [[snake charm]] for 100 coins (if you already have a snake charm from [[The Feud]] quest in your inventory or bank, you will not receive another). You can charm him with the ring of charos to lower his price to 50 coins, and also skip the walking away part.

Return to Port Sarim and stand near the docks. Compose the tune on the snake charm in the order that you can find on your music scroll (as seen in the screenshot; D, G, E, F#, (raise octave D), B, C#, A). One note is selected per page; note that the fifth note is an octave higher, which requires pressing the ''Raise an Octave'' button on the top left of the scroll. Note also that there are two notes with two holes. Once you're done, click "PLAY". Note: You cannot play the tune unless you have gotten the music scroll from Ali (or Badir) the Snake Charmer. If you try, you'll get a message that your fingers are not dexterous enough to play the tune.

Your character will proceed to play the song, which will charm the rats. You'll see a cutscene where you lead the rats into the ocean. Talk to Felkrash in the Port Sarim Rat Pits to finish the quest.

{{Bug|Talking to Felkrash with an overgrown cat in the inventory will cause her to train it into a wily cat, which will automatically be set as your follower. Doing so will '''automatically delete''' your current follower, such as a kitten.}}

'''Congratulations, quest complete!'''

{{Clear}}
"""
