quest = "The Queen of Thieves"
step_count = 5

[[steps]]
index = 0
name = "Beginning the quest"
links = ["Tomas Lawry", "Poor looking woman", "Robert O'Reilly", "The Warrens", "Conrad King", "Port Piscarilius", "bank", "Kourend Council", "Saviours of Kourend", "Great Kourend"]
text = """
{{Map|mtype=pin|align=right|caption=The locations of various NPCs during the quest.
|1796,3782,title:[[Tomas Lawry]],icon:bluePin,desc:
|1804,3737,title:[[Poor looking woman]],desc:
|1794,3757,title:[[Robert O'Reilly]],desc:
|1813,3745,title:[[The Warrens]],desc:
|1848,3734,title:[[Conrad King]],desc:
}}
[[File:Tomas Lawry chathead.png|left]]
Speak to [[Tomas Lawry]] outside the [[Port Piscarilius]] [[bank]]. He is conducting an investigation on behalf of the [[Kourend Council]] to investigate unusual happenings in [[Port Piscarilius]]. A new gang called the [[Saviours of Kourend]] has recently formed, absorbing many of the other gangs, and has become the largest gang in [[Great Kourend|Kourend]], with more joining them each day. According to him, their leader is The Queen of Thieves. Tomas attempted to infiltrate the gang with little success. Agree to help him.
"""

[[steps]]
index = 1
name = "Discovery"
links = ["poor looking man", "poor looking woman", "Robert O'Reilly", "Kenelme", "stew", "Kenelme's Wares", "Leenz's General Supplies", "range", "The Warrens", "manhole (Port Piscarilius)", "icon", "minimap"]
text = """
[[File:Robert O'Reilly chathead.png|left]]
Speak to one of the [[poor looking man|poor looking men]] or [[poor looking woman|women]] (one can be found in the house directly south of the bridge) and ask about the Saviours of Kourend's location. They will say they doesn't know where they can be found, but they do know a man who has been working with them: [[Robert O'Reilly]]. He can be found in the building directly west of the bridge, in the room to the right of [[Kenelme]]. In order to reveal the location of the Saviours of Kourend, he will ask for a [[stew]].

'''If you don't have the stew:'''

A piece of meat along with a '''raw''' potato can be purchased from [[Kenelme's Wares]] in the house directly to the west, a bowl can be purchased from the [[Leenz's General Supplies|general store]] and filled in the sink in Robert's house, and the stew can be cooked on the [[range]] in Robert's house. Use the potato on the bowl of water, then cook the piece of meat and add it to the bowl followed by cooking the stew.

'''Once you have the Stew:'''

Give him the stew and he will tell you they are located in [[The Warrens]]. The entrance to The Warrens is a [[manhole (Port Piscarilius)|manhole]] located a short walk to the east, marked by the [[File:Dungeon map link icon.png]] [[icon]] on the [[minimap]].
"""

[[steps]]
index = 2
name = "Infiltration"
links = ["minimap", "Devan Rutter", "Conrad King", "Warrens General Store", "Kourend & Kebos Diary"]
text = """
[[File:Devan Rutter chathead.png|left]]
After climbing down the manhole go a little bit south and head west over the two small bridges (they aren't on the [[minimap]] and may not show up on some web browsers, or on Low Detail mode on some clients) to arrive at the large island. Talk to [[Devan Rutter]]. You will ask to join the gang, but he will want you to kill [[Conrad King]], a senior member of a rival gang, the Vipers, to prove your loyalty.
[[File:The Queen of Thieves - killing Conrad King.png|thumb|220px|The player kills Conrad King.]]
'''Note''': Browse the [[Warrens General Store]] to complete an easy task in the [[Kourend & Kebos Diary]].

Go back past the two bridges, then head up where you climbed down the manhole. Walk a bit east until you see Conrad King on the dock on the southern side of the Piscarilius mess hall. You have the option to kill him 'brutally' or 'softly.' Choosing 'softly' results in a humorous dialogue stating that this is impossible, causing you to kill him 'brutally' anyway.
"""

[[steps]]
index = 3
name = "The truth"
links = ["Devan Rutter", "Lady Shauna Piscarilius", "Councillor Hughes", "Disciple of Yama", "Kingstown", "Letter (The Queen of Thieves)"]
text = """
[[File:Lady Shauna Piscarilius chathead.png|left]]
Return to [[Devan Rutter]]. Then, enter the tent north of him and speak to the Queen of Thieves. You will attempt to arrest her, but she tells you the truth about the gang: Before they came along, Kourend was filled with violent gangs who stole and killed, but the Saviours of Kourend pick particular targets, removing people of power and giving it back to those who keep the kingdom alive. She will reveal that she is none other than the leader of Piscarilius, [[Lady Shauna Piscarilius]], and that "Queen of Thieves" is her alias which she uses to strike fear into the rich and degenerate.
[[File:The Queen of Thieves - searching chest.png|thumb|220px|Searching the chest in Councillor Sophia Hughes' home.]]
You will doubt her claims, so she tells you about the current leadership situation, and the corruption of the Kourend Council.
{{Map|name=The Queen of Thieves|x:1670,y:3677|x:1670,y:3684|x:1684,y:3684|x:1684,y:3677|plane=0|mapID=0|mtype=polygon|height=250|width=250|align=left|caption=The location of Councillor Hughes' house.}}
To prove she is telling the truth, she will ask you to search [[Councillor Hughes]]' home, as they believe she has ties with the [[Disciple of Yama|Disciples of Yama]].

Travel to [[Kingstown]] and head east to the houses of the Council members. Councillor Hughes' house is immediately north (south of the [[File:Rare trees icon.png]] icon). The evidence Shauna refers to is found upstairs; she is not home, so simply pick the lock and search the chest to find a [[Letter (The Queen of Thieves)|letter]], which proves Shauna's claims.
"""

[[steps]]
index = 4
name = "Finishing up"
links = ["Tomas Lawry", "Letter (The Queen of Thieves)", "Disciple of Yama", "Lady Shauna Piscarilius", "Councillor Hughes"]
text = """
Return to [[Tomas Lawry]] and give him the [[Letter (The Queen of Thieves)|letter]]. Reading the contents of the letter, he will forget about the Queen of Thieves, believing Councillor Hughes' ties with the [[Disciple of Yama|Disciples of Yama]] is more pressing, and plans to report it to the Council immediately. However, if you ask him for a reward, he will tell you that the best reward is the satisfaction of a job well done and will tell you to go away as he has more work to do.

Return to [[Lady Shauna Piscarilius]] down the manhole in "The Warrens" by Devan Rutter. She will tell you that [[Councillor Hughes]] has been arrested, and admits that you're not totally useless after all. She continues, saying that her arrest is only the beginning, and there's still much work to be done. Lastly, she will tell you that she may call on your help once more, or maybe not. She will then give you your rewards.

'''Congratulations, quest complete!'''
"""
