quest = "Icthlarin's Little Helper"
step_count = 14

[[steps]]
index = 0
name = "Flashback Mechanics"
links = []
text = """
'''{{Colour|Red|Warning}}''': Throughout this quest, you will encounter several flashbacks where you remember what you did while you were hypnotised. You must play through these in order to progress through the quest. Prior to triggering each flashback, make sure you are prepared as once you begin a flashback, you will be '''unable to teleport away until you either finish the flashback, or die.''' Dying will cause your cat to be lost. During a flashback, to leave the pyramid you are expected to walk back to the entrance. You may also log out and back in, which will place your character outside of the pyramid entrance.
"""

[[steps]]
index = 1
name = "Getting Started"
links = ["cat", "Nardah teleport", "magic carpet", "Pollnivneach", "fairy ring", "Wanderer", "Sophanem", "Attack", "Strength", "Ranged", "Magic", "canopic jar", "apparition", "Apparition", "27 April", "2022", "tinderbox", "waterskin", "Rock (Agility Pyramid)", "Klenter's Pyramid"]
text = """
Collect all the supplies needed for the quest including your [[cat]]. Use the [[Nardah teleport]] if you have one or use a [[magic carpet]] ride to [[Pollnivneach]], then south to Nardah  (or [[fairy ring]] code {{Fairycode|DLQ}}) and head to the [[Wanderer]] (north of [[Sophanem]]) in the desert. If you brought an empty bucket to get a pile of salt, go to the pond west of the Wanderer, prior to talking to her. Use the collect water option to get a bucket of salt water.

Note that when you first speak to the wanderer and begin the quest, the game will check your [[Attack]], [[Strength]], [[Ranged]], and [[Magic]] levels, as well as the Strength, Ranged strength, Magic strength, and defence bonuses of any items you have equipped or in your inventory. The highest of these influences which [[canopic jar]] you are most likely to obtain, which affects which [[apparition]] you fight and which potion drop you will receive from the quest's final boss. While your stats and items make getting a certain jar more likely, note that there is still a chance to get a different one regardless.

{| class="wikitable mw-collapsible"
|+ Canopic jars
|-
!Stats
!Equipment bonuses
!Jar
!Apparition
!Potion
|-
|{{Skill clickpic|Attack}}[[Attack]] & {{Skill clickpic|Strength}}[[Strength]]
|Strength, Stab defence, Slash defence, Crush defence
|{{plink|Canopic jar (Het)|txt=Lid shaped like a man, contains a liver}}
|[[Apparition#Het|Het apparition]] (fights with melee)
|{{plink|Defence potion(4)}}
|-
|{{Skill clickpic|Ranged}}[[Ranged]]
|Ranged strength, Ranged defence
|{{plink|Canopic jar (Apmeken)|txt=Lid shaped like an ape, contains intenstines}}
|[[Apparition#Apmeken|Apmeken apparition]] (fights with magic)
|{{plink|Attack potion(4)}}
|-
|{{Skill clickpic|Magic}}[[Magic]]
|Magic strength, Magic defence
|{{plink|Canopic jar (Scabaras)|txt=Lid shaped like a bug, contains a stomach.}}
|[[Apparition#Scabaras|Scabaras apparition]] (fights with melee)
|{{plink|Agility potion(4)}}
|-
|Unused, unless the quest was started prior to [[27 April]] [[2022]]
|Unused
|{{plink|Canopic jar (Crondis)|txt=Lid shaped like a crocodile, contains lungs}}
|[[Apparition#Crondis|Crondis apparition]] (fights with magic)
|{{plink|Magic potion(4)}}
|}

The Wanderer will have a strange reaction to your cat. Ask her why she has a problem with the cat. She will tell you that if you get your cat away from her, she would tell you about the secret entrance to [[Sophanem]]. Wait, and you will automatically pick up your cat. She will then ask for a [[tinderbox]] and full [[waterskin]]. Talk to her again and say '''Yes, I have them all here''' (4th dialogue option). Once you give them to her, she will hypnotise you and you'll enter a [[Rock (Agility Pyramid)|small cave]] just north-east of her tent. You can now use this passage to enter the city at any time, including if you die, which will give you the quest items back.
[[File:Icthlarin's Little Helper - The Pyramid Door.png|thumb|The pyramid door.]]
You will end up just outside a [[Klenter's Pyramid|pyramid]] in Sophanem, and a [[canopic jar]] will appear in your inventory. The door to the pyramid is immediately to your south, with a picture of a cat on the door. Proceed to the first Flashback. '''Note: If you take too long, a spectre will attack you and steal some of your gold or deal damage.'''
"""

[[steps]]
index = 2
name = "First Flashback"
links = ["Klenter's Pyramid", "mummies", "Scarab swarm", "poison"]
text = """
'''{{Colour|Red|Warning}}''': Prior to proceeding, ensure you are prepared and familiar with the Flashback mechanics outlined at the start of this walkthrough.

'''Important note: Using the mini-map to navigate the pyramid will automatically avoid the traps (both the wall-crushers and pit traps) and is much more time efficient than manually navigating it.'''

Touch the door of the [[Klenter's Pyramid|pyramid]] to begin the first flashback. During the flashback, you will need to go through the pyramid. You'll see some wall crushers. Stand on the opposite wall and don't go next to them, as they will damage you if you do. Once you're past the crusher blocks, you'll find pit traps in the next hallway. If you step on the wrong spot, you'll fall into a pit and end up at the beginning of the pyramid. You can move forward by clicking on the map, and your character will avoid the traps automatically. To avoid traps, stay along the left wall until you pass the whitish rectangle on the wall, and then go to the right side. Continue walking until you are opposite a square. Go back to the left side until you pass a candle. Switch to the right wall once more.
[[File:Icthlarin's Little Helper - The Pit.png|thumb|The pit.]]
You'll see [[mummies]] (level 84). They will attack you; simply go past them. You'll also see [[Scarab swarm|Scarab swarms]] (level 96) crack out of the ground. They can rapidly hit you for 2 damage and can also inflict a [[poison]] condition which hits you for another 2 points of damage, and they very obnoxiously stop you in your tracks, regardless of whether or not you have auto-retaliate enabled. Continue to some more wall crushers. Past these—you'll eventually find a large pit. Jump over it. (You'll need 20% run energy. If you fail, you'll reappear near the second set of wall crushers.)

Go to the west door (double-check your compass) and try to open it. Now, you need to solve a puzzle. The objective is to flip all of the tiles onto their gold sides. There is no required number of flips that you must make, nor is there any limit of tries. Each time you flip a tile, the nine tiles in a 3x3 grid will also flip. To solve this puzzle click on the squares in the order shown on the image below (make sure the puzzle is in the default position as shown below. To get to the default position, right click on the gold solution to reset. Keep hitting the "reset puzzle" button until the puzzle looks as shown in the picture below).
Once you've solved it, you'll wake up fully healed outside the pyramid.
[[File:Icthlarin's Little Helper - Puzzle.png|left|thumb|The puzzle.]]
[[File:Icthlarin's Little Helper - Puzzle solution.png|thumb|Solution]]
{{Clear|left}}
"""

[[steps]]
index = 3
name = "After Flashback 1"
links = ["Sphinx", "cat", "Gertrude", "Sphinx's token", "High Priest (Sophanem)", "Klenter's Pyramid"]
text = """
After you finish the flashback, talk to the [[Sphinx]] with your [[cat]] out. Ask for help and the Sphinx will ask you this question: "A husband and a wife have six sons and each son has one sister. How many people are in the family?" The answer is 9 (6 brothers + 1 sister + 2 parents = 9; while a naive reading might assume that each brother has a separate sister, since every member of the family is related, if that was true each brother would have six sisters, not one sister). '''If you guess wrong, you will lose your cat and have to obtain another one from [[Gertrude]].''' Before making your guess, the Sphinx will ask you to confirm your answer; '''if you are about to choose the wrong answer, your cat will shake its head and scratch your leg as a warning.''' Once answered correctly, you will receive the [[Sphinx's token]], so you can speak to the [[High Priest (Sophanem)|High Priest]].

Go to the High Priest, located in the south-west corner of the city, and ask him about the remains. He will tell you to put them back in the burial chamber.

Return to the [[Klenter's Pyramid|pyramid]], and select open door. Your cat will help you get back inside. Go through the pyramid using the same steps as in the first flashback. ''Before you jump the pit examine the canopic jar in your inventory''! so that you can know in advance which attack style the apparition you must fight will use, and thus be able to bring the appropriate equipment to fight it. When you jump across the pit, you'll enter the second flashback.
"""

[[steps]]
index = 4
name = "Second Flashback"
links = ["Magic", "Melee", "Protection prayers", "respawn", "Ultimate Ironmen"]
text = """
[[File:Icthlarin's Little Helper - Attacking the Guardian.png|thumb|Attacking the guardian.]]
The second flashback begins where the first one left off—on the other side of the pit. Open the unlocked door of the west room. Examine the four jars to find which one you used to have in your inventory. If you don't remember, you can open your quest journal to figure out which jar you need to pick up, which will be stated by the major organ inside of it, or just try them all. The player will only take the correct one. As soon as you try to pick up your jar, one of four apparitions will attack you, which can range in Level between 75 and 81 and which uses a specific attack style. Two of the apparition types attack with [[Magic]] and the other two with [[Melee]], and which one will appear depends on which specific jar you have, as follows. [[Protection prayers]] offer full protection against their attacks.

* If your jar's examine text is "It has a lid shaped like an '''ape'''. Eeew! I think it contains someone's '''intestines'''", then the guardian will be Apmeken, who attacks with '''Magic'''.
* If your jar's examine text is "It has a lid shaped like a '''crocodile'''. Yuck! I think there are '''lungs''' inside.", then the guardian will be Crondis, who attacks with Magic.
* If your jar's examine text is "It has a lid shaped like a '''bug'''. Disgusting! I think there's a '''stomach''' inside", then the guardian will be Scabaras, who attacks with '''Melee'''.
* If your jar's examine text is "It has a lid shaped like a '''man'''. I think it contains someone's '''liver'''. Eeew!", then the guardian will be Het, who attacks with Melee.

Dying during this fight will send you to your [[respawn]] location with the canopic jar in your inventory. Any other items are subject to normal death rules, while [[Ultimate Ironmen]] will have a death pile next to the pyramid entrance in Sophanem. Your cat will be gone. Re-entering the pyramid will return you outside of the west room in the flashback state.

'''Once you've defeated the guardian, pick up the jar.''' Leave the room and jump across the pit again. The flashback ends. (If you forgot to pick up the jar before jumping the pit, leave the pyramid and enter it again to return to just outside the jar room.)
"""

[[steps]]
index = 5
name = "Returning the canopic jar"
links = ["canopic jar", "Klenter's Pyramid", "High Priest (Sophanem)"]
text = """
[[File:Icthlarin's Little Helper - Puzzle solution.png|thumb|Solve the puzzle by pressing the squares in the order indicated by the numbers]]
{{Listen|filename=Icthlarin's Little Puzzle.ogg|desc=The jingle that plays upon solving the puzzle.|title=Solved!}}
After the flashback is over, you will feel regret, and you will say to yourself that you think you should put the jar back. Jump the pit and go to the west door (remember you need to have 20% run energy to successfully jump the pit). You will need to solve the same door puzzle to enter the room. Click on the large golden bird to reset the puzzle until it lands on the solution shown in the image to the right. Then click the tiles indicated on the picture. Once you turn all of the tiles to their gold side; you will automatically enter the room. Drop the [[canopic jar]] where you found it and go back through the [[Klenter's Pyramid|pyramid]], across the pit, past the monsters, and past the traps to the [[High Priest (Sophanem)|High Priest]]. Alternatively, you can log out and back in, which will return you to the entrance with the objective still completed.
"""

[[steps]]
index = 6
name = "The High Priest"
links = ["High Priest (Sophanem)", "Embalmer", "Carpenter"]
text = """
Talk with the [[High Priest (Sophanem)|High Priest]]. He will ask you to prepare a ceremony. You will need to help the [[Embalmer]] and the [[Carpenter]]. If you used a Protection prayer during the fight, recharge your prayer points at the altar here.
"""

[[steps]]
index = 7
name = "The carpenter"
links = ["Carpenter", "willow log", "Holy symbol (Icthlarin's Little Helper)"]
text = """
Then, head to the city's eastern side to find the [[Carpenter]], who can be found directly East of the Southern pyramid. He needs a [[willow log]] to make a [[Holy symbol (Icthlarin's Little Helper)|holy symbol]]. Talk to him again to give him your willow log. After a short wait, the carpenter will give you the symbol.

'''Note:''' You can skip the "short wait" by turning in the bucket of sap, linen, and bag of salt to the Embalmer and then going back to the Carpenter to collect the holy symbol immediately.
"""

[[steps]]
index = 8
name = "The embalmer"
links = ["Embalmer", "High Priest (Sophanem)", "bucket of sap", "Linen (Icthlarin's Little Helper)", "bag of salt", "bucket of saltwater", "suntrap", "knife", "evergreen tree", "Raetul", "Sophanem"]
text = """
Talk to the [[Embalmer]] in the building south of the [[High Priest (Sophanem)|High Priest]], near the water symbol. He will ask for a [[bucket of sap]], [[Linen (Icthlarin's Little Helper)|linen]], and a [[bag of salt]]. Tell him you will get the items later. To get a pile of salt, use the [[bucket of saltwater]] on the [[suntrap]] east of the embalmer. A bucket of sap can be obtained by using a [[knife]] with an [[evergreen tree]] or a pointy regular wood tree with the description "A commonly found tree" while you have a bucket. If you didn't bring sap, you can get some from the latter kind around Lumbridge or the Grand Exchange. The [[Linen (Icthlarin's Little Helper)|linen]] can be bought from [[Raetul]] for 30 coins. He is located in the north-east part of [[Sophanem]], near the silk stall. '''Note:''' You will not be able to buy the Linen from him before you have spoken to the embalmer, as your player character will decline his offer.
"""

[[steps]]
index = 9
name = "Starting the ceremony"
links = ["High Priest (Sophanem)", "Klenter's Pyramid"]
text = """
The Carpenter or the Embalmer (whoever you helped last) will tell you that the [[High Priest (Sophanem)|High Priest]] began the ceremony without you. To find him, go back into the [[Klenter's Pyramid|pyramid]] past the traps and the pit. As you cross the pit, the third flashback will begin.
"""

[[steps]]
index = 10
name = "Third Flashback"
links = ["Unholy symbol (Icthlarin's Little Helper)", "Klenter's Pyramid"]
text = """
You will now have an [[Unholy symbol (Icthlarin's Little Helper)|unholy symbol]] in your inventory. Your character tells you that your mistress wants it inside the [[Klenter's Pyramid|pyramid]] so she can teleport there. Enter the east room and use the symbol on any sarcophagus around the walls. The flashback will end once you're done; if not, leave the room.
"""

[[steps]]
index = 11
name = "The ceremony"
links = ["Wanderer", "Possessed Priest", "Protect from Magic", "Attack potion", "Magic potion", "Agility potion", "defence potion", "High Priest (Sophanem)", "Hitpoints"]
text = """
[[File:Icthlarin's Little Helper - The ceremony.png|thumb|The ceremony started and the player was too late.]]
You will speak to yourself again showing your regret for causing harm to the town. Jump across the pit again and re-enter the eastern burial chamber. After a cutscene, you'll learn that the [[Wanderer]] was behind it. She is really the Devourer, an evil goddess, and she'll possess one of the priests.

You will fight a level 91 [[Possessed Priest]]. You can use [[Protect from Magic]] and kill him. Once you have dealt with him he drops a four-dose [[Attack potion|attack]], [[Magic potion|magic]], [[Agility potion|agility]], or [[defence potion]] (Ironmen may wish to keep the agility potion if they plan on doing Tai Bwo Wannai Trio, should they receive it). Talk to the [[High Priest (Sophanem)|High Priest]] again, and he will tell you to meet them back above.

'''Note:''' If you take too long to defeat him, the message "''The priest seems to have recovered from the Devourers spell''" will appear, and you will have to exit the door and re-enter to face him again with full [[Hitpoints]].
"""

[[steps]]
index = 12
name = "Fourth Flashback"
links = ["Klenter's Pyramid", "Icthlarin"]
text = """
[[File:Icthlarin's Little Helper - Meeting Icthlarin.png|thumb|Icthlarin, god of the dead stops the player from stealing.]]
After talking to the High Priest, leave the room, and you will see the final flashback as a cut-scene. You will be escaping from the [[Klenter's Pyramid|pyramid]], and [[Icthlarin]], god of the dead, will dehypnotise you.
"""

[[steps]]
index = 13
name = "Finishing the quest"
links = ["High Priest (Sophanem)"]
text = """
You will find yourself outside the pyramid. Talk to the [[High Priest (Sophanem)|High Priest]] to complete the quest.

'''Congratulations, quest complete!'''
"""
