quest = "Family Pest"
step_count = 4

[[steps]]
index = 0
name = "Avan"
links = ["Avan", "Al Kharid mine", "Al Kharid", "Emir's Arena", "ring of dueling", "Family Crest"]
text = """
[[File:Avan chathead.png|left]]
[[Avan]] is located in the [[Al Kharid mine]], north of [[Al Kharid]]. He can be reached quickly by teleporting to the [[Emir's Arena]] via [[ring of dueling]], then running north-west.

Speak to Avan. You will ask if he needs help with anything, as you've had "a bit of spare time lately". He will say that everything is fantastic and thanks you for the perfect jewellery you obtained for him during [[Family Crest]]. You will then say that you have a LOT of spare time, and will help out with anything he can think of, but he refuses again.
"""

[[steps]]
index = 1
name = "Caleb"
links = ["Caleb", "Catherby", "Catherby Teleport", "lunar spellbook", "Camelot teleport"]
text = """
[[File:Caleb chathead.png|left]]
[[Caleb]] is located in [[Catherby]], in the building north-east of the bank. He can be quickly reached with a [[Catherby Teleport]] if players have access to the [[lunar spellbook]]. Otherwise, players can use [[Camelot teleport]] and run south-east, or south-west from the white wolf mountain gnome glider.

Speak to Caleb. You will say that you are ready to help with whatever he needs (again). You will daydream about what the family will reward you with, only catching the last bit of what he says, which is investigating a broken lamping stick. You will then ask for him to repeat his problem, as your mind was elsewhere, but this frustrates him and he asks you not to worry about it.
"""

[[steps]]
index = 2
name = "Johnathon"
links = ["Johnathon", "Jolly Boar Inn", "Varrock", "Lumberyard teleport", "Digsite pendant"]
text = """
[[File:Johnathon chathead.png|left]]
[[Johnathon]] is located upstairs in the [[Jolly Boar Inn]], north-east of [[Varrock]]. He can be quickly reached by using a [[Lumberyard teleport]] or [[Digsite pendant|Digsite pendant]], and running north-west.

He will excitedly ask for more help, in which he mentions a woman he loves is trapped in a tall tower, surrounded by a flying dragon. Ready to jump into action, you ask the location of the tower. It turns out, unfortunately, that he was joking.
"""

[[steps]]
index = 3
name = "Finishing up"
links = ["Dimintheis"]
text = """
As the sweet smell of great rewards fades almost completely, head back to [[Dimintheis]], who is happy to hear that his sons are doing well.

As you are about to leave, disappointed in the lack of help the family needs, Dimintheis suddenly remembers that he does indeed have something you can help him with: 500,000 coins. As they are supposedly a rich family, you ask him why he would need an exorbitant amount of money.

He will tell you that his family only pretends to be rich, and that they gave themselves a fancy surname. In addition, the gauntlets are not a family heirloom and that he asked the player to recover the family crest to appear wealthy.

Give him 500,000 coins. Miniquest complete!
"""
