#!/usr/bin/env python3
"""Generate the viewer-only prayer catalog from B237 object parameters."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from validate_b237_cache import parse_dump_file, parse_symbol_file

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from export_prayers import PRAYERS


def read_catalog(path: Path = ROOT / "rc-viewer/prayer_icons.inc") -> list[tuple]:
    rows = []
    for line in path.read_text().splitlines():
        if not line or line.startswith("//"):
            continue
        match = re.fullmatch(r'PRAYER_ICON\((\d+), (".*"), (\d+), (\d+), (".*")\)', line)
        if not match:
            raise ValueError(f"invalid prayer icon row: {line}")
        rows.append((int(match[1]), json.loads(match[2]), int(match[3]),
                     int(match[4]), json.loads(match[5])))
    if len(rows) != len(PRAYERS) or [r[0] for r in rows] != list(range(len(PRAYERS))):
        raise ValueError("prayer catalog must cover every gameplay definition in order")
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dump", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=ROOT / "rc-viewer/prayer_icons.inc")
    args = parser.parse_args()
    graphics = {name: number for number, name in
                parse_symbol_file(args.dump / "symbols/graphic.sym").items()}
    enums = parse_dump_file(args.dump / "config/dump.enum")
    standard = {value.split(",", 1)[1] for book in (4956, 3341, 3342, 3343)
                for value in enums[book].fields["val"]}
    by_name = {}
    for obj in parse_dump_file(args.dump / "config/dump.obj").values():
        if obj.symbol not in standard:
            continue
        params = dict(p.split(",", 1) for p in obj.fields.get("param", []))
        if "param_1752" in params:
            name = params["param_1752"]
            if name in by_name:
                raise ValueError(f"duplicate prayer object: {name}")
            by_name[name] = params
    # B237 headicons_prayer frames; these are presentation mappings only.
    overheads = {"Protect from Melee": 0, "Protect from Missiles": 1,
                 "Protect from Magic": 2, "Retribution": 3,
                 "Smite": 4, "Redemption": 5}
    lines = ["// B237 params 1752/1756/1757; generated by export_prayer_icons.py."]
    for i, prayer in enumerate(PRAYERS):
        name = prayer["name"]
        params = by_name[name]
        on = graphics[params["param_1757"].strip('"')]
        off = graphics[params["param_1756"].strip('"')]
        overhead = f"headicons_prayer_{overheads[name]}" if name in overheads else ""
        lines.append(f"PRAYER_ICON({i}, {json.dumps(name)}, {on}, {off}, {json.dumps(overhead)})")
    args.output.write_text("\n".join(lines) + "\n")
    read_catalog(args.output)
    print(f"wrote {len(PRAYERS)} prayer icons to {args.output}")


if __name__ == "__main__":
    main()
