#!/usr/bin/env python3
"""Refresh the viewer's B237 spell/icon catalog from maintainer dump inputs."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from validate_b237_cache import parse_dump_file, parse_symbol_file

ROOT = Path(__file__).resolve().parents[2]


def read_catalog(path: Path = ROOT / "rc-viewer/spell_icons.inc") -> list[tuple[int, str, int]]:
    rows = []
    for line in path.read_text().splitlines():
        if not line or line.startswith("//"):
            continue
        match = re.fullmatch(r'SPELL_ICON\(([0-3]), (".*"), (\d+)\)', line)
        if not match:
            raise ValueError(f"invalid spell icon row: {line}")
        rows.append((int(match[1]), json.loads(match[2]), int(match[3])))
    if not rows:
        raise ValueError("empty spell icon catalog")
    return rows


def spell_icons(dump: Path) -> list[tuple[int, str, int, int]]:
    graphics = {name: number for number, name in
                parse_symbol_file(dump / "symbols/graphic.sym").items()}
    objects = parse_dump_file(dump / "config/dump.obj")
    enums = parse_dump_file(dump / "config/dump.enum")
    by_symbol = {obj.symbol: obj for obj in objects.values()}
    result = []
    for book in range(4):
        symbols = [value.split(",", 1)[1]
                   for value in enums[1982 + book].fields["val"]]
        # Keep the individual jewellery enchantments available without a submenu.
        if book == 0:
            symbols += [obj.symbol for obj in objects.values()
                        if any(p.startswith("param_601,Lvl-") for p in obj.fields.get("param", []))]
        seen = set()
        for symbol in symbols:
            params = dict(p.split(",", 1) for p in by_symbol[symbol].fields["param"])
            name = params["param_601"]
            if name in seen:
                raise ValueError(f"duplicate spell in book {book}: {name}")
            seen.add(name)
            sprite = graphics[params["param_599"].strip('"')]
            level = int(params.get("param_604", "0"))
            result.append((book, name, sprite, level))
    return sorted(result, key=lambda row: (row[0], row[3]))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dump", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=ROOT / "rc-viewer/spell_icons.inc")
    args = parser.parse_args()
    rows = spell_icons(args.dump)
    args.output.write_text("// B237 spell params 601/599 and spellbook enums 1982..1985.\n"
        "// Generated by tools/cache_pipeline/export_spell_icons.py; no runtime dump dependency.\n"
        + "".join(f"SPELL_ICON({book}, {json.dumps(name)}, {sprite})\n"
                  for book, name, sprite, _level in rows))
    print(f"wrote {len(rows)} spell icons to {args.output}")


if __name__ == "__main__":
    main()
