quest = "Prying Times"
step_count = 2

[[steps]]
index = 0
name = "Starting off"
links = ["Captain's log", "coins", "ring of charos(a)", "Port Sarim", "The Pandemonium", "captain's log", "charter ship", "'Squawking' Steve Beanie", "The Pandemonium (Pub)", "crate of looty", "ledger table", "Crate of pirate looty", "Junior Jim"]
text = """
[[File:Prying_Times_task_in_Captain's_log.png|right|thumb|The task as it appears in the captain's log|250px]]
{{Needed|[[Captain's log]]|recommended=60 [[coins]] ''or'' [[ring of charos(a)]] for a charter ship from [[Port Sarim]] to [[The Pandemonium]] and back}}
[[File:'Squawking' Steve Beanie chathead.png|left|frameless]]
Make sure you have at least one task slot open and the [[captain's log]] in your inventory, then make your way to [[The Pandemonium]]. You can save some time in this section by leaving your boat docked at [[Port Sarim]], taking a [[charter ship]] to [[The Pandemonium]], then returning to Port Sarim via charter ship after Steve gives you the task.
Speak to [['Squawking' Steve Beanie]] in [[The Pandemonium (Pub)|The Pandemonium Pub]] and ask if he has heard any word from Old Grog. Old Grog hasn't returned yet, but in the meantime Steve wants you to collect some precious pirate looty from [[Port Sarim]]. Steve will add a Port Task to your [[captain's log]].

Travel to the [[Port Sarim]] dock and take the [[crate of looty]] from the [[ledger table]], then board your vessel and deposit the crate into the cargo hold. Sail south, back to [[The Pandemonium]], dock your boat, withdraw the [[Crate of pirate looty|crate of looty]] from the cargo hold, and disembark the vessel. Deposit the crate at the ledger table on The Pandemonium docks. Return to Steve, and tell him you delivered the cargo, and he'll encourage you to find a "special key" to open the crate. Pick up a hammer from the crate next to [[Junior Jim]] if you didn't bring one.{{Map|align=right|height=200|width=200|zoom=2|mtype=square|x=3014|y=2999|r=1|stroke=#FF0000|caption=Sealed Crate Location}}
"""

[[steps]]
index = 1
name = "Key findings"
links = ["redberry pie", "steel bar", "hammer", "coins", "ring of charos(a)", "The Pandemonium", "Port Sarim", "Thurgo", "anvil", "sealed crate", "bottle of fish bladder stout", "drink troll"]
text = """
{{Needed|[[redberry pie]], [[steel bar]], [[hammer]]|recommended=60 [[coins]] ''or'' [[ring of charos(a)]] for a charter ship from [[The Pandemonium]] to [[Port Sarim]] and back}}
[[File:Thurgo chathead.png|left]][[File:Prying Times - Drink Troll.png|thumb|The result of the grog.|width=280x280]]Travel to [[Thurgo]], in his hut with the [[anvil]] south of Port Sarim. Ask for help with the key; he'll say he needs a steel bar, a hammer, and a redberry pie, which he'll use to make a crowbar. Give him the items, then return to [[The Pandemonium]].

Return to the pub and talk to Steve about the "special key," and he'll ask you to test it out on another crate before using it on his precious pirate looty. Return to the docks to board your vessel, then sail to the north-west island off of The Pandemonium to find a [[sealed crate]]. From your vessel, pry open the sealed crate to find a [[bottle of fish bladder stout]]. '''If you want to skip the following fight, return to the buoys before drinking it'''. Drink the stout and either defeat the [[drink troll]] that spawns or disembark to despawn it, then return to The Pandemonium and talk to Steve for the final time. Open the crate behind Steve to finish the quest.

::::'''Congratulations, quest complete!'''
[[File:Steve's Locked Crate.png|thumb|Steve's Locked Crate|left|250px]]
{{Clear}}
"""
