quest = "Fight Arena"
step_count = 3

[[steps]]
index = 0
name = "Kidnapping"
links = ["Ardougne Monastery", "Lady Servil", "Tree Gnome Village (location)", "General Khazard", "Khazard armour", "drop trick"]
text = """
{{Needed|recommended=Combat equipment, preferably Ranged or Magic to utilise safespots}}
{{Map|2566,3199|align=left|r=5|height=240|width=240|mtype=square|caption=Location of quest start.}}
[[File:Lady Servil chathead.png|left]]
Head just south-west of the [[Ardougne Monastery]] and talk to [[Lady Servil]] by the north-east corner of the [[Tree Gnome Village (location)|Tree Gnome Village]] maze. She will explain that her family has been kidnapped by [[General Khazard]] and his group of mercenaries and forced to fight in their arena. The player will agree to help rescue them.

{{Map|2613,3190|mtype=pin|align=right|height=220|width=220|caption=The location of the suit of armour containing the [[Khazard armour|armour]].}}
[[File:Fight Arena - Khazard armour chest.png|thumb|220px|The chest containing the [[Khazard armour|armour]].]]
Head east to a group of buildings located south of the [[Ardougne Monastery]]. In the most north-eastern house, search the chest to obtain [[Khazard armour]]. Equip both pieces and head south to the prison, which forms the south and east boundaries of the arena.

'''Note:''' Multiple sets of armour may be obtained using the [[drop trick]].

The guards will only let you into the prison wearing the Khazard armour. Once inside, do not remove it, or the guards will not speak to you. You can wear anything in any of the other slots.
"""

[[steps]]
index = 1
name = "Staging a breakout"
links = ["Sammy Servil", "Khazard cell keys", "Khali brew", "Khazard barman", "coins", "combat", "equipment", "safespottable", "Justin Servil", "Khazard ogre"]
text = """
{{Needed|5 coins}}
[[File:Khazard Guard chathead.png|left]]
[[Sammy Servil]] (the boy in the purple shirt) is located in the northernmost cell of the east wing of the prison. Ask him where the [[Khazard cell keys|cell keys]] are, and he will explain the Head Guard has them.

Head to the south-eastern corner of the jail and talk to the Head Guard by the staircase. He will mention his cravings for [[Khali brew]] and let it slip that last time he had too many, he fell asleep on the job.

Head to the bar found west of the western entrance to the jail, and purchase [[Khali brew]] from the [[Khazard barman]] for five [[coins]]. '''If there is no option to, you must finish the dialogue with the head guard.'''

Return to the head guard and give him the brew, and he will quickly get drunk, handing the player the keys when asked.

Ensure you have your [[combat]] [[equipment]] and prepare for three enemies you must fight in a row (all [[safespottable]]).

Use the keys on Sammy's prison door to free him and a cutscene will begin, in which Sammy enters the main arena in search of his father [[Justin Servil|Justin]], who is being attacked by a [[Khazard ogre]].
"""

[[steps]]
index = 2
name = "The fights"
links = ["dwarven multicannon", "Khazard Guard", "Khazard Ogre", "safespot", "Magic", "Ranged", "halberd", "Protect from Melee", "General Khazard", "Hengrad", "Khazard scorpion", "Bouncer", "Lady Servil"]
text = """
{{Instance}}

'''Note''': The [[dwarven multicannon]] cannot be set up in the arena.

'''Note:''' Throughout the fights, you may teleport out if you run into trouble. Speaking to the [[Khazard Guard]] by the door of the prison will take you back into the arena.

[[File:General Khazard chathead.png|left]]
You must kill the level 63 [[Khazard Ogre]] attacking Sammy's father. There is a very easy [[safespot]]
behind a nearby skeleton, whereby you may use [[Magic]], [[Ranged]] or a [[halberd]] for an easy fight. All of the following enemies use melee, so you can alternately use [[Protect from Melee]].

'''Note''': If a fight sequence does not initiate, speak to Justin in order to continue, '''but note that if the ogre has already spawned, a second one will appear if you talk to Justin.'''

After defeating the ogre, [[General Khazard]] will appear and order his guards to lock you away after suggesting that if you fight in his arena, he might let the Servils go.

Talk to your cellmate [[Hengrad]], and after a brief conversation the guard will bring you back to the arena.

The second fight is with a level 44 non poisonous [[Khazard scorpion]]. Note that it will reach you quickly, so you should immediately run to the same safespot or activate [[Protect from Melee]].

[[File:Fight Arena - Fighting General Khazard.png|thumb|right|Fighting [[General Khazard]] with [[Magic]] using the [[safespot]].]]
After defeating the scorpion, Khazard will release [[Bouncer]] the level 137 hellhound. You will need high healing food if not using the safespot or [[Protect from Melee]] at a low level, but otherwise the strategy is the same.

After killing the hellhound, a level 142 [[General Khazard]] will vow to make you pay for killing his puppy, and then attack you. '''This fight is optional''', and the quest progresses the same if you leave now via the door (use its Quick-escape option to avoid needing to confirm you wish to leave). The same strategies as before are effective against the general.

Return to [[Lady Servil]] and she will tell you that her son and husband are safe and recovering at home.

'''Congratulations, quest complete!'''
"""
