quest = "Mage Arena II"
step_count = 9

[[steps]]
index = 0
name = "Starting out"
links = ["Mage Arena", "Wilderness", "knife", "slash weapon", "Kolodion", "god cape", "gods", "Saradomin", "Zamorak", "Guthix", "enchanted symbol", "enchanted key", "strange device"]
text = """
Head to the broken down house north-west of the [[Mage Arena]] in level 55 [[Wilderness]]. Use a [[knife]] or [[slash weapon]] to cut down the two webs in the house. Once the webs have been cut, pull the lever on the wall to be teleported into a small cave. The cave is a '''safe zone'''; you cannot be attacked by other players inside here.

Speak to [[Kolodion]] about additional challenges. He will tell you that he has been working on a spell that will increase the powers given by your [[god cape]], but the components he requires are difficult for him to obtain. As the spell imbues the power of the three [[gods]], namely [[Saradomin]], [[Zamorak]], and [[Guthix]], he requires the components of three powerful opponents who are each aligned to a god. You will then receive the [[enchanted symbol]]. This acts similar to the [[enchanted key]] and [[strange device]].
"""

[[steps]]
index = 1
name = "Tracking"
links = ["Options", "skulled", "enchanted symbol", "Wilderness", "Lava Dragon Isle", "multi-combat", "Treasure Trails/Guide/Hot Cold", "Treasure Trails", "World switching"]
text = """
<!-- this isn't using the regular map template because it's not really possible to do multiple different boundaries in the same map with it, the "geojson" stuff is hugely bloating so is in mapspace and transcluded here-->
{{Map:God followers spawn locations}}

Before tracking down the followers, it is '''highly recommended''' to set the Player 'Attack' option to "Always right-click" or "Hidden" in the ''Controls'' panel in the [[Options]] interface, as well as enabling "PK Skull Prevention", so you do not accidentally become [[skulled]].

After you have received the [[enchanted symbol]], you can look for the three god followers located within the deep [[Wilderness]], around [[Lava Dragon Isle]]. Most areas will be in [[multi-combat]] zones, so stay cautious! Each use of the symbol can deal up to 16 damage, and can kill the player.

The three god followers can be tracked in any order, as you choose the follower to track with each use of the symbol. Once a follower is defeated, the symbol will no longer track that follower until the miniquest is complete.

The symbol functions similarly to the [[Treasure Trails/Guide/Hot Cold|Hot & Cold]] from Master [[Treasure Trails]]; as the player gets closer to where the follower is residing, the symbol will glow hotter, and the farther you are, the colder it gets.

When the symbol states that it is visibly shaking, the follower will appear and attack you. Since you may run out of food most of the time searching for the followers, try to pinpoint their exact location before returning to a bank to restock on food.

The followers' spawn locations are random and change approximately every 45 minutes. The 45-minute rotation timer only progresses while the player is inside the Wilderness; time spent outside the Wilderness does not count. Spawn rotations are unique for each player, and the player will be notified of a rotation when using the enchanted symbol after the change.

If a follower has already spawned in the location where yours is supposed to spawn, you must either [[World switching|hop worlds]] or wait for it to despawn and use the enchanted symbol again. The currently active follower locations are the same between worlds.
{{clear}}
"""

[[steps]]
index = 2
name = "The followers"
links = ["God spell", "Ice Barrage", "Tele Block", "staff of the dead", "Toxic staff of the dead", "staff of light", "staff of balance", "void knight mace", "Flames of Zamorak", "Saradomin Strike", "Claws of Guthix", "Porazdir", "Justiciar Zachariah", "Derwen"]
text = """
The followers are very powerful monsters, using powered up versions of their respective [[God spell|god spells]] along with powerful melee attacks. All followers can hit up to 43 (26 for Zachariah) with magic, and up to 16 damage (43 for Zachariah) with melee. Protection prayers reduce the accuracy and strength of their attacks.

They can also cast [[Ice Barrage]] and [[Tele Block]]. It is possible to dodge the Ice Barrage attack by stepping off the square you were standing on when the spell was cast. Unlike other players' Tele Block, this only lasts for a minute if Protect from Magic is used, rather than two minutes. The Tele Block effect fades immediately upon killing the monster.

In addition, the followers can only be harmed by their respective god spells, so you must use all three god staves for each of the three followers. Alternatively, using the [[staff of the dead]] (or its [[Toxic staff of the dead|toxic variant]]), the [[staff of light]], or the [[staff of balance]]/[[void knight mace]] to autocast [[Flames of Zamorak]], [[Saradomin Strike]], and [[Claws of Guthix]], respectively, is recommended, as their magic attack bonuses are higher in addition to making the fight slightly easier by allowing the player to autocast god spells.

Each follower also has their own unique ability, making the fight slightly more challenging:

*[[Porazdir]] can launch an energy ball at the player that can hit through protection prayers. The amount of damage it deals is dependent on your distance to him. The farther you are, the less damage it deals. Near him it can hit up to 30, but if the player is at least 12 tiles away from him it will hit 0.
*[[Justiciar Zachariah]] will occasionally swing his sword, resulting in a blue wave aimed at the player's current tile when it was used. If the player does not move, it drags them to melee distance and binds them in place, where he will also perform melee attacks. Simply move one tile elsewhere from its target tile to avoid the attack.
*[[Derwen]] can launch energy balls on the ground. They heal him for 5 health every few seconds, and must be destroyed to stop him from healing. Each ball has 20 health. Claws of Guthix is not required to damage or destroy the orbs.
<gallery captionalign="center" widths="180">
Fighting Porazdir.png|A player fighting Porazdir, one of Zamorak's most trusted generals.
Fighting Justiciar Zachariah.png|A player fighting Zachariah, one of the last remaining justiciars of Saradomin.
Fighting Derwen.png|A player fighting Derwen, an ancient servant of Guthix.
</gallery>
"""

[[steps]]
index = 3
name = "Locating the followers"
links = ["enchanted symbol", "wine", "slash weapon", "energy potions", "Wilderness", "amulet of glory", "royal seed pod", "Slayer ring", "Ferox Enclave", "Pool of Refreshment", "stats", "prayers", "HP", "stamina", "imbued heart", "Edgeville", "Kolodion", "Wilderness lever", "knife"]
text = """
The safest method is to do the following for each follower:

1. '''Locate''' a follower using the [[enchanted symbol]] while consuming a cheap food source such as [[wine]] when the symbol deals damage. Bring a [[slash weapon]] to break through webs, [[energy potions]], wine, and a level 30 teleport out of the [[Wilderness]], such as an [[amulet of glory]], [[royal seed pod]], or [[Slayer ring]]. Make note of the location, as you will need to return to it once geared up and restocked on food.

2. '''Leave''' and use the [[Ferox Enclave]] [[Pool of Refreshment]] to reset [[stats]], [[prayers]], and [[HP]]. Next, gear up. This is the ideal time to use stat-boosting potions, cast boost spells, consume overheals, drink a [[stamina]] dose, or use (and bank) an [[imbued heart]].

3. '''Return''' to the location and kill the follower. Take the remains, teleport away, bank your gear, and go to [[Edgeville]]. Note that the remains themselves cannot be banked.

4. '''Hand in''' the follower's remains to [[Kolodion]]. The Edgeville [[Wilderness lever]] teleports you just east of the building with the lever. A '''[[knife]] or a slash weapon is needed''' to break the two webs leading to the Arena bank.

5. '''Repeat''' for the other two.
"""

[[steps]]
index = 4
name = "Killing the followers"
links = ["player killers", "magic gear", "black dragonhide armour", "magic robes", "Magic"]
text = """
As there's a risk of [[player killers]], it's a good strategy to take as few valuable items as possible.

If the followers are not slain quick enough, they will despawn, and you will have to track it again and restart the fight. It's important to kill them quickly and efficiently, and the appropriate tools and gear must be used. The example equipment here shows a viable low-cost [[magic gear]]. Although the followers have a somewhat high Magic level, this is offset with extremely poor magical defence, so it may make sense to opt for a defensive gear, such as [[black dragonhide armour]] instead of [[magic robes]], especially if your [[Magic]] level is high.
"""

[[steps]]
index = 5
name = "=Inventory="
links = ["Stamina potion", "Energy potion", "Saradomin brew", "Super restore", "sharks", "Enchanted symbol", "knife", "slash weapon", "god spell", "Derwen", "Ring of recoil", "royal seed pod", "amulet of glory", "Wilderness", "antipoison", "Poison spider", "Blighted"]
text = """
{{Inventory|align=right
|1= Stamina_potion%281%29
|2= Blighted super restore(4)
|3= Saradomin brew(4)
|4= Energy potion(4)
|5= Energy potion(4)
|6= Enchanted symbol
|7= Blood rune
|8= Fire rune
|9= Air rune
|10= Ring of recoil
|11=
|12= Wilderness sword 1
|13= Blighted manta ray
|14= Blighted manta ray
|15= Blighted manta ray
|16= Blighted manta ray
|17= Blighted manta ray
|18= Blighted manta ray
|19= Blighted manta ray
|20= Blighted manta ray
|21= Blighted manta ray
|22= Blighted manta ray
|23= Blighted manta ray
|24= Blighted manta ray
|25= Blighted manta ray
|26= Blighted manta ray
|27= Blighted manta ray
|28= Royal seed pod
}}
Your inventory should contain:
*[[Stamina potion]] and/or [[Energy potion]]s
*[[Saradomin brew]]s
*[[Super restore]]s
*Food ([[sharks]] or better recommended).
*[[Enchanted symbol]]
*A [[knife]] or a [[slash weapon]] (if the target is behind a spider webbed area)
*50+ casts of the appropriate [[god spell]] (more for [[Derwen]])
*
*[[Ring of recoil]] (with one already equipped)
*An escape teleport. This can be a [[royal seed pod]] or an [[amulet of glory]], as both work at level 30 [[Wilderness]].
*An [[antipoison]] may be needed for some of the locations. Although the god followers do not inflict poison, [[Poison spider|poison spiders]] may roam in the vicinity of said locations.
[[Blighted|Blighted supplies]] can be used, and are often significantly cheaper than their standard counterparts.
"""

[[steps]]
index = 6
name = "=Equipment="
links = ["Protect from Magic", "dragonhide armour", "Culinaromancer's gloves", "book of darkness", "dragonhide shield", "god cape", "Magic", "Charge", "Ancient brew", "super magic potion", "Nightmare Zone", "Wilderness", "occult necklace", "tormented bracelet", "black demon", "Slayer task", "Slayer helmet (i)", "Porazdir", "rings of recoil", "Auto Retaliate"]
text = """
{{Equipment
| align = right
| head = Red hat
| cape = Saradomin cape
| neck = Amulet of magic
| ammo = Rada's blessing 2
| weapon = Saradomin staff
| torso = Black d'hide body
| legs = Black d'hide chaps
| shield = Black d'hide shield
| gloves = Rune gloves
| boots = Mystic boots
| ring = Ring of recoil
| caption = Low-risk gear
}}

Even with [[Protect from Magic]], they will still hit hard and accurately, up to 20+. However, their magical defence is extremely weak and not a lot of accuracy is needed to hit on them consistently. Thus, it is recommended to wear [[dragonhide armour]], along with easily replaceable items, such as the [[Culinaromancer's gloves]], the [[book of darkness]] or a [[dragonhide shield]], and a [[god cape]].

At level 80 [[Magic]], casting [[Charge]] will increase the max hit of your god spells from 20 to 30. As Charge lasts for seven minutes, you may choose to cast it before gearing up to start the fight. Boosts such as the [[Ancient brew]] may be used to reach the level requirement. If you need a boost larger than 5, you may use a [[super magic potion]] within a practice dream at the [[Nightmare Zone]] and cast Charge there before heading to the [[Wilderness]].

If possible, use an [[occult necklace]] and [[tormented bracelet]] for their magic damage boost to increase max hits.

If players are assigned a [[black demon]] for their [[Slayer task]], wearing a [[Slayer helmet (i)]] is recommended when fighting [[Porazdir]], as the player's attacks would be more accurate.

Because of the high damage dealt by them, taking at least two [[rings of recoil]] gives 80 free damage over the course of the fight, which can be very helpful.

It is recommended to turn off [[Auto Retaliate]] for all the fights.
"""

[[steps]]
index = 7
name = "=Prayer="
links = ["Protect from Magic", "Protect Item", "prayer points", "Prayer", "Mystic Lore"]
text = """
Use [[Protect from Magic]] and [[Protect Item]]. If [[prayer points]] can be spared (75+ [[Prayer]]), it's also an option to enable a cheap magic accuracy prayer, such as [[Mystic Lore]].
"""

[[steps]]
index = 8
name = "Finishing up"
links = ["Justiciar Zachariah", "Porazdir", "Derwen", "Justiciar's hand", "demon's heart", "ent's roots", "Kolodion"]
text = """
Upon killing [[Justiciar Zachariah]], [[Porazdir]], and [[Derwen]], they'll drop a [[Justiciar's hand]], [[demon's heart]], and [[ent's roots]], respectively. Once you obtain one, run back to [[Kolodion]] so that he can hold it for safekeeping. If your supplies are low, it's best to teleport back to a safe location and restock on food and potions before giving the component to Kolodion. If you're killed, you'll have to kill the follower again.
"""
