quest = "Merlin's Crystal"
step_count = 10

[[steps]]
index = 0
name = "Merlin's predicament"
links = ["Camelot", "Seers' Village", "King Arthur", "Merlin"]
text = """
[[File:King Arthur chathead.png|left]]
{{map|width=250|height=250|align=right|zoom=2|x=2759|y=3500|caption=
{{legend|#F0FF00|caption=King Arthur}}
{{legend|#00FF00|caption=Sir Gawain}}
|mtype:pin,icon:yellowPin,2764:3515
|mtype:pin,2763:3506
|mtype:text,class:,label:Camelot<br>Castle,2759:3484
}}
Head to [[Camelot]], east of [[Seers' Village]]. Ask [[King Arthur]] if you can join the Knights of the Round Table, and he'll suggest you complete a quest first to prove yourself; [[Merlin]] has been found trapped in a crystal. He wants you to ask the other knights for ideas on how to rescue him.
{{Clear|left}}
"""

[[steps]]
index = 1
name = "Gathering information"
links = ["Sir Gawain", "Morgan Le Faye", "Keep Le Faye", "Mordred", "Sir Lancelot", "Catherby"]
text = """
[[File:Sir Gawain chathead.png|left|frameless]]
Speak to [[Sir Gawain]], found either within the castle or roaming in the courtyard. Ask him how Merlin got trapped, and he will suspect it to be the work of [[Morgan Le Faye]]. However, he does not know how to get into her [[Keep Le Faye|keep]], which is guarded by [[Mordred]] and his group of renegade knights.

Next, talk to [[Sir Lancelot]] on the {{FloorNumber|uk=1}}. Ask him if he has any ideas on how to get into the keep. He will mention that there is a sea entrance to the keep, and that the knights get all of their deliveries by boat from [[Catherby]].
{{Clear|left}}
"""

[[steps]]
index = 2
name = "Infiltrating the keep"
links = ["Catherby", "bucket of wax", "insect repellent", "Perdu", "Candle Shop", "Keep Le Faye"]
text = """
{{Needed|recommended=Combat equipment, food}}

Now that you have a lead, follow the road south-east to [[Catherby]]. If you do not already have a [[bucket of wax]], pick up the nearby [[insect repellent]] for use later, which can be found on a table in the house containing [[Perdu]] just north of the bank. Ensure you have your combat equipment, then head just north of the dock between the bank and the [[Candle Shop]], where you'll find a few crates against the back of the shop. Click on them to hide inside. There will be a bit of dialogue as workers come to pack you up and put you in the boat. After a while, you'll end up in the [[Keep Le Faye]]; when prompted, choose yes to climb out.
"""

[[steps]]
index = 3
name = "Defeating Mordred"
links = ["renegade knight", "Sir Mordred", "Morgan Le Faye", "Excalibur"]
text = """
[[File:Merlin's Crystal - Fighting Sir Mordred.png|thumb|220px|Fighting Sir Mordred.]]
[[File:Sir Mordred chathead.png|left|frameless]]
Head up the stairs to the top floor, ignoring the [[renegade knight]]s that are wandering around the castle. You should find [[Sir Mordred]] (level 39); fight him, and just as you are about to defeat him, [[Morgan Le Faye]] will appear and beg for her sons life. '''Do not select the option to kill him or interrupt the conversation, or you'll need to fight Mordred again. Running out of Prayer will interrupt it.'''

Agree to spare him in return for information on how to untrap Merlin, and she will tell you that you will need a magic symbol, bat bones, and a black candle, in order to summon a mighty spirit. You'll need to bind the spirit with magic words, and then obtain the sword [[Excalibur]] to finally shatter the crystal.
{{Clear|left}}
"""

[[steps]]
index = 4
name = "Obtaining the items"
links = ["bread", "bat bones", "bucket of wax"]
text = """
{{Needed|[[bread]], [[bat bones]] (obtainable below), [[bucket of wax]] (obtainable below)|recommended=Fast travel method to Taverley, Port Sarim, Varrock and Camelot for subsequent sections}}
"""

[[steps]]
index = 5
name = "=Bat bones="
links = ["bat bones", "giant bat"]
text = """
If you did not bring [[bat bones]], you can obtain some by descending the stairs to the {{FloorNumber|uk=0}} and leaving through the doors, then killing the [[giant bat]]s around the keep.

:'''Note:''' Upon leaving the keep, you will only be able to return through the Catherby crates.
"""

[[steps]]
index = 6
name = "=Black candle="
links = ["black candle", "bucket of wax", "candle maker", "Catherby", "insect repellent", "Beekeeper's outfit"]
text = """
The [[black candle]] can be obtained by bringing a [[bucket of wax]] to the [[candle maker]] in [[Catherby]], located in his house west of the bank. Ask him about black candles, then talk to him again to give him the wax.

If you do not yet have a [[bucket of wax]], head to the fenced-in area north of the keep, by the flax field. Pick up a bucket by the gate. If you have [[insect repellent]], use it on one of the beehives, then use the bucket on the beehive to obtain your bucket of wax. If you wear the [[Beekeeper's outfit]], you can simply click the beehive with the bucket in your inventory, without needing to use insect repellant.
"""

[[steps]]
index = 7
name = "=Excalibur="
links = ["Bread", "The Lady of the Lake", "Taverley", "Hot Air Balloon", "Port Sarim", "Grum's Gold Exchange", "bread dough", "cooking range", "pot of flour", "Wydin's Food Store", "Trader crewmember", "magic shop", "X Marks the Spot", "Veos", "Port Piscarilius", "Kourend Castle Baker's Stall.", "Excalibur"]
text = """
{{Needed|[[Bread]]}}
[[File:Merlin's Crystal - Lady of the Lake.png|thumb|180px|The Lady of the Lake]]
[[File:The Lady of the Lake chathead.png|left|frameless|80px]]
The sword is kept by [[The Lady of the Lake]], found by the lake within [[Taverley]], in the peninsula just south of the [[Hot Air Balloon]]. Tell her you seek Excalibur, and she will say that she will only give it to one who is worthy and good. She has set a test for you; she wants you to first enter the [[Port Sarim]] [[Grum's Gold Exchange|Jeweller's shop]].

Head to [[Port Sarim]]. If you don't have any bread, you can make [[bread dough]] on the [[cooking range]] just south of the Jeweller's shop. Purchase a [[pot of flour]] from [[Wydin's Food Store]], a bucket from the [[Trader crewmember]]'s on the southernmost dock, fill it at the sink east of the [[magic shop]], then use it on the flour to make [[bread dough]] for cooking. Alternately, if you have completed [[X Marks the Spot]], you can travel via [[Veos]] to [[Port Piscarilius]], and head west to the [[Kourend Castle Baker's Stall.]] to purchase some bread.

Open the door to the jeweller's shop and a beggar will approach, asking for food to feed his starving family. Give him the loaf of bread. When you do, he will change into the Lady of the Lake, who gives you [[Excalibur]] for passing the test. '''You must finish this dialogue or you will need another piece of bread to repeat it.'''

{{clear|left}}
"""

[[steps]]
index = 8
name = "Chaos altar inscription"
links = ["Zamorak", "Varrock"]
text = """
{{Map|mtype=pin|3258,3381|align=right|caption=Location of the inscription.|width=200|height=200}}
[[File:Chaos altar.png|100px|frameless|left]]Finally, you will need the magic words for the spell. Head to the [[Zamorak]] chaos temple in the south-east corner of [[Varrock]]. "Check" the altar to find the words needed: ''Snarthon Candtrick Termanto''. '''Finishing this dialogue is required to progress further.'''
"""

[[steps]]
index = 9
name = "Breaking the Crystal"
links = ["Excalibur", "black candle", "tinderbox", "bat bones", "Camelot", "Thrantax the Mighty", "Merlin", "Camelot Castle", "King Arthur"]
text = """
{{Needed|[[Excalibur]], [[black candle]], [[tinderbox]], [[bat bones]]}}
[[File:Merlin's Crystal - Thrantax the Mighty.png|thumb|left|220px|Summoning Thrantax.]]
Now that you have all the required items and the magic words, return to [[Camelot]], where you will find the magical symbol on the north-east side of the castle's garden, just inside the fence. Light your black candle and '''drop''' the bat bones in the circle ('''DO NOT BURY THEM'''). A demonic spirit named [[Thrantax the Mighty]] will appear, and you will be presented with a sequence of words. The correct incantation is "'''Snarthon Candtrick Termanto'''". If you get it right, the spirit will obey you.

:'''{{Colour|red|Warning}}:''' If you recite the wrong phrase, the spirit will attack you, and you will have to get a new black candle and try again. Be careful as the spirit is  level 92, with a max hit of 10, and can hit rather accurately.

Once under your control, the spirit will offer a boon, which the player uses to make the request to free [[Merlin]]. After granting your boon, he will disappear. Head into [[Camelot Castle]], and climb up the south-east ladder to the very top of the south-east tower, where [[Merlin]] is imprisoned in a blue crystal. Use [[Excalibur]] on the crystal, and it will shatter.

Head back down and talk to [[King Arthur]], who will dub the player an honorary Knight Of The Round Table.

'''Congratulations, quest complete!'''
"""
