quest = "Mage Arena I"
step_count = 2

[[steps]]
index = 0
name = "Getting to the Mage Arena"
links = ["Wilderness", "knife", "sword", "Edgeville", "West Ardougne", "Deserted Keep", "Mage Arena", "weapon", "slash", "attack style", "lever (Mage Arena)", "PKers", "Lundail's Arena-side Rune Shop", "bank", "Kolodion", "non-player character"]
text = """
Head out into level 56 [[Wilderness]] to start, but watch out for player-killers. The arena has a bank, so there is no need to bring any equipment besides a [[knife]], [[sword]], or other slashing weapon. The quickest way to get there is by use of the lever in the ruins of [[Edgeville]] or in the small building near the gate to [[West Ardougne]]. Pulling either of these levers will teleport you to the [[Deserted Keep]], a small island surrounded by lava in level 54 Wilderness. From there, run north, slash the web with your [[knife]], [[sword]], or other slashing weapon, and then proceed west a short distance to the northern entrance of the [[Mage Arena]].

North-west of the actual Mage Arena is a little broken down house. Use a [[knife]] or a [[weapon]] which has the '[[slash]]' [[attack style]] to cut down the webs in the house. Once the two webs have been cut, pull the [[lever (Mage Arena)|lever]] on the wall of the house to be teleported into a small cave. While you are in this first room, you are completely safe from [[PKers]]. In here is a [[Lundail's Arena-side Rune Shop|rune store]], a [[bank]], and [[Kolodion]], the [[non-player character]] who must be talked to in order to start the Mage Arena miniquest. Kolodion will also be fought during the miniquest, so just talk to him to begin. After a long dialogue, you will fight him.
"""

[[steps]]
index = 1
name = "Battling Kolodion"
links = ["Kolodion", "Magic", "ogre", "Melee", "Protect from Magic", "prayer", "Ice spider", "ghost", "black demon", "spell", "Hitpoints", "Prayer", "food", "Blast spells", "Wave spells", "Iban Blast", "Mystic robes", "powered staff"]
text = """
[[File:Fighting_Kolodion.png|thumb|left|A player engages in combat with Kolodion.]]
[[Kolodion]] changes form as the fight progresses. At the start, he appears in the form you see him when you speak to him. He can only be damaged using [[Magic]]. After defeating this form, he transforms into an [[ogre]]-type creature. Despite being in [[Melee]] range, this form and all forms afterwards are magic-based, so the [[Protect from Magic]] [[prayer]] will make you invulnerable to all of his attacks. The next form is a giant [[Ice spider|frost spider]], then a [[ghost]], then finally a level 112 [[black demon]].

For all of these battles, it is recommended to use the strongest [[spell]] you have the level for. As each form changes, the [[Hitpoints]] of the form increases. With the Protect from Magic [[Prayer]] or decent [[food]], the battles are fairly easy to win. At level 70+ Magic, only around 100 casts of [[Blast spells|blast]] or [[Wave spells|wave]] spells are needed to defeat all five of Kolodion's forms. [[Iban Blast]] is also a viable option as its power allows for Kolodion's defeat in as few as 50 casts, even at level 60 Magic wearing only [[Mystic robes]].

You can exit the fight at any time by running out of the arena and pulling the lever to the north. Kolodion will be in the form you left off at when you return.

You may also use a [[powered staff]] for this fight, avoiding the need to bring runes with you.
{{clear}}
"""
