quest = "Tears of Guthix"
step_count = 6

[[steps]]
index = 0
name = "Getting started"
links = ["The Lost Tribe", "Brooch"]
text = """
'''If you have completed [[The Lost Tribe]] quest, you may skip to Option B! If not, use Option A. Partial completion is possible, you must only reach the point at which it is possible to obtain the [[Brooch]].'''
"""

[[steps]]
index = 1
name = "=Option A="
links = ["Juna", "Lumbridge Swamp", "bullseye lantern", "Smithing", "Crafting", "Firemaking", "sapphire", "sapphire lantern", "Wall beast", "rope", "Giant frog"]
text = """
To start, you need to find [[Juna]] deep inside the caves under the [[Lumbridge Swamp]]. A [[bullseye lantern]] is recommended to get deep enough safely, as a bullseye lantern will not be extinguished, will not explode from swamp gas, and cannot break. You don't have to make it yourself, as a player with high enough [[Smithing]] and [[Crafting]] can put one together for you, but you must be able to [[Firemaking|light]] it yourself. Before you enter the caves, use a cut [[sapphire]] on the bullseye lantern to get a [[sapphire lantern]]. If you do not do this now you will not be able to swap in the caves, as you cannot extinguish your lantern in the cave in order to replace the lens. This sapphire lantern will also light the caves. If you go to Juna's cave through the normal route, as you pass by [[Wall beast|holes in the wall]], stop one square away from them; then, run past them. You will not be grabbed by the wall beasts if you use this method.

You can enter the cave from the swamp (first time entry requires a [[rope]]), travelling south, then hugging the south wall all the way until there's a place where you can jump on a rock to cross a small, subterranean river. On the way, you will pass by a room where swamp gas will blow up any open flames you are carrying on you if you take too long to go past, each one hitting 10-15 damage. Watch for a grey 'X' marked on the northern side of a wall, this is the room. South of the [[Giant frog|frogs]] is a cave entrance. From there, head east, climb down the slope, and continue east until you see Juna sitting in front of the cave. Talk to her to begin the quest.

Skip to the '''Juna''' paragraph to continue.
"""

[[steps]]
index = 2
name = "=Option B="
links = ["Sapphire lantern", "The Lost Tribe", "Lumbridge Castle", "pickaxe", "Giant frog", "Juna"]
text = """
As mentioned above, you will need a lit [[Sapphire lantern|sapphire bullseye lantern]]. Since you have at least started [[The Lost Tribe]] quest, you can just go to the basement of [[Lumbridge Castle]], climb through the hole in the wall, head south, and then squeeze through the hole to get into the cave (right-click use on your [[pickaxe]] on the second hole to clear the pathway). From there, head straight south to the [[Giant frog|frogs]] and then jump across the stepping stone at the southern river, and enter another tunnel at the south. From there, head east, climb down the rocky slope, and continue east until you see [[Juna]] sitting in front of the cave. If you are carrying a weapon be sure to have it unequipped when you talk to Juna to be able to tell her a story. Talk to her to begin the quest.
"""

[[steps]]
index = 3
name = "Juna"
links = ["Juna", "stone bowl"]
text = """
When you talk to [[Juna]], she will tell you some stories about the Tears and tell you of how very bored she has become. Also you need to tell a story for her to be able to continue the quest. She's willing to let you into the cave for a little while to gather some of the miraculous Tears of Guthix, but first, she has a task for you. To collect the tears, you will need a [[stone bowl]]. Getting there will be a bit tricky, though, since you can't quite climb up to where the rocks you need are.
"""

[[steps]]
index = 4
name = "The Light Creatures"
links = ["Juna", "light creature", "sapphire lantern", "magical rocks"]
text = """
[[File:Riding light creature.png|thumb|Riding a light creature.]]
Head north-west of [[Juna]] up the path toward the direction you came from, and climb the rocks. In the big black middle area are a group of floating orbs of light called [[light creature]]s. Use your lit [[sapphire lantern]] on one of them, the creature will pick you up and give you a ride to the south side where the [[magical rocks]] are.
"""

[[steps]]
index = 5
name = "The Bowl"
links = ["pickaxe", "Magic stone (Tears of Guthix)", "chisel", "Stone bowl"]
text = """
Use your [[pickaxe]] to get a [[Magic stone (Tears of Guthix)|magic stone]], and then use your [[chisel]] to craft it into a [[Stone bowl|bowl]]. One will be enough. If the player did not tell Juna a story, then the player will receive a message "You don't know what to make." and will be unable to make a Stone bowl. Now, head east to climb back down and then go back to Juna. Give the bowl to her, and your quest is complete.

'''Congratulations, quest complete!'''

You can now reacquire the sapphire used when making your sapphire lantern by using the lantern with your lantern lens.
"""
