quest = "Doric's Quest"
step_count = 3

[[steps]]
index = 0
name = "Getting started"
links = ["Doric", "Falador", "Taverley", "Goblin Village", "whetstone", "anvil", "pickaxe", "bronze pickaxe", "clay", "copper ore", "iron ore"]
text = """
{{Map|name=Doric|x=2952|y=3452|r=4|height=250|width=250|mtype=square|align=right|caption=The quest's start location.}}
[[Doric]] can be found in a small building on the crossroads north of [[Falador]], east of the [[Taverley]] gate, and south of the [[Goblin Village]].

Ask Doric if you could use his [[whetstone]] or [[anvil]]. Doric will tell you he needs some materials in order to manufacture some [[pickaxe]]s. He will hand you a [[bronze pickaxe]]. He wants you to get him:

*6 [[clay]]
*4 [[copper ore]]s
*2 [[iron ore]]s

(''These cannot be noted'')

These materials must be turned in all at once ''(12 inventory slots)''.
"""

[[steps]]
index = 1
name = "Obtaining the materials"
links = ["Mining", "iron ore", "Dwarven Mine", "Ice Mountain", "Dwarf", "Iron rocks", "Copper rocks", "tin rocks", "Clay rocks", "Ironmen", "Members", "Ore Seller", "Blast Furnace", "pickpocketing", "H.A.M. Member", "Iron ore", "Sand Crab", "Rock Crab", "Rimmington mine"]
text = """
''(Skip this part if you already have all of the required materials)''

Where you obtain the ores does not matter, and can for example be obtained from other players or by mining the ores yourself (15 [[Mining]] is required for [[iron ore]]).

The [[Dwarven Mine]] is located near Doric's house, so you can head there. To get there, go east from Doric's house and then north to find a path onto [[Ice Mountain]]. On the mountain, walk south and look for a ladder surrounded by buildings and [[Dwarf|dwarves]]. Climb down the ladder to enter the Dwarven Mine. The [[Iron rocks|iron]], [[Copper rocks|copper]], and [[tin rocks]] are located due south of the entrance. [[Clay rocks]] are located a little further south.

[[Dwarf|Dwarves]] located outside the [[Dwarven Mine]], east of Doric's house, sometimes drop [[iron ore]]. This may help [[Ironmen]] trying to complete this quest before level 15 [[Mining]]. [[Members]] can buy the copper ores and iron ores at [[Ore Seller|the store]] in [[Blast Furnace]]. [[Ironmen]] can also complete the quest before reaching level 15 Mining by [[pickpocketing]] [[H.A.M. Member|H.A.M members]] as they have an uncommon chance to give [[Iron ore]]. Also you can kill for example [[Sand Crab|Sand]] or [[Rock Crab]]s which drop both copper and iron.

Alternatively, instead of mining in the Dwarven Mine, you can use the [[Rimmington mine]] south of Falador, which contains all the required ores right next to each other.
"""

[[steps]]
index = 2
name = "Finishing up"
links = ["Doric", "anvil"]
text = """
When you have all the ores needed, return to [[Doric]] to finish the quest. He will appreciate your help, reward you, and allow you to use his [[anvil]]s whenever you'd like.
"""
