quest = "Curse of the Empty Lord"
step_count = 4

[[steps]]
index = 0
name = "[[Valdez]] the Explorer"
links = ["ring of visibility", "ghostspeak amulet", "Morytania legs 2", "Morytania legs 3", "Morytania legs 4", "Glarial's Tomb", "Fishing Guild", "Rennard", "Staff of Armadyl", "Entrana", "Saradomin", "Ghostly robe (top)", "Members world", "Free-to-play world"]
text = """
{{Map|name=Valdez|x=2558|y=3446|r=4|mtype=square|align=right|width=200|height=200|caption=Valdez's location}}
Wearing your [[ring of visibility]] and your [[ghostspeak amulet]] or [[Morytania legs 2]]/[[Morytania legs 3|3]]/[[Morytania legs 4|4]], go to [[Glarial's Tomb]] (''not the waterfall cave'') north-west of the [[Fishing Guild]]. Talk to the ghost standing around the tomb entrance.

:'''Note:''' Be aware that throughout the miniquest the ghosts will not appear on the minimap, and can be difficult to spot due to their transparency.

Surprised that you can see and understand him, Valdez will offer to tell you a tale of woe. Agree to be told to the story, and he will explain how he was cursed to become a ghost. He blames [[Rennard]], a thief that stole the [[Staff of Armadyl]] from Valdez while he was delivering it to [[Entrana]] for [[Saradomin]]. He will give you a  [[Ghostly robe (top)]] and ask you to find [[Rennard]], offering a hint as to his location.

To obtain the full set of robes, the miniquest will require you to speak to five additional ghosts while wearing your chosen method of ghostspeak and [[ring of visibility]]. Each ghost will tell their part of the story to unravel the mystery of the Empty Lord's curse.

The locations you will need to visit are randomized between three possible sequences. '''Pay attention to the location hint given''', as it will indicate the sequence you need to follow. You can speak to him again if you missed it.

*If he mentions ''pirates and a shipwreck'', '''Sequence 1''' must be followed for the entirety of the quest.
*If he mentions the thief being ''north-east'' of there, '''Sequence 2''' must be followed for the entirety of the quest.
*If he mentions the thief being ''south-east'' of there, '''Sequence 3''' must be followed for the entirety of the quest.

'''Note:''' The ghosts will still appear at all three possible locations, but they will only allow you to progress if you speak to them at the location your sequence indicates.

'''Tip:''' When visiting ghosts within free-to-play regions of the Wilderness, you can reduce your risk by equipping the [[ring of visibility]] on a [[Members world]] beforehand, then visiting and completing the ghosts dialogue on a [[Free-to-play world]].
"""

[[steps]]
index = 1
name = "Sequence 1"
links = ["ring of visibility", "ghostspeak amulet", "Wilderness Agility Course", "Pirates' Hideout", "Lava Maze", "Chaos Temple (hut)", "Wilderness", "The Forgotten Cemetery", "Entrana", "Wizards' Tower", "Rogues' Castle", "Bronze sq shield", "Wilderness Obelisk"]
text = """
{{Needed|[[ring of visibility]], [[ghostspeak amulet]] ('''not morytania legs''')}}

You must visit the ghosts in the order given to collect all five additional pieces:

{| class="wikitable lighttable"
!Ghost
!Rewards
!Map
!Location
!Fast Travel
|-
|{{chatl|Rennard}} || {{plink|Ghostly gloves}} || {{Map|type=maplink|name=Rennard|x=3022|y=3946|plane=0|r=4|mapID=0|mtype=square}} || Near the shipwrecked ship between the [[Wilderness Agility Course]] and [[Pirates' Hideout]], within level 52 Wilderness. || {{plink|Burning amulet}} ([[Lava Maze]])
|-
|{{chatl|Kharrim}} || {{plink|Ghostly boots}} || {{Map|type=maplink|name=Kharrim|x=2950|y=3820|plane=0|r=4|mapID=0|mtype=square}} || The [[Chaos Temple (hut)]] altar in Level 38 [[Wilderness]] north of [[The Forgotten Cemetery]]. || {{plink|Burning amulet}} ([[Lava Maze]])
|-
|{{chatl|Lennissa}} || {{plink|Ghostly robe (bottom)}} ||{{Map|type=maplink|name=Lennissa|x=2850|y=3348|plane=0|r=4|mapID=0|mtype=square}} || [[Entrana]] church. '''Morytania legs cannot be used''' as your method of ghostspeak as they are not allowed on Entrana. || {{plink|Teleport to House}} (Rimmington), {{plink|Minigame Teleport}} (Rat Pits), {{plink|Amulet of glory}} (Draynor Village)
|-
|{{chatl|Dhalak}} || {{plink|Ghostly hood}} || {{Map|type=maplink|name=Dhalak|x=3109|y=3160|r=7|mtype=square}} || [[Wizards' Tower]], on the {{FloorNumber|uk=0}}. || {{plink|Necklace of passage}} (Wizards' Tower), {{plink|Amulet of glory}} (Draynor Village)
|-
|{{chatl|Viggora}} || {{plink|Ghostly cloak}} || {{Map|type=maplink|name=Viggora|x=3294|y=3934|plane=1|r=4|mapID=0|mtype=square}} || [[Rogues' Castle]] on the {{FloorNumber|uk=1}}, in the small easternmost room with a [[Bronze sq shield]] spawn.  Within level 52-56 [[Wilderness]].|| {{plink|Annakarl teleport (tablet)}}, {{plink|Wilderness sword 3|txt=Wilderness sword 3/4}} (Fountain of Rune), [[Wilderness Obelisk]]
|}
"""

[[steps]]
index = 2
name = "Sequence 2"
links = ["ring of visibility", "ghostspeak amulet", "morytania legs", "Bandit Camp (Wilderness)", "Bandits", "Graveyard of Shadows", "Port Sarim", "Lady Lumbridge", "Edgeville Monastery", "Slayer Tower", "Canifis", "Infernal Mage"]
text = """
{{Needed|[[ring of visibility]], [[ghostspeak amulet]] or [[morytania legs]] 2+}}

You must visit the ghosts in the order given to collect all five additional pieces:

{| class="wikitable lighttable"
!Ghost
!Rewards
!Map
!Location
!Fast Travel
|-
|{{chatl|Rennard}} || {{plink|Ghostly gloves}} || {{Map|type=maplink|name=Rennard|x=3024|y=3691|plane=0|r=4|mapID=0|mtype=square}} || The [[Bandit Camp (Wilderness)]] near the shops. If the [[Bandits]] interrupt your dialogue, you can try to lure them into the nearby food store and shut the door. || {{plink|Burning amulet}} (Bandit Camp)
|-
|{{chatl|Kharrim}} || {{plink|Ghostly boots}} ||  {{Map|type=maplink|name=Kharrim|x=3157|y=3667|plane=0|r=4|mapID=0|mtype=square}} || The [[Graveyard of Shadows]], typically near the southern tomb within the graveyard. || {{plink|Burning amulet}} (Bandit Camp)
|-
|{{chatl|Lennissa}} || {{plink|Ghostly robe (bottom)}} || {{Map|type=maplink|name=Lennissa|x=3044|y=3204|plane=0|r=4|mapID=0|mtype=square}} ||  [[Port Sarim]] docks at the [[Lady Lumbridge]] (second to southmost dock). || {{plink|Teleport to House}} (Rimmington), {{plink|Minigame Teleport}} (Rat Pits), {{plink|Amulet of glory}} (Draynor Village)
|-
|{{chatl|Dhalak}} || {{plink|Ghostly hood}} || {{Map|type=maplink|name=Dhalak|x=3052|y=3498|plane=1|r=4|mtype=square}} ||  [[Edgeville Monastery]], upstairs by the altar (requires {{SCP|Prayer|31}}). || {{plink|Combat bracelet}} (Edgeville Monastery), {{plink|Amulet of glory}} (Edgeville), {{plink|Lassar teleport (tablet)}}
|-
|{{chatl|Viggora}} || {{plink|Ghostly cloak}} || {{Map|type=maplink|name=Viggora|x=3448|y=3550|plane=1|r=4|mapID=0|mtype=square}} || [[Slayer Tower]] in [[Canifis]], on the {{FloorNumber|uk=1}} by the entrance to the [[Infernal Mage]]s on the eastern side. || {{plink|Slayer ring}} (Slayer Tower), {{plink|fairy ring|txt=fairy ring|pic=fairy ring icon}} {{fairycode|cks}}, {{plink|Salve graveyard teleport (tablet)}}
|}
"""

[[steps]]
index = 3
name = "Sequence 3"
links = ["ring of visibility", "ghostspeak amulet", "morytania legs", "knife", "shantay pass", "coins", "fairy rings", "Bandit Camp (Kharidian Desert)", "Magic carpet", "Shantay Pass", "Lava Maze", "slash weapon", "muddy key", "Muddy chest", "Wilderness diary", "Tree Gnome Stronghold", "Falador Party Room", "Edgeville Dungeon", "earth warrior"]
text = """
{{Needed|[[ring of visibility]], [[ghostspeak amulet]] or [[morytania legs]] 2+, [[knife]] or slash weapon, [[shantay pass]] and 200 [[coins]] if not using [[fairy rings]]}}

You must visit the ghosts in the order given to collect all five additional pieces:

{| class="wikitable lighttable"
!Ghost
!Rewards
!Map
!Location
!Fast Travel
|-
|{{chatl|Rennard}} || {{plink|Ghostly gloves}} || {{Map|type=maplink|name=Rennard|x=3162|y=2982|plane=0|r=4|mapID=0|mtype=square}} || The [[Bandit Camp (Kharidian Desert)]] in the bar on the western side of the camp. Note that players training here may be standing on the NPC. || {{plink|fairy ring|txt=fairy ring|pic=fairy ring icon}} {{fairycode|biq}}, {{plink|Amulet of glory}} (Al Kharid) and then take the [[Magic carpet]] from [[Shantay Pass]]
|-
|{{chatl|Kharrim}} || {{plink|Ghostly boots}} || {{Map|type=maplink|name=Kharrim|x=3068|y=3858|plane=0|r=4|mapID=0|mtype=square}} || The end of the [[Lava Maze]] inside the second fenced in area. Bring a [[slash weapon]] or [[knife]] to cut through the webs. '''Tip:''' If you have a [[muddy key]], you may choose to open the [[Muddy chest]] in the [[Lava Maze]] to complete a task in the [[Wilderness diary#Medium|medium Wilderness diary]]. || {{plink|Burning amulet}} (Lava Maze)
|-
|{{chatl|Lennissa}} || {{plink|Ghostly robe (bottom)}} || {{Map|type=maplink|name=Lennissa|x=2396|y=3481|plane=0|r=4|mapID=0|mtype=square}} || The west side of [[Tree Gnome Stronghold]], directly south of the centre of the Gnome Ball Field along the outer edge of the fence. || {{plink|Spirit tree|pic=Spirit tree icon}} (Tree Gnome Stronghold), {{plink|Slayer ring}} (Stronghold Slayer Cave), {{plink|Necklace of passage}} (The Outpost)
|-
|{{chatl|Dhalak}} || {{plink|Ghostly hood}} || {{Map|type=maplink|name=Dhalak|x=3046|y=3379|squareX=20|squareY=15|mtype=square}} || The [[Falador Party Room]], upstairs on the eastern side. || {{plink|Skills necklace}} (Mining Guild), {{plink|Ring of wealth}} (Falador Park), {{plink|Falador Teleport}}
|-
|{{chatl|Viggora}} ||{{plink|Ghostly cloak}} || {{Map|type=maplink|name=Viggora|x=3119|y=9996|plane=0|r=4|mapID=-1|mtype=square}} || The [[Edgeville Dungeon]] near the [[earth warrior]]s in the northernmost room. To avoid the earth warriors interrupting your dialogue, you can trap them behind the ghost with you on the other side; you must talk to Viggora as soon as this happens and click through the first dialogue window to make this effect permanent for the whole chat. || {{plink|Amulet of glory}} (Edgeville), {{plink|Skills necklace}} (Cooks' Guild)
|}
"""
