quest = "Sheep Shearer"
step_count = 2

[[steps]]
index = 0
name = "Obtaining the wool"
links = ["shears", "sheep", "spinning wheel", "Lumbridge Castle", "free-to-play", "Prince Ali Rescue", "ball of wool", "rams", "Sheep (penguins)", "Cold War", "Settings", "penguin"]
text = """
{{Needed|recommended=21 free inventory spaces (24 if doing Prince Ali Rescue)}}
[[File:Lumbridge Sheep chathead.png|left|frameless]]
If you did not bring [[shears]], Fred will give you some. Enter the fenced area connected to the east side of the house where the [[sheep]] are.
[[File:Sheep Shearer - Spinning wheel.png|thumb|The [[spinning wheel]] on the {{FloorNumber|uk=1}} of [[Lumbridge Castle]].]]

'''Note''': Players planning to do the [[free-to-play]] quest [[Prince Ali Rescue]] are advised to shear and spin at least three more [[ball of wool|balls of wool]].

Shear the sheep, either by selecting the "shear" option on the sheep, or right-clicking the shears and selecting "use," then clicking the sheep. After shearing them, the skinny looking sheep will grow back their wool after one minute. If they run away while shearing, just keep trying.

Avoid the [[rams]], which look like regular sheep with horns. They cannot be sheared, and it is easy to accidentally attack them. The pen also contains "[[Sheep (penguins)|The Thing]]", which Fred warned the player about. This is actually two penguins in disguise as a sheep, and attempting to shear it will cause the penguins to squeak and run away from you. It can be identified as the only sheep with the "Talk to" option, and poses no danger during the quest. "The Thing" is later encountered during the [[Cold War]] quest.

Low-level players may consider setting their [[Settings#Controls|attack options]] to "Hidden" for the duration of this quest to avoid entering combat with them on accident.

[[File:Sheep Shearer - Abnormal sheep.png|thumb|The two [[penguin]]s disguised as a [[sheep]].]]
"""

[[steps]]
index = 1
name = "Spinning the wool"
links = ["wool", "Lumbridge Castle", "spinning wheel", "inventory", "Banknote"]
text = """
Once you have 20 pieces of [[wool]], they must be spun into balls of wool. Go to the {{FloorNumber|uk=1}} of the [[Lumbridge Castle]], and find the bedroom on the south end of the castle. Inside is a [[spinning wheel]]; click on the wheel with the wool in your [[inventory]] to spin your wool into balls. When they are all spun, go back to Fred the Farmer to finish the quest. If you do not have the space to carry all 20 pieces of wool, you can make smaller deliveries until you reach the required total. Note that Fred will not accept [[Banknote|noted]] balls of wool.

'''Congratulations, quest complete!'''
"""
