quest = "Shield of Arrav"
step_count = 2

[[steps]]
index = 0
name = "Choosing your gang"
links = ["Reldo", "Varrock Palace library", "bookcase (Shield of Arrav)", "Phoenix Gang", "Black Arm Gang", "Charlie the Tramp", "chat-channel", "coins", "scams"]
text = """
[[File:Reldo chathead.png|left]]

Talk to [[Reldo]] in the [[Varrock Palace library]], the northernmost room on the ground floor. Ask him for a quest, and he will suggest you look around for a book called the Shield of Arrav, which may have a quest for you. To find it, search the [[bookcase (Shield of Arrav)|bookcase]] with a blue and white book in the top shelf, located on the east side of the short bookcases in the middle of the room. Read the book, then speak with Reldo again to tell him you have read it. The player will ask him about the whereabouts of the [[Phoenix Gang]] and the [[Black Arm Gang]]. At this stage, you can choose to join either gang. If you wish to join the Phoenix Gang, speak to Baraek, the fur trader in the market. Otherwise, talk to [[Charlie the Tramp]] next to the southern gate of Varrock.

'''Note''': You will only need to follow the steps to join one of the two gangs. It is recommended to '''make sure you have a partner from the opposite gang''' before choosing one. To find one, you may ask in the official [[chat-channel]] ''OSRS SOA''.

{{Colour|red|Warning:}} Although the majority of players in the chat-channel offer their services for free, some players also charge [[coins|in-game money]]. Beware of the possibility of being [[scams|scammed]] when engaging in [[scams#Trust trading scams|trust trades]] with other players.

When picking your gang, there are a number of considerations:
*It is much easier to find Phoenix Gang members via the official chat-channel.
*Phoenix Gang is recommended for lower combat levels.
*Black Arm Gang is recommended if you do not want to gain combat experience.
*If your partner has previously combined the two half pieces to create the complete certificate or has completed the quest, they cannot obtain the half piece of the shield from their gang hideout - which means certificates cannot be obtained from them. If your partner is from Phoenix Gang, they can help you acquire the key to the weapon store only.
*The half shield of arrav reappears in their respective locations if the half certificate is lost, allowing players to repeatedly offer half certificates as long as they have not completed the quest.

<choose>
<option>
{{:Shield of Arrav/Phoenix Gang}}
{{:Shield of Arrav/Black Arm Gang}}</option>
<option>
{{:Shield of Arrav/Black Arm Gang}}
{{:Shield of Arrav/Phoenix Gang}}</option>
</choose>
"""

[[steps]]
index = 1
name = "Finishing up"
links = ["Broken shield", "Curator Haig Halen", "Varrock Museum", "Half certificate", "Certificate (Shield of Arrav)", "Ironman", "King Roald", "Varrock Palace"]
text = """
{{Needed|[[Broken shield]]}}

Take your half of the shield to [[Curator Haig Halen]], located in the [[Varrock Museum]]. He will take your half of the shield and give you two copies of [[Half certificate|half the certificate]]. Your partner, who has the other half of the Shield, will receive the other half of the certificate. Trade one half of the certificate with your partner for the other half. When you have both certificate halves, use them on the other to obtain a completed [[Certificate (Shield of Arrav)|certificate]]. If completing the quest as an [[Ironman]] you must 'use' the key/certificate on each other. [[File:Shield of Arrav - Certificate.png|centre]]

Take the certificate to [[King Roald]] in [[Varrock Palace]] to receive your reward. Congratulations, quest complete!
"""
