quest = "Death on the Isle"
step_count = 4

[[steps]]
index = 0
name = "Getting the right fit"
links = ["Aldarin", "Mastering Mixology", "Minigame Teleport", "fairy ring", "coins", "Sunset Coast", "Patzi", "Villa Lucens", "butler's uniform", "Adala", "Aldarin General Store", "house window", "Wandering Guard", "Wardrobe (Death on the Isle)", "Head Butler"]
text = """
[[File:Death on the Isle - breaking into villa.png|thumb|Breaking into a villa for a butler's uniform.]]
Travel to the island of [[Aldarin]]; the easiest method is to use the [[Mastering Mixology]] [[Minigame Teleport]] (requires {{SCP|Herblore|60|link=yes}}), [[fairy ring]] {{fairycode|CKQ}}, or you can pay 20 [[coins]] to take a boat from the [[Sunset Coast]].

Talk to [[Patzi]] at the entrance to [[Villa Lucens]]. He will ask that you help him with a new play that is due to be performed at the villa, whose owner is a patron of the arts and is hosting a party for the play. He will ask that you acquire a [[butler's uniform]] to help him fit in; [[Adala]], Patzi's bag carrier, suggests "borrowing" one and tells you she recalls seeing some through a window in a villa to the north.

The villa in question is found just west of the [[Aldarin General Store]]. Break into the villa via the [[house window]] on the south side once the [[Wandering Guard]] is far enough, then take a uniform from the [[Wardrobe (Death on the Isle)|wardrobe]] nearby.

Return to Patzi, who will then ask that you follow along Adala to the staff entrance to blend in. Wear your uniform, then head south along the hedge until you see the [[Head Butler]]. He will inform you of the rules whilst inside the villa, and will hold onto your items before entering for security purposes.
"""

[[steps]]
index = 1
name = "Inside Villa Lucens"
links = ["snake mask", "Ram mask", "jaguar mask", "Wolf mask (Death on the Isle)", "bird mask", "butler's tray", "Constantinius", "Cozyac", "Pavo", "Xocotla", "wine cellar", "cellar entrance", "antique wine", "Stradius", "Hutza", "Livius", "case file"]
text = """
[[File:Death on the Isle - inside Villa Lucens.png|thumb|The player plays the part of a butler in Villa Lucens.]]
Once inside Villa Lucens, you will be wearing one of several possible masks ([[snake mask]], [[Ram mask|ram mask]], [[jaguar mask|jaguar mask]], [[Wolf mask (Death on the Isle)|wolf mask]] or [[bird mask]]) and [[butler's tray]] alongside your uniform. You will find Patzi by the eastern exit, who will tell you to introduce yourself to the guests on his behalf; however, as a butler, he will ask that you at least get their names for him.

Speak to [[Constantinius]], who you find out is the host of the party, and then the three guests: [[Cozyac]], [[Pavo]], and [[Xocotla]]. After doing so, you will relay what you've learned to Patzi, who then asks you to fetch him a glass of Principum Red in the [[wine cellar]]. Head outside and enter the [[cellar entrance]], then head to the south-west room and investigate the [[antique wine]] along the south wall.

As you attempt to retrieve some wine from the [[antique wine]] jug, you will hear glass breaking in another part of the cellar, spilling some on you. Head to the south-east corner to find a fallen man. Upon investigating him, two guards, [[Stradius]] and [[Hutza]], will accuse you of murder and take you away to a small room in the villa. After some questioning, you offer to help solve the murder of [[Livius]], an actor who was due to perform on stage. They will give you a [[case file]] and ask you to investigate the crime scene.
"""

[[steps]]
index = 2
name = "Playing detective"
links = ["Jug (Death on the Isle)", "Small box", "Broken stool", "Wine storage", "Broken pottery", "Cozyac", "threatening note", "Pavo", "drinking flask", "Xocotla", "shipping contract", "Adala", "wine labels", "Principum Red"]
text = """
[[File:Death on the Isle - dead man in cellar.png|thumb|Livius' corpse in the wine cellar.]]
Speak to Constantinius, Cozyac, Pavo, and Xocotla again, then return to the wine cellar and investigate the following:

* [[Jug (Death on the Isle)|Jug]] by the stairs
* [[Small box]] in south room
* [[Broken stool]] in south room
* [[Wine storage#Half full|Wine storage]] in east room
* [[Broken pottery]] in east room
* Livius' corpse in east room

After investigating everything, speak to Stradius and Hutza to discuss your findings. You will not find sufficient evidence to accuse the guests, but believe the butlers may be suspicious like you were, and will attempt to pickpocket them in hopes of finding something of note.

Pickpocket the following people for your investigation:

* [[Cozyac]] - [[threatening note]]
* [[Pavo]] - [[drinking flask]]
* [[Xocotla]] - [[shipping contract]]
* [[Adala]] - [[wine labels]]

[[File:Death on the Isle - fighting Adala.png|thumb|Adala lashes out after being accused.]]
After inspecting each item, return to the guards and they will gather everyone on the top floor. Speak to all the suspects, then place your accusations on Adala, who admits to being in the cellar to steal the extremely valuable [[Principum Red]]. However, she claims not to have killed Livius and starts attacking the player. She is level 49, and has no special mechanics to attack with. Once either of you are close to death, she will stop and claim that she's too weak to kill Livius or you depending on how the fight went. She will then be taken away.
"""

[[steps]]
index = 3
name = "The Show Must Go On"
links = ["loose rocks (Death on the Isle)", "backstage entrance", "costumer", "crate (Death on the Isle)", "costume rack", "Naiatli", "bookshelf (Death on the Isle)", "Prop sword (Death on the Isle)", "Head Butler", "Ram mask", "Wolf mask (Death on the Isle)", "Bird mask", "Jaguar mask", "Snake mask", "butler's tray", "costume needle", "Crafting", "needle", "thread", "Constantinius", "Chest key (Fancy chest)", "fancy chest", "Icon_(Aldarin)", "pendant of ates"]
text = """
Though the killer is still at large, Constantinius demands that the show must go on, and asks that you keep an eye on the situation behind the scenes. He will tell you to use the back way around the theatre so as to not attract attention.

Use the southern path down the steps that leads around the cliffs until you reach a set of [[loose rocks (Death on the Isle)|loose rocks]] by the [[File:Agility shortcut icon.png|link=]] shortcut icon. Navigate through them and speak to the guards - they will ask that you investigate the backstage downstairs to check for additional clues.

Enter the [[backstage entrance]] then speak to the [[costumer]], and ask about the actors. Then search the following:

* The [[crate (Death on the Isle)|crate]] next to the exit containing poison
* The [[costume rack]] behind the mirror containing [[Naiatli|Naiatli's]] wine-stained costume
* The [[bookshelf (Death on the Isle)|bookshelf]] hiding a secret passage to the wine cellar

[[File:Death on the Isle - improv.png|thumb|The player confronts Naiatli without revealing to the audience what is truly happening.]]
After searching the aforementioned objects, speak to the costumer and ask her about each of them. Next, return to the guards and accuse Naiatli of being the culprit. However, the play has started already, and you decide to step into the limelight.

As you accuse Naiatli of her crimes whilst doing so under the guise of improvising the play, you begin to attack her with a [[Prop sword (Death on the Isle)|prop sword]] while she continues to "perform". Whenever she runs away, resume attacking her until she "dies". You will find out that in reality, Naiatli only tripped him in an attempt to injure Livius so that he would be unable to perform the play, but was far too drunk and fell harder than anticipated.

Stradius and Hutza will thank you for your assistance and apologise for hastily accusing you.

'''Congratulations, quest complete!'''

Before leaving Villa Lucens, players can claim some rewards:

* Speak to the [[Head Butler]] in the kitchen to obtain the masks ([[Ram mask|ram]], [[Wolf mask (Death on the Isle)|wolf]], [[Bird mask|bird]], [[Jaguar mask|jaguar]], and [[Snake mask|snake]]) that you and the butlers wore during the quest, as well as the [[butler's tray]] you used.
* Speak to the [[costumer]] for a [[costume needle]], which can be used for [[Crafting]] in place of a regular [[needle]], without needing any [[thread]].
* Pickpocketing [[Constantinius]] for a [[Chest key (Fancy chest)|chest key]], which is used to open the [[fancy chest]] in the wine cellar. This allows the fountain to the south-west of the villa to be searched for an [[Icon_(Aldarin)|icon]], which is then used to activate the statue on the North-East corner of the island. This drops one water rune on the ground and unlocks a teleport destination on a [[pendant of ates]].
"""
