quest = "Rag and Bone Man I"
step_count = 3

[[steps]]
index = 0
name = "Starting out"
links = ["Varrock Teleport", "digsite pendant", "balloon transport system", "willow logs", "Odd Old Man", "Varrock", "Paterdomus Temple", "Silvarea", "Earth Altar", "Saradomin", "Digsite", "Balloon transport system", "Castle Wars", "minigame teleport", "Canifis", "Silvarea mine", "icon", "minimap", "mining site"]
text = """
{{Needed|recommended=A [[Varrock Teleport|Varrock teleport]] or [[digsite pendant]] (or usage of the [[balloon transport system]] (with [[willow logs]])) for a faster route of travel to the [[Odd Old Man]]}}
[[File:Sack chathead.png|left]]

The [[Odd Old Man]] (quest start location) is found east of [[Varrock]] and west of [[Paterdomus Temple]] in [[Silvarea]].

If travelling from Varrock, walk east of the city and through the gate near the [[Earth Altar]], directly east of the nearby statue of [[Saradomin]]. If travelling from the [[Digsite]], walk north and east around the mountain. You can also use the [[Balloon transport system|balloon Transport System]], as one of the destinations is directly north-west of the gate (it is suggested to have the [[Castle Wars]] location unlocked due to its proximity to a balloon. Use the [[minigame teleport]] to Castle Wars, then fly to the [[Varrock]] balloon location (1 willow log required). The Odd Old Man is a fairly short distance to the east).

Reaching him will take you down the same path as travelling [[Canifis]] would. Halfway down that path, you will find the Odd Old Man to the north, just slightly north-west of the [[Silvarea mine|limestone quarry]] (marked by a quest [[icon]] on your [[minimap]], right next to the [[mining site]] icon).

Talk to him, and he will tell you that he needs several bones to complete his collection. '''Then talk to him again''' after getting the list to have him list every bone individually; go through the chat dialogue, where he tells you what bones you have remaining and where to get them individually, until he guides you on how to polish the bones in vinegar. '''If you do not speak to him and go through the entire dialogue, you will be unable to add bones to the pots of vinegar later on unless you talk to him, so doing this will efficiently save you a trip or two.'''
"""

[[steps]]
index = 1
name = "Collecting the bones"
links = ["Odd Old Man", "Giant rat bone", "Giant rat", "Varrock", "South-east Varrock mine", "Varrock Sewer", "Lumbridge Swamp", "Port Sarim jail", "Unicorn bone", "Unicorn", "Draynor Village", "Edgeville", "Catherby", "Entrana", "Law Altar", "Ardougne Zoo", "Games necklace", "Tithe Farm", "Bear ribs", "Bear", "Falador", "Ardougne", "Ram skull", "Ram", "Fred the Farmer", "Crafting Guild", "Make-over mage", "Fisher Realm", "Sir Percival", "Goblin skull", "Goblin", "Lumbridge", "goblin", "Big frog leg", "Big frog", "Monkey paw", "Monkey", "Karamja Volcano", "Karamja", "ranged", "magic", "equipment", "Telekinetic Grab", "Giant bat wing", "Giant bat", "Crandor and Karamja Dungeon", "Keep Le Faye", "Heroes' Guild", "Yanille", "Coins", "Jug of vinegar", "Amulet of glory", "Port Sarim", "Lumbridge Swamp Caves", "giant rat bone", "unicorn", "black bear", "unicorn bone", "bear ribs", "ram", "ram skull", "River Lum", "goblin skull", "big frog", "big frog leg", "frog", "giant frog", "Fortunato", "Rag and Bone Man II", "jugs of vinegar", "Varrock Teleport", "Magic tablet", "Digsite pendant", "logs", "axe", "monkey paw", "giant bat", "giant bat wing"]
text = """
Below is the list of monsters that need to be killed to obtain all the bones (8 total).

'''Note:''' All of these monsters can be found in other places; listed are the most convenient spots.

'''Note:''' At any point, a player can turn in a bone or bones to the [[Odd Old Man]], assuming it has been polished. Having all 8 at once is not necessary, but preferable to save time.
{|class="wikitable lighttable" style="text-align:center;"
!colspan=2|Bone
!Monster
!Locations (preferable) - Click to mark
|-
|[[File:Giant rat bone.png]]
|[[Giant rat bone]]
|[[Giant rat]]
|South-east of [[Varrock]] by the [[South-east Varrock mine|mine]], [[Varrock Sewer]], [[Lumbridge Swamp]], near the [[Port Sarim jail]].
|-
|[[File:Unicorn bone.png]]
|[[Unicorn bone]]
|[[Unicorn]]
|The forest south-east of [[Varrock]], [[Lumbridge Swamp]], by [[Draynor Village]], south of [[Edgeville]], west of [[Catherby]], on [[Entrana]] (west from the [[Law Altar]]), next to fairy ring {{Fairycode|BIS}} in [[Ardougne Zoo]], outside of Corporeal beast cave in Wilderness (very close to [[Games necklace]] teleport), Hosidius saltpetre mines (close to the [[Tithe Farm]] minigame teleport and Hosidius house portal).
|-
|[[File:Bear ribs.png]]
|[[Bear ribs]]
|[[Bear]]
|The forest south-east of [[Varrock]], the enclosure north-east of the palace in [[Varrock]], north of [[Falador]], the forests near [[Ardougne]] (south-west of fairy ring {{Fairycode|BLR}}).
|-
|[[File:Ram skull.png]]
|[[Ram skull]]
|[[Ram]]
|The sheep pen south of [[Varrock]], in [[Fred the Farmer|Fred the Farmer's]] sheep pen (north of Lumbridge), north of the [[Crafting Guild]] (by the [[Make-over mage]]), in the [[Fisher Realm]] (fairy ring {{Fairycode|BJR}}) after finding [[Sir Percival]].
|-
|[[File:Goblin skull.png]]
|[[Goblin skull]]
|[[Goblin]]
|Both east and west of [[Lumbridge]] (the [[goblin]]s at the farm south of Varrock and north of  [[Ardougne]] '''do not''' drop the bone).
|-
|[[File:Big frog leg.png]]
|[[Big frog leg]]
|[[Big frog]]
|The [[Lumbridge Swamp]]. Both the Level 10 and 24 Big Frogs can be killed to acquire the bone.
|-
|[[File:Monkey paw.png]]
|[[Monkey paw]]
|[[Monkey]]
|East of the [[Karamja Volcano]], south [[Karamja]] (right next to fairy ring {{Fairycode|CKR}}), [[Ardougne Zoo]] (if you choose to go to Ardougne Zoo, you must bring [[ranged]] and/or [[magic]] [[equipment]] and have 33 Magic for [[Telekinetic Grab]]).
|-
|[[File:Giant bat wing.png]]
|[[Giant bat wing]]
|[[Giant bat]]
|[[Crandor and Karamja Dungeon]] (which can be accessed on the [[Karamja Volcano]]), outside [[Keep Le Faye]] (north of fairy ring {{Fairycode|BLR}}), below the [[Heroes' Guild]], [[Yanille]] dungeon, coal trucks west of McGrubor's Wood, mine west of [[Tithe Farm]] (close to the minigame teleport, or Hosidius house portal).
|}
{{Needed| 8 [[Coins|gp]] to buy the 8 [[Jug of vinegar|jugs of vinegar]] with, 60 gp to travel to and back from [[Karamja]] (if walking), and 8 empty inventory slots for the bones|recommended=Teleports to [[Lumbridge]], [[Draynor Village]]'' (''[[Amulet of glory]]) and [[Karamja]] (will save some time).}}

Collecting all of the required bones is a relatively easy task if you walk south of the [[Odd Old Man|Odd Old Man's]] location, down to [[Lumbridge]], and then to [[Port Sarim]] in the west to get to [[Karamja]]. Using teleports to get to the required locations will speed up the process ([[Lumbridge]], [[Draynor Village]], and [[Karamja]] teleport). Ensure you '''talk to the Odd Old Man before you begin gathering and go through the entire dialogue'''. All needed bones are a guaranteed drop.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1108655941006835713|date=21 March 2019|archiveurl=https://archive.is/A1bcg|archivedate=18 May 2019|quote=The initial quest ones are guaranteed drops. The longer wish-list is 1/4.}} The following is a recommended route for the first six of the eight required bones, starting from the Odd Old Man's house and ending in the [[Lumbridge Swamp Caves]].

#Run west from the Odd Old Man's house and through the gate, then south to the mines south-east of Varrock and kill a [[Giant rat]] near or inside the mine, picking up the [[giant rat bone]] it drops in the process.
#Head slightly south of the mine to the forest and kill a [[unicorn]] and [[black bear]], picking up the [[unicorn bone]] and the [[bear ribs]] respectively.
#Head into the sheep pen to the south-west of the mine and west of the forest and kill a [[ram]] to get a [[ram skull]].
#Walk south towards [[Lumbridge]] (or teleport to the city and walk east) and kill a [[goblin]] on the eastern side of the [[River Lum]] to get a [[goblin skull]].
#Head down to the [[Lumbridge Swamp]] and kill one of the [[big frog]]s for the [[big frog leg]]. The small [[frog]]s and [[giant frog]]s do '''NOT''' drop the big frog leg.

From here, head to [[Draynor Village]], north-west of the Lumbridge Swamps. Find and '''talk to''' [[Fortunato]] in the market about vinegar. Only after talking about vinegar will he have it stocked in the store, trade him and purchase 8 (or 35 if intending to do [[Rag and Bone Man II]] at some point, saving time later) [[jugs of vinegar]]. '''Do not steal from the market stall or he won't talk to you.'''

This is also a good opportunity to withdraw items to return to the Odd Old Man ([[Varrock Teleport|Varrock teleportation runes]] or [[Magic tablet|tablet]], [[Digsite pendant]]), and, if returning directly to him, all 6 currently collected bones and the necessary supplies to polish all 8 (8 jugs of vinegar, 8 pots (highly recommended to make the 6 bone in vinegar you currently can and 2 pots of vinegar to save space - see "Polishing the bones" for details), and 8 [[logs]] (of any type - alternatively, an [[axe]] to cut down the trees by the Odd Old Man, which will save a lot of space)).

'''Note:''' Be careful that you '''do not''' accidentally "empty" a bone in vinegar, because if you do, '''you will lose the bone and have to collect that bone again'''.

From here, travel south-west to Port Sarim and take the ship (the third transportation icon from the north, fourth from the south) (requires 30 gp each way) to Karamja (can also teleport (amulet of glory)). Once there:

#Walk west towards the [[Karamja Volcano]] and kill a monkey on the way, picking up the [[monkey paw]].
#Head into the [[Crandor and Karamja Dungeon]], which is located at the top of the Karamja Volcano (marked by a dungeon icon), and kill a [[giant bat]], picking up the [[giant bat wing]].

After you've gathered all 8 bones, head back to the Odd Old Man, and a bank if necessary.
"""

[[steps]]
index = 2
name = "Polishing the bones"
links = ["bone in vinegar", "Jug of vinegar", "pot", "tinderbox", "logs", "axe", "Odd Old Man", "Varrock", "Digsite pendant", "Pot of vinegar", "tree", "Firemaking", "experience"]
text = """
{{Inventory|align=right
|Bone in vinegar |Bone in vinegar |Bone in vinegar |Bone in vinegar
|Bone in vinegar |Bone in vinegar |Bone in vinegar |Bone in vinegar
|Logs |Logs |Logs |Logs
|Logs |Logs |Logs |Logs
|Tinderbox |Varrock teleport (tablet)
}}
{{Needed|8 [[bone in vinegar]] (requiring 8 [[Jug of vinegar|jugs of vinegar]], 8 [[pot]]s, and all 8 bones to make), a [[tinderbox]], 8 [[logs]] (of any type - can also bring an [[axe]] to chop them down by the [[Odd Old Man]]|recommended=A teleportation method to the [[Odd Old Man]] ([[Varrock]] teleport, [[Digsite pendant]]).}}

An example of how an inventory looks, before heading back to the Odd Old Man, can be seen on the right.

If you haven't already, make 8 [[Pot of vinegar|pots of vinegar]] by using the [[Jug of vinegar|jugs of vinegar]] on your pots and then use all the bones on the pots of vinegar to make 8 [[bone in vinegar]].

'''Note:''' Be careful that you '''do not''' accidentally "empty" a bone in vinegar, because if you do, '''you will lose the bone and have to collect that bone again'''.

Go back to the old man taking the eight bones in vinegar, a [[tinderbox]] and eight [[logs]] (or, alternatively, bring an [[axe]] instead of logs; there are [[tree]]s near the Odd Old Man at the bottom of the stairs where logs can be cut). '''Any''' type of logs works for this quest, provided you have the [[Firemaking]] level to light the logs.

To polish the bones, use a log on the pot-boiler next to the Odd Old Man. Then, use a bone in vinegar on the pot boiler, and finally, use your tinderbox to light it (you will not receive [[experience]] for lighting the logs). It takes 12 seconds for each pot to boil. You can hop worlds after lighting the logs to skip these 12 seconds. Repeat this for all eight bones.

Talk to the [[Odd Old Man]], and give him the polished bones to complete the quest.

'''Congratulations, quest complete!'''
"""
