quest = "Recipe for Disaster/Freeing Skrach Uglogwee"
step_count = 1

[[steps]]
index = 0
name = "Rewards"
links = ["Woodcutting", "Cooking", "Crafting", "Ranged", "Ogre boat", "Karamja", "Feldip Hills", "Culinaromancer's Chest"]
text = """
----
{{Quest rewards
|name = Recipe for Disaster/Freeing Skrach Uglogwee
|image = [[File:Recipe for Disaster (Freeing Skrach Uglogwee) reward scroll.png|centre]]
|qp = 1
|rewards =
*{{SCP|Woodcutting|1,500}} [[Woodcutting]] experience
*{{SCP|Cooking|1,500}} [[Cooking]] experience
*{{SCP|Crafting|1,500}} [[Crafting]] experience
*{{SCP|Ranged|1,500}} [[Ranged]] experience
*The ability to use the [[Ogre boat|boat trip]] to travel between [[Karamja]] and the [[Feldip Hills]] (you must pay a fee of chompies or exotic herbs)
*Further access to the [[Culinaromancer's Chest]]
}}</onlyinclude>
"""
