quest = "In Search of Knowledge"
step_count = 1

[[steps]]
index = 0
name = "Main"
links = ["Forthos Dungeon", "Brother Aimeri", "Sarachnis", "tattered sun page", "tattered moon page", "tattered temple page", "Red dragon", "Undead Druid", "Baby red dragon", "Temple Spider", "multicombat area", "Dwarf multicannon", "Ancient Magicks", "Chinchompa", "Altar (Forthos Dungeon)", "undead", "Salve amulet(ei)", "Olbertus", "Cursed Altar", "Grubby Chest", "undead druid", "Protect from Magic", "Prayer", "musty bookshelf", "tome of the sun", "tome of the moon", "tome of the temple", "Logosia", "Arceuus Library"]
text = """
Enter [[Forthos Dungeon]] and talk to the injured monk, [[Brother Aimeri]], located in the south-east corner of the dungeon, outside the entrance to [[Sarachnis]]' lair. Use five pieces of food (must be fish, meat or vegetables), and he will heal to full health. Ask him who he is, and he will say he is here to discover the origins of his religion, and asks that you let him know about anything of interest that you find. Once you say "I'll keep my eyes open", the miniquest will begin.

The player must now gather four [[tattered sun page]]s, [[tattered moon page]]s, and [[tattered temple page]]s. The pages are dropped by all types of monsters within the Dungeon at the rates shown below.
{| class="wikitable"
|+
!Monster
!Level
!Hitpoints
!Droprate
|-
|[[Sarachnis]]
|318
|400
|1/5
|-
|[[Red dragon]]
|152
|140
|1/10
|-
|[[Undead Druid|Undead druid]]
|105
|140
|1/20
|-
|[[Baby red dragon]]
|48
|50
|1/25
|-
|[[Temple Spider|Temple spider]]
|75
|70
|1/30
|}

* At lower levels, [[Baby red dragon|baby red dragons]] are the easiest to kill for the pages - there is an alcove in the south-east corner of the [[Forthos Dungeon#Scorched Grotto|Scorched Grotto]] where two baby red dragons spawn and the adult dragons cannot reach.
* [[Temple Spider|Temple spiders]] are quicker to kill, due to having more spawns and being in a [[multicombat area]]. While the [[Dwarf multicannon|cannon]] is not available for use in the dungeon, it is extremely efficient to use [[Ancient Magicks|ancient spells]], [[Chinchompa|chinchompas]], or other multi-target attacks on the spiders to find all pages quickly.
* The [[Undead Druid|undead druids]] in the south-west room offer players a less click-intensive and more sustainable method to hunt for the pages. Players can avoid all damage by attacking them from outside of melee range and praying against magic, restoring their prayer points at the nearby [[Altar (Forthos Dungeon)|altar]] when needed. Players can kill the druids indefinitely until the pages are found without needing to resupply. Additionally, the druids are [[undead]] and thus susceptible to the effects of the [[Salve amulet(ei)|salve amulet]]. '''Note: This method does not work if [[Olbertus]] has [[Cursed Altar|cursed the altar]].'''

Once four of each page has been obtained, head west from Brother Aimeri and then north from the [[Grubby Chest|grubby chest]] into a library area with [[undead druid]]s; it is recommended to have the [[Protect from Magic]] [[Prayer]] active, as their magic attacks are accurate and hit hard. Search all except the north-western [[musty bookshelf|bookshelves]] in the temple library; you should have obtained three tomes: the [[tome of the sun]], [[tome of the moon]], and [[tome of the temple]].
[[File:Forthos Dungeon - Temple Library.png|thumb|The temple library, where the tomes are found.]]
Use the pages on the respective tomes. Once filled, they can be used on [[Logosia]] in the centre of the [[Arceuus Library]], completing the miniquest.
"""
