quest = "Bone Voyage"
step_count = 4

[[steps]]
index = 0
name = "Starting out"
links = ["Curator Haig Halen", "Varrock Museum", "Morytania", "barge foreman", "Digsite"]
text = """
[[File:Curator Haig Halen chathead.png|left]]
Talk to [[Curator Haig Halen]] at the [[Varrock Museum]]. Ask if he has any interesting news. He will tell you that they have found an interesting island north of [[Morytania]], and that they believe it may be of archaeological significance. They are in the process of making the final preparations for the voyage, and he has recommended you talk to the [[barge foreman]], who has requested the aid of a qualified and experienced adventurer. Agree to help, and make your way to the [[Digsite]].
"""

[[steps]]
index = 1
name = "The finishing touches"
links = ["canal barge", "Digsite", "barge foreman", "magic logs", "Great Kourend", "Sawmill operator", "Sawmill", "Lumber Yard", "Woodcutting Guild", "sawmill proposal", "Hosidius", "Xeric's talisman", "Tithe Farm", "minigame teleport", "fairy ring", "Berry (Woodcutting Guild)", "Varrock", "sawmill agreement"]
text = """
Head to the [[canal barge]] north of the [[Digsite]]. There, speak to the [[barge foreman]] in front of the barge. They are in the final stages of preparation, but there are a few minor adjustments he'd like to make to the barge before getting the crew ready. He requires a sturdier type of wood to keep the barge afloat; [[magic logs]] will not do, since they had peculiar side effects (which you will learn later). He will require a high-grade wood found only in the [[Great Kourend|distant Western lands]] - redwood.

The barge foreman will instruct the player to talk to the [[Sawmill operator]] at the [[Sawmill]] north-west from the barge.

Travel to the [[Lumber Yard]] and speak to the Sawmill operator. In order to obtain redwood planks, he has arranged a fairly generous deal between himself and the sawmill in [[Great Kourend]]'s [[Woodcutting Guild]]. He will give you a [[sawmill proposal]], which you will have to deliver to the Woodcutting Guild.

Now, travel to the Woodcutting Guild in [[Hosidius]] using your skills necklace, or [[Xeric's talisman|Xeric's Talisman - Xeric's Lookout]] which is fairly close. Ironmen may want to use the [[Tithe Farm|Tithe farm]] [[minigame teleport]] instead (Must have entered farmer Gricollers' guild before. Otherwise travel from Veos in Port Sarim, or use [[fairy ring]] {{Fairycode|AKR}}), and hand the proposal to the Woodcutting Guild Sawmill operator. If you don't have the requirements to enter the Woodcutting Guild, try to open the eastern gate to the guild to complete this step; [[Berry (Woodcutting Guild)|Berry]] will sign it on behalf of the guild's sawmill operator.

Return to the [[Varrock]] Sawmill operator, and give him the [[sawmill agreement]].
"""

[[steps]]
index = 2
name = "The cursed voyage"
links = ["barge foreman", "Canal barge", "barge guard", "Lead Navigator", "anchovies", "magic logs", "Crandor", "Rusty Anchor Inn", "Port Sarim", "amulet of glory", "Teleport to House", "Rat Pits", "Minigame teleport", "Jack Seagull", "bone charm", "Odd Old Man", "Silvarea", "Ahab", "potion of sealegs", "Junior Navigator", "Silvarea mine", "Digsite", "Apothecary", "Varrock", "marrentill potion (unf)", "vodka"]
text = """
[[File:Bone Voyage.png|thumb|250px|The completed barge.]]
Go back to the [[barge foreman]], who will ask you to board the [[Canal barge|barge]]. Speak to the [[barge guard]], and he will let you board the barge. On the barge, speak to the [[Lead Navigator]]. First, confirm that you are here to help them out. Then he will ask you if you are aware of the previous attempts at the expedition. Pick the first option if you wish to know what happened. Otherwise, pick the second to skip the dialogue.

*The first barge had some serious design flaws... it didn't float.
*The second barge suffered from 'feature creep'. Senior museum staff stuck their oar in and added unnecessary features: 'go-faster stripes', a portable fossil centrifuge and a walk-on mini-museum. Needless to say, it had... buoyancy issues.
*The third barge made it out to sea, but a special sealant was used that attracted sea monsters. They didn't make it very far.
*The fourth also used a special sealant, this one attracted icebergs.
*The fifth barge crashed into the sixth.
*We lost the seventh one.
*The eighth barge is still here, we think. An accident involving a magical explosion and some talking [[anchovies]] means that it is now believed to reside 12 seconds out of phase.
*The ninth version was built with [[magic logs]]. The barge gained some form of rudimentary sentience. It developed serious depression and ran itself aground near [[Crandor]].

Thus, he will believe the voyage is cursed, and will refuse to sail unless you can ensure the safety of the crew from this curse. He asks you to talk to some experienced sailors in the [[Rusty Anchor Inn]] in [[Port Sarim]].

Teleport and go to the Rusty Anchor Inn in [[Port Sarim]] using an [[amulet of glory|amulet of glory (Draynor)]], Rimmington [[Teleport to House|house teleport]], or the [[Rat Pits]] [[Minigame teleport]]. Talk to [[Jack Seagull]] in the Rusty Anchor Inn, and ask him if he has ever made any cursed voyages. He will claim that you need a lucky [[bone charm]], and that you should speak to the [[Odd Old Man]] in [[Silvarea]] to get one. [[Ahab]] will interrupt, claiming that a '[[potion of sealegs]]' will have you sail the voyage unscathed. You decide that you'll ask the navigators which one they'll prefer to have.

Return to the Lead Navigator. He will want the potion of sealegs, but the [[Junior Navigator]] wants the bone charm instead.

Visit the Odd Old Man (the rag and bone man) by the [[Silvarea mine]], north of the [[Digsite]], and ask for a lucky charm. Tell him that you're making a cursed voyage to receive the bone charm.

Speak to the [[Apothecary]] in [[Varrock]] south-west of Varrock Square (you will need to select "Talk about something else"). He will require a [[marrentill potion (unf)]] and two bottles of [[vodka]]. Speak to him again to receive the potion of sealegs.
"""

[[steps]]
index = 3
name = "The "cursed" voyage"
links = ["barge", "Junior Navigator", "bone charm", "Lead Navigator", "potion of sealegs", "Fossil Island"]
text = """
[[File:Bone Voyage - sailing the ocean blue.png|thumb|250x250px|Sailing the treacherous waters to Fossil Island.]]
Return to the [[barge]], and give the [[Junior Navigator]] the [[bone charm]] and the [[Lead Navigator]] the [[potion of sealegs]].

[[File:Barge controls.png|left|thumb|The barge controls.]]
Unsurprisingly, the potion has made everyone except the Junior Navigator pass out. As he has never navigated open waters, you will now have to steer the barge. You will have to steer the rudder left, right, or straight using the controls on the interface. The progress bar will indicate how far you have to go to reach the island; going too far off course will reduce your progress. If it takes too long, the boat will get lost and the crew will wake up; simply talk to the Junior Navigator to start again.

Tips to get there quickly:

*When the top arrow tilts to the left, click on the right arrow a couple of times to tilt the rudder.
*When the top arrow tilts to the right, click on the left arrow a couple of times to tilt the rudder.
*When the top arrow is mostly straight ahead, click on the arrows to centre the rudder.
*Changing the height of the sails will alter how drastically the boat shifts from side to side. Having the boat's sails as large as possible when going in a straight line will allow for faster travel. It's possible to successfully navigate to the island by leaving the sails fully deployed the whole time.

Once the progress bar is filled, you will arrive at [[Fossil Island]].

'''Congratulations, quest complete!'''
"""
