quest = "The Golem"
step_count = 4

[[steps]]
index = 0
name = "Optional Diary Tasks"
links = ["pickaxe", "bracelet of clay", "clay", "bird snare", "Digsite pendant", "Digsite teleport", "Eagles' Eyrie", "necklace of passage", "Uzer", "Phoenix Feather", "Desert Phoenix", "Desert Diary", "soft clay", "Golden warbler", "Bird snare", "Waterskin", "knife"]
text = """
{{Needed|[[pickaxe]], [[bracelet of clay]] or 4 [[clay]], [[bird snare]]|recommended=[[Digsite pendant]] or [[Digsite teleport]], a woodcutting axe for another diary task later|skills={{SCP|Thieving|25}} {{Boostable|yes}} to steal a phoenix feather, {{SCP|Hunter|5}} {{Boostable|yes}} to catch a golden warbler}}
This quest takes place in the vicinity of several diary tasks which may be optionally completed. This is recommended as several of the tasks may also save you time during the quest. You may choose to teleport to [[Eagles' Eyrie]] with the [[necklace of passage]], complete the tasks and then head south-east towards the Ruins of [[Uzer]] where the quest takes place.

{{Checklist|
*Steal a [[Phoenix Feather]] from the [[Desert Phoenix]] ({{SCP|Thieving|25}}) for both a medium [[Desert Diary]] task and use in the quest itself.
*Mine 5 pieces of [[clay]] for an easy [[Desert Diary]] task (4 of which can be used in the quest itself but require a method such as mining it with a bracelet of clay to turn it into [[soft clay]]).
*Catch a [[Golden warbler|Golden Warbler]] with a [[Bird snare|Bird Snare]] ({{SCP|Hunter|5}}) for an easy [[Desert Diary]] task.
*Fill a [[Waterskin]] with water by cutting a Khardian cactus with a [[knife]] for an easy [[Desert Diary]] task.
}}

{{Map|3422,3162|r=5|mtype=square|align=right|width=220|height=220|caption=The clay mining spot. The desert phoenix can also be found nearby.}}
"""

[[steps]]
index = 1
name = "Repairing the golem"
links = ["soft clay", "bracelet of clay", "pickaxe", "Digsite pendant", "Digsite teleport", "Uzer", "necklace of passage", "Eagles' Eyrie", "fairy ring", "clay", "jug of water", "Oasis", "Thammaron", "Letter (The Golem)", "The Digsite", "Varrock", "black mushroom", "strange implement", "Shadow of the Storm", "Desert Diary", "Teak tree"]
text = """
{{Needed|4 [[soft clay]] '''or''' a [[bracelet of clay]] and a [[pickaxe]]|recommended=[[Digsite pendant]] or [[Digsite teleport]], a woodcutting axe for a diary task|skills={{SCP|Woodcutting|35}} {{Boostable|yes}} if completing an optional diary task}}

Travel to the Ruins of [[Uzer]]. You can use a [[necklace of passage]] to the [[Eagles' Eyrie]] or [[fairy ring]] {{fairycode|dlq}}.

Talk to the broken clay golem to learn it is in need of repair. Use each piece of [[soft clay]] on it to slowly repair it. If you didn't already, you can mine [[clay]] at the north-western mine with a [[bracelet of clay]]. If you didn't bring a bracelet, there is a [[jug of water]] in the [[Oasis]] to the south of Uzer that may be used on the clay to make soft clay (world hop to respawn it).

Once fully repaired, the golem will explain that he was programmed to destroy a powerful demon, [[Thammaron]], and that he needs assistance to open a portal to defeat it. '''Ask him how to open the portal''',  and he will explain that four statuettes in the temple must be turned to the correct pattern, but he doesn't know it.

Outside the temple ruins, near the golem, there is a [[Letter (The Golem)|letter]]. Take the letter and read it; it describes how an expedition here was discontinued after the opening of [[The Digsite]] near [[Varrock]].

Head east into the temple by climbing down the stairs behind the golem. Once inside, pick a [[black mushroom]] by the entrance, then pick up the [[strange implement]] in the north-western corner.

:'''Tip:''' Pick a second for [[Shadow of the Storm]], and keep the strange implement for the same quest. If you brought an axe, you may also choose to complete a medium [[Desert Diary]] task here by cutting the [[Teak tree]] ({{SCP|Woodcutting|35}}) behind the ruins, indicated on the minimap with a tree icon.
"""

[[steps]]
index = 2
name = "The Digsite"
links = ["Digsite", "Elissa", "digsite pendant", "gnome glider", "Exam Centre", "Varmen's notes", "Uzer", "Varrock Museum", "Curator Haig Halen", "pickpocket", "display cabinet key", "statuette (The Golem)"]
text = """
{{Needed|skills={{SCP|Thieving|25}} {{Boostable|yes}} to pickpocket Curator Haig}}
{{Map|name=Elissa|x=3374|y=3434|r=4|mtype=square|align=left|width=240|height=240|caption=The location of Elissa.}}
Head to the north-eastern corner of the [[Digsite]] to find [[Elissa]], the author of the letter. The fastest method of reaching her is a [[digsite pendant]] or [[gnome glider]].

Talk to her about the letter, and she will suggest you look in the [[Exam Centre]] for her late husband's notes, the man whom led the discontinued Uzer expedition.

Head to the [[Exam Centre]] and search the south-eastern most bookshelf to find [[Varmen's notes]]. '''Read them''' before progressing; Varmen describes in detail the discovery of the golems and the great city of [[Uzer]], and mentions taking a statuette from the ruins. Return to Elissa and ask where the statuette went, and she will point you towards the [[Varrock Museum]].

[[File:The Golem - stealing statuette.png|thumb|224px|The player steals the statuette.]]

Go to the [[Varrock Museum]] and ask [[Curator Haig Halen]] on the {{FloorNumber|uk=0}} about a missing statuette. Then, [[pickpocket]] him to get a [[display cabinet key]] ({{SCP|Thieving|25}}).

:'''Note:''' Ensure that you have read the notes and completed all prior dialogue if the dialogue options do not appear.

Unlock Display Case 30 upstairs to steal the [[statuette (The Golem)|statuette]]. It is on the {{FloorNumber|uk=1}} in the first row, the fourth case after you ascend the stairs.

:'''Note:''' If you lose the statuette, you can use the display cabinet key on the empty display cabinet to receive a new one.

{{Clear|left}}
"""

[[steps]]
index = 3
name = "Returning to Uzer"
links = ["vial", "pestle and mortar", "statuette (The Golem)", "papyrus", "Phoenix feather", "Uzer", "chisel", "hammer", "gems", "Door (Ruins of Uzer)", "Thammaron", "Throne (Thammaron's throne room)", "rubies", "emeralds", "sapphires", "black dye", "phoenix quill pen", "Golem program"]
text = """
{{Needed|An empty [[vial]], [[pestle and mortar]], [[statuette (The Golem)|statuette]], black mushroom (obtainable in Uzer dungeon), Strange implement, [[papyrus]], [[Phoenix feather]] (obtainable near the clay mines north of [[Uzer]]), [[chisel]] and [[hammer]] (optional, for cutting [[gems]]).}}

[[File:The Golem - desert phoenix.png|thumb|left|210px|The Desert Phoenix, near the clay mine.]]
[[File:The Golem - the alcove.png|thumb|200px|The alcove in the centre where the statuette goes.]]
[[File:The Golem - Thammaron's remains.png|thumb|200px|The dead demon.]]
Ensure you have the required items and return to [[Uzer]]. Enter the dungeon near the golem, then use the statuette on the empty alcove on the wall in the centre. Turn all of the statuettes north to face towards the [[Door (Ruins of Uzer)|double doors]] to unlock the demon's lair. The east statues should face right and the west statues should face left when the player examines them. The statues will lock and the doors will automatically open. Go inside to discover that [[Thammaron]] had succumbed to his wounds long ago after the battle with the golems.

:'''Note:''' You may optionally use a chisel and hammer on the [[Throne (Thammaron's throne room)|throne]] to take 2 cut [[rubies]], 2 [[emeralds]], and 2 [[sapphires]]  for yourself.

Return to the golem to inform him of the demon's death. He does not believe the player - you will need to reprogram him to put his mind to rest.

With an empty vial in your inventory, use your pestle and mortar on the black mushroom to make [[black dye]]. Use the phoenix feather on your ink to make a [[phoenix quill pen]], then use it on your papyrus to write a [[Golem program]].

Use the strange implement on the golem followed by the golem program, and the golem will declare that his task is complete.

'''Congratulations, quest complete!'''
"""
