quest = "Cold War"
step_count = 8

[[steps]]
index = 0
name = "Penguin spotting"
links = ["oak plank", "steel nails", "hammer", "spade", "Dramen", "Lunar", "Fairy ring network", "Ardougne", "Ardougne cloak 1", "Larry", "Ardougne Zoo", "penguin", "Rellekka", "Iceberg", "fairy ring", "The Giant Dwarf", "Grand Exchange", "enchanted lyre", "Camelot", "cutscene", "Emotes", "emotes", "clockwork suit", "Clockwork book"]
text = """
{{Needed|10 [[oak plank]]s, 10 [[steel nails]], a [[hammer]], and a [[spade]].|recommended=[[Dramen]] or [[Lunar]] staff (as well as a teleport to access the [[Fairy ring network]]), [[Ardougne]] teleport runes or [[Ardougne cloak 1]] or higher (to get to Ardougne and start the quest).}}
[[File:Cold War - Finished bird hide structure.png|thumb|220px|The finished bird hide structure.]]

Speak to [[Larry]] at the south entrance of the [[Ardougne Zoo]]. He's a bit nutty about [[penguin]]s. Larry hopes to build a lookout to observe the penguins. His instructions are to collect him 10 [[oak plank]]s, 10 [[steel nails]], a [[hammer]] and a [[spade]]. When you have your supplies, talk to him again and tell him that you have the materials to build the lookout (He also says to meet him north-east of [[Rellekka]], but this is not necessary). He will now teleport you to the [[Iceberg]]. Accept the teleportation prompt (you can't have any pet following you, otherwise you won't be teleported).

''If you opt out of Larry's offer or ever need to get to the meeting location without his teleport, you have to go to the north-east of the rock crabs, and can teleport very close to it with the [[fairy ring]] code {{fairycode|dks}} (just walk down the mountain and a small bit north-west to the dock). If you have completed [[The Giant Dwarf]], you can use the [[Grand Exchange]] trapdoor to shortcut to Rellekka. You can also use the [[enchanted lyre]] to teleport to Rellekka and walk to the meeting spot. If no closer teleport is available to you, teleport to [[Camelot]] and walk north. '''If you leave an area during any point in the quest, Larry will not teleport you back and you'll need to make your way there yourself. Prepare for this if necessary.'''''

Upon arrival, you'll see a firm snow patch next to the landing spot. Build the lookout here by using an oak plank on the patch. Then, use a [[spade]] on the lookout to cover it in snow. You can also use the dig option on the spade while standing near the lookout.

[[File:Cold War - Spying on penguins.png|thumb|220px|Spying on the penguins.]]

When the lookout is ready, speak to Larry. This will be followed by a rather strange [[cutscene]]. '''Keep note of the emotes the penguin does, as the emote greeting code is unique for every player and will need to be used, in order, for several later parts of the quest.''' There are eight different [[Emotes#Penguin emotes|penguin emotes]] in all, similar to the normal character [[emotes]], and the greeting will consist of three of those. If you need to see them again, click "Use Snowy bird hide" to watch the cutscene again. After the cutscene, speak to Larry and suggest to him that the behaviour of the penguins in the cutscene was suspicious.

{| class="wikitable lighttable align-center-2 align-center-3"
!Emote
!Image
!Animation
|-
|Shiver
|[[File:Shiver (Penguin) emote icon.png]]
|[[File:Shiver.gif|70x70px]]
|-
|Cheer
|[[File:Cheer (Penguin) emote icon.png]]
|[[File:Penguin cheer.gif|70x70px]]
|-
|Spin
|[[File:Spin (Penguin) emote icon.png]]
|[[File:Penguin spin.gif|70x70px]]
|-
|Wave
|[[File:Wave (Penguin) emote icon.png]]
|[[File:Penguin wave.gif|70x70px]]
|-
|Clap
|[[File:Clap (Penguin) emote icon.png]]
|[[File:Penguin clap.gif|70x70px]]
|-
|Preen
|[[File:Preen emote icon.png]]
|[[File:Preen.gif|70x70px]]
|-
|Bow
|[[File:Bow (Penguin) emote icon.png]]
|[[File:Penguin Bow.gif|70x70px]]
|-
|Flap
|[[File:Flap (Penguin) emote icon.png]]
|[[File:Penguin flap.gif|70x70px]]
|}

Use the boat or the 'travel' option on Larry to return to the dock and speak to Larry again - now, here's where things get strange. Larry requests to now design a [[clockwork suit]], which will be used to spy on the penguins. He gives a [[Clockwork book|book]] filled with instructions.
"""

[[steps]]
index = 1
name = "The clockwork suit"
links = ["clockwork", "crafting table 3", "Player-owned house", "workshop", "crafting table 2", "plank", "games necklace", "Barbarian Outpost", "Port Khazard", "silk", "Ardougne Market", "steel bar", "Clockwork", "inventory", "clockwork suit"]
text = """
{{Needed|A plank, a piece of silk, and a [[clockwork]] or a steel bar to make one (access to a [[crafting table 3]] or better is also required. It must either be built by the player in their own [[Player-owned house|player-owned house]] (also requiring the prerequisites to do so, those being having a [[workshop]] and [[crafting table 2]] to upgrade) or one must be accessed in another player's house).}}

Collect a regular wood [[plank]] (the [[games necklace]] teleport is handy here; just teleport to the [[Barbarian Outpost]] and head east a bit to find some planks. Or, go just south-east of the zoo to pick one up at [[Port Khazard]]), a piece of [[silk]] (steal one at the [[Ardougne Market|East Ardougne market place]] if you have level 20+ Thieving) and a [[clockwork]] (or a [[steel bar]] if you're making one).

If making one, use the clockmaker's bench ([[crafting table 3]]) at your [[Player-owned house|house]] (or someone else's) to make a [[Clockwork|clockwork mechanism]] with the steel bar in your [[inventory]]. Then, use the clockmaker's bench again and select "clockwork toy" followed by "clockwork penguin" to make the [[clockwork suit]] with the plank, the piece of silk, and the clockwork mechanism in your inventory.
"""

[[steps]]
index = 2
name = "Back to the Iceberg"
links = ["Dramen", "Lunar", "Fairy ring network", "GE", "raw cod", "ring of charos (a)", "Larry", "Clockwork suit", "Rellekka", "Ardougne Zoo", "Iceberg"]
text = """
{{Needed|recommended=To avoid unnecessary banking, bring a [[Dramen]] or [[Lunar]] staff and teleport runes to access the [[Fairy ring network]] (Alternative: Varrock/[[GE]] teleport runes to take the Kelda mine cart back to Larry), a [[raw cod]] or [[ring of charos (a)]], and multiple teleportations to Lumbridge.}}

Return to [[Larry]] after finishing the [[Clockwork suit|suit]] (in the north-east of [[Rellekka]] or at the [[Ardougne Zoo]]) Then, return to the [[Iceberg]] with him to test it out.

After returning, you come to find out that the lookout has been completely destroyed and that all the penguins are missing. Speak to Larry, and to no surprise, he will blame the penguins. Now, since there are no penguins, it appears impossible to test the suit. However, being the clever adventurer, you will suggest that the suit be tested on the penguins at the zoo. Larry will kindly assist with a teleport back to the [[Ardougne Zoo]], should you accept.
"""

[[steps]]
index = 3
name = "Meet the penguins"
links = ["Raw cod", "ring of charos (a)", "Larry", "Clockwork suit", "Penguin (Cold War)", "cutscene", "Ardougne Zoo", "Mission report (Ardougne)", "Lumbridge", "Between a Rock...", "Enlightened Journey", "Crazy penguin", "Fred the Farmer", "Sheep Shearer", "inventory", "raw cod"]
text = """
{{Needed|[[Raw cod]] or [[ring of charos (a)]].|recommended=Teleportation methods to Lumbridge.}}
[[File:Cold War - Disguised as penguin.png|thumb|220px|The player, disguised as a penguin.]]

Free your hand and cape slots and talk to [[Larry]]. He will then cast a magic spell. The magic causes a player to shrink and enter the [[Clockwork suit|penguin suit]]! Now, test out the disguise. Head into the penguin enclosure and right click on the penguins until you find one with the talk option. Talk to that [[Penguin (Cold War)|penguin]], and you will be forced to give him a greeting before he shall speak to you; this is different for each player. Use the emote sequence that the earlier [[cutscene]] showed. If you do not know the sequence it is too late to go back and find out, but fortunately you can guess the emotes and will be told as soon as you make a mistake. This means a maximum of 24 guesses are needed, not 512! The penguin will start talking once you're successful, and will reveal that they're trying to learn how to fly in order to escape from the [[Ardougne Zoo]]. The penguin will give you a [[Mission report (Ardougne)|mission report]] to return to the ''outpost'' and ask you to speak to the penguins in [[Lumbridge]]. Note that the mission report received will be different depending on whether the player completed the quests [[Between a Rock...]] and/or [[Enlightened Journey]]. At this point, this will determine whether two [[Crazy penguin]] NPCs will appear in the game or not and '''the outcome will be permanent, even if the related quests are later completed'''.


Leave the cage and speak with Larry. You will discuss where penguins could be in [[Lumbridge]]. Now, head to [[Lumbridge]].

In Lumbridge, head to [[Fred the Farmer]]'s sheep pasture where you will find Larry; use the tuxedo time option with him (don't forget to remove everything from your hand and cape slots). Now, head off and find a "sheep" with flippers and a talk option (if you've done the quest [[Sheep Shearer]], you may remember this "sheep" as the "Thing"). Talk to the "sheep" and perform the secret greeting (which remains the same as the previous step). The penguins in the sheep disguise will tell you to go away, demanding a secret phrase in addition to the secret greeting.

Speak to Larry, and he will help you both return to the [[Ardougne Zoo]]. When you have either the raw cod in your [[inventory]] or are wearing a [[ring of charos (a)]], re-tuxedo and enter the penguin enclosure once more and speak to the penguin again. If you are not wearing the ring, he will not give you the phrase, requesting a [[raw cod]] in exchange for it, the penguins' favourite food. If you are wearing the ring, he will simply provide it in the conversation, telling you that the secret phrase is ''do not trust the walrus''.
"""

[[steps]]
index = 4
name = "Intelligence"
links = ["Swamp tar", "feather", "Lumbridge", "Lumbridge Swamp", "food", "Mahogany plank", "Leather", "cowbells", "Fred the Farmer", "Iceberg", "mahogany plank", "leather", "Combat equipment", "Larry", "KGP Agent", "Noodle", "Kgp id card", "Penguin agility course", "cutscene"]
text = """
{{Needed|[[Swamp tar]], five white [[feather]]s, (both can be obtained during this part, but the [[Swamp tar]] is some distance away), and the Mission Report.}}

Make your way to [[Lumbridge]] (Larry does not provide a teleport this time). If you don't have swamp tar yet, head south to the [[Lumbridge Swamp]] and pick some up. Then, head north to the farm again. If you need feathers, kill enough chickens to obtain five of them. If you can, grab the items  (''[[food]]'' ''if low combat level level or at the minimum agility requirement for the quest, [[Mahogany plank]], [[Leather]],  and a [[cowbells|cowbell]])''  for the next steps as a bank will be far away. Go to [[Fred the Farmer]]'s sheep pen and penguin suit up! Talk to the "sheep" again. Now, the penguins will tell you to talk to Fred the Farmer to see if he's an undercover agent for the humans.

[[File:Cold War - Bullying Fred.png|thumb|220px|Bullying [[Fred the Farmer|Fred]] in order to obtain the information from the disguised penguins.]]

Exit your penguin suit and speak to Fred the Farmer about penguins. Use either the bully option or warn option. Both work. When you are done talking to Fred, return and speak with the penguin again. Pick either option in the conversation with the penguin and then they will give you the location of the outpost - it is on the [[Iceberg]] you visited earlier under what appears to be an avalanche. They will also give you a password: ''cabbage''.

'''It is advised you steal a cowbell now from a nearby dairy cow before proceeding to next section of the quest (one can be stolen to the north or east of the sheep pen).'''

'''It is also recommended to obtain the last remaining items for this quest now in order to save time later on (those items being a [[mahogany plank]] and [[leather]]. Optionally, [[Combat equipment]] and [[food]] if you have a low combat or agility  level).'''

Speak to [[Larry]], and he will teleport you to the Iceberg. Suit up to penguin again and head north-west until you see a [[KGP Agent]] penguin. Talk to him and use the emote greeting; then, tell him the password, and then he will ask you for an ID but, guess what, you don't have one!

Now, speak to [[Noodle]]. He's the black market merchant close to the KGP agent, and he'll trade you an ID and a report if you give him one swamp tar and five feathers.

'''Note:''' If you do not have space in your inventory, you will not gain the required 3rd report and will not be notified of it.

[[File:Cold War - Debriefing.png|thumb|220px|Being debriefed by the [[KGP Agent]].]]

Exchange the materials with Noodle for the [[Kgp id card|ID]] and another mission report. Speak to the KGP agent and he'll let you through; then, left click on the avalanche and you should see the option ''use avalanche'' and you will enter the outpost.

:'''Note:''' Whenever you wish to leave the outpost, simply removing the penguin suit will have you teleported back to Larry.

Once inside, go into the first room on the left (West), and talk to the KGP agent to be debriefed there; once done, head into the corridor on the other side of the room; you will now have to complete an [[Penguin agility course|agility course]].

[[File:Cold War - Penguin army.png|thumb|220px|The penguin army!]]

Once you have exited the door at the end of the corridor, you shall see a small [[cutscene]] showing a penguin army! Suddenly, you realise their intentions are a little more devious than just flying! Follow the signs with arrows to the agility course, and when the path ends, just past some blue crates; turn past the crates to start the agility course.
"""

[[steps]]
index = 5
name = "Agility course"
links = ["Food", "Penguin agility course", "cutscene", "Agility Instructor", "Clockwork suit"]
text = """
{{Needed|recommended=[[Food]] (if low combat level level or at the minimum agility requirement for the quest)}}

Climb down the steps and into the water. Avoid the moving ice in the water. Climb the stepping stone at the end.

Jump to the next stepping stone. Jump to the five next stones. (If you fail you will take minor damage). Then, jump to the land on the other side.

After you manage to cross, continue on the path until you come to a shelf with icicles on it. Use the ''tread softly'' option to get across. You will have to repeat this several times at each shelf. If you fail, you will be hit taking a small amount of damage.

Next, you will have to cross ice; this may prove a little annoying. You will take 2 damage each time you fail.

:[[File:Cold War - Penguin agility course.png|thumb|220px|Crossing the [[Penguin agility course|agility course]].]]

After that, you will see a small [[cutscene]] of you sliding down a hill.

Speak to the [[Agility Instructor]], who will tell you that you have completed the agility arena and are free to return whenever you like.

:'''Note:''' You may re-enter the [[Penguin agility course|agility course]] after completion of the quest if you have made another [[Clockwork suit|penguin suit]].
"""

[[steps]]
index = 6
name = "Discover the penguin plan"
links = ["Mahogany plank", "Leather", "Cowbells", "Combat equipment", "food", "Larry", "Clockwork suit", "dairy cow", "Penguin bongos", "fairy ring", "Rellekka", "Zanaris", "Ardougne Zoo", "KGP Agent", "Kgp id card", "Ping", "Pong", "The Penguin Bards", "cowbells", "penguin bongos", "cutscene", "control panel (Cold War)"]
text = """
{{Needed|[[Mahogany plank]], [[Leather]], [[Cowbells|cowbell]].|recommended=[[Combat equipment]] and [[food]] (if low level)}}

Return to [[Larry]] (take off your [[Clockwork suit|penguin suit]] to be thrown (teleported) out of the facility and right next to him, or go through the gate and walk back the way you came) and tell him about the army you saw! He will tell you he needs you to find where they are making their war plans.

If you haven't already, find a [[dairy cow]] and steal a cowbell. One is located in south-east Rellekka. Then, use your [[Mahogany plank|Mahogany Plank]] on the [[Leather]] to make [[Penguin bongos|Penguin Bongos]]. If you have access to the [[fairy ring]] network and '''are not equipped for the upcoming fight''', you can quickly bank by taking the boat back to [[Rellekka]], and using the fairy ring just east of the dock (D•K•S). There is also a dairy cow just on the other side of the field in [[Zanaris]]. Return to the Iceberg (This time, Larry will not teleport you from [[Ardougne Zoo]] or the Lumbridge sheep pen; you will need to take the boat east of [[Rellekka]].)

Tuxedo up and return to the outpost (use avalanche), but instead of turning left this time, head straight until you come to a set of massive doors. Ask the [[KGP Agent]] in the booth to the left of the doors to let you in. He will ask you for your [[Kgp id card|ID]] and say you do not have the clearance to go through the doors.

[[File:Cold War - Ping and Pong play.png|thumb|220px|[[Ping]] and [[Pong]], playing with their new instruments.]]
{{Listen
|title = [[The Penguin Bards]]
|desc = The music played by Ping and Pong.
|filename = The Penguin Bards.ogg
}}
Head back down the hallway and enter the eastern room with [[Ping]] and [[Pong]]. They will ask you for a [[cowbells|cowbell]] and a set of [[penguin bongos]]. Talk to them again to give them the items.

During a [[cutscene]], the guard will become distracted by their harmonious vibes. Leave the room and use the [[control panel (Cold War)|controls]] where the KGP agent used to be standing to open the large doors. The war room is to the east.
"""

[[steps]]
index = 7
name = "Caught by Pescaling Pax"
links = ["Penguin Plots", "cutscene", "Gielinor", "icelord", "Larry", "Gigantic penguin"]
text = """
{{Listen
|title = [[Penguin Plots]]
|desc = The music which plays during various cutscenes throughout the quest.
|filename = Penguin Plots.ogg
}}
You will see a [[cutscene]] of the penguins planning to take over [[Gielinor]]! Due to an anti-magic system that was conveniently installed, you'll be compromised and the penguins will throw you into a cage full of [[icelord]]s. To get out, you may have to kill up to three Icelords, though for some players it is possible to exit after killing just one or two '''Warning:''' Each icelord killed grants 40 Attack experience.

Note that should the player teleport out of the icelord cage, they will be sent back to the cage as soon as they arrive to the Iceberg.

Exit the cage through the fence door made of ice; then, exit through a chasm east of the Icelord cage.

Talk to [[Larry]] and inform him of your discovery. Larry will state that he has a lot to do with his other "contacts", telling you that he will call for you again when the time comes.

'''Congratulations, quest complete!'''

<gallery captionalign="left" position="center">
Cold War - Pescaling Pax in the war room.png|The War Room!
Cold War - Caught by Pescaling Pax.png|Your disguise is found out!
Cold War - Giant suit in construction.png|The [[Gigantic penguin|giant penguin]] suit...
</gallery>
"""
