quest = "Desert Treasure I"
step_count = 1

[[steps]]
index = 0
name = "Enchanting the mirrors"
links = ["Shantay pass (item)", "Kharidian Desert", "coins", "blood rune", "ashes", "bones", "charcoal", "molten glass", "magic logs", "steel bar", "Waterskin", "desert clothing", "magic carpet", "ring of charos (a)", "Exam Centre", "digsite pendant", "Varrock", "Al Kharid", "ring of dueling", "amulet of glory", "Shantay Pass", "Bedabin Camp", "Fairy ring", "Kalphite Lair", "Asgarnia Smith", "etchings", "Terry Balando", "Digsite", "translation", "Bandit Camp (Kharidian Desert)", "Saradomin", "Zamorak", "Bartender (The Big Heist Lodge)", "Bandit's brew", "Diamonds of Azzanadra", "Eblis", "general store", "Nature Impling", "Wintertodt", "Brimstone chest", "Revenants", "Hunters' Rumours", "Larran's big chest", "Larran's small chest", "Larran's keys", "Wilderness Slayer", "Yommi tree", "Legends' Quest", "Steel bar", "fire", "Wilderness", "Bones", "Charcoal", "Ancient Pyramid"]
text = """
{{Needed|Two [[Shantay pass (item)|Shantay pass]]es (or another method of entering the [[Kharidian Desert]]), 650 [[coins]], [[blood rune]], [[ashes]], [[bones]], [[charcoal]], 6 [[molten glass]] (noted works), 12 [[magic logs]] (noted works), 6 [[steel bar]]s (noted works)|recommended=[[Waterskin]]s, [[desert clothing]], coins for [[magic carpet]] rides (bring a [[ring of charos (a)]] for discounted rides), teleportation methods to the [[Exam Centre]] ([[digsite pendant]], [[Varrock]] teleport) and [[Al Kharid]] ([[ring of dueling]], [[amulet of glory]]).}}

Travel through the [[Shantay Pass]] south of [[Al Kharid]] and then west via flying carpet or by running to the [[Bedabin Camp]]. [[Fairy ring]] code {{Fairycode|BIQ}}, near the [[Kalphite Lair]], is north-east of the camp. Talk to [[Asgarnia Smith]] near the small water pool; he'll give you some [[etchings]] to bring to [[Terry Balando]], the archaeological expert, at the [[Digsite]] [[Exam Centre]].

Go to the Digsite, east of [[Varrock]], and talk to Terry in the Exam Centre, who will take the etchings. Talk to him again to receive the [[translation]] to take back to Asgarnia Smith.

Go back to Asgarnia Smith in the desert. When talking to him, choose the ''Don't read book'' option. Talk to him again and agree to help.

Go south to the [[Bandit Camp (Kharidian Desert)|Bandit Camp]]. ''Before entering the camp, remove any equipment that depicts [[Saradomin]] or [[Zamorak]] imagery, otherwise the bandits will be aggressive''. Talk to the [[Bartender (The Big Heist Lodge)|bartender]] and buy a [[Bandit's brew|drink]] for 650 [[coins]]. Talk to him again to find out about the four [[Diamonds of Azzanadra]]. '''This step must be completed before talking to Eblis otherwise the option to talk with him about the diamonds won't appear.'''

Talk to [[Eblis]] in a nearby building to the east, past the [[general store]]. Ask him about the diamonds and he'll tell you that he needs various items to create some scrying glasses:

{| class="wikitable"
!Item
!GE Price
!Notes and ironman concerns
|-
|{{plinkp|Magic logs}} x 12
|{{Coins|{{GEP|Magic logs|12}}}}
|There are many ways to obtain magic logs:

* Cutting a magic tree (75 {{SCP|Woodcutting}}, boostable)
* Looting [[Nature Impling|Nature Implings]] (58 {{SCP|Hunter}}, boostable)
* Opening supply crates from [[Wintertodt]]
* Looting the [[Brimstone chest|Brimstone Chest]]
* Defeating various [[Revenants]]
* Completing [[Hunters' Rumours]]
* Opening Larran's [[Larran's big chest|big]] or [[Larran's small chest|small]] chests, using [[Larran's keys]] obtained through [[Wilderness Slayer]]
* Chopping dead [[Yommi tree]]s during [[Legends' Quest]]
|-
|{{plinkp|Molten glass}} x 6
|{{Coins|{{GEP|Molten glass|6}}}}
|Can be made at 1 {{SCP|Crafting}}
|-
|{{plinkp|Steel bar}} x 6
|{{Coins|{{GEP|Steel bar|6}}}}
|Requires 30 {{SCP|Smithing}}, or [[Steel bar#Spawns|dropped by various monsters]]
|-
|{{plinkp|Ashes}} x 1
|{{Coins|{{GEP|Ashes|1}}}}
|Can be obtained from any [[fire]]
|-
|{{plinkp|Blood rune}} x 1
|{{Coins|{{GEP|Blood rune|1}}}}
|4 spawn in the [[Wilderness]]
|-
|{{plinkp|Bones}}x 1
|{{Coins|{{GEP|Bones|1}}}}
|See all bone spawn locations [[Bones|here]]
|-
|{{plinkp|Charcoal}}x 1
|{{Coins|{{GEP|Charcoal|1}}}}
|See all charcoal spawn locations [[Charcoal|here]]
|-
|Total:
|{{Coins|{{GEP|Magic logs|12}}+{{GEP|Molten glass|6}}+{{GEP|Steel bar|6}}+{{GEP|Ashes|1}}+{{GEP|Blood rune|1}}+{{GEP|Bones|1}}+{{GEP|Charcoal|1}}}}
|''It's possible for level three ironmen to obtain all items''
|}
[[File:Desert Treasure mirrors.png|thumb|right|The mirrors, made by [[Eblis]].]]
{{Colour|Red|Wearing a Zamorak item when giving Eblis the items will cause Eblis to not create the scrying glasses!}}

Bring Eblis the items required. Make sure to '''use''' the bones on him instead of burying them, noting them will avoid this.

After giving him the items, Eblis will have travelled south-east on top of a hill (shown as a grey circle on the minimap), surrounded by six mirrors. Looking into them will show locations related to the diamonds, though it is not required.

Talk to Eblis again and he'll explain that his spell only makes the mirrors reveal where the diamonds have been at one point in time. Two of the mirrors show other locations entirely; the [[Bedabin Camp]], which you visited, and the [[Ancient Pyramid]] itself, which you need to acquire the diamonds in order to enter.

If using Runelite, disable the 'Easy Unnote' plug-in, or you will not be able to give Eblis noted items.

'''Diamonds can be acquired in any order. The order below is sorted from easiest to hardest.'''
"""
