quest = "Recipe for Disaster/Freeing the Mountain Dwarf"
step_count = 1

[[steps]]
index = 0
name = "Rewards"
links = ["Slayer", "Cooking", "Culinaromancer's Chest", "dwarven rock cake"]
text = """
----
{{Quest rewards
|name = Recipe for Disaster: Freeing the Mountain Dwarf
|image = [[File:Recipe for Disaster (Freeing the Mountain Dwarf) reward scroll.png|centre]]
|qp = 1
|rewards =
*{{SCP|Slayer|1,000}} [[Slayer]] experience
*{{SCP|Cooking|1,000}} [[Cooking]] experience
*Further access to the [[Culinaromancer's Chest]]
*Ability to obtain additional [[dwarven rock cake]]s from Rohak for either 100 coins or the raw ingredients
}}</onlyinclude>
"""
