quest = "Prince Ali Rescue"
step_count = 3

[[steps]]
index = 0
name = "Setting up (obtaining the required items)"
links = ["coins", "Grand Exchange", "pink skirt", "Thessalia's Fine Clothes", "Varrock", "beer", "Blue Moon Inn", "pot", "logs", "ashes", "south-east Varrock mine", "Tin ore", "copper ore", "bronze bar", "redberries", "south-west Varrock mine", "clay", "Fred the Farmer", "Lumbridge", "sheep", "wool", "onions", "wheat", "pot of flour", "windmill", "Lumbridge Castle", "spinning wheel", "balls of wool", "jug", "soft clay", "Al Kharid"]
text = """
{{Needed|axe, tinderbox, pickaxe, shears, 16 [[coins]]}}
'''Skip this part if you have all the required items''' (can be bought on the [[Grand Exchange]]).

{{Checklist|
*Purchase the [[pink skirt]] at [[Thessalia's Fine Clothes]] immediately south of the [[Varrock]] town square.
*Buy 3 [[beer]]s at the [[Blue Moon Inn]] just south-east of [[Thessalia's Fine Clothes]], and pick up the [[pot]] in the bar.
*Cut down a tree, light the [[logs]], then wait for it to burn out to take the [[ashes]].
*Head to the [[south-east Varrock mine]] and mine one [[Tin ore|tin]] and one [[copper ore]] to later make a [[bronze bar]], and pick one bunch of [[redberries]] from the nearby bushes.
*Head to the [[south-west Varrock mine]], and mine one [[clay]].
*Head to [[Fred the Farmer]]'s pen north of [[Lumbridge]] and shear three [[sheep]] for [[wool]]. Pick two [[onions]] from the garden behind his house.
*Pick some [[wheat]] from the nearby grain field, then make a [[pot of flour]] at the [[windmill]].
*Spin the wool on the {{FloorNumber|uk=1}} of the [[Lumbridge Castle]] using the [[spinning wheel]] to get three [[balls of wool]].
*Take the [[jug]] from the castle's kitchen basement and fill it with water, then use it on your [[clay]] to create [[soft clay]].
*Head to [[Al Kharid]] through the toll gate to the east across the river with your 10 [[coins]], and smith a [[bronze bar]] on the furnace there.
}}

The remaining items can be gathered during the quest.
"""

[[steps]]
index = 1
name = "Planning a rescue"
links = ["balls of wool", "rope", "Ned", "onion", "yellow dye", "redberries", "pot of flour", "ashes", "bucket of water", "jug of water", "soft clay", "bronze bar", "pink skirt", "coins", "Al Kharid palace", "Al Kharid", "Chancellor Hassan", "Osman", "Draynor Village", "Leela", "Aggie", "Paste", "flour", "water", "Draynor", "jail guard", "Lady Keli", "key print", "Bronze key (Prince Ali Rescue", "Lumbridge", "Members", "Amulet of glory", "Edgeville"]
text = """
{{Needed|3 [[balls of wool]], [[rope]] (unless buying from [[Ned]]), 2 [[onion]]s '''or''' [[yellow dye]], 1 [[redberries]], [[pot of flour]], [[ashes]], a [[bucket of water]] or [[jug of water]], [[soft clay]], a [[bronze bar]], 3 normal beers, a [[pink skirt]], and 30 [[coins]] (unless teleporting)}}
[[File:Chancellor Hassan chathead.png|left|frameless]]
{{Map|name=Leela|x=3113|y=3262|plane=0|r=3|mtype=square|caption=Leela's location just east of Draynor Village.|align=right|width=250|height=250}}
Head to the [[Al Kharid palace]], located in the south of [[Al Kharid]]. There is a [[jug of water]] in the eastern room if you did not bring one. Talk to [[Chancellor Hassan]] in the southern chamber and ask if he needs help; he will direct you towards Spymaster [[Osman]], who can be found outside the northern perimeter of the palace. Osman will explain that Prince Ali, heir to the Emir of Al Kharid, has been taken by a group of bandits to the abandoned jail just east of [[Draynor Village]]. He wants you to talk to his daughter [[Leela]], who will help you attempt a rescue.

[[Leela]] can be found strolling east of [[Draynor Village]] just south of the wheat field. Talk to Leela and ask her about the key and disguise, and she will explain what you will need to pull off the escape.

To the west of Leela is [[Ned]]'s house. Ask him to make you a wig from the [[balls of wool]]. If you haven't brought a rope, you can buy one from him for 18 [[coins]]. Once you have the rope and wig, talk to [[Aggie]] in the house just west of Ned's, and ask her to make you some [[Paste|paste]]. She will use your [[redberries]], [[ashes]], [[flour]] and [[water]] to make the paste. If you did not bring yellow dye, you can ask her to make it for you in exchange for 2 [[onion]]s and five coins. Use the dye on the wig to dye it yellow.

[[File:Draynor jail front.png|thumb|left|200px|Guards patrolling the Draynor jail.]]

Head inside the jail directly east of [[Draynor]], avoiding the aggressive level 26 [[jail guard]]s. They will ignore you if your combat level is 53 or higher. Once inside, speak to [[Lady Keli]] and tell her she's famous, then ask her about her latest plan, then praise her skill. Ask her how she knows someone won't try to free him, and she'll mention the key. Ask her if you can see the key and then if you can touch the key for a short amount of time. You will make a [[key print]] of the key using the [[soft clay]]. {{Chat option|1Heard of you? You're famous in Gielinor!|1What is your latest plan then?|2How do you know someone won't try to free him?|1Could I see the key please?|1Could I touch the key for a moment please?}}

Once you have the key print, head to any furnace to smelt the [[Bronze key (Prince Ali Rescue|bronze key]] using the key print and your [[bronze bar]]. The closest is in [[Lumbridge]]. [[Members]] may use a [[Amulet of glory]] to teleport to the [[Edgeville]] furnace, and then to teleport to [[Draynor Village]] for the next section.
{{Clear|left}}
"""

[[steps]]
index = 2
name = "Saving the Prince"
links = ["beer", "rope", "pink skirt", "wig", "paste", "Leela", "Joe (jail)", "Lady Keli", "Prince Ali", "Hassan", "Members", "Osman", "Minigame Teleport", "Sorceress's Garden"]
text = """
{{Needed|3 [[beer]]s, [[rope]], a [[pink skirt]], a [[wig]] (dyed yellow), and [[paste]]}}
[[File:Prince Ali chathead.png|left|frameless]]
Talk to [[Leela]], who will tell you to talk to [[Joe (jail)|Joe]] the guard to find a weakness before breaking the prince out.

'''Note''': If she doesn't tell you to talk to the guard, you may have forgotten to dye the wig yellow.

Talk to Joe and offer him a drink of all three beers, until he is drunk. Use the rope on [[Lady Keli]], the key on the cell door, then talk to [[Prince Ali]] and he will use the [[wig]] and [[pink skirt]] as a disguise and escape.

Return to [[Hassan]] in the Al Kharid palace to claim your reward.

'''Congratulations, quest complete!'''

:'''Tip:''' [[Members]] may talk to [[Osman]] outside the palace after the quest to unlock the [[Minigame Teleport]] to the [[Sorceress's Garden]].
"""
