quest = "Devious Minds"
step_count = 4

[[steps]]
index = 0
name = "The monk"
links = ["quest", "Monk (Devious Minds)", "Paterdomus Temple", "Priest in Peril", "River Salve", "Varrock", "Digsite teleport", "Earth Altar", "Lumberyard teleport", "Morytania", "fairy ring", "bow-sword"]
text = """
[[File:Monk (Devious Minds) chathead.png|left]]
You start this [[quest]] by speaking to the [[Monk (Devious Minds)|monk]] just outside the [[Paterdomus Temple]] (this is the temple you encountered during [[Priest in Peril]]), the temple on the [[River Salve]]. It is east of [[Varrock]] and can be reached by walking north-east from the [[Digsite teleport]], or east of the ruins of the [[Earth Altar]] or the [[Lumberyard teleport]]. Or it can be reached by walking west from [[Morytania]]; the closest [[fairy ring]] is {{fairycode|CKS}}.

The monk requires a new, stronger weapon for a certain group of warriors, in order to secure more victories. He wants you to make a [[bow-sword]].
"""

[[steps]]
index = 1
name = "A strange weapon"
links = ["mithril 2h sword", "bow string", "Doric", "Falador", "slender blade", "bow string spool", "bow-sword", "temporary boosts", "dwarven stout", "dwarven stout (m)", "Kovac's grog", "spicy stew", "Smithing", "balloon transport system", "willow logs", "Varrock"]
text = """
[[File:Making slender blade.gif|frame|A player using Doric's whetstone.]]
{{Needed|A [[mithril 2h sword]] and a [[bow string]]}}

To make this bow-sword, take a [[mithril 2h sword]] to [[Doric]]'s house, just north of [[Falador]], and use it on the whetstone inside to make a [[slender blade]], then attach a [[bow string]] (the [[bow string spool]] works) to it to make the [[bow-sword]].

''It is possible to use [[temporary boosts]] ([[dwarven stout]], [[dwarven stout (m)]], [[Kovac's grog]], or [[spicy stew]]) to reach the required [[Smithing]] level of 65.''

When you've made the bow-sword, make your way back to the monk. You can use the [[balloon transport system]] to fly from Taverley back to the Earth Altar by using a set of [[willow logs]], if you have already unlocked the [[Varrock]] destination.
"""

[[steps]]
index = 2
name = "A gift for Entrana"
links = ["bow-sword", "large pouch", "colossal pouch", "Entrana", "Orb (Devious Minds)", "Abyss", "Law Altar", "Large pouch (Devious Minds)", "Rewards Guardian", "Guardians of the Rift", "abyssal leech", "abyssal guardian", "abyssal walker", "Abyssal Area", "Runecraft", "Port Sarim", "giant pouch", "weapons", "armour", "Mage of Zamorak", "Wilderness", "River Lum", "Edgeville", "Dark Mage (Abyss)", "NPC Contact"]
text = """
{{Needed|The [[bow-sword]] and a [[large pouch|large]]/[[colossal pouch]]}}

Give the [[bow-sword]] to the Monk and he will be grateful for it; although he needs one more favour. A special ceremony is to be held on the island of [[Entrana]], though unfortunately the monk cannot attend it and he wants to give them a special present to mark the occasion.

He gives you an [[Orb (Devious Minds)|orb]] to deliver to the church in [[Entrana]]. But for the surprise to work, you must sneak into the church and not be seen entering the island. He advises using the realm of the [[Abyss]] to get to the [[Law Altar]] on [[Entrana]]; he also wants you to keep the orb in a vessel from the realm to avoid it from being damaged. To do this, hide the orb in a [[large pouch]] - thus creating an [[Large pouch (Devious Minds)|illuminated large pouch]]. A [[colossal pouch]] can also be used, but will not be destroyed like a large pouch.
[[File:Large pouch detail.png|right|180px]]
Large pouches can be obtained as rewards from the [[Rewards Guardian]] at [[Guardians of the Rift]] or as drops from [[abyssal leech]]es, [[abyssal guardian|guardians]] and [[abyssal walker|walkers]] found within the [[Abyss]] or the [[Abyssal Area]]. In addition, the pouch is only dropped if you have all the pouches below it. You do not need to have the [[Runecraft]] level (50) in order for it to be dropped, but it is required to use it.
:'''Please note:''' The ''only possible way'' to get to [[Entrana]] with the orb is through the [[Abyss]]. If you try the balloons, or [[Port Sarim]], you will be cut off when the monks or balloon assistant asks about the 'pouch and its contents'.

:'''Note:''' It must be a [[large pouch]] or [[colossal pouch]], if you try to use a [[giant pouch]] you will get a message objecting it is too large to safely transport the orb.

As usual, no other [[weapons]] or [[armour]] are allowed on [[Entrana]], so bank them before entering the Abyss. The Abyss is accessible only through a teleport from the [[Mage of Zamorak]], who is located in the [[Wilderness]] at the point where the [[River Lum]] goes underground, just north of [[Edgeville]]. Enter the Abyss to reach the Law Altar, and through it, Entrana.

''If your pouch is degraded, you will be denied access into [[Entrana]] with the orb in it. Contact the [[Dark Mage (Abyss)|dark mage]], either by the [[NPC Contact]] spell or directly in the Abyss to get it repaired.''

:'''Note for UIMs:''' The orb and the [[Large pouch (Devious Minds)|large pouch]] containing the orb will be lost if the player dies after putting the orb in the pouch, including to deathpile or deathbank. If obtaining a large pouch from Abyss, make sure to deathpile or deathbank gear and items after obtaining the pouch but before putting the orb in it (the orb is always lost on death, players can get a new orb after dying from the Monk at Paterdomus). Do not put the orb in the pouch before you deathbank or deathpile and are fully ready to go to [[Entrana]]. Note the pouch used for this quest will be lost regardless as part of successful completion.
"""

[[steps]]
index = 3
name = "Surprise!"
links = ["large pouch (Devious Minds)", "Entrana", "Relic (Devious Minds)", "Assassin", "bow-sword", "High Priest (Entrana)", "Paterdomus", "Paterdomus Temple", "Monk (Devious Minds)", "Dead Monk", "Port Sarim", "Sir Tiffy Cashien", "Falador", "Falador Park", "Temple Knights"]
text = """
{{Needed|The [[large pouch (Devious Minds)]]}}
[[File:Devious minds - temple attack.png|thumb|220px|The assassination.]]
On [[Entrana]], head to the church at the heart of the island and use your large pouch on the altar. A cutscene ensues, wherein the monks are walking towards the altar to begin the ceremony, one of them holding a mysterious [[Relic (Devious Minds)|relic]], when suddenly an [[Assassin]] wielding the [[bow-sword]] teleports in, swiftly kills the monks and steals the relic! It turns out that the orb you delivered was in fact a teleportation item using ancient magic, which allowed the assassin to sneak into the holy island, unhindered.

After the cutscene, talk to the [[High Priest (Entrana)|High Priest]], who'll forgive for it not being your fault and tells you to return to the monk at [[Paterdomus]] to investigate.
[[File:Devious Minds - dead monk.png|thumb|220px|The dead monk at Paterdomus.]]
On arriving back at the [[Paterdomus Temple]], you see the [[Monk (Devious Minds)|monk]] you helped is gone, replaced by a [[Dead Monk]]. Searching the body reveals that he has been killed by powerful magic, and is not the same person you spoke to earlier.

Go back to [[Entrana]] and speak with the [[High Priest (Entrana)|High Priest]] again (you can travel via [[Port Sarim]] this time if you wish). Upon hearing about the strange events, he asks you to contact [[Sir Tiffy Cashien]] at the [[Falador]] park. Locate [[Sir Tiffy Cashien|Sir Tiffy]] sitting on a bench in [[Falador Park]] and tell him about the incident; he too seems puzzled, and promises to investigate with his [[Temple Knights]] resources.

'''Congratulations, quest complete!'''
"""
