quest = "Another Slice of H.A.M."
step_count = 6

[[steps]]
index = 0
name = "Excavation"
links = ["Ur-tag", "Ambassador Alvijar", "Keldagrim", "Dorgesh-Kaan", "Tegdak", "trowel", "specimen brush", "artefact", "armour shard", "axe head", "helmet fragment", "ancient mace", "shield fragment", "sword fragment"]
text = """
[[File:Ur-tag chathead.png|left]]
Speak to [[Ur-tag]] (upstairs) or [[Ambassador Alvijar]]. They can be found in the northern part of the city, up the stairs, then east to house with quest start icon. They will explain they are making a train route between [[Keldagrim]] and [[Dorgesh-Kaan]]. Go to the Station south-west of the city (without going down the first staircase, see middle image above) until you find a transportation sign (on your minimap). Go through the doorway, and you will end up in a train station.
[[File:Another Slice Of H.A.M - speaking to Tegdak.png|thumb|220px|Talking to Tegdak.]]
Walk south on the tracks and talk to [[Tegdak]]; he will give you a [[trowel]] and a [[specimen brush]]. Dig up the [[artefact]]s hidden on the unfinished railway tracks by using the trowel on them. They look similar to the other rocks but are bigger; using the trowel over the right rocks will label them as "artefact." Clean all six artefacts by using an artefact on the specimen table - you will then end up with an [[armour shard]], an [[axe head]], a [[helmet fragment]], an [[ancient mace]] (shows as a "mace" for now), a [[shield fragment]], and a [[sword fragment]]. After cleaning them, talk to Tegdak.
[[File:Another Slice Of H.A.M - excavating goblin artefacts.png|thumb|220px|Digging up one of the artefacts.]]
"""

[[steps]]
index = 1
name = "To the village"
links = ["Zanik", "goblin scribe", "Goblin Village", "Oldak", "Bandos"]
text = """
{{Needed|Ranged or magic weapons and armour, a light source}}

Before continuing, it's recommended that you bank and equip gear to fight with ranged or magic now (knives and darts will not work unless you can use long range). You won't get a chance to bank before the upcoming fight.
[[File:Another Slice Of H.A.M - Goblin Village gathering.png|thumb|left|220px|The meeting.]]

'''NOTE:''' In this section, Zanik will follow you just as she did in the past. '''''You must dismiss your follower before taking her with you.''''' Additionally, if you teleport yourself you will leave Zanik behind. If you lose her, return to the railway station tunnel to ask her to follow you again; you must ask Oldak to teleport you again afterwards. Zanik will abandon you and return to the railway if you enter the '''Dorgesh-Kaan Mine.''' Travelling back to the Goblin Village without talking to Oldak will not trigger the cutscene.

Now, take [[Zanik]] with you, and go north. Exit the station and visit the [[goblin scribe]] west of Ur-tag's house, where you started the quest.

Talk to him about the symbols that are covering the mace that you found. The scribe will not be able to tell you anything about the symbols, but he suggests that you go talk to the goblin generals in [[Goblin Village]].

Go down the stairs in the house just west of the scribe and talk to [[Oldak]]. He will teleport you to the [[Goblin Village]] and give you a sphere to teleport back to the city.
Once you're in the village, talk to one of the generals and a cutscene will begin. In the end, you discover that Zanik is likely the goblins' prophesied 'Chosen Commander'. The mace is also found to have the power of the goblin 'Big High War God', [[Bandos]].
{{clear|left}}
"""

[[steps]]
index = 2
name = "The H.A.M-bush"
links = ["H.A.M. Member", "Ranged", "Magic", "H.A.M. Mage", "H.A.M. Archer", "bronze crossbow", "bronze bolts", "Prayer", "crossbow (weapon)", "bolt", "Zanik", "Sigmund", "Lumbridge Swamp Caves", "ancient mace"]
text = """
{{Instance}}
[[File:Another Slice Of H.A.M - H.A.M attack.png|thumb|220px|Attacking the H.A.M units.]]
At the end of the cutscene, two [[H.A.M. Member]]s show up and start attacking the goblins with [[Ranged]] and [[Magic]]. Head south, taking the path around the back (west side) of the buildings, but stay out of the attack range. When you get to the tower, climb up the ladder and kill the [[H.A.M. Mage]] and [[H.A.M. Archer]] with either Magic or Ranged. A [[bronze crossbow]] and 50 [[bronze bolts]] spawn upstairs next to the ladder if you need a weapon. They do not respawn if you run out of ammo. However, you can respawn the bolts by closing and reopening the quest's instance. This can be done in a relatively quick fashion by walking a few tiles south of the ladder and then back north. This will reset both of the enemies as well, so if you think you'll need more than 50 bolts, collect extra bolts before you start trying to kill them. You will likely take hits climbing up and down the ladder even if you're only grabbing the bolts.
[[File:Another Slice Of H.A.M - Sigmund appears.png|thumb|left|220px|Sigmund threatening to kill Zanik.]]
You can simply fight the two foes, or you can also take cover behind the box so you won't take damage. When you're prepared, come out from behind the crates and attack the H.A.M. If things get too hot, or you need a break, click "''hide behind crate''" again in order to stop the damage. The mage and ranger will hit at the same time, and never miss, so using [[Prayer|protection prayers]] can only reduce damage. It is possible to avoid all damage by hiding behind crates, click one enemy, and then immediately after hide behind crates. Using a [[crossbow (weapon)|crossbow]] on rapid-fire allows the player to fire a [[bolt]] and hide behind the crates before the enemy's projectile hits. In order to use darts, the player must use the Long Range combat style.

When you have done this, there will be another short cutscene where [[Zanik]] is kidnapped by [[Sigmund]]. The goblin generals will tell you they are sending two sergeants to help you and that you should meet them at [[Lumbridge Swamp Caves|Lumbridge Swamp]]. They will also give you the [[ancient mace]].
{{clear|left}}
"""

[[steps]]
index = 3
name = "Getting past the guards"
links = ["Sigmund", "Keldagrim", "Dorgesh-Kaan", "Lumbridge Swamp", "Sergeant Slimetoes", "Sergeant Mossfists", "light source", "Guard (Another Slice of H.A.M.)"]
text = """
{{Instance}}
{{map|align=right|mapID=-1|zoom=3|x=2401|y=5543|caption=This map shows how to navigate the guards.
|mtype:square,r:0.5,stroke:#32bc2e,fill-opacity:1,fill:#32bc2e,2402:5538,2405:5538,2408:5538,2401:5535,2404:5535,2407:5535
|mtype:line,stroke-width:1,stroke:#ff0000,2397.5:5554,2397.5:5542.3,2400.5:5542.3,2400.5:5541.7,2397.5:5541.7,2397.5:5538,2401:5538,2401:5536.5,2412:5536.5,2412:5527}}
[[Sigmund]] plans to kill her on the train tracks between [[Keldagrim]] and [[Dorgesh-Kaan]], making it look like an accident so that war will break out between the dwarves and the goblins. You cannot enter through the Dorgesh-Kaan entrance this time (it will say the staircase is closed), so you must go to the Lumbridge swamp cave entrance and meet the goblin warriors who will be helping you.

Now, go to the [[Lumbridge Swamp]], and talk to the goblin sergeants, [[Sergeant Slimetoes]] and [[Sergeant Mossfists]]. They should be near the entrance to the Lumbridge Swamp Caves (make sure you have your [[light source]] for this part).
[[File:Another Slice Of H.A.M - getting past guards.png|thumb|220px|Hiding behind the boxes.]]

{{Checklist|
*Climb down the entrance to the caves and next to the rope should be another ladder.
*Go down the ladder, and you will briefly see a [[Guard (Another Slice of H.A.M.)|H.A.M. Guard]] before he runs away to get reinforcements.
*Now, talk to the goblins. Tell one to wait behind and then run down the hallway into the nearby room, hiding while the two guards run past.
*Make sure the second goblin is not standing by the wall, then tell him to wait in the room.
*When the two guards walk past the room and engage in combat with the goblin that you left behind, go down by the boxes, and hide behind one of them until a third guard walks past.
*After the third guard attacks the first goblin, run back into the room and tell the second goblin to follow you.
*With the goblin following you, run to the last guard standing by the ladder. Make sure that goblin is near you and stand behind him so that the guard attacks him.
*After the guard engages in combat with the goblin, head down the ladder.
}}
"""

[[steps]]
index = 4
name = "Another Sigmund showdown"
links = ["Sigmund", "Protection prayers", "ancient mace", "special attack", "Zanik", "Hitpoints"]
text = """
{{Instance}}
[[File:Another Slice Of H.A.M - Zanik tied up.png|thumb|200px|Zanik, tied up.]]
'''Note:''' If you use the mace's special attack too quickly after the fight starts there is a possibility that it will not work and the prayer-draining effect will not appear.
[[File:Another Slice Of H.A.M - Sigmund smited.png|thumb|200px|Sigmund is smited!]]
{{Listen
|title = Grand Opening
|desc = The music which plays during the grand opening of the train line.
|filename = Another Slice of H.A.M. - Grand Opening.ogg
}}
A cutscene will play, and you will immediately have to fight [[Sigmund]] (level 64). Attack him using any weapon, and he will turn on the [[Protection prayers|Protection prayer]] corresponding to that attack, thus making him invulnerable. Use the [[ancient mace]]'s [[special attack]] to remove his ability to use protection prayers for the rest of the fight, and finish him off using whichever method you prefer.

Note that this fight is not optional; if you attempt to untie [[Zanik]] whilst the fight is still in progress, you will be hit for around 10 [[Hitpoints]] of damage.
"""

[[steps]]
index = 5
name = "The end"
links = ["Zanik", "Dorgesh-Kaan\u2013Keldagrim train system"]
text = """
[[File:Another Slice Of H.A.M - train system opening.png|thumb|left|200px|The grand opening of the train line.]]
Once Sigmund has been defeated, he will teleport away. Untie [[Zanik]] and get ready to watch the final cutscene about the grand opening of the [[Dorgesh-Kaan–Keldagrim train system]].

'''Congratulations, quest complete!'''
{{Clear}}
"""
