title = "Transcript:Burntmeat"
npcs = ["Burntmeat", "Wolfbone"]
node_count = 7

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Burntmeat"
text = "Ah, you come back again."
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Wolfbone"
text = "How are things at Weiss?"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Player"
text = "Snowflake and My Arm are ruling the town together, and now I've built them a special fire, they can grow goutweed there."
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Wolfbone"
text = "I plan to stay here, in the Stronghold, with my friend Burntmeat, but it good to hear of my home. Thank you."
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Burntmeat"
text = "Stronghold trolls not all that interested in firemaking, after all, but t'anks for bringing book anyway. It taste lovely."
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Player"
text = "... you're welcome."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
