title = "Transcript:Caninelle Draynar"
npcs = ["Caninelle Draynar", "Pipistrelle Draynar"]
node_count = 18

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Player"
text = "Player: Hello there."
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Caninelle Draynar"
text = "Darling, who's this?"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Pipistrelle Draynar"
text = "I don't know, darling. Why don't you ask them?"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Caninelle Draynar"
text = "Yes, good idea!"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Caninelle Draynar"
text = "Who are you?"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Player"
text = "I'm [Vampyre name]."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Caninelle Draynar"
text = "Hello, [Vampyre name]. I'm Caninelle Draynar and this is Pipistrelle Draynar."
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Pipistrelle Draynar"
text = "Hello there!"
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Player"
text = "Draynar? Any connection to Draynor?"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Pipistrelle Draynar"
text = "Oh yes. The Draynar family has been around since before vampyres came to this world."
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "speaker"
speaker = "Caninelle Draynar"
text = "Over time, some people took the name and started pronouncing it differently. Hence Draynor."
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "speaker"
speaker = "Pipistrelle Draynar"
text = "Draynor is more commonly used as a first name though, with Draynar as a last name."
parent = -1

[[nodes]]
id = 12
depth = 1
kind = "speaker"
speaker = "Player"
text = "Thanks for the information. I wonder if there's a Draynor Draynar out there."
parent = -1

[[nodes]]
id = 13
depth = 1
kind = "speaker"
speaker = "Pipistrelle Draynar"
text = "Now that would be funny."
parent = -1

[[nodes]]
id = 14
depth = 1
kind = "speaker"
speaker = "Player"
text = "See you around."
parent = -1

[[nodes]]
id = 15
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 16
depth = 1
kind = "speaker"
speaker = "Caninelle/Pipistrelle Draynar"
text = "Human! Get back to the slave pens before I call the guards!"
parent = -1

[[nodes]]
id = 17
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
