title = "Transcript:Doric's Quest"
npcs = ["Doric"]
node_count = 103

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Doric"
text = "Hello traveller, what brings you to my humble smithy?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "select"
text = "Select an Option"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "option"
text = "I wanted to use your anvils."
parent = -1
children = [3, 4, 5, 6, 34]

[[nodes]]
id = 3
depth = 2
kind = "speaker"
speaker = "Player"
text = "I wanted to use your anvils."
parent = 2

[[nodes]]
id = 4
depth = 2
kind = "speaker"
speaker = "Doric"
text = "My anvils get enough work with my own use. I make pickaxes, and it takes a lot of hard work. If you could get me some more materials, then I could let you use them."
parent = 2

[[nodes]]
id = 5
depth = 2
kind = "select"
text = "Start Doric's Quest?"
parent = 2

[[nodes]]
id = 6
depth = 2
kind = "option"
text = "Yes."
parent = 2
children = [7, 8, 9, 10, 22]

[[nodes]]
id = 7
depth = 3
kind = "speaker"
speaker = "Player"
text = "Yes, I will get you the materials."
parent = 6

[[nodes]]
id = 8
depth = 3
kind = "speaker"
speaker = "Doric"
text = """
Clay is what I use more than anything, to make casts. Could you get me 6 clay, 4 copper ore, and 2 iron ore, please? I could pay a little, and let you use my anvils. Take this pickaxe with you just in case you need it.
"""
parent = 6

[[nodes]]
id = 9
depth = 3
kind = "cond"
text = "If the player does not already have all of the materials:"
parent = 6

[[nodes]]
id = 10
depth = 3
kind = "select"
text = "Select an Option"
parent = 6
children = [11, 19]

[[nodes]]
id = 11
depth = 4
kind = "option"
text = "Where can I find those?"
parent = 10
children = [12, 13, 14, 18]

[[nodes]]
id = 12
depth = 5
kind = "speaker"
speaker = "Player"
text = "Where can I find those?"
parent = 11

[[nodes]]
id = 13
depth = 5
kind = "speaker"
speaker = "Doric"
text = "You'll be able to find all those ores in the rocks just inside the Dwarven Mine. Head east from here and you'll find the entrance in the side of Ice Mountain."
parent = 11

[[nodes]]
id = 14
depth = 5
kind = "cond"
text = "If the player does not have 15 Mining:"
parent = 11
children = [15, 16, 17]

[[nodes]]
id = 15
depth = 6
kind = "speaker"
speaker = "Player"
text = "But I'm not a good enough miner to get iron ore."
parent = 14

[[nodes]]
id = 16
depth = 6
kind = "speaker"
speaker = "Doric"
text = "Oh well, you could practice mining until you can. Can't beat a bit of mining - it's a useful skill. Failing that, you might be able to find a more experienced adventurer to buy the iron ore off."
parent = 14

[[nodes]]
id = 17
depth = 6
kind = "act"
text = "continues"
parent = 14

[[nodes]]
id = 18
depth = 5
kind = "act"
text = "end"
parent = 11
is_terminal = true

[[nodes]]
id = 19
depth = 4
kind = "option"
text = "Certainly, I'll be right back!"
parent = 10
children = [20, 21]

[[nodes]]
id = 20
depth = 5
kind = "speaker"
speaker = "Player"
text = "Certainly, I'll be right back!"
parent = 19

[[nodes]]
id = 21
depth = 5
kind = "act"
text = "end"
parent = 19
is_terminal = true

[[nodes]]
id = 22
depth = 3
kind = "cond"
text = "If the player already has all of the materials:"
parent = 6
children = [23, 24, 25, 26, 27, 28, 31, 32, 33]

[[nodes]]
id = 23
depth = 4
kind = "speaker"
speaker = "Player"
text = "You know, it's funny you should require those exact things!"
parent = 22

[[nodes]]
id = 24
depth = 4
kind = "speaker"
speaker = "Doric"
text = "What do you mean?"
parent = 22

[[nodes]]
id = 25
depth = 4
kind = "speaker"
speaker = "Player"
text = "I can usually fit 28 things in my backpack and in a world full of quite literally limitless possibilities, a complete coincidence has occurred!"
parent = 22

[[nodes]]
id = 26
depth = 4
kind = "speaker"
speaker = "Doric"
text = "I don't quite understand what you're saying?"
parent = 22

[[nodes]]
id = 27
depth = 4
kind = "speaker"
speaker = "Player"
text = "Well, out of pure coincidence, despite definitely not knowing what you were about to request, I just so happened to have carried those exact items!"
parent = 22

[[nodes]]
id = 28
depth = 4
kind = "cond"
text = "If the player has the exact amounts:"
parent = 22
children = [29, 30]

[[nodes]]
id = 29
depth = 5
kind = "speaker"
speaker = "Player"
text = "In fact, in the exact quantities too!"
parent = 28

[[nodes]]
id = 30
depth = 5
kind = "act"
text = "continues"
parent = 28

[[nodes]]
id = 31
depth = 4
kind = "speaker"
speaker = "Doric"
text = "Oh my, that is a coincidence! Pass them here, please. I can spare you some coins for your trouble, and please use my anvils any time you want."
parent = 22

[[nodes]]
id = 32
depth = 4
kind = "box"
text = "pic=Copper ore detail.png|You hand the clay, copper, and iron to Doric."
parent = 22

[[nodes]]
id = 33
depth = 4
kind = "other"
text = "{{qact|Quest complete!}}"
parent = 22

[[nodes]]
id = 34
depth = 2
kind = "option"
text = "No."
parent = 2
children = [35, 36, 37]

[[nodes]]
id = 35
depth = 3
kind = "speaker"
speaker = "Player"
text = "No, hitting rocks is for the boring people, sorry."
parent = 34

[[nodes]]
id = 36
depth = 3
kind = "speaker"
speaker = "Doric"
text = "That is your choice. Nice to meet you anyway."
parent = 34

[[nodes]]
id = 37
depth = 3
kind = "act"
text = "end"
parent = 34
is_terminal = true

[[nodes]]
id = 38
depth = 1
kind = "option"
text = "I want to use your whetstone."
parent = -1
children = [39, 40, 41, 42, 44]

[[nodes]]
id = 39
depth = 2
kind = "speaker"
speaker = "Player"
text = "I wanted to use your whetstone."
parent = 38

[[nodes]]
id = 40
depth = 2
kind = "speaker"
speaker = "Doric"
text = "The whetstone is for more advanced smithing, but I could let you use it as well as my anvils if you could get me some more materials."
parent = 38

[[nodes]]
id = 41
depth = 2
kind = "select"
text = "Start Doric's Quest?"
parent = 38

[[nodes]]
id = 42
depth = 2
kind = "option"
text = "Yes."
parent = 38
children = [43]

[[nodes]]
id = 43
depth = 3
kind = "act"
text = "above"
parent = 42

[[nodes]]
id = 44
depth = 2
kind = "option"
text = "No."
parent = 38
children = [45]

[[nodes]]
id = 45
depth = 3
kind = "act"
text = "above"
parent = 44

[[nodes]]
id = 46
depth = 1
kind = "option"
text = "Mind your own business, shortstuff!"
parent = -1
children = [47, 48, 49]

[[nodes]]
id = 47
depth = 2
kind = "speaker"
speaker = "Player"
text = "Mind your own business, shortstuff!"
parent = 46

[[nodes]]
id = 48
depth = 2
kind = "speaker"
speaker = "Doric"
text = "How nice to meet someone with such pleasant manners. Do come again when you need to shout at someone smaller than you!"
parent = 46

[[nodes]]
id = 49
depth = 2
kind = "act"
text = "end"
parent = 46
is_terminal = true

[[nodes]]
id = 50
depth = 1
kind = "option"
text = "I was just checking out the landscape."
parent = -1
children = [51, 52, 53, 54, 58]

[[nodes]]
id = 51
depth = 2
kind = "speaker"
speaker = "Player"
text = "I was just checking out the landscape."
parent = 50

[[nodes]]
id = 52
depth = 2
kind = "speaker"
speaker = "Doric"
text = "Hope you like it. I do enjoy the solitude of my little home. If you get time, please say hi to my friends in the Dwarven Mine."
parent = 50

[[nodes]]
id = 53
depth = 2
kind = "select"
text = "Select an Option"
parent = 50

[[nodes]]
id = 54
depth = 2
kind = "option"
text = "Dwarven Mine?"
parent = 50
children = [55, 56, 57]

[[nodes]]
id = 55
depth = 3
kind = "speaker"
speaker = "Player"
text = "Dwarven Mine?"
parent = 54

[[nodes]]
id = 56
depth = 3
kind = "speaker"
speaker = "Doric"
text = "Yep, the entrance is in the side of Ice Mountain just to the east of here. They're a friendly bunch. Stop in at Nurmof's store and buy one of my pickaxes!"
parent = 54

[[nodes]]
id = 57
depth = 3
kind = "act"
text = "end"
parent = 54
is_terminal = true

[[nodes]]
id = 58
depth = 2
kind = "option"
text = "Will do!"
parent = 50
children = [59, 60]

[[nodes]]
id = 59
depth = 3
kind = "speaker"
speaker = "Player"
text = "Will do!"
parent = 58

[[nodes]]
id = 60
depth = 3
kind = "act"
text = "end"
parent = 58
is_terminal = true

[[nodes]]
id = 61
depth = 1
kind = "option"
text = "What do you make here?"
parent = -1
children = [62, 63, 64, 65]

[[nodes]]
id = 62
depth = 2
kind = "speaker"
speaker = "Player"
text = "What do you make here?"
parent = 61

[[nodes]]
id = 63
depth = 2
kind = "speaker"
speaker = "Doric"
text = "I make pickaxes. I am the best maker of pickaxes in the whole of Gielinor."
parent = 61

[[nodes]]
id = 64
depth = 2
kind = "speaker"
speaker = "Player"
text = "Do you have any to sell?"
parent = 61

[[nodes]]
id = 65
depth = 2
kind = "speaker"
speaker = "Doric"
text = "Sorry, but I've got a running order with Nurmof."
parent = 61
children = [66, 67, 71]

[[nodes]]
id = 66
depth = 3
kind = "select"
text = "Select an Option"
parent = 65

[[nodes]]
id = 67
depth = 3
kind = "option"
text = "Who's Nurmof?"
parent = 65
children = [68, 69, 70]

[[nodes]]
id = 68
depth = 4
kind = "speaker"
speaker = "Player"
text = "Who's Nurmof?"
parent = 67

[[nodes]]
id = 69
depth = 4
kind = "speaker"
speaker = "Doric"
text = "Nurmof has a store over in the Dwarven Mine. You can find the entrance on the side of Ice Mountain to the east of here."
parent = 67

[[nodes]]
id = 70
depth = 4
kind = "act"
text = "end"
parent = 67
is_terminal = true

[[nodes]]
id = 71
depth = 3
kind = "option"
text = "Ah, fair enough."
parent = 65
children = [72, 73]

[[nodes]]
id = 72
depth = 4
kind = "speaker"
speaker = "Player"
text = "Ah, fair enough."
parent = 71

[[nodes]]
id = 73
depth = 4
kind = "act"
text = "end"
parent = 71
is_terminal = true

[[nodes]]
id = 74
depth = 1
kind = "speaker"
speaker = "Doric"
text = "Hey, who said you could use that? My anvils get enough work with my own use. I make pickaxes, and it takes a lot of hard work."
parent = -1

[[nodes]]
id = 75
depth = 1
kind = "select"
text = "Select an Option"
parent = -1

[[nodes]]
id = 76
depth = 1
kind = "option"
text = "Sorry, would it be OK if I used your anvils?"
parent = -1
children = [77, 78, 79, 80, 82]

[[nodes]]
id = 77
depth = 2
kind = "speaker"
speaker = "Player"
text = "Sorry, would it be OK if I used your anvils?"
parent = 76

[[nodes]]
id = 78
depth = 2
kind = "speaker"
speaker = "Doric"
text = "If you could get me some more materials then I could let you use them."
parent = 76

[[nodes]]
id = 79
depth = 2
kind = "select"
text = "Select an Option"
parent = 76

[[nodes]]
id = 80
depth = 2
kind = "option"
text = "Yes, I will get you materials."
parent = 76
children = [81]

[[nodes]]
id = 81
depth = 3
kind = "act"
text = "above"
parent = 80

[[nodes]]
id = 82
depth = 2
kind = "option"
text = "No, hitting rocks is for the boring people, sorry."
parent = 76
children = [83]

[[nodes]]
id = 83
depth = 3
kind = "act"
text = "above"
parent = 82

[[nodes]]
id = 84
depth = 1
kind = "option"
text = "I didn't want to use your anvils anyway."
parent = -1
children = [85, 86, 87]

[[nodes]]
id = 85
depth = 2
kind = "speaker"
speaker = "Player"
text = "I didn't want to use your anvils anyway."
parent = 84

[[nodes]]
id = 86
depth = 2
kind = "speaker"
speaker = "Doric"
text = "That is your choice."
parent = 84

[[nodes]]
id = 87
depth = 2
kind = "act"
text = "end"
parent = 84
is_terminal = true

[[nodes]]
id = 88
depth = 1
kind = "box"
text = "You should probably ask before using that."
parent = -1

[[nodes]]
id = 89
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 90
depth = 1
kind = "speaker"
speaker = "Doric"
text = "Have you got my materials yet, traveller?"
parent = -1

[[nodes]]
id = 91
depth = 1
kind = "speaker"
speaker = "Player"
text = "Sorry, I don't have them all yet."
parent = -1

[[nodes]]
id = 92
depth = 1
kind = "speaker"
speaker = "Doric"
text = "Not to worry, stick at it. Remember, I need 6 clay, 4 copper ore, and 2 iron ore."
parent = -1

[[nodes]]
id = 93
depth = 1
kind = "select"
text = "Select an Option"
parent = -1

[[nodes]]
id = 94
depth = 1
kind = "option"
text = "Where can I find those?"
parent = -1
children = [95]

[[nodes]]
id = 95
depth = 2
kind = "act"
text = "above"
parent = 94

[[nodes]]
id = 96
depth = 1
kind = "option"
text = "Certainly, I'll be right back!"
parent = -1
children = [97]

[[nodes]]
id = 97
depth = 2
kind = "act"
text = "above"
parent = 96

[[nodes]]
id = 98
depth = 1
kind = "speaker"
speaker = "Doric"
text = "Have you got my materials yet, traveller?"
parent = -1

[[nodes]]
id = 99
depth = 1
kind = "speaker"
speaker = "Player"
text = "I have everything you need!"
parent = -1

[[nodes]]
id = 100
depth = 1
kind = "speaker"
speaker = "Doric"
text = "Many thanks! Pass them here, please. I can spare you some coins for your trouble, and please use my anvils any time you want."
parent = -1

[[nodes]]
id = 101
depth = 1
kind = "box"
text = "pic=Copper ore detail.png|You hand the clay, copper, and iron to Doric."
parent = -1

[[nodes]]
id = 102
depth = 1
kind = "other"
text = "{{qact|Quest complete!}}"
parent = -1
