title = "Transcript:Draynor bank robbery"
npcs = ["Market Guard (Draynor)", "Banker (Draynor Bank Robbery)", "Banker", "Cool Mom227", "Qutiedoll", "1337sp34kr", "Elfinlocks", "Purepker895", "Wise Old Man", "Olivia", "Pillory Guard"]
node_count = 51

[[nodes]]
id = 0
depth = 1
kind = "other"
text = "{{Qact|The recording begins with a view of Draynor market as Cool Mom227 attempts to steal from Olivia's seed stall}}"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Market Guard"
text = "{{overhead|Hey! Get your hands off there!}}"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "other"
text = "{{Qact|The Market Guard attacks Cool Mom227}}"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "other"
text = "{{Qact|The scene pans down to Draynor bank with a few [[Player spoof|players]] trading within}}"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Qutiedoll"
text = "{{overhead|Thx}}"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "1337sp34kr"
text = "{{overhead|Yw}}"
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Elfinlocks"
text = "{{overhead|Buying 2k nats - no noob offers}}"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "1337sp34kr"
text = "{{overhead|I h4ve n4ts}}"
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Elfinlocks"
text = "{{overhead|You sell?}}"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "1337sp34kr"
text = "{{overhead|Tr4de}}"
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "other"
text = "{{Qact|Purepker895 leaves the bank and heads towards the market, as the Wise Old Man opens his door and casts a spell, killing Purepker895}}"
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "speaker"
speaker = "Qutiedoll"
text = "{{overhead|Huh?}}"
parent = -1

[[nodes]]
id = 12
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Please don't block my line of fire!}}"
parent = -1

[[nodes]]
id = 13
depth = 1
kind = "speaker"
speaker = "Olivia"
text = "{{overhead|Hey, what are you doing?}}"
parent = -1

[[nodes]]
id = 14
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Olivia - please go away!}}"
parent = -1

[[nodes]]
id = 15
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man casts a [[Teleother]] spell on Olivia and sends her away before turning to the bank}}"
parent = -1

[[nodes]]
id = 16
depth = 1
kind = "speaker"
speaker = "Olivia"
text = "{{overhead|Eeeek!}}"
parent = -1

[[nodes]]
id = 17
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Ah, now I can get on with it...}}"
parent = -1

[[nodes]]
id = 18
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man picks up the coins dropped from Purepker895 and casts a spell at the bank wall, blasting a hole in it}}"
parent = -1

[[nodes]]
id = 19
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Could everyone please not move?}}"
parent = -1

[[nodes]]
id = 20
depth = 1
kind = "other"
text = "{{Qact|Two of the bankers attempt to restrain the Wise Old Man as the third hides in a corner}}"
parent = -1

[[nodes]]
id = 21
depth = 1
kind = "speaker"
speaker = "Banker 1"
text = "{{overhead|Hey - you can't come in here!}}"
parent = -1

[[nodes]]
id = 22
depth = 1
kind = "speaker"
speaker = "Banker 2"
text = "{{overhead|Oi!}}"
parent = -1

[[nodes]]
id = 23
depth = 1
kind = "speaker"
speaker = "Banker 3"
text = "{{overhead|Uh-oh!}}"
parent = -1

[[nodes]]
id = 24
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|I do wish you'd just stop it!}}"
parent = -1

[[nodes]]
id = 25
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man defeats the two bankers with a few strikes from his staff, drawing the attention of the players in the bank}}"
parent = -1

[[nodes]]
id = 26
depth = 1
kind = "speaker"
speaker = "Banker 3"
text = "{{overhead|Help! Help!}}"
parent = -1

[[nodes]]
id = 27
depth = 1
kind = "speaker"
speaker = "Elfinlocks"
text = "{{overhead|Hey - how'd he get in there?}}"
parent = -1

[[nodes]]
id = 28
depth = 1
kind = "speaker"
speaker = "1337sp34kr"
text = "{{overhead|Hax!}}"
parent = -1

[[nodes]]
id = 29
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|My sincerest regrets, dear lady...}}"
parent = -1

[[nodes]]
id = 30
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man casts a spell at Elfinlocks, killing her as she drops her [[Blue partyhat|blue partyhat]]}}"
parent = -1

[[nodes]]
id = 31
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|And also you, sir...}}"
parent = -1

[[nodes]]
id = 32
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man does the same to 1337sp34kr, as Qutiedoll walks back into the bank.}}"
parent = -1

[[nodes]]
id = 33
depth = 1
kind = "speaker"
speaker = "Qutiedoll"
text = "{{overhead|How you do that?}}"
parent = -1

[[nodes]]
id = 34
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Oh dear - another one...}}"
parent = -1

[[nodes]]
id = 35
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man uses the same spell to kill Qutiedoll}}"
parent = -1

[[nodes]]
id = 36
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Ooh - a party hat?}}"
parent = -1

[[nodes]]
id = 37
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man casts [[telegrab]] on the partyhat and puts it on before advancing on the remaining banker}}"
parent = -1

[[nodes]]
id = 38
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Now, my dear...}}"
parent = -1

[[nodes]]
id = 39
depth = 1
kind = "speaker"
speaker = "Banker 3"
text = "{{overhead|Eeeek!}}"
parent = -1

[[nodes]]
id = 40
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Just give me the money, please.}}"
parent = -1

[[nodes]]
id = 41
depth = 1
kind = "other"
text = "{{Qact|A pillory guard appears behind the Wise Old Man and attempts to arrest him}}"
parent = -1

[[nodes]]
id = 42
depth = 1
kind = "speaker"
speaker = "Pillory Guard"
text = "{{overhead|Old man, you're for da cage!}}"
parent = -1

[[nodes]]
id = 43
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Oh, am I?}}"
parent = -1

[[nodes]]
id = 44
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Ahh!}}"
parent = -1

[[nodes]]
id = 45
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man casts a spell on the pillory guard}}"
parent = -1

[[nodes]]
id = 46
depth = 1
kind = "speaker"
speaker = "Pillory Guard"
text = "{{overhead|Aaargh!}}"
parent = -1

[[nodes]]
id = 47
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|Yah!}}"
parent = -1

[[nodes]]
id = 48
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man defeats the pillory guard with a melee strike before turning to the camera}}"
parent = -1

[[nodes]]
id = 49
depth = 1
kind = "speaker"
speaker = "Wise Old Man"
text = "{{overhead|And YOU can stop spying on me!}}"
parent = -1

[[nodes]]
id = 50
depth = 1
kind = "other"
text = "{{Qact|The Wise Old Man casts the same spell he killed the players with towards the camera, breaking it and ending the recording}}"
parent = -1
