title = "Transcript:Duck"
npcs = ["Duck", "Duckling", "Ducklings"]
node_count = 3

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Duck"
text = "{{overhead|Quack!}}"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Duck"
text = "{{overhead|Quack?}}"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "[Duckling/Ducklings]"
text = "{{overhead|Eep!}}"
parent = -1
