title = "Transcript:Dung"
npcs = ["Ash", "Dung"]
node_count = 26

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Dung cook human.}}"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ash eat human.}}"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Dung will fry human.}}"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Dung is wrong!}}"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|My brother in stronghold best cook.}}"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ash will boil human 'till it tender.}}"
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Much more tasty.}}"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Ash will not cook human!}}"
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ash will boil!}}"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Dung will boil Ash's head!}}"
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Boil better!}}"
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Fry better!}}"
parent = -1

[[nodes]]
id = 12
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Boil!}}"
parent = -1

[[nodes]]
id = 13
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Fry!}}"
parent = -1

[[nodes]]
id = 14
depth = 1
kind = "act"
text = "The trolls begin fighting."
parent = -1

[[nodes]]
id = 15
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ow!}}"
parent = -1

[[nodes]]
id = 16
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Ugh!}}"
parent = -1

[[nodes]]
id = 17
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Dung not hit Ash!}}"
parent = -1

[[nodes]]
id = 18
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Ow!}}"
parent = -1

[[nodes]]
id = 19
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ow!}}"
parent = -1

[[nodes]]
id = 20
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Ugh!}}"
parent = -1

[[nodes]]
id = 21
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ouch!}}"
parent = -1

[[nodes]]
id = 22
depth = 1
kind = "speaker"
speaker = "Dung"
text = "{{overhead|Dung hate Ash!}}"
parent = -1

[[nodes]]
id = 23
depth = 1
kind = "act"
text = "Dung turns their back on Ash."
parent = -1

[[nodes]]
id = 24
depth = 1
kind = "speaker"
speaker = "Ash"
text = "{{overhead|Ash hate Dung!}}"
parent = -1

[[nodes]]
id = 25
depth = 1
kind = "act"
text = "Ash turns their back on Dung."
parent = -1
