title = "Transcript:Freald"
npcs = ["Freald", "Batt Mellamy"]
node_count = 6

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Freald"
text = "Greetings traveller. What brings you to my residence?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Player"
text = "You keep a pet bat? That's a bit odd."
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Batt Mellamy"
text = "{{overhead|shadow=yes|colour=yellow|Squeak!}}"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Freald"
text = "Yes traveller, this is not out of the ordinary for us. The bats respond well to the powers of the dark altar after being drawn here by the river of blood."
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Player"
text = "Well I hope he keeps you 'mused."
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
