title = "Transcript:Gem (Clan Hall)"
npcs = ["Gem", "Raqueel"]
node_count = 5

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Player"
text = "Hello! Who are you?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Gem"
text = "Hi. I'm Gem. That's what they call me, anyway. My real name is actually-"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Raqueel"
text = "OH GEEEEM! You missed a spot!"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Gem"
text = "Sigh. Nevermind. I have to go."
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
