title = "Transcript:Guild door (Ranging Guild)"
npcs = ["Ranging Guild Doorman"]
node_count = 2

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Ranging Guild Doorman"
text = "Hey you can't come in here. You must be a level 40 ranger to enter."
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
