title = "Transcript:Haera"
npcs = ["Haera", "Hegir"]
node_count = 24

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Haera"
text = "What are you doing in our home?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Player"
text = "I just came to ask you a question."
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Haera"
text = "Hegir, why did you let this human into our home?"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Hegir"
text = "I didn't let him in, he let himself in!"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Haera"
text = "Now what do you want, human? Speak up, speak up!"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Player"
text = "I ehm, just wanted some information."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Haera"
text = "Well go ask someone else instead of barging into people's homes!"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Hegir"
text = "There's no need to be rude to the human, Haera dear."
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Haera"
text = "Now don't you dear me. I'll do whatever I please."
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Player"
text = "I think this is my cue to leave..."
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 11
depth = 1
kind = "other"
text = "{{trandom}}"
parent = -1

[[nodes]]
id = 12
depth = 1
kind = "option"
text = "Dialogue 1"
parent = -1
children = [13]

[[nodes]]
id = 13
depth = 2
kind = "speaker"
speaker = "Haera"
text = "{{overhead|That's the last straw!}}"
parent = 12

[[nodes]]
id = 14
depth = 1
kind = "option"
text = "Dialogue 2"
parent = -1
children = [15]

[[nodes]]
id = 15
depth = 2
kind = "speaker"
speaker = "Haera"
text = "{{overhead|Do your chores!}}"
parent = 14

[[nodes]]
id = 16
depth = 1
kind = "option"
text = "Dialogue 3"
parent = -1
children = [17]

[[nodes]]
id = 17
depth = 2
kind = "speaker"
speaker = "Haera"
text = "{{overhead|Useless... completely useless.}}"
parent = 16

[[nodes]]
id = 18
depth = 1
kind = "option"
text = "Dialogue 4"
parent = -1
children = [19]

[[nodes]]
id = 19
depth = 2
kind = "speaker"
speaker = "Haera"
text = "{{overhead|Don't talk to me like that!}}"
parent = 18

[[nodes]]
id = 20
depth = 1
kind = "option"
text = "Dialogue 5"
parent = -1
children = [21]

[[nodes]]
id = 21
depth = 2
kind = "speaker"
speaker = "Haera"
text = "{{overhead|You're no good!}}"
parent = 20

[[nodes]]
id = 22
depth = 1
kind = "option"
text = "Dialogue 6"
parent = -1
children = [23]

[[nodes]]
id = 23
depth = 2
kind = "speaker"
speaker = "Haera"
text = "{{overhead|I'm warning you, Hegir!}}"
parent = 22
