title = "Transcript:Izel"
npcs = ["Izel", "Hugh"]
node_count = 23

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Izel"
text = "Can I help you?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Player"
text = "What's up with him?"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Izel"
text = "Another gift from the sea. Found him on the shore a few days ago."
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Hugh"
text = "The moon... His face was the moon..."
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Player"
text = "Is he going to be okay?"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Izel"
text = "Maybe. Maybe not. Only time will tell."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Player"
text = "Okay... What are you going to do with him?"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Izel"
text = "He'll get the same offer they all do. We don't need mouths to feed if they won't contribute. Once he's up, he can either stick around or ship out, but if he's staying, he has to help."
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Player"
text = "Help with what?"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Izel"
text = "Salvage of course. We don't have the luxuries of Fortis out here. We have to make do with what we can find. Luckily for us, there's always plenty to be found thanks to all the wrecks."
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "speaker"
speaker = "Player"
text = "I see. Well I hope he gets well soon."
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 12
depth = 1
kind = "speaker"
speaker = "Izel"
text = "You've returned. Can I help you?"
parent = -1

[[nodes]]
id = 13
depth = 1
kind = "speaker"
speaker = "Player"
text = "Is he doing any better?"
parent = -1

[[nodes]]
id = 14
depth = 1
kind = "speaker"
speaker = "Hugh"
text = "The moon... His face was the moon..."
parent = -1

[[nodes]]
id = 15
depth = 1
kind = "speaker"
speaker = "Izel"
text = "What do you think?"
parent = -1

[[nodes]]
id = 16
depth = 1
kind = "speaker"
speaker = "Player"
text = "What happens if he doesn't recover?"
parent = -1

[[nodes]]
id = 17
depth = 1
kind = "speaker"
speaker = "Izel"
text = "The sea can have him back."
parent = -1

[[nodes]]
id = 18
depth = 1
kind = "speaker"
speaker = "Player"
text = "Harsh."
parent = -1

[[nodes]]
id = 19
depth = 1
kind = "speaker"
speaker = "Izel"
text = "I told you before, we don't have the luxuries of Fortis out here. The dead are not useful, nor are they worth anything."
parent = -1

[[nodes]]
id = 20
depth = 1
kind = "speaker"
speaker = "Izel"
text = "If he does live, he will have an opportunity. If he desires, he can have a home here, provided he's willing to contribute."
parent = -1

[[nodes]]
id = 21
depth = 1
kind = "speaker"
speaker = "Player"
text = "I see. Well I hope he gets well soon."
parent = -1

[[nodes]]
id = 22
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
