title = "Transcript:Knight (Falador Party Room)"
npcs = ["Knight (Falador Party Room)", "Party Pete"]
node_count = 10

[[nodes]]
id = 0
depth = 1
kind = "box"
text = "He is too busy dancing to talk!"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|We're Knights of the Party Room}}"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|We dance round and round like a loon}}"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|Quite often we like to sing}}"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|Unfortunately we make a din}}"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|We're Knights of the Party Room}}"
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|Do you like our helmet plumes?}}"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|Everyone's happy now we can move}}"
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Knights"
text = "{{overhead|Like a party animal in the groove}}"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Party Pete"
text = "{{overhead|The party room is a silly place!}}"
parent = -1
