title = "Transcript:Lair of Tarn Razorlor"
npcs = ["Tarn"]
node_count = 8

[[nodes]]
id = 0
depth = 1
kind = "other"
text = "{{qact|Camera pans from the player to Tarn.}}"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Tarn"
text = "Who? How did you get here? Never mind. I'll deal with you myself!"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "other"
text = "{{qact|Tarn casts a spell on the terror dog statues, bringing them to life. Tarn then turns into a mutant before sending his dogs after the player.}}"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Mutant tarn"
text = "{{overhead|Ha! I can't be slain that easily, fool!}}"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "other"
text = "{{qact|Tarn transforms into a ghost.}}"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "other"
text = "{{mes|Killing Tarn Razorlor has greatly improved your Slayer knowledge. You gain 5000 Slayer XP.}}"
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "other"
text = "{{qact|The camera pans to show the terror dog cages being unlocked.}}"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "other"
text = "{{qact|Congratulations! Miniquest complete!}}"
parent = -1
