title = "Transcript:Lord Crombwick"
npcs = ["Damien Leucurte", "Lord Crombwick"]
node_count = 12

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Player"
text = "Are you alright?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Lord Crombwick"
text = "..."
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Damien Leucurte"
text = "You may speak."
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Lord Crombwick"
text = "Oh, yes yes, I'm fine."
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Player"
text = "You look a little beat up."
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Lord Crombwick"
text = "These scratches? Don't worry, just a disagreement with a thorn bush."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Player"
text = "Sure..."
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Damien Leucurte"
text = "Is there something you wanted, bloodbag?"
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Player"
text = "Just looking around."
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Damien Leucurte"
text = "Well, I'd prefer you did it elsewhere, Crombwick is busy entertaining his guests."
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "speaker"
speaker = "Player"
text = "Strange bunch of guests..."
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
