title = "Transcript:Magic guild door"
npcs = ["Wizard Distentor"]
node_count = 2

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Wizard Distentor"
text = "You need a magic level of 66 for admittance to the guild. The magical energy inside the guild is unsafe for anyone below that level. For any other business please ring for attention."
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
