title = "Transcript:Nirrie"
npcs = ["Hallak", "Nirrie", "Tirrie"]
node_count = 49

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Player"
text = "Well I got the people of Nardah their statuette back."
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Nirrie"
text = "We noticed and removed the curse. Hopefully they"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Tirrie"
text = "will get the message and begin to follow Elidinis properly again."
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "option"
text = "Wow how do you finish each others sentences like that?"
parent = -1
children = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

[[nodes]]
id = 4
depth = 2
kind = "speaker"
speaker = "Player"
text = "Wow how do you finish each others sentences like that?"
parent = 3

[[nodes]]
id = 5
depth = 2
kind = "speaker"
speaker = "Nirrie"
text = "We are a gestalt entity. We each have our own body, but our minds"
parent = 3

[[nodes]]
id = 6
depth = 2
kind = "speaker"
speaker = "Tirrie"
text = "are united and we all think as one. Well except when Hallak doth leaveth"
parent = 3

[[nodes]]
id = 7
depth = 2
kind = "speaker"
speaker = "Nirrie"
text = "the toilet seat up."
parent = 3

[[nodes]]
id = 8
depth = 2
kind = "speaker"
speaker = "Hallak"
text = "That's the way it's meant to be!"
parent = 3

[[nodes]]
id = 9
depth = 2
kind = "speaker"
speaker = "Nirrie"
text = "Ok we're a mostly gestalt entity. We each have own body, but"
parent = 3

[[nodes]]
id = 10
depth = 2
kind = "speaker"
speaker = "Hallak"
text = "our minds are united, except for some parts which aren't. We mostly"
parent = 3

[[nodes]]
id = 11
depth = 2
kind = "speaker"
speaker = "Tirrie"
text = "think as one."
parent = 3

[[nodes]]
id = 12
depth = 2
kind = "speaker"
speaker = "Player"
text = "That doesn't really have the same ring to it."
parent = 3

[[nodes]]
id = 13
depth = 2
kind = "act"
text = "end"
parent = 3
is_terminal = true

[[nodes]]
id = 14
depth = 1
kind = "option"
text = "What manner of beings are you?"
parent = -1
children = [15, 16, 17, 18, 19, 20, 22]

[[nodes]]
id = 15
depth = 2
kind = "speaker"
speaker = "Player"
text = "What manner of beings are you?"
parent = 14

[[nodes]]
id = 16
depth = 2
kind = "speaker"
speaker = "Nirrie"
text = """
We are the spirits of the river Elid, many ages ago we used to be mindless wandering spirits, with little mind or purpose, we were here even in the first age. Then great Elidinis came to the desert and bound us to her
"""
parent = 14

[[nodes]]
id = 17
depth = 2
kind = "speaker"
speaker = "Nirrie"
text = "river, we've"
parent = 14

[[nodes]]
id = 18
depth = 2
kind = "speaker"
speaker = "Tirrie"
text = """
become one with the river and over the centuries become full of the power of Elidinis that was in her river. We are now her trusted guardians of the Elid, we can control the river and anything which happens
"""
parent = 14

[[nodes]]
id = 19
depth = 2
kind = "speaker"
speaker = "Tirrie"
text = "near the river we know about."
parent = 14

[[nodes]]
id = 20
depth = 2
kind = "option"
text = "Wow how do you finish each others sentences like that?"
parent = 14
children = [21]

[[nodes]]
id = 21
depth = 3
kind = "act"
text = "above"
parent = 20

[[nodes]]
id = 22
depth = 2
kind = "option"
text = "Tell me more of Elidinis."
parent = 14
children = [23, 24, 25]

[[nodes]]
id = 23
depth = 3
kind = "speaker"
speaker = "Player"
text = "Tell me more of Elidinis."
parent = 22

[[nodes]]
id = 24
depth = 3
kind = "speaker"
speaker = "Nirrie"
text = "Elidinis is one of a group of gods, known as the Menaphite Pantheon. She is wife of their leader Tumeken. She is the Menaphite goddess of growth and fertility and goddess of the river."
parent = 22

[[nodes]]
id = 25
depth = 3
kind = "act"
text = "end"
parent = 22
is_terminal = true

[[nodes]]
id = 26
depth = 1
kind = "option"
text = "Don't many other towns not follow Elidinis?"
parent = -1
children = [27, 28, 29, 30, 46]

[[nodes]]
id = 27
depth = 2
kind = "speaker"
speaker = "Player"
text = "Don't many other towns not follow Elidinis though? Why did you pick on Nardah specifically?"
parent = 26

[[nodes]]
id = 28
depth = 2
kind = "speaker"
speaker = "Tirrie"
text = "It is true many do not follow Elidinis, but there is more to the story than that. The answers"
parent = 26

[[nodes]]
id = 29
depth = 2
kind = "speaker"
speaker = "Hallak"
text = "lie in the story of Nardarine. Wouldst thou likest to hear the telling of this tale? It is not a short one."
parent = 26

[[nodes]]
id = 30
depth = 2
kind = "option"
text = "Yes I would like to hear this story."
parent = 26
children = [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]

[[nodes]]
id = 31
depth = 3
kind = "speaker"
speaker = "Player"
text = "Yes I would like to hear this story."
parent = 30

[[nodes]]
id = 32
depth = 3
kind = "speaker"
speaker = "Tirrie"
text = "Nardarine came from a town towards the north side of the desert which does not exist today. This was in the third age in the time thou callest"
parent = 30

[[nodes]]
id = 33
depth = 3
kind = "speaker"
speaker = "Hallak"
text = "the God Wars. Her town was once controlled by Saradomin, but there was a great battle there between Saradominist and Zamorakian forces which pretty much levelled the town"
parent = 30

[[nodes]]
id = 34
depth = 3
kind = "speaker"
speaker = "Nirrie"
text = """
to the ground. Most of the human citizens perished. Nardarine had the wisdom to escape into the desert before the fighting got really serious and thus survived. However she found herself wandering lost and alone in
"""
parent = 30

[[nodes]]
id = 35
depth = 3
kind = "speaker"
speaker = "Tirrie"
text = """
the desert. She prayed to Saradomin for help, but Saradomin was too concerned with the loss of a strategic outpost to worry about the fate of one small human. Nardarine had wandered towards the realm of
"""
parent = 30

[[nodes]]
id = 36
depth = 3
kind = "speaker"
speaker = "Hallak"
text = """
the Menaphite God Pantheon. Elidinis heard the prayers of Nardarine, she took pity on the wandering human and came unto her with water. 'Oh great goddess' exclaimed Nardarine 'I wish not to be involved more in
"""
parent = 30

[[nodes]]
id = 37
depth = 3
kind = "speaker"
speaker = "Nirrie"
text = """
the wars of the gods for they have caused me so much hardship already, I wish only for a quiet life somewhere'. Elidinis replied 'I will grant this unto thee on the condition that thou swearest to forever pay fealty and
"""
parent = 30

[[nodes]]
id = 38
depth = 3
kind = "speaker"
speaker = "Tirrie"
text = "homage to me and I grant this also unto thine descendents as long as they too will pay an oath of fealty and homage to me'. Nardarine said 'If you would grant me a safe home, with a"
parent = 30

[[nodes]]
id = 39
depth = 3
kind = "speaker"
speaker = "Hallak"
text = "supply of food and water, then I would surely do this for it is more than any other God would seem to do for me'. Then Elidinis made"
parent = 30

[[nodes]]
id = 40
depth = 3
kind = "speaker"
speaker = "Nirrie"
text = "a spring of water appear at Nardarines feet and brought stone from below the sand so that she"
parent = 30

[[nodes]]
id = 41
depth = 3
kind = "speaker"
speaker = "Tirrie"
text = """
might have something to build with. She called forth camels which have many uses and taste good in kebabs. She then provided Nardarine with a statuette in her image to worship. Nardarine built up her home. Over
"""
parent = 30

[[nodes]]
id = 42
depth = 3
kind = "speaker"
speaker = "Hallak"
text = """
time more refugees from the God Wars found Nardarine's home. Nardarine let them stay with her as long as they did make the same oath as her. Hence the town of Nardah was born and Nardarine lived the rest
"""
parent = 30

[[nodes]]
id = 43
depth = 3
kind = "speaker"
speaker = "Nirrie"
text = "of her days in the peacefulness that she craved. The oath was passed down the generations for many ages, but now seemeth to be forgotten. Now maybe thou canst see why we are not best pleased."
parent = 30

[[nodes]]
id = 44
depth = 3
kind = "speaker"
speaker = "Player"
text = "That does make some sense."
parent = 30

[[nodes]]
id = 45
depth = 3
kind = "act"
text = "end"
parent = 30
is_terminal = true

[[nodes]]
id = 46
depth = 2
kind = "option"
text = "Maybe another day."
parent = 26
children = [47, 48]

[[nodes]]
id = 47
depth = 3
kind = "speaker"
speaker = "Player"
text = "Maybe another day."
parent = 46

[[nodes]]
id = 48
depth = 3
kind = "act"
text = "end"
parent = 46
is_terminal = true
