title = "Transcript:Phingspet"
npcs = ["Grimesquit", "Phingspet"]
node_count = 102

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "'Ello 'Ello!"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "Who's this then?"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "I don't know any more than you do!"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "Well ask them!"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "You ask them!"
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "No! I'm not talking to some stranger in a sewer."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Go away, weirdo! We're busy!"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Would you look at that!"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Player"
text = "At what?"
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "It's [player name] again!"
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "speaker"
speaker = "Player"
text = "What do you want?"
parent = -1

[[nodes]]
id = 12
depth = 1
kind = "select"
text = "Select an Option"
parent = -1

[[nodes]]
id = 13
depth = 1
kind = "option"
text = "Jimmy Dazzler"
parent = -1
children = [14, 15, 16, 17, 18, 19]

[[nodes]]
id = 14
depth = 2
kind = "speaker"
speaker = "Player"
text = "Where can I find Jimmy Dazzler again?"
parent = 13

[[nodes]]
id = 15
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Didn't you find him in Ardougne?"
parent = 13

[[nodes]]
id = 16
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "He's normally in the Flying Horse Inn."
parent = 13

[[nodes]]
id = 17
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Give him a kiss from me!"
parent = 13

[[nodes]]
id = 18
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "I will absolutely not be doing that."
parent = 13

[[nodes]]
id = 19
depth = 2
kind = "act"
text = "end"
parent = 13
is_terminal = true

[[nodes]]
id = 20
depth = 1
kind = "option"
text = "Hooknosed Jack"
parent = -1
children = [21, 22, 23, 24, 25, 26, 27, 28, 29]

[[nodes]]
id = 21
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I can find Hooknosed Jack?"
parent = 20

[[nodes]]
id = 22
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "He's here in Varrock!"
parent = 20

[[nodes]]
id = 23
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Who 'nose' where, though!"
parent = 20

[[nodes]]
id = 24
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Ha! I'm sure you can 'scent' him out, [player name]{{sic}}"
parent = 20

[[nodes]]
id = 25
depth = 2
kind = "speaker"
speaker = "The Sisters Grime"
text = "Hahahaha!"
parent = 20

[[nodes]]
id = 26
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Come on, it's not that funny."
parent = 20

[[nodes]]
id = 27
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "You think our nose jokes are bad? Well..."
parent = 20

[[nodes]]
id = 28
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Our eye jokes are even cornea!"
parent = 20

[[nodes]]
id = 29
depth = 2
kind = "act"
text = "end"
parent = 20
is_terminal = true

[[nodes]]
id = 30
depth = 1
kind = "option"
text = "Smokin' Joe"
parent = -1
children = [31, 32, 33]

[[nodes]]
id = 31
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I can find Smokin' Joe?"
parent = 30

[[nodes]]
id = 32
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Last we heard he was in Keldagrim."
parent = 30

[[nodes]]
id = 33
depth = 2
kind = "act"
text = "end"
parent = 30
is_terminal = true

[[nodes]]
id = 34
depth = 1
kind = "option"
text = "The Face"
parent = -1
children = [35, 36, 37, 38]

[[nodes]]
id = 35
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I can find the Face?"
parent = 34

[[nodes]]
id = 36
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "She was in Port Sarim last we heard."
parent = 34

[[nodes]]
id = 37
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "You can't miss her!"
parent = 34

[[nodes]]
id = 38
depth = 2
kind = "act"
text = "end"
parent = 34
is_terminal = true

[[nodes]]
id = 39
depth = 1
kind = "option"
text = "Felkrash"
parent = -1
children = [40, 41, 42, 43, 44]

[[nodes]]
id = 40
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I can find Felkrash?"
parent = 39

[[nodes]]
id = 41
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "We shouldn't say, but-"
parent = 39

[[nodes]]
id = 42
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "She's got a secret den in Port Sarim!"
parent = 39

[[nodes]]
id = 43
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Not secret now, is it?!"
parent = 39

[[nodes]]
id = 44
depth = 2
kind = "act"
text = "end"
parent = 39
is_terminal = true

[[nodes]]
id = 45
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Would you look at that!"
parent = -1

[[nodes]]
id = 46
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "At what?"
parent = -1

[[nodes]]
id = 47
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "It's [player name] again!"
parent = -1

[[nodes]]
id = 48
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "What do you want?"
parent = -1

[[nodes]]
id = 49
depth = 1
kind = "speaker"
speaker = "Player"
text = "Can I have another rat pole please?"
parent = -1

[[nodes]]
id = 50
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Here you go."
parent = -1

[[nodes]]
id = 51
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Stick the ratsies your cat splats on it!"
parent = -1

[[nodes]]
id = 52
depth = 1
kind = "speaker"
speaker = "Player"
text = "Er... will do."
parent = -1

[[nodes]]
id = 53
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "Anything else?"
parent = -1

[[nodes]]
id = 54
depth = 1
kind = "select"
text = "Select an option"
parent = -1

[[nodes]]
id = 55
depth = 1
kind = "option"
text = "Jimmy Dazzler"
parent = -1
children = [56]

[[nodes]]
id = 56
depth = 2
kind = "act"
text = "above"
parent = 55

[[nodes]]
id = 57
depth = 1
kind = "option"
text = "Hooknosed Jack"
parent = -1
children = [58]

[[nodes]]
id = 58
depth = 2
kind = "act"
text = "above"
parent = 57

[[nodes]]
id = 59
depth = 1
kind = "option"
text = "Smokin' Joe"
parent = -1
children = [60]

[[nodes]]
id = 60
depth = 2
kind = "act"
text = "above"
parent = 59

[[nodes]]
id = 61
depth = 1
kind = "option"
text = "The Face"
parent = -1
children = [62]

[[nodes]]
id = 62
depth = 2
kind = "act"
text = "above"
parent = 61

[[nodes]]
id = 63
depth = 1
kind = "option"
text = "Felkrash"
parent = -1
children = [64]

[[nodes]]
id = 64
depth = 2
kind = "act"
text = "above"
parent = 63

[[nodes]]
id = 65
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "Eh? Would you credit da."
parent = -1

[[nodes]]
id = 66
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Wha?"
parent = -1

[[nodes]]
id = 67
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "It's [player name] again init?"
parent = -1

[[nodes]]
id = 68
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Wha?"
parent = -1

[[nodes]]
id = 69
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "[player name] has come back again."
parent = -1

[[nodes]]
id = 70
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "S' wha does 'ey want?"
parent = -1

[[nodes]]
id = 71
depth = 1
kind = "speaker"
speaker = "Player"
text = "Oh come on, stop the act. It's just not funny anymore."
parent = -1

[[nodes]]
id = 72
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "Ya it is."
parent = -1

[[nodes]]
id = 73
depth = 1
kind = "speaker"
speaker = "Grimesquit"
text = "Ha! Ha!"
parent = -1

[[nodes]]
id = 74
depth = 1
kind = "speaker"
speaker = "Phingspet"
text = "Ha! Ha!"
parent = -1

[[nodes]]
id = 75
depth = 1
kind = "option"
text = "Jimmy Dazzler"
parent = -1
children = [76, 77, 78, 79, 80]

[[nodes]]
id = 76
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I would find Jimmy Dazzler?"
parent = 75

[[nodes]]
id = 77
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "'Ees in Ardougne. In ee?"
parent = 75

[[nodes]]
id = 78
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "'e is, e is. He stays in the Flying Horse dun 'e?"
parent = 75

[[nodes]]
id = 79
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Tell 'im we said 'ello. Will ye? {{Colour|#0000ff|She then breaks out in a burst of girly giggles.}}"
parent = 75

[[nodes]]
id = 80
depth = 2
kind = "act"
text = "end"
parent = 75
is_terminal = true

[[nodes]]
id = 81
depth = 1
kind = "option"
text = "Hooknosed Jack"
parent = -1
children = [82, 83, 84, 85, 86, 87, 88]

[[nodes]]
id = 82
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I would find Hooknosed Jack?"
parent = 81

[[nodes]]
id = 83
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Da big ugly's ere in Vu'rock."
parent = 81

[[nodes]]
id = 84
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Da big ugly! Ha that's a good one. 'E is big n ugly though isn't e, serve him right for all the fights e get's in."
parent = 81

[[nodes]]
id = 85
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Ha! I nose the truth when I 'ears it! Get it? Get it? Nose the truth?"
parent = 81

[[nodes]]
id = 86
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Ha, ha, ha ah ha....."
parent = 81

[[nodes]]
id = 87
depth = 2
kind = "other"
text = "You leave the sisters grime mid cackle."
parent = 81

[[nodes]]
id = 88
depth = 2
kind = "act"
text = "end"
parent = 81
is_terminal = true

[[nodes]]
id = 89
depth = 1
kind = "option"
text = "Smokin' Joe"
parent = -1
children = [90, 91, 92]

[[nodes]]
id = 90
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I would find Smokin' Joe?"
parent = 89

[[nodes]]
id = 91
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Short stuff's out in Keldagrime."
parent = 89

[[nodes]]
id = 92
depth = 2
kind = "act"
text = "end"
parent = 89
is_terminal = true

[[nodes]]
id = 93
depth = 1
kind = "option"
text = "The face"
parent = -1
children = [94, 95, 96, 97]

[[nodes]]
id = 94
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I would find the Face?"
parent = 93

[[nodes]]
id = 95
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "Hey features? Where is she?"
parent = 93

[[nodes]]
id = 96
depth = 2
kind = "speaker"
speaker = "Grimesquit"
text = "Port Sarim last I 'eard."
parent = 93

[[nodes]]
id = 97
depth = 2
kind = "act"
text = "end"
parent = 93
is_terminal = true

[[nodes]]
id = 98
depth = 1
kind = "option"
text = "Felkrash"
parent = -1
children = [99, 100, 101]

[[nodes]]
id = 99
depth = 2
kind = "speaker"
speaker = "Player"
text = "Can you tell me where I would find Felkrash?"
parent = 98

[[nodes]]
id = 100
depth = 2
kind = "speaker"
speaker = "Phingspet"
text = "She's travels about a bit, but I reckon Port Sarim."
parent = 98

[[nodes]]
id = 101
depth = 2
kind = "act"
text = "end"
parent = 98
is_terminal = true
