title = "Transcript:Recruiter"
npcs = ["Man (West Ardougne)", "Recruiter"]
node_count = 6

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Recruiter"
text = "Citizens of West Ardougne! King Tyras needs you for his Royal Army! Who will join this noble cause?"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Man"
text = "Plague bringer!"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Man"
text = "King Tyras is scum!"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Recruiter"
text = "Tyras will be informed of these words of treason!"
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "box"
text = "Someone throws a tomato at the recruiter."
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
