title = "Transcript:Shilop"
npcs = ["Wilough", "Shilop"]
node_count = 12

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Player"
text = "Hello youngster!"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Shilop"
text = "[I/We] don't talk to strange old people."
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Player"
text = "Hey who you calling old?! And strange?!"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 4
depth = 1
kind = "speaker"
speaker = "Player"
text = "Hello again."
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Wilough"
text = "You think you're tough do you?"
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Player"
text = "Pardon?"
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "speaker"
speaker = "Wilough"
text = "I can beat anyone up!"
parent = -1

[[nodes]]
id = 8
depth = 1
kind = "speaker"
speaker = "Shilop"
text = "He can you know!"
parent = -1

[[nodes]]
id = 9
depth = 1
kind = "speaker"
speaker = "Player"
text = "Really?"
parent = -1

[[nodes]]
id = 10
depth = 1
kind = "box"
text = "The boy begins to jump around with his fists up. You decide it's best not to kill him just yet."
parent = -1

[[nodes]]
id = 11
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
