title = "Transcript:The Magic Egg"
npcs = ["Duke Rabbacio"]
node_count = 8

[[nodes]]
id = 0
depth = 1
kind = "speaker"
speaker = "Player"
text = "Big Egg, will I ever..."
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "speaker"
speaker = "Duke Rabbacio"
text = "None can talk to it except me!"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "speaker"
speaker = "Player"
text = "Sorry Duke..."
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true

[[nodes]]
id = 4
depth = 1
kind = "box"
text = "You hop closer to the table to try take the egg."
parent = -1

[[nodes]]
id = 5
depth = 1
kind = "speaker"
speaker = "Duke Rabbacio"
text = "What are you doing?! Step away from it."
parent = -1

[[nodes]]
id = 6
depth = 1
kind = "speaker"
speaker = "Player"
text = "Sorry Duke..."
parent = -1

[[nodes]]
id = 7
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
