title = "Transcript:Trailblazer cane"
npcs = []
node_count = 5

[[nodes]]
id = 0
depth = 1
kind = "other"
text = "{{mes|You must be wearing the full set of Trailblazer Relic hunter (T3) to use this emote.}}"
parent = -1

[[nodes]]
id = 1
depth = 1
kind = "other"
text = "{{mes|You must be wearing the full set of Trailblazer Relic hunter (T3) to use this emote.}}"
parent = -1

[[nodes]]
id = 2
depth = 1
kind = "other"
text = "{{mes|This seems like an odd place to perform this emote.}}"
parent = -1

[[nodes]]
id = 3
depth = 1
kind = "speaker"
speaker = "Player"
text = "Wait... That's illegal."
parent = -1

[[nodes]]
id = 4
depth = 1
kind = "act"
text = "end"
parent = -1
is_terminal = true
