quest = "The Frozen Door"
step_count = 2

[[steps]]
index = 0
name = "The Four Pieces"
links = ["Frozen key (The Frozen Door)", "God Wars Dungeon", "Kree'arra/Strategies", "General Graardor/Strategies", "Commander Zilyana/Strategies", "K'ril Tsutsaroth/Strategies"]
text = """
[[File:Fighting General Graardor.png|thumb|280px|To obtain the pieces of the [[Frozen key (The Frozen Door)|frozen key]], the generals of each faction in the [[God Wars Dungeon]] must be defeated.]]
The player will have to kill the generals of each faction in the [[God Wars Dungeon]]. They must deal the most damage to the boss prior to their death in order to obtain the key pieces. If the player cannot deal enough damage (if going in groups), they can obtain the pieces from their bodyguards, albeit at a rate of 1/20. Once all four pieces have been obtained, they can be assembled to create the [[Frozen key (The Frozen Door)|frozen key]].

Strategy guides for each of the four bosses can be found here:
* [[Kree'arra/Strategies|Kree'arra]]
* [[General Graardor/Strategies|General Graardor]]
* [[Commander Zilyana/Strategies|Commander Zilyana]]
* [[K'ril Tsutsaroth/Strategies|K'ril Tsutsaroth]]
"""

[[steps]]
index = 1
name = "The Evil Within"
links = ["frozen door", "God Wars Dungeon", "Ashuelot Reis", "Zaros", "Nex"]
text = """
[[File:Ashuelot Reis chathead.png|left]]
After assembling the frozen key, the player can finally unlock the [[frozen door]] and enter. The frozen door is located on the south side of the main chamber in the [[God Wars Dungeon]]. Inside, they will be greeted by [[Ashuelot Reis]], a nature spirit who reveals that there is no treasure inside, but instead a powerful [[Zaros]]ian general known as [[Nex]] and her army. Ashuelot explains Nex's history to the player before disappearing to the inner lobby area of the prison. This completes the miniquest.
{{clear|left}}
"""
