quest = "His Faithful Servants"
step_count = 1

[[steps]]
index = 0
name = "Main"
links = ["Strange Old Man", "Barrows", "Barrows Brothers", "Barrows chest", "strange icon", "Barrows/Strategies"]
text = """
Speak to the [[Strange Old Man]] at the [[Barrows]]. He will ask that you retrieve an icon that the [[Barrows Brothers]] have guarded and that an unknown entity wants back.

Players must defeat all six brothers and then open the [[Barrows chest]] to receive the [[strange icon]]. For a guide on taking on the brothers, [[Barrows/Strategies|see here]].

You '''MUST''' have enough inventory space to receive the strange icon when looting the chest, as it will not drop to the ground and will require you to defeat all the brothers again. If you want to be sure that you will receive the icon, leave at least six inventory spaces open before searching the chest.

After receiving the strange icon, speak with the Strange Old Man again to complete the miniquest.
"""
