quest = "The Feud"
step_count = 5

[[steps]]
index = 0
name = "Starting in Pollnivneach"
links = ["The Asp & Snake Bar.", "beer", "Ali the Barman", "Drunken Ali", "Ali Morrisane", "Menaphite Thug", "Ali the Operator", "Ali the Camel Man", "coins", "Receipt (The Feud)", "Thieving", "villager"]
text = """
[[File:The Asp & Snake Bar..png|thumb|right|220px|The Asp & Snake Bar]]
Head to the [[The Asp & Snake Bar.|bar]] in the south-eastern corner of the village. Buy 3 [[beer]]s from [[Ali the Barman]] if you don't already have some, and then talk to [[Drunken Ali]], who will ask for beer in return for information. '''Use''' each beer on him, '''completing each dialogue before continuing'''. He will tell you that [[Ali Morrisane]]'s nephew is in trouble with the gangs, but you won't get any information out of them while they are feuding.

Head west of the bar to a purple and yellow tent, and talk to any [[Menaphite Thug]] (not [[Ali the Operator]]). They will mention that the feud started after the Bandits stole a camel from them.

Talk to any bandit in the north part of the town, who will blame the feud on the Menaphites stealing a camel from them.

Talk to [[Ali the Camel Man]] at the building north-west of the bar, south of the kebab store, and ask to buy two camels. Offer him 500 [[coins]] to receive two camel [[Receipt (The Feud)|receipts]]. Return to any Menaphite thug in the southern part of town, and then any Bandit in the northern part of town, to give each receipt. Both gangs will be outraged at the offering.

Talk to [[Ali the Operator]] by the purple tent south-west of Pollnivneach, and ask him if you can join his gang. He will ask the player to [[Thieving#Pickpocketing|pickpocket]] 3 [[villager]]s to prove themselves.
"""

[[steps]]
index = 1
name = "Picking the villagers' pockets"
links = ["villager", "Thieving", "Ali the Operator", "Street urchin", "coins", "blackjack"]
text = """
[[File:The Feud - knocking out villager.png|thumb|220px|Knocking out one of the [[villager]]s.]]
*'''1st villager''' – Simply head out and [[Thieving#Pickpocketing|pickpocket]] any villager. You will always fail unless you have spoken with [[Ali the Operator]].
*'''2nd villager''' – Go and talk to a [[Street urchin]] in or around the bar, and pay him 10 [[coins]] to distract a [[villager]], then quickly pickpocket the villager with the flashing arrow above his head. Make sure that the Street urchin is nearby one of the villagers, otherwise he will tell you that there is none around to distract. You must approach the villager from behind. If it fails, you will not lose your payment: talk to the urchin to try again.
*'''3rd villager''' – Talk to Ali the Operator again and ask for advice: he will give you a [[blackjack]]. Equip it, then lure a villager (into a secluded area in an empty building), knock them out with the blackjack, and finally pick their pocket (all options are right click).
"""

[[steps]]
index = 2
name = "The second job"
links = ["Ali the Operator", "jewels", "keys", "fake beard", "Kharidian headpiece", "desert disguise", "gloves", "Cactus (The Feud)", "wikipedia:Fibonacci_sequence", "inventory"]
text = """
[[File:The Feud - cracking the safe.png|thumb|220px|Cracking the safe.]]

Return to [[Ali the Operator]], who now wants you to steal the mayor's wife's [[jewels]] from the safe in their villa. He will give you [[keys]] to the front door. Combine the [[fake beard]] with the [[Kharidian headpiece]] to make a [[desert disguise]], then equip it and your [[gloves]]. The villa is north-east of the bar; on the huge [[Cactus (The Feud)|cactus]] just outside, click '''Hide behind'''.

When the dialogue appears and tells you that it is safe to go in since nobody is home, use your key on the door and go in.

On the {{FloorNumber|uk=1}}, search the landscape picture hanging beside the bed to discover the safe. The numbers on the safe progress from 1-9 (clockwise), and you must click '''1, 1, 2, 3, 5, 8''', on the dial to unlock it and take the jewels. This solution is the [[wikipedia:Fibonacci_sequence|Fibonacci sequence]], and you would have found a clue by searching the bed for a note which gives the first 5 numbers of the sequence.

:'''Note:''' If you do not have at least one [[inventory]] space open, you will have to enter this sequence again.
"""

[[steps]]
index = 3
name = "The third job"
links = ["Ali the Hag", "jewels", "Ali the Operator", "Menaphite Thug", "Ali the Barman", "snake", "coins", "snake charm", "snake basket", "Ratcatchers", "Ugthanki dung", "Ali the Kebab seller", "red hot sauce", "Dung (scenery)", "bucket", "My Arm's Big Adventure", "Forgettable Tale of a Drunken Dwarf", "Traitorous Ali"]
text = """
[[File:The Feud - Ali the Hag.png|thumb|220px|Talking to the [[Ali the Hag|Hag]].]]
Give the [[jewels]] to [[Ali the Operator]]. For your final task, he wants you to root out a traitor within the gang.

Talk to a [[Menaphite Thug]] gang member about it, who will suggest that the traitor must be Traitorous Ali. Return to Ali the Operator who will ask the player to quietly kill him.

Talk to [[Ali the Barman]] to find out that the beer on the table belongs to the traitor. Go talk to [[Ali the Hag]] up the hill to the west of the town, who will agree to make a poison for you if you can get her a [[snake]].

[[File:The Feud - snake charming.png|thumb|left|220px|Charming the [[snake]].]]
Now, go around the back of the pub, and put some [[coins]] in the snake charmer's money pot. He will give you a [[snake charm]] and a [[snake basket]].

Use ('''not''' Play) the snake charm on a desert snake, which can be found north of Ali the Operator's tent. You may fail to charm the snake causing it to attack you, simply kill it and then try again on another snake.

:'''Note''': You may have a snake charm already in your bank if you have completed [[Ratcatchers]]. You may receive another now if you have lost it.

Once you've brought the snake back to [[Ali the Hag]], she will tell you the second item she needs is fresh [[Ugthanki dung|camel dung]]. Go to [[Ali the Kebab seller]], located just north-west of the well in the centre of town, and ask for his [[red hot sauce]]. Take this to the camel shop, and use it on the food trough. A pile of [[Dung (scenery)|dung]] will appear after a few seconds; if it's green, repeat until you get brown dung. Use a [[bucket]] on it to obtain the desired Ugthanki dung.

:'''Tip:''' Consider gathering 3 more pieces of dung for [[My Arm's Big Adventure]], and 1 for [[Forgettable Tale of a Drunken Dwarf]] (where there is a 1/25 chance to need one).

Take the dung to Ali the Hag and she'll give you some poison to kill [[Traitorous Ali]].

Go to the pub, use the poison on the table with the beer, and then go back to Ali the Operator.

<gallery mode="packed" heights="150">
The Feud - pouring hot sauce.png|Pouring the [[red hot sauce]] on the trough.
The Feud - poisonining drink.png|Pouring the hag's poison onto Traitorous Ali's drink.
</gallery>
"""

[[steps]]
index = 4
name = "Defeating the gang leaders"
links = ["safespot", "Tough Guy", "Ali the Operator", "Menaphite Leader", "bandit champion", "villager", "Bandit Leader", "Rug Merchant", "adamant scimitar", "Ali the Mayor", "Ali Morrisane"]
text = """
[[File:The Feud - Tough Guy safespot.png|thumb|220px|The [[safespot]] for the [[Tough Guy]].]]

Prepared for a fight, talk to [[Ali the Operator]], who wants you to meet the [[Menaphite Leader]]. Speak to him outside the tent to discover that the Menaphites have world domination plans. After the player declines his offer to join them, the leader will summon a level 75 [[Tough Guy]] to attack you. You can [[safespot]] him behind the table inside the Menaphite Tent.

[[File:The Feud - Bandit champion safespot.png|thumb|220px|The ideal safespot for the [[bandit champion]].]]

After defeating him, talk to a [[villager]]; they are angry with you for upsetting the balance of power and will tell you that you need to deal with the [[Bandit Leader]] too. He's just north-west of the village by the [[Rug Merchant]].

Talk to the bandit leader, who will refuse to leave unless you can defeat their strongest warrior in battle, summoning a level 70 [[bandit champion]]. There is a [[safespot]] behind the crate near the rug merchant. Upon defeat, he will drop an [[adamant scimitar]].

Talk to the villagers, who will still be unimpressed by your actions so far and tell you to talk to the Mayor if you are looking for a reward.

Talk to [[Ali the Mayor]] by the well in the centre of the village. He will be a little more grateful about the results of your deeds, and explain that he smuggled [[Ali Morrisane]]'s nephew out of the town after he angered the gangs.

Finally, return to Ali Morrisane, who reveals that the entire quest was an elaborate scheme to get the player involved in Pollnivneach 'tourism'.

'''Congratulations, quest complete!'''
"""
