name = "Abyssal Sire"
source_pages = ["Abyssal Sire", "Abyssal Sire/Strategies"]
npc_ids = [5908, 5886, 5887, 5888, 5889, 5890, 5891]

[sections]
"=Phase 1=" = """
{{anchor|phase 1 equipment}}<tabber>
Recommended=

'''Note:''' This is only if the player is using melee for phase 2 and 3. The melee gear will be whatever you're using later in the fight. For phase 2 and 3, a melee weapon will be needed (if one handed, a shield slot item too).

<br/><br/>

The player brings a [[Scorching bow]] and arrows with full Melee gear in order to take out the respiratory system with the bow. This is because even with full melee gear, the bow is fairly accurate and usually oneshots the respiratory systems. The scorching bow allows the player to quickly dispose of the respiratory system without needing a full gear switch, making it possible to quickly move on to phase 2 so the player can melee the boss. At that stage, the weapon and shield slot can be switched out.

{{Recommended equipment
|style = Phase 1 Melee
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Amulet of rancour}}
|neck2 = {{plink|Amulet of torture}}
|neck3 = {{plink|Amulet of fury}}
|neck4 = {{plink|Amulet of glory}}
|cape1 = {{plink|Infernal cape}}
|cape2 = {{plink|Fire cape}}
|cape3 = {{plink|Max cape}} / {{plink|Hitpoints cape}}
|cape4 = {{plink|Mixed hide cape}}
|body1 = {{plink|Torva platebody}}
|body2 = {{plink|Bandos chestplate}}
|body3 = {{plink|Blood moon chestplate}}
|body5 = {{plink|Fighter torso}}
|legs1 = {{plink|Torva platelegs}}
|legs2 = {{plink|Bandos tassets}}
|legs3 = {{plink|Blood moon tassets}}
|legs4 = {{plink|Obsidian platelegs}}
|weapon1 = {{plink|Scorching bow}}{{efn|Only for phase 1. A melee weapon switch for phase 2 and 3 is needed. For example [[Emberlight]] and [[Avernic defender]] will be in the inventory ready to switch for phase 2; The player will also have special attack melee weapon}}
|ammo1 = {{plink|Amethyst arrow}}{{efn|The player can usually get a couple of shots off on the boss in the transition between phase 1 and 2, before it is in melee range. Therefore having decent arrows can help deal a little more damage, but are not necessary}}
|ammo2 = {{plink|Arrows|pic=Bronze arrow}}{{efn|Weaker arrows do not reduce accuracy and are therefore just as likely to oneshot the respiratory systems}}
|hands1 = {{plink|Ferocious gloves}}
|hands2 = {{plink|Barrows gloves}}
|hands3 = {{plink|Dragon gloves}}
|feet1 = {{plink|Avernic treads (max)}}
|feet2 = {{plink|Primordial boots}}
|feet3 = {{plink|Dragon boots}}
|feet4 = {{plink|Rune boots}}
|ring1 = {{plink|Ultor ring}}
|ring2 = {{plink|Berserker ring (i)}}
|ring3 = {{plink|Lightbearer}}
}}
{{notelist}}

|-|
Magic=
Unless using a [[Tumeken's shadow]], [[Magic]] is only used to kill the [[respiratory system]]s. Their magic defence is so low they can be hit when wearing full melee gear.

{{Recommended equipment
|style = Phase 1 Magic
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Occult necklace}}
|cape1 = {{plink|Imbued god cape|pic=Imbued guthix cape}}
|body1 = {{plink|Ancestral robe top}}
|body2 = {{plink|Virtus robe top}}
|body3 = {{plink|Bloodbark body}}{{efn|name=bloodbark|with [[Ancient blood sceptre]] for additional healing}}
|legs1 = {{plink|Ancestral robe bottom}}
|legs2 = {{plink|Virtus robe bottom}}
|legs3 = {{plink|Bloodbark legs}}{{efn|name=bloodbark|with [[Ancient blood sceptre]] for additional healing}}
|weapon1 = {{plink|Tumeken's shadow}}
|weapon2 = {{plink|Sanguinesti staff}}
|weapon3 = {{plink|Trident of the swamp}}
|weapon4 = {{plink|Trident of the seas}}
|weapon5 = {{plink|Blood ancient sceptre}} (for overheal) / {{plink|Ancient sceptre}}
|shield1 = {{plink|Elidinis' ward (f)}}{{efn|name=offhand|with 1 handed staffs}}
|shield2 = {{plink|Elidinis' ward}} / {{plink|Arcane spirit shield}}{{efn|name=offhand|with 1 handed staffs}}
|shield3 = {{plink|Ancient wyvern shield}} / {{plink|Malediction ward}} / {{plink|Mage's book}}{{efn|name=offhand|with 1 handed staffs}}
|hands1 = {{plink|Confliction gauntlets}}
|hands2 = {{plink|Tormented bracelet}}
|hands3 = {{plink|Bloodbark gauntlets}}{{efn|name=gauntlets|If blood barrage's max hit is >39 with [[Blood ancient sceptre]], will give 1 more hp}}
}}
{{notelist}}

|-|
Ranged=
Unless ranging the boss, [[Ranged]] is only used to kill the [[respiratory system]]s. Their defence is very low so high accuracy is unnecessary. The Scorching bow will one-shot the systems, even with bronze arrows. You do not need any switches other than the bow.

{{Recommended equipment
|style = Phase 1 Ranged
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Necklace of anguish}}
|neck2 = {{plink|Amulet of fury}}
|neck3 = {{plink|Amulet of glory}}
|cape1 = {{plink|Dizana's quiver}}
|cape2 = {{plink|Ava's assembler}} (Or best [[Ava's device]])
|body1 = {{plink|Masori body (f)}}
|body2 = {{plink|Crystal body}} {{efn|name=Crystal|With Bow of Faerdhinen}}
|body3 = {{plink|Hueycoatl hide body}} > <br>{{plink|Blessed body|pic=Guthix d'hide body}}
|body4 = {{plink|Black d'hide body}}
|legs1 = {{plink|Masori chaps (f)}}
|legs2 = {{plink|Crystal legs}} {{efn|name=Crystal|With Bow of Faerdhinen}}
|legs3 = {{plink|Hueycoatl hide chaps}} > <br>{{plink|Blessed chaps|pic=Guthix chaps}}
|legs4 = {{plink|Black d'hide chaps}}
|weapon1 = {{plink|Scorching bow}}
|weapon2 = {{plink|Bow of faerdhinen}}
|weapon3 = {{plink|Toxic blowpipe}} (with {{plink|amethyst dart}}s or better)
|weapon4 = {{plink|Webweaver bow}} / <br/>{{plink|Craw's bow}}
|weapon5 = {{plink|Crystal bow}}{{efn|name=Crystal2|With Crystal equipment}}
|ammo1 = {{plink|Dragon arrow}}
|ammo2 = {{plink|Amethyst arrow}}
|hands1 = {{plink|Zaryte vambraces}}
|hands2 = {{plink|Barrows gloves}}
|hands3 = {{plink|Blessed vambraces|pic=Guthix bracers}} <br>{{plink|Black d'hide vambraces}}
}}
{{notelist}}
|-|
Melee=
[[Melee]] is only viable for killing the [[respiratory system]]s if using a [[Noxious halberd]], but is worse than both ranged and magic due to the extra distance the player must run.

{{Recommended equipment
|style = Phase 1 Melee
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Amulet of rancour}}
|neck2 = {{plink|Amulet of torture}}
|neck3 = {{plink|Amulet of fury}}
|neck4 = {{plink|Amulet of glory}}
|cape1 = {{plink|Infernal cape}}
|cape2 = {{plink|Fire cape}}
|cape3 = {{plink|Max cape}} / {{plink|Hitpoints cape}}
|cape4 = {{plink|Mixed hide cape}}
|body1 = {{plink|Torva platebody}}
|body2 = {{plink|Bandos chestplate}}
|body3 = {{plink|Blood moon chestplate}}
|body5 = {{plink|Fighter torso}}
|legs1 = {{plink|Torva platelegs}}
|legs2 = {{plink|Bandos tassets}}
|legs3 = {{plink|Blood moon tassets}}
|legs4 = {{plink|Obsidian platelegs}}
|weapon1 = {{plink|Noxious halberd}}
|ammo1 = {{plink|Rada's blessing 4}}
|ammo2 = {{plink|God blessing|pic=Peaceful blessing}}
|hands1 = {{plink|Ferocious gloves}}
|hands2 = {{plink|Barrows gloves}}
|hands3 = {{plink|Dragon gloves}}
|feet1 = {{plink|Avernic treads (max)}}
|feet2 = {{plink|Primordial boots}}
|feet3 = {{plink|Dragon boots}}
|feet4 = {{plink|Rune boots}}
|ring1 = {{plink|Ultor ring}}
|ring2 = {{plink|Berserker ring (i)}}
|ring3 = {{plink|Lightbearer}}
}}
{{notelist}}
</tabber>
"""

"=Phase 2 and Phase 3=" = """
<tabber>
Melee - No defence reduction=
The optimal strategy is to use [[Emberlight]] or [[Osmumten's fang]], along with a [[Lightbearer]]. The high accuracy of these weapons makes reducing the Sire's defence unnecessary, so all special attack energy is saved for damage in Phase 3.

{{Recommended equipment
|style = Phase 2 Melee - DPS
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Amulet of rancour}}
|neck2 = {{plink|Amulet of torture}}
|neck3 = {{plink|Amulet of fury}}
|neck4 = {{plink|Amulet of glory}}
|cape1 = {{plink|Infernal cape}}
|cape2 = {{plink|Fire cape}}
|cape3 = {{plink|Ardougne cloak 4}}
|cape4 = {{plink|Max cape}} / {{plink|Hitpoints cape}}
|body1 = {{plink|Torva platebody}}
|body2 = {{plink|Bandos chestplate}} ><br>{{plink|Oathplate chest}}
|body3 = {{plink|Justiciar chestguard}}
|body4 = {{plink|Barrows equipment|pic=Torag's platebody|txt=Barrows body}}
|body5 = {{plink|Fighter torso}}
|legs1 = {{plink|Torva platelegs}}
|legs2 = {{plink|Bandos tassets}} ><br>{{plink|Oathplate legs}}
|legs3 = {{plink|Justiciar legguards}}
|legs4 = {{plink|Barrows equipment|pic=Torag's platelegs|txt=Barrows legs}}
|legs5 = {{plink|Obsidian platelegs}}
|weapon1 = {{plink|Emberlight}}{{efn|name=stab|Use stab attack style, use slash when using Oathplate armour.}}
|weapon2 = {{plink|Osmumten's fang}}
|shield1 = {{plink|Avernic defender}}
|shield2 = {{plink|Dragon defender}}
|shield3 = {{plink|Dragonfire shield}}
|shield4 = {{plink|Rune defender}}
|ammo1 = ''See [[#phase 1 equipment|Phase 1]] recommended''
|ammo2 = {{plink|Rada's blessing 4}}
|ammo3 = {{plink|God blessing|pic=Peaceful blessing}}
|hands1 = {{plink|Ferocious gloves}}
|hands2 = {{plink|Barrows gloves}}
|hands3 = {{plink|Dragon gloves}}
|feet1 = {{plink|Avernic treads (max)}}
|feet2 = {{plink|Primordial boots}}
|feet3 = {{plink|Dragon boots}}
|feet4 = {{plink|Echo boots}}
|feet5 = {{plink|Guardian boots}}
|ring1 = {{plink|Lightbearer}}
|special1 = {{plink|Burning claws}}{{efn|name=stab|Use stab attack style, use slash when using Oathplate armour.}}
|special2 = {{plink|Voidwaker}}
|special3 = {{plink|Dragon claws}} /<br/>{{plink|Crystal halberd}}{{efn|Dragon claws will deal higher damage per second, but a crystal halberd will deal more damage per special attack energy.}}
|special4 = {{plink|Abyssal dagger}}
|special5 = {{plink|Dragon dagger}}
}}
{{notelist}}

|-|
Melee - Defence reduction=
If the player can reduce the Sire's defence with an [[Elder maul]] or [[Dragon warhammer]] special attack, weapons such as the [[Scythe of vitur]] become considerably more effective. However, this approach is typically slower than using a highly accurate weapon and damaging special attacks.</br>

With lower defence levels, players should consider prioritising ranged defence over melee strength to avoid being overwhelmed with damage from the spawns.

{{Recommended equipment
|style = Phase 2 Other Melee Weapons
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Amulet of rancour}}
|neck2 = {{plink|Amulet of torture}}
|neck3 = {{plink|Amulet of fury}}
|neck4 = {{plink|Amulet of glory}}
|cape1 = {{plink|Infernal cape}}
|cape2 = {{plink|Fire cape}}
|cape3 = {{plink|Ardougne cloak 4}}
|cape4 = {{plink|Max cape}} / {{plink|Hitpoints cape}}
|body1 = {{plink|Torva platebody}} /<br>{{plink|Oathplate chest}}
|body2 = {{plink|Bandos chestplate}} / {{plink|Blood moon chestplate}}
|body3 = {{plink|Justiciar chestguard}}
|body4 = {{plink|Barrows equipment|pic=Torag's platebody|txt=Barrows body}}
|body5 = {{plink|Fighter torso}}
|legs1 = {{plink|Torva platelegs}} /<br>{{plink|Oathplate legs}}
|legs2 = {{plink|Bandos tassets}} / {{plink|Blood moon tassets}}
|legs3 = {{plink|Justiciar legguards}}
|legs4 = {{plink|Barrows equipment|pic=Torag's platelegs|txt=Barrows legs}}
|legs5 = {{plink|Obsidian platelegs}}
|weapon1 = {{plink|Scythe of vitur}} > {{plink|Emberlight}}{{efn|name=stab|Use stab attack style, use slash when using Oathplate armour.}}
|weapon2 = {{plink|Ghrazi rapier}} / {{plink|Arclight}}
|weapon3 = {{plink|Inquisitor's mace}}
|weapon4 = {{plink|Blade of saeldor}}
|weapon5 = {{plink|Zamorakian hasta}}
|shield1 = {{plink|Avernic defender}}
|shield2 = {{plink|Dragon defender}}
|shield3 = {{plink|Dragonfire shield}}
|shield4 = {{plink|Rune defender}}
|ammo1 = {{plink|Rada's blessing 4}}
|ammo2 = {{plink|God blessing|pic=Peaceful blessing}}
|hands1 = {{plink|Ferocious gloves}}
|hands2 = {{plink|Barrows gloves}}
|hands3 = {{plink|Dragon gloves}}
|feet1 = {{plink|Avernic treads (max)}}
|feet2 = {{plink|Primordial boots}}
|feet3 = {{plink|Dragon boots}}
|feet4 = {{plink|Echo boots}}
|feet5 = {{plink|Guardian boots}}
|ring1 = {{plink|Ultor ring}}
|ring2 = {{plink|Bellator ring}}{{efn|If using a slash weapon|name=bellator}}
|ring3 = {{plink|Lightbearer}}
|ring4 = {{plink|Berserker ring (i)}}
|ring5 = {{plink|Ring of suffering (i)}}
|special1 = {{plink|Elder maul}}
|special2 = {{plink|Dragon warhammer}}
|special3 = {{plink|Bandos godsword}}
|special4 = {{plink|Emberlight}} > {{plink|Arclight}}
}}
{{notelist}}

|-|
Magic - Tumeken's Shadow=

Magic is a viable method for killing the Abyssal Sire if using a Tumeken’s shadow as the primary weapon. With the best possible gear, Tumeken's shadow can offer excellent damage output against the Abyssal Sire, comparable to the best possible gear with melee. Important to keep in mind is the overall lower defence of a magic setup, so you should be careful with keeping your health up. The method is low effort as it reduces the amount of swaps; allowing you to bring more supplies.

The Eldritch nightmare staff and Accursed sceptre can be used interchangeably. It is recommended to use the Accursed sceptre for faster kills as it reduces the boss's magic and defence levels regardless of hit.

{{Recommended equipment
|style = Phase 2 Magic
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Occult necklace}}
|neck2 = {{plink|Amulet of fury}}
|neck3 = {{plink|Amulet of glory}}
|cape1 = {{plink|God capes#Imbuing|txt=Imbued god cape|pic=Imbued saradomin cape}}
|cape2 = {{plink|God capes|pic=Saradomin cape}}
|cape3 = {{plink|Max cape}}
|cape4 = {{plink|Infernal cape}}
|ammo1 = {{plink|Rada's blessing 4}}
|body1 = {{plink|Ancestral robe top}}
|body2 = {{plink|Virtus robe top}}
|legs1 = {{plink|Ancestral robe bottom}}
|legs2 = {{plink|Virtus robe bottom}}
|weapon1 = {{plink|Tumeken's shadow}}
|shield1 = {{plink|Elidinis' ward (f)}}{{efn|name=spec|For special attack}}
|shield2 = {{plink|Elidinis' ward}} {{efn|name=spec}}
|shield3 = {{plink|Ancient wyvern shield}} / {{plink|Malediction ward}} / {{plink|Mage's book}} {{efn|name=spec}}
|hands1 = {{plink|Confliction gauntlets}}
|hands2 = {{plink|Tormented bracelet}}
|feet1 = {{plink|Avernic treads (max)}}
|feet2 = {{plink|Eternal boots}}
|feet3 = {{plink|Echo boots}}
|feet4 = {{plink|Guardian boots}}
|ring1 = {{plink|Magus ring}} / {{plink|Lightbearer}}
|ring2 = {{plink|Seers ring (i)}}
|ring3 = {{plink|Brimstone ring}}
|special1 = {{plink|Eldritch nightmare staff}}
|special2 = {{plink|Accursed sceptre}}
}}
{{notelist}}

|-|
Ranged=

Ranged generally performs worse than melee, and the reduced defence will shorten trips. </br>
</br>

However, ranged can be used to deal additional damage before the start of Phase 2. Once all four respiratory systems are defeated, there is a brief window to attack the boss, despite it being out of melee range initially. Once the Abyssal Sire raises its arms, it becomes vulnerable to damage, including ranged attacks. During this window players can shoot the boss three times with the Scorching bow before it comes within melee range. Doing this can reduce its health by a good amount (up to 50% of your Scorching bow's max hit, multiplied by 3) before Phase 2 properly begins, making it a good strategy for players who want to optimize their kills.</br>
</br>
Thus, it can be a good idea to bring a few ranged switches, to ensure the player doesn't hit any zeroes while killing the respiratory systems, and to also help with the few bonus hits the Phase 1 to Phase 2 transition provides.

{{Recommended equipment
|style = Phase 2 Ranged
|head1 = {{plink|Slayer helmet (i)}}
|head2 = {{plink|Black mask (i)}}
|neck1 = {{plink|Necklace of anguish}}
|neck2 = {{plink|Amulet of fury}}
|neck3 = {{plink|Amulet of glory}}
|cape1 = {{plink|Dizana's quiver}}
|cape2 = {{plink|Ava's assembler}} (Or best [[Ava's device]])
|cape3 = {{plink|Max cape}}
|cape4 = {{plink|Ranging cape}}
|cape5 = {{plink|Infernal cape}} / {{plink|Mythical cape}} (for special)
|ammo1 = {{plink|Dragon arrow}}
|ammo2 = {{plink|Amethyst arrow}}
|ammo3 = {{plink|Rune arrow}}
|body1 = {{plink|Masori body (f)}}
|body2 = {{plink|Armadyl chestplate}}
|body3 = {{plink|Crystal body}}
|body4 = {{plink|Blessed body|pic=Guthix d'hide body}}
|body5 = {{plink|Karil's leathertop}}
|legs1 = {{plink|Masori chaps (f)}}
|legs2 = {{plink|Armadyl chainskirt}}
|legs3 = {{plink|Crystal legs}}
|legs4 = {{plink|Blessed chaps|pic=Guthix chaps}}
|legs5 = {{plink|Karil's leatherskirt}}
|weapon1 = {{plink|Scorching bow}}
|weapon2 = {{plink|Twisted bow}}
|weapon3 = {{plink|Toxic blowpipe}} ([[Dragon darts]])
|weapon4 = {{plink|Bow of faerdhinen}} (With [[Crystal armour]])
|weapon5 = {{plink|Toxic blowpipe}} (Amethyst or Rune darts)
|hands1 = {{plink|Zaryte vambraces}}
|hands2 = {{plink|Barrows gloves}}
|hands3 = {{plink|Combat bracelet|pic=Combat bracelet(4)}}
|feet1 = {{plink|Avernic treads (max)}}
|feet2 = {{plink|Pegasian boots}}
|feet3 = {{plink|Ranger boots}}
|feet4 = {{plink|Blessed boots|pic=Guthix d'hide boots}}
|feet5 = {{plink|Aranea boots}}
|ring1 = {{plink|Venator ring}}
|ring2 = {{plink|Archers ring (i)}}
|ring3 = {{plink|Ring of suffering (i)}}
|ring4 = {{plink|Tyrannical ring (i)}} (for special)
|special1 = {{plink|Elder maul}} /<br/>{{plink|Bandos godsword}}
|special2 = {{plink|Toxic blowpipe}}
|special3 = {{plink|Dragon claws}}
}}

|-|

</tabber>
"""

"=Phase 2=" = """
Stay on Row 1 during this phase, as attacking it from outside melee distance will cause the Sire to teleport you to itself and discharge a damaging blast of energy.

The Sire will use melee attacks that can hit up to 26 through prayer. Watch for miasma pools underneath the player; when they appear run to the other marked tile on Row 1. Ignore spawns unless killing the Sire at low levels with low DPS (in which case long kill times may make removing minions desirable). If reducing the Sire's defence, use one special attack now, otherwise save all special attack energy for phase 3.

Once the Sire is damaged below 50% of its health (212 health or less) it will start walking south. Run to Row 2 and activate [[Protect from Missiles]]. Advanced techniques can be used to pull the Sire south while attacking it, reducing the amount of time spent waiting for the Sire.

If the Sire reaches 0 health before the next phase starts, it will begin the next phase with 20% of its health.
"""

"=Standard attacks=" = """
During phase 2, the Sire uses three types of melee attacks; a swipe from its right arm, a flick from its right tendril, or a flick from both tendrils. The double flick can deal up to 66 damage. Using [[Protect from Melee]] will reduce the damage from these attacks to 6, 6 and 26 respectively.
"""
