name = "Ahrim the Blighted"
source_pages = ["Ahrim the Blighted"]
npc_ids = [1672]

[sections]
"Prayer info" = """
{{Prayer info
|name = Ahrim the Blighted
|level = 40
|xp = 20
|type = spectral
}}
"""
