name = "Blood Moon"
source_pages = ["Blood Moon"]
npc_ids = [13011]

[sections]
"Fight overview" = """
{{Main|Moons of Peril/Strategies#Boss mechanics}}

The boss' standard attacks are a series of three hits, rolling accuracy and damage against the player's melee defence. Once the boss misses one of the hits, the remaining hits in the stack will automatically miss. Each [[hitsplat]] will heal her for 1x and 2x for the first 2 taken hits respectively, essentially making this boss unkillable without a certain threshold of [[Damage per second/Melee|DPS]] to damage taken. The healing on the 3rd hit is 3x the damage dealt, with a minimum of 30 and a maximum of 50 healed.

After six standard attacks, she will use one of two special attacks, alternating between them:
* '''Blood Rain''' - The Blood Moon will disappear and rain blood from above, forming temporary pools of blood throughout the room. Move off of the blood pools on the floor to avoid standing on them.
* '''Blood Jaguar''' - [[Blood jaguar]]s spawn around the room, along with a damaging square of blood pools. Run to [[Eyatlalli]]'s glyph and attack the jaguar. Damage taken by stepping onto the pool too early or not stepping out of the jaguar's attack range will heal the Blood Moon for 3x the damage taken.
The entire fight repeats on a cycle of 156 game ticks making a tick counting cycle of either 2, 3, or 13 most useful.
"""
