name = "Blue Moon"
source_pages = ["Blue Moon"]
npc_ids = [13013]

[sections]
"Fight overview" = """
{{Main|Moons of Peril/Strategies#Boss mechanics}}

The boss' standard attacks are a series of three hits, rolling accuracy and damage against the player's melee defence. Once the boss misses one of the hits, the remaining hits in the stack will automatically miss. Not having enough defence and being hit by the boss will cause your hands to freeze, causing you to miss attacks.

After six standard attacks, she will use one of two special attacks, alternating between them:
* '''Weapon Freeze''' - Your weapon is forcefully removed and placed in a block of ice, where you must punch the ice with Eyatlalli's glyph under it. Icy spikes will also periodically appear that must be avoided.
* '''Frost Storm''' - Two braziers at the ends of the chamber are extinguished. Run to each and relight them, whilst avoiding the moving storms that deal damage and force you to walk for two ticks. The boss will also heal five times during the storm, restoring 10 health for each unlit brazier.  Restoring both braziers will also remove a portion of stacks from Curse of the Moon.
Stand in the sun symbol that rotates around the boss during regular attacks. Remaining outside the symbol will cause you to take increasing damage over time.
"""
