name = "Chaos Elemental"
source_pages = ["Chaos Elemental", "Chaos Elemental/Strategies"]
npc_ids = [2054]

[sections]
"Attacks" = """
The Chaos Elemental's primary attack, Discord, is a projectile attack that resembles series of three different colours fired at the target. This attack can deal either [[Magic]], [[Ranged]], or [[Melee]] damage — it is impossible to distinguish what damage is dealt. The projectiles hit into the 20s, but it is still suggested that players utilise [[Protect from Magic]] to reduce the chance of being hit, as the projectile deals magic damage most frequently.

It also has two special attacks. The first one, Confusion, teleports players a short space or several spaces away from it. The second attack, Madness, unequips up to four items that players are wielding, forcing them to take time to re-equip their [[armour]] and [[weapons]] before continuing the battle. Like most monsters, its attacks will continue to follow the player until impact and can travel through walls. The weapon of the player is always prioritised, so when this attack is successful, the player will always have to re-equip their weapon.

{| class="wikitable"
|-
! Discord !! Confusion !! Madness
|-
| [[File:Chaos Elemental primary attack.png|center|100px]]|| [[File:Chaos Elemental teleporting attack.png|center|100px]]|| [[File:Chaos Elemental disarming attack.png|center|50px]]
|-
| [[File:Chaos Elemental - Discord.ogg]]|| [[File:Chaos Elemental - Confusion.ogg]]|| [[File:Chaos Elemental - Madness.ogg]]
|-
|Deals [[Melee]], [[Ranged]] or [[Magic]] damage||Teleports the target somewhere nearby||Unequips up to four worn items
|}
"""

"Fight overview" = """
{{Main|Chaos Elemental/Strategies}}
The Chaos Elemental has three attacks:
* '''Discord''' - Deals either [[Magic]], [[Ranged]], or [[Melee]] damage
* '''Confusion''' - Teleports the player somewhere nearby, away from it
* '''Madness''' - Unequips up to four equipped items
"""
