name = "Commander Zilyana"
source_pages = ["Commander Zilyana", "Commander Zilyana/Strategies"]
npc_ids = [2205]

[sections]
"Fight overview" = """
{{Main|Commander Zilyana/Strategies}}
Like other God Wars Dungeon bosses, Zilyana roams around a rectangular room with her bodyguards until a player enters, attacking them on sight. While she has a significantly lower max hit than the other generals, she makes up for it with extremely fast and accurate attacks, and her bodyguards use a different combat style each. She will only use her magic attacks at melee distance, which has a minimum hit of 10 should it successfully hit the player{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1055016564595011585|date=24 October 2018|archiveurl=https://reldo.runescape.wiki/i/108460|archivedate=26 May 2020|quote=Zilyana has a 10-20 attack and K'ril has a 10-30 attack.}}. If all players leave, her health and stats will be reset.
"""
