name = "Corrupted Hunllef"
source_pages = ["Corrupted Hunllef"]
npc_ids = [9035, 9036, 9037, 9038]

[sections]
"=Attack style cycle=" = """
The Hunllef changes its prayer and attack styles on predictable cycles. Every fourth attack performed by the Hunllef (excluding the stomp attack but including summoning tornadoes) will cause the Hunllef to change its standard attack style; it will perform an animation before switching attack styles.
"""

"=Attacks=" = """
[[File:Fighting Corrupted Hunllef.png|thumb|left|250px|A player battles the Corrupted Hunllef.]]
*'''Standard attacks:''' The Hunllef uses two main standard attacks, a range crystal-like attack and a magic based orb attack.  The Hunllef will use Ranged as its first attack style.
*'''Stomp attack:''' If a player is underneath the Hunllef when it tries to attack the player, the Hunllef will perform a stomp attack which deals up to 68 typeless damage, similar to the stomp attack used by the [[Corporeal Beast]]. This attack does not count towards one of the Hunllef's four standard attacks it uses before switching.
*'''Prayer Disabling Attack:''' When the Hunllef is attacking using magic-based attacks, it has a chance to use an attack which turns off prayers. These attacks use a different game sound, hence it is recommended to use sounds during the fight. They are also a different colour, in case audio cues are not used.
*'''Tornadoes:''' The Hunllef summons multiple tornadoes that chase the player and deal high damage if they reach the player's location. These tornadoes disappear after 20 ticks (12 seconds). The amount of tornadoes summoned increases as the Hunllef takes damage.

The Hunllef will alternate between mage and ranged standard attacks after any combination of 4 standard, prayer-disabling, or tornado attacks.
"""

"Mechanics" = """
Both the Crystalline and Corrupted Hunllef use the same mechanics.
"""

"Protection against its attacks" = """
Players can use their [[protection prayers]] to reduce the damage from the Corrupted Hunllef's standard attacks. Wearing pieces of the crystal armour will further reduce the incoming damage.

{|class="wikitable"
! colspan=2 | Armour combination
!Corrupted Hunllef's max hit<ref group="A">While using the correct [[protection prayer]] against its ranged and magic attacks.</ref>
!Damage from tornadoes
!Corrupted Hunllef's max hit (no protection prayer)
|-
|{{NA}}||No armour||16||15-30
|?
|-
|{{plinkp|Corrupted helm (basic)}}{{plinkp|Corrupted body (basic)}}{{plinkp|Corrupted legs (basic)}}||Full T1 armour||13||15-25
|55
|-
|{{plinkp|Corrupted helm (attuned)}}{{plinkp|Corrupted body (attuned)}}{{plinkp|Corrupted legs (attuned)}}||Full T2 armour||10||10-20
|?
|-
|{{plinkp|Corrupted helm (perfected)}}{{plinkp|Corrupted body (perfected)}}{{plinkp|Corrupted legs (perfected)}}||Full T3 armour||8||7-15
|35
|}

{{Reflist|group=A}}
"""
