name = "Crystalline Hunllef"
source_pages = ["Crystalline Hunllef"]
npc_ids = [9021, 9022, 9023, 9024]

[sections]
"=Attack style cycle=" = """
The Hunllef changes its prayer and attack styles in predictable cycles. Every fourth attack performed by the Hunllef (excluding the stomp attack) will cause the Hunllef to change its standard attack style.
"""

"=Attacks=" = """
[[File:Fighting Crystalline Hunllef.png|thumb|left|250px|A player battles the Crystalline Hunllef.]]
*'''Standard attacks:''' The Hunllef uses two main standard attacks, a range crystal-like attack and a magic based orb attack. The Hunllef will alternate between the two attack styles every 4 attacks. The Hunllef will use Ranged as its first attack style.
*'''Stomp attack:''' If a player is underneath the Hunllef when it tries to attack the player, the Hunllef will perform a stomp attack which deals very high damage, similar to the stomp attack used by the [[Corporeal Beast]]. This attack does not count towards one of the Hunllef's four standard attacks it uses before switching.
*'''Prayer Disabling Attack:''' When the Hunllef is attacking using magic-based attacks, it has a chance to use an attack which turns off prayers. These attacks use a different game sound, hence it is recommended to use sounds during the fight.
*'''Tornadoes:''' The Hunllef summons multiple tornadoes that chase the player and deal high damage if they reach the player's location. The number of tornadoes summoned increases as the Hunllef takes damage. However, they always last for 20 ticks (12 seconds) before despawning.
"""

"Mechanics" = """
Both the Crystalline and Corrupted Hunllef use the same mechanics.
"""

"Protection against his attacks" = """
Players can use their [[protection prayers]] to reduce the damage from the Crystalline Hunllef's standard attacks. Wearing pieces of the crystal armour will further reduce the incoming damage.

{|class="wikitable"
! colspan=2 | Armour combination
!Crystalline Hunllef's max hit <ref group="a">While using the correct [[protection prayer]] against its ranged and magic attacks.</ref>
!Damage from tornadoes
|-
|{{NA}}||No armour||12||10-20
|-
|{{plinkp|Crystal helm (basic)}}{{plinkp|Crystal body (basic)}}{{plinkp|Crystal legs (basic)}}||Full T1 armour||10||10-16
|-
|{{plinkp|Crystal helm (attuned)}}{{plinkp|Crystal body (attuned)}}{{plinkp|Crystal legs (attuned)}}||Full T2 armour||8||7-13
|-
|{{plinkp|Crystal helm (perfected)}}{{plinkp|Crystal body (perfected)}}{{plinkp|Crystal legs (perfected)}}||Full T3 armour||6||5-10
|}

{{Reflist|group=a}}
"""
