name = "Dagannoth mother"
source_pages = ["Dagannoth mother"]
npc_ids = [980, 981, 982, 983, 984, 985, 986, 987, 988]

[sections]
"Weakness by colour" = """
{|class="wikitable"
!Image
!Colour
!Weakness
!Attack Using
|-
|[[File:Dagannoth mother white.png|40px]]
|White
|[[Air spells]]
|[[Wind Strike]], [[Wind Bolt|Bolt]], [[Wind Blast|Blast]], [[Wind Wave|Wave]], or [[Wind Surge|Surge]].
|-
|[[File:Dagannoth mother blue.png|40px]]
|Blue
|[[Water spells]]
|[[Water Strike]], [[Water Bolt|Bolt]], [[Water Blast|Blast]], [[Water Wave|Wave]], or [[Water Surge|Surge]].
|-
|[[File:Dagannoth mother orange.png|40px]]
|Orange
|Melee
|[[Melee]] attacks.
|-
|[[File:Dagannoth mother brown.png|40px]]
|Brown
|[[Earth spells]]
|[[Earth Strike]], [[Earth Bolt|Bolt]], [[Earth Blast|Blast]], [[Earth Wave|Wave]], or [[Earth Surge|Surge]].
|-
|[[File:Dagannoth mother red.png|40px]]
|Red
|[[Fire spells]]
|[[Fire Strike]], [[Fire Bolt|Bolt]], [[Fire Blast|Blast]], [[Fire Wave|Wave]], or [[Fire Surge|Surge]].
|-
|[[File:Dagannoth mother green.png|40px]]
|Green
|Ranged
|[[Ranged]] attacks.
|}
"""
