name = "Dharok the Wretched"
source_pages = ["Dharok the Wretched"]
npc_ids = [1673]

[sections]
"Prayer info" = """
{{Prayer info
|name = Dharok the Wretched
|level = 40
|xp = 20
|type = spectral
}}
"""
