name = "Eclipse Moon"
source_pages = ["Eclipse Moon"]
npc_ids = [13012]

[sections]
"Fight overview" = """
{{Main|Moons of Peril/Strategies#Boss mechanics}}

The boss' standard attacks are a series of three hits, rolling accuracy and damage against the player's melee defence. Once the boss misses one of the hits, the remaining hits in the stack will automatically miss.

After six standard attacks, she will use one of two special attacks, alternating between them:
* '''Searing Rays ''' - A moon shield will appear, and the Eclipse Moon will forcefully shove you behind it. The Eclipse Moon will begin attacking with rays of light, which the player can avoid by moving alongside the moon shield.
* '''Clones''' - You are shoved to the centre of the room and are bound in place. Clones of the Eclipse Moon will spawn around you, attacking you in five cycles of three, for a total of 15 attacks. You must face your character toward each clone as it spawns to prevent damage. Doing so will parry the incoming attack, sending an undelayed attack back at the boss; as such, slow, high-hitting weapons are recommended to be used during this attack. '''Only melee weapons will damage the boss during this phase - ranged and magic weapons will not deal damage.'''
"""
