name = "Elvarg"
source_pages = ["Elvarg"]
npc_ids = [817]

[sections]
"Dragonfire" = """
The [[dragonfire]] max damage only depends on your [[Dragonfire#Protection|dragonfire protection]] (prayer, potion, and/or shield). The [[super antifire potion]] (including the [[Extended super antifire|extended]] and [[Super antifire mix|mix]] versions) by itself is enough to prevent all damage (even without an [[anti-dragon shield]]) and stat drain, except for [[Prayer points]] which will still be drained every attack.

Every dragonfire attack will deduct 10% of the Player's remaining [[Prayer points]], rounded down.

{{:Dragonfire/Elvarg}}
"""
