name = "Galvek"
source_pages = ["Galvek"]
npc_ids = [8097, 8094, 8095, 8177, 8098, 8178, 8179, 8096]

[sections]
"=Dragonfire Bomb=" = """
Similarly to [[Vorkath]], Galvek can throw a special dragonfire ball in the air which lands on the player's position at the time of firing. This will instantly kill the player if they do not move away from it. Standing next to it will deal 50% as much damage. Antifire effects '''''do not''''' work against the special one-hit attack.
"""

"=Dragonfire=" = """
Galvek can utilise two other types of normal dragonfire; a pink variant that disables prayers on impact, and a normal orange variant. Using a super antifire potion in combination with the [[Anti-dragon shield]] will nullify all damage from his orange and pink dragonfire attacks as seen in the table below. {{:Dragonfire/Galvek}}
"""

"=Phase I (Fire)=" = """
Galvek stands at the bow of the ship, attacking players with [[Melee]] and [[Magic]]. He can occasionally launch fire bombs, which if touched (bombs cover a 3x3 radius), will deal an incredible amount of damage, and will very likely instantly kill the player. These fire bombs are always placed in the same position, and will explode after a set amount of time has passed or if the player moves within one tile of it. This phase is common to die in due to players trying to move to avoid his special [[dragonfire]] attack or moving at the same time Galvek teleports them, resulting in the player running into a bomb and dying. Galvek's defence in this phase can be lowered, however on transition to phase II his defence will be restored to its base value.
"""

"=Phase II (Air)=" = """
Galvek takes on the powers of air, flying towards the western side of the ship. He can occasionally launch gusts of wind that drain the player's stats by 2 and run energy by 40%. Galvek also begins to use [[Ranged]] attacks here and uses his Ranged and [[Magic]] attacks at random. Galvek '''still uses''' the one-hit fireball in this stage.
"""

"=Phase III (Water)=" = """
Galvek takes on the powers of water, flying towards the eastern side of the ship. He can occasionally send out [[tsunami]]s (acting much like the [[Fire Wave (Judge of Yama)|fire waves]] during a fight in the quest [[A Kingdom Divided]]) '''along with''' the standard one-hit fireball. If hit by these waves, the player will take between '''70 and 120 damage'''.{{CiteDiscord|author=Mod Ash|url=https://discord.com/channels/324132423636090880/431834766325841920/1418565018965901408|date=19 September 2025|quote=[Does Galvek have a minimum hit for his tsunami waves? Saw a 77 wiki says "will be hit 100+".] I think it hits 70-120 inclusive.|image=Ash Galvek tsunami damage.png|archiveurl=https://reldo.runescape.wiki/i/27962762#chat-messages-431834766325841920-1418565018965901408|archivedate=8 March 2026}}
Phase III has the potential to be Galvek's deadliest phase, as the player has very limited room for movement if Galvek launches his tsunami and his fireball special while the tsunami is active, leaving almost no room for error. Galvek also uses [[Ranged]] attacks much more commonly in this phase.
"""

"=Phase IV (Earth)=" = """
Galvek takes on the powers of earth, landing on the middle of the ship. He can occasionally launch earth projectiles, which if the player is caught in, will be bound for several seconds. This deals no actual damage to the player, but leaves them extremely vulnerable to the highly damaging [[dragonfire]], which he almost always uses if he is successful in binding the player. His earth attack can be avoided by simply moving one square. Moreover, walking in circles around Galvek or back and forth on the North or South end allows the player to avoid his rocks and dragonfire.

<gallery widths="300" heights="200" perrow="4">
File:Dragon Slayer II - Galvek's fire traps.png|Galvek's fire bombs during phase 1.
File:Dragon Slayer II - Galvek's hurricane.png|Galvek's hurricane attack during phase 2.
File:Dragon Slayer II - Galvek's tsunami.png|Galvek's tsunami attack during phase 3.
File:Dragon Slayer II - entombed in rock.png|Galvek's rock tomb attack during phase 4.
</gallery>{{clear}}
"""

"Mechanics" = """
Galvek has 1,200 health and four phases, with each phase consisting of 300 [[Hitpoints]]. Galvek can attack with all three forms of combat.
If player is outside of melee range, he may use a blue attack that pulls the player closer. Defence lowering attacks work against Galvek, but he will reset his Defence to its original level after every phase. [[Thrall]]s cannot be summoned during the fight, and he is immune to reflect damage.
"""
