name = "Gemstone Crab"
source_pages = ["Gemstone Crab", "Gemstone Crab/Strategies"]
npc_ids = [14779]

[sections]
"Mechanics" = """
* [[Ruby bolts (e)|Ruby bolt (e)]] special attacks treat the boss as if it has 300 [[Hitpoints]] and will deal 60 damage, increased to 66 if using a [[Zaryte crossbow]].
* The Gemstone Crab does not count towards slayer tasks, thus players will not receive a damage or accuracy bonus from a [[slayer helmet]] or [[black mask]].
* A [[dwarf multicannon]] cannot be placed in the crab's vicinity.
* [[Thrall|Thralls]] are unable to attack the Gemstone Crab, even though they can be summoned near it.
* The Gemstone Crab can be walked under while it is active, though its normal attacks can target and damage players if they stand in the quadrant it is focusing its attacks. The center tile of the 5x5 square it occupies is safe from attacks from all sides, though all players standing underneath will be shoved out when the Crab burrows with the message {{Mes|The burrowing crab forces you out of its way.}}.
"""
