name = "General Graardor"
source_pages = ["General Graardor", "General Graardor/Strategies"]
npc_ids = [2215]

[sections]
"=Attack Styles=" = """
Graardor attacks with both Melee and Ranged:

*The melee attack consists of a simple punch that deals up to 60 damage. He has a 2/3 chance of using melee whenever he attacks.
*As his Ranged attack, Graardor slams the ground to emit shockwaves to all players inside his chamber, dealing between 15 and 35 damage on successful hits. Despite it being a Ranged attack, Graardor can only use it within melee range of his current target. He has a 1/3 chance of using Ranged whenever he attacks.
"""

"Fight overview" = """
[[File:Fighting General Graardor.png|thumb|250px|A group of players fighting General Graardor and his minions.]]
{{Main|General Graardor/Strategies}}
Like other God Wars Dungeon bosses, Graardor roams around a rectangular room with his bodyguards until a player enters, attacking them on sight. He attacks primarily with [[melee]] (2/3 chance{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/689065027844878338|date=17 January 2016|archiveurl=https://reldo.runescape.wiki/i/102219|archivedate=29 March 2019|quote=2/3 melee, 1/3 "ranged".|name=attack chance}}), and his bodyguards use a different combat style each. Graardor may also use a [[ranged]] attack (1/3 chance{{NamedRef|attack chance}}) where he slams the ground, hitting all players in the room which has an equal chance to hit between 15-35 upon successfully hitting the player.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1054823168559538177|date=23 October 2018|archiveurl=https://reldo.runescape.wiki/i/102298|archivedate=26 May 2020|quote=[Graardor's ranged attack is] rolling 15-35 inclusive, with equal chances for each of those 21 numbers.}} Despite it being a Ranged attack, Graardor can only use it if he is within melee range of his current target. If there are no players in his chamber, his health and stats will be reset.
"""
