name = "Guthan the Infested"
source_pages = ["Guthan the Infested"]
npc_ids = [1674]

[sections]
"Prayer info" = """
{{Prayer info
|name = Guthan the Infested
|level = 40
|xp = 20
|type = spectral
}}
"""
