name = "Kephri"
source_pages = ["Kephri"]
npc_ids = [11721, 11719]

[sections]
"Mechanics" = """
{{Main|Tombs of Amascut/Strategies#Kephri, Guardian of Scabaras}}
[[File:Tombs of Amascut - Fighting Kephri.png|thumb|left|280px|A player fighting Kephri, the Guardian of Scabaras.]]
Kephri's main attack is a fireball that she launches into the air every few ticks. Players must move away from where it will land, which is indicated by the shadow on the ground. Her base defence level can be lowered by a maximum of 20 damage, reducing her base defence level down to a minimum of 60, however the defence level is reset for the final phase.

She is also shielded by scarab swarms, and must be defeated to disperse them. Whilst shielded, she will use two special attacks:
* '''Dung Strike''' - Kephri knocks the player backwards, dropping a row of dung along and blocking the way. This attack is forewarned by flies buzzing around a player, giving teammates a warning.
* '''Mass Incubation''' - Kephri will lay [[Egg (Tombs of Amascut)|eggs]] around the arena. If left unattended, they will explode in a 3x3 area with the larger, darker eggs hatching [[Agile Scarab]]s, while the smaller dormant eggs will deal surrounding damage.

Should players have the '''Path Level''' invocations active, every two levels will cause the following:

* Kephri's auto-attacks will be faster.
* During the shield recharge phase, groups of three scarab swarms may appear instead of one. The frequency of these increase at raid level 4.
{{Clear|left}}

Once Kephri's shield is depleted, she will summon her children which should be dealt with before resuming the fight. After two phases of shields, Kephri will finally be vulnerable to attacks and can be attacked directly.
"""
