name = "Kraken"
source_pages = ["Kraken", "Kraken/Strategies"]
npc_ids = [494, 496]

[sections]
"=Attack styles=" = """
During the fight, the player will be attacked by four [[Enormous Tentacle]]s and by the [[Kraken]] itself:
*The Kraken and the tentacles only attack with a [[typeless]] [[magical ranged]] attack:
**'Typeless' means that [[protection prayers]] will not have any effect.
**'Magical ranged' means that the attack accuracy is decided by the ranged attack bonuses of the Kraken and the magic defence bonuses of the player.
**The max hit of this attack is 28 from Kraken, and 2 from each tentacle.
**The attacks have an attack speed of 4 (i.e. every 2.4 seconds). Kraken's attacks are fairly inaccurate, but the tentacles are relatively accurate.
"""
