name = "Kree'arra"
source_pages = ["Kree'arra", "Kree'arra/Strategies"]
npc_ids = [3162]

[sections]
"Fight overview" = """
{{Main|Kree'arra/Strategies}}
Like other [[God Wars Dungeon]] [[bosses]], Kree'arra roams around a rectangular room with his bodyguards until a player enters, attacking them on sight. He attacks primarily with [[Ranged]], and his bodyguards use a different combat style each. However, if no one is targeting Kree'arra, he will fly up to players to use [[Melee]] attacks as well. If all players leave, his health and stats will be reset.

Like other Armadylean followers in the God Wars Dungeon, he and his bodyguards cannot be attacked with Melee, except when using [[Halberd]]s or [[Salamander]]s. This includes Magic-based [[special attacks]] from melee weapons, such as the [[Voidwaker]].
"""
