name = "Nylocas Vasilias"
source_pages = ["Nylocas Vasilias"]
npc_ids = [8354, 8355, 8356, 8357, 10807, 10808, 10809, 10810, 10786, 10787, 10788, 10789]

[sections]
"Mechanics" = """
Vasilias changes its combat style throughout the fight by changing its carapace, which also indicates its weakness: blue for magic, green for ranged and white for melee. Attacking it with the wrong combat style will cause it to reflect the hit back towards the player as well as healing from the hit. It will change every 10 [[tick]]s (6 seconds), and it will always change to one of the other two styles (meaning it will not stay on one style twice in a row).
"""
