name = "Revenant maledictus"
source_pages = ["Revenant maledictus"]
npc_ids = [11246]

[sections]
"=Attacks=" = """
Despite the caves being [[singles-plus combat]], the maledictus itself is functionally multi-combat; it can be attacked by any number of players, and will attack all players in range simultaneously. The maledictus will cycle through its three special attacks after every few standard attacks, telegraphing each attack with the Zarosian symbol on its back. Protection prayers will reduce damage taken by half. Its attacks are as follows:

* Standard attack: a white, spike-shaped ranged attack.
* Ice spell: When the symbol glows blue, it will target players' current tiles, then freeze anyone who doesn't move, dealing damage and preventing them from moving or attacking.
* Blood spell: When the symbol glows red, it will target players' current tiles, then deal damage and heal itself for half of the total damage dealt.
* Air surge: When the symbol glows white, it will launch a typeless area-of-effect at one player. The spell explodes outward from where it lands, and deals up to 25 damage to anyone in a 5x5 area, but less near the edges.
"""

"=Drop mechanics=" = """
Upon death, the revenant maledictus will reward players appropriately for their efforts:

*The top damaging player will obtain either an [[ancient totem]] or [[ancient emblem]] drop, along with two rolls on the [[revenant dragon]]'s drop table. They will additionally gain the Forinthry Surge buff, provided that they were wearing an [[amulet of avarice]] before it died.
**Ironmen are eligible for both Forinthry Surge and item drops, as long as they are the top damage dealer.
*All other players will get one [[blighted super restore]] and two pieces of blighted food drop under them regardless of their location as long as they dealt damage to the boss.

The drop table below has been copied from the revenant dragon and only represents one of two non-guaranteed loot rolls.

{{Revenants/Drops|combat=135|hitpoints=155}}
"""
