name = "Sarachnis"
source_pages = ["Sarachnis", "Sarachnis/Strategies"]
npc_ids = [8713]

[sections]
"Mechanics" = """
[[File:Fighting Sarachnis.png|thumb|right|A player fights Sarachnis, the mother of the temple spiders.]]
Sarachnis has several attacks that she will occasionally use other than the standard melee and ranged attacks. Her melee attacks consist of smashing the player with her legs, while she launches barbed projectiles as her ranged attack.

* '''Healing strike''' - Sarachnis' standard attacks will heal her on [[successful hit]]s, indicated by a [[File:Heal hitsplat.png]] magenta [[hitsplat]]. She heals 5 health for every successful melee attack, and 10 health for every successful ranged attack, regardless of how much damage she actually deals, including zeros.
* '''Sticky web''' - Every four standard attacks, Sarachnis will screech out {{overhead|Hsss!}} and shoot out a sticky web that leaves players bound for 6 [[ticks]] (3.6 seconds), then moving a short distance away from where she was before attacking the player. This attack can be completely negated by wearing [[aranea boots]], and the bind effect can be partially mitigated with a [[transformation ring]] (see [[#Strategy]]).
* '''Spawns''' - When Sarachnis reaches 66% and 33% health, she summons two [[Spawn of Sarachnis]] per player; a level 68 that uses Magic and has a maximum hit of 11, and a level 107 that uses Melee and has a maximum hit of 13. Both have 30 health.
"""
