name = "Scorpia"
source_pages = ["Scorpia", "Scorpia/Strategies"]
npc_ids = [6615]

[sections]
"Fight overview" = """
{{Main|Scorpia/Strategies}}The Scorpion Pit is filled with many [[Scorpia's offspring (monster)|Scorpia's offspring]], which use weak but accurate ranged attacks. Scorpia herself uses melee attacks which, whether successful or not, drain the player's prayer points by 2 if they have the [[Protect from Melee]] prayer active. Both Scorpia and her offspring are capable of inflicting [[poison]], starting at 20 and 6 damage, respectively.

Once Scorpia falls below 50% health, the next attack against her, whether successful or not, will cause her to summon two [[Scorpia's guardian]]s, which heal her rapidly.
"""
