name = "Spindel"
source_pages = ["Spindel", "Spindel/Strategies"]
npc_ids = [11998]

[sections]
"Attacks" = """
Spindel has many attacks that she uses against her target.

*Melee attack: She simply lunges at the player. This is the only normal attack she will use if the player is within melee distance.
*Ranged attack: Launches green spit at players.
*Magic attack: Launches webs at players.
*Sticky Web: Spindel will occasionally deploy a sticky web at a player, sending a white-blue web at the target's location. It will then expand into a 7x5 AoE - while in this web, any player caught in it will take rapid hits of 3 damage, have their prayer drained by 3, and run energy by 10.
**Note that [[aranea boots]] will only negate the first tick of damage taken from the web attack.
*Spiderlings: Spindel will occasionally call some [[Spindel's Spiderling|spiderlings]] to assist her in battle. While fairly weak, they will drain prayer on every hit regardless if prayed against or hits. They will also increase her damage and allow her to hit through prayers if left alive. Thrall damage is reduced while spiderlings are alive.
"""

"Overview" = """
[[File:Spindel.png|thumb|width=300x300|Spindel's in-game appearance.]]
Spindel can attack with all three forms of combat. While she will only use one combat style at a time, players in melee distance will instead only be attacked by melee. Like [[Calvar'ion]], she is weakest to crush.

She will begin the fight using 8 ranged attacks, followed by 8 magic attacks, all while moving position every 4 attacks. She will spawn spiderlings on the 1st ranged attack in cycle, and deploy her web attack on the 3rd mage attack in the cycle.  This pattern will repeat until Spindel is defeated.

Players who enter the arena will appear to the north, so always keep an eye out for PKers and teleport or run to the exit if needed.

Players should avoid the webs at all costs, as their ability to drain run energy will prevent them from escaping from player killers. The web can be positioned safely by standing on the outskirt of the arena on the 3rd magic attack to help prevent accidentally walking into the web.

The spiderlings should be killed as soon as they spawn to prevent them from empowering her too much; fortunately, they only have 5 health and can be killed in one hit by any combat style.

* Any tier of [[Chinchompa (weapon)|chinchompa]] can eliminate multiple spiderlings with a well-placed shot as well as damage Spindel's south-west tile, (Ensure PK Skull prevention is activated).
* [[Dart|Darts]] or [[throwing knives]] can quickly eliminate individual spiderlings.
* Players with 70+ [[Magic]] and [[Ancient Magicks]] can use a burst spell with [[Blighted ancient ice sack|blighted ancient ice sacks]] to eliminate multiple spiderlings at once.
"""
