name = "The Mimic"
source_pages = ["The Mimic", "The Mimic/Strategies"]
npc_ids = [8633]

[sections]
"Attacks" = """
The Mimic uses several attacks throughout the duration of the fight.

* '''Melee attack:''' The Mimic can hit you with a normal melee attack if you are standing beside it.
* '''Candy attack:''' The Mimic throws six candies at you. If you fail to step out of the way, you will receive about 10 damage. Three candies are purple, and there is one red, one blue and one green candy. The red, blue and green candies spawn the [[Third Age Warrior]], [[Third Age Mage]], and [[Third Age Ranger]] respectively. There is no benefit to killing them as they drop nothing and, when killed, they instantly respawn when another candy attack occurs.
* '''Stomp Attack:''' Sometimes, The Mimic will step one tile forward onto you. Alternatively, this attack is activated when you walk under The Mimic. For every [[tick]] (0.6 seconds) that you stand under The Mimic, you will receive damage. The damage scales as follows: 1-1-1-2-2-2-3-... and so on, capping out at 6 damage. Simply step away from The Mimic to stop and reset the damage counter.
"""

"Fight overview" = """
{{main|The Mimic/Strategies}}
With the right strategy, The Mimic is very easy to defeat for any high-level player. However, at combat stats around 70, The Mimic can pose a real challenge.

Always use [[Protect from Melee]], move around the room when the Mimic throws sweets, and ignore the spawned Third Age minions. Use stat-boosting potions and prayers as well.

* The quickest way to slay The Mimic is to bring [[dragon claws]] or a [[dragon dagger]] with full [[strength bonus|melee gear]], then after using the two/four special attacks, switch into a full magic setup with a [[powered staff]]. With high melee stats and [[Piety]], you can switch to a [[abyssal whip|whip]] or better and kill the boss before minions even spawn.
* Alternatively, using magic, The Mimic can be frozen using [[ice spells]] or [[Entangle]] evading the melee attack completely. [[Powered staves]] can then be used to quickly kill The Mimic.
* Although The Mimic is weak to [[Magic]], players can also opt to use [[Ranged]] with a [[toxic blowpipe]].

[[File:Fighting The Mimic.png|thumb|left|260px|A player faces The Mimic.]]
The Mimic has three different attacks:

* '''Melee attack:''' The Mimic can hit you with a normal melee attack if you are standing beside it.

* '''Candy Attack:''' The Mimic throws six candies at you. If you fail to step out of the way, you will receive about 10 damage. Three candies are purple, and there is one red, one blue, and one green candy. The red, blue, and green candies spawn the [[Third Age Warrior]], [[Third Age Mage]], and [[Third Age Ranger]] respectively. There is no benefit to killing them as they drop nothing and, when killed, they instantly respawn when another candy attack occurs.

* '''Stomp Attack:''' Sometimes, The Mimic will step one tile forward onto you. Alternatively, this attack is activated when you walk under The Mimic. For every tick (0.6 seconds) that you stand under The Mimic, you will receive damage. The damage scales as follows: 1-1-1-2-2-2-3-... and so on, capping out at 6 damage. Simply step away from The Mimic to stop and reset the damage counter.
{{clear|left}}
"""
