name = "Thermonuclear smoke devil"
source_pages = ["Thermonuclear smoke devil", "Thermonuclear smoke devil/Strategies"]
npc_ids = [499]

[sections]
"=Attack styles=" = """
The thermonuclear smoke devil only attacks with a [[typeless]] [[magical ranged]] attack:
*'Typeless' means that [[protection prayers]] will not have any effect.
*'Magical ranged' means that the attack accuracy is decided by the ranged attack bonuses of the thermonuclear smoke devil and the magic defence bonuses of the player.
*The max hit of this attack is 8.
*The attack is very accurate and has an attack speed of 2 [[tick]]s (1.2 seconds).
*The attack range is eight tiles.
"""
