name = "Torag the Corrupted"
source_pages = ["Torag the Corrupted"]
npc_ids = [1676]

[sections]
"Prayer info" = """
{{Prayer info
|name = Torag the Corrupted
|level = 40
|xp = 20
|type = spectral
}}
"""
