name = "Tree spirit (Lost City)"
source_pages = ["Tree spirit (Lost City)"]
npc_ids = [1163]

[sections]
"Prayer info" = """
{{Prayer info
|name = Tree spirit
|level = 40
|xp = 17
|type = spectral
}}
"""
