name = "TzTok-Jad"
source_pages = ["TzTok-Jad"]
npc_ids = [3127]

[sections]
"Fighting TzTok-Jad" = """
{{Main|TzHaar Fight Cave/Strategies#TzTok-Jad}}
[[File:Fighting TzTok-Jad.png|thumb|left|A player fighting TzTok-Jad.]]
TzTok-Jad is the boss monster of the TzHaar Fight Cave, and is encountered on Wave 63 (the final wave). This is the only place where Jad can be found.

Once TzTok-Jad is reached, fighting and defeating him requires decent skill and reflexes. It is possible to engage TzTok-Jad using [[Melee]], but as TzTok-Jad's melee attack has no warning animation, players must have Protect from Melee active when in melee distance, and switch to Protect from Missiles or Protect from Magic once the respective warning animation is identified. When at a distance, TzTok-Jad only uses Ranged and Magic attacks, which can hit the player from up to 15 tiles away. While Jad has no defence bonuses, it is recommended to kill Jad with ranged, as it avoids the melee attack completely, only leaving the magic and ranged attacks for Jad.

As with all other off-colored monsters in the Fight Caves, locating where the orange [[Ket-Zek]] spawned will indicate Jad's spawn point. Like the [[Tok-Xil]], Jad has a very long attack range, and players not using drawn out clients can find themselves being attacked by Jad without seeing the combat style he uses and where he comes from.

Like Ket-Zek, Jad's attacks can deal extremely high damage, and is even capable of killing lower-leveled players in one hit if not protected against. Jad's melee and ranged attacks have a max hit of 97, while the magic attack has a max hit of 95.
[[File:TzTok-Jad Animations.mp4|thumb|350px|TzTok-Jad's Ranged and Magic attacks.|autoplay|loop]]

*'''Melee:''' TzTok-Jad thrusts forward with a sharp bite. He only does this if the player is within melee distance. Unlike the Magic and Ranged attacks, the Melee attack is instant.
*'''Magic:''' TzTok-Jad rears up on his hind legs and dangles his forward legs for a few seconds before launching a fireball from his mouth at the player.
*'''Ranged:''' TzTok-Jad rears up on his hind legs, then slams down his front legs onto the ground causing a boulder to fall on the player (it is not possible to evade this boulder by running).

Once TzTok-Jad is reduced to below 150 health, he will summon four [[Yt-HurKot]]s to come and heal him repeatedly — the player must deal with them whilst warding off TzTok-Jad's attacks. <u>If they manage to heal him to full health</u>, then they <u>should not be killed</u> as the healers that have died will respawn once he is reduced to half health again. If they are distracted before healing him to full health, they '''will not respawn''' when killed.

:'''Note:''' If you take the attention of the Yt-HurKots and they are hitting you, they '''WILL''' still heal Jad if they are close enough to him.

You can practice fighting Jad by logging into a speed running world and set up a speed run for [[Beneath Cursed Sands]]. Because you have a fire cape there, you can do the first one of [[TzHaar-Ket-Rak's Challenges]] and fight [[JalTok-Jad]], which is a stronger variant of Jad. Here, the healers have higher stats, but their mechanics are more forgiving - needing to be untagged and directly next to Jad in order to heal.
"""
