name = "Vespula"
source_pages = ["Vespula"]
npc_ids = [7530, 7531, 7532]

[sections]
"Mechanics" = """
Vespula will spawn alongside four [[lux grub]]s and an [[abyssal portal]] when the encounter begins. Vespula is not aggressive towards players when they enter the chamber, but will retaliate back when attacked with rapid ranged attacks, which can inflict [[poison]] starting at 20 damage, the highest possible amount while also stinging grubs at the same time.

As Vespula stings the lux grubs, their health will deplete. If their health is allowed to fully deplete, they will transform into [[vespine soldier]]s, who also attack with melee and inflict poison starting at 15 damage. These soldiers will additionally heal her and the abyssal portal while alive, so it is important not to let them appear. The grubs' health can be restored by feeding them [[Medivaemia blossom]]s.

Upon reaching 20% of her health, Vespula will land on the ground for ~20 seconds. At this point, the abyssal portal can be safely attacked, and destroying it will end the encounter. If the portal is attacked while Vespula is flying, she will enter an enraged state, rapidly flying back and forth in the area in front of the portal, stinging anyone in melee range for 5-20 typeless damage. Anyone standing underneath her is instead stomped for 2-8 damage every tick. She will remain in this state until the portal is no longer attacked, after which she resumes normal behaviour.
"""
