name = "Vorkath"
source_pages = ["Vorkath", "Vorkath/Strategies"]
npc_ids = [8058, 8060, 8059, 8061]

[sections]
"=Advanced dragonfire=" = """
Vorkath's advanced dragonfire attacks that are not all affected by dragonfire protection.

{| class="wikitable"
! Image !! Name !! Notes
|-
| |[[File:Vorkath dragonfire attack.png|150px]]|| Standard Dragonfire|| Deals [[dragonfire]] damage dependent on the number of layers of dragonfire protection used by the player. Full damage mitigation requires a [[super antifire potion]] along with a dragonfire protection shield. Players also typically use a regular antifire potion with a shield that protects against dragonfire, or a super antifire potion along with the protect from magic prayer; both combinations reduce the max hits of dragonfire to 10.
|-
| |[[File:Vorkath venom dragonfire attack.png|150px]]|| Venomous Dragonfire || Inflicts [[venom]] if not immune. Dragonfire protection does negate damage inflicted by this attack, but does not protect against the infliction of venom.
|-
| |[[File:Vorkath prayer disabling attack.png|150px]]|| Corrupting Dragonfire || Deactivates all [[prayers]] upon impact. Players should have quick-prayers accordingly set to reactivate their prayers immediately afterward. Dragonfire protection does negate damage inflicted by this attack, but does not protect against the prayer disabling effect.
|-
| |[[File:Vorkath deadly dragonfire attack.png|150px]]|| Deadly Dragonfire || Vertically launched at the player's position when fired. This will often outright kill the player if hit; if adjacent to the strike zone, it will deal half the damage it would have dealt. Thus, players should always be prepared to click two tiles away from where they are at all times. This attack cannot be defended against with any type of dragonfire protection.
|}
"""

"=Standard Dragonfire=" = """
{{:Dragonfire/Vorkath}}
"""

"=Standard attacks=" = """
Vorkath uses the following standard attacks:
[[File:Vorkath - deadly dragonfire.mp4|thumb|400px|Vorkath's deadly dragonfire attack directly striking a player.]]
{| class="wikitable"
! Image !! Name !! Notes
|-
| |[[File:Vorkath.png|150px]] || Melee Attack || Deals [[melee]] damage up to 32.
|-
| |[[File:Vorkath magic attack.png|150px]] || Magic Attack || Deals [[magic]] damage up to 30. Used more frequently if in melee distance.
|-
| |[[File:Vorkath ranged attack.png|150px]]|| Ranged Attack|| Deals [[ranged]] damage up to 32. Used more frequently if out of melee distance.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/966003811084111872?s=19|date=20 February 2018|archiveurl=https://reldo.runescape.wiki/i/103777|archivedate=29 May 2020|quote=Relative weightings of 3 for magic, 4 for ranged.}}
|}

* Vorkath's standard attacks are '''unreactable''', and therefore the player should constantly pray against the attack style they are weakest to

*[[Dragonfire]]: Aside from standard dragonfire, Vorkath has multiple variants that it can use, similar to the [[King Black Dragon]]
"""

"Fight overview" = """
[[Vorkath]] is similar to most dragons in that it is weak against stab melee and ranged. Upon awakening, Vorkath's attack pattern consists of six random standard attacks, one special attack, another six standard attacks, then the other special attack, and so on until defeated. During the fight, it is recommended to always maintain at least a [[super antifire potion]] and [[Protect from Magic]], or a regular [[antifire potion]] and a dragonfire protection shield.

Whether to have run on during the fight is a matter of preference. Keeping run on, except for during the acid special attack, increases the margin for error when dodging the fireball attack, but requires the player to manually toggle run when the acid attack occurs. Leaving run off eliminates the need to toggle and players can rely on quick reactions to dodge the fireball while walking, and use Ctrl-click to override the run setting if needed.

The optimal [[protection prayer]]s to use will depend on the gear being used:
*[[Protect from Magic]] if using [[melee]], a [[toxic blowpipe]], or if holding a [[book of law]] (along with a super antifire potion)
*[[Protect from Missiles]] if using a crossbow with a [[dragonfire ward]], [[dragonfire shield]] or [[anti-dragon shield]]

Vorkath is capable of [[Venom|envenoming]] players with its venom dragonfire; as such, bring appropriate venom protection. The prayer dragonfire turns all active prayers off, including [[Preserve]]; for this reason, divine potions are recommended over normal potions. Additionally, recoil damage such as [[Vengeance]] and [[Ring of recoil|rings of recoil]] do not work on Vorkath.
"""
