name = "Zebak"
source_pages = ["Zebak"]
npc_ids = [11730, 11732]

[sections]
"Mechanics" = """
{{Main|Tombs of Amascut/Strategies#Zebak, Guardian of Crondis}}
[[File:Tombs of Amascut - Fighting Zebak.png|thumb|left|280px|A player fighting Zebak, the Guardian of Crondis.]]
Zebak's base defence level can be lowered by a maximum of 20 damage, reducing his base defence level down to a minimum of 50.

Zebak attacks with all three attack styles, with his melee attack having a chance to inflict bleeding, which deals additional damage over time that is increased further with movement. His melee attack can be avoided simply by standing away from melee range. Zebak's standard attacks will be indicated by visual and audio cues: His magic attack spits a pot into the air that splits into red orbs, whereas his ranged attack spits a large rock into the air that splinters into smaller rocks.

At 85%, 70%, 55% and 40% health, Zebak will queue one of two special attacks and alternate between them.

* '''Great Roar''' - Zebak launches more acid into the arena, this time with three stones. The players will then have some time (four of Zebak's attacks) to move pots of water towards the stones, to then break to cleanse the area behind the stones of poison before Zebak lets out a mighty roar. Each jug of water will clear a 5x5 area of poison (3x3 with '''Upset Stomach''' enabled). If the player is not within 3 tiles behind the stones that Zebak previously spat out, this roar knocks the player back and deals massive amounts of damage.

* '''Tidal Waves''' - Zebak launches waves that slowly move from one side of the arena to the other. The player will have to navigate Zebak's arena and avoid getting hit by the waves by going between the gaps in the waves. If the player is hit by one of Zebak's waves, the player will take 6 - 10 damage, (scales with invocation), and be pushed in the direction that the wave is going. If the wave pushes the player over into the water, they will need to quickly scale back up a nearby ramp; they cannot attack in this state, and Zebak will continue attacking alongside other crocodiles lurking in the water.
{{clear|left}}

Upon reaching ~25% of his health, Zebak will become enraged, significantly increasing his attack speed.

Should players have the '''Path Level''' invocations active, every two levels will cause the following:

* Zebak's auto-attacks will be faster. This speed only affects the projectile launch, not when it shatters into the team below.
* The Tidal Waves open gap is tightened by one tile.
"""
