quest = "Scorpion Catcher"
step_count = 4

[[steps]]
index = 0
name = "Scattered scorpions"
links = ["Thormac", "Sorcerer's Tower", "Ranging Guild", "Seers' Village", "Kharid Scorpion", "Scorpion cage", "Taverley Dungeon"]
text = """
{{Map|name=Sorcerer's Tower|x=2702|y=3405|zoom=2|align=right|caption=The location of the Sorcerer's Tower.|width=200|height=200}}
[[File:Thormac chathead.png|left|frameless|80px]]
Talk to [[Thormac]] on the top floor of the [[Sorcerer's Tower]], just south-east of the [[Ranging Guild]] and south of [[Seers' Village]]. He'll tell you that his rare [[Kharid Scorpion]]s have escaped and are currently running loose. He'll give you a [[Scorpion cage]] to catch the scorpions with and suggest you go talk to the Seers that live just to the north.

Speak with any Seer in Seers' Village. He will tell you that the first scorpion is in a secret room with nasty spiders nearby. This is the [[Taverley Dungeon]].

:'''Note''': The secret room is '''only''' accessible once you have spoken to the seer about the location of the first scorpion. Once that is done, you can now catch the three scorpions in any order and may skip talking to the Seer again to find their locations.
{{Clear|left}}
"""

[[steps]]
index = 1
name = "The first scorpion"
links = ["Taverley Dungeon", "anti-dragon shield", "blue dragon", "antifire potion", "Dragon Slayer I", "Agility", "shortcut", "poison spider", "dusty key", "Black Knights' Base", "jailer", "jail key", "Velrak the explorer", "black demon", "scorpion cage", "Hitpoints", "baby blue dragon", "hardcore ironman"]
text = """
[[File:Kharid Scorpion.png|left|frameless|80px]]
{{Map|2877,9796|name=Kharid Scorpion|width=250|height=250|r=3|mtype=square|mapID=20|caption=The location of the first scorpion, in the [[Taverley Dungeon]].|align=right}}
'''Note''': In the following section, low levelled players are '''highly recommended''' to use an [[anti-dragon shield]] when passing the [[blue dragon]]s, as their dragonfire can inflict up to 50 damage, which the shield reduces by roughly 80%. If used in combination with an [[antifire potion]], the player will gain full immunity. If you have not started [[Dragon Slayer I]] to obtain the shield, read the following sections for a more difficult strategy to avoid the dragonfire. The blue dragons may also be skipped if you have 80 [[Agility]].

Make your way to the [[Taverley Dungeon]]. Once inside, you can skip the following steps if you have 70+ [[Agility]], by either using the [[shortcut]] to the [[blue dragon]]s (70 Agility) or the [[shortcut]] directly to the [[poison spider]]s (80 Agility).

If you cannot use the shortcuts, a [[dusty key]] is required to enter the section of the dungeon that the scorpion is located in. If you do not already have one, follow the track towards the [[Black Knights' Base]] and kill the [[jailer]] located in the eastern area of the base, who will drop a [[jail key]]. Use the jail key on the door of the cell containing [[Velrak the explorer]]. Speak to him; ask if there are any good places to explore, and when he asks you if you want to go further into the dungeon, say yes and he will give you a dusty key. Head to the blue dragons area.

Walk south of the blue dragons, west to pass the [[black demon]]s, and north to the [[poison spider]]s. To the south of the two coffins, there's a small room with a false wall that you can search to open (see the map). If you are unable to open the door, you probably did not speak with the seer about the first scorpion.

Use the [[scorpion cage]] on the small scorpion inside this room to catch it ''(if you try to pick it up, it will sting you for 3 [[Hitpoints]] of damage)''.

'''Strategy without [[anti-dragon shield]]:''' When running past the blue dragons, ensure a [[baby blue dragon]] is fighting you at all times (they do not breathe dragonfire). The dungeon is single-combat, so the more dangerous blue dragons will not attack you while you are in combat. Avoid standing too close to adult dragons, and hop from baby to baby and draw their aggression when passing through. This strategy is not recommended for [[hardcore ironman|hardcore ironmen]] who are not confident they know what they are doing.

{{Map|3058,3488|name=Kharid Scorpion|plane=1|caption=The location of the second scorpion.|width=200|height=200|r=3|mtype=square|align=left}}
"""

[[steps]]
index = 2
name = "The second scorpion"
links = ["Edgeville Monastery", "Abbot Langley"]
text = """
{{Needed|skills={{SCP|Prayer|31}} {{Boostable|no}} to enter the {{FloorNumber|uk=1}} of the [[Edgeville Monastery]]}}
The second scorpion is on the {{FloorNumber|uk=1}} of the [[Edgeville Monastery]]. To enter the {{FloorNumber|uk=1}} you'll need to speak with [[Abbot Langley]] to join their guild ({{SCP|Prayer|31}}). You do not have to do this again if you have already done it.

Climb the south-east ladder in the Monastery. The scorpion will be either right at the top of the ladder, or in the bedroom directly north of the ladder. Use your cage on it to catch it.
"""

[[steps]]
index = 3
name = "The third scorpion"
links = ["Barbarian Outpost Agility Course", "Alfred Grimhand's Barcrawl", "scorpion cage", "Thormac"]
text = """
{{Map|2553,3570|name=Kharid Scorpion|caption=The location of the third scorpion.|width=200|height=200|r=3|mtype=square|align=right}}

The third scorpion is in the [[Barbarian Outpost Agility Course]] (requires completion of [[Alfred Grimhand's Barcrawl]]), found in the north eastern gated building. The scorpion will be wandering just inside the entrance. Use your cage on it to catch it.

Finally, bring the full [[scorpion cage]] to [[Thormac]].

'''Congratulations, quest complete!'''
{{Clear}}
"""
