#!/usr/bin/env python3
"""Export item-use/effect rows from RuneLite itemstats + curated specials."""
from __future__ import annotations

import argparse
import json
import re
import tomllib
from pathlib import Path

from source_paths import RUNELITE

ITEM_IDS = RUNELITE / "runelite-api/src/main/java/net/runelite/api/gameval/ItemID.java"
ITEMSTATS = (
    RUNELITE
    / "runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java"
)
SPECIALS = Path("data/curated/specials")


def load_item_ids(path: Path) -> dict[str, int]:
    text = path.read_text()
    text = text.split("\n\tpublic static final class ", 1)[0]
    return {m.group(1): int(m.group(2)) for m in re.finditer(
        r"public static final int ([A-Z0-9_]+) = (\d+);", text)}


def strip_comments(s: str) -> str:
    return re.sub(r"/\*.*?\*/", "", s, flags=re.S)


def split_args(s: str) -> list[str]:
    out: list[str] = []
    depth = 0
    start = 0
    for i, ch in enumerate(s):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            out.append(s[start:i].strip())
            start = i + 1
    out.append(s[start:].strip())
    return out


def add_calls(text: str) -> list[str]:
    calls: list[str] = []
    i = 0
    while True:
        start = text.find("add(", i)
        if start == -1:
            break
        pos = start + 4
        depth = 1
        while pos < len(text) and depth:
            ch = text[pos]
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            pos += 1
        calls.append(text[start + 4:pos - 1])
        i = pos
    return calls


def quote(s: str) -> str:
    return json.dumps(s, ensure_ascii=True)


def write_toml(path: Path, rows: list[dict]):
    lines = [
        "# Generated by tools/export_item_effects.py.",
        "# Runtime will compile/load these when item-use behavior lands.",
        "",
    ]
    for row in rows:
        lines.append("[[effect]]")
        for key in ("source", "kind", "effect", "path"):
            if row.get(key) is not None:
                lines.append(f"{key} = {quote(str(row[key]))}")
        lines.append("item_ids = " + json.dumps(row["item_ids"]))
        if row.get("unresolved"):
            lines.append("unresolved = " + json.dumps(row["unresolved"]))
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def rune_lite_rows(item_ids: dict[str, int]) -> tuple[list[dict], set[str]]:
    rows: list[dict] = []
    unresolved: set[str] = set()
    text = strip_comments(ITEMSTATS.read_text())
    for body in add_calls(text):
        args = split_args(body)
        if len(args) < 2:
            continue
        symbols = re.findall(r"ItemID\.([A-Z0-9_]+)", ",".join(args[1:]))
        ids: list[int] = []
        missing: list[str] = []
        for sym in symbols:
            iid = item_ids.get(sym)
            if iid is None:
                missing.append(sym)
                unresolved.add(sym)
            elif iid not in ids:
                ids.append(iid)
        if ids or missing:
            rows.append({
                "source": "runelite_itemstats",
                "kind": "stat_change",
                "effect": " ".join(args[0].split()),
                "item_ids": ids,
                "unresolved": missing,
            })
    return rows, unresolved


def special_rows() -> tuple[list[dict], list[str]]:
    rows: list[dict] = []
    unresolved: list[str] = []
    for path in sorted(SPECIALS.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        ids = [int(i) for i in data.get("item_ids", []) if isinstance(i, int)]
        if not ids:
            unresolved.append(str(path))
        rows.append({
            "source": "curated_specials",
            "kind": "special_attack",
            "effect": data.get("name") or path.stem,
            "path": str(path),
            "item_ids": ids,
            "unresolved": [] if ids else [data.get("name") or path.stem],
        })
    return rows, unresolved


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--output", type=Path, default=Path("data/curated/items/effects.toml"))
    p.add_argument("--report", type=Path, default=Path("tools/reports/item_effects.txt"))
    args = p.parse_args()

    ids = load_item_ids(ITEM_IDS)
    rl_rows, rl_unresolved = rune_lite_rows(ids)
    sp_rows, sp_unresolved = special_rows()
    rows = rl_rows + sp_rows
    write_toml(args.output, rows)

    total_ids = sum(len(r["item_ids"]) for r in rows)
    lines = [
        "Item effects export",
        "",
        f"runelite item ids loaded: {len(ids)}",
        f"runelite itemstats rows: {len(rl_rows)}",
        f"runelite unresolved symbols: {len(rl_unresolved)}",
        f"curated special rows: {len(sp_rows)}",
        f"curated specials missing item_ids: {len(sp_unresolved)}",
        f"total effect rows: {len(rows)}",
        f"total item id references: {total_ids}",
        "",
    ]
    if rl_unresolved:
        lines.append("--- unresolved RuneLite symbols ---")
        lines.extend(f"  {s}" for s in sorted(rl_unresolved)[:200])
    if sp_unresolved:
        lines.append("--- curated specials missing item_ids ---")
        lines.extend(f"  {s}" for s in sp_unresolved)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {args.output} ({len(rows)} rows)")
    print(f"wrote {args.report}")


if __name__ == "__main__":
    main()
