#!/usr/bin/env python3
"""Generate the reviewed B237 storage policy used by native content registration."""
from pathlib import Path
import argparse
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent / "cache_pipeline"))
from rc_cache import (RcCacheStore, decode_item_definition,
                      decode_location_definition, decode_npc_definition)

ROOT = Path(__file__).resolve().parents[1]
DEPOSIT_NAMES = {"bank deposit box", "bank deposit chest", "bank deposit pot"}
USE_NAMES = {"bank chest", "bank booth"}


def object_masks(definition):
    bank = deposit = 0
    for slot, action in enumerate(definition.actions):
        if action == "Bank" or (action == "Use" and definition.name.lower() in USE_NAMES):
            bank |= 1 << slot
        if action == "Deposit-box" or (action == "Deposit" and definition.name.lower() in DEPOSIT_NAMES):
            deposit |= 1 << slot
    return bank, deposit


def ranges(values):
    result = []
    for value in sorted(values):
        if result and result[-1][1] + 1 == value:
            result[-1][1] = value
        else:
            result.append([value, value])
    return result


def generate(cache):
    store = RcCacheStore(cache)
    # B237: int, default 0, auto-disable false. rsmod BaseParams.no_bank
    # identity hash 88687214541 resolves to 59 with these exact attributes.
    if store.read_group(2, 11)[59] != bytes.fromhex("0401690800020000000000"):
        raise ValueError("B237 no_bank parameter signature changed; review before exporting")
    items = {i: decode_item_definition(i, raw) for i, raw in store.read_group(2, 10).items()}
    denied = []
    for i, item in items.items():
        if not item.complete:
            raise ValueError(f"item {i}: incomplete decode")
        for param in item.params:
            if param.key == 59:
                if param.is_string or param.int_value not in (0, 1):
                    raise ValueError(f"item {i}: unsupported bankability value")
                if param.int_value:
                    denied.append(i)
    lines = ["// Generated by tools/export_storage_policy.py from RuneC's B237 cache.",
             f"#define STORAGE_REVIEWED_ITEM_MAX {max(items)}"]
    for name, values in (("unbankable", denied),
                         ("unknown_items", set(range(max(items) + 1)) - items.keys())):
        lines.append(f"static const int {name}[][2] = {{")
        lines += [f"    {{{lo}, {hi}}}," for lo, hi in ranges(values)]
        lines.append("};")
    lines.append("static const RcStorageBinding object_storage[] = {")
    for i, raw in sorted(store.read_group(2, 6).items()):
        loc = decode_location_definition(i, raw)
        bank, deposit = object_masks(loc)
        if bank or deposit:
            if not loc.complete:
                raise ValueError(f"object {i}: incomplete decode")
            lines.append(f"    {{{i}, {bank}, {deposit}}},")
    lines.append("};")
    lines.append("static const RcStorageBinding npc_storage[] = {")
    for i, raw in sorted(store.read_group(2, 9).items()):
        npc = decode_npc_definition(i, raw)
        bank = sum(1 << slot for slot, action in enumerate(npc.actions) if action == "Bank")
        if bank:
            if not npc.complete:
                raise ValueError(f"NPC {i}: incomplete decode")
            lines.append(f"    {{{i}, {bank}, 0}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=ROOT / "rc-content/storage_policy.inc")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = generate(args.cache)
    if args.check:
        if args.output.read_text() != output:
            raise SystemExit("storage policy differs from reviewed B237 inputs")
    else:
        args.output.write_text(output)
    print(f"Storage policy {'verified' if args.check else 'generated'}: {args.output}")


if __name__ == "__main__":
    main()
