name = "Abyssal bludgeon"
item_ids = [13263]

[special]
"Special attack" = """
[[File:Penance.gif|frame|A player performs the abyssal bludgeon's special attack, ''Penance''.]]
The abyssal bludgeon has a [[special attacks|special attack]], ''Penance'', which increases damage dealt by 0.5% for every [[prayer point]] that the wielder is missing, consuming 50% of the wielder's special attack energy.
"""
