name = "Abyssal tentacle"
item_ids = [12006]

[special]
"Special attack" = """
[[File:Binding Tentacle.gif|thumb|right|220px|A player performs the abyssal tentacle's special attack, ''Binding Tentacle''.]]
The abyssal tentacle has a [[special attacks|special attack]], ''Binding Tentacle'', which consumes 50% of the player's special attack energy. Regardless of whether the hit is [[successful hit|successful]], the target will be bound for 5 seconds, and there will be approximately a 50% chance of applying poison, starting at 4 damage.
"""
