name = "Abyssal dagger"
item_ids = [13265]

[special]
"Special attack" = """
[[File:Abyssal Puncture.gif|frame|A player performs the abyssal dagger's special attack, ''Abyssal Puncture''.]]
The abyssal dagger has a [[special attack]], ''Abyssal Puncture'', which hits twice in quick succession with a 25% increase in accuracy and 15% reduced damage, consuming 25% of the player's special attack energy. A single attack roll is performed, meaning that either both hits are successful, or both hits miss. The damage calculation rolls against the opponent's slash defence.

The highest the dagger can possibly hit with its special attack is 44-44 against players and 50-50 while using a [[salve amulet (e)]] against [[undead]] creatures. The abyssal dagger's special attack is notably weaker than the [[Dragon dagger|dragon dagger's]]; this is evident when comparing the abyssal dagger's max hit of 44-44, to the dragon dagger's max hit of 50-50. However, it is more accurate against higher defence monsters due to its higher attack bonuses. This makes it a more accurate option at the cost of max hits.
"""
