name = "Abyssal whip"
item_ids = [4151, 4178, 20405]

[special]
"Special attack" = """
[[File:Energy Drain.gif|frame|A player performing the abyssal whip's special attack, ''Energy drain''.]]
The abyssal whip has a [[special attack]], ''Energy Drain'', which consumes 50% of the player's special attack energy, increases accuracy by 25%, and in [[Player killing|PvP]], transfers 10% of the target's run energy to the wielder. The target player will receive the message, "You feel drained!" in their chat window. The accuracy roll for ''Energy Drain'' is made against an opponent's slash defence.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/904101556034920449|date=2 September 2017|archiveurl=https://reldo.runescape.wiki/i/103702|archivedate=24 December 2022|quote=[Are whip & dscim spec tooltips correct? Supposedly more accurate, but my experience has been exactly the opposite. (...)] Both have a 25% accuracy buff, rolling against your opponent's effective slash defence.}}
"""
