name = "Accursed sceptre"
item_ids = [27665]

[special]
"Special attack" = """
[[File:Condemn.gif|thumb|250px|A player performing the Accursed sceptre's special attack, ''Condemn''.]]
The accursed sceptre has a [[special attack]], ''Condemn'', which consumes 50% of the player's special attack energy and 1 [[revenant ether]] (whether it hits or not). The special attack hits an enemy with a 50% increase to max hit and accuracy, and upon a [[successful hit]], also drains the target's Defence and Magic by 15%, regardless of the damage inflicted.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1630218328240209920|date=27 February 2023|archiveurl=https://reldo.runescape.wiki/i/97025|archivedate=29 March 2023|quote=Looks to me like it's unaffected by what damage you did. It's saying "up to 15%" because if the target's stat was already de-buffed, it'll take them down to a total de-buff of 15%, rather than stacking with the existing de-buff for a bigger total effect.}}

If the target's levels have already been reduced, ''Condemn'' will only drain them to a maximum of 15%. As a result, multiple special attacks do not stack. For example, a target with level 80 Defence and Magic cannot have their stats drained lower than 68 if using Condemn.
"""
