name = "Ancient godsword"
item_ids = [26233, 27184]

[special]
"Special attack" = """
[[File:Blood Sacrifice.gif|thumb|249px|A player uses ''Blood Sacrifice'', the ancient godsword's special attack.]]
Like all godswords, the ancient godsword has a [[special attacks|special attack]]: ''Blood Sacrifice''. In addition to doubled accuracy, it inflicts damage with a 10% higher maximum hit than a normal attack, consuming 50% of the player's special attack energy.

Upon a [[successful hit]], the target will be marked for sacrifice and will have eight ticks (4.8 seconds) to move at least five tiles away from the attacker. If the target fails to do so, they will take 25 [[typeless]] magic damage, and the attacker will be healed for 15% of the target's max Hitpoints level, up to a cap of 25 against NPCs and 15 against players. The sacrifice must deal the full 25 damage in order to receive the full healing effect, otherwise the attacker will only be healed for the damage done by the sacrifice up to the max of 15%. Since sacrifice damage is typeless, praying [[Protect from Magic]] '''will not''' reduce its damage.

The magic damage will always hit 0 on [[Cyclops|cyclopes]] in the [[Warriors' Guild]], as with all non-melee damage there.

It is possible to stack the special attack on the same target, dealing 25 damage before the effect of the second special attack activates, resulting in a total damage of 50.
"""
