name = "Armadyl crossbow"
item_ids = [11785, 23611]

[special]
"Special attack" = """
[[File:Armadyl Eye.gif|thumb|250px|A player performing the Armadyl crossbow's special attack, ''Armadyl Eye''.]]
[[File:Armadyl crossbow special attack projectile.gif|left|The projectile from the special attack.]]
The Armadyl crossbow has a [[special attack]], ''Armadyl Eye'', which consumes 50% of the player's special attack energy. Armadyl Eye will, for one shot, double the player's overall accuracy (level + gear accuracy), as well as doubling the base chance of an [[enchanted bolt]]'s special effect to occur.

For example, when performing the special attack with [[diamond bolts (e)|enchanted diamond bolts]], the bolt's special effect, ''Armour Piercing'', would have a 20% chance of activating instead of 10%. If the [[Hard Kandarin Diary]] has been completed, the additional chance given from the diary reward is added after doubling,{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1480491964260925444|date=10 January 2022|archiveurl=https://reldo.runescape.wiki/i/105529|archivedate=11 January 2022|quote=The diary reward adds an extra 10% of the base chance.}} meaning the chance of activating for that shot is increased from 10% to a total of 21%.

{{Listen
|title = Armadyl Eye attack
|align = right
|filename = Armadyl Eye sound.ogg
|desc = The sound which can be heard when players use the crossbow's special attack. (Warning: Extremely loud)
}}
"""
