name = "Armadyl godsword (Last Man Standing)"
item_ids = [20593]

[special]
"Special attack" = """
[[File:The Judgement.gif|frame|A player uses ''The Judgement'', the Armadyl godsword's special attack]]
The Armadyl godsword has a [[special attack]], ''The Judgement''. In addition to doubled accuracy, it inflicts damage with a 37.5% (125% multiplied by the hidden 110% every godsword special possesses, the calculation uses integer values after the multiplication of 1.1 the value gets rounded down and then multiplied by 1.25) higher maximum hit than a normal attack, consuming 50% of the player's special attack energy.

''The Judgement'' is capable of dealing a very large amount of damage; under ideal conditions, a player can potentially deal over 70 damage in a single blow. In PvP scenarios the Armadyl godsword is most commonly used as a "knock-out" weapon, as the special is often capable of finishing an injured player in one large blow.
"""
