name = "Armadyl crossbow (Last Man Standing)"
item_ids = [23611]

[special]
"Special attack" = """
The Armadyl crossbow has a [[special attack]], ''Armadyl Eye'', which consumes 50% of the player's special attack energy. Armadyl Eye will, for one shot, doubles the player's overall accuracy (level + gear accuracy), as well as the chance of an [[enchanted bolt]]'s special effect to occur.

For example, when performing the special attack with [[diamond bolts (e)|enchanted diamond bolts]], the bolt's special effect, ''Armour Piercing'', would have a 20% chance of activating instead of 10%. If the [[Hard Kandarin Diary]] has been completed, the chance of activating for that shot is increased from 11% to 21%.
"""
