name = "Bandos godsword"
item_ids = [11804, 20782, 21060]

[special]
"Special attack" = """
[[File:Warstrike.gif|thumb|260px|A player uses ''Warstrike'', the Bandos godsword's special attack.]]
The Bandos godsword's [[special attacks|special attack]], ''Warstrike'', has doubled accuracy, inflicts 21% more damage and drains the opponent's combat levels equivalent to the damage hit in the following order: [[Defence]], [[Strength]], [[Prayer]], [[Attack]], [[Magic]], [[Ranged]]. ''Warstrike'' consumes 50% of the wielder's special attack energy. ''Warstrike'' rolls against the opponent's slash defence roll.

In order for the godsword to drain stats from another category, the current stat that is being drained must hit 0. For example, if a target has 20 Defence, 50 Attack and 20 Prayer and the special attack hits an 80, the target would lose 20 Defence levels, 20 prayer points and 40 Attack levels.<!--need to double check def caps If the target in question has a defence cap (such as [[Akkha]]), the godsword will drain as many levels as allowed from the targeted stat, and leftover damage is ignored.-->

Against [[Tekton]], it drains his combat skills by 10 (following the stat drain order) if it fails to hit.

The special attack [[animation]]'s colours can be changed to gold, which costs 75 [[Last Man Standing]] points. Once unlocked, the gold trim can be toggled at [[Justine's stuff for the Last Shopper Standing]] whenever the player desires.
"""
