name = "Blisterwood flail"
item_ids = [24699]

[special]
"Special attack" = """
[[File:Retainer (flail).gif|thumb|220px|A player performs the blisterwood flail's special attack, ''Retainer''.]]
The blisterwood flail retains the [[Ivandis flail]]'s special attack, ''Retainer'', which traps a [[vampyre juvenile]] or [[vampyre juvinate|juvinate]] that has less than 50% hitpoints remaining, preventing it from retaliating for 30 seconds. This consumes 10% of the player's special attack energy.

Even if the attack fails to activate, stating either {{mes|This spell can only be used on vampyre juveniles or vampyre juvinates.}} or {{mes|This spell only works against vampyres with less than half of their health remaining.}}, it will still incur the normal attack delay, so take care not to accidentally use it in those circumstances.
"""
