name = "Blue moon spear"
item_ids = [28988, 29849]

[special]
"Special attack" = """
[[File:Break Shackles.gif|thumb|220px|A player performing the blue moon spear's special attack, ''Break Shackles''.]]
The blue moon spear has a [[special attack]], ''Break Shackles'', costing 50% special attack energy and requiring the full blue moon armour set to use.

''Break Shackles'' removes all active binding effects on a target and has a 1.5% increase in accuracy and damage for every [[tick]] of binding removed. The damage boost from ''Break Shackles'' is capped at a 112.5% increase, while the accuracy boost is not capped.

When the special attack is used while casting movement impairing attack spells, the next activation of the ''Frostweaver'' effect will also trigger the special allowing for a 3-hit combo that starts with the spell cast and ends with the melee hit from the ''Frostweaver'' effect.

Although the special attack uses the Fend animation, it actually grants [[Strength]] experience. When automatically performed, this attack can hit targets across diagonal spaces and over small fences or walls.
"""
