name = "Bone dagger"
item_ids = [8872]

[special]
"Special attack" = """
[[File:Backstab.gif|250px|thumb|A player performing the bone dagger's special attack, ''Backstab''.]]
The bone dagger has a [[special attack]], ''Backstab'', (75%) which will never miss as long as the target has not been damaged previously or you weren't the last one to damage the target. It lowers the target's [[Defence]] by the amount of damage dealt, similar to the [[Bandos godsword]]'s and [[Dorgeshuun crossbow]]'s special attacks. The defence lowering is only applied when the target doesn't currently have their defence levels lowered.{{CiteTwitter|author=Mod Ash|url=https://x.com/JagexAsh/status/1798626951885889739|date=6 June 2024|archiveurl=https://archive.ph/tsLWH|archivedate=6 June 2024|quote=Correct - they'll only try to reduce it if it's on (or above) its base level at the time. If it had been reduced previously, then restored to the base level, they could try to reduce it again.}}

While the weapon can be used prior to the [[Death to the Dorgeshuun]] [[quest]], the special attack can only be used after completion.

Bone dagger's special attack is commonly used within the [[Tombs of Amascut]], where the guaranteed hit is particularly effective against high defence enemies in higher invocation raids. It can be used effectively in both solo and team raids, where the player should ensure that they were not the last one to damage the target and it is used before any other forms of defence reduction.

{{bug|When the special attack is used against [[Kephri]] in teams, the bone dagger must be the first attack before anyone else hits the boss to hit her for a guaranteed hit.}}
"""
