name = "Brine sabre"
item_ids = [11037]

[special]
"Special attack" = """
[[File:Liquify.gif|thumb|230px|A player performing the Brine sabre's special attack, ''Liquify''.]]
The brine sabre has a [[special attacks|special attack]], ''Liquify'', which doubles the player's accuracy, and increases the player's [[Strength]], [[Attack]] and [[Defence]] levels by 25% of the damage dealt.

The special attack only works underwater, and consumes 75% of the player's special attack energy.
"""
