name = "Crystal harpoon"
item_ids = [23762, 23864]

[special]
"Special attack" = """
[[File:Fishstabber (crystal harpoon).gif|frame|A player performs the crystal harpoon's special attack, ''Fishstabber''.]]
The crystal harpoon has the same [[special attacks|special attack]] as a [[dragon harpoon]], ''Fishstabber'', that provides a visible +3 [[boost]] to [[Fishing]], consuming 100% special attack energy. It cannot be used without the level 70 [[Attack]] and 50 [[Agility]] requirement to wield the harpoon.

Also note that any levels boosted above 99 with the special attack will be treated as 99. Therefore, you will start to receive diminishing returns with the special attack at level 97 and 98, with there being no value in activating the special attack at level 99.
"""
