name = "Crystal halberd (i)"
item_ids = [13080, 13081, 13082, 13083, 13084, 13085, 13086, 13087, 13088, 13089, 13090]

[special]
"Special attack" = """
[[File:Sweep (crystal halberd).gif|thumb|200px|A player performing the crystal halberd's special attack, ''Sweep''.]]
The crystal halberd shared the same [[special attack]] as the [[dragon halberd]], consuming 30% of the player's special attack energy. In addition to a 10% damage boost, if used against "large" monsters (anything that is larger than 1x1, such as [[General Graardor]]), the special attack would deal an additional second hit onto them, although with 25% reduced accuracy. It could also hit 10 NPCs in a [[multi-combat area]] in a 3x1 area centred on the main target. In [[Player killing|PVP]], it could only hit three players. The crystal halberd's special attack's accuracy rolled against the opponent's slash defence.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/690476787806158848|date=22 January 2016|archiveurl=https://reldo.runescape.wiki/i/100957|archivedate=28 May 2020}}
"""
