name = "Crystal pickaxe"
item_ids = [23680, 23863]

[special]
"Special attack" = """
[[File:Rock Knocker (crystal pickaxe).gif|frame|A player performs the crystal pickaxe's special attack, ''Rock Knocker''.]]
The crystal pickaxe's [[special attack]], ''Rock Knocker'', temporarily boosts the player's [[Mining]] level by 3 (players will need to have 70 [[Attack]] and 50 [[Agility]] to utilise this special). This consumes 100% of the player's special attack energy.

As long as a player can wield the pickaxe, requiring 50 Agility and 70 Attack, the special attack can be used to mine with the pickaxe starting at 70 Mining.

Note that any levels boosted above 99 with the special attack will be treated as 99. Therefore, you will start to receive diminishing returns with the special attack at level 97 and 98, with there being no value in activating the special attack at level 99.
"""
