name = "Dark bow (Last Man Standing)"
item_ids = [20408]

[special]
"Special attack" = """
The dark bow has a unique [[special attack]] comprised of two different attacks, both of which consume 55% of the player's special attack energy.
[[File:Descent of Dragons.gif|thumb|300px|A player performing one of the dark bow's special attacks, ''Descent of Dragons''.]]
The 1st special attack, ''Descent of Darkness'', deals up to 30% more damage with a minimum of 5 damage per arrow. The animation shows two arrows fired at the target, surrounded in a black shroud.

If the player has [[dragon arrow]]s equipped, the 2nd special attack, ''Descent of Dragons'', is used instead. This attack deals up to 50% more damage with a minimum of 8 damage per arrow, while capping the max hit at 48 damage per arrow.{{CiteForum|author = Mod Ronan|url = http://services.runescape.com/m=news/architectural-alliance?oldschool=1|title = Architectural Alliance|forum = Old School RuneScape|postdate = March 3, 2016}}
The animation shows two [[black dragon]] heads fired at the target.
"""
