name = "Darklight"
item_ids = [6746]

[special]
"Special attack" = """
[[File:Weaken (special attack).gif|thumb|250px|A player performing the darklight's special attack, ''Weaken''.]]
Darklight has a [[special attack]], ''Weaken'', which consumes 50% of the player's special attack energy and lowers the opponent's [[Strength]], [[Attack]], and [[Defence]] levels by 5% (10% for [[Demon (attribute)|demons]]) of their base level + 1.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/948619653617717248|date=3 January 2018|archiveurl=https://archive.ph/yDVqL|archivedate=24 December 2022|quote=[It seems like the Darklight special attack actually drains by 5%/10% + 1. Is that true or just an inconsistency I'm seeing?] It's got a +1 in there, yes. Possibly to ensure it always does something, even if a stat is already low.}}

The accuracy roll for ''Weaken'' is made against an opponent's stab defence,{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/793083437976543233|date=31 October 2016|archiveurl=https://archive.ph/vuwtr|archivedate=24 December 2022|quote=[Against what defensive style bonus does the special attack of the darklight/arclight roll against? The dds always uses slash.] Stab.}} and its drain effect only applies to [[successful hit]]s.

''Weaken'' will stack additively upon [[successful hit]]s unlike the [[dragon warhammer]], which stacks multiplicatively. Two successful special attacks thus reduce an opponent's Strength, Attack and Defence by 10% + 2, or 20% + 2 against demonic targets.
"""
