name = "Dawnbringer"
item_ids = [22516]

[special]
"Special attack" = """
[[File:Pulsate.gif|thumb|300px|A player using the Dawnbringer's special attack, ''Pulsate''.]]
The staff's [[special attack]], ''Pulsate'', fires a powerful blast towards [[Verzik Vitur]], inflicting 75-150 [[hitpoints]] of damage towards her and consuming 35% of the wielder's special attack energy.

As players must deplete her health quickly before all the pillars in her throne room collapses, it is mandatory for teammates to drop the staff for another player to perform the special attack once they have depleted their own special attack energy.

[[Magic damage]] gear bonuses, prayer and base magic level/boosts do not affect the damage inflicted by the Dawnbringer's special attack, and it is guaranteed to be a [[successful hit]].{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1368923472840232966|date=8 march 2021|archiveurl=https://archive.is/XZ3H8|archivedate=22 July 2021|quote=[When using the Dawnbringer's special attack on Verzik, do items like occult/ancestral help max hits? I know you always hit 75-150, but do the extra damage boosts help you roll over the max hit cap, which would then be reduced to 150? (...)] Looking through its code, it looks like it doesn't respond to that sort of thing. (...) [So if I understand correctly, it seems that your roll would be completely random. Does accuracy help any? (...)] It did indeed look completely random to me, with no accuracy roll either.}}
"""
