name = "Dragon knife"
item_ids = [22804, 22812, 22814, 27157]

[special]
"Special attack" = """
[[File:Duality.gif|frame|A player performs the dragon knife's special attack, ''Duality''.]]
The dragon knife has a [[special attack]], ''Duality'', which consumes 25% of the player's special attack energy. It causes the player to throw two dragon knives at once, with each knife having its own accuracy and damage rolls.

This special attack is similar to [[dragon dagger]]'s, albeit without an extra increase in accuracy and damage.
"""
