name = "Dragon sword"
item_ids = [21009]

[special]
"Special attack" = """
[[File:Wild Stab.gif|thumb|250px|A player performing the dragon sword's special attack, ''Wild Stab''.]]
The dragon sword has a [[special attack]], ''Wild Stab'', that consumes 40% of the player's [[special attack energy]] to hit the target with 25% increased accuracy and damage. If the target is using [[Protect from Melee]], the special attack will ignore the [[prayer]] for one attack. This special rolls off of the opponent's stab defence regardless of which mode it is in.
"""
