name = "Dragon mace"
item_ids = [1434]

[special]
"Special attack" = """
[[File:Shatter.gif|frame|A player performing the dragon mace's special attack, ''Shatter''.]]
The dragon mace has a [[special attacks|special attack]] called ''Shatter'', which increases the player's accuracy by 25% and damage by 50%, while rolling against the target's crush defence. This attack consumes 25% of the player's special attack energy.
"""
