name = "Dragon dagger"
item_ids = [1215, 20407]

[special]
"Special attack" = """
[[File:Puncture.gif|frame|A player performing the dragon dagger's special attack, ''Puncture''.]]
The dragon dagger's [[special attacks|special attack]], ''Puncture'', deals two hits at once with an extra 15% accuracy and 15% damage for each of the two hits, consuming 25% of the wielder's special attack energy. ''Puncture'' rolls against opponent's slash defence roll.

When used against other players, both hits are applied simultaneously. There is a slight delay between the two hits when the special is used on NPCs.

The special attack's highest possible hit under normal combat conditions is 50 damage for each of the two hits, or a total of '''100''' damage. Although rare, the poisoned dagger's special attack can occasionally stack with the [[Weapon poison(++)|poison]] damage, resulting in a theoretical damage stack of 106. Against a Slayer target with a [[black mask]] or [[Slayer helmet]] equipped, the maximum becomes 54 per hit, dealing a maximum of '''108''' damage.

For these reasons, the dragon dagger is a staple 'knock-out' weapon in [[Player killing|PvP]] combat and a cheap option for a high-damage spec weapon in [[Monster killing|PvM]]. [[Dragon claws]] are often superior but carry a much higher price.
"""
