name = "Dragon hasta"
item_ids = [22731]

[special]
"Special attack" = """
[[File:Unleash.gif|frame|A player performs the dragon hasta's special attack, ''Unleash''.]]
The dragon hasta has a [[special attack]] called ''Unleash'', which drains the player's special attack bar and attacks with a 5% boost in accuracy and a 2.5% boost in damage for every 5% of special attack energy used. Notably, it ignores the 40% damage reduction from [[Protect from Melee]] if the opponent has the prayer active.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1581996752193789952|date=17 October 2022|archiveurl=https://archive.ph/iP4xr|archivedate=21 October 2022|quote=It [Unleash] ignores the damage reduction effect [of Protect from Melee], unlike most attacks.}} This special rolls off of the opponents stab defence regardless of which mode it is in.

For example, a player with 100% special attack energy who performs the special attack will have 100% increased accuracy (meaning the accuracy is doubled) and a damage boost of 50%.
"""
