name = "Dragon claws (Last Man Standing)"
item_ids = [20784]

[special]
"Special attack" = """
[[File:Slice and Dice.gif|frame|A player performing the dragon claws' special attack, ''Slice and Dice''.]]
These claws feature a [[special attack]], ''Slice and Dice'', which drains 50% of the special attack bar and hits an enemy four times in succession, which is commonly used by [[player killing|PKers]] as a finisher. The damage calculation rolls against the opponent's slash defence.{{CiteForum|author=Bitterkoekje|url=https://web.archive.org/web/20190905124128/http://webcache.googleusercontent.com/search?q=cache:http://services.runescape.com/m=forum/forums.ws?317,318,712,65587452,goto,2|title=Combat Formulas|postdate=10 March 2015|name=Bitterkoekje}}

:''For more info regarding the special attack, see [[Dragon claws#Special attack|here]].
"""
