name = "Dragon halberd"
item_ids = [3204]

[special]
"Special attack" = """
[[File:Sweep.gif|frame|A player uses the dragon halberd's special attack, ''Sweep''.]]
[[File:Sweep (large monster).gif|frame|A player uses the dragon halberd's special attack on a large monster.]]
The dragon halberd has a [[special attack]] called ''Sweep'', consuming 30% of the player's special attack energy. In addition to a 10% damage boost, if used against "large" monsters (anything that is larger than 1x1, such as most [[Boss]] monsters), the special attack will deal an additional second hit onto them, although with 25% reduced accuracy. It can also hit 10 NPCs in a [[multi-combat area]] in a 3x1 area centred on the main target. In [[PvP]], it can only hit three players. This can deal very high damage in multi-combat situations where there are many enemies in close vicinity.

''Sweep''{{'}}s accuracy rolls against the opponent's slash defence roll.
"""
