name = "Dragon 2h sword"
item_ids = [7158]

[special]
"Special attack" = """
[[File:Powerstab.gif|thumb|A player performing the dragon 2h sword's special attack, ''Powerstab''.]]
The dragon 2h sword has a [[special attack]], ''Powerstab'', which consumes 60% of the player's special attack energy. When used in a [[multi-combat area]], the attack hits all targets within 1 square of the player, including the one they are standing on; no more than 14 NPCs or three players can be hit at one time with this attack. However, there are no advantages when using this attack in a single-combat area.

It can be especially useful while training in multi-combat areas, like those where one may fight [[Bandit (Bandit Camp)|Bandits]] or [[Skeleton Monkeys]]. The attack is also useful in [[Nightmare Zone/Strategies|Nightmare Zone]], when used in with the "Power Surge" power-up that gives the player temporary infinite special attacks. This allows the player to deal massive amounts of damage to many surrounding enemies at once, repeatedly. It is also uncommonly used during the fight against [[The Nightmare]] when [[husk]]s are summoned around the player. The special attack is ideal when many husks or [[parasite]]s are on adjacent tiles, able to damage many at once.
"""
