name = "Dragon thrownaxe"
item_ids = [20849]

[special]
"Special attack" = """
[[File:Momentum Throw.gif|thumb|350px|A player performs the dragon thrownaxe's special attack, ''Momentum Throw''.]]
The dragon thrownaxe has a [[special attack]], ''Momentum Throw'', which consumes 25% of the player's special attack energy. It improves the player's accuracy by 25% along with guaranteeing that the player will attack on the next game tick.

The special attack could be used to attack several times in quick succession with improved accuracy. However, unlike the [[granite maul]]'s special attack, it would '''not''' be possible to use all of these special attack hits at once in the same game tick. Only one can be launched per game cycle.

Note that in addition to itself attacking on the next game tick, using the special attack counts as a normal attack, resetting the player's attack delay to 5 ticks, or 4 using rapid. Even factoring in the additional tick to throw the thrownaxe, this can result in an increased attack speed for slower weapons such as the [[heavy ballista]] or [[dark bow]], and even melee weapons such as a [[crystal halberd]].

Dragon thrownaxes are instantly consumed when they are thrown using the special attack if not used with an Ava's device.
"""
