name = "Dragon scimitar"
item_ids = [4587, 20406]

[special]
"Special attack" = """
[[File:Sever.gif|frame|A player performing the dragon scimitar's special attack, ''Sever''.]]
The dragon scimitar has a [[special attacks|special attack]], ''Sever'', costing 55% of the player's special attack energy and rolls against the target's slash defence with 25% higher accuracy.{{CiteForum|author=Bitterkoekje|url=https://web.archive.org/web/20190905124128/http://webcache.googleusercontent.com/search?q=cache:http://services.runescape.com/m=forum/forums.ws?317,318,712,65587452|title=Combat Formulas|postdate=10 March 2015|name=Bitterkoekje}} In PvP fights, this special attack has an additional effect that, upon a [[successful hit]], disables the targeted player's active [[protection prayers]] ([[Protect from Magic]], [[Protect from Missiles]], and [[Protect from Melee]]) and prevents the targeted player from using said prayers for 8 ticks (4.8 seconds).
"""
