name = "Dragon crossbow"
item_ids = [21902]

[special]
"Special attack" = """
[[File:Annihilate.gif|thumb|270px|A player performs the special attack of the Dragon crossbow, ''Annihilate''.]]
The crossbow has a [[special attack]], ''Annihilate'', which drains 60% of the special attack bar and hits up to 9 enemies in a 3x3 area. The player will roll for accuracy, and if it succeeds, then rolls for a hit between 0 and the usual maximum hit from the regular attack. The primary target of Annihilate will take 20% extra damage, and all other targets will take 20% less damage. For example, if a hit of 25 is rolled, the primary target will get 30 damage and the other targets will get 20 damage. If used in a [[single-way combat]] area, the attack will still work but only hit one target with 20% extra damage.

[[Enchanted bolt]]s cannot activate their effects when using the dragon crossbow's special attack.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/950832168426754048|date=9 January 2018|archiveurl=https://reldo.runescape.wiki/i/97662|archivedate=20 May 2023|quote=It does not have a chance to do the special effect during the special attack, correct.}}
"""
