name = "Dragon longsword"
item_ids = [1305]

[special]
"Special attack" = """
[[File:Cleave.gif|thumb|200px|A player performing the dragon longsword's special attack, ''Cleave''.]]
The dragon longsword has a [[special attack]] called ''Cleave'', which raises the player's maximum hit by 25% for one hit, consuming 25% of the player's special attack energy. The accuracy roll for ''Cleave'' is based on the attack bonus of the player's currently selected style, which is rolled against an opponent's slash defence.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1019216709914423296|date=17 July 2018|archiveurl=https://reldo.runescape.wiki/i/109277|archivedate=24 December 2022|quote=[Hey, do you happen to know  whether the dragon long uses your current combat style for its spec or is just always slash? (...)] It uses your current style but rolls against the NPC's slash defence.}}
"""
