name = "Dragon harpoon"
item_ids = [21028]

[special]
"Special attack" = """
[[File:Fishstabber.gif|frame|A player performs the dragon harpoon's special attack, ''Fishstabber''.]]
The dragon harpoon has a [[special attack]], ''Fishstabber'', that provides a visible +3 boost to [[Fishing]]. This consumes 100% of the player's special attack energy. Special attacks require the player to wield the weapon, so this Fishing boost cannot be used without the 60 [[Attack]] required to wield the harpoon.

Also note that any levels boosted above 99 with the special attack will be treated as 99. Therefore, you will receive diminished returns with the special attack at level 97 and 98, with there being no value in speccing at level 99.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1375844352098975753|date=27 March 2021|archiveurl=https://reldo.runescape.wiki/i/98237|archivedate=29 March 2021}} Like the [[dragon axe]], the dragon harpoon's special attack does '''not''' disrupt resource gathering if the player is already fishing when the special attack is activated.
"""
