name = "Dual macuahuitl"
item_ids = [28997, 29850]

[special]
"Special attack" = """
[[File:Blood Infusion.gif|thumb|220px|A player performing the dual macuahuitl's special attack, ''Blood Infusion''.]]
The dual macuahuitl has a [[Special attacks|special attack]], ''Blood Infusion'', costing 25% special attack energy and requiring the full [[blood moon armour]] set to use.

Blood Infusion removes the sequential accuracy check and raises the player's minimum and maximum hit by 25% for that attack, whilst taking damage equal to 25% of their current [[Hitpoints]], rounded down (dealing no damage when less than 4 health). Additionally, the [[Blood moon armour#Set effect|''Bloodrager'']] set effect is guaranteed to trigger if the attack hits; if the special attack fails, the player will still take the damage used for it.

Within the [[Nightmare Zone]], the special attack will remove [[absorption]] charges if above 4 HP, dealing 0 damage to the player.
"""
