name = "Echo harpoon"
item_ids = [25114]

[special]
"Special attack" = """
[[File:Echo fishstabber.webm|frame|A player performs the echo harpoon's special attack, ''Fishstabber''.]]
The echo harpoon has the same [[special attacks|special attack]] as the [[dragon harpoon]] and [[crystal harpoon]], ''Fishstabber'', that provides a visible +3 [[boost]] to [[Fishing]], consuming 100% special attack energy.

Also note that any levels boosted above 99 with the special attack will be treated as 99. Therefore, you will start to receive diminishing returns with the special attack at level 97 and 98, with there being no value in activating the special attack at level 99.
"""
