name = "Eclipse atlatl"
item_ids = [29000, 29851]

[special]
"Special attack" = """
[[File:Eclipse.gif|thumb|220px|A player performing the eclipse atlatl's special attack, ''Eclipse''.]]
The eclipse atlatl has a special attack, ''Eclipse'', costing 50% special attack energy and requiring the full eclipse moon armour set to use. The attack itself is magic-based and performed at melee distance, with a 50% accuracy bonus. Atlatl darts do not need to be equipped to perform the special attack.

If the target was inflicted with a burn, such as from the armour's set effect or the special attack of the [[Burning claws]], [[Arkan blade]], or [[Scorching bow]], the special attack will consume the remainder of the burn damage it would have dealt to the target, increasing the player's max hit by that number and their minimum hit by half of that number, capped at 50.

For example, if the burn effect would have dealt 6 more damage before dissipating, the special attack would increase the player's max hit by 6, and their minimum hit by 3, for that attack.
"""
