name = "Excalibur"
item_ids = [35]

[special]
"Special attack" = """
[[File:Sanctuary.gif|thumb|200px|''A player performing the Excalibur's special attack, '''Sanctuary'''''.]]
Excalibur has a [[special attack]], ''Sanctuary'', which temporarily increases the player's [[Defence]] by 8 and consumes 100% special attack energy.
"""
