name = "Eye of ayak"
item_ids = [31113]

[special]
"Special attack" = """
[[File:Soul Rend.gif|thumb|250px|A player using the eye of Ayak's special attack, ''Soul Rend''.]]
The eye of Ayak has a [[special attack]], ''Soul Rend'', which consumes 50% of the player's special attack energy. The special attack is fired slower than a standard attack, with it being a 5-tick attack rather than 3. As compensation, the player's accuracy is doubled and max hit is increased by 30%.

When it successfully damages a target, the target will lose Magic Defence equal to the amount dealt. This is different compared to Magic levels, but can still provide a noticeable impact when facing an enemy with a low Magic level but high Magic Defence, such as [[General Graardor]]. As Magic Defence is a stat and not a level, NPCs cannot restore drained defence.

Magic Defence cannot be drained below 0, but it will carry over if any stat changes are detected. For example, a player hits 50 with the special on [[Yama]] while he is in his melee stance (-30 Magic Defence). If Yama changes to his magic stance (+60 Magic Defence in phase 1/2, or +81 in phase 3), Yama's actual Magic Defence will become +10/31 respectively. The same applies to [[Zulrah]], whose tanzanite form has Magic Defence, but not its serpentine or magma forms.
"""
