name = "Granite hammer"
item_ids = [21742]

[special]
"Special attack" = """
[[File:Hammer Blow.gif|thumb|250px|A player performing the granite hammer's special attack.]]
The granite hammer has a [[special attacks|special attack]], ''Hammer Blow'', which consumes 60% of the player's special attack energy, and deals an attack with 50% increased accuracy, while guaranteeing 5 additional damage to that attack.

Even if the special attack misses, the target will still take a minimum of 5 damage from it. This excludes NPCs that are immune to normal forms of attack, such as [[vyrewatch]] and [[slayer monster]]s the player does not have the [[Slayer]] level to harm.
"""
