name = "Granite maul"
item_ids = [4153, 12848, 20557, 24225, 24227]

[special]
"Special attack" = """
[[File:Quick Smash.gif|thumb|250px|A player performing the granite maul's special attack, ''Quick Smash''.]]
The granite maul's [[special attacks|special attack]], ''Quick Smash'', consumes 60% of the player's special attack energy and deals an instant attack. This is reduced to 50% when using a [[granite maul (ornate handle)]].

With the handle added, the special attack can result in two or three hits in a very short amount of time, making it a popular choice for [[player killing]]. If the three hits are timed correctly, the granite maul can kill instantly. However, one drawback is that unlike most special attacks, ''Quick Smash'' does not increase accuracy.

It is commonly used in the [[Nightmare Zone]] in conjunction with the Power surge power-up. Because ''Quick Smash'' can be performed rapidly under the effect of Power surge, the granite maul is able to put out more total damage than other special attacks for as long as the power-up is active.
"""
