name = "Heavy ballista"
item_ids = [19481, 23630]

[special]
"Special attack" = """
[[File:Concentrated Shot (heavy ballista).gif|thumb|250px|A player performing the heavy ballista's special attack, ''Concentrated Shot''.]]
The heavy ballista has a [[special attack]], ''Concentrated Shot'', which it shares with the [[light ballista]]. It performs an attack with 25% increased accuracy and damage.

The special attack consumes 65% of the player's special attack energy.
"""
