name = "Keris partisan of the sun"
item_ids = [27291]

[special]
"Special attack" = """
[[File:Tumeken's Light.gif|thumb|250px|A player performing the Keris partisan of the sun's special attack, ''Tumeken's Light''.]]
The keris partisan of the sun has a [[special attacks|special attack]], ''Tumeken's Light'', which consumes 50 [[prayer points]] in addition to 75% of the player's special attack energy.

The special attack will fully heal the player to their maximum health and overheal players up to 20% of their base Hitpoints level. It will also cure [[poison]], and venom, as well as restore the player's [[run energy]] and any drained [[stats]].
"""
