name = "Keris partisan of corruption"
item_ids = [27287]

[special]
"Special attack" = """
[[File:Wrath of Amascut.gif|thumb|250px|A player performing the Keris partisan of corruption 's special attack, ''Wrath of Amascut''.]]
The keris partisan of corruption has a [[special attacks|special attack]], ''Wrath of Amascut'', which consumes 75% of the player's special attack energy. The special attack, for the next hit, provides a 100% increase to accuracy and a 25% increase to the player's damage.

The target hit by the special attack will also receive 25% increased damage for 10 [[ticks]] (6 seconds); the special attack must be a [[successful hit]] in order for it to take effect. However, players performing the special attack will be unable to attack for 8 ticks (4.8 seconds). As such, it is recommended to have teammates focus on the target hit by the special attack afterwards if possible.
"""
