name = "Light ballista"
item_ids = [19478, 27188]

[special]
"Special attack" = """
[[File:Concentrated Shot (light ballista).gif|thumb|250px|A player performing the light ballista's special attack, ''Concentrated Shot''.]]
The light ballista has a [[special attack]], ''Concentrated Shot'', which it shares with the [[heavy ballista]]. It performs an attack with 25% increased accuracy and damage and uses 65% of the player's special attack energy.
"""
