name = "Morrigan's throwing axe (bh)"
item_ids = [27912]

[special]
"Special attack" = """
[[File:Hamstring.gif|thumb|260px|A player performing Morrigan's throwing axe's special attack.]]
Morrigan's throwing axe has a [[special attack]], ''Hamstring'', that consumes 50% of the player's [[special attack energy]]. ''Hamstring'' has 150% accuracy and deals between 50% and 150% of the user's max hit.

Against players, it will also increase the rate that the target's [[run energy]] is drained by six times. When this occurs, the target will receive a message in their chatbox stating {{mes|You've been hamstrung! For the next minute, your run energy will drain 6x faster.}}
"""
