name = "Morrigan's javelin (bh)"
item_ids = [27916]

[special]
"Special attack" = """
[[File:Phantom Strike.gif|thumb|260px|A player performing Morrigan's javelin special attack.]]
Morrigan's javelin has a [[special attack]], ''Phantom Strike'', that consumes 50% of the player's [[special attack energy]] and applies a damage over time effect to the opponent after the special attack is performed. This special attack has no effect on [[NPC]]s. The special attack has 150% accuracy.

Every tick (0.6 seconds) after the special attack is performed, the opponent will take an additional 10 hitpoints of damage until 75% of the damage dealt by the special attack has been delivered. When this occurs, the target will receive a message in their chatbox stating "''You start to bleed as a result of the javelin strike.''" Subsequent damage will result in the chatbox stating "''You continue to bleed as a result of the javelin strike.''"
"""
