name = "Morrigan's throwing axe (Deadman Mode)"
item_ids = [22634]

[special]
"Special attack" = """
[[File:Hamstring.gif|thumb|260px|A player performing Morrigan's throwing axe's special attack.]]
Morrigan's throwing axe has a [[special attack]], ''Hamstring'', that consumes 25% of the player's [[special attack energy]] and deals between 20% and 120% of the user's max hit. if the hit lands, it will also reduce the attack interval of the next attack by 1 tick.

Against players, it will also increase the rate in which the target's [[run energy]] is drained by sixfold. When this occurs, the target will receive a message in their chatbox stating {{mes|You've been hamstrung! For the next minute, your run energy will drain 6x faster.}}
"""
