name = "Noxious halberd"
item_ids = [29796, 33178]

[special]
"Special attack" = """
[[File:Virulence.gif|thumb|200px|A player performs the noxious halberd's special attack, ''Virulence''.]]
The noxious halberd has a [[special attack]], ''Virulence'', which consumes 50% of the wielder's special attack energy. ''Virulence'' can only be used if the player is afflicted with [[poison]] or [[venom]], and instantly cures the condition; attempting to use the special attack while not poisoned/venomed will give the message {{mes|You can only use this special attack whilst you are poisoned.}}. The player's next accurate attack with the halberd will have its minimum hit increased by the damage the player would have taken from their cured affliction. This effect is lost if the player changes weapon or logs out.

For example, a poisoned player who is poised to take 16 poison damage can use ''Virulence'' to cure themselves, and their next accurate attack will do a damage roll between 16 and their max hit.

Note that ''Virulence'' does not give any period of immunity towards poison and venom.
"""
