name = "Osmumten's fang"
item_ids = [26219, 33174]

[special]
"Special attack" = """
[[File:Eviscerate.gif|thumb|250px|A player performing Osmumten's fang's special attack, ''Eviscerate''.]]
Osmumten's fang has a [[special attack]], ''Eviscerate'', which consumes 25% of the player's special attack energy. The attack provides a 50% increase to accuracy for the next hit. The fang's normal attacks are limited to 85% of the player's max hit; the special attack instead uses the fang's true max hit when determining damage rolls (i.e., 100% of max hit).

For example, if the fang's true max hit was 60, it would roll between 9 to 60 damage upon a successful hit, rather than the usual 9 to 51 damage it would normally roll. This effectively increases damage by the same amount as a weapon special that increases max hit by 17.65%.
"""
