name = "Rod of ivandis"
item_ids = [7639, 7640, 7641, 7642, 7643, 7644, 7645, 7646, 7647, 7648]

[special]
"Special attack" = """
[[File:Retainer (rod).gif|frame|A player performs the rod of Ivandis' special attack, ''Retainer''.]]
The rod of Ivandis has a special attack, ''Retainer'', which traps a [[Vampyre Juvenile]] or [[Vampyre Juvinate]] that has less than 50% hitpoints remaining, preventing it from retaliating for 30 seconds. This consumes 10% of the player's special attack energy.

Each special attack consumes one charge from the rod. After all charges have been used, the player will be left with [[rod dust]] in their weapon slot.

Even if the attack fails to activate, stating either {{mes|This spell can only be used on vampyre juveniles or vampyre juvinates.}} or {{mes|This spell only works against vampyres with less than half of their health remaining.}}, it will still incur the normal attack delay, so take care not to accidentally use it in those circumstances.
"""
