name = "Rosewood blowpipe"
item_ids = [31583]

[special]
"Special attack" = """
[[File:Rapid Burst.gif|250px|thumb|A player performs the rosewood blowpipe's special attack, ''Rapid Burst''.]]
The rosewood blowpipe has a [[special attack]], ''Rapid Burst'', which will shoot two darts in rapid succession, using 25% of a player's special attack energy. Each dart shot has its own accuracy and damage rolls, with accuracy reduced by 20% and damage increased by 10%.

It functions similarly to a budget [[dragon knife]] for enemies with low defence, or against targets on which the player is guaranteed a [[successful hit]].

Ranging and hitpoints experience is granted for the second hit even if the first hit fully depletes the target's hitpoints. The second hit will show as a blue zero damage splat despite being calculated as a hit.
"""
