name = "Rune claws"
item_ids = [3101]

[special]
"Special attack" = """
[[File:Impale.gif|thumb|230px|A player using the rune claws' special attack, ''Impale''.]]
Rune claws have a [[special attacks|special attack]], ''Impale'', which consumes 25% of the player's special attack energy and deals 10% increased damage. The special attack increases the time until the next attack by one tick (0.6 seconds). This effectively lowers your damage output by taking 25% more time to deal only 10% more damage.
"""
