name = "Saradomin's blessed sword"
item_ids = [12809]

[special]
"Special attack" = """
[[File:Saradomin's Blessed Lightning.gif|thumb|200px|A player performing the Saradomin's blessed sword's special attack, ''Saradomin's Lightning''.]]
Saradomin's blessed sword has a [[special attacks|special attack]], ''Saradomin's Lightning'', which deals a [[Magic]]-based attack ([[Magical melee]]) that increases the player's max hit by 25%, consuming 65% of the player's special attack energy.

The special attack rolls against the opponent's Magic defence.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1461036149733011456|date=17 November 2021|archiveurl=https://reldo.runescape.wiki/i/109795|archivedate=24 December 2022|quote=(...) The blessed Saradomin sword's hit counts as *melee*, though it rolls against the target's magical defence.}} Under perfect conditions, the special attack can hit up to 72. Despite being Magic-based, it will still inflict damage on [[Cyclops]] in the [[Warriors' Guild]] and soldiers inside the [[Shayzien]] [[combat ring (shayzien)|combat ring]].
"""
