name = "Scorching bow"
item_ids = [29591]

[special]
"Special attack" = """
[[File:Scorching shackles.gif|thumb|300px|A player performing the scorching bow's special attack, ''Scorching shackles''.]]
The scorching bow has a [[special attack]], ''Scorching shackles'', which drains 25% of the player's special attack energy.

''Scorching shackles'' binds [[Demon (attribute)|demons]] for 20 ticks (12 seconds), dealing 1 [[burn]] damage in the process. It deals an additional 1 burn damage every 4 ticks (2.4 seconds), for a total of 5 burn damage.<!--The in-game tooltip mentions it having "30% bonus accuracy" as well, though this appears to be referring to the bow's native 30% demonbane bonus since the special attack only affects demons.-->

Against non-demonic creatures, attempting to use the special attack results in the message {{mes|Scorching shackles won't work against a non-demon enemy.}}
"""
