name = "Seercull"
item_ids = [6724]

[special]
"Special attack" = """
[[File:Soulshot.gif|thumb|280px|A player using the bow's special attack, ''Soulshot''.]]
The Seercull has a [[special attack]], ''Soulshot'', which consumes 100% of the player's special attack energy. It is [[Successful hit|guaranteed to hit]] and lowers the opponent's [[Magic]] level equal to damage dealt. However, damage inflicted by ''Soulshot ''is only boosted strictly through ammunition and visible range level. Ranged [[prayer]]s (such as [[Eagle Eye]] and [[Rigour]]) and all other equipment providing ranged strength, including those with special effects such as any variants of [[Void Knight equipment]], [[salve amulet]], or [[Slayer helmet]], will all have no effect. The special attack will only drain the opponent's Magic level if it is not already reduced; consecutive use of ''Soulshot ''or [[accursed sceptre]] special attacks will have no effect on their Magic level until the stat has been fully restored, at which point it may be reapplied.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1282369216058982400|date=12 July 2020|quote=Same in PvP too, by the way, since I wasn't explicit earlier.|archiveurl=https://reldo.runescape.wiki/i/105845|archivedate=17 December 2020}}

In PvP combat, the special attack gains use for its ability to lower the Magic level of a mage to prevent them from casting spells. However, this can be mitigated by use of [[super restore]] potions.

The following formula can be used to calculate the max hit of ''Soulshot'': <br/>
<br/>
<math>\\text{Maximum Hit} =\\left\\lfloor 0.5+\\frac{\\text{(Visible Ranged Level} + 10) *(\\text{Ammo Ranged Strength} +64)}{640} \\right\\rfloor</math> {{efn|name=stance|A stance bonus of 10 is used regardless of attack style used.}}

{{notelist}}
"""
