name = "Soulreaper axe"
item_ids = [28338]

[special]
"Special attack" = """
[[File:Behead.gif|thumb|250px|A player performing the soulreaper axe's special attack, ''Behead,'' with five Soul Stacks.]]
The Soulreaper axe has a [[special attack]], ''Behead'', which consumes all Soul Stacks and does not require special attack energy.

For each Soul Stack consumed, ''Behead'' increases the player's accuracy and damage by 6% and heals them by 8 Hitpoints, effectively restoring any health spent to create those Soul stacks. Players are healed regardless of whether the attack was a [[successful hit]] or not. If a player is at full health and has active ''Soul stacks'' they can utilise them as a temporary health bank; using ''Behead'' to restore up to 40 hitpoints instantly when needed.

Equipping the Soulreaper axe replaces the special attack interface with a unique graphic ([[File:Soul Stack.png|link=]]) that indicates the Soul stack resource, however player's special attack energy continues to regenerate in the background normally. Since the special attack only consumes Soul stacks, In PvP it's useful to combo ''Behead'' into special attacks from other weapons like the [[granite maul]], [[Dragon claws]] or [[Voidwaker]] for high amounts of burst damage on the target and burst healing for yourself.
"""
