name = "Staff of the dead"
item_ids = [11791, 23613]

[special]
"Special attack" = """
[[File:Power of Death.gif|thumb|170px|A player using the staff of the dead's special attack, ''Power of Death''.]]
The staff has a [[special attack]], ''Power of Death'', that halves all of the opponent's [[melee]] damage, consuming 100% of the player's special attack energy. Upon activating the special attack, a message will appear in the player's chatbox: {{mes|Spirits of deceased evildoers offer you their protection.|color=green}}

The effect lasts for one minute after using the special attack, but will instantly end if the player takes damage while the staff is not equipped. In addition, the effect stacks with the PvP damage reduction effect of the [[Protect from Melee]] [[prayer]]. The effect '''does not''' stack with itself should the player manage to cast the effect more than once before the initial cast expires.

The special attack '''cannot''' be used in legacy duels within the [[Emir's Arena]] if magic is disabled.

This special attack is also shared with the [[staff of light]], [[staff of balance]], and [[toxic staff of the dead]].
"""
