name = "Statius's warhammer (bh)"
item_ids = [27908]

[special]
"Special attack" = """
[[File:Smash (Statius's warhammer).gif|thumb|250px|A player performing Statius's warhammer's special attack.]]
Statius's warhammer has a [[special attack]], ''Smash'', that consumes 35% of the player's [[special attack energy]] and deals between 25% and 125% of the user's max hit, while lowering the target's '''current''' [[Defence]] level by 75% on a [[successful hit]].

Defence level reductions '''do stack''' over multiple successful hits; each reduction is calculated from the current temporary level (so follow-up drains reduce fewer levels). Two successful special attacks thus reduce an opponent's Defence by a total of ~93%.
"""
