name = "Tonalztics of ralos"
item_ids = [28922]

[special]
"Special attack" = """
The Tonalztics of ralos has a [[special attack]], ''Division'', costing 50% special attack energy. ''Division'' reduces the target's [[Defence]] level by 10% of the target's [[Magic]] level on a [[successful hit]]. This effect occurs for each individual hit, meaning a ''charged'' special attack can potentially reduce the target's defence two times ''(20% of Magic level)'' with a potential four time reduction if using two specials in a row ''(40% of Magic level)''.

This effect makes it uniquely useful for high-defence targets who have an accompanying high-magic level, or for draining the defence of targets who are otherwise unreachable with standard methods (like a [[dragon warhammer]]). One example is [[Zulrah]]: with its 300 Magic and Defence, ''Division'' can potentially drain up to 120 Defence (30 x 4) immediately and greatly increase accuracy for the duration of the fight.

When used on NPCs, the defence reduction from a successful first hit will apply for the calculation of the second hit. However, this is not the case when used in PvP.{{CiteTwitter|url=https://x.com/jagexash/status/1794310805233840131|date=25 May 2024|author=Mod Ash|archiveurl=https://archive.is/uEGYt|archivedate=30 May 2024|quote=On an NPC, I believe any defence reduction from the 1st calculated hit can help with the 2nd roll even though it's in the same tick. However, on a player, I *believe* the target's effective defence would not be recalculated within that tick, so the 2nd roll may not be helped.}}

The special attack animation differs depending on whether the weapon is charged.

<gallery mode="packed" heights="200" style="text-align:left">
Division.gif|A player performs ''Division'' with the uncharged weapon.
Division (charged).gif|A player performs ''Division'' with the charged weapon.
</gallery>
"""
