name = "Toxic staff (deadman)"
item_ids = [33036]

[special]
"Special attack" = """
[[File:Power of Death (Deadman).gif|thumb|170px|A player using the toxic staff of the dead's special attack, ''Power of Death''.]]
The staff has a [[special attack]], ''Power of Death'', that halves all of the opponent's [[melee]] damage, consuming 100% of the player's special attack energy. Upon activating the special attack, a message will appear in the player's chatbox: "''{{Colour|#007f00|Spirits of deceased evildoers offer you their protection.}}''"

The effect lasts for one minute after using the special attack, but is immediately lost if players unequip the staff. In addition, the effect stacks with the PvP damage reduction effect of the [[Protect from Melee]] [[prayer]].
"""
