name = "Toxic blowpipe"
item_ids = [12926]

[special]
"Special attack" = """
[[File:Toxic blowpipe special attack projectile.gif|left|The projectile from the special attack.]]
[[File:Toxic Siphon.gif|250px|thumb|A player performs the toxic blowpipe's special attack, ''Toxic Siphon''.]]
The toxic blowpipe has a [[special attack]], ''Toxic Siphon'', which increases accuracy by 100% and damage by 50%, while healing the user by half of the damage dealt (rounded down). This consumes 50% of the player's special attack energy.

Similar to the [[Saradomin godsword]] special attack, if the target dies from the special attack, it will still heal the player based on what they would have hit if the target  had more Hitpoints; for example, if the hit was calculated to deal 20 damage and the target only has 4 Hitpoints, it will heal the player by 10 Hitpoints. For certain monsters, it heals based on the damage dealt before calculating damage reduction, such as [[Vorkath]] during its acid phase (where it will take 50% reduced damage), [[kurasks]] that have 100% damage resistance to most weaponry, or [[Akkha]] during his ranged state which is 100% resistant to Ranged attacks.
"""
