name = "Ursine chainmace"
item_ids = [27660]

[special]
"Special attack" = """
[[File:Bear Down.gif|thumb|250px|A player performing the ursine chainmace's special attack, ''Bear Down''.]]
The ursine chainmace has a [[special attacks|special attack]], ''Bear Down'', which consumes 50% of the player's special attack energy and is only usable whilst charged. The special attack hits an enemy with doubled accuracy, and upon a [[successful hit]], also deals 20 damage over 6 seconds, prevents running for 3.6 seconds (6 ticks), and reduces the target's Agility level by 20.

The accuracy roll for ''Bear Down'' is based on the offensive bonuses of one's currently selected style, which is rolled against an opponent's slash defences.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1661795401769385993|date=25 May 2023|archiveurl=https://reldo.runescape.wiki/i/100345|archivedate=25 May 2023|quote=Accuracy roll is based on whatever style you have selected (which is pretty normal for specs); defence roll is based on the target's slash detence.}}
"""
