name = "Vesta's spear (Deadman Mode)"
item_ids = [22610]

[special]
"Special attack" = """
[[File:Spear Wall.gif|thumb|250px|A player performing Vesta's spear's special attack.]]
Vesta's spear has a [[special attack]], ''Spear Wall'', that consumes 50% of the player's [[special attack energy]] and damages up to 16 targets within 8 tiles surrounding the player (one if the player is outside a [[multicombat area]]).

In addition, the user becomes immune to melee attacks for 8 ticks (4.8 seconds).
"""
