name = "Vesta's spear (bh)"
item_ids = [27900]

[special]
"Special attack" = """
[[File:Spear Wall.gif|thumb|250px|A player performing Vesta's spear's special attack.]]
Vesta's spear has a [[special attack]], ''Spear Wall'', that consumes 50% special attack energy and performs an initial hit that deals up to 100% of the player's max hit. After 2 ticks (1.2 seconds), a second hit lands that deals between 50% and 75% of the damage inflicted by the first hit.

In addition, the user becomes immune to melee and ranged attacks for 8 ticks (4.8 seconds). Upon a successful hit, the player's attack delay is reduced by 1 tick.
"""
