name = "Vesta's longsword (Last Man Standing)"
item_ids = [23615]

[special]
"Special attack" = """
[[File:Feint.gif|thumb|260px|A player performing Vesta's longsword's special attack.]]
Vesta's longsword has a [[special attack]], ''Feint'', that consumes 25% of the player's [[special attack energy]] and deals between 20% and 120% of the user's max hit, with the accuracy of this attack rolled against 25% of the opponent's [[defence]].

{{Last Man Standing}}
{{Last Man Standing in-game items}}
[[Category:Weapons with Special attacks]]
"""
