name = "Vesta's blighted longsword"
item_ids = [24617]

[special]
"Special attack" = """
[[File:Feint.gif|thumb|260px|A player performing Vesta's blighted longsword's special attack.]]
Vesta's blighted longsword has a [[special attacks|special attack]], ''Feint'', that consumes 25% of the player's [[special attack energy]] and deals between 20% and 120% of the user's max hit.

The accuracy of this special attack is rolled against 25% of the opponent's [[defence]].
"""
