name = "Voidwaker"
item_ids = [27690, 27869]

[special]
"Special attack" = """
[[File:Disrupt.gif|thumb|250px|A player performing the Voidwaker's special attack, ''Disrupt''.]]
The Voidwaker has a [[special attack]], ''Disrupt'', which consumes 50% of the player's special attack energy. The special attack deals [[successful hit|guaranteed]] Magic damage between 50-150% of the wielder's maximum melee hit. The special attack will provide 2 Magic experience per damage dealt.

The special attack is particularly useful due to its guaranteed medium to high damage. In [[Player killing|PvP]], it can be used for a consistent finishing blow and it pairs well with other high-damage special attack weapons such as the [[Armadyl godsword|Armadyl]] or [[ancient godsword]], [[dragon claws]], or [[granite maul]] due to its special attack cost. In [[Monster killing|PvM]], it excels against opponents with high Defence and low-medium Hitpoints, such as [[Kalphite Queen]], [[God Wars Dungeon]] bosses, and [[Phosani's Nightmare]], where dragon claws or other weapons would deal less damage on average and Defence reduction is less effective.

As it deals Magic damage, it is less effective against opponents with a Magic damage resistance, such as players using [[Protect from Magic]] or [[Great Olm]]'s melee claw. Conversely, it deals full damage against the [[Corporeal Beast]]. In the [[Theatre of Blood]], in the fight against [[Nylocas Vasilias]], this special attack only deals damage against the magic (blue) form.
"""
