name = "Voidwaker (Last Man Standing)"
item_ids = [27869]

[special]
"Special attack" = """
[[File:Disrupt.gif|thumb|250px|A player performing the Voidwaker's special attack, ''Disrupt''.]]
The Voidwaker has a [[special attack]], ''Disrupt'', which consumes 50% of the player's special attack energy. The special attack deals [[successful hit|guaranteed]] Magic damage between 50-150% of the wielder's maximum melee hit.

{{Last Man Standing}}
{{Last Man Standing in-game items}}
[[Category:Weapons with Special attacks]]
"""
