name = "Webweaver bow"
item_ids = [27655]

[special]
"Special attack" = """
[[File:Swarm.gif|thumb|250px|A player performing the Webweaver bow's special attack, ''Swarm''.]]
The webweaver bow has a [[special attack]], ''Swarm'', which consumes 50% of the player's special attack energy. The special attack hits an enemy four times in succession with doubled accuracy, each dealing up to 40%, rounded up, of the player's max hit.{{CiteTwitter|author=Mod Ash|url=https://twitter.com/JagexAsh/status/1644697183013285889|date=8 April 2023|archiveurl=https://reldo.runescape.wiki/i/103577|archivedate=9 April 2023|quote=It doubles the value used for the accuracy roll on all four. Yes, they're rolled separately.}}

Each hit also has a chance to inflict [[poison]], starting at four damage.
"""
