name = "Zaryte crossbow"
item_ids = [26374, 27186]

[special]
"Special attack" = """
[[File:Evoke.gif|thumb|280px|A player performing the Zaryte crossbow's special attack, ''Evoke'', with [[Diamond bolts (e)|enchanted diamond bolts]].]]
The Zaryte crossbow has a [[special attack]], ''Evoke'', which consumes 75% of the player's special attack energy. The special attack provides doubled accuracy for the attack, and guarantees the special effect of any [[enchanted bolt]]s used, provided that the player lands a [[successful hit]] on the target.

[[Enchanted ruby bolts]] are the most popular bolts to use with ''Evoke'' in most [[boss]] encounters, as successful hits can guarantee that up to 110 damage is dealt. Unless the enemy has high Ranged defence or low health (with diminishing returns below 500), this makes the Zaryte crossbow one of the most powerful special attack weapons in the game, dealing an extremely high amount of damage reliably. For prolonged encounters, wearing the [[lightbearer]] will make this combination even more effective.

Coupled with natural ruby bolt procs, this special attack is also popular for speed-based [[Combat Achievement]] tasks where frequent high hits are necessary.
"""
