quest = "Murder Mystery"
step_count = 1

[[steps]]
index = 0
name = "Starting out"
links = ["Sinclair Mansion", "Camelot", "Guard (Sinclair Mansion)", "pungent pot", "criminal's dagger", "criminal's thread", "Anna", "silver necklace", "Bob (Sinclair)", "silver cup", "Carol", "silver bottle", "David (Murder Mystery)", "silver book", "Elizabeth (Murder Mystery)", "silver needle", "Frank", "silver pot (Murder Mystery)", "Sinclair Guard dog", "flypaper", "unknown print", "Gossip", "Poison Salesman", "bank", "Seers' Village", "Sinclair family compost heap", "Sinclair family beehive", "Sinclair mansion drain", "Spiders' nest", "Sinclair family fountain", "Sinclair family crest"]
text = """
{{Map|x=2741|y=3562|r=4|mtype=square|width=250|height=250|align=right|caption=The quest's start point.}}
Head to the [[Sinclair Mansion]] located north to [[Camelot|camelot castle]].

Talk to the [[Guard (Sinclair Mansion)|guard]] to activate the quest. Then, enter the house and search the murder scene, which is on the east side of the {{FloorNumber|uk=0}}. There are three things you need to do in this room.

# Inside will be a [[pungent pot]] on a table, which you should pick up.
# There is the [[criminal's dagger]] on the floor, which you should collect.
# Investigate the smashed window to find the [[criminal's thread]].

Go around to the various bedrooms belonging to the suspects to find six silver items, all contained within barrels in each room. (There are four rooms upstairs and two on the {{FloorNumber|uk=0}}.) Look for:

*[[Anna]]'s [[silver necklace]]
*[[Bob (Sinclair)|Bob]]'s [[silver cup]]
*[[Carol]]'s [[silver bottle]]
*[[David (Murder Mystery)|David]]'s [[silver book]]
*[[Elizabeth (Murder Mystery)|Elizabeth]]'s [[silver needle]]
*[[Frank]]'s [[silver pot (Murder Mystery)|silver pot]]

Now, it's time to get your first piece of evidence. Go to the main entrance of the mansion, and go north-east until you reach the [[Sinclair Guard dog|guard dog]] enclosure. Investigate the sturdy wooden gate for more information.

Next, go to the gardener's shed (the small house on the ground level, west side of the outside of the mansion) and investigate the sacks to find [[flypaper]]. Take seven of these.

Go to the kitchen, and fill your pot with flour. Use it on the criminal's dagger; then, use the dagger on a piece of flypaper to get an [[unknown print]]. Dust each silver item with more flour, and use the flypaper to lift fingerprints from the items; then, compare them to the print of the criminal's dagger you found at the crime scene by using the flypaper pieces on the first flypaper print you got from the dagger.

Once you've got a match, all the silver items are no longer needed and can be safely dropped, except for your proof.

You'll need more than just that for a conviction, though. Go to the entrance of the mansion, and talk to [[Gossip]], and ask him who he thinks is responsible.

[[File:Murder Mystery - Poison Salesman.png|thumb|250px|Talking to the Poison Salesman]]

Next, you need to gather info about the poison. There's a [[Poison Salesman|poison salesman]], who sells it inside of the pub west of the [[bank]] in [[Seers' Village]]. Ask him to whom he sold the poison, and he'll tell you that everyone at the mansion bought some.

Go back to the house and ask the person who had the fingerprints on the criminal's dagger to find out what the poison was used on. Search the item they mention, detailed here:

*Anna - [[Sinclair family compost heap]]
*Bob - [[Sinclair family beehive]] in cow pen
*Carol - [[Sinclair mansion drain]], west of the front door
*David - [[Spiders' nest]], upstairs between the two rooms with three beds each in them
*Elizabeth - [[Sinclair family fountain]]
*Frank - [[Sinclair family crest]], east of the front door

You'll find that the subject was lying and didn't use their poison on what they had said they did.

:'''Note:''' If you wish to keep the silver necklace as a souvenir, drop it before talking to the guard (banking will not work).

Go back and talk to a guard and tell him you know who did it. Use the fingerprints of the person that did it on the unknown fingerprint. Show him the fingerprints, tell him about the poison, and show him the thread from the windowsill, since its colour will be a match to an article of the culprit's clothing. Case closed!

'''Congratulations, quest complete!'''
"""
