quest = "Shades of Mort'ton"
step_count = 4

[[steps]]
index = 0
name = "Starting the quest"
links = ["Diary (Shades of Mort'ton)", "smashed table (Mort'ton)", "Tarromin", "Rogue's purse", "Zogre Flesh Eaters"]
text = """
[[File:Diary (Shades of Mort'ton) detail.png|left|70px]]
Head to the most south-western house in Mort'ton and search the shelf on the wall to find a [[Diary (Shades of Mort'ton)|book]]. '''You should also search the [[smashed table (Mort'ton)|smashed table]], as it contains two [[Tarromin]] and [[Rogue's purse]].''' The Tarromin will allow you to create additional potions later on, and you may save the Rogue's purse if you plan to do [[Zogre Flesh Eaters]]. This building also contains a vial spawn in case you didn't bring vials of water with you. You can fill the vials in the sink in the easternmost building.
"""

[[steps]]
index = 1
name = "Serum 207 and killing shades"
links = ["coins", "tarromin potion (unf)", "tarromin", "vials of water", "ashes", "food", "armour", "weapon", "Serum 207", "vial of water", "Grand Exchange", "Razmire Keelgan", "general store", "Loar Shade", "Loar remains", "Ulsquire Shauncy", "olive oil", "timber beam", "limestone brick", "swamp paste", "shade remains", "Flamtaer"]
text = """
{{Needed|1000+ [[coins]], 2 [[tarromin potion (unf)]] (or 2 [[tarromin]] and 2 [[vials of water]]), 2 [[ashes]], [[food]], [[armour]], and a [[weapon]]|skills={{SCP|Herblore|15}} {{Boostable|yes}} to create [[Serum 207]]}}
[[File:Serum 207 (4) detail.png|left|70px]]
Reading the book will now allow you to create [[Serum 207]], a potion which may be used on the afflicted in town to '''temporarily''' interact with them. If you don't already have a [[tarromin potion (unf)]], use [[tarromin]] on a [[vial of water]] ({{SCP|Herblore|12}}). Use [[ashes]] on the unfinished potion to create the Serum (also complete your second potion) ({{SCP|Herblore|15}}).

:'''Note''': Serum 207 can be bought on the [[Grand Exchange]], but you must make at least one yourself for the purpose of this quest.

[[File:Razmire General Store..png|thumb|250px]]

Use the Serum on [[Razmire Keelgan]] in the [[general store]]. Ask him what all these shadowy creatures are, and he will tell you they are restless spirits of the dead. He asks you to kill 5 [[Loar Shade]]s (the level 40 green shadows) and collect their [[Loar remains|remains]] so that he may do some experiments on them.

:'''Note''': The kills will only count after Razmire has asked you to kill them, and you must collect the remains via killing them.

{{mes|That's all five Shades!}} will appear in the chat when you are done. Return to Razmire and use the Serum 207 on Razmire again, and he will take two of the shade remains from you. He then mentions that [[Ulsquire Shauncy]] might also be interested in seeing some shade remains.

Before heading to Ulsquire, open the general store through Razmire and buy some [[olive oil]]. Then ask him to open the builders store, and buy 1-2 [[timber beam]], 1-2 [[limestone brick]], and 10-20 [[swamp paste]].

:'''Note''': The supplies may be much more expensive on World 377 (the official Shades of Mor'ton minigame world) due to players buying them up, so consider switching worlds temporarily before buying them.

Ulsquire can be found in the house right next to Razmire to the south-east. Give him a dose of Serum 207, and then one of your [[shade remains]]. Talk to him again, and ask what he found out from the remains. Ulsquire believes that the tormented spirits should be put to rest, and jokes about rebuilding the nearby [[Flamtaer|temple]] and experimenting with the sacred flame. Next, ask him what he can tell you about the temple. He will suggest that to rebuild it, you will need the items you have just bought from Razmire. {{Chat option|1What did you find out about the remains?|2What can you tell me about that temple?}}

:'''Note''': Make sure you complete the dialogue options with Ulsquire, or interacting with the temple will result in the message {{Mes|You're not quite sure how to fix this}}.
"""

[[steps]]
index = 2
name = "Repairing the Temple"
links = ["Hammer", "Flamtaer hammer", "food", "armour", "Weapons", "tinderbox", "logs", "axe", "loar remains", "olive oil", "Serum 207", "limestone brick", "timber beam", "swamp paste", "Flamtaer bracelet", "serum 208", "Shades of Mort'ton (minigame)", "Loar Shade", "sacred oil", "Loar Shades", "Serum 208", "Razmire", "Ulsquire", "afflicted", "Serum_208"]
text = """
{{Main|Shades of Mort'ton (minigame)}}
{{needed|[[Hammer]] or [[Flamtaer hammer]], [[food]], [[armour]], [[Weapons|weapon]], [[tinderbox]], [[logs]] or [[axe]], [[loar remains]], [[olive oil]], and 1+ [[Serum 207|doses of Serum 207]] (2+ recommended). Building materials: multiples of [[limestone brick]], [[timber beam]], 5 [[swamp paste]]|recommended=1-2 [[Flamtaer bracelet]]s are recommended|skills={{SCP|Crafting|20}} {{Boostable|yes}} to repair the temple walls, {{SCP|Herblore|15}} {{Boostable|yes}} if choosing to create [[serum 208]]}}
 [[File:Flaming Fire altar.png|left|70px]]
[[File:Flamtaer.png|thumb|250px|The Flamtaer temple when fully repaired with the fire altar lit.]]
Now, you must help rebuild the temple located on a small island north-east of the general store, in order to create the sacred oil needed for a pyre funeral.

This section of the quest serves as a short introduction to the Shades of Mort'ton [[Shades of Mort'ton (minigame)|minigame]]. It is possible to complete this solo if using several [[Flamtaer bracelet]]'s along with the [[Flamtaer hammer]], but you may consider using the official World 377 dedicated to this minigame to find other players also rebuilding the temple, as this will make the process '''significantly faster'''.

In this minigame, players work together to rebuild the temple while under attack from [[Loar Shade]]s. To complete this quest, rebuild the walls around the temple using your hammer and build materials ({{SCP|Crafting|20}}). The [[Flamtaer hammer]] and [[Flamtaer bracelet]] make this process approximately 75% faster (the bracelet degrades after 80 uses). Once fully rebuilt, ignite the flame and then use the [[olive oil]] on it to create [[sacred oil]], provided you have at least 10% Sanctity. Sanctity is earned by your contribution towards repairing or reinforcing the walls, or by killing [[Loar Shades]] (only recommended for high combat levels).

:'''Note''': Once you have your sacred oil, it is optional but '''highly recommended''' to use your remaining [[Serum 207]] on the flame with at least 20% Sanctity, to create [[Serum 208]] ({{SCP|Herblore|15}}). This will permanently cure [[Razmire]] and [[Ulsquire]], making them permanently available for dialogue and trade. It may also be used on other [[afflicted]] citizens for a small [[Serum_208#Cure_rewards|reward]].
"""

[[steps]]
index = 3
name = "Burning a Shade"
links = ["Sacred oil", "logs", "axe", "loar remains", "tinderbox", "dead tree", "pyre logs", "Loar remains"]
text = """
[[File:Shades of Mort'ton - Burning shade remains.gif|thumb|right|250px||The Shade spirit is now free!]]
{{Needed|[[Sacred oil]], [[logs]] or [[axe]], [[loar remains]], [[tinderbox]]|skills={{SCP|Firemaking|5}} {{Boostable|yes}} to use pyre logs on the funeral pyre}}

If you do not yet have logs, cut down a nearby [[dead tree]]. Use your sacred oil on the [[logs]] to receive a [[pyre logs|pyre log]]. Then, head over to one of the funeral pyres, which are the brown patches on the map west of the General Store. Use the pyre logs on the funeral pyre, followed by the [[Loar remains]]. Light this and you will see a spirit rise from the pyre. ({{SCP|Firemaking|5}})

Collect your reward from the stone pillar next to the pyre and head back to Ulsquire. Speak with him to prompt the end of the quest (use a serum if he has reverted to being afflicted).

'''Congratulations, quest complete!'''
{{clear}}
"""
