quest = "The Eyes of Glouphrie"
step_count = 4

[[steps]]
index = 0
name = "Starting out"
links = ["Brimstail's cave", "Spirit Tree", "Tree Gnome Stronghold", "Brimstail", "singing bowl", "machine panel", "Oaknock's exchanger", "Oaknock's Machine", "Hazelmere", "Yanille", "fairy ring", "Watchtower Teleport", "Nightmare Zone", "minigame teleport"]
text = """
{{Map|x=2402|y=3419|r=4|mtype=square|caption=[[Brimstail's cave]] entrance.|align=right|width=250|height=250}}
[[File:Brimstail chathead.png|left]]
Head south-west from the [[Spirit Tree]] in [[Tree Gnome Stronghold]] until you see a dungeon entrance marker near the edge of a small lake. Enter the cave, and speak to [[Brimstail]]. Ask him about the cute creature wandering around, and then agree to let him tell you about his research. He will offer to tell you some history - agree and say that you love a bit of history (the second option does not work to skip the dialogue). You will then be given the option to start the quest.

Brimstail will ask you to go into the next room and look at it carefully.  First, ''Inspect'' the [[singing bowl]] set in the centre of the cave and surrounded by a black circular pothole. Next, ''Inspect'' the [[machine panel]] next to [[Oaknock's exchanger]]. Then, ''Unlock'' [[Oaknock's Machine]]. After completing these three actions, '''in that order''', talk to Brimstail again.

Talk to Brimstail again, and he will tell you to go and talk to [[Hazelmere]]. '''Fully finish the dialogue or Hazelmere will not be understood later on.''' Hazelmere is located on the island chain east of [[Yanille]], there is also a [[fairy ring]] directly beside his hut code {{Fairycode|CLS}}. You can also use the [[Watchtower Teleport]] spell and run east. Another way to reach him is by using the [[Nightmare Zone]] [[minigame teleport]] and running south-east.
"""

[[steps]]
index = 1
name = "Memories"
links = ["Hazelmere", "Yanille", "Magic", "cutscene", "gnomes", "goblin", "King Healthorg", "Oaknock", "Glouphrie", "Argento", "Gnome Stronghold", "violet pentagon"]
text = """
Speak to [[Hazelmere]], located east of [[Yanille]]. There's a long conversation, and he will get inside your mind where you can now talk to him. This requires 46 [[Magic]] and '''cannot''' be boosted. A long [[cutscene]] will follow showing the battle between the [[gnomes]] and [[goblin]]s, with [[King Healthorg]], [[Oaknock]], [[Glouphrie]] and Hazelmere fighting alongside. Glouphrie uses his magic to scare away the goblins, and later uses his magic to cover up [[Argento]]'s death. Oaknock then builds a machine that reverses Glouphrie's magic, revealing that Argento is actually dead to the King. The King, unable to trust Glouphrie, banishes him from the [[Gnome Stronghold|Stronghold]], which Glouphrie isn't happy about. Hazelmere will then give you a [[violet pentagon]] for the machine.

<gallery captionalign="center" widths="180">
File:The Eyes of Glouphrie - Hazelmere enters player's mind.png|Hazelmere gets inside your mind.
File:The Eyes of Glouphrie - gnome battalion.png|Gnomes and Goblins battle.
File:The Eyes of Glouphrie - gnome army council.png|King Healthorg (top), Oaknock (left), Glouphrie (front), and Hazelmere (right) are seen on the battlefield.
File:The Eyes of Glouphrie - Glouphrie's grand illusion.png|Glouphrie summons holograph tortoises to fool Goblins.
File:The Eyes of Glouphrie - Argento dies.png|Argento is dead!
File:The Eyes of Glouphrie - Argento convention.png|Oaknock summons the King and his advisors.
</gallery>
"""

[[steps]]
index = 2
name = "Sabotage"
links = ["Brimstail", "cutscene", "Intruder", "mud rune", "pestle and mortar", "bucket of sap", "magic glue", "maple logs", "oak logs", "hammer", "saw", "Machine panel", "Oaknock the Engineer"]
text = """
[[File:The Eyes of Glouphrie - sabotage.png|thumb|left|Someone sneaks in during the conversation with Brimstail...]]
Go back and speak to [[Brimstail]] where you will see a shorter [[cutscene]] in which an [[Intruder|invisible gnome]] will sabotage the machine you examined earlier.

[[File:The Eyes of Glouphrie - Oaknock's damaged machine.png|thumb|right|You'll need to repair this]]
Crush your [[mud rune]] with the [[pestle and mortar]], and then use it on the [[bucket of sap]] to create [[magic glue]]. Repair the machine using your [[maple logs]], [[oak logs]] and the glue. You will need to have a [[hammer]] and a [[saw]] in your inventory.

If you did not bring a [[bucket of sap]] ahead of time, there is a tree just north of Brimstail's cave, between two Oak trees, that you can extract sap from. Use a knife on it with a bucket in your inventory to extract the sap.

Now, you will have to unlock and restart the machine. For this, you will need more crystal discs—talk to Brimstail to get some from him. You can talk to him multiple times to get more shapes. If you can no longer get discs from Brimstail, drop the discs and talk to him again to get more discs. '''Alternatively, you can exchange the discs at the exchanger next to the machine.'''

To work this machine, you have to fit crystal discs to the numbers shown. The numbers will be different for everybody; therefore, you have to solve this mostly yourself. This is how it works:

To the west side is a [[Machine panel|chart]] showing the values of each colour.

{{Colour-shape value|align=right}}
The crystal is equal to:
*Red: 1
*Orange: 2
*Yellow: 3
*Green: 4
*Blue: 5
*Indigo: 6
*Violet: 7

This value is multiplied by the number of sides each crystal has:
*Circle has 1 side.
*Triangle has 3 sides.
*Square has 4 sides.
*Pentagon has 5 sides.

*Example 1: a 4 can be a red square or a green circle (1 * 4)
*Example 2: a 7 can only be a violet circle (7 * 1)
*Example 3: a 12 can be a green triangle or a yellow square (4 * 3)

Some of the colours can be easily mixed up, since they are very similar (e.g. blue, indigo, and violet). Hover them with your mouse to be sure.

The yellow circle can '''never''' be obtained. If the puzzle requires a value of three, you must use the red triangle instead. Brimstail cannot directly give you any circles, or red coloured shapes. If you need the lower value shapes the exchanger must be used.

There is a token exchanger on the right-hand side, which allows you to insert various tokens and change them for others of the same value. <u>You cannot exchange more than 35 points worth at a time</u>, but you may exchange a single token for many other lower valued tokens if its value is high enough. You will always receive the same value back, in different tokens. For example, if you need an indigo pentagon (30), and have a violet pentagon (35). Put the violet pentagon into the exchanger, and keep declining the transaction until the machine offers you an indigo pentagon (30) and a red pentagon (5).

[[File:The Eyes of Glouphrie - token exchanger interface.png|thumb|right|Token exchanger]]

To ''unlock'' the machine, you have to create a single disc worth the number of points shown on [[Oaknock the Engineer|Oaknock's]] machine. The numbers are different for everyone. As a general strategy, try and get the smaller numbers and it's easier. Any violet pentagons or similar if not needed may be exchanged for ones of a lower value using the Oaknock's exchanger.

Once unlocked, you need to ''restart'' the machine. For this, you will need to fit '''six''' separate tokens to three different numbers (1 for the first number, 2 for the second and 3 for the third). Be patient—it can take a while to get all the tokens that you need. '''You may speak to Brimstail to get more tokens which may make getting the ones you want easier; it is possible to solve the puzzle by continuously asking for and dropping coins until you get the ones you need.'''

[[File:The Eyes of Glouphrie - solved puzzle.png|140px|left|Successfully restarting the machine]]
An example of a completed machine. '''Note: You must fill all slots to unlock the machine!''' In this example, using two violet triangles turned the light green, but still did not work. If this happens, you can just use the exchanger to turn it into two pieces, since the total points stay the same.
"""

[[steps]]
index = 3
name = "Assassination"
links = ["Brimstail", "cute creature", "evil creature", "King Narnode", "Hitpoint", "Ranged", "mage", "Grand Tree", "tortoise", "Spirit Tree", "Gnome Stronghold", "Evil creature", "Tree Gnome Stronghold"]
text = """
Once you have unlocked the machine, speak to [[Brimstail]] again. The once [[cute creature]]s are revealed to be [[evil creature]]s. After the cut-scene, talk to Brimstail and he will tell you to speak to [[King Narnode]].
[[File:The Eyes of Glouphrie - Izzie's true appearance.png|thumb|Brimstail, shocked by Izzie's true appearance!]]

There are six creatures in total, and they have 1 [[Hitpoint]] each.
{{checklist|
* 1 - One by Brimstail (he may kill it for you).
* 2 - One by [[King Narnode]]. (You may need to [[Ranged|range]] or [[mage]] this one, as it can get stuck behind the trapdoor.)
* 3 - One at the top of the [[Grand Tree]], by the prison. (Do not climb down the ladders immediately after killing the creature—it will not count as a kill.)
* 4 - One by the giant [[tortoise]]s in the pen north-west of the [[Grand Tree]] (north of the toad swamp).
* 5 - One by the Gnome Stronghold [[Spirit Tree]].
* 6 - One by the entrance to the [[Gnome Stronghold]]. Go south from the Grand Tree, down the ramp and keep walking to the main entrance of the Stronghold.
}}
'''Note:''' If Brimstail kills the evil creature, or if you mess up a creature kill count at any time, the last [[Evil creature|Evil Creature]] will spawn at the entrance to [[Tree Gnome Stronghold|Gnome Stronghold]].

Talk to King Narnode, and he will reward you.

'''Congratulations, quest complete!'''
"""
