quest = "Scrambled!"
step_count = 6

[[steps]]
index = 0
name = "Humphrey Dumphrey Sat On A Wall"
links = ["Tal Teok", "Tal Teklan", "Alan (Scrambled!)", "Humphrey Dumphrey", "King (Tal Teklan)", "The King's Inn"]
text = """
[[File:Scrambled! - a great fall.png|thumb|250px|Oh <nowiki>********</nowiki>, Mumpty Rumpty had a great fall.]]
Head to the temple of [[Tal Teok]], just north of [[Tal Teklan]]. You will find a tourist named [[Alan (Scrambled!)|Alan]], alongside his egg-shaped friend [[Humphrey Dumphrey|Humpy Plumpy]], who has chosen to occupy the temple as a squatter. He will ask that you stay as a guest and insists he prepare a feast, and requests you to look after Wumty Scrumpty while he gathers the food.

As soon as he leaves however, gravity claims the life of Hampty and results in a great fall. Inspect Gumty on the ground, which prompts you to head back to Tal Teklan to look for help. Talking to any citizen there will direct you to [[King (Tal Teklan)|King]], the local bartender for [[The King's Inn]].
"""

[[steps]]
index = 1
name = "All the King's Men"
links = []
text = """
Speak to King located in the inn about your predicament. She will tell you that she has to stay and man the bar, but has capable men who are up to the task. She will direct you to three people.
"""

[[steps]]
index = 2
name = "=Acatzin="
links = ["Acatzin", "Blacksmith (Tal Teklan)", "Acatzin's axe"]
text = """
[[Acatzin]] is also in the inn. He will help you as soon as he gets his axe back from the [[Blacksmith (Tal Teklan)|blacksmith]]. Head south-west to the furnace and speak to the blacksmith, who will tell you that his whetstone has broken and needs repairing.

Take the hammer nearby and repair the whetstone. He will then give you [[Acatzin's axe]] (not knowing that's his) and ask you to repair it instead. Repair the axe on the whetstone then return to Acatzin and he will be on his merry way to Tal Teok.

Before leaving, take the empty bowl on the table.
"""

[[steps]]
index = 3
name = "=Nezketi="
links = ["Nezketi", "damiana leaves", "Damiana", "plank", "bowl of water", "The King's Inn", "Tal Teklan General Store", "damiana water", "damiana tea"]
text = """
[[Nezketi]] is found at the temple directly south of the inn. In order to help you, he will need to be on top of his game - he will need tea made from [[damiana leaves]]. Agree to get his tea, and he will give you an empty cup.

[[Damiana]] can be found directly outside of the south-eastern walls of Tal Teklan. While you are there, head a bit further south-west and pick up the two [[plank]]s.

Acquire a [[bowl of water]]; if you didn't take a bowl earlier, pick it up on a table in [[The King's Inn]]. A fountain is right outside to fill the bowl. Use the [[damiana leaves]] on the bowl of water, then head into the [[Tal Teklan General Store]] just south of the bank, and use the bowl on the oven to boil the [[damiana water]]. Finally, use the bowl of tea on the empty cup to finally create [[damiana tea]].

Head back to the temple and talk to Nezketi, who you will automatically give the tea to. Freshly energised, he will depart for the temple immediately after.
"""

[[steps]]
index = 4
name = "=Kauayotl="
links = ["Kauayotl", "Blacksmith (Tal Teklan)", "iron nails", "Arcuani's Archery Supplies"]
text = """
[[File:Scrambled! - repairing racing cart.png|thumb|250px|Repairing Kauayotl's racing cart.]]
From the temple, head directly east to the eastern entrance of Tal Teklan, where you will find [[Kauayotl]] with a damaged cart. In order to help you, he will first need to sort out his racing cart. Offer to help repair it, and he will tell you what you'll need:
* Two planks - if you did not pick up two planks earlier, there are two spawns south of the city.
* Nails - search the [[Blacksmith (Tal Teklan)|blacksmith's]] workbench for 20 [[iron nails]].
* Hammer - spawns on the table south-west of the workbench
* Saw - spawns on a table in [[Arcuani's Archery Supplies]] just south of the blacksmith.

Return to Kauayotl, repair the damaged cart, and speak to him again to have him on his way to the temple.
"""

[[steps]]
index = 5
name = "Putting Humphrey together again"
links = ["large chicken", "large egg", "Dragon Nest", "Red dragon (Scrambled!)", "Dragon egg (Scrambled!)", "Black jaguar (Scrambled!)", "jaguar egg", "Alan's bones", "bonecrusher", "bonecrusher necklace"]
text = """
Head back north to Tal Teok and speak to any of the three men. It quickly becomes apparent that all of King's men couldn't put Pumpty Lumpty together again, and that replacing him is the only option. However, the three argue over which type of egg is suitable: a large chicken's, a dragon's, or a... jaguar's. You will offer to get all three and have them pick a suitable one.

Head to the small chicken farm directly south of the Tal Teok temple in the north of Tal Teklan, and search the pile of eggs. A level-16 [[large chicken]] will attack; defeat it, then search the eggs again to obtain a [[large egg]].
[[File:Scrambled! - red dragon safespot.png|thumb|250px|Safespotting the red dragon using their own eggs.]]
The entrance to the [[Dragon Nest]] is found to the south-east of Tal Teok temple, across the river. Once inside, make your way to the south-east and search the pile of eggs. A level-106 [[Red dragon (Scrambled!)|red dragon]] will attack. Players can safespot the dragon using the eggs; defeat it, then search the eggs again to obtain a [[Dragon egg (Scrambled!)|dragon egg]].

Head back outside, and run eastwards until you reach a campsite. Search the pile of eggs, and a level-88 [[Black jaguar (Scrambled!)|black jaguar]] will attack; as it has routefinding capabilities, you will have to trick the jaguar by standing next to tropical tree and a fern to safespot it. After triumphing over the egglaying jaguar search the eggs again to obtain a [[jaguar egg]].
[[File:Scrambled! - egg piecing solution.png|thumb|250px|The nearly-reassembled Lumpty Mumpty.]]
Return to Tal Teok and speak to each of King's men, who will each paint the egg to resemble Rumpty Bumpty as best they can. Once all three eggs have been given, a cutscene will play in which the eggs are judged. The chicken egg is deemed too small to be Wumty Scrumpty, the dragon egg's innate heat is melting the paint, and the jaguar egg is deemed to be the best replacement for Mumpty Rumpty.

However, gravity is a cruel mistress and claims the lives of all the eggs, resulting in three additional great falls. With no options left, you and King's men must put Humphrey Dumphrey together again.

There are many pieces to reassemble, but players can hover over the puzzle piece icon to view the solution. When a piece is rotated in the correct orientation and placed in the correct location, it will stay in place indicating the correct placement.

Upon putting Scrumpty Lumpy back together again, a cutscene will play in which you thank King's men before they take their leave, and Alan returns none the wiser. As you head down to help him bring in the food, he reflects on his life, finally sure of himself and his place in the world. However, gravity is apparently out for blood, giving Alan a great fall.

'''Note:''' Players who wish to keep [[Alan's bones]] as a souvenir should ensure they do not have a [[bonecrusher]] or [[bonecrusher necklace]] on their person before fixing Bumpty Numpty, as the bonecrusher deems the player responsible for his death and will automatically crush his bones.

<gallery captionalign="center" heights="200" widths="300">
File:Scrambled! - judging eggs.png|The player and King's men judging their eggs.
File:Scrambled! - three great falls.png|Gravity causes several great falls.
File:Scrambled! - Alan's great fall.webm|Alan has a great fall.
</gallery>

'''Congratulations, quest complete!'''
"""
