quest = "The Path of Glouphrie"
step_count = 5

[[steps]]
index = 0
name = "The King's Little Dumpling"
links = ["Tree Gnome Village (location)", "spirit tree", "King Bolren", "cute creature", "Glouphrie", "evil creature", "Yewnock", "Oaknock the Engineer", "Tree Gnome Village Dungeon", "Golrie", "Key (Tree Gnome Village Dungeon)", "Bolrie", "monolith", "Chest (The Path of Glouphrie, wood)", "Chest (The Path of Glouphrie, silver)", "Chest key (The Path of Glouphrie)", "Yewnock's notes", "Chest (The Path of Glouphrie, gold)", "strongroom key", "crystal chime seed", "singing bowl", "crystal chime"]
text = """
{{Needed|recommended=10-14 free inventory spaces to make room for crystalline disks.}}
[[File:King Bolren chathead.png|left]]
Make your way to the [[Tree Gnome Village (location)|Tree Gnome Village]]; the quickest way to reach it is by [[spirit tree]]. Once there, talk to [[King Bolren]] and you'll notice that he has acquired another [[cute creature]], who he's affectionally named "Dumpling". Recognising it as one of [[Glouphrie]]'s [[evil creature]]s in disguise, you will attempt to warn him about its true nature; as usual, however, Bolren will refuse to believe you without sufficient evidence.

Bolren will mention [[Yewnock]], the son of [[Oaknock the Engineer]], who used to visit the village and brought some unusual objects with him. The objects will remind you of Oaknock's machine, and Bolren will recommend you look underground for a local gnome who might know something about an anti-illusion machine.
[[File:Path of Glouphrie puzzle path w-disks.png|alt=Path of push box puzzle|thumb|width=300x300|The path for the monoliths puzzle.]]
Head down to the [[Tree Gnome Village Dungeon]] by squeezing through the loose railing to the south-west and then running east to the dungeon ladder. In the western area of the cave, speak to [[Golrie]] and ask him about a device; if you have not freed him, you will need a [[Key (Tree Gnome Village Dungeon)|key]] to unlock the room he is in, which can be found in the eastern storeroom (inside the crate that looks different than the others).

Golrie will tell you that his grandfather, [[Bolrie]], used to travel the world collecting elven artefacts and bringing them back to the village, often stashing them in the storeroom nearby. He will tell you that the storeroom is found in the eastern area of the cave, past the tunnel entrance, and that the storeroom's gated strongroom will require a key to enter.

Head to the storeroom by entering the tunnel in the easternmost part of the dungeon, and you will find multiple [[monolith]]s in your way. Push the first monolith north, then search the nearby [[Chest (The Path of Glouphrie, wood)|chest]] for some familiar discs. Next, you will see another four monoliths; push the south-west one north, then the north-west one east. Search the wood chest for more discs, and the silver [[Chest (The Path of Glouphrie, silver)|chest]] for a [[Chest key (The Path of Glouphrie)|chest key]] and [[Yewnock's notes]]. ''You do not need to read the notes, but they will give further lore.''

Push the small monolith south and the north-west monolith west to access the gold [[Chest (The Path of Glouphrie, gold)|chest]], which contains the [[strongroom key]] Golrie mentioned earlier, as well as a [[crystal chime seed]]. Next, inspect the nearby [[singing bowl]] to create the [[crystal chime]], which is needed later in the quest.
"""

[[steps]]
index = 1
name = "Yewnock's Legacy"
links = ["strongroom key", "Yewnock's machine", "King Bolrie", "advisor", "King Healthorg", "General Khazard", "Argenthorg", "Yewnock", "Oaknock the Engineer", "Glouphrie the Untrusted"]
text = """
[[File:Argenthorg chathead.png|left|frameless]]
Push the south-east monolith west, then use the [[strongroom key]] on the gate to the west to enter a room with a lectern and [[Yewnock's machine]]. The lectern contains a diary belonging to [[King Bolrie]], who formerly ruled the village; all three chapters will trigger cutscenes, which must be watched to move to the next step in the quest.

The cutscenes will show an [[advisor]] to King Bolrie, who is tired of the aging [[King Healthorg]]'s inaction against the army of [[General Khazard]]. The advisor suggests to Bolrie that he should campaign to replace the king of the Tree Gnome Stronghold; his opponent [[Argenthorg]], the crown prince, will be "revealed" to care more about humans than gnomes, giving the election to Bolrie. However, sensing foul play, Argenthorg will call upon [[Yewnock]] (son of [[Oaknock the Engineer]]) to activate an anti-illusion machine and expose the advisor as [[Glouphrie the Untrusted]]. Having been tricked, Bolrie is forced to stand down as a candidate to the throne and leave the Tree Gnome Stronghold, as well as abdicate the throne of the Tree Gnome Village.<gallery captionalign="center" widths="200">
The Path of Glouphrie - Bolrie's Diary chapter 1.png|King Bolrie, frustrated at King Healthorg's inaction.
The Path of Glouphrie - Bolrie's Diary chapter 2.png|Campaign posters for the election to become king of the Tree Gnome Stronghold.
The Path of Glouphrie - Bolrie's Diary chapter 3 saboteur.png|A saboteur creates illusions of human food.
The Path of Glouphrie - Bolrie's Diary chapter 3 accused.png|Argenthorg, suspicious of the ruse, gets Yewnock to activate his anti-illusion machine.
The Path of Glouphrie - Bolrie's Diary chapter 3 exposed.png|King Bolrie's advisor is exposed as Glouphrie.
</gallery>{{Colour-shape value|align=right}}
"""

[[steps]]
index = 2
name = "=The Machine="
links = ["Yewnock's machine", "Oaknock's Machine", "Yewnock's exchanger", "Longramble", "Arposandra", "Gianne jnr.", "spirit tree", "Grand Tree", "tangled toad's legs", "mint cake"]
text = """
[[Yewnock's machine]] is similar to [[Oaknock's Machine]] in that players must solve a disc-based puzzle. This time, instead of being given a number you are given the value of the disc(s) to match. In the machine interface, the value of the discs '''inserted on the left''' need to '''add up to the same total value of the one(s) on the right'''. Use the table to calculate the total value of the disc(s) to match, and then solve as before. You will need to match two different values; first, a single shape that adds up to the value of the two displayed at the top, and second, two shapes that add up to the value of the single shape shown on the bottom.

[[Yewnock's exchanger]], located directly next to Yewnock's machine, can be used by first inserting higher valued discs in exchange for multiple lower valued ones, or by combining two smaller discs into a bigger disc. The total value of the input and output will be the same. To operate the machine, click the desired disc in the inventory and then click the disc slot on the machine interface. Then click the double arrows between the two sides to view what will be exchanged. Note that the exchange has three tiers; exchanging a disc in the second slot will exchange for two shapes, and so on.

''Any items left on the ground will disappear following the cutscene.''

Once the machine puzzle is successfully solved, a brief cutscene will play where Dumpling is revealed to be an evil creature. Head back up to the village and kill the evil creature, then talk to King Bolren. He will tell you of a gnome explorer named [[Longramble]], who went in search of the lost city, [[Arposandra]]. Though no one knows of his current whereabouts, King Bolren suggests asking [[Gianne jnr.|Aluft Gianne jnr.]] at the Grand Tree for help.

Use the [[spirit tree]] and travel to the [[Grand Tree]]. Bank all unnecessary items (you may safely drop the shapes) and stock up on food and armour. If you're going to trade a [[tangled toad's legs]] for the [[mint cake]] (optional, but highly recommended as the tangled toad's legs is worth {{Coins|{{GEP|tangled toad's legs}}}} and a mint cake is worth {{Coins|{{GEP|mint cake}}}}), be sure to bring it along.<gallery captionalign="center" widths="400" perrow="2">
File:The Path of Glouphrie - Yewnock's machine interface.png|Operating Yewnock's machine
File:The Path of Glouphrie - Yewnock's machine exchanger.png|Operating Yewnock's exchanger
</gallery>
"""

[[steps]]
index = 3
name = "Arbor Incomitata"
links = ["crossbow", "mith grapple", "crystal chime", "Tangled toad's legs", "mint cake", "Gianne jnr.", "tangled toads' legs", "Galarpos Mountains", "Poison Waste", "fairy ring", "Castle Wars", "ring of dueling", "Longramble", "Spirit Tree (Incomitatus)", "Anima Mundi", "Hazelmere"]
text = """
{{Needed|A [[crossbow]] and [[mith grapple]], [[crystal chime]], combat equipment.|recommended=[[Tangled toad's legs]] to receive a [[mint cake]]}}
[[File:Longramble chathead.png|left|frameless]]
[[File:The Path of Glouphrie - grappling to Longramble.png|thumb|300px|The player grapples toward Longramble's coordinates.]]
[[File:The Path of Glouphrie - Incomitatus is healed.png|thumb|300px|Incomitatus is healed to perfect health.]]
Make your way to the Grand Tree, and climb up the ladder once. In the north-west corner, speak to  [[Gianne jnr.]] to learn about Longramble's whereabouts. He will tell you that gnomes have been trying to deliver a dish of [[tangled toads' legs]] to him, but have not been able to reach him. He tells you the coordinates of the delivery is at 2 degrees 7 minutes south and 3 degrees 7 minutes west.

These coordinates will point toward the [[Galarpos Mountains]], just east of the [[Poison Waste]]. The quickest way to travel there is by using the [[fairy ring]] code {{Fairycode|bkp}} and then running north-west; An alternative way to get there is by teleporting to [[Castle Wars]] via [[ring of dueling]], then heading south-west alongside the river. Equip a [[crossbow]] and [[mith grapple]], and cross to the mountain side via the tree in the middle of the river.

Speak to [[Longramble]], who believes Arposandra is close to the Poison Waste. If you brought a tangled toad's legs, he will automatically take it. After going through the dialogue, head further north, and you will feel a strange voice calling to you; this is the [[Spirit Tree (Incomitatus)|spirit tree]] nearby calling you, who tells you to call it [[Spirit Tree (Incomitatus)|Incomitatus]]. The tree's connection to the [[Anima Mundi]], the life force of the world, has been lost due to the toxic waste nearby corrupting its roots, and thus it has fallen ill.

You will mention that how Incomitatus speaks to you through the mind is reminiscent of [[Hazelmere]]'s, and will unintentionally contact him through Incomitatus as the conduit. He will sense that it is unwell, and conclude that the poison seeping into the soil is a byproduct of powerful magic having separated the Anima Mundi from its source. Hazelmere will suggest that healing the tree requires a spiritual cleansing by way of elven magic; he will then notice that you have a set of chimes that can purify it, and ask that you use it on the tree. This will heal Incomitatus, and connects it with the rest of the spirit trees. From this point forward, players can use the tree as a teleport option.
"""

[[steps]]
index = 4
name = "The Warped Depths"
links = ["Warped Tortoise", "earmuffs", "Protect from Missiles", "Warped Terrorbird", "aggressive", "Earmuffs", "slayer helmet", "run energy", "Crystal chime", "Terrorbird Guard 21", "Terrorbird Guard 72", "Hazelmere", "Argento", "Yanille Chain"]
text = """
[[File:Terrorbird Guard 21 chathead.png|left|frameless]]
Head west of the spirit tree, and then run south and enter the sewer entrance. You '''do not need''' to fight the [[Warped Tortoise]] at the entrance. ''Note that if you have not yet healed the spirit tree, warped tree roots will block your path after the second warped tortoise.'' [[File:Poison Waste dungeon map.png|thumb|A map of the Poison Waste Dungeon.]]

Once inside, you will need to run a considerable distance to the end of the dungeon; refer to the table below. It is recommended to wear a set of [[earmuffs]] '''''and''''' activate the [[Protect from Missiles]] prayer while traversing the dungeon, as this will negate almost all damage taken. Without ear protection, the [[Warped Terrorbird]]s inside will be able to '''hit through prayers''' with their ranged attacks.

There is a caged hallway at the half-way point where players are safe if they close the gate behind them. Players can also do so in the hallway just before entering the final area.

The level 121 [[Warped Tortoise]]s in the dungeon are not [[aggressive]], but the level 96 [[Warped Terrorbird]]s are, and they use frequent, highly accurate ranged attacks as well as a fairly accurate melee attack. [[Earmuffs]] or a [[slayer helmet]] will reduce the maximum hit of the ranged attacks, '''but the attacks will remain accurate''', so [[Protect from Missiles]] is recommended. Run past them, and avoid stepping on the tar on the ground, as it will turn off [[run energy]] and force you to walk, signaled by the game message {{Mes|You accidentally step in some sticky tar!|colour=red}}.

Head to the end of the dungeon, in a room with a pit in the centre that is connected to three other rooms. To reach the room from the entrance:
{| class="wikitable lighttable"
!Dungeon directions
|-
| Enter the sewer entrance.
|-
| Climb up the ladder.
|-
|Run all the way east.
|-
|Climb down the ladder.
|-
|Run north and climb up the ladder.
|-
|Run all the way west.
|-
|Enter the north room. Close the gates and rest here if needed.
|-
|Climb down the ladder in the northern side of the room.
|-
| Run slightly east and climb up the ladder.
|-
|Run north to the room with the pit.
|-
|Enter the east room and fight the terrorbirds.
|}
[[File:The Path of Glouphrie - warped terrorbird fight.png|thumb|300px|Using a pillar to minimise the amount of terrorbirds attacking.]]

The east room contains three [[Warped Terrorbird]]s that must be slain. The terrorbirds use both melee and ranged, and will path towards the player. You must be carrying the [[Crystal chime]] that you sang earlier to harm the birds.

Lower-levelled players can use the pillars around the room to stop the other terrorbirds from attacking. Standing at the door until the three terrorbirds approach you will allow you to engage only one at a time. They may also be poisoned, envenomed, and flinched by trapping them behind the pillars.  They are weakest to crush attacks, and their ranged defence is the strongest defensive stat, but their melee and magic defence is fairly low, and they can be quickly eliminated with any attack style.

You can also position yourself so that they're not in melee distance (note that they ''can'' melee at a diagonal, unlike most units) so that you only need to pray Ranged. If you are low on prayer and have made sure that all the birds are not in melee distance, you can conserve prayer by only turning it on every 15 ticks once you have successfully prayed against their ranged attack. This is every 5th attack with a shortbow on rapid or every 3rd attack with autocast. ''If you get hit'', they will immediately attack on the 3rd tick after the hit, so be prepared to reset your cycle!

After killing the Warped Terrorbirds, head towards the heavy door on the eastern side of the room to begin a cutscene showing two intelligent terrorbirds, [[Terrorbird Guard 21]] and [[Terrorbird Guard 72|72]], talking to each other. They will lament the boringness of the job, until they notice you and panic, pressing an alarm button that releases tar from the grills. You will try to run but become stuck in the tar, and toxic gases will begin to seep into the room, causing you to become hazy.

As you are about to blackout, [[Hazelmere]] will appear in the nick of time. He activates a special seed pod, the last gift given to him by [[Argento]], which surrounds the both of you with a large aura and teleports you both out to safety. Arriving at his house on the [[Yanille Chain]], he will impart upon you his vision of the future, a vision that heavily involves you and signifies much to come.

<gallery captionalign="center" widths="200">
The Path of Glouphrie - Terrorbird Guard panic.png|The Terrorbird Guards notice your presence.
The Path of Glouphrie - player trapped.png|You are tarred and gassed close to death.
The Path of Glouphrie - Hazelmere appears.png|Hazelmere arrives to rescue the player, activating a special seed pod.
</gallery>

'''Note :''' ''If there is not enough space in the inventory during completion, you can talk to [[Hazelmere]] again to receive the missing rewards. Destroyed lamps can be reclaimed from Hazelmere at any time.''

'''Congratulations, quest complete!'''
"""
