quest = "Tree Gnome Village"
step_count = 4

[[steps]]
index = 0
name = "Protecting the Spirit Tree"
links = ["Gnome Maze", "East Ardougne", "Yanille", "King Bolren"]
text = """
{{Map:Tree Gnome Village path}}
[[File:King Bolren chathead.png|left|frameless]]
Head to the centre of the [[Gnome Maze|Tree Gnome Maze]] (see the map to the right for the path through the maze). The maze is located south-east of [[East Ardougne]] and north of [[Yanille]]. Talk to [[King Bolren]], who will say that three orbs have been stolen by Khazard troops. Agree to help him, and you will be escorted by Elkoy out of the maze.
{{Clear|left}}
"""

[[steps]]
index = 1
name = "The three trackers"
links = ["Gnome maze", "battlefield", "Commander Montai", "logs", "ballista (Tree Gnome Village)", "Ballista (Tree Gnome Village)", "Catapult (Battlefield)"]
text = """
{{Needed|6 normal logs.}}
[[File:Commander Montai chathead.png|left|frameless]]
[[File:Tree Gnome Village - Tracker gnome locations.png|thumb|220px|Tracker locations.]]
North to the [[Gnome maze|maze]] you will find a [[battlefield]]. Find [[Commander Montai]] and speak with him, he is wearing red clothing. He will ask for you to bring him 6 [[logs]] to repair their defences. After giving him the logs, talk to [[Commander Montai]] again, and he'll tell you that three trackers that have been sent out to retrieve coordinates to fire the [[ballista (Tree Gnome Village)|ballista]] have not returned. He asks you to find them.

You can find all three tracker gnomes at the buildings north to the [[battlefield]]. (look at the picture to the right to see the locations)
{{Clear|left}}
*The first tracker is behind or on the side of the biggest building in the north-west.
*The second tracker is in the north-east building in a Khazard Prison Cell.
*The third tracker is roaming outside the south-west corner of the stronghold.

The first two trackers will give you the coordinates you need, which you'll automatically commit to memory. The third tracker, however, has been driven mad as a result of the chaos. Though most of what he says is garbage, he will give you a hint as to the number you need. You may have to do a bit of guesswork, though. For instance, ''"Less than my hands"'' would equal 1, where ''"More than my head less than my fingers"'' could be 2, ''"More than we but less than our feet"'' is 3, and lastly, ''"My legs and your legs"'' is 4. (It should not be any other possible number so try and remember what the third tracker said.)

Head back to the [[Ballista (Tree Gnome Village)|ballista]] (not the [[Catapult (Battlefield)|catapult]], which is next to Montai), which is located in the south-west corner of the battlefield, here you want to choose the coordinate given from the third gnome tracker. If you miss, just try again until you get it.
"""

[[steps]]
index = 2
name = "Retrieving the first orb"
links = ["Food", "armour", "Commander Montai", "Khazard commander", "Hitpoints", "safespot", "ladder", "orb of protection", "Elkoy", "King Bolren", "orbs of protection", "Khazard warlord"]
text = """
{{Needed|recommended=[[Food]] and [[armour]] for low levels}}
[[File:Orb of protection detail.png|left|80px]]
[[File:Tree Gnome Village - Crumbled wall.png|thumb|220px|The crumbled wall you can climb over.]]
Once you get a hit, talk to [[Commander Montai]] once again then walk north to the stronghold (building where Gnome Tracker 1 was) and climb over the crumbled wall.

'''Note:''' There is a stall after climbing the crumbled wall where you are attacked without being able to heal; as a low-levelled player, this may be dangerous.

Once you climb the wall you will be attacked by a level 48 [[Khazard commander]]; they have low [[Hitpoints]] (22) and should not be troublesome for most mid-levelled players (can be [[safespot]]ted behind northern broken chair). You can skip defeating the commander if you wish and proceed to the western room and climb up the ladder.

When you climb the [[ladder]] you will once again be attacked by a level 48 [[Khazard commander]], kill him or head to the chest and  find the [[orb of protection]]. When you have the orb, run back down the ladder and out of the nearby door.

Return to the north-west maze entrance and talk to [[Elkoy]], he will offer to lead you through the maze, accept his offer.

Talk to [[King Bolren]] in the centre of the maze and he will inform you that the other two [[orbs of protection]] have been stolen by the [[Khazard warlord|Khazard Warlord]].
"""

[[steps]]
index = 3
name = "Retrieving the last two orbs"
links = ["West Ardougne", "Khazard trooper", "Khazard warlord", "Rune armour", "rune scimitar", "food", "lobster", "safespot", "flinched", "orbs of protection"]
text = """
{{Needed|Combat equipment to defeat a level 112}}
[[File:Khazard warlord chathead.png|left|frameless]]
'''Note:''' The orbs will only be dropped by the Warlord after you've spoken to the King.

{{Map|name=Khazard warlord|2455,3301|r=4|mtype=square|caption=The location of the Khazard warlord.|align=right|width=220|height=220}}

Exit the village and start heading north past the stronghold where you found the first orb. When you hit the wall to [[West Ardougne]], follow it to the west past the wolves and then to the north until you see two [[Khazard trooper|Khazard troopers]] and the level 112  [[Khazard warlord]]. The warlord will be unaggressive until you talk with him, at which point he will challenge you to a fight and attack.

Kill him to retrieve the other two orbs. Players with [[Rune armour]] and at least a [[rune scimitar]] should have little trouble fighting him if they have a small amount of decent quality [[food]] ([[lobster]] or better), though the warlord has a rather large HP of 170.

[[File:Tree Gnome Village - Warlord safespot.png|thumb|left|220px|A player safespotting the Khazard warlord.]]

Lower levelled players may consider using Magic or Ranged to [[safespot]] him. After initiating the fight, head west until the warlord de-aggros near the larger dead tree. Move a little south and attack the warlord with Ranged or Magic while outside his aggro range. This will force the warlord to walk backwards at an angle and get caught against the West Ardougne wall and the northern large dead tree. If done correctly, players can attack the warlord safely as long as they keep distant enough as to not aggro the warlord again. If you fail to get the warlord stuck, you can also simply run away from him whenever he gets close, only attacking him while he is wandering back.

'''Note''': He may despawn if you take too long to kill him using this method.

He may also be [[flinched]] using melee by repeatedly stepping in and out of his walking range. One good spot is beside the large skull to the south. He does not despawn when flinched.

After killing him, pick up the [[orbs of protection]]. Go back to King Bolren and hand over the orbs to him. A cutscene ensues, where the gnomes are seen celebrating and holding a ceremony in which the orbs are returned to their places on the sacred spirit tree.

[[File:Tree Gnome Village - Orbs restored.gif|thumb|left|180px|King Bolren returns the orbs to the spirit tree.]]

'''Congratulations, quest complete!'''
{{Clear}}
"""
