quest = "Wanted!"
step_count = 11

[[steps]]
index = 0
name = "Getting started"
links = ["Falador Park", "Sir Tiffy Cashien", "Temple Knights", "Sir Amik Varze", "White Knights' Castle"]
text = """
{{Map|x:2997,y:3373|plane=0|mapID=0|align=right|width=250|height=250|r=5|mtype=square|zoom=1|caption=The start point at [[Falador Park]].}}
[[File:Sir Tiffy Cashien chathead.png|left]]
To begin the quest, speak with [[Sir Tiffy Cashien]] in the [[Falador Park]]. Ask if he has any jobs for you, and he lets you know that a clerk has made an error and that you're not actually permitted to be a [[Temple Knights|Temple Knight]]. It turns out you have to work as a squire for five years. Because this will take too long, Sir Tiffy offers an alternative by exploiting a loophole. He'll then ask you to go see [[Sir Amik Varze]] in the [[White Knights' Castle]].
{{clear|left}}
"""

[[steps]]
index = 1
name = "Sir Amik Varze"
links = ["Initiate armour", "Sir Amik Varze", "White Knights' Castle", "Falador", "Asgarnian ale", "Sir Tiffy Cashien", "Falador Park", "Solus Dellagar"]
text = """
:'''''Note:''' If wearing [[Initiate armour]] during the chat with [[Sir Amik Varze]], the dialogue will be different, but you may still go through the quest without it.''
[[File:Sir Amik Varze chathead.png|left]]

Speak to [[Sir Amik Varze]] by going up 2 flights of stairs, on the west side in the [[White Knights' Castle]] in [[Falador]]. He will ask you to become a squire after a small conversation. '''Decline his offer''', and the conversation will continue. If you do not decline his offer to become a squire, he will ask for [[Asgarnian ale]] in an endless loop. Speak to [[Sir Tiffy Cashien]] to undo this.

It turns out that there needs to be a crisis for you to become a deputy, but there is no current crisis. Report back to Sir Tiffy in the [[Falador Park]]. For some players, Sir Tiffy will not say anything about a crisis until you have spoken to him a few times. Eventually, Sir Tiffy will inform you of a crisis that has arisen. Head back to talk to Sir Amik again.

Sir Amik will tell you the news that a criminal named [[Solus Dellagar]], the "infamous murder-mage," is back. Sir Amik mentions they have been unable to capture Solus Dellagar due to his powers and, to only kill Solus Dellagar as a last resort. Join the White Knights, and accept the mission to pursue Solus Dellagar.
"""

[[steps]]
index = 2
name = "The Communication Orb"
links = ["law rune", "molten glass", "enchanted gem", "Sir Tiffy Cashien", "Solus Dellagar", "coins", "Commorb", "Savant", "Black Knights' Base", "Taverley Dungeon", "Mage of Zamorak", "Varrock", "Runecraft"]
text = """
{{Needed|10,000 coins '''or''' 1 [[law rune]], 1 [[molten glass]], and 1 [[enchanted gem]].}}
[[File:Savant chathead.png|left]]

Once again, go back to [[Sir Tiffy Cashien]]. It turns out you're just the "agent" that needs to locate [[Solus Dellagar]]. As an agent, you need to be in constant communication. Sir Tiffy offers you a communication device for 10,000 [[coins]], or he can make one if you bring the supplies. Give Sir Tiffy the money or the supplies (a [[law rune]], an [[enchanted gem]] and [[molten glass]]). Either way, you'll receive a [[Commorb]] from him. It is needed for the whole quest.

Use the "contact" feature on the orb to talk to [[Savant]]. It turns out that you should investigate the [[Black Knights' Base|Black Knight Hideout]] in [[Taverley Dungeon]], and investigate the [[Mage of Zamorak]] in [[Varrock]] that is interested in [[Runecraft]].

If you lose your [[Commorb]] after acquiring one, [[Sir Tiffy Cashien]] will lend you his.
"""

[[steps]]
index = 3
name = "Taverley Dungeon"
links = ["equipment", "Black Knight", "Antipoison", "Varrock", "Taverley Dungeon", "Taverley", "bank", "Falador", "Agility", "shortcut", "magic axe", "Poison Scorpion", "chaos dwarves", "Hill Giant", "Lord Daquarius", "Savant", "Commorb", "Solus Dellagar", "fur", "bear"]
text = """
{{Needed|Combat [[equipment]] to kill [[Black Knight]]s, the Commorb, and [[Antipoison]] for low-level players.|recommended=Teleport method to [[Varrock]].}}
{{Map|x:2884,y:3397|plane=0|mapID=0|align=right|r=5|mtype=square|zoom=1|caption=The [[Taverley Dungeon|dungeon]]'s location, south of [[Taverley]].}}

Next, head over to the [[Taverley Dungeon]].
{{Checklist|
*From the west [[bank]] in [[Falador]], you can use the [[Agility]] [[shortcut]] (level 5 Agility required), and keep heading north-west towards [[Taverley]] until you see a ladder.
*Use the ladder and follow the dungeon
**North
**Then east
**Then south past the [[magic axe]]s, [[Poison Scorpion]]s, [[chaos dwarves]] (do not cross the bridge)
**And finally past the [[Hill Giant]]s, and into the [[Black Knight]]s' rooms.
}}
[[File:Wanted! - Solus meets with Lord Daquarius.png|thumb|left|Solus meets with [[Lord Daquarius]].]]
'''Warning:''' The black knights are aggressive if you are under 67 combat; you can stand on the north-western corner of the room to hop worlds if you want to avoid them.

Continue through the double doors, and talk to [[Lord Daquarius]] in the south-western-most room. He tells you nothing. [[Savant]] will call you. (Use the '''contact''' option on the [[Commorb]] if she doesn't call automatically.) She advises you to try to bluff him into giving you something. Go kill a level 33 [[Black Knight]] to make Lord Daquarius give in and beg you not to kill any more of his men. He tells you that [[Solus Dellagar]] is in a place with a lot of [[fur]], but that the fur is not from a [[bear]].

:'''Note:''' The Black Knight kill won't count if you kill it before talking to Lord Daquarius, if you leave the room after the kill, or if you get interrupted during the ensuing conversation.
"""

[[steps]]
index = 4
name = "Zamorak Mage"
links = ["Rune essence", "pure essence", "Void Knight equipment", "Varrock", "Wilderness", "Enter the Abyss", "Edgeville", "Grand Exchange", "Mage of Zamorak", "Solus Dellagar", "Guthix", "Saradomin", "Commorb", "Savant", "Canifis", "Werewolf"]
text = """
{{Needed|The Commorb and either 20 unnoted [[Rune essence|rune]] OR [[pure essence]] (must all be of the same type).}}
{{Map|3256,3391|3264,3391|3264,3380|3253,3380|3253,3386|3256,3386|mtype=polygon|align=left|caption=Location of the Chaos Temple in Varrock.}}
'''Note:''' Do not equip any Saradomin or Guthix items (such as [[Void Knight equipment]]) or the Zamorak Mage will refuse to speak with you. In addition, if you have talked to the Zamorak Mage within the wilderness prior you can go straight to the [[Varrock#Altars of Zamorak|Chaos Altar]] in Varrock.

'''Warning:''' The [[Wilderness]] is a dangerous place, proceed with caution and only bring items you are willing to lose.

If you haven't done the [[Enter the Abyss|Abyss miniquest]], bank all your items and follow the river between [[Edgeville]] and the [[Grand Exchange]] into the [[Wilderness]] to find the [[Mage of Zamorak]]. He will then tell you to meet him "somewhere" in [[Varrock]], which is the Chaos Altar in the temple in south-east Varrock. Grab 20 unnoted [[Rune essence|rune]]/[[pure essence]] from the bank and head to the Chaos Altar.

If you have completed the miniquest, go directly to the Chaos Altar with 20 unnoted [[Rune essence|rune]] essence.

[[File:Wanted! - Solus confronts Mage of Zamorak.png|thumb|Solus meets with the Zamorakian [[Mage of Zamorak|mage]].]]
Talk to him about [[Solus Dellagar]], and make sure you do not wear anything of [[Guthix]] or [[Saradomin]] (including Void). The Zamorak Mage wants your [[Commorb|orb]] in return for information, but [[Savant]] explains that it would be useless to him. He offers to trade his information for 20 rune essence instead. Talk to him again with the unnoted essence. The mage gives your character the tip that Solus went east. Your character connects "east" with the previous tip, "fur," and realises that Solus must be in [[Canifis]] with the [[Werewolf|werewolves]].{{clear|left}}
"""

[[steps]]
index = 5
name = "Canifis"
links = ["Canifis", "Ghosts Ahoy", "Ectophial", "Slayer Tower", "Slayer ring", "fairy ring", "Fenkenstrain's castle teleport", "Savant", "Commorb", "Solus Dellagar"]
text = """
Either run to [[Canifis]] or, if you have completed [[Ghosts Ahoy]], grab your [[Ectophial]] from the bank to teleport to Port Phasmatys and run from there. Alternatively, you teleport to the [[Slayer Tower]] using a [[Slayer ring]] and run south, or use the [[fairy ring]] code {{Fairycode|cks}}, or using [[Fenkenstrain's castle teleport]] tab to get nearby.

[[File:Wanted! - encountering Solus.png|thumb|The player encounters Solus for the first time.]]
Once in Canifis, [[Savant]] will call you and tell you in a lengthy conversation that Solus is probably using a unique "slow teleport", which makes him invisible. If you accidentally keep running and skip the conversation with Savant, step outside the town back to the fairy ring and the conversation will trigger again. Now, use the "scan" option on your [[Commorb]] as you walk around the town until you uncover [[Solus Dellagar]]. Solus briefly appears, speaks with you, and disappears.
"""

[[steps]]
index = 6
name = "Chasing Solus"
links = ["Solus Dellagar", "Flames of Zamorak", "Gielinor", "Champions' Guild", "Dorgesh-Kaan Mine", "Rune essence mine"]
text = """
[[File:Wanted! - Solus disguised.png|thumb|Solus disguises himself as a woman to distract the player.]]
[[File:Wanted! - Solus attacks.png|thumb|[[Solus Dellagar]] strikes the player with the [[Flames of Zamorak]].]]
Savant then calls and finds that she is able to pull items off of Solus as he escapes. These items give the player a clue as to Solus' next whereabouts. From this point on, the player will be chasing Solus throughout [[Gielinor]], and each time Solus is found, he will leave behind an item. That item is a hint for where to go next. There are '''seven''' locations in total, and each location is random, except for the [[Champions' Guild]], the [[Dorgesh-Kaan Mine]], and the [[Rune essence mine]], which are always the third, fifth, and seventh locations, respectively (including Canifis). '''The items received for the second, fourth, and sixth locations are always random.''' Listed below are all of the items that may be received, as well as the location they point to.
"""

[[steps]]
index = 7
name = "=Predetermined items="
links = ["Blue cape", "Champions' Guild", "Smoke Barrage", "Bone spear", "Dorgesh-Kaan mine", "light source", "Kazgar", "Woman (Wanted!)", "Rune essence", "pure essence", "Rune essence mine"]
text = """
These items always appear in a predetermined order.
*[[Blue cape]] - Inside [[Champions' Guild]]. This location is always the third location. Solus will cast a [[Smoke Barrage]] spell on the player, disorienting them but neither dealing damage nor inflicting poison.
*[[Bone spear]] - [[Dorgesh-Kaan mine]] - A [[light source]] is required. The player should follow [[Kazgar]] to the mines (not the water mill) then scan for Solus. This location is always the fifth location. A [[Woman (Wanted!)|woman]] will appear, claiming to be taken hostage by Solus. However, the woman turns out to be Solus himself, who will sucker punch the player and leave (via moonwalk).
*[[Rune essence|Rune]]/[[pure essence]] (20 noted) - [[Rune essence mine]]s. This is the final location; Solus will be fought here.
"""

[[steps]]
index = 8
name = "=Random items="
links = ["Rellekka", "Musa Point", "banana plantation", "Wizards' Tower", "Dorgesh-Kaan mine", "Nardok's Bone Weapons", "The Lost Tribe", "Ardougne Market", "Champions' Guild", "Castle Wars", "Grand Tree", "Canifis Slayer Tower", "Brimhaven", "Ali Morrisane", "Lumbridge Swamp Caves", "Goblin Village", "Dragon Inn", "Yanille", "McGrubor's Wood", "Rune Essence mine", "Draynor Village", "Diango", "Shrine of Scorpius", "Observatory", "ghost", "Solus Dellagar", "Camelot", "Flames of Zamorak", "Hitpoints", "protection prayers", "Savant", "Falador", "White Knights' Castle", "Rune essence mine", "Black Knight (Wanted!)", "Armour", "weapon"]
text = """
These items appear in a random order, and vary from player to player.
{| class="wikitable align-center-1"
! colspan="2" |Item
!Savant says
!Location
|-
|{{plinkt|Fremennik purple cloak}}
|It's... a cloak?
|[[Rellekka]]
|-
|{{plinkt|Banana}}
|It's...a banana?
|[[Musa Point]] [[banana plantation]]
|-
|{{plinkt|Blue wizard hat}}
|It's...a wizard hat?
|[[Wizards' Tower]] south of Draynor Village, {{FloorNumber|uk=0}} library
|-
|{{plinkt|Bone spear}}
|It's... a very strange weapon?
|[[Dorgesh-Kaan mine]] - Bring a light source, and follow the goblin to the mines and [[Nardok's Bone Weapons]] in order to scan for Solus. You do '''not''' need to finish [[The Lost Tribe]] in order to complete this step. You only need to progress far enough in The Lost Tribe to clear the rubble in the Lumbridge castle basement and proceed through the tunnel behind it.
|-
|{{plinkt|Bear fur}}
|It's... fur?
|[[Ardougne Market]]
|-
|{{plinkt|Blue cape}}
|It's a cape...
|[[Champions' Guild]] - you need to be inside the guild before you scan your Commorb in order for Solus to appear
|-
|{{plinkt|Cake}}
|It's... a cake?
|[[Ardougne Market]]
|-
|{{plinkt|Castle wars ticket|txt=Castle{{nbsp}}wars{{nbsp}}ticket}}
|It's... a ticket?
|[[Castle Wars]]
|-
|{{plinkt|Cream hat}}
|It's... a hat?
|The [[Grand Tree]], next to King Narode Shareen (not by the clothing store that sells the hat).
|-
|{{plinkt|Earmuffs}}
|It's... ear muffs?
|[[Canifis Slayer Tower]]
|-
|{{plinkt|Right eye patch}}
|It's... an eye patch?
|[[Brimhaven]] pub
|-
|{{plinkt|Fake beard}}
|It's...a fake beard?
|[[Ali Morrisane]]'s stall in Al Kharid
|-
|{{plinkt|Fremennik cloak|pic=Fremennik green cloak}}
|It's... a cloak?
|[[Rellekka]]
|-
|{{plinkt|Fur}}
|It's... fur?
|[[Ardougne Market]]
|-
|{{plinkt|Giant frog legs}}
|It's... some big frogs legs?
|[[Lumbridge Swamp Caves]] - Bring a light source, a spiny helmet, and if it is your first time entering, a rope. Head to the end of the caves near the level 99 frogs.<br/>Using the Tears of Guthix teleport from a games necklace, running north and entering the cave is a quick way to get there.
|-
|{{plinkt|Goblin mail}}
|It's... goblin armour?
|[[Goblin Village]]
|-
|{{plinkt|Greenman's ale}}
|It's a beer?
|[[Dragon Inn]] ([[Yanille]])
|-
|{{plinkt|Red vine worm}}
|It's... a worm?
|[[McGrubor's Wood]] (fairy ring {{Fairycode|als}})
|-
|{{plinkt|Pure essence}}<br />(20 noted)
|It's some kind of highly magically susceptible rock...
|[[Rune Essence mine]]
|-
|{{plinkt|Toy horsey|pic=Black toy horsey}}
|It's... a toy horse?
|[[Draynor Village]], near [[Diango]]
|-
|{{plinkt|Unholy symbol}}
|It's... an unholy symbol!
|[[Shrine of Scorpius]], north of the [[Observatory]] with all the [[ghost]]s. A quick way there is using a spirit tree to the Khazard Battlefield.
|}

[[Solus Dellagar]] will also react based on which scan location out of seven the player is at.
*If it is the '''second''' scan location, Solus will forcibly teleport the player to [[Camelot]].
*If it is the '''fourth''' scan location, Solus will attempt to personally ward the player off with a particularly strong cast of [[Flames of Zamorak]]. The damage he deals is equal to a percentage of the player's '''current''' [[Hitpoints]] total. At level 99 [[Hitpoints]] with maximum boosts it will deal up to 96 damage, 111 damage when the player has 121 Hitpoints when boosted with an Anglerfish. The damage he deals is typeless, meaning [[protection prayers]] have no effect on it. However, no matter how much damage it inflicts, it will '''never''' kill the player as [[Savant]] will protect them and teleport them back to [[Falador]], in the [[White Knights' Castle]] with all items intact.
*If it is the '''sixth''' scan location (the one before the [[Rune essence mine]]), Solus will summon a level 32 [[Black Knight (Wanted!)|Black Knight]] in an attempt to take the player out. [[Armour]] and a [[weapon]] should be brought. It is not necessary to kill the Black Knight; you can simply run away.
"""

[[steps]]
index = 9
name = "Confronting Solus"
links = ["Solus Dellagar", "Ice Barrage", "Pure essence", "rune essence", "Savant", "Solus's hat", "Combat level", "Hitpoints"]
text = """
{{Instance}}
[[File:Wanted! - Solus decimates rangers.png|thumb|[[Solus Dellagar]]'s powerful [[Ice Barrage]] attack.]]
The final clue will be 20 noted [[Pure essence|pure]]/[[rune essence]]. Bank and equip a weapon and armour for the final fight. Use any rune essence teleport spot you want, and [[Savant]] will close off possible teleports in order to trap him. After a small cutscene, Savant will summon 15 rangers to assist you, but Solus kills them all with [[Ice Barrage]].

[[File:Wanted! - Fighting Solus.png|thumb|The final battle.]]
Go attack Solus yourself and kill him, and you'll get his [[Solus's hat|hat]]. He's fairly easy as he has been weakened after using such a powerful attack on the Temple Knight rangers. He has no specific [[Combat level]], has 40 [[Hitpoints]] and only uses a weak, but fairly rapid melee attack. After the fight, Savant congratulates you. You are returned to the rune essence teleport location. If you lose Solus's hat, contact Savant for another one. You will lose Solus's hat if your inventory is full at the end of the fight.
"""

[[steps]]
index = 10
name = "Finishing"
links = ["Falador", "Sir Amik Varze", "White Knights' Castle", "drop trick", "White equipment", "Black Knight", "White Knight"]
text = """
Return to [[Falador]]. Talk to [[Sir Amik Varze]] in the [[White Knights' Castle]], and hand over the hat. To keep a hat for after the quest, [[drop trick]] it before talking to him. He'll explain to you about the [[White equipment|new armour]] system and killing [[Black Knight]]s (and [[White Knight]]s).

'''Congratulations, quest complete!'''
"""
