quest = "Recipe for Disaster/Freeing Pirate Pete"
step_count = 2

[[steps]]
index = 0
name = "=Under the sea="
links = ["pestle and mortar", "fishbowl", "needle", "bronze wires", "Murphy", "Port Khazard", "Minigame Teleport", "Fishing Trawler", "diving apparatus", "Bank chest", "Cat", "kelp (scenery)", "kelp", "fishcake", "Nung", "mudskipper hide", "rings of recoil", "mudskipper", "crab", "Rock (Mogre Camp)", "bronze wire", "Cook (Lumbridge)", "Pirate Pete"]
text = """
{{Needed|A [[pestle and mortar]], ''A [[fishbowl]] (empty), a [[needle]], 3 [[bronze wires]], weight less than 28 kg, at least 5 free inventory spaces|recommended=A weapon}}
[[File:Recipe for Disaster - Freeing Pirate Pete - Mogre Camp.png|thumb|220px|Underwater, talking to Nung.]]
Go to [[Murphy]], who can be found at [[Port Khazard]] ([[Minigame Teleport]] to the [[Fishing Trawler]]), to get your [[fishbowl]] made into a [[diving apparatus]]. Put it on, then ask to go diving. Your weight must be under 28 kilograms. Have multiple empty inventory spots, as you will not be able to drop items underwater if you need to pick up new items. The nearby [[Bank chest]] may be useful. You may not bring a [[Cat]] with you, on the ground or in your inventory, and attempting to will prompt some amusing dialogue from Murphy.

Once you're underwater, find a [[kelp (scenery)|tall plant]], and pick it for the [[kelp]]. '''Get some extras in case you burn the [[fishcake]].''' Then, look for a crab pen to the north. Talk to [[Nung]]. He will tell you to get him five [[mudskipper hide]]s.

:'''Note''': If using [[rings of recoil]] for the following [[mudskipper]] and [[crab]] kills, at least one damage must be dealt by the player to receive the hides.

Head to the entrance to the mudskippers' cave, on the western wall of the underwater area. Pick up five [[Rock (Mogre Camp)|rocks]] near the entrance to the cave and then enter the cave. While in the cave (and the crab pen thereafter), you will be able to wield weapons as normal as you will be standing upright. Kill five [[mudskipper]]s (level 30 and 31) to get hides. You can do this in multiple trips if inventory space is tight as Nung will accept any hides you currently carry. ('''Remember to give them to Nung before surfacing, as they will disappear!''') Take them back to Nung. Give him your [[needle]] and three [[bronze wire]]; he will let you into the crab pen after this.

In the pen, kill a [[crab]] and collect its meat. Grind the crabmeat and kelp with a [[pestle and mortar]]. '''Get some extras in case you burn the [[fishcake]]'''.

Return to and speak with the [[Cook (Lumbridge)|Cook]]. Use the ingredients on each other, and cook it to get a [[fishcake]]. '''Right-click and use it on (don't eat it!)''' [[Pirate Pete]] in the dining room for your reward.
"""

[[steps]]
index = 1
name = "Rewards"
links = ["Cooking", "Crafting", "Fishing", "Smithing", "crab", "diving apparatus", "crab meat", "Crab helmet", "Crab claw", "chisel", "Culinaromancer's Chest"]
text = """
----
{{Quest rewards
|name = Recipe for Disaster/Freeing Pirate Pete
|image = [[File:Recipe for Disaster (Freeing Pirate Pete) reward scroll.png|centre]]
|qp = 1
|rewards =
*{{SCP|Cooking|1,000}} [[Cooking]] experience
*{{SCP|Crafting|1,000}} [[Crafting]] experience
*{{SCP|Fishing|1,000}} [[Fishing]] experience
*{{SCP|Smithing|1,000}} [[Smithing]] experience
*The ability to go diving and fight [[crab]]s (you need your [[diving apparatus]])
*The ability to cook [[crab meat]] (heals 10 hitpoints in 5 bites)
*The ability to kill crabs to get their shells and claws, which can be made into a [[Crab helmet|helmet]] and [[Crab claw|gloves]] with a [[chisel]]
*Further access to the [[Culinaromancer's Chest]]
}}</onlyinclude>
"""
