quest = "Family Crest"
step_count = 5

[[steps]]
index = 0
name = "The crest"
links = ["Dimintheis", "Varrock", "Fancy Clothes Store", "Caleb", "White Wolf Mountain", "Catherby"]
text = """
{{Map|x=3281|y=3404|r=4|width=250|height=250|align=right|caption=The quest's starting point|mtype=square}}

To begin, talk with [[Dimintheis]], who lives in south-eastern [[Varrock]], within the fenced off area, in the house just above the [[Fancy Clothes Store|clothes shop]]. Tell him you are a bold adventurer and he will propose an adventure for you; he needs his family crest returned. Ask him where the crest is, and he will explain his three sons took it with them when they rode out to battle many years ago. He hadn't heard from them since, until he recently learned that his son [[Caleb]] was working as a chef beyond the [[White Wolf Mountain]], in [[Catherby]].
"""

[[steps]]
index = 1
name = "Caleb"
links = ["Shrimps", "bass", "salmon", "tuna", "swordfish", "Catherby", "Farming shop", "Crest part", "shrimp"]
text = """
{{Needed|[[Shrimps]], [[bass]], [[salmon]], [[tuna]] and a [[swordfish]] (all cooked).}}

Head to [[Catherby]], where Caleb can be found either inside the building with the sink to the south of the [[Farming shop]], or wandering outside of it. Talk to him and ask if he is Caleb Fitzharmon, and he will tell you he has a 'bit' of the crest. Ask him what happened to the rest of it, and he will explain that he and his brothers broke the crest into three [[Crest part|parts]] after a disagreement about who would become heir to their fathers' lands, and each of them ended up with a piece. Ask if you can have his bit of the crest, and he will agree to give you his piece provided you bring him ingredients for his fish salad. Agree to bring him the ingredients.

:'''Note''': You must ask him what happened to the rest of the crest, or you will be unable to collect the other parts.

Bring him the [[shrimp]], [[salmon]], [[tuna]], [[bass]], and [[swordfish]] (all cooked) and he will give you his piece of the crest.
"""

[[steps]]
index = 2
name = "Avan"
links = ["necklace mould", "ring mould", "pickaxe", "Ruby", "perfect gold ore", "perfect gold bar", "'perfect' necklace", "'perfect' ring", "gem trader", "Al Kharid", "gnome glider", "Lumbridge", "gold rocks", "Al Kharid Mine", "cape", "Avan", "dwarf", "Boot", "Dwarven Mine", "Dwarven Mines", "Edgeville Monastery", "Ardougne", "Witchaven Shrine", "Witchaven", "hobgoblins", "ogres", "hellhounds", "Combat Level", "Protect from Melee", "lever (Family Crest)", "'perfect' gold ore", "safespot", "furnace", "rubies", "'perfect' gold bar"]
text = """
{{Needed|[[necklace mould]], [[ring mould]], any [[pickaxe]], 2 [[Ruby|cut rubies]]|recommended=Food and armour, fast travel method to Dwarven Mine, Witchaven and Al Kharid.|skills={{SCP|Mining|40}} {{Boostable|yes}} to mine [[perfect gold ore]], {{SCP|Smithing|40}} {{Boostable|yes}} to smelt [[perfect gold bar]], {{SCP|Crafting|40}} {{Boostable|yes}} to craft the [['perfect' necklace]] and [['perfect' ring]]}}

Caleb mentioned that the last he heard from his brother Avan, he was searching for treasure in the desert, and that you might want to ask the traders there about him.

Head to the [[gem trader]] in the north of [[Al Kharid]], found next to the [[gnome glider]] just south of the gate to [[Lumbridge]]. Ask him about Avan Fitzharmon, and he will remember that the man was searching for 'perfect gold'. The gem trader told him to search the sand dunes where [[gold rocks]] can be found. Head to the northern [[Al Kharid Mine]], and a man can be found wandering around just at the entrance to the pit with a yellow [[cape]] on. This is, indeed, [[Avan]], as he'll tell you when you ask him. He's not giving up his piece of the crest though unless you can help him win the affection of a certain lady by getting him a [['perfect' ring|ring]] and [['perfect' necklace|necklace]] made out of perfect gold. Unfortunately, the stuff there in the desert isn't nearly good enough. He'll tell you a [[dwarf]] named [[Boot]] might know something about where to find the gold.

:'''Note:''' The player must speak to Boot before being able to give the jewellery to Avan, even though it is possible to mine and smith perfect jewellery without speaking to him.

{{Map|mapID=6|2984,9810|width=250|height=250|align=right|r=6|mtype=square|caption=[[Boot]] is located towards the far west end of [[Dwarven Mine]].}}

Head to the [[Dwarven Mines]], located just west of the [[Edgeville Monastery]]. Climb down the trapdoor behind the eastern building to enter the mines. Boot can be found south-west from this northern entrance, wandering by the two rock columns - see the map to the right. Tell him you are in search of very high quality gold, and he will direct you to east of [[Ardougne]], underground somewhere. The location you need to visit is the [[Witchaven Shrine|Witchaven Dungeon]] in [[Witchaven]].

:'''Note''': You will need to pass by level 28 [[hobgoblins]], level 53 [[ogres]], and level 122 [[hellhounds]] in this dungeon, though you do not need to kill any of them. The hobgoblins will attack you immediately after entering the dungeon if below 57 [[Combat Level]], and you will need to solve a puzzle while being attacked by ogres. [[Protect from Melee]] will negate all damage, as the monsters only use melee.

Enter the dungeon and head north east along the path. To the north and south are two rooms with [[lever (Family Crest)|lever]]s in and outside of them. You'll have to complete a lever puzzle here to unlock the eastern area which contains the gold rocks and hellhounds:

{{Checklist|
*Go to the northern room and pull the outside lever up.
*Head into the southern room using the eastern door, pull the lever up, then exit via the '''western''' door.
*Go to the northern room and pull the outside lever down, then enter and pull the inner lever up.
*Leave the room and pull the outside lever up again.
*Go back to the southern room through the '''western''' door and pull the lever down, then exit via the '''eastern''' door.
*The hellhound room should now be unlocked.
}}

'''Note''': Once unlocked, you do not need to do the puzzle again to re-enter.

Enter the hellhound room to the east and mine at least two [['perfect' gold ore]] from the gold rocks ({{SCP|Mining|40}}). The hellhounds have a short aggression range - try and zigzag past them to find an open rock to mine. If you draw aggression before you are done mining, there is a [[safespot]] you can use to hide in behind the rock column directly south of the entrance - you can then world hop to lose aggression and try again. Low levelled players may also consider waiting 10 minutes in this safespot, after which the hellhounds will not attack you while mining the southern rocks. The rocks will take some time to respawn, so once you have mined one rock, use another or world hop to reset the rock.

[[File:Family Crest - Witchaven Dungeon levers.png|thumb|The sequence of operating the levers to get perfect gold.]]

Once you have your two 'perfect' gold ore, head to any [[furnace]] with the ore, your [[rubies]], your [[ring mould]], and your [[necklace mould]]. You may consider using the one in [[Al Kharid]], as you will be returning to Avan in the Al Kharid mine afterwards. Smelt the ore into [['perfect' gold bar]]s ({{SCP|Smithing|40}}), then smelt a bar each into a ruby necklace and ruby ring respectively ({{SCP|Crafting|40}}, {{SCP|Smithing|40}}), which will make the [['perfect' ring]] and [['perfect' necklace]] ('''DO NOT SELECT the GOLD necklace and ring!''').

Return to Avan in the Al Kharid Mine, and he will take your jewellery and give you the second piece of the crest in return. He will then tell you how to find the final brother Johnathon.
"""

[[steps]]
index = 3
name = "Johnathon"
links = ["antipoison", "runes", "Chronozon", "Fire Blast", "Varrock", "Wilderness", "Antipoison", "Poison spider", "Edgeville Dungeon", "poison spiders", "Earth obelisk", "player killers", "Wind Blast", "Water Blast", "Earth Blast", "Water spells", "poison cure", "Edgeville", "Obelisk of Earth", "safespot", "Twinflame staff"]
text = """
{{Needed|An [[antipoison]] potion, [[runes]] to cast the four Blast spells, combat equipment for the battle with [[Chronozon]].|recommended=Fast travel method to the Jolly Boar Inn, Edgeville and Varrock|skills={{SCP|Magic|59}} {{Boostable|yes}} to cast [[Fire Blast]]}}
[[File:Edgeville Dungeon map.png|thumb|upright|Edgeville Dungeon]]
The last brother is holed up on the {{FloorNumber|uk=1}} of the Jolly Boar Inn north-east of [[Varrock]] near the edge of the [[Wilderness]]. Bring your [[Antipoison|antipoison potion]], and head up to the {{FloorNumber|uk=1}} where he is huddled in the north western room. Talk to him and he will be delirious - he has been bitten by a [[Poison spider|poisonous spider]]. Once he has finished speaking, use the antipoison on him (he'll take the entire potion, but you may bring a lower dosed potion) and he'll be very grateful to be cured.

Johnathon will tell you that he lost the crest while attempting to kill a powerful demon named [[Chronozon]]. If you want it back, you'll have to kill the demon yourself. Johnathon explains that to defeat the demon, you will need to first hit him once with each of the four elemental spells of death.

[[Chronozon]] can be found in the [[Edgeville Dungeon]], by the [[poison spiders]] near the [[Earth obelisk]].

:'''{{Colour|red|Warning}}:''' You will be heading into the [[Wilderness]], where other players may kill you. Only take items you are willing to lose to [[player killers]], and consider using a low population world.

[[File:Chronozon safespot.png|thumb|Chronozon safespot.]]

To defeat Chronozon, you will need to cast [[Wind Blast]], [[Water Blast]], [[Earth Blast]], and [[Fire Blast]] and '''successfully hit him''' once with each (in any order). {{mes|Chronozon weakens....}} will appear in the chat after each individual hit from a blast spell. You do not need to kill him using Magic after he has been weakened, though he has no Magic defence and is weak to [[Water spells]].

Along with enough runes to cast each blast spell several times, bring food, combat equipment and a [[poison cure]] for the poison spiders near Chronozon. Head to [[Edgeville]] and enter the dungeon through the trapdoor in the south eastern corner of the building south of the bank. Head north, then east through the gate past the skeletons, then north through the gate with thugs on the other side. Continue north past the thugs, west past the red spiders and black demons, then south to the [[Obelisk of Earth]].

There is a [[safespot]] one square in front of the eastern standing torch for Magic and Ranged. If you draw aggression of the poison spiders, stand behind the stalagmite to avoid it, then hop worlds. Weaken him with each blast spell, then kill him with any combat style.

:'''Note''': If you take too long to kill him, his weakness will wear off and you'll have to weaken him again.

{{bug|The [[Twinflame staff]]'s double cast feature does not kill him as expected.}}

Chronozon will drop the final crest piece on death, pick it up.
"""

[[steps]]
index = 4
name = "The crest reassembled"
links = ["family crest (item)", "Varrock", "Dimintheis", "Family Pest"]
text = """
Now that you have all three crest pieces, put them together to make the [[family crest (item)|Family Crest]] and then make your way back to [[Varrock]]. Give the crest to [[Dimintheis]] who will be very, very pleased to have it back.

'''Congratulations, quest complete!'''

:'''Tip:''' You may choose to talk to Dimintheis again to start the [[Family Pest]] miniquest before imbuing one of the gauntlets, as you will additionally have the chat option to progress the miniquest.
"""
