quest = "Troubled Tortugans"
step_count = 6

[[steps]]
index = 0
name = "Finding Floopa"
links = ["boat", "The Great Conch", "Quests", "Injured Tortugan", "palm leaf", "seaweed", "makeshift bandages", "Floopa", "the Great Conch"]
text = """
Using your [[boat]], head to the remote island north-west of [[The Great Conch]], marked on the map with the [[Quests|quest]] icon [[File:Quest start icon.png|frameless]]. Talk to the [[Injured Tortugan|injured tortugan]] to attempt to help her, and she will decline your assistance. Eventually, the tortugan will reluctantly accept your aid, and ask you to make some bandages with nearby resources. Shake the palm trees for a [[palm leaf]], then pick up a nearby [[seaweed]] spawn, and use the items on each other to create [[makeshift bandages]]. Give the bandages to the tortugan, who will then introduce herself as [[Floopa]]. Offer to take Floopa home and she'll again refuse your help, this time believing that returning home would mean failing everything. Eventually, she will begrudgingly agree, and let you bring her back home to [[the Great Conch]]. Floopa will then board your [[boat]], who will remain there even if the boat capsizes or is abandoned.
"""

[[steps]]
index = 1
name = "The Great Conch"
links = ["Elder Korel", "Fairy ring", "Elder Raley", "range"]
text = """
[[File:Raley and Floopa.png|thumb|width=275x275|Floopa, back home at Elder Raley's.]]
Sail south-east from where you found Floopa, making your way to the pier at the southern end of the Great Conch. Disembark and head up the docks to find Floopa, alongside [[Elder Korel]].

:'''Note''': [[Fairy ring]] {{Fairycode|CJQ}}'' '' will now be unlocked, allowing you to return to the island at any time.

Speak to Floopa, and Elder Korel will send her to [[Elder Raley]]'s hut. Elder Korel will then ask you to leave, as the tortugans are not fond of humans; you'll insist on staying until she recovers, causing Elder Korel to allow you on the island as a "tourist." He will mention that in order to stay permanently, you will need to become a honorary tortugan. He will then direct you to Elder Raley's hut, found just east of the entrance to the town (marked on the map with a [[range]] icon [[File:Cooking range icon.png|frameless]]).
"""

[[steps]]
index = 2
name = "Making repairs"
links = ["hammer", "saw", "axe", "jatoba logs", "sea shell", "tortugan scute", "gryphons", "list of repairs", "shop", "Construction", "Jatoba tree", "bronze axe", "Logs (bronze axe)", "Elder Raley", "Gryphon (Troubled Tortugans)"]
text = """
{{Needed|[[hammer]], [[saw]], [[axe]], 10 [[jatoba logs]], 6 [[sea shell]]s, 6 [[tortugan scute]]s}}
<!--These are NOT required to all be in a single inventory; you do NOT need 22 free inventory slots.-->
Speak to Floopa inside Elder Raley's hut, and Elder Raley will tell her that the village was attacked by [[gryphons]]. While no one died, the village was damaged in the scuffle. They will then notice you, with Floopa surprised to see that you were still waiting for her. You explain to them that Korel allowed you to stay as a tourist, and offer to help fix the damage, causing Elder Raley to thank you and give you a [[list of repairs]]. You will now need to make six repairs in the town centre, marked by several [[shop]] icons. Each repair gives 80 [[Construction]] experience.
{| class="wikitable lighttable"
!Repair
!Location
!Items needed
|-
|Krill's wall
|House north of the marketplace
|2 {{Plink|Tortugan scute|txt=Tortugan scutes}}<br>2 {{Plink|Jatoba logs}}
|-
|Krill's stall
|North-western market stall
|1 {{Plink|Tortugan scute}}<br>1 {{Plink|Sea shell}}
2 {{Plink|Jatoba logs}}
|-
|Strom's wall
|House south-west of the marketplace
|2 {{Plink|Tortugan scute|txt=Tortugan scutes}}<br>2 {{Plink|Jatoba logs}}
|-
|Strom's crate
|Crate south-west of the marketplace
|2 {{Plink|Sea shell|txt=Sea shells}}<br>1 {{Plink|Jatoba logs}}
|-
|Coco's stall
|South-eastern market stall
|1 {{Plink|Tortugan scute}}<br>1 {{Plink|Sea shell}}<br>2 {{Plink|Jatoba logs}}
|-
|Coco's crate
|Crate south of the marketplace
|2 {{Plink|Sea shell|txt=Sea shells}}<br>1 {{Plink|Jatoba logs}}
|}
A cluster of [[Jatoba tree|jatoba trees]] can be found west of the village, and a [[bronze axe]] can be picked up from a [[Logs (bronze axe)|tree stump]] north of the calquat tree patch. Scutes can be found all across the village, and sea shells can be found by the shore when you entered the island. A [[hammer]] and [[saw]] also spawn in the village, in the blacksmith's workshop to the north-east and in [[Elder Raley]]'s house respectively. Once all repairs are done, return to Elder Raley.
[[File:Gryphon cave.png|thumb|width=275x275|The cave where the [[Gryphon (Troubled Tortugans)|gryphon]] is nesting. ]]
"""

[[steps]]
index = 3
name = "Tracking the attacker"
links = ["Gryphon (Troubled Tortugans)", "melee", "Protect from Melee"]
text = """
{{Needed|Axe, combat gear}}

As you return, Floopa will lament the permanent damage to her flipper. Raley will reassure her that the village will be there for her, at which point you will inform Raley that the repairs are done. Elder will now ask for your help finding and killing the gryphon that attacked the village, saying it's only a matter of time before it returns. Since the gryphon was injured in battle, it wasn't able to fly away; however, it retreated into the forest, and you'll now have to track it.

Head to the statue in the centre of the village and inspect it to reveal some tracks. Follow these tracks west, then examine the spiky red plant found at the split in the path. Follow the tracks north, and inspect the rockslide, then continue north once more and inspect the plant immediately east of the passage entrance. You'll come to a cluster of three plants; inspect the eastern plant to find the final set of tracks, which takes you to a cave entrance. Use your axe to clear the growth blocking the cave, and enter it to begin a fight with a level 95 [[Gryphon (Troubled Tortugans)|gryphon]].

The gryphon only attacks with [[melee]], but it will also use a special attack that knocks the player back and deals moderate damage if their '''worn weight''' is not high enough. To avoid taking any damage, simply stand next to the wall and pray [[Protect from Melee]]. Once the gryphon is dead, report back to Elder Raley.
[[File:Battle at the Little Pearl.png|thumb|width=350x350|Tortugans fighting to protect their eggs.]]
"""

[[steps]]
index = 4
name = "Pearl in peril"
links = ["tortugan shield", "Elder Blunn", "Elder Hubber", "Elder Root", "Shellbane gryphon (Troubled Tortugans)"]
text = """
{{Needed|combat gear, prayer, food, and a [[tortugan shield]]}}

You'll return to Elder Raley's hut to find Elder Korel informing him of another gryphon attack, this time on the Little Pearl. Elder Korel will immediately depart, as this is where tortugans lay their eggs. Elder Raley will ask you to help Elder Korel, but since the gryphon appears to be one of the larger ones, he'll direct you to [[Elder Blunn]] for further preparation. Grab any gear, food and supplies from the bank before speaking to Elder Blunn, then speak to him in the marketplace to receive a [[tortugan shield]]. Head back to the dock and sail to the Little Pearl, which is south-east from the dock. When you arrive, you will see a cutscene in which a strange ship quickly departs, leaving elders Korel, [[Elder Hubber|Hubber]], and [[Elder Root|Root]] engaged in battle with a [[Shellbane gryphon (Troubled Tortugans)|shellbane gryphon]].
"""

[[steps]]
index = 5
name = "= The fight ="
links = ["Protect from Melee", "Protect from Missiles", "Weight", "Shellbane_gryphon/Strategies", "Gold helmet", "corrosion", "Shipwright"]
text = """
As soon as the cutscene ends, the gryphon will attack. Activate [[Protect from Melee]] if attacking from up close, otherwise go with [[Protect from Missiles]] and stand near the ocean shore where the gryphon can't reach you directly. The tortugan shield '''must be equipped''' for the entire fight, or else the gryphon's attacks will deal heavy damage that ignores protection prayers.

The gryphon will use both melee and ranged auto-attacks and occasionally line up a special attack:
{| class="wikitable"
!Attack
!Attack
!Negation
|-
|Slam
|The gryphon will knock the player back and deal heavy damage if '''[[Weight|worn weight]]''' is less than 40kg.
|Wear [[Shellbane_gryphon/Strategies#Equipment|heavy equipment]], or any items with a [[Gold helmet]]. Alternatively, stand out of reach; behind a tree or eggs, or near the ocean shore.
|-
|Whirlwinds
|The gryphon will flap its wings, creating whirlwinds on the player's location that can hit for 50+.
|Moving around during the flapping sequence will prevent the whirlwind from growing and hurting you.
|-
|Corrosive spit
|The gryphon will spit orange acid on the player's current tile, causing a [[corrosion]] effect.
|Step at least one tile away from the spit before it lands.
|}
[[File:Mysterious ship.png|thumb|width=275x275|The mysterious ship seen fleeing the scene of the gryphon attack.]]
If you die during the fight, your gravestone will appear where you last docked, and the ship you moored at the Little Pearl will be considered Lost, requiring recovery at a [[Shipwright]]. Dying to the Gryphon's whirlwind attack after reducing its HP to 0 will still progress the quest. Players having trouble fighting the Gryphon may hide behind the palm trees and let the Tortugans lower its health to 20 hitpoints.

Speak to Elder Korel after killing the gryphon, and he will question how the gryphon went so far from the conch. You will then tell him about the strange ship with red sails leaving the island as you came, and he'll suggest you inform Elder Raley. Head back to Elder Raley's hut and tell him and Floopa about the ship, and Floopa recalls being betrayed by her crew and thrown overboard. She'll comment that might be a connection between the events, but will need time to think about it further. Raley will tell her to rest and allows you to explore the island in the meantime, promising to call you when Floopa has recovered.

'''Congratulations, quest complete!'''
"""
