quest = "A Tail of Two Cats"
step_count = 5

[[steps]]
index = 0
name = "Cat hunt"
links = ["catspeak amulet", "Unferth", "Burthorpe", "Dunstan", "Hild", "death runes", "Bob (cat)", "Misthalin", "Asgarnia", "Kharidian Desert", "Shantay Pass", "Varrock west bank", "Clock Tower (building)", "East Ardougne", "Edmond", "Gielinor Parcel Delivery Team", "Barbarian Village", "Turael", "Heroes' Guild", "Warriors' Guild", "Burthorpe Castle", "Catherby", "Hickton's Archery Emporium", "Spria", "Draynor Village", "Wise Old Man", "H.A.M. Hideout", "Draynor Manor", "Mining Guild", "Falador", "Falador Party Room", "Rising Sun Inn", "White Knights' Castle", "Dark Wizards' Tower", "Mage Training Arena", "Citharede Abbey mine", "Giants' Plateau", "Lumbridge", "Chicken", "Port Khazard", "Port Sarim", "Hetty", "Rimmington", "Cow", "Crafting Guild", "Seers' Village", "Elemental Workshop", "witch's house (location)", "Taverley", "Jatix's Herblore Shop", "Lady of the Lake", "Grand Exchange", "Varrock Palace", "Estate agent", "Anvil", "Varrock", "White Wolf Mountain"]
text = """
{{Needed|a cat '''or''' kitten, 5 death runes, a catspeak amulet|recommended=a Varrock teleport, Games necklace}}

You do not need to have your kitten or cat following the entire time—simply keep it in your inventory throughout the quest, and it will jump out to participate in necessary dialogue, and then you can pick it back up again to avoid it becoming overgrown. Equip your [[catspeak amulet]], and start the quest by talking to [[Unferth]], who can be found in east [[Burthorpe]] in the house south of [[Dunstan]]. After starting, talk to [[Hild]] in the nearby house north-east of [[Unferth]]. She will enchant your catspeak amulet if you give her five [[death runes]]. You can now open it to find [[Bob (cat)|Bob]]'s location. It works somewhat like a compass - when facing north, click the left or right whiskers to control the interface and point it in the right direction. When you see the central cat's eyes light up, go in that direction to find Bob. He can only be found in [[Misthalin]], [[Asgarnia]], and the northern part of the [[Kharidian Desert]] (he cannot pass through the [[Shantay Pass]] into the rest of the desert). '''However it is recommended to pick a common spot where Bob is found, and then world hop.''' He is commonly found at the Varrock anvils (south of the [[Varrock west bank]], not the armour shop anvils), or the Catherby Archery Shop.

'''List of common locations:'''
[[File:A Tail of Two Cats - catspeak amulet in action.png|thumb|The interface of the Amulet of catspeak (e). This specific picture shows that Bob is south-east to the player's current location.]]

{{Map
 |3164,3489,desc:Grand Exchange
 |3255,3480,desc:Varrock Church
 |2929,3536,desc:Turael's House
 |3078,3439,desc:Barbarian Village Pub
 |2616,3332,desc:East Ardougne Bank (North)
 |3105:3384,desc:Draynor Manor
 |3092:3267,desc:Spria's house
 |3046:3377,desc:Falador Party Room
 |3051:3248,desc:Catherby Docks
 |2713:3480,desc:Elemental Workshop
 |3240:3474,desc:Varrock Estate Agent
 |2823:3443,desc:Catherby Archery Shop
 |3187:3425,desc:Varrock West Anvils
 |2816,3512,desc:White Wolf Mountain (North-West)
 |2866,3512,desc:White Wolf Mountain (North-East)
 |2865,3455,desc:White Wolf Mountain (South-East)
 |mtype=dot|caption=Bob the Cat possible locations (''hover to see descriptions'')
 |align=right
}}
{| class="wikitable"
|+
!Location
!Description
|-
|style="text-align:center; font-style:italic;"|Ardougne
|
*[[Clock Tower (building)|Clocktower]] south of [[East Ardougne]]
*[[Edmond]]'s house in [[East Ardougne]]
*[[Gielinor Parcel Delivery Team|GPDT Delivery]] in [[East Ardougne]] by docks
*Northern bank in [[East Ardougne]]<!-- Mapped: 2616,3332 -->
|-
|style="text-align:center; font-style:italic;"|Barbarian Village
|
*Outside the pub in [[Barbarian Village]]<!-- Mapped: 3078,3439 -->
|-
|style="text-align:center; font-style:italic;"|Burthorpe
|
*Next to [[Turael]]'s house<!-- Mapped: 2929,3536 -->
*North wall of the [[Heroes' Guild]] in [[Burthorpe]]
*North wall of the [[Warriors' Guild]] in [[Burthorpe]]
*Outside [[Burthorpe Castle]], between the castle and its outer wall
|-
|style="text-align:center; font-style:italic;"|Catherby
|
*[[Catherby]] docks<!-- Mapped: 3051,3248 -->
*[[Hickton's Archery Emporium|Catherby archery shop]]<!-- Mapped: 2823,3443 -->
|-
|style="text-align:center; font-style:italic;"|Draynor
|
*[[Spria]]'s house in [[Draynor Village]]<!-- Mapped: 3092,3267 -->
*Inside the jail east of [[Draynor Village]]
*[[Wise Old Man]]'s house in [[Draynor Village]]
*Near the entrance to the [[H.A.M. Hideout]] east of [[Draynor Village]]
*[[Draynor Manor]] (north of the manor but may be within the fenced area)<!-- Mapped: 3105,3384 -->
|-
|style="text-align:center; font-style:italic;"|Falador
|
*Entrance of the [[Mining Guild]] in [[Falador]]
*[[Falador Party Room]]<!-- Mapped: 3046,3377 -->
*Farm south of [[Falador]]
*[[Rising Sun Inn]] in West [[Falador]]
*[[White Knights' Castle]] in [[Falador]]
*North-East from [[Dark Wizards' Tower]], South-West from [[Falador]] Agility Shortcut in its West Wall, in the woods
*East of the Goblin Village, near the house of Miazrqa
|-
|style="text-align:center; font-style:italic;"|Kharidian Desert
|
*[[Mage Training Arena]] (south-west)
*[[Citharede Abbey mine]]
*Mining site at [[Giants' Plateau]]
|-
|style="text-align:center; font-style:italic;"|Lumbridge
|
*Between the chicken farm and cow farm north of [[Lumbridge]]
*[[Chicken]] farm north of [[Lumbridge]] (east of river)
|-
|style="text-align:center; font-style:italic;"|Port Khazard
|
*Inside General shop in [[Port Khazard]]
|-
|style="text-align:center; font-style:italic;"|Port Sarim
|
*[[Port Sarim]] docks (near quest marker)
|-
|style="text-align:center; font-style:italic;"|Rimmington
|
*[[Hetty]]'s house in [[Rimmington]]
*Inside the Onion/Cabbage patch in [[Rimmington]]
*[[Cow]] Pen outside the [[Crafting Guild]] near [[Rimmington]]
|-
|style="text-align:center; font-style:italic;"|Seers' Village
|
*[[Seers' Village]] graveyard
*Near [[Seers' Village]] bank, in the building for [[Elemental Workshop]]<!-- Mapped: 2713,3480 -->
|-
|style="text-align:center; font-style:italic;"|Taverley
|
*By the south wall of the [[witch's house (location)|witch's house]] in [[Taverley]]
*The house just north of [[Jatix's Herblore Shop]] in [[Taverley]]
*[[Lady of the Lake]]'s peninsula  in [[Taverley]]
|-
|style="text-align:center; font-style:italic;"|Varrock
|
*Inside the [[Grand Exchange]]<!-- Mapped: 3164,3489 -->
*Church east of [[Varrock Palace]]<!-- Mapped: 3255,3480 -->
*Inside the Varrock [[Estate agent]] house<!-- Mapped: ,3474 -->
*Western [[Anvil]]s in [[Varrock]]<!-- Mapped: 3187,3425 -->
|-
|style="text-align:center; font-style:italic;"|White Wolf Mountain
|
*[[White Wolf Mountain]] (North-West)<!-- Mapped: 2816,3512 -->
*[[White Wolf Mountain]] (North-East)<!-- Mapped: 2866,3512 -->
*[[White Wolf Mountain]] (South-East)<!-- Mapped: 2865,3455 -->
|}
"""

[[steps]]
index = 1
name = "Strong lineage"
links = ["Bob (cat)", "Neite", "Gertrude", "Robert the Strong", "Varrock Palace", "Reldo", "Dragonkin", "cat", "Sphinx"]
text = """
After finding [[Bob (cat)|Bob]], talk to him. He will tell you that he's in love with [[Neite]], but she has no idea what his origins are so she's not interested in him. Talk to [[Gertrude]] (located south of the Cooking Guild, West of Varrock) about Bob's family. While there, your cat will tell you to research a warrior called [[Robert the Strong]].

In the [[Varrock Palace]] library, talk to [[Reldo]]. He will tell you that Robert the Strong was much taller and stronger than any other man of his time. His longbow was six feet tall, and he fought immortal monsters known as the [[Dragonkin]]. He fought alongside a black panther.

Return to Bob ('''who might have changed location, use the enchanted Catspeak amulet to locate him'''). You and your [[cat]] will try to convince Bob he is Robert the Strong. Your cat will remind you of the fact that the [[Sphinx]] knows how you were hypnotised, so perhaps it can hypnotise Bob.
"""

[[steps]]
index = 2
name = "Hidden memories"
links = ["Nardah teleport", "ring of charos", "Raetul and Co's Cloth Store.", "Sphinx", "Sophanem", "Pyramid Plunder", "Burthorpe", "Robert the Strong", "Odysseus", "Dragonkin (A Tail of Two Cats)", "Neite"]
text = """
[[File:A Tail of Two Cats - talking to sphinx.png|thumb|The Sphinx talking to Bob the cat in the desert.]]
{{Needed|recommended=[[Nardah teleport]]''' AND coins for the magic carpets (and [[ring of charos]] for discounted rides) OR Desert clothing AND waterskins AND 80gp if you are buying the desert outfit in Sophanem. ''Additionally''' you will need a games necklace if you decide to skip the cutscene}}

You can use the Pharoh's sceptre to get here faster (Jalsavrah teleport is in Sophanem).

If you haven't gotten the desert outfit, you can buy it from [[Raetul and Co's Cloth Store.]], which can be found east of the [[Sphinx]].

Talk to the Sphinx in [[Sophanem]]. A good way of getting there is to take a magic carpet to Pollnivneach from Shantay Pass and then to Sophanem using Pollnivneach's southern carpet - the Sphinx is south-east of the northern [[Pyramid Plunder|pyramid]]. Ask her for help, and after a bit, you'll have the option to view a five-minute cutscene or get a brief summary of what happens. '''''If you choose the brief summary, you won't be offered the option of being teleported to [[Burthorpe]].'''''

During the cutscene, the Sphinx will teleport Bob to Sophanem and hypnotise him. Bob, thinking back on his earliest memories, recalls himself as [[Robert the Strong]]. He sees himself looking over at a tower beside [[Odysseus]], followed by a battle between them and a [[Dragonkin (A Tail of Two Cats)|Dragonkin]]. The Dragonkin manages to slay the panther and weaken Robert, however Robert manages to kill the Dragonkin.<gallery captionalign="center">
Bob The Cat Hypnotised.gif|Bob the Cat hypnotised by the Sphinx
A Tail of Two Cats - dragonkin's castle.png|The Dragonkin on top of its castle.
A Tail of Two Cats - Odysseus dies.png|Odysseus fighting the Dragonkin, before being killed.
A Tail of Two Cats - Robert vs the Dragonkin.png|Robert continues to fight the Dragonkin after Odysseus dies.
A Tail of Two Cats - dragonkin dies.png|Robert finally kills the Dragonkin
</gallery>
After the cutscene, the Sphinx teleports [[Neite]] to Bob, who will be impressed and fall in love with him. Bob will tell you to keep his owner busy by doing his chores, and you will be given the option to teleport back to Burthorpe (only if you choose to hear the long summary), or stay in Sophanem.
"""

[[steps]]
index = 3
name = "Bob's list"
links = ["Unferth", "Burthorpe", "chores", "Unferth's patch", "potato seed", "bed (A Tail of Two Cats)", "logs", "fireplace (A Tail of Two Cats)", "bucket of milk", "chocolate cake", "table (A Tail of Two Cats)", "shears", "Apothecary", "Varrock", "doctor's hat", "nurse hat", "vial of water"]
text = """
{{Needed|Catspeak amulet (wear it), A vial of water, logs, a tinderbox, a bucket of milk, a chocolate cake, shears, a rake, a seed dibber, 4 potato seeds, Desert shirt or Druid's robe top or Medical gown, Desert robe or Druid's robe|recommended=Varrock teleports, a games necklace}}

Go back to [[Unferth]]'s house in [[Burthorpe]] and do these [[chores]]:
[[File:A Tail of Two Cats - cutting Unferth's hair.png|thumb|One of the chores Bob asks you to do while he is gone.]]

*Tend garden: Using your rake, weed [[Unferth's patch]] in the yard just north of the house and plant four [[potato seed]]s. You now need to wait about 15 – 35 minutes for them to grow. You do not need to water or compost the patch. ''If this is the only remaining chore, you will be alerted by your character or your cat/kitten saying all the chores are finished once the potatoes are done growing.''
*Tidy house: Make [[bed (A Tail of Two Cats)|Unferth's bed]]. This takes one click and is the easiest chore.
*Warm human: Use some [[logs]] on the [[fireplace (A Tail of Two Cats)|fireplace]] and light it.
*Feed human: Use a [[bucket of milk]] and a [[chocolate cake]] on the [[table (A Tail of Two Cats)|table]]. '''Right click your cake! Do not eat it. A slice of cake does not work. Make sure it is the table with a cup and plate on it, NOT the one next to his bed.'''
*Tidy human: Use a pair of [[shears]] on Unferth to shave his hair. '''Note: The animation takes a couple of seconds, do not click away until he is bald.'''
*Note: the quest will not allow you to continue until the potatoes are grown.

After you've done all of this, talk to Unferth again. He'll tell you that he's very ill and must see a doctor or a nurse. Talk to the [[Apothecary]] in [[Varrock]] (located in the south-west of the city). He will tell you that Unferth is a {{wp|hypochondria|hypochondriac}} - he thinks that he's sick all the time even though he really has been tested for illnesses and it's all in his head. You need to use a placebo on him - pick a [[doctor's hat]] or [[nurse hat]] from the Apothecary, and wear some white robes (princess robes and graceful outfit don't work).

Go back to Unferth's house, and give him a [[vial of water]]. His illness will clear up. '''Note:''' You can't be wielding a weapon/shield; otherwise, Unferth won't believe you.
"""

[[steps]]
index = 4
name = "Love-cats"
links = ["catspeak amulet", "Bob (cat)", "Neite", "magic carpet", "Sophanem", "King Black Dragon", "R4ng3rNo0b889", "Fishing Trawler", "Unferth", "present"]
text = """
Using your [[catspeak amulet]], find [[Bob (cat)|Bob]] again and talk to him. Log out and log in again if he is not in the same place as before, he will reappear. He may have moved to another of the other locations mentioned above, or he may be in the same location as before. You'll see a cutscene showing all the adventures Bob takes [[Neite]] on, including a [[magic carpet]] ride in [[Sophanem]], a conversation between Bob and the [[King Black Dragon]] (a player spoof known as [[R4ng3rNo0b889]] also tries to attack the dragon, but the dragon kills him instantly), and a journey on the [[Fishing Trawler]] ship.

After the cutscene, you will be teleported in front of [[Unferth]]'s house. Talk to him to get a [[present]] from Bob, finishing the quest.

'''Congratulations, quest complete!'''

{{Listen
|title = Bob's on Holiday
|desc = The music which plays during the adventures of Bob and Neite.
|filename = Bob's on Holiday.ogg
}}
<gallery captionalign="center" widths="150">
A Tail of Two Cats - Bob and Neite in Sophanem.png|Bob and Neite in Sophanem
A Tail of Two Cats - Bob talking to KBD.png|Bob talking to the King Black Dragon
A Tail of Two Cats - R4ng3rNo0b889 dying.png|R4ng3rno0b889 is killed by the King Black Dragon.
A Tail of Two Cats - Bob and Neite sailing.png|Bob and Neite sailing.
</gallery>
"""
