quest = "Holy Grail"
step_count = 7

[[steps]]
index = 0
name = "King Arthur and the Holy Grail"
links = ["King Arthur", "Camelot", "holy grail (item)", "Gielinor", "Merlin", "Camelot Castle", "Entrana", "Sir Galahad"]
text = """
[[File:King Arthur chathead.png|left]]
Speak to [[King Arthur]] in [[Camelot]], who mentions he is sending out knights on an important quest. Ask him about it, and he will say they have recently learned the [[holy grail (item)|holy grail]] has passed into [[Gielinor]]. He wants you to speak to [[Merlin]] who may know more about where to find it.

[[Merlin]] can be found on the {{FloorNumber|uk=1}} of [[Camelot Castle]], up the staircase in the main part of the castle in the south-east room (not the tower); he will appear once you enter. Merlin will suggest that the grail is likely to reside in a holy place like [[Entrana]], and that [[Sir Galahad]] previously quested for the grail and may know more.
{{Clear|left}}
"""

[[steps]]
index = 1
name = "The old crone's warning"
links = ["Port Sarim", "Monks of Entrana", "weapons", "armour", "High Priest (Entrana)", "Crone", "Fisher King", "Mysterious statue", "magic whistle"]
text = """
{{Needed|recommended=Fast travel to Galahad, Draynor Manor, and then Brimhaven for future sections. You will need your combat equipment before the Brimhaven step.}}
[[File:Crone chathead.png|left|frameless]]
Before speaking to Galahad, you must first visit Entrana. Head to [[Port Sarim]] and travel with the [[Monks of Entrana]], depositing any [[weapons]] or [[armour]] via the nearby bank deposit box, as the monks will not allow them on the island.

Speak to the [[High Priest (Entrana)|high priest]] of the church, who says that the grail passed through the island but is no longer here. A [[Crone|strange old crone]] will appear and say that a [[Fisher King]] is in trouble. To help him you must find where the six [[Mysterious statue|stone heads]] around the world point to and blow a [[magic whistle]] there, in order to enter his realm.
{{Clear|left}}
"""

[[steps]]
index = 2
name = "Galahad's holy table napkin"
links = ["Galahad", "McGrubor's Wood", "Camelot", "Fisher Realm", "holy table napkin", "Kandarin Diary", "Draynor Manor", "Fairy rings"]
text = """
[[File:Galahad chathead.png|left|frameless]]
{{Map|name=Galahad|x=2613|y=3477|r=4|mtype=square|caption=[[Galahad]]'s house west of [[McGrubor's Wood]]s and [[Camelot]].|width=220|height=220|align=right}}
Head to [[Galahad]], found in a house west of [[McGrubor's Wood]]. Tell him you're looking for an item from the [[Fisher Realm]], and he will reluctantly give you a [[holy table napkin]], a souvenir he took from the Fisher Realm.

'''Note:''' To complete a task in the easy [[Kandarin Diary]], ask him if he ever gets lonely, and he will give you a cup of tea.

With your napkin, head to the top floor of [[Draynor Manor]] and into the southern room. You will see a pair of magic whistles on the table. Pick up '''both''', one will be taken from you later. [[Fairy rings|Fairy ring]] {{Fairycode|BJR}} will become accessible later in the quest - if you plan to use it, you will only need one, though taking multiple is still useful in case of mistakes. More than two can be obtained by dropping the whistles outside the room, entering it again, grabbing the two new whistles that spawn, and picking the dropped ones back up.

'''Note''': The whistles have a despawn timer, but will respawn upon re-entering the room.
{{Clear|left}}
"""

[[steps]]
index = 3
name = "Passing into the Fisher Realm"
links = ["Excalibur", "magic whistle", "food", "anti-poison", "Combat", "Brimhaven", "North Brimhaven mine", "poisonous", "scorpions", "Combat level", "gold rocks", "Karamja Diary", "Fisher King's Realm"]
text = """
[[File:Magic whistle detail.png|left|60px]]
{{Needed|[[Excalibur]], [[magic whistle]], and combat equipment|recommended=[[food]], [[anti-poison]] if under level 41 [[Combat]], fast travel method to Camelot and Goblin Village for future sections, pickaxe for an easy Karamja Diary task ({{SCP|Mining|40}})|skills={{SCP|Attack|20}} {{Boostable|no}} to wield [[Excalibur]]}}{{Map|2742,3234|r=3|mtype=square|caption=The location to blow the magic whistle.|width=220|height=220|align=right}}
Head to [[Brimhaven]], ensuring you have your combat equipment with you. Go west of the town and then up the northern peninsula to the [[North Brimhaven mine|goldmine]], avoiding the [[poisonous]] [[scorpions]] if below [[Combat level]] 41. Look for a guard tower north of where the [[gold rocks]] are.

'''Note:''' To complete an easy [[Karamja Diary]] task, take the rope swing to the western island (with the Giants) and back.

'''Note:''' If you brought a pickaxe, you can complete an easy [[Karamja Diary]] task by mining a piece of gold here with {{SCP|Mining|40}}.

Go under the tower and blow one of the magic whistles, and you will be teleported to the [[Fisher King's Realm]].
"""

[[steps]]
index = 4
name = "Black Knight Titan"
links = ["Black Knight Titan", "Excalibur", "melee", "Magic", "Ranged", "flinching", "halberd", "Fisherman (Holy Grail)", "grail bell", "Grail Maiden", "Fisher King", "Percival"]
text = """
[[File:Black Knight Titan chathead.png|left|80px|frameless]]
[[File:Holy Grail - Fighting the Black Knight Titan.png|thumb|right|220px|Fighting the [[Black Knight Titan]].]]
The [[Black Knight Titan]] guards the bridge ahead, and you must defeat him before you may continue. You may deal damage to him with other weapons but the '''killing blow must be dealt with [[Excalibur]]''', otherwise he will heal to full health. Using [[melee]] to defeat him is '''highly recommended''', as he has +1000 defence against [[Magic]] and [[Ranged]].

As the Black Knight Titan will not move, it is extremely easy to defeat him through [[flinching]], by hitting him and moving back one square immediately, then waiting for his health bar to disappear before repeating. If you do take damage, his max hit is up to 15, so beware. Using a [[halberd]] will allow you to defeat him with [[melee]] from range with no chance of taking damage. '''Remember to switch back to Excalibur''' at around 10% hitpoints remaining to avoid accidentally healing him to full. At low levels the knight may take 15 minutes or more to kill due to its 142 hitpoints and high melee defence.

After killing the titan, cross the bridge and then head south along the river until you find a [[Fisherman (Holy Grail)|fisherman]]. Ask him how to get inside the castle, and he will tell you to ring the bell.

Head to the castle located south-west from the fisherman where you will find a [[grail bell]] on the ground in front of the entrance. Ring it and a [[Grail Maiden]] will invite you inside.

Head upstairs and speak to the [[Fisher King]]. Tell him you seek the grail, and he will reply that legend has it a questing knight will restore the Fisher Realm to its former glory and then claim the grail as their prize. Tell the Fisher King he doesn't look well, and he will tell you he fears his life is running short; he wants you to find his son [[Percival]], who is actually a Knight of the Round Table, and bring him to the castle.

{{Color|Red|Warning:}} Complete both dialogues before leaving, or you may have to return and kill the titan again!

Blow your whistle again to be teleported out, or teleport out through other means and return to Camelot.
"""

[[steps]]
index = 5
name = "Finding Percival"
links = ["Sir Percival", "magic whistle", "King Arthur", "Percival", "magic gold feather", "Goblin Village", "Falador", "Sacks (Holy Grail)", "Holy grail (item)"]
text = """
[[File:Holy Grail - Talking to Sir Percival.png|thumb|right|220px|Finding [[Sir Percival]].]]
{{Needed|Both [[magic whistle]]s.|recommended=Fast travel to the Fisher Realm and then Camelot, bring antipoison if not using fairy rings and under combat level 41}}
[[File:Sir Percival chathead.png|left|frameless]]
Speak to [[King Arthur]], who will recall [[Percival]] riding off on a quest to recover the golden boots of Arkaneeses a few months back. He will give you a [[magic gold feather]] which is said to point towards the location of the boots.

Blow on the feather, and it will guide you towards [[Goblin Village]], located north of [[Falador]]. Once at the Goblin Village, Open the [[Sacks (Holy Grail)|sacks]] in the east house (do not just prod), and you will find Sir Percival ('''you must have the feather in your inventory'''). Tell him that his father wishes to see him. Percival doesn't know how to get to the castle; if you have a magic whistle in your inventory, you will automatically give it to him when the conversation ends.

[[File:Holy Grail - Taking the Holy grail.png|thumb|left|220px|Take the [[Holy grail (item)|Holy grail]].]]
"""

[[steps]]
index = 6
name = "Retrieving the Holy Grail"
links = ["Black Knight Titan", "fairy ring", "Fisher King", "Holy grail (item)"]
text = """
Head back to the Fisher King's Realm like before (you don't need to fight the [[Black Knight Titan]] this time). You may now also teleport there using [[fairy ring]] {{Fairycode|BJR}}. Return to where the [[Fisher King]] previously was to find that Percival has become the new king.

Head back downstairs, go up the staircase on the east end of the castle, and continue up the ladder. Take the [[Holy grail (item)|holy grail]].

Return to King Arthur in Camelot and the player will inform him that the grail has been retrieved.

'''Congratulations, quest complete!'''
{{Clear}}
"""
