quest = "The Garden of Death"
step_count = 5

[[steps]]
index = 0
name = "Starting the quest"
links = ["Kebos Lowlands", "Shayziens' Wall", "Mount Quidamortem", "lizardmen", "lizardmen brute", "mountain troll", "Tent (The Garden of Death)", "Kasonde's journal", "Old Ones", "Varlamore", "Camping Equipment (The Garden of Death)", "secateurs", "Hole_(The_Garden_of_Death)"]
text = """
{{Map|zoom=0|mtype=pin|align=right|caption=Various locations the player visits during the quest. The blue pin indicates the quest start location.
|1313,3469,icon:bluePin,desc:Quest start
|1364,3637,desc:Molch Island|1314,3617,desc:Xeric's Shrine|1450,3511,desc:Ruins of Morra}}
To start the quest, head to the campsite located south of the lizardman settlement in the [[Kebos Lowlands]]. Fairy ring {{fairycode|BLS}} is the closest teleport.

Alternatively, players can head to the [[Shayziens' Wall]] and make their way south-west, or start from [[Mount Quidamortem]] and head south-east – in these cases, be wary of aggressive [[lizardmen]] and [[lizardmen brute]]s or [[mountain troll]]s.

Search the [[Tent (The Garden of Death)|tent]] to start the quest and receive [[Kasonde's journal]]. Read the journal, discovering about the [[Old Ones]], who were once an ancient race that inhabited what is today the Kingdom of [[Varlamore]], and suggests lizardmen architecture was derived from theirs. Search the [[Camping Equipment (The Garden of Death)|camping equipment]] for some [[secateurs]] if you don't already have some, and climb down the nearby [[Hole_(The_Garden_of_Death)|hole]].
"""

[[steps]]
index = 1
name = "A swampy dungeon"
links = ["Stone tablet (The Garden of Death)", "word translations", "wood carving", "dirty note", "Lake Molch", "secateurs", "fairy ring", "boaty", "Molch Island", "Shayzien", "Kharedst's memoirs", "Giant Pit"]
text = """
[[File:The Garden of Death - campsite dungeon searchable objects.png|thumb|350px|The locations of searchable objects in the dungeon south-east of Mount Quidamortem. Search the table labelled "1" to receive the stone tablet.]]
You will arrive in a dungeon with lizardmen architecture and a set of farming patches. Look around the stone tables until you see one with a "Search" option. This will give you your first [[Stone tablet (The Garden of Death)|stone tablet]]. Read it to discover that it is written in an ancient unknown language. Upon closing the interface, you will receive a set of incomplete [[word translations]] which you must uncover further in the quest.

The other stone tables should now have "Search" options; do so to receive two [[wood carving]]s. Inspect these to view detailed illustrations and words corresponding with them. One of the vases can be searched to receive a [[dirty note]]; this gives the players a hint on how to translate the carvings. Next, search the stone chest at the eastern end to learn the phrase 'Miki Toka'.

Once you believe you've figured out the meaning of the words, read the [[word translations]] again and click "Attempt Translation"; you will be prompted to enter a word's translation. As you translate the words, the stone tablet you read earlier will automatically update with the words you know of. Only one translation of each word is required to progress through the quest, but the stone tablets will not be fully readable until all are discovered. If the most contextually appropriate translation for a stone tablet's word has not been discovered, another will be substituted if available in blue lettering. Correctly translated words will be shown in green lettering.

Input the following words into the word translations:
* Island = Ikam
* Lake/Pond/Water = Ates
* Time/Death = Miki
* Vessel/Container/Holder = Toka
* Garden/Plant/Tree/Forest/Wood = Tlane
* North = Makt

You will be directed to somewhere north under an island. The only large island that currently can be travelled to is the one on [[Lake Molch]]. If you don't have a pair of [[secateurs]] on you, climb back up and search the camping equipment for one before leaving, as you'll need it for the next part.

Players can quickly get there by using [[fairy ring]] code {{Fairycode|DJR}} and running south-west to the eastern dock. From the dock, board the [[boaty]] to [[Molch Island]]. Alternatively, you can teleport to [[Shayzien]] via [[Kharedst's memoirs]] and run north-west to the east dock near the [[Giant Pit]].
"""

[[steps]]
index = 2
name = "Lake Molch Island"
links = ["Secateurs", "Magic secateurs", "Vines (The Garden of Death)", "Kasonde Shaw", "Stone tablet (The Garden of Death)", "wood carving", "Molch", "Xeric's Shrine"]
text = """
[[File:The Garden of Death - Lake Molch Island searchable objects.png|thumb|350px|The locations of searchable objects in the dungeon beneath Lake Molch Island. Search the table labelled "1" to receive the stone tablet.]]
{{Needed|[[Secateurs]] or [[Magic secateurs]]}}
Upon arriving at Molch Island, climb down the hole behind the hut to arrive at a similarly looking dungeon. Inspect the [[Vines (The Garden of Death)|vines]] for another dirty note, which suggests that [[Kasonde Shaw]] returned to his camp as you left.

Cut the vines and squeeze through them, and once again look around the stone tables for one with a "Search" option. This will give you your second [[Stone tablet (The Garden of Death)|stone tablet]]. Read it, and the other stone table behind you should now have a "Search" option, which will give you your third [[wood carving]]. On the eastern side of the room, search the vase for your fourth wood carving, as well as the other vase for the phrase 'Tlane Kualt' and the chest for the phrase 'Olkat'. Lastly, search the rubble by the farming patches below the platform for your fifth wood carving.

After inspecting the carvings, input the following words into the word translations:
* West = Silam
* Poison = Achi
* Animal/Creature = Ayak
* Body = Olkat
* Food/Eat/Feed = Kualt
* Earth/Land/Ground = Xali
* Air/Wind = Ehke
* Fire/Destroy/Break = Tepat

Once these words are translated, you will be prompted to read the stone tablet for your next steps. You will be directed somewhere west of the lake. Leave the dungeon, and board the boaty to travel to [[Molch]]. Upon arrival, make your way south-west to [[Xeric's Shrine]].
"""

[[steps]]
index = 3
name = "Xeric's Shrine"
links = ["Compass (The Garden of Death)", "Ruins of Morra", "Shayzien", "Shayziens' Wall", "Kharedst's memoirs"]
text = """
[[File:The Garden of Death - Xeric's Shrine searchable objects.png|thumb|350px|The locations of searchable objects in the dungeon beneath Kebos Swamp. Search the table labelled "1" to receive the stone tablet.]]
Upon arriving at Xeric's Shrine, climb down the hole at the eastern side of the shrine to arrive in the third dungeon. Search the south-eastern stone table for your third stone tablet, then search the open stone chest adjacent to it for a [[Compass (The Garden of Death)|compass]]. Inspect it to discover the word equivalents for the cardinal directions.

Next, search the vase just north, the other two stone tables, and the huge mushroom in the centre for the next four wood carvings. After inspecting the carvings, input the following words into the word translations:
* Build/Create/Make = Chua
* Yes/Success/Right/Correct = Kemo
* No/Failure/Wrong/Incorrect = Ami
* Move/Transfer/Deliver/Send = Lini
* Arrive/Here = Xita
* East = Takam
* South = Uitt

Once these words are translated, you will be prompted to read the stone tablet for your next steps. You will be directed to a structure somewhere in a forest south-east. The final location is the [[Ruins of Morra]]; players can leave the dungeon, board the boaty to travel to [[Shayzien]], and run south-east past the [[Shayziens' Wall]]. Alternatively, players can leave the dungeon and teleport to [[Shayzien]] via [[Kharedst's memoirs]] and run southwards.
"""

[[steps]]
index = 4
name = "Ruins of Morra"
links = ["Ruins of Morra", "warning note", "Kasonde Shaw", "Citizens of Arceuus"]
text = """
[[File:The Garden of Death - Ruins of Morra searchable objects.png|thumb|350px|The locations of searchable objects in the dungeon beneath the Ruins of Morra. Search the table labelled "1" to receive the stone tablet.]]
The last hole to enter is found in front of the large step pyramid in the [[Ruins of Morra]]. Search the southern stone table for the final stone tablet, and search the other stone tables, vase, stone chest, and rubble for the remaining wood carvings and dirty note.

After inspecting the carvings, input the following words into the word translations:
* Small/Few/Little = Amok
* Big/Many/Plenty/Lots = Siua
* Light/Sun = Ralo
* Dark/Moon = Rani
* Life/Soul = Tal
* Death/Time/Die/Kill = Miki
* Knowledge/Mind = Yoka
* Home = Antil

Once these words are translated, you will be prompted to read the stone tablet and to take a [[warning note]] that you spotted on the floor.

Read it to discover that [[Kasonde Shaw]] was several steps ahead of you and that you must have come to the same conclusion: that the Old Ones were the first ones to perform soul transference, rather than the [[Citizens of Arceuus]].

Congratulations, quest complete!
"""
