quest = "Sheep Herder"
step_count = 3

[[steps]]
index = 0
name = "A threat to public health and safety"
links = ["coins", "Councillor Halgrive", "East Ardougne", "Sick-looking sheep", "incinerator (Sheep Herder)", "Farmer Brumty", "plague suit", "Doctor Orbon", "sheep feed", "Prayer points", "altar", "Ardougne diary"]
text = """
{{Needed|100 [[coins]]}}
{{Map|x=2617|y=3299|r=3|mtype=square|align=right|caption=The quest's start point.|width=250|height=250}}

Speak to [[Councillor Halgrive]] located in [[East Ardougne]] in the graveyard directly south of the church.

He is concerned about [[Sick-looking sheep|plagued sheep]] located near East Ardougne that escaped from a local farm, causing a threat to the health and safety for the public. He is looking for someone to herd the sheep, kill them quickly and cleanly, and dispose the remains in a special [[incinerator (Sheep Herder)|incinerator]] set up by [[Farmer Brumty]].

Agree to help do the job. He will happily thank you and mention you need a [[plague suit]] while herding the sheep. He will tell you to pick up the plague suit from [[Doctor Orbon]] and hand you some poisoned [[sheep feed]].

Head inside the church and talk to Doctor Orbon. After explaining you need protective clothing to dispose the escaped infected sheep, he will sell his last suit for 100 [[coins]] so he can afford a replacement for himself. Agree to pay for the suit, and you should receive a plague jacket and plague trousers. Pray with missing [[Prayer points]] at the [[altar]] to complete an easy task in the [[Ardougne diary]].
"""

[[steps]]
index = 1
name = "Herding the sheep"
links = ["Plague jacket", "plague trousers", "East Ardougne", "plague suit", "cattleprod", "Warrior (Thieving)", "moss giant", "Fishing Guild"]
text = """
{{Needed|[[Plague jacket]], [[plague trousers]]}}
{{Map|align=right|mtype=pin|caption=Location of the sheep.
|2609,3389,title:Location of the yellow sheep,icon:yellowPin,desc:
|2620,3368,title:Location of the green sheep,icon:greenPin,desc:
|2608,3346,title:Location of the red sheep,icon:redPin,desc:
|2569,3383,title:Location of the blue sheep,icon:bluePin,desc:
}}
Head to the fenced in enclosure located north-west of the north bank in [[East Ardougne]]. With your [[plague suit]] equipped, enter the gate on the west side of the enclosure. Head towards the incinerator where you will find a [[cattleprod]] lying on the ground a few steps south of the incinerator. Pick it up.

Leave the fenced in enclosure using the west gate. You can begin to dispose of the sheep by equipping the cattleprod and using it to direct the sheep into the fenced in enclosure using the west gate. The sheep will be prodded in the direction of which you are facing. The sheep can return back to their initial locations if you wait too long to prod. '''You only need one of each colour (in any order)''', and you can finish one sheep at a time.

Note: You can have a friend join you and body block the sheep, preventing them from going farther than desired and also prevent them from going back to their original location.

*Red sheep are located north of the north bank in East Ardougne.
*Green sheep are north-east of the red sheep, directly north of a fenced in area with chopped and fallen trees.
*Blue sheep are located north-west of the fenced in enclosure with the incinerator, nearby a small camp with [[Warrior (Thieving)|warriors]]. Do not go too far, as there are also aggressive level 42 [[moss giant]]s nearby.
*Yellow sheep are located south of the [[Fishing Guild]].

Note: If a sheep goes '''''BAAAAA!''''' (uppercase letters), it will be prodded in the direction you direct them towards. If a sheep goes '''''Baa''''', it will return to its initial location. When directing them to the fenced in pen with the incinerator located, it is better to spam click the sheep so that it does not walk back. If the sheep gets stuck against a corner or wall, prod them again, this will cause them to move towards an open tile. Make sure you prod the sheep one last time to get it IN the pen when you are close.
[[File:Sheep Herder - Sheep.png|thumb|All four sheep in the pen.]]
"""

[[steps]]
index = 2
name = "Killing the plagued sheep"
links = ["Plague jacket", "plague trousers", "Sheep feed", "Councillor Halgrive", "coins"]
text = """
{{Needed|[[Plague jacket]], [[plague trousers]], [[Sheep feed|poisoned sheep food]]}}

Once you have directed them to the gate of the incinerator, the sheep will automatically go inside the gate. Use the [[Sheep feed|poisoned sheep food]] to kill each sheep. Collect their bones and use them on the incinerator to burn the remains.

Return to [[Councillor Halgrive]] and tell him you disposed of the four sheep. He will reimburse you the 100 [[coins]] you spent for the protective clothing in addition to 3,000 coins as recognition of your service.

'''Congratulations! Quest completed!'''
"""
